### ISSUE TITLE
Add sails CLI to documentation

### ISSUE THREAD

**Issue by ProLoser** [balderdashy/sails#1002]
It would be handy if you guys provided links in the docs like 'Help us improve this doc' that linked to a github patch so that it's easier for people to expand the documentation.

That said, there's no online documentation for sails (such as what sails console does). I had to search other issues to figure it out.

**Comment by jorgecasar** [comment]
Here is the [CLI documentation](https://github.com/balderdashy/sails-docs/tree/master/reference/cli)
