### ISSUE TITLE
Socket.io not working when called from 3rd party domain

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#1003]
Hi,

I want to connect to socket on

```
api.myproject.com
```

from

```
admin.myproject.com
```

I get following notice:

> warn: handshake error No cookie transmitted with socket.io connection.  Are you trying to access your Sails.js server via socket.io on a 3rd party domain?  If you're ok with losing users' session data, you can set `authorization: false` to disable cookie-checking.  Or you can send a JSONP request first from the client to the Sails.js server to get the cookie (be sure it's the same domain!!)

Then I set in config/socket.js

```
 authorization: false
```

As a result I get an error: http://pastebin.com/9AvhxAw9

> info: handshake authorized 36lItmixjZvvdqlVtJsg
> error: Error: No valid session available from this socket.

whats the problem? Sails socket pretends to work for 3rd party domains, but it does not work.

**Comment by elennaro** [comment]
I have the same problem: I have myhost.com for http and www.myhost.com for socket io.
Is there some solution or workaround?
