### ISSUE TITLE
Use Sails without the ORM?

### ISSUE THREAD

**Issue by flockonus** [balderdashy/sails#1004]
Hi Guys,

I am trying to get started on Sails, (REST + Websockets + assets specially) but I am not down with losing the power of Mongoose. Is there a simple way to just override Waterline with it?

Personally I think making an ORM is a diversion from Sails shiny points, i.e. people are never satisfied with it, diff DBs are naturally diff, there are good projects out there for interfacing DBs

<3 Sails

Cheers!

**Comment by austinmao** [comment]
FYI this is doable. See https://github.com/austinmao/sails-es6-mongoose-react-boilerplate. In particular, you can reference:

* https://github.com/austinmao/sails-es6-mongoose-react-boilerplate/blob/master/config/bootstrap.js

**Comment by nicolapalavecino** [comment]
You can follow [these](https://sailsjs.com/documentation/reference/waterline-orm/datastores/manager) instructions for having the mongo adapter and to call native mongo shell methods. This is very useful for complicated queries. Enjoy!
