### ISSUE TITLE
Sails new blah --template=swig doesn't produce a 'views' folder

### ISSUE THREAD

**Issue by ghost** [balderdashy/sails#1079]
When I `sails new blah --template=jade`, it produces the 'views' folder with some jade templates. By default, it does this with EJS too, however it doesn't seem to work with swig, mustache, or any of the other template engines.

**Comment by IranPhpMaster** [comment]
according to : http://sailsjs.org/#!/documentation/reference/cli/sailsnew.html
when you wanna chnage the view engine for scaffold generation you need the neccessary tools !

--template=[template language] Use a different template language than the default (e.g. jade). Requires that a views generator for that language (e.g. sails-generate-views-jade) be installed in your global node path (e.g. ~/node_modules/ works).

it mean for SWIG support we need necessary generator !!!!
