### ISSUE TITLE
Swagger #feature

### ISSUE THREAD

**Issue by klh** [balderdashy/sails#1094]
Add Swagger to AUTO document the API in any project:
https://developers.helloreverb.com/swagger/

It would go well with the overall Sails mentality.

sample in use here:
http://swagger.wordnik.com/#!/pet

**Comment by psi-4ward** [comment]
+1

**Comment by ptos79** [comment]
This email account is inactive

http://www.wavebreakmedia.com/stock-photo-video-footage-i-74/Contact-Us.html

**Comment by drmikecrowe** [comment]
+1

**Comment by ptos79** [comment]
This email account is inactive

http://www.wavebreakmedia.com/stock-photo-video-footage-i-74/Contact-Us.html

**Comment by medokin** [comment]
+1

**Comment by karantan** [comment]
+1
Any updates on this?

**Comment by ifig** [comment]
+1

**Comment by bostrom** [comment]
I don't fully understand the last comment from @mikermcneil about the `usage` section, nor the reason for closing this issue. I'd also really like to see some easy way to generate a swagger.json documenting the API of my Sails project, either via a dependency or out-of-the-box. Is anyone working on it at the moment or has it been completely swept under the rug?

**Comment by flipside** [comment]
+2

**Comment by leoliew** [comment]
+1

**Comment by fehguy** [comment]
We have a lot of interest to do this.  I'm happy to help contribute if someone wants to join me with some pointers on getting to the routes, etc inside of sails.

**Comment by tjwebb** [comment]
I've set up a repo based on `swagger-express`: https://github.com/tjwebb/swagger-sails. I'd love to get some help on it. Basically my plan would be to expose the underlying `express` object in sails to `swagger-express` and go from there. Maybe that's all it takes to get a decent first version up and running, and then we can get more detailed metadata from waterline and so forth. Sound good?

sails's express instance is `sails.hooks.http.app`

**Comment by joshuajabbour** [comment]
Just FYI, [swagger-express only works with Swagger 1.2](https://github.com/fliptoo/swagger-express/issues/23)...

**Comment by tjwebb** [comment]
Ah ok, looks like forking https://github.com/paulhill/swagger-n will be a better way to start then.

**Comment by fehguy** [comment]
This is the direction swagger for node has been going:

https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/nodejs

This uses the swagger specification (JSON format in this example) as the DSL that routes http requests to a controller.

It's relying on middleware from the [apigee-127 project](https://github.com/apigee-127/swagger-tools) by @whitlockjc.  I believe that with this--and the hooks into sails routing may be a killer combo.  I'll dig into the sails router shortly.

BTW the swagger-tools project works with both 1.2 and 2.0 specs, and is thoroughly tested.

**Comment by 285858315** [comment]
+1

**Comment by dinana** [comment]
@tjwebb @fehguy : What's the latest direction here and how can I help?

**Comment by ptos79** [comment]
This email account is inactive

http://www.wavebreakmedia.com/stock-photo-video-footage-i-74/Contact-Us.html

**Comment by tjwebb** [comment]
At this point we're looking for a team of community members to help out. It looks like there's a ton of interest here, we're just swamped at the moment. I think @renanvieira wants to help out too.

Do you guys want to fork https://github.com/tjwebb/sails-swagger and get started there? A basic API generator would be an awesome first step :)

**Comment by ifig** [comment]
I am going to take a look at it, I see swagger as a documentation tool more than an API generator, and that's where my focus will go.

**Comment by Cooker-Monster** [comment]
Hi !
Could be very smart indeed : very fast API code thanks to Sail and nice API browser thanks to Swagger ...
By the way, Swagger is going further than an Api doc tool and Sails generator from Swagger Specification 2.0 makes sense for me.
My 2 cents !

**Comment by ptos79** [comment]
This email account is inactive

http://www.wavebreakmedia.com/stock-photo-video-footage-i-74/Contact-Us.html

**Comment by Benew** [comment]
Yet another +1

**Comment by niktrix** [comment]
+1

**Comment by dlai0001** [comment]
:+1:  love to see swagger in Sails.

**Comment by whitlockjc** [comment]
I've just released [sway](https://github.com/apigee-127/sway), the API behind [swagger-tools](https://github.com/apigee-127/swagger-tools), and the plan is to create some sway-based middleware/plugins/integrations for Connect, Express, Hapi, Restify and Sails.  I'll update this issue as things progress.

**Comment by tjwebb** [comment]
Hey guys,

I built a swagger sails hook that generates a Swagger 2.0 document: https://github.com/tjwebb/sails-swagger

It's alpha-quality at this point, but it basically works.

**Comment by fehguy** [comment]
This is awesome, thank you!

**Comment by yz89** [comment]
@tjwebb  thank you!

**Comment by orhemi** [comment]
@tjwebb  Thanks for your work !
But, it's not working with sails v0.11.

There is any hope to see it working soon?

**Comment by tjwebb** [comment]
It currently only works on master, I hope to see the latest sails released
soon.

**Comment by arnthorsnaer** [comment]
Looking forward to trying out swagger-sails when sails.js 0.12 is released

**Comment by theo4u** [comment]
anyone here can check out this library i think it better solve the problem and open for contributions

https://github.com/theo4u/sails-hook-swagger-generator
