### ISSUE TITLE
swig view engine requires manual restart to see changes.

### ISSUE THREAD

**Issue by airtonix** [balderdashy/sails#1131]
If you use swig in your `config/views.js`: 

```
module.exports.views = {
  engine: 'jade',
  ...
}
```

Then changes to the view files won't cause sailsjs to use the changes unless you manually stop the sailsjs server `ctrl+c`, then restart it `sails lift`.

This is a shame, because swig templates provide far more utility than ejs templates and present less obstacles than jade (converting html files from less technically apt colleagues).

**Comment by mahdaen** [comment]
Me too. I must restart the server to see the changes. Even I've tried to use nodemon but still need to restart the server manually.

**Comment by akd3vs** [comment]
Is there a workaround?

**Comment by mahdaen** [comment]
I get it working by using **`forever -w start app.js`** and to enable livereload on development, I manually create **`grunt-watch`** task and only watch the **`./tmp`** folder to ensure browser is reloaded after sails finished running the grunt.

**Comment by akd3vs** [comment]
@mahdaen Nice, thank you.

**Comment by mahdaen** [comment]
@akd3vs you're welcome. :)
