### ISSUE TITLE
Reversible Routes... address D.R.Y.

### ISSUE THREAD

**Issue by airtonix** [balderdashy/sails#1133]
A bit of backstory (because from my experience, most NodeJS people aren't even aware this is a thing)

In django we have the concept of DRY, where we only define our routes once in the project or apps urls.py. There we give each route a regex pattern (defining some matches for kwargs and args), a name, a namespace and a controller to handle this matched route.

if for example I have a route like (using python code as an example): 

```
import stuff here(views, urls, patterns)

urlpatterns = patterns('', 
    url("^products/(?P<productID>\d+)/$", views.ProductDetailView.as_view(), name="product-detail"),
    url("^auth/google/$", views.SocialAuthRedirectView.as_view(), name="social-auth-google"),
    url("^login/$", views.LoginView.as_view(), name="auth-login"),
)
```

In a template if I want to generate an url in my controllers (django calls them views):

```
import stuff here(RedirectView, reverse)


class LoginView(RedirectView):
    def get_success_url(self, *args, **kwargs):
        return reverse("social-auth-google")
```

and in my templates (what you guys call views):

```
{% extends "base.html" %}

{% block content %}
  <a href='{% url "social-auth-google" %}'> login with google </a>
{% endblock %}
```

So ignoring that i'm using python here to illustrate a deficiency in most nodejs routing modules... (that of Don't Repeat Yourself), how would I achieve the above in sailsjs?

I'm really not keen on hardcoding urls in my templates or my js modules. it's really bad practice and makes my modules non-portable.

This stackoverflow thread talks about this issue and the apparent misunderstanding of the issue by most noders: 

http://stackoverflow.com/questions/10027574/express-js-reverse-url-route-django-style

it's obviously not part of ExpressJS core because someone had to make: 

https://github.com/web-napopa/node-reversable-router

**Comment by mikermcneil** [comment]
This will be a core part of Sails in v0.12:  https://github.com/balderdashy/sails/issues/3402
