### ISSUE TITLE
FEATURE_REQUEST: HTML CRUD scaffolds generator with html views

### ISSUE THREAD

**Issue by lmasforne** [balderdashy/sails#1146]
it is expected to add a  Scaffolding / Crud generator with html views , and generic code in controller's actions from Models definition ? 
It's very helpful when you want to develop quickly an application without a very specific interface ;) 
I know it represent lot of works but it's expected ?
Thanks for your answer.

**Comment by matt-cook** [comment]
should this be closed? seems like it's still an outstanding issue.

**Comment by psylo31** [comment]
Yes you can close the issue, thanks for your work.  ; )

**Comment by iiitmahesh** [comment]
@lmasforne 
do u any other solution. to generate  HTML+CRUD scaffolds generator with sails.
