### ISSUE TITLE
Feature Request: Dynamic Models at runtime!

### ISSUE THREAD

**Issue by ArdentZeal** [balderdashy/sails#1160]
Hello dear Sails-Community,

we are developing a prototype for a new application in our company. We would like to be able to implement Sailsjs for all its nice features in the final product. So basically we want to change from the MEAN Stack in the prototype app to the MEANS Stack in the production app.

While there are still some issues with Angular and Sails which are not perfect yet, there seems to be a workaround for most of them. Saddly there is one special requirement we would need, which seems to be nearly impossible at the moment.

The app is able to generate Database Schemata provided by the end-user "on-the-fly". Which means we need to be able to generate routing "on-the-fly" as well, which looks sth like this in the MEAN Stack.

``` js
var setupStaticRoutesForDynamicObject = function(dynamicObject) {

    removeRouteToAngular();
    var model_tol = dynamicObject.model.toLowerCase();

    app.get("/api/" + model_tol, RoutesDynamic.all(dynamicObject));
    app.get("/api/" + model_tol + "/:id", RoutesDynamic.show(dynamicObject));
    app.post("/api/" + model_tol, RoutesDynamic.create(dynamicObject));
    app.put("/api/"  + model_tol + "/:id", RoutesDynamic.update(dynamicObject));
    app.del("/api/"  + model_tol + "/:id", RoutesDynamic.del(dynamicObject));

    addRouteToAngular();
};
```

Is there a way this is already possible with Sailsjs and i am just too blind to see?

the second part ist the removeRouteToAngular(); and addRouteToAngular();. The angular app takes over routing, for anything but the dataapi and the index.html, so we need a catchAll block **at the end** to catch all routes not related to the dataapi and the index.html to be routed to angular. 

So at the moment we remove the catchAll Route from app.routes, add our dynamic Routes, and add the catchAll again at the end. 

Some guidance on handling this behaviour in Sailsjs would be much appreciated.

Thanks for this amazing framework.

**Comment by IranPhpMaster** [comment]
When you generate that model on-the-fly the other API part also work ?!
for example dynamically generate USER model, now what about USER controller ? USER REST API and ... ?!!

**Comment by otaviodecampos** [comment]
+1

**Comment by IranPhpMaster** [comment]
I find a solution! we generate a model by a template and copy to model path and then reload the ORM, it work for me ;)

**Comment by mateeyow** [comment]
@IranPhpMaster Can you elaborate on the `reload the ORM` part?

**Comment by AddoSolutions** [comment]
+1

**Comment by AddoSolutions** [comment]
This is a huge contingency for me on my application, does anybody have any idea as to how I can get this to work?

**Comment by AddoSolutions** [comment]
This is a huge contingency for me on my application, does anybody have any idea as to how I can get this to work? @IranPhpMaster could you please elaborate on your solution?

**Comment by IranPhpMaster** [comment]
@AddoSolutions :
this is my way. I make some template of controllers and models and during runtime , fill that template with real code and put in correct place.

beacuse we are at run time mode, we need to restart sails.js to know about new models and load the API and routes and other stuffs !!! for restarting sails.js I use this code  :

    reloadSailsJs : function(callback) {

      // Reload controller middleware
      sails.hooks.controllers.loadAndRegisterControllers(function() {

        sails.once('hook:orm:reloaded', function() {

          async.auto({
            flushRoute : function (callbackThis) {
              // Flush router
              sails.log.verbose('START :: sails flush router');
              sails.router.flush();
              sails.log.verbose('END :: sails flush router');
              callbackThis();
            },
            reloadBlueprintRoute: ['flushRoute', function (callbackThis, results) {
              // Reload blueprints
              sails.log.verbose('START :: sails reload blueprint');
              sails.hooks.blueprints.bindShadowRoutes();
              sails.log.verbose('END :: sails reload blueprint');
              callbackThis();
            }],
            reloadAppRoute: ['reloadBlueprintRoute', function (callbackThis, results) {
              // Reload app dynamic routes
              sails.log.verbose('START :: sails reload app dynamic routes');
              CoreService.App.Route.reload(callbackThis);
              sails.log.verbose('END :: sails reload app dynamic routes');
            }]
          },  callback);

        });

        // Reload ORM
        sails.emit('hook:orm:reload');

      });

**Comment by rh0dium** [comment]
+1

**Comment by ArunLaks** [comment]
@ArdentZeal I put your code in bootstrap.js but is giving error. Can you share some working example. Your Idea is great.

**Comment by simonmilz** [comment]
+1

**Comment by cburatto** [comment]
+1

**Comment by wongpratan** [comment]
+1

**Comment by mantir** [comment]
+1

**Comment by cburatto** [comment]
+1

**Comment by duyphuong13** [comment]
Hi everyone,
Does the code of @ali-pourzahmatkesh  could apply in  new SailsJs 1.0  ?

**Comment by avinashk2946** [comment]
How to switch to different data-store for a model in run-time dynamically?

**Comment by MattGarnettWelsh** [comment]
Sorry to comment on a closed issue, but I'm not sure this was actually ever implemented into Sails.

@ArdentZeal Did you ever get anywhere with this and get any sort of production ready code?
