### ISSUE TITLE
User friendly validation message defined in the model itself?

### ISSUE THREAD

**Issue by arvindcr** [balderdashy/sails#1173]
Why not let users define nice validation messages in the model itself, next to each validation, and keyed to say the field name - like is done in rails.

This could make it super easy to flash the messages and highlight the fields where validation failed in the UI. This should not require any further parsing and stuff like mongoose requires.

**Comment by torayeff** [comment]
@mikermcneil Was this feature added at the latest version? Currently having problems with validation errors.

**Comment by lykmapipo** [comment]
For sails v0.11.X you may use this [sails-hook-validation](https://github.com/lykmapipo/sails-hook-validation)

**Comment by mikermcneil** [comment]
@lykmapipo thanks for the link!

**Comment by Boycce** [comment]
Latest version `0.12.9` of sails doesn't seem to be working with sails-hook-validation.
