### ISSUE TITLE
Socket subscriptions send duplicate messages

### ISSUE THREAD

**Issue by ndhoule** [balderdashy/sails#1180]
Whenever clients subscribe to a collection, they get duplicate messages from the server's publish calls.

Using the stock `sails.io.js` to post data:

```
var socket = io.connect('http://localhost:1337')
// ...
socket.get('/api/v1/help');
socket.post('/api/v1/help', { text: "fdsafdsafdsafsa"});
```

Sails' `—verbose` logs when the above post call is made:

```
verbose: Routing message over socket:  {"url":"/api/v1/help","data":{"text":"fdsafdsafdsafsa"}}
verbose: websocket writing 4:::{"model":"help","verb":"create","data":{"uid":null,"state":null,"text":"fdsafdsafdsafsa","instructorFeedback":null,"instructorRating":null,"instructorOk":null,"studentFeedback":null,"studentRating":null,"stu
dentOk":null,"id":48,"createdAt":"2013-12-08T03:57:41.000Z","updatedAt":"2013-12-08T03:57:41.000Z"},"id":48}
verbose: websocket writing 4:::{"model":"help","verb":"create","data":{"uid":null,"state":null,"text":"fdsafdsafdsafsa","instructorFeedback":null,"instructorRating":null,"instructorOk":null,"studentFeedback":null,"studentRating":null,"stu
dentOk":null,"id":48,"createdAt":"2013-12-08T03:57:41.000Z","updatedAt":"2013-12-08T03:57:41.000Z"},"id":48}
verbose: Introduced model sails_c_help_48
verbose: sending data ack packet
verbose: websocket writing 6:::3+["{\"uid\":null,\"state\":null,\"text\":\"fdsafdsafdsafsa\",\"instructorFeedback\":null,\"instructorRating\":null,\"instructorOk\":null,\"studentFeedback\":null,\"studentRating\":null,\"studentOk\":null,\"
id\":48,\"createdAt\":\"2013-12-08T03:57:41.000Z\",\"updatedAt\":\"2013-12-08T03:57:41.000Z\"}"]
```

On the client side, I end up getting two incoming messages. I opened a second window and executed this:

```
socket.get('/api/v1/help');
```

But no matter which client I post from, all connected clients still get duplicate messages.

I tried tracing through the model's `publish` call (https://github.com/balderdashy/sails/blob/master/lib/hooks/pubsub/index.js#L133) just to make sure it wasn't being called twice, and that's not the case.

I had this behavior using the blueprint controllers, so I copied/overrode the `create` and `find` controllers, adding a few `console.log`s in to be notified whenever a user was subscribed. For some reason, each `get` subscribes the user twice. I checked the room's subscribers, however, and there were no duplicates. I also tried doing multiple `get`s for a given collection, and this didn't change the behavior--users always get two messages. Same thing happens with other operations--updates, deletes, etc.

Anyone else experiencing this behavior? Is it expected?

**Comment by matuuz** [comment]
this is happening to me too now... i can't understand why :(
