### ISSUE TITLE
Promises in Sails.js

### ISSUE THREAD

**Issue by ajbraus** [balderdashy/sails#1186]
I just started on Sails.js and besides associations the only other issue I've come up against that is a really pain is the "Pyramid of Doom" or "Callback Hell."

Is there any plan to integrate promises into Sails.js to avoid this?

I can imagine that a successful implementation of promises would create a very flat and delightful DSL.

**Comment by arthur5005** [comment]
Yay for Bluebird in Waterline!!

**Comment by mikermcneil** [comment]
btw re pluggable promises, here's where that happens in WL2 if you're interested in contributing: https://github.com/mikermcneil/waterline2/blob/master/standalone/Deferred/Deferred.js#L58

**Comment by AlexVentura** [comment]
Actually, what's the best way to implement Promises in Sails.JS v0.11.3 or v0.11.4?

**Comment by Crusader4Christ** [comment]
```return Model.findOne(pk).where(where).then(matchingRecord => {```
leads to "a promise was created in a handler but was not returned from it"
How to solve?
