### ISSUE TITLE
Warning in production env

### ISSUE THREAD

**Issue by jashsayani** [balderdashy/sails#1187]
The application worked fine in prod, but when I switched from EJS to Handlebars, I started getting the following error on sails lift (in prod):

Warning: connection.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

**Comment by gotmikhail** [comment]
Should I still get this warning if I have `session` `middleware` disabled altogether?

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here:
https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052

**Comment by mikermcneil** [comment]
Also, see sailsjs.org/documentation/concepts/deployment for more info on deploying to production.
