### ISSUE TITLE
What do you think of koa.js

### ISSUE THREAD

**Issue by ghost** [balderdashy/sails#1238]
It looks like they are moving from express to [koa.js](http://koajs.com/).
What do you guys think about it?

**Comment by internalfx** [comment]
Fast forward a year.....what are the teams thoughts now?

With io.js and node 0.12 landing, generators are readily available.

**Comment by kristianmandrup** [comment]
If/when someone in the community does a rewrite of Sails.js internals for use with Koa, almost everybody will follow... I think.

**Comment by kristianmandrup** [comment]
Should be easy to tweak Sails to support Koa instead:

mainly here?

https://github.com/balderdashy/sails/tree/master/lib/hooks/http


Such as:
https://github.com/balderdashy/sails/blob/master/lib/hooks/http/view.js
https://github.com/balderdashy/sails/blob/master/lib/hooks/http/index.js

Happy tweaking!

**Comment by silenceisgolden** [comment]
To bump this somewhat, the async/await pattern is very nice in koa@2. Some middleware changes would definitely need to happen, but I also think that it would be logically to make the core changes to switch.

**Comment by mikermcneil** [comment]
> Does this means, sailsjs will follow?

@silenceisgolden @internalfx @kristianmandrup see https://github.com/balderdashy/sails/issues/1684#issuecomment-169547093
