### ISSUE TITLE
Can't model.save() in Sails console (update: make callback optional in model.save)

### ISSUE THREAD

**Issue by OscarGodson** [balderdashy/sails#1242]
In Sails 0.9.3 I can't figure out what im doing wrong. As an example, if I try this:

```
Users.findOne({ username: 'test' }).done(function (err, user) { user.email = 'foo@foo.com'; user.save() })
```

I get this:

```
sails> Users.findOne({ username: 'test' }).done(function (err, user) { user.email = 'foo@foo.com'; user.save() })
undefined
sails>
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/model/index.js:140:9
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql.js:307:11
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:116:25
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:24:16
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql.js:294:13
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:139:25
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql.js:287:15
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:137:39
    at runner (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql.js:285:13)
    at iterate (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:131:13)
    at Object.async.eachSeries (/usr/local/l
```

That seems to be right... not sure what im doing wrong.

**Comment by 9me** [comment]
var Q = require('q');
Q(User.findOne().where({id: someId}))
.then(function(user) {
    // update user object
    user.foo = 'bar';
     // What about user.foo() and foo() takes time and save triggered before  completion of foo() ???
    user.save();
}).then(function(user) {
    res.send(200);
}).fail(function(err) {
    res.send(500);
});

**Comment by onetwopunch** [comment]
@9me and anyone else reading this, Waterline uses Bluebird as the stock promise library https://github.com/balderdashy/waterline#query-methods for good reason. Check out [this](https://github.com/petkaantonov/bluebird/issues/381). Probably a good idea to stick with the standard Promise library instead of casting to Q instead :)

**Comment by jfrumar** [comment]
Yup - that was an old Waterline issue that has now been solved.
