### ISSUE TITLE
Returning Data from Mongo Store and Casting to _proto_

### ISSUE THREAD

**Issue by crh3675** [balderdashy/sails#1269]
I am using Mongo for a data store.  When I return a user, it comes back as an obvious JSON object.  Which means, I lose all methods for that object.  

I an inquiring as to how I re-cast that object as a Model instance to get the methods back onto it. I have checked the Waterline docs but I am unsure as to how the SailsJS layer is protecting the underlying _proto_

Any help is appreciated.

**Comment by jifeon** [comment]
Hi guys, did someone create such a feature request? There is still nothing in docs about it.

**Comment by crh3675** [comment]
I would say that the documentation has a lot of growing to do. One of the wonderful things with NodeJS and SailsJS is the continuous and awesome support from the community.  One thing that always trumps me is the REST query abilities that can serve AJAX requests seamlessly.  Can we expose more granularity of those in the docs as well as things like this?
