### ISSUE TITLE
Routing subdomains

### ISSUE THREAD

**Issue by cliffordduke** [balderdashy/sails#1297]
I can't find anything on this topic so I figured I'd ask here.

Does Sails.JS routing support handling subdomains?  I have just started a project and it would make things much neater if I could have the entire site running on one instance of Sails instead of configuring many different Instances.

**Comment by dustinbolton** [comment]
Is there a best practice approach for routing subdomain routes since this?

**Comment by sgress454** [comment]
Nothing official.  Another way to do this (if you have a limited set of subdomains, rather than a wildcard subdomain) is using express's `vhost` module.  See http://stackoverflow.com/questions/25345423/node-js-express-with-vhost-conflict-with-sails-js-framework-app/25497976#25497976 for more info.  You'd modify that example slightly to just include one app, and point multiple vhosts to it.

**Comment by mukulsoftwap** [comment]
can i use vhost for this sub domain problem

**Comment by netlander** [comment]
@sgress454 the vhost example shown on stackoverflow doesn't work with recent sails versions, I've just spend a couple of days trying to get sails to play nice with vhost at no avail.
Currently thinking of giving up on sails and reverting back to express and building from that point on.

**Comment by sgress454** [comment]
@netlander Sorry to hear that. I can't think of any reason why this should be. I would make sure you're using Express 3, though, since that's what Sails uses under the hood.

**Comment by sgress454** [comment]
Actually, scratch my previous comment -- the version of Express you have installed shouldn't matter to the Sails apps that you include via `vhost`; it should only effect any vanilla _express_ apps that you also include.  I tried [the example from @migswd](https://github.com/migswd/express-sails-vhosts) with Sails v0.12.3 and it worked perfectly for me.

**Comment by netlander** [comment]
@sgress454 , Yes I've tried the example, don't remember what problems I've encountered but I did find issues with the setup. However, for now, I've moved a simpler express only setup. I might return to sails in future but it would probably be for a stand-alone sails app.

**Comment by drinchev** [comment]
@airtonix super nice approach. 

👍 

What I'm having trouble with these days is to reuse routes based on domain. e.g. :

```
{
    'GET /:username' : 'UserController.profile',
    'GET /' : 'UserController.profile',
    'GET /' : 'IndexController.home'
}

So far I haven't found a way to route agains a policy and if `req.profile` is defined to route the UserController, otherwise to route to `IndexController`.

**Comment by ram-you** [comment]
So, what is the best way for routing subdomains in a pure Sails application ?
