### ISSUE TITLE
how to connect with mysql exist database?

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#1331]
i use generate user
to create user controller/model.
and in config/adapters.js 

i made mysql the default adapter.

module.exports.adapters = {

  // If you leave the adapter config unspecified
  // in a model definition, 'default' will be used.
  'default' : 'mysql',

  // Persistent adapter for DEVELOPMENT ONLY
  // (data is preserved when the server shuts down)
  disk : {
    module : 'sails-disk'
  },

  // MySQL is the world's most popular relational database.
  // Learn more: http://en.wikipedia.org/wiki/MySQL
  mysql : {
    module : 'sails-mysql',
    host : 'localhost',
    user : 'pass',
    // Psst.. You can put your password in config/local.js instead
    // so you don't inadvertently push it up if you're using version control
    password : 'pass',
    database : 'pass',
    prefix : ''
  }
};

after defining user model.

i visit:

http://localhost:1337/user

i got the unexpected  

[]

instead of existing data from mysql.

how can i get the existing mysql data?

thanks.

**Comment by honnikery** [comment]
Added Connection Configuration 

Open /config/connections.js 

	module.exports.connections = {
mysql: {
    module    : 'sails-mysql',
    host      : 'localhost',
     user      : 'honnikery',
    password  : 'honnikery',
    database  : 'test'
      }
	
Go to  /config/models.js

module.exports.models = {

  connection: 'mysql',
  host: process.env.WATERLINE_ADAPTER_TESTS_HOST || 'localhost',
  port: process.env.WATERLINE_ADAPTER_TESTS_PORT || 3306,
  user: process.env.WATERLINE_ADAPTER_TESTS_USER || 'honnikery',
  password: process.env.WATERLINE_ADAPTER_TESTS_PASSWORD || 'honnikery',
  database: process.env.WATERLINE_ADAPTER_TESTS_DATABASE || 'test',
  pool: true,
  connectionLimit: 10,
  waitForConnections: true

more: http://oramysqldba.blogspot.in/2015/07/how-to-save-users-details-in-mysql.html
