### ISSUE TITLE
How to configure a custom static (flatFileServer) route?

### ISSUE THREAD

**Issue by kbsanders** [balderdashy/sails#1345]
I would like to expose a cache directory as a static route to serve up things like dynamically generated PDF reports, thumbnails, etc.

It is my understanding that anything I put under `/.tmp/public` will get wiped each time I lift the server. Also, I would like to avoid having an entire `/assets/cache` directory copied over each time I lift the server.

This cache directory would not be committed to the repository and the app would control the expiration and periodic purging of the files inside the directory.

After some trial and error I was able to achieve what I wanted but I'm just wondering if this is the best approach?

Here is what worked:

``` javascript

// /config/local.js module.exports

express: {
    customMiddleware: function(app) {

      // This will expose files under /.cache 
      // as /cache on the web server

      // Ugly, but avoids having another instance of express
      // installed in the app's modules. Is there a better way
      // to get to the express object?
      var express = require('sails/node_modules/express');

      // We're in the config dir now, so we have to back up
      // one directory to get to the app root      
      app.use('/cache', express.static(__dirname + '/../.cache'));
    }
  }
```

I'm also aware that `local.js` won't be committed to the repo which makes this configuration more difficult to maintain.

It would be preferred to just be able to do something like this in the routes configuration. Is something like this already in place?

``` javascript

// /config/routes.js

module.exports.routes = {
  '/cache': {
    'static': '/.cache'
  }
};

```

**Comment by stellanor** [comment]
Hi, I ran into this issue as well and I would like to encourage you to re-open this issue. Here's a legitimate use case for serving a static file with no extension:

iOS developers who wish to enable deep app linking (e.g. visiting https://www.example.com/foo will open the Foo view if you have the Example app installed) must serve a file named `apple-app-site-association` from the root of their site. Here's Apple's documentation on the matter: https://developer.apple.com/library/ios/documentation/Security/Reference/SharedWebCredentialsRef/

For now I am exploring using middleware or a controller as a workaround, but it would be really great if Sails supported this.

**Comment by albertpeiro** [comment]
I'd definitely like something like this. Would make sails more friendly to architect frontend + backend on it. Especially if you want to serve a separate frontend static app that's compiled separately from the main views.
