### ISSUE TITLE
How to run sails.js application on port 80 with example?

### ISSUE THREAD

**Issue by JigneshPansuriaDeveloper** [balderdashy/sails#1361]
I want to run sails.js application ny default to 80 not 1337.

My local url must be like this http://localhost not http:localhost:1337

**Comment by SpaceG** [comment]
Yeah, and yes, thanks man. D ! :)  Take Care ! :D

**Comment by mikedevita** [comment]
oh god men, so many email alerts, men. unsubscribe, men.

**Comment by abderrahmane8** [comment]
thanks ..am in love with sails

**Comment by dilagurung** [comment]
> I want to run sails.js application ny default to 80 not 1337.
> 
> My local url must be like this http://localhost not http:localhost:1337

Run with port as an option
sails console --port 1338

**Comment by robbiedh** [comment]
try this open config/env/production.js and scroll down, find //port 80 end then, uncomment it , work well for me
