### ISSUE TITLE
Feature Request: Named Routes

### ISSUE THREAD

**Issue by rjmoggach** [balderdashy/sails#1366]
It'd be great to have named routes ...

As an example in a view template you might have an ejs tag like the following:

```
<a href="<%- route('user-index') %>">User List</a>
```

Routes could have another attribute, say **name**? Here's a snippet for routes.js...

```
'get /users': {
  controller: 'user',
  action: 'index',
  name: 'user-index'
}
```

**Comment by scippio** [comment]
What is the status?
