### ISSUE TITLE
Expose target action in req object

### ISSUE THREAD

**Issue by marionebl** [balderdashy/sails#1372]
The `req.target` object was removed on the road to v0.10 ([discussed here](https://github.com/balderdashy/sails/pull/1219), commit [409f744](https://github.com/balderdashy/sails/commit/409f744dcccf03fe2e42f79504cd32fec9ab0fc7)) and replaced by `req.options`.

This is all nice looking at it from the hooks and configuration side, but the options object does not contain information about the target action (formerly `req.target.action`) the request will land on, e.g. 

``` javascript
{ detectedVerb: { verb: '', original: '/user/:id?', path: '/user/:id?' },
  actions: false,
  rest: true,
  shortcuts: false,
  prefix: '',
  pluralize: false,
  index: true,
  model: 'user' }
```

exposes not enough information to get the target action in a sane way.  That makes it really hard to write solid policies or views that need to know about the target action without mimicking a big part of the sails router logic (read: I was not able to find one). 

Now to what this boils down is the following proposal: Expose the target action in the request object again, e.g. like this:

``` javascript
{ detectedVerb: { verb: '', original: '/user/:id?', path: '/user/:id?' },
  target: { action: 'find', controller: 'user' },
  actions: false,
  rest: true,
  shortcuts: false,
  prefix: '',
  pluralize: false,
  index: true,
  model: 'user' }
```

Related SO question: [stackoverflow.com/../get-sails-request-target-from-policy-scope](http://stackoverflow.com/questions/21514822/get-sails-request-target-from-policy-scope)
 Related Google Groups posting: https://groups.google.com/forum/#!topic/sailsjs/faX54hqcNZE

**Comment by luqezman** [comment]
Some news about how to get action and controller? :'(

**Comment by RWOverdijk** [comment]
@luqezman `req.options.controller` and `req.options.action`

**Comment by luqezman** [comment]
@RWOverdijk this options is only available after "route" middleware run :'( Inside a hook using "after route" listener, is impossible to get it 👎

**Comment by RWOverdijk** [comment]
I'm not familiar with the after route listener, so I can't help.
