### ISSUE TITLE
dedupe issue

### ISSUE THREAD

**Issue by Karnith** [balderdashy/sails#1436]
Using npm dedupe causes a crash in app due to socket.io/node_modules/redis not being in sails node_modules folder, or so the error explains. The only way to fix this issue is to delete sails module and npm install it again after everything else is deduped.

OS: Windows 8 x64
Node: 0.10.26
Npm: 1.4.3

I have tried this with previous node versions with the same effect.

looking at sails / lib / hooks / sockets / loadSocketIO.js I see require being set 

/**
     \* Module dependencies.
     */

```
var     util            = require( 'sails-util'),
        SocketServer    = require('socket.io'),
        RedisStore      = require('socket.io/lib/stores/redis'),
        Redis           = require('socket.io/node_modules/redis'),
        Socket          = {
            authorization   : require('./authorization')(sails),
            connection      : require('./connection')(sails)
        };
```

require doesn't seem to be resolving to socket.io if it is installed in root node_modules folder of app.

**Comment by hwwan80** [comment]
Got the same issue for npm dedupe  for v0.11 because of the following code in lib/hooks/session/index.js because the node_modules/connect directory under express is removed after npm dedupe:

```
// (this dependency is only here for sails.session.generate()-
// which is really only here to enable socket lifecycle callbacks)
var ConnectSession = require('express/node_modules/connect').middleware.session.Session;
```

**Comment by hwwan80** [comment]
similar code occur in lib/hooks/csrf/index.js as well

**Comment by mdh-cc** [comment]
+1
