### ISSUE TITLE
If bootstrap does not finish within 2 seconds, log a warning

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#147]
The user probably forgot to call the callback function.

**Comment by GuillaumeLeclerc** [comment]
@loicsaintroch I can't find the file you are talking about. Maybe the file structure has changed since your comment. How is the new official way to remove this warning ?

Thank you

**Comment by scott-wyatt** [comment]
I don't think disabling the warning is a good idea. I would much prefer that the timeout be extended through a variable.  For instance with ORM hook and the PubSub hook their warning can be extended like so:
```js
// config/orm.js
module.exports.orm = {
  _hookTimeout: 60000 // I used 60 seconds as my new timeout
};

// config/pubsub.js
module.exports.pubsub = {
  _hookTimeout: 60000 // I used 60 seconds as my new timeout
};
``` 
I'd figure that the bootstrap warning would be a prime candidate for this methodology as well.

**Comment by virpool** [comment]
@GuillaumeLeclerc new file location is ``./lib/app/private/bootstrap.js``. At this moment you can increase timeout value ``sails.config.bootstrapTimeout``.

**Comment by GuillaumeLeclerc** [comment]
@scott-wyatt I agree. 
The problem in my case that I do (sometimes) heavy disk operations before during the bootstrap. The time depend on the hardware. I think in this case disabling it might be the best option.

Maybe setting the timeout to 0 to disable the warning is a good idea ?

**Comment by blah238** [comment]
I believe you can set this via `sails.config.bootstrapTimeout` nowadays.

**Comment by scott-wyatt** [comment]
@GuillaumeLeclerc I know putting heavy lifting in bootstrap is super tempting, I'm guilty of that as well.  Then I found that writing my own hooks is more modular, reusable, and more effective in my opinion.  It's a bit of a learning curve, but then you could add a specialized timeout to each of your hooks... that may solve your issue (and make it more testable). Just a thought.

**Comment by GuillaumeLeclerc** [comment]
@scott-wyatt It is not a production server (ie it is only started 1 or 2 hours a day). Hooks would be disabled when the server is down. That's why I need to check at start-up if something has changed. I don't think hooks would be a good idea here. But thank you :)
