### ISSUE TITLE
Command to drop all tables? and seed data perhaps?

### ISSUE THREAD

**Issue by mewben** [balderdashy/sails#1481]
Hi, Is there a command or code that drops all the table?
Or seed data to tables prior to sails lift?

**Comment by jossemarGT** [comment]
@mikermcneil I'll be glad to help you adding that db seeding approach to the [sails-docs](https://github.com/balderdashy/sails-docs/blob/master/reference/sails.config/sails.config.bootstrap.md), but, I'm afraid to ask is ok if I open a new issue just to check if someone else is interested in `sails --seed <options> && sails lift` cli-command/feature as well?

Regards :octocat:
