### ISSUE TITLE
BeforeUpdate doesn't contain ID

### ISSUE THREAD

**Issue by vavrecka** [balderdashy/sails#1503]
When I am trying to update record in BeforeUpdate method, I get the ID in the first parameter. But, when I override PUT method in my routes:

```
'put /v1/productlection/:id' : {
        controller : 'ProductLectionController',
        action : 'put'
    }
```

I get undefined here:

```
beforeUpdate: function (valuesToBeUpdated, cb) {
        console.log('values section');
        console.log(valuesToBeUpdated.id);  // this is undefined

        // ...

        cb();
    }
```

The BeforeUpdate is still triggered, and contain all the values which needs to be updated, but the ID is missing.

**Comment by Benew** [comment]
Hey guys I know this is old but I can't seem to find a way to get the object's PK before updating. Can you please help?
How can I access the `req` object in the lifecycle callback (`beforeUpdate`)? 
Is there no other way to get the object's `id`? Accessing `req` from the model clearly seems wrong.

**Comment by Benew** [comment]
OK as of sails 0.12.0-rc? the id is in the `value` argument. Thanks!
