### ISSUE TITLE
Model Inheritence

### ISSUE THREAD

**Issue by adhambadr** [balderdashy/sails#1504]
Hi Sails team, 

I have been looking into this for a while, on how to structure the Models in my Application  to inherit one another. The motive behind this is that a lot of DataStructures share common Fields, and children of these Structures use the common fields + implement their own new ones. 
I have been trying to integerate a Javascript inheritance library like Klassjs or similar but no avail. 
Id appreciate any blog post mentioning best practices in regards to this matter, should the Model be intact as possible and only match the Database attributes, and I should implement an application layer wrapper model around it on query, or should such a wrapper be implemented client side to decrease the model's size etc. I am very interested in hearing your take on this. 

regards.

**Comment by Crusader4Christ** [comment]
@mikermcneil I have the same issue: 3 types of users, all in one table - managers, affiliates and customers. Every user has a field `type` with value one of 'manager', 'affiliate' and 'customer'. It works well with associations to user with particular type, but not with associations with any user. Example: I need to create a log with user_id linked to any of user. Can I make 3 associations like this:
```
customers: {
collection: 'customer',
<here some join condition like ON user_id AND user_type='customers'>
```
