### ISSUE TITLE
`defaultLocale` option in `i18n.js` is not working , always use the `en` locale

### ISSUE THREAD

**Issue by lyfeyaj** [balderdashy/sails#1508]
I try to set `defaultLocale` as other languages, say `defaultLocale: 'de'`, but it is not working, unless I set the locale specially in controller as `res.setLocale('de')`, it will use the right locale.

**Comment by tojibon** [comment]
Here again!

In my case I am with sails v0.11.2
Seems it is also not loading default local anyway.

I had to solve it with policies again like.

Created: api/policies/lang.js with below codes
```
module.exports = function(req, res, next) {
    res.setLocale('fr');
    next();
}
```

Then updated: config/policies.js
```
'*': [..., 'lang'],
```

Thanks

**Comment by jeswinjames24** [comment]
How can i load the default route '/' to load with default locale in it

ex: '/' loads http://mywebsite/login

how can i make it to be http://mywebsite/en/login

**Comment by iwatakeshi** [comment]
@jeswinjames24 I'm not sure if i18n-node supports url parsing but if you are interested, you can give [sails-hook-gengojs](https://github.com/gengojs/sails-hook-gengojs) a try. You can turn on url parsing in the options under: 
`header: { detect: {/*...*/} }`. More info about gengo.js can be found at https://github.com/gengojs/gengojs.

Note: I am the author of gengo.js ;).
