### ISSUE TITLE
Support CoffeeScript classes as models and controllers

### ISSUE THREAD

**Issue by ghost** [balderdashy/sails#1544]
Sails _mostly_ supports CoffeeScript.  And that's great.  However, it doesn't support the use of CoffeeScript classes (which are just JS functions) as models or controllers.  Thus, it's not possible to easily implement one's own controller or model inheritance ([as suggested in this issue](https://github.com/balderdashy/sails/issues/1356)).  I recommend either reopening that task and providing a "Sails way" to do inheritance, or support CoffeeScript classes (JS constructor functions) to make it easy for developers to do it themselves, as you suggested.

No doubt there are technical hurdles to making this work.  But the power it provides developers in organizing their own code / implementing their own inheritance would be well worth it.

The following CoffeeScript works:

```
MyController =
    myMethod: (req, res) ->
        res.view()
```

The following CoffeeScript doesn't work:

```
class MyController
    @myMethod: (req, res) ->
        res.view()
```

At the end of the day, both controllers have the same method signature, but the latter doesn't currently work for whatever reason:

```
MyController.myMethod
```

**Comment by rkingon** [comment]
I just tried to use a coffeescript class as my controller and it worked just fine..

the op's example was missing the 'new' when calling the class.

```coffee
class CoffeeController
  
  index: (req, res) ->
    res.json success: true

module.exports = new CoffeeController
```

that being said, i really don't see any benefits in using a CS class.. It's not like you need multiple of the same controllers or to share variables across methods. It just creates a larger memory footprint (which is so small that it likely won't ever affect anything, but you get the point =p)
