### ISSUE TITLE
Updating records with associations using blueprints

### ISSUE THREAD

**Issue by npfitz** [balderdashy/sails#1573]
Currently, if I pull down a record from Sails, it will auto-populate with any associated objects, which has been great. However, I've run into some issues whenever I've modified that data and tried to save it back to the server. As it is right now, I need to ensure that I am removing all associated objects before I send it back to the server, which doesn't seem ideal.

Any thoughts on how this should be handled? My thought is that it should check for any association objects, and simply use their PK for the update, but I'm not sure that I have that kind of control inside of the update hook.

**Comment by sudhirjena** [comment]
@npfitz , @CWyrtzen - I do see the pull request for this issue merged with Waterline lib but I am facing the same issue with respect to One Way Associated models. E.g A **User** is associated with a **Role** but not vice-versa.

'GET /user/53' yields:
```
{
    "roleid": {
        "id": 9,
        "Role": "Admin",
        "Description": "Site Administrator"
    },
    "id": 53,
    "username": "some.user",
    "firstname": "Some",
    "lastname": "User",
    "email": "some.user@somewhere.com",
    "enabled": false
}
```
'PUT /user/53' with payload:
```
{
    "roleid": {
        "id": 9,
        "Role": "Admin",
        "Description": "Site Administrator"
    },
    "id": 53,
    "username": "someoneIKnowNow",
    "firstname": "Someone I Know",
    "lastname": "Now",
    "email": "someoneIKnowNow@somewhere.com",
    "enabled": true
}
```
does update the MySQL database but results in following error:
```
Details:  Error: ER_BAD_NULL_ERROR: Column 'roleid' cannot be null
```
