### ISSUE TITLE
Out of memory. nodejs using more than 100MB of RAM

### ISSUE THREAD

**Issue by pixelfreak** [balderdashy/sails#1577]
Is this normal? I've been running Node.js for a while now and only recently I have used sails. I ran 2 sails instances with sails-mysql, one for HTTP, another for HTTPS. Each of them starts at 75MB+ but quickly goes up to over 100MB and eventually crash due to out of memory :( (I have 512MB)

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here: https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
