### ISSUE TITLE
Object has no method 'done'

### ISSUE THREAD

**Issue by mt-bt** [balderdashy/sails#1607]
Hi,
I face a very strange issue since this afternoon. 
In a nutshell : 
1. I create a new project with all the code I need : everything works fine. I import this project into my svn server.
2. A friend checkout this project
3. He runs 'npm install' to get every dependencies
4. He lifts the server

The issue :
The server doesn't seem to recognize the method 'done' anymore and crash the first time there is a call to 'done' function.

 For example :`User.find(id).done(function(err, user){
//some code
})`

When I checkout the same project from the svn into another folder, after running npm install I have the same issue as my friend.

Here is the error message : 

```
/home/matthieu/Desktop/server/api/services/passport.js:20
  }).done(function (err, user) {
     ^
TypeError: Object [object Object] has no method 'done'
    at findByUsername (/home/matthieu/Desktop/server/api/services/passport.js:20:6)
    at /home/matthieu/Desktop/server/api/services/passport.js:58:7
    at process._tickDomainCallback (node.js:459:13)

```

Here is my package.json : 

```
{
  "name": "server",
  "private": true,
  "version": "0.0.0",
  "description": "a Sails application",
  "dependencies": {
    "rc": "~0.3.3",
    "include-all": "~0.1.3",
    "grunt": "0.4.2",
    "grunt-sync": "~0.0.4",
    "grunt-contrib-copy": "~0.4.1",
    "grunt-contrib-clean": "~0.4.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-sails-linker": "~0.9.5",
    "grunt-contrib-jst": "~0.5.0",
    "grunt-contrib-watch": "~0.4.4",
    "grunt-contrib-uglify": "~0.2.2",
    "grunt-contrib-cssmin": "~0.6.1",
    "grunt-contrib-less": "~0.9.0",
    "grunt-contrib-coffee": "~0.7.0",
    "sails": "0.10.0-rc4",
    "grunt": "0.4.1",
    "ejs": "0.8.4",
    "optimist": "0.3.4",
    "passport": "~0.1.16",
    "passport-local": "~0.1.6",
    "bcrypt": "~0.7.6",
    "connect-flash": "*",
    "jade": "*",
    "sails-mongo": "^0.10.0-rc2"
  },
  "scripts": {
    "start": "node app.js",
    "debug": "node debug app.js"
  },
  "main": "app.js",
  "repository": "",
  "author": "",
  "license": ""
}
```

**Comment by vishivish18** [comment]
Had the same issue while using passport, the problem is resolved by replacing done to exec, but can any one explain the reason please?

**Comment by animedbz16** [comment]
Additional information can be found in https://github.com/balderdashy/sails/issues/1617

This is fairly old and I believe the Q promises have all been replaced with Bluebird at this point, which did cause some other issues (#2278), but I believe those have been resolved.

**Comment by vishivish18** [comment]
thanks :)



*Regards,*

Vishal Ranjan | Software Developer


Specta®  <http://www.specta.in/>

*Mobile* : (+91) 750-389-7921 |*E-mail* : Vishal@specta.in


*"Because for productivity, health matters"*
