### ISSUE TITLE
Where is require('sails').express at?

### ISSUE THREAD

**Issue by laurynasra** [balderdashy/sails#1634]
Hello everyone,
it's more like a question, not an issue report. 

In my test env I am using supertest module which heavily relies on sails.express.app. After update to 0.10.x tests fails as express object can't be found on sails module. Maybe it was moved to another place?

Thanks!

**Comment by rhewitt22** [comment]
@Jaconil any idea why `sails.hooks.http.app` would be undefined?

https://stackoverflow.com/questions/31323962/cant-access-sails-app-in-integration-tests
