### ISSUE TITLE
Is it possible to search a model property via "contains" using REST blueprints?

### ISSUE THREAD

**Issue by Samstiles** [balderdashy/sails#1649]
Currently I can search as such:

`/person/find?name=Bob`

-- returns bob

`/person/find?age=36`

-- returns bob

`/person/find?description="This is Bobs entire description property"`

-- returns bob

But what if I wanted to search with a "like" or "contains" via the REST blueprints?

`/person/find?description="property"`

-- returns bob and any other person objects whose description contains the word "property".

Same goes for arrays, Bob has 3 relatives...

`relatives: ["Jane","Eric","Kim"]`

Is there a way to query via REST blueprints on a models array property? 

`/person/find?relatives=Kim`

-- would return any people (in this case Bob) whose `relatives` property (an array) has an array element that matches `Kim`.

**Comment by AlexanderKozhevin** [comment]
I didn't found a way to configure request on client side to search by object property.
LIke "about.rank": 500. 

It works on server side 

sails.models.hack.find({'about.rank': 600}).exec(function(err, found){
res.json(found)
})

But I can't figure out how to form url.
