### ISSUE TITLE
Better support for pagination

### ISSUE THREAD

**Issue by tarlepp** [balderdashy/sails#1653]
Now blueprints supports following reserved query parameters:

```
limit - the maximum number of records to send back-- useful for pagination.
skip - the number of records to skip-- useful for pagination. e.g. the following would return the second page of 30 results http://localhost:1337/pony?skip=30&limit=30
sort - the order in which to sort results, e.g. http://localhost:1337/pony?sort=name DESC or http://localhost:1337/pony?sort=createdAt ASC
```

It would be great if you add also support for `count` that will just return plain number of total records of asked endpoint.

Total count of records is needed for proper pagination to calculated how many pages there is with specified limit per page.

**Comment by shanelau** [comment]
@ArtworkAD 
In the file `route.js`,

I write this,

```
  'get /:model/count': {blueprint: 'count'},
``` 
It dose not work, the result is 404,
I need to specify parameter `model`.

Is there a better way to implement that  the `count ` route  is useful for every model ?

**Comment by tarlepp** [comment]
@shanelau I did make that bit different, add some "default" actions to each controller like this:

Controller:
https://github.com/tarlepp/angular-sailsjs-boilerplate/blob/master/backend%2Fapi%2Fcontrollers%2FBookController.js#L11

Base controller:
https://github.com/tarlepp/angular-sailsjs-boilerplate/blob/master/backend%2Fapi%2Fbase%2FController.js

With this way, no need to additional routes.

**Comment by shanelau** [comment]
@tarlepp Thank you ! This is a very good method.

**Comment by sylvainlap** [comment]
> @ArtworkAD @tarlepp You can also (as of v0.10) create custom blueprints, e.g. api/blueprints/count.js, which will be automatically merged in to the default blueprint actions

@mikermcneil I do not understand the route to use to get the count blueprint.
If I create a new route 'GET /count': { blueprint: 'count' }, what's the point to create a blueprint, and not add this action to a controller ?

**Comment by wfpaisa** [comment]
work

 UserController.js 

config/routes.js
``` 
'GET /user/count': { blueprint: 'count' },
``` 


api/blueprints/count.js
```javascript
module.exports = function count (req, res) {
  res.ok('ok')
}
``` 
---
if prefix in config/blueprints.js  ` prefix: '',`  no work

**Comment by elesdoar** [comment]
This not work if prefix is different that empty.
