### ISSUE TITLE
Session expires then receiving "warn: handshake error Connect encountered error parsing cookie!"

### ISSUE THREAD

**Issue by animedbz16** [balderdashy/sails#1663]
I have set up the sessions config as follows:
```
session: {
    secret: 'my secret',

    adapter: 'mongo',
    host: 'localhost',
    port: 27017,
    db: 'database',
    collection: 'sessions',

    cookie: {
      secure: true,
      maxAge: 900000, // 900,000 ms = 15 min
      expires: new Date(Date.now() + 900000) // 900,000 ms = 15 min
    }
}
```
Note: I am also ssl config since I set the cookie to secure: true
```
express: {
    serverOptions: {
      key: fs.readFileSync('ssl/ssl.key'),
      cert: fs.readFileSync('ssl/ssl.crt'),
    }
  }
```
Deleting the database and sails lifting, I can see from the mongo terminal the session collection has an index to expire documents where the session.expires value expires.

```
> db.sessions.getIndexSpecs();
[
        {
                "v" : 1,
                "key" : {
                        "_id" : 1
                },
                "ns" : "database.sessions",
                "name" : "_id_"
        },
        {
                "v" : 1,
                "key" : {
                        "expires" : 1
                },
                "ns" : "database.sessions",
                "name" : "expires_1",
                "expireAfterSeconds" : 0
        }
]
```

I access the http://localhost:1337/login, I can see a session is created in mongo now.
I log in and passport.js verifies my user account and adds my userID into the session.
I can see a local cookie is created in the browser with the expire date.

Upon accessing additional pages, I see that the session expire date in mongodb is updated, but the browser cookie does not appear to update. This seems like this should update automatically?

If I let the session time out, mongodb will purge the session document as per its expire index and now I try to access the server again, but receive the following message:
```
2014-05-07T13:28:34.462Z - warn: handshake error Connect encountered error parsing cookie!
TypeError: Cannot call method 'indexOf' of undefined
```
I would think that this happens because the cookie is still in the browser and attempts to find the session, but id doesn't exist so the warning occurs.

Is this something handled through sails or passport and how would I ensure that the browsers cookie is invalidated and/or a new session is required?

**Comment by CWyrtzen** [comment]
What is the status of this issue? Any updates or movement?

**Comment by sgress454** [comment]
@animedbz16 I can't reproduce this on the latest Sails--I'm not using passport, but with `session.js` set just like yours, both my Mongo session and my cookie have their expirations updated with each request.  It might be something with Passport sessions, but I can't say for sure.  If you continue to have this issue with the latest Sails code and you get any more info, please re-open.
