### ISSUE TITLE
Any example of how to work with socket.io?

### ISSUE THREAD

**Issue by elranu** [balderdashy/sails#167]
Hi,
Any example of how to develop with socket.io?  In the wiki pages only there are examples about how to work with EJS.

New with Sails... seems a nice framework

Regards,
Mariano

**Comment by stenio123** [comment]
If you are still interested, check out my blog - I'm writing a 4 part series on Socket.io with Sails.

http://impacta.us/sails-with-socket-io-part-14/

**Comment by tjwebb** [comment]
@stenio123 when you're done, let me know! We'd be happy to promote your tutorials in the docs
