### ISSUE TITLE
Cannot include font files in production mode

### ISSUE THREAD

**Issue by parnurzeal** [balderdashy/sails#1712]
I am using font-awesome and trying to run `sails lift --prod`. 
But the problem is normally I put all file structure as following:

```
styles
 |- font-awesome-4.0.3
     |- css
          |- font-awesome.min.css
     |- fonts
          |- .otf and .eot files
```

When running in production mode, it minimises all css into production.css file and put in `min` folder outside of styles but font-awesome css code itself still links to font source files as before (../fonts/_.etf, ../fonts/_.eof ).
So, it is not pointing to correct path. 

In this case, what should I do?

**Comment by elipeters** [comment]
A very old post but here is a link to grunt tasks [grunt tasks](https://sailsjs.com/documentation/concepts/assets/default-tasks), in particular **copy** and **cssmin**.

Move your fonts outside of the **styles** folder, re-link to your css and you're good to go.
