### ISSUE TITLE
Model update callback never triggered

### ISSUE THREAD

**Issue by Shepless** [balderdashy/sails#1713]
I am trying to update a model but the callback in the `exec()` is never fired:

``` js
console.log('----------------START----------------', existingModel.id);
MyModel.update({ id: existingModel.id }, modelUpdates).exec(function(e, updatedModel) {
      console.log('----------------FIN----------------', updatedModel.id);
      callback();
});
```

The above is essentially what I am doing, but `FIN` is never logged. Where am I going wrong? 

`modelUpdates` is an object containing values to update.
##### **_UPDATE**_

The records ARE being updated, but the callback just doesn't fire!

**Comment by chozzz** [comment]
+1 Have you figured out a solution yet?
