### ISSUE TITLE
Policies do not apply to views

### ISSUE THREAD

**Issue by dbkaplun** [balderdashy/sails#1737]
It seems like my policies are only being evaluated for my controllers. Is there a way to get Sails to evaluate policies for views as well?

**Comment by matthewarkin** [comment]
I think this is a bug too. I encountered it today. 

I was adding a policy to redirect everything to https that was in http and for the life of me, I couldn't get it working.

The code: 

    module.exports.policies = { '*': 'forcessl' }

seems like it should affect any endpoint a user can reach not simply controller actions.

**Comment by matthewarkin** [comment]
It looks like this was removed in https://github.com/balderdashy/sails/commit/7791bb12494e8932804bcf63e61864edfb33ffb4#diff-147c207980b31f4d1e891820f8df554a  :disappointed:

**Comment by sgress454** [comment]
Policies apply only to controllers, not views; this is [in the documentation](http://sailsjs.org/#/documentation/concepts/Policies?q=overview).

You can protect your views by:

1. Serving them from a controller action via `res.view` or,
2. If you're binding routes to them directly in `config/routes.js`, chain a policy before the view, e.g.:

```
"get /myView": [{policy: "myPolicy"}, {view: "someView"}]
```
