### ISSUE TITLE
Query date fields in GET requests

### ISSUE THREAD

**Issue by pixtron** [balderdashy/sails#1743]
Imagine a `Event` model with a field `startDate: {type: 'date'}`. 

If the blueprint route `find` is queried with a GET request `/events?where={"startDate":{">":"2014-05-24T00:00:00.000Z"}}`, i get an empty result set 
even if there are events with a `startDate` > 05/24/2014.

I assume the ISO date string should be casted to a `Date` object, 
as the query below works as expected.

```javascript
Event.find({ startDate: { '>': new Date('5/24/2014')} });
```

Tested on 0.10.0-rc7 and master at 4f9469edc9

**Comment by elementsinsured** [comment]
Any update on this issue? Would be great to be able to filter on date fields using the REST api...

**Comment by mkeremguc** [comment]
+1

**Comment by frankwong** [comment]
+1

**Comment by mwielbut** [comment]
I was able to resolve the issue by forking the sails-mongo module and making the following changes:

In sails-mongo/lib/query/index.js

Add the following lines to Query.prototype.parseValue

      if (self.schema[field].type === 'datetime') {
        return new Date(val);
      }

      if (self.schema[field].type === 'date') {
        return new Date(val);
      }


after


      if(self.schema[field].type === 'float'){
        return parseFloat(val);
      }

**Comment by frankwong** [comment]
@mwielbut that totally worked! Are you going to do a pull request on sails-mongo?

**Comment by mwielbut** [comment]
Looks like it was fixed before but then overwritten by another commit. Also, the previous commit only considered the 'date' type, not the 'datetime' type. Best to follow https://github.com/balderdashy/sails-mongo/issues/177

**Comment by loicsaintroch** [comment]
Thank you for the help guys, you rock!
