### ISSUE TITLE
Hidden folders from assets/ are not synced with .tmp/public/

### ISSUE THREAD

**Issue by lextiz** [balderdashy/sails#1764]
OS: Linux, Ubuntu 14.04
Sails: 0.10.0-rc7
grunt-sync will not sync folders starting with dot character in Linux. For instance after clean install of sails and putting sencha touch project into assets folder ".sencha" folder will not be accessible.

**Comment by johnabrams7** [comment]
See: https://github.com/balderdashy/sails/issues/4576
