### ISSUE TITLE
Would be great if SailsJS included full-fledged user support by default in new projects

### ISSUE THREAD

**Issue by dbkaplun** [balderdashy/sails#1772]
It seems like most SailsJS projects have the concept of a user, so it would be nice if it was easier to create an authentication layer.

There is the existing [sails-generate-auth](https://github.com/kasperisager/sails-generate-auth) which is great. However if this was integrated into SailsJS, I wouldn't have to maintain the auth code as a part of my project -- instead, the burden of maintenance would be shifted elsewhere.

This would also introduce the possibility of a Django-like admin tool.

**Comment by lykmapipo** [comment]
@secrettriangle Though this is closed try [sails-police](https://github.com/lykmapipo/sails-police)

**Comment by mikedevita** [comment]
whats the diff between waterlock and sails-police?
