### ISSUE TITLE
Getting criteria (e.g. ID) on Update in Lifecycle-Callback

### ISSUE THREAD

**Issue by mdunisch** [balderdashy/sails#1794]
How i can access the primary id in the livecyle-callback (on update)?

I have:

````javascript
beforeValidate: function (values, cb) {
    console.log(values._id);
    cb()
}
````

When i use the sails console:

     Anzeige.update({_id:'5384aae31af30e60170ad2ac'},{price:213}).exec(console.log)

i get a **undefined**.

----------
I try a workaround with: 

     Anzeige.update({_id:'5384aae31af30e60170ad2ac'},{price:213, _id:'5384aae31af30e60170ad2ac'}).exec(console.log)

and

````javascript
beforeValidate: function (values, cb) {
    console.log(values._id);
    delete values._id;
    cb()
}
````

So i can access the id - but i think thats not the best way.
If there is any good solution for getting primary key in Lifecycle-Callback before validation?

**Comment by jdcauley** [comment]
This issue has substantially aged, can anyone confirm an ongoing example and/or need to remain open.

**Comment by Benew** [comment]
+1

**Comment by nbkhope** [comment]
Has anyone found a workaround to obtain the record-to-be-updated's `id` in a lifecycle like `beforeUpdate`? If I do not include the record id in the request body (`valuesToBeUpdated`), then there's no way I can get the id.
