### ISSUE TITLE
How to pass in config to sails.io.js so socket.io connects to another port?

### ISSUE THREAD

**Issue by geertbrit** [balderdashy/sails#1803]
I have a client and server running on different ports: 
- client: 8080
- server: 1337

This leads to an expected **404** on : `http://localhost:8080/socket.io/1/?__sails_io_sdk_version=0.10.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1401903892072` 

Instead I want to configure `sails.io.js` so that  socket.io connects to `localhost:1337` instead. 

How to do this? 

The logical solution would be to pass a custom `io` parameter to `SailsIOClient(io)` but on line 817 of `sails.io.js` `SailsIOClient` is called without the option to pass in a custom `io`. See the below snippet: 

```
  // Otherwise, try to instantiate the client:
  // In case you're wrapping the socket.io client to prevent pollution of the
  // global namespace, you can replace the global `io` with your own `io` here:
  return SailsIOClient();
```

Now the comments seem to refer to the thing I want to do (pass in my own `io`) but, again, it's unclear to me how exactly to do this. 

Anyone?

**Comment by enuggetry** [comment]
This worked for me:  In sails.io.js, in the "io.sails" section, I added a "url: ..."
```
io.sails = {
   url: "http://<address>:1337",  // or localhost
.
.
.
```
In the version of sails I use, this is at around line 1350
This still doesn't feel quite right to have to modify this file.
Can anyone recommend something better?
