### ISSUE TITLE
Boolean filter /v1/model?enabled=1 not working

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#1818]
I try to request models by a boolean flag like

```
/v1/model?enabled=1
```

or

```
/v1/model?enabled=true
```

Both is not working. However things like

```
 /v1/model?city=FooBar
```

is working. How can we filter by boolean?

**Comment by shashankmeyar** [comment]
@jasonsims Is this issue fixed in latest version sails? 
Or do we still need the middleware mentioned above.
