### ISSUE TITLE
Using populate and where produces no results

### ISSUE THREAD

**Issue by WorldWideWebb** [balderdashy/sails#1846]
When I use both populate and a where, when the where includes a date equals query, I get no results. Example:

Doesn't work (produces no results and no errors):

```
Tasktime.find()
	.where({ date: taskDate })
	.populate('task')
	.exec(function(err, tasks){...
```

This works (gives me 2 results):

```
Tasktime.find()
	.where({ date: taskDate })
	//.populate('task')
	.exec(function(err, tasks){...
```

This also works, although it's not the query that I want:

```
Tasktime.find()
	.where({ date: {'>=' : taskDate} })
	.populate('task')
	.exec(function(err, tasks){...
```

**Comment by jdcauley** [comment]
@WorldWideWebb 

Your using a sql db correct?
Does the below query net results?

```
Tasktime.find({date: taskDate})
    .populate('task')
    .exec(function(err, tasks){
```

**Comment by jdcauley** [comment]
I'm closing this for no response.
