### ISSUE TITLE
Rest endpoints via `config.blueprints.rest = true` are 404s

### ISSUE THREAD

**Issue by clouddueling** [balderdashy/sails#1851]
v. 0.10.0-rc8
http://api.539df678d6bb0d065b000032.boweryapps.com

GET /api/users?      
- UserController.index
- Lists all users.

GET /api/users/:id
- UserController.find
- 404

POST /api/users
- UserController.create
- Lists all users.

PUT /api/users/:id
- BoatController.update
- 404

DELETE /api/users/:id
- BoatController.destroy
- 404

/config/blueprints.js

``` javascript
module.exports.blueprints = {
  actions: false,
  rest: true,
  shortcuts: false,
  prefix: '/api',
  pluralize: true
};
```

/api/controllers/UserController.js

``` javascript
module.exports = {

  // GET List objects
  index: function(req, res) {
    res.send("List all users.");
  },

  // POST Create object
  create: function(req, res) {
        res.send("Create a user.");
  },

  // GET Find object
  find: function(req, res) {
    res.send("Get user: " + req.params.id);
  },

  // PUT Update object
  update: function(req, res) {
        res.send("Update user: " + req.params.id);
  },

  // DELETE Delete object
  destroy: function(req, res) {
    res.send("Delete user: " + req.params.id);
  }

};
```

Temporarily I am relying on shortcuts to make this work but is not ideal.
Could you rely on https://github.com/visionmedia/express-resource to do this part?  I'd hate to see you have to maintain another piece that is already written tested for something kinda simple.

**Comment by sylvainlap** [comment]
I have the same problem...
