### ISSUE TITLE
How to support multi tenant application?

### ISSUE THREAD

**Issue by kesavkolla** [balderdashy/sails#1857]
I'm starting a new project with sails.js.  My application is a web application which is catered for multiple tenants.  Can anyone provide me some pointers on how to setup sails for multiple tenants?  I'm using Postgresql as my backend with one schema per tenant.  Also planning to use Redis for session storage and each tenant with it's own prefix.

How sails.js can help in configuring redis and postgresql for this?

Thanks in advance.

**Comment by Glavin001** [comment]
I have submitted a Pull Request to Waterline: https://github.com/balderdashy/waterline/pull/787

I will be also submitting a Pull Request to Sails to update Blueprints to support Multi-Tenancy.
