### ISSUE TITLE
Cannot re-lift sails after lowering it in tests

### ISSUE THREAD

**Issue by blah238** [balderdashy/sails#1860]
I am trying to create some tests for a Sails 0.10.0-rc8 app and as long as I only lift the server once it works fine. As soon as I lift the server a second time (after calling lower of course), I get an error:

```
/media/sf_vm-share/sails-test-app/node_modules/sails/lib/hooks/http/middleware/defaults.js:27
        maxAge: sails.config.cache.maxAge
                                  ^
TypeError: Cannot read property 'maxAge' of undefined
    at _.defaults.www (/media/sf_vm-share/sails-test-app/node_modules/sails/lib/hooks/http/middleware/defaults.js:27:35)
    at module.exports (/media/sf_vm-share/sails-test-app/node_modules/sails/lib/hooks/http/middleware/defaults.js:36:7)
    at loadExpress (/media/sf_vm-share/sails-test-app/node_modules/sails/lib/hooks/http/initialize.js:103:61)
    at Hook.initialize (/media/sf_vm-share/sails-test-app/node_modules/sails/lib/hooks/http/index.js:167:11)
    at Hook.bound [as initialize] (/media/sf_vm-share/sails-test-app/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /media/sf_vm-share/sails-test-app/node_modules/sails/lib/hooks/index.js:124:33
    at /media/sf_vm-share/sails-test-app/node_modules/sails/node_modules/async/lib/async.js:425:17
    at /media/sf_vm-share/sails-test-app/node_modules/sails/node_modules/async/lib/async.js:419:17
    at Array.forEach (native)
    at _each (/media/sf_vm-share/sails-test-app/node_modules/sails/node_modules/async/lib/async.js:32:24)
    at Object.taskComplete (/media/sf_vm-share/sails-test-app/node_modules/sails/node_modules/async/lib/async.js:418:13)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

The tests look like this:

``` js
var Sails = require('sails'),
  request = require('supertest'),
  assert = require('assert');

describe('some tests that need to lift sails', function (done) {
  // Lift Sails before the tests
  beforeEach(function (done) {
    Sails.lift({
      log: {
        level: 'error'
      },
      hooks: {
        grunt: false,
      }
    }, done);
  });

  // Lower Sails after the tests
  afterEach(function (done) {
    sails.lower(done);
  });

  it('should redirect the user to the user page if registration succeeded', function (done) {
    request(sails.hooks.http.app)
      .post('/register')
      .send({
        // Pass in a valid username/password
        username: 'user',
        password: 'pass'
      })
      .expect('Location', '/user')
      .expect(302, done);
  });

  it('should redirect the user to the registration page if registration failed', function (done) {
    request(sails.hooks.http.app)
      .post('/register')
      .send({
        // Pass in an invalid username/password
        username: '',
        password: ''
      })
      .expect('Location', '/register')
      .expect(302, done);
  });
});
```

Is there something else I need to do in order for this to work?

**Comment by jonny2779** [comment]
This is how I got it to work in  Jasmine.

```
var Sails = require('sails'),
  sails;

beforeEach(function(done) {
  Sails.lift({
    // configuration for testing purposes
  }, function(err, server) {
    sails = server;
    if (err) return done(err);
    // here you can load fixtures, etc.
    done(err, sails);
  });
});

afterEach(function(done) {
  // here you can clear fixtures, etc.
  sails.lower(done);
});


describe('User', function () {
  it('should not store your real password', function (done) {
    expect(true).toBe(true);

    User.create({firstName: 'jon', lastName: 'odonnell', email: 'jon@test.com', password: 'foobar888'}).exec(function (user) {
      console.log(user);
      console.log('here');
      done();
    });
  });
});
```

**Comment by g2graman** [comment]
I'm getting a similar result with Sails v 0.10.5. In the root of my test folder I have the following code in afile called 'bootstrap.test.js':

     var Sails = require('sails');
     var server;

    module.exports = {
        lift: function (done) {
            Sails.lift({
                environment: 'development',
                port: 9999,
                globals: {
                    sails: true,
                    models: true
                },
                log: {
                  level: 'error'
                },
                adapters: {
                  memory: {
                    adapter: 'sails-memory'
                  }
                },
                session: {
                    secret: 'ed3279f6619f7f4ed36f043ac0681768',

                    adapter: 'memory',
                    cookie: {
                      maxAge: 900000,
                      expires: null,
                      path: '/',
                      _expires: null,
                      originalMaxAge: null,
                      httpOnly: true
                    },
                    ssl: false
                },
                config:{
                    cache: {
                        maxAge: 900000
                    }
                },

                http: {
                    cache: 31557600000
                }
            }, function(err, sails) {
                if(err) return done(err);
                server = sails;
                this.server = server;
                return done();
            });
        },

        lower: function (done) {
            return sailsprocess.lower(done);
        },

        server: server,
        sails: Sails
    };

and invoke it in my unit tests with global hooks:

    var bootstrap = require('../../bootstrap.test.js');

    before(function (done) {
      this.timeout(5000);
      console.log(bootstrap);
      bootstrap.lift(done);
    });

    after(function (done) {
      console.log(bootstrap);
      bootstrap.lower(done);
    });

And yet, no matter how many settings I try to fiddle with, I seem unable to avoid:

    1)  "before all" hook:
     Uncaught TypeError: Cannot read property 'maxAge' of undefined

Any help would be much appreciated!
