### ISSUE TITLE
Model attribute Validation Rules: weird behavior for `int` and `integer` 

### ISSUE THREAD

**Issue by tsterker** [balderdashy/sails#1861]
Disclaimer:
>
I'm well aware that this might be a waterline issue, but I have only tested this behavior by setting attributes in my Sails models that have those validation rules attached to them.

I've encountered some weird behavior with the `int` and `integer` validation rules, which presumably should behave the same.

In Anchor (see [rules.js#L67-L68](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js#L67-L68)), the same validation rules seem to be used for both:
    
    ....
    'int'        :  validator.isInt,
    'integer'	 :  validator.isInt,
    ....

So one would assume it should have the exact same behavior. But here are some validation results (non-exhaustive list):

`int` rejects everything that is not clearly an int and stores it as `string`

     1      VALID     =>   '1'     
     1.0    VALID     =>   '1'     
    '1.0'   INVALID
     1.1    INVALID
    '4/2'   INVALID

`integer` is very liberal in what an integer is, even floors values and then stores them as 'number`

     1      VALID     =>   1     
     1.0    VALID     =>   1     
    '1.0'   VALID     =>   1
     1.1    VALID     =>   1
    '4/2'   VALID     =>   4

I am currently too busy to shed more light on this but I thought it might be useful to at least document my observations.

**Comment by sgress454** [comment]
This was an odd one, and might have had to do with [anchor](/balderdashy/anchor) treating "int" and "integer" differently, but since a) that's [definitely not the case now](https://github.com/balderdashy/anchor/blob/master/lib/match/rules.js#L70-L71) and b) only "integer" is referenced in the Sails and Waterline docs, not "int", I think we can lay this to rest.
