### ISSUE TITLE
socket.io connection through nginx

### ISSUE THREAD

**Issue by brunomacf** [balderdashy/sails#1868]
I set a nginx server to serve my static angular site and want to use sails to provide a rest api to deal with a mongo database. I set a prefix of /api to the sails server blueprints and set nginx proxy like this:

```
location /api/ {
                proxy_pass   http://localhost:1337;

                # the following is required for WebSockets
                proxy_redirect                off;
                proxy_set_header              Host             $host;
                proxy_set_header              Port             $server_port;
                proxy_set_header              X-Real-IP        $remote_addr;
                proxy_set_header              X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header              X-NginX-Proxy    true;
                proxy_pass_request_headers    on;
        }
```

the nginx server is set to http://localhost:10018 and in my client angular site i create a socket.io connection like this:

```
var socket = io.connect('http://localhost:10018', {
    path: '/api/socket.io'
});
```

The problem is that handshake is not performed and i'm getting a 404 response from the server with socket.io!!!! Is that a problem with the nginx? Or with my sails config? 

PS.: I'm using sails 0.10, nginx 1.4.7 and socket.io 1.0.

**Comment by luislobo** [comment]
just to complete @brunomacf nginx config, for socket to work in nginx, you need the config mentioned:

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

and also you need to add this to nginx.conf:

        ##
        # Virtual Host Configs
        ##
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }

Check https://www.nginx.com/blog/websocket-nginx/ for more info
