### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by maksymshtyria** [balderdashy/sails#1880]
We have some sails application which have been deployed on DigitalOcean. Sometimes we are checking with newrelic how it is working. 
After we have started load tests on our app we have found out that our app has memory leaks. For example we have created test where 2000 users are trying to get static pages about 2000 times. After perform this operation memory have grew a lot.

My questions is - have you checked sails on memory leaks? Maybe you know how we can find them (in node js) or probably places where you think them can be.

Thx.

**Comment by kaduev13** [comment]
Well, I have sails.js application, and have found that it has some memory leak. I'm using pm2 monit command for testing application memory usage. My application using postgresql as database back-end and redis as sessions store. I try to open static page (default sails homepage), and each time I have opened it, used memory size increased by 80-90 KB. Of course it is production environment. Any ideas?

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here:
https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
