### ISSUE TITLE
toJSON / v 0.10

### ISSUE THREAD

**Issue by mbdwey** [balderdashy/sails#1885]
Hello ,

i need to delete attribute from returned object i try to use toJSON but it dons't work

Users.findOneByUser_email(req.param('email')).exec(function (err, user)
{
    // user with password
}

toJSON: function ()
{
    var obj = this.toObject();
    delete obj.user_password;
    return obj;
}

info:    Sails
info:    v0.10.0-rc7

**Comment by albertpeiro** [comment]
@mikermcneil Where the documentation has gone for this? any light appreciated.
Seems broken:
http://sailsjs.org/#/documentation/concepts/ORM/Models.html?q=attribute-methods-(ie-record%2Finstance-methods)

**Comment by masumeEbhami** [comment]
dear albertpeiro
the right link is
http://sailsjs.org/#!/documentation/concepts/ORM/Attributes.html
the better way is go to sailsjs.org and select your page :-)
