### ISSUE TITLE
i18n fails silently on invalid JSON

### ISSUE THREAD

**Issue by tsterker** [balderdashy/sails#1908]
I just spent quite some time figuring out why I got the following error when trying to access i18n in my views or controllers:
`Cannot read property 'Error.Passport.Username.Missing' of undefined`

As it turned out, I had a trailing comma in my `config/locales/en.json`.

When I run my app with
`DEBUG=i18n:warn node app.js`

I actually get a somewhat meaningful warning:

```
i18n:warn WARN: No locale found - check the context of the call to __(). Using en as current locale +13s
i18n:warn WARN: Locale en couldn't be read - check the context of the call to $__. Using en (default) as current locale +0ms
```

Wouldn't it be useful to show these warnings, at least in verbose mode?

**Comment by susuhahnml** [comment]
I had that issue and solved it by removing a space in the string of the translation. 
From:
	"duplicates": " Tiene valores duplicados",
To:
	"duplicates": "Tiene valores duplicados",
