### ISSUE TITLE
+feature: sails new {app} --coffee

### ISSUE THREAD

**Issue by xpepermint** [balderdashy/sails#1923]
Hi. Sails is getting sexy! I'm slowly switching from Ruby on Rails to Sails but I really miss the default support for `coffescript`. I believe that writing Sails apps using `coffeescript` would add some extra push in productivity/code-readability/convention and would convince many modern developers who love `beautiful code` to use Sails.

``` ruby
sails new {app} --coffee
```

**Comment by ebourmalo** [comment]
I'm also interested. I just started working on it by speaking with @mikermcneil and @konstantinzolotarev :) I keep you updated

**Comment by ebourmalo** [comment]
And here is the PR: https://github.com/balderdashy/sails-generate-backend/pull/27 :)
cc @mikermcneil @konstantinzolotarev
