### ISSUE TITLE
Using database field "id" as attribute and association key in models

### ISSUE THREAD

**Issue by edoardocavazza** [balderdashy/sails#1924]
Hi,

I have noticed that if I have a model defined in this way:
<pre>
module.exports = {
  migrate: 'safe',
  tableName: 'objects',
  autoPK: false,
  attributes: {
        id: {type: 'INTEGER', primaryKey: true},
        ...   
        // Associations
        content: {
            model: 'contentModel',
            columnName: 'id'
        }
    }
};
</pre>
and I exec a find(), my objects are returned with the id field empty. If I not define an association, the field is filled right.

Is this a correct behaviour or an issue?
(ps: I am using the mysql adapter)

Thank you guys for your great work! ;-)

**Comment by particlebanana** [comment]
This belongs in Waterline but still not sure what is going on here. You are saying the `id` field is the primary key but it is also a foreign key for other records in the same db table?

If you open an issue in WL and post an example of the data being stored we can take a look and categorize as a bug or feature.
