### ISSUE TITLE
Policy doesn't protected blueprint action with custom route option

### ISSUE THREAD

**Issue by clarkorz** [balderdashy/sails#1932]
$ sails generate new sails-rc8
    $ sails generate api user

    // edit config/policies.js
    module.exports.policies = {
	  '*': false
	}

     // edit config/routes.js
    module.exports.routes = {
	  'GET /user': { model: 'user', blueprint: 'find', populate: false }
	}

    $sails lift
    $ curl http://127.0.0.1:1337/user

### Expect

Response 403 Forbidden

### Actual

Response 200

**Comment by loicsaintroch** [comment]
I close this issue in favor of your PR. Thank you for your contribution @clarkorz, we appreciate. I'll take a look at the PR as soon as I have more time, sorry for the delay.
