### ISSUE TITLE
warning: Recursive process.nextTick detected

### ISSUE THREAD

**Issue by dottodot** [balderdashy/sails#1944]
I've recent updated all my modules and I now get the following errors.

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
error: Grunt :: 
error: Grunt :: node.js:0
error: Grunt :: // Copyright Joyent, Inc. and other Node contributors.
^
error: Grunt :: RangeError: Maximum call stack size exceeded
```

**Comment by dottodot** [comment]
For anyone else with this issue adding `ulimit -n 10000` to your .bashrc will resolve the problem.

**Comment by mikermcneil** [comment]
@dottodot yup exactly right-- seen this a couple of times too.  Upgrading to newer versions of grunt deps  in your local project yields a slightly better error message at least, but certainly doesn't solve the problem.  (I _think_ it was either `grunt` or `grunt-contrib-watch` that caused the change in my experimenta couple of months ago).  I believe this is related to an issue in grunt where filesystem opens need to be queued.  The only good workaround I've been able to come up with is just setting a higher ulimit  (note if you're on a newer version of Mac OS X, you can no longer set ulimit that high-- you have to use e.g. `ulimit -n 1024`).

@RWOverdijk @dottodot I think it would be a good idea to put something together in the grunt hook that sniffs this message out from the grunt child proc, and if detected, provides a better error message w/ some troubleshooting tips.  If there's interest there, if someone wouldn't mind creating a pull request to ROADMAP.md that adds this as a new row in the **Backlog** table, that'll give us a clean slate to spec out how that would work (should be a pretty simple one).  Thanks!
