### ISSUE TITLE
Turn off grunt in production

### ISSUE THREAD

**Issue by prateekbhatt** [balderdashy/sails#1945]
I have a large angular js app, and the build process in production takes a long time because of the `uglify` step. Is there a way to first build the app, commit it, and then skip the grunt build process in production env ? (Something like _locking_ the production build)

**Comment by marcusnielsen** [comment]
I think this should be reopened since it does not work in `config/env/production.js` as @edy wrote. The `if`-statement workaround feels like a hack. Inlining configuration makes it impossible to find for other developers.

**Comment by samlroberts** [comment]
I agree with @marcusnielsen. The ability to set more of these things in `config/env` would be better than it `if`-statement workaround. Right now I have a `.sailsrc` file different in my test and production branches than my local, because i wanted turn off grunt hooks and set a custom path for assets, but it would be great to be able to add those configs to `config/env/production` instead of `app.js`. 

Is this a possible change?

**Comment by crobinson42** [comment]
:+1: +1 for edy's feature/enhancement request @mikermcneil 

> config/env/production.js is a good place for this too, but hooks config doesn't apply from there.
```
module.exports = {
    hooks: {
        grunt: false // doesn't work
    },
    log: {
        level: 'silly' // doesn't work
    },
    port: 12345 // works
};
```

**Comment by sgress454** [comment]
Beginning with the next patch release of Sails, you should be able to turn off hooks via environment vars, e.g.:

```
sails_hooks__grunt=false NODE_ENV=production sails lift
```

In the meantime, check out [this comment](https://github.com/balderdashy/sails/issues/3577#issuecomment-184786535) about turning off Grunt tasks in production.

**Comment by TemaSM** [comment]
:+1: +1 for crobinson42's idea
How about cmd line argument switch(--no-grunt) for disabling grunt at specific launch?
For example I have automatic deployment system (which clones repo from GitHub & sends it to production server) and configured load balancer using **Nginx:**
```bash
upstream sails {
    ip_hash;                    # WebSockets support
    server localhost:2001;      # Instance 1
    server localhost:2002;      # Instance  2
    server localhost:2003;      # Instance  3
}
```
For zero downtime while upgrading code from git, I launching Sails app like this (ssh queue after repo was cloned locally to server):
```bash
pm2 delete app-2001 -f && echo = 1 INSTANCE DELETED
pm2 start app.js --name app-2001 -x -f -- --prod --port=2001 && sleep 15 && echo = 1 INSTANCE RELOAED AND LIFTED ON 2001 PORT
pm2 delete app-2002 -f && echo = 2 INSTANCE DELETED
pm2 start app.js --name app-2002 -x -f -- --prod --port=2002 && sleep 15 && echo = 2 INSTANCE RELOAED AND LIFTED ON 2002 PORT
pm2 delete app-2003 -f && echo = 3 INSTANCE DELETED
pm2 start app.js --name app-2003 -x -f -- --prod --port=2003 && sleep 00 && echo = 3 INSTANCE RELOAED AND LIFTED ON 2003 PORT
```
But while some of instances starting after code upgrading, it does grunt tasks & removing `.tmp` dir, and when user refreshing a page, instance №2(for example) successfully processed request (while №1 still lifting and doing grunt tasks), but no assets loaded, cause `.tmp` dir temporary removed or doesn't contain all/any minified files for production.

**Please, pay attention for this feature/enhancement request - it's very important for real production needs.**
 THANKS :wink:
