### ISSUE TITLE
Sails lift takes long with large amount of models in database (mysql)

### ISSUE THREAD

**Issue by jrderuiter** [balderdashy/sails#1953]
I am currently trying to set up an application using Sails.js in which I need to store a rather large amount of data in the database. At this time I have two rather large tables (a gene table with 39.026 rows and a transcript table with approximately 95.000 rows) and expect to add two larger tables (exons and a transcript - exon join table). 

Loading the data into the database using sails-mysql seems to go fine, however I find that with every increase of the amount of data 'sails lift' takes considerably longer, now taking longer than a minute to start up (instead of a few seconds, as would normally be the case). 

Any idea on why this is happening? Is there anything we can do to remedy this? 

I noticed that the slowdown is also happening in some code that uses Waterline directly (without sails). Is this maybe something that should be fixed in Waterline?

Gene.js: 

``` javascript
module.exports = {

  attributes: {

    stableId:    { type: 'string', required: true },
    name:        { type: 'string', required: true },
    biotype:     { type: 'string', required: true },
    description: { type: 'text',   defaultsTo: '' },

    chromosome: { type: 'string',  required: true },
    start:      { type: 'integer', required: true },
    end:        { type: 'integer', required: true },
    strand:     { type: 'string',  required: true },

    transcripts: {
      collection: 'transcript',
      via: 'gene'
    },

    canonicalTranscript: {
      model: 'transcript'
    }

  }
};
```

Transcript.js:

``` javascript
module.exports = {

  attributes: {

    stableId:    { type: 'string',  required: true },
    name:        { type: 'string',  required: true },
    biotype:     { type: 'string',  required: true },

    chromosome: { type: 'string',  required: true },
    start:      { type: 'integer', required: true },
    end:        { type: 'integer', required: true },
    strand:     { type: 'string',  required: true },

    gene: { model: 'Gene' },

    exons: {
      collection: 'exon',
      via: 'transcripts',
      dominant: true
    }

  }
};
```

**Comment by pigerla** [comment]
It helps me a lot , thanks
