### ISSUE TITLE
0.10.0-rc8 - req.host === undefined, req.headers['host'] === undefined

### ISSUE THREAD

**Issue by fabdrol** [balderdashy/sails#1958]
Bug? 
`req.host` and `req.headers['host']` return "undefined" when used in a policy.

**Comment by sgress454** [comment]
Confirmed that `req.host` and `req.headers.host` work as expected over HTTP.  With sockets, the only header sent by default is the cookie.  Anything else you want you'll need to send along yourself.  If you're using the sails.io.js client, you can use the `io.socket.request` method:

```
io.socket.request({
  method: "get",
  url: "/user",
  headers: {
    "host": window.location.host
  }
}, cb);
```
