### ISSUE TITLE
Sails 0.10.10-rc8 / mongo session: receives incoming connection before connect-mongo is connected

### ISSUE THREAD

**Issue by fabdrol** [balderdashy/sails#1959]
I'm getting this error - but only sometimes: it occurs when I have a page open in the browser (which uses sockets) or if I navigate to that page too early. It seems to be caused by connect-mongo receiving an incoming session connection before connect-mongo has managed to connect to the database. See [this question on SO](http://stackoverflow.com/questions/22698661/mongodb-error-setting-ttl-index-on-collection-sessions)

```
node_modules/connect-mongo/lib/connect-mongo.js:161
                throw new Error('Error setting TTL index on collection : ' + s
```

**Comment by mikermcneil** [comment]
@fabdrol ok looks like we just need a quick rebase, let's continue discussion in the PR: https://github.com/balderdashy/sails/pull/2407  

thanks again!
