### ISSUE TITLE
Assets cached on production despite having file changes.

### ISSUE THREAD

**Issue by codebykenny** [balderdashy/sails#2002]
Is there a way to make it so browsers force reloading of asset files such as Javascript and CSS files upon there being changes? 

Particularly referring to production.css/js

**Comment by sochka** [comment]
How did you actually make use of cache initially? For me nothing is cached in browser, even though server returns 304 code - there still is a round-trip request.

**Comment by gavinbunney** [comment]
@sochka a `304` will always make a round-trip request as it is validating that the content hasn't been modified.

In our app instance, we _also_ have middleware that adds cache headers to various requests (depending on what is being requested, cache headers are different), something along the lines of:

```
var limit = 60 * 60 * 24 * 1000; /* one day */
res.header('Cache-Control', 'public, max-age='+ (limit / 1000));
res.header('Expires', new Date(Date.now() + limit).toUTCString());
```

**Comment by sochka** [comment]
@gavinbunney thanks, I've made it work using `express.static` and `maxAge` option.
