### ISSUE TITLE
JSON response/payload

### ISSUE THREAD

**Issue by crobinson42** [balderdashy/sails#2022]
Is there an adapter/serializer available to conform to http://jsonapi.org

**Comment by CWyrtzen** [comment]
This will come up in search results open or closed--does it still need discussion? Does the problem persist in v0.11?

**Comment by leejt489** [comment]
I think it should probably be an enhancement.  Nothing is broken, but I am still an advocate for making the response format easier to tweak.  There are solutions like https://github.com/mphasize/sails-ember-blueprints.

**Comment by IanVS** [comment]
[JSON API](jsonapi.org) was recently tagged at 1.0, and I would love to make a 100% JSON API 1.0 compliant Sails.js backend.  @mphasize has expressed a desire to implement in https://github.com/mphasize/sails-generate-ember-blueprints, but so far it's not there yet.
