### ISSUE TITLE
How to log socket requests?

### ISSUE THREAD

**Issue by tarlepp** [balderdashy/sails#2032]
In `config/http.js` is example of request logger:

```
myRequestLogger: function (req, res, next) {
    console.log("Requested :: ", req.method, req.url);

    return next();
}
```

But this won't catch any socket request? What is the proper way to log socket requests?

**Comment by mikermcneil** [comment]
see https://github.com/balderdashy/sails-hook-dev/commit/7ba63f27d87de25ee6dc8fdba099d193ac3e66e8 re @tarlepp and my conversation in IRC
