### ISSUE TITLE
Blueprints routes not working if Controller inside a folder

### ISSUE THREAD

**Issue by adrianocola** [balderdashy/sails#2064]
If I have a Controller inside a folder (like api/controllers/test/FooController.js) and a model (like api/models/Foo.js) all blueprint routes return a 404 error for calls like http://localhost:1337/test/foo

If I my Controller to the root controllers folder (api/controllers/FooController.js) all blueprint routes starts to work ( accessing http://localhost:1337/foo).

I've tested this with sails 0.10.1 and with a new project generated with the sails CLI.

**Comment by Enethion** [comment]
I found another problem with that.
I've tested it for my new project, and when my structure reach that point:
```
  models/
    test/dir/model.js //with identity: "test/dir/model"
    test2/dir/modej.js //with identity: "test2/dir/model"
    model.js // no changes in identity
```
In my `sails.model` only existing were `model` and `"test2/dir/model"`. Is there any chance to fix it? I need something like `vendor/package` structure.
