### ISSUE TITLE
error not specific!

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#2065]
I got an error on database query.
but the error message is too limited to find the exact reason.
please also give the full database query, when database error occur.

the following is the error message
```
Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' alias = , password = 'e10adc3949ba59abbe56e057f20f883e', introduce = null, crea' at line 1
```

**Comment by sgress454** [comment]
I was never able to reliably reproduce this with the code provided.  Happy to look into it some more if more info comes to light.
