### ISSUE TITLE
Cannot populate associations after updating to 0.10.2

### ISSUE THREAD

**Issue by mateeyow** [balderdashy/sails#2076]
I'm trying to populate associations between mongo and mysql. When I last installed sails it was version 0.10.0-rc9 and I can populate between two databases just fine. But, after upgrading to the current version (0.10.2) it is giving me this error: `Details:  TypeError: Cannot call method '_getPK' of undefined`

**Comment by wayne-o** [comment]
I am getting this in 0.10.14 - was this fix confirmed?

**Comment by wayne-o** [comment]
Upgrading to sails-mongo@beta fixed this - weird
