### ISSUE TITLE
Firefox 'no element found' on res.end()

### ISSUE THREAD

**Issue by gulakov** [balderdashy/sails#2087]
http://stackoverflow.com/questions/975929/firefox-error-no-element-found
According to this the fix is to add header('Content-Type: text/plain'); before exiting in php

sails js should specify a header content type in the res.end() function. 

This occurs on any route call that has return res.end() in Firefox

**Comment by sgress454** [comment]
This doesn't really sound like a Sails problem.  If the issue is that Firefox has problems with empty responses, and you are sending an empty response, and you don't want to offend Firefox, you can put add that header call to your controller action yourself.  Unless I'm missing something?
