### ISSUE TITLE
Feature propose: Crontab in Sails

### ISSUE THREAD

**Issue by mdunisch** [balderdashy/sails#2092]
In an App I developed a few months ago I needed frequently database-cleaning. For that I implemented **node-cron** (https://github.com/ncb000gt/node-cron) in my app and now I ask me if this a functionality can be helpful in the Sails-core.
### Add node-cron to Sails core

With node-cron you can use cron-syntax (like `0 */30 11 * * 1-5`) to run functions in nodejs. node-cron haven't any dependencies.

We can implement this into Sails and adding a **cron.js** in the `config`-folder. A simple implementation could look for example:

``` js
// cron.js
module.exports = {

         // Every day at 02:30
         "0 30 2 * * *": function cleandb(){
                mymodel.destroy({last_activity: { "<": 2} }).exec(sails.log.error);
         },

         // Every 5 minutes
         "0 */5 * * * *": function checksomething(){
                ....
         }
}
```

What you think about that?

**Comment by lethalgit** [comment]
I've tried using the hook example explained by @tommy31 , the path to hook i provided looks something like this - /api/hook/hook1/cronScript.js. While restarting the sails engine by "sails lift", i encounter these errors-
1. Malformed hook! (hook1)
2. Hooks should be a function with one argument (`sails`)
Since i've never tried cron related service before, i'm unable to figure out how to resolve these errors.
Help me. Thanks.

**Comment by farandal** [comment]
There is a hook that seems to work pretty well: 
github.com/ghaiklor/sails-hook-cron

**Comment by scott-wyatt** [comment]
Here's something that I've found while making larger sails applications.  Not all Cron Jobs are global and not all Cron jobs are local. For a global example, if you have a server cluster and you have a Cron Job that sends out emails you wouldn't want each sails app in the cluster each sending out the email list, you would want them to work together. For a local example, if you have a server cluster and your app requires some sort of file purge, it doesn't make sense for only one app instance in the cluster to purge just itself.  
How I now implement this is using two things: `cron-cluster` and `humpback-redis-event`.  Cron cluster allows clusters to work together globally, and then if there is a local need for a cron, which ever app in the cluster picks up the cron requests issues a humpback-redis-event to all the other servers in the cluster to perform their local task.
Hopes this idea helps someone else out there.

**Comment by wladiston** [comment]
+1
I had a similar problem using the AWS elasticbeanstalk. I simple job to send an email was sending six instead... @scott-wyatt gave a good idea.

**Comment by arthursp** [comment]
It will be interesting to cronify route directly.
