### ISSUE TITLE
Sails not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by gorgekara** [balderdashy/sails#2120]
Sails seems not to be working on the newest LTS version of Ubuntu - 14.04.
When running 'which sails' in command line nothing is returned.

Searched for sails in the /usr/bin folder and sails is not there (not sure if it should be listed here but wanted to mention this).

Also did a global system search for the term 'sails' and these are the results:

```
./usr/lib/node_modules/sails
./home/gjorge/.npm/sails
./home/gjorge/.npm/registry.npmjs.org/sails
```

---

This seems to be working:

```
/usr/lib/node_modules/sails/bin/sails.js new projectName
```

Any ideas on how can I make a sails command to point there?

**Comment by gauravdhiman** [comment]
Rather than add in in .bashrc, you can create a soft link using ln -s command.

I am also facing this same issue on 14.04. For me even '/use/lib/node_modules/sails/.bin/sails.is new test' is also not working. Its throughing error.

**Comment by Tandzone** [comment]
If it can still helps someone I found this that worked for me

Not really sure why, but uninstalling node and following the guide on the sails.js site worked...
sudo apt-get install python-software-properties python g++ make
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs
sudo npm -g install sails

**Comment by jaswinderwadali** [comment]
ubuntu 16.+

alias sails="~/.npm-global/lib/node_modules/sails/bin/sails.js"
