### ISSUE TITLE
MongoDB (sails-mongo) remote connection authorization fails - Sailsjs v0.10.4

### ISSUE THREAD

**Issue by derekbasch** [balderdashy/sails#2123]
## Environment:
- Sailsjs 0.10.4
- Win 7
- MongoHQ
- MongoLab
## Configuration:

`local.js` :

Empty/Commented Out

`connections.js`:

```
  someMongodbServer: {
    adapter: 'sails-mongo',
    schema: 'true',

    // url: 'mongodb://admin:********@kahana.mongohq.com:10071/app28526123',
    url: 'mongodb://admin:********@ds063439.mongolab.com:63439/app28526123 ',

    // host: 'kahana.mongohq.com',
    // port: 10071,
    // database: 'app28526123',
    // username: 'admin',
    // password: '********',
```

`model.js`:

```
  connection: 'someMongodbServer',
  migrate: 'drop'
```

`package.json`:

```
  "dependencies": {
    "bcrypt": "^0.8.0",
    "connect-mongo": "^0.4.1",
    "ejs": "~0.8.4",
    "grunt": "0.4.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "include-all": "~0.1.3",
    "mandrill-api": "^1.0.40",
    "moment": "^2.8.1",
    "passport": "^0.2.0",
    "passport-facebook": "^1.0.3",
    "passport-local": "^1.0.0",
    "rc": "~0.5.0",
    "sails": "~0.10.3",
    "sails-disk": "~0.10.0",
    "sails-mongo": "^0.10.4",
    "validator": "^3.17.0"
  },
```
## Error

```
error: A hook (`orm`) failed to load!
error: MongoError: auth fails
    at Object.toError (c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\utils.js:114:11)
    at c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\db.js:1131:31
    at c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\db.js:1846:9
    at Server.Base._callHandler (c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:445:41)
    at c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\connection\server.js:468:18
    at MongoReply.parseBody (c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:68:5)
    at null.<anonymous> (c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\connection\server.js:426:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (c:\Users\Derek\Desktop\workspace\urban-x-app\node_modules\sails-mongo\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:201:13)
    at EventEmitter.emit (events.js:98:17) { [MongoError: auth fails] name: 'MongoError', code: 18, ok: 0, errmsg: 'auth fails' }
```
## Assertion

```
C:\Program Files\MongoDB 2.6 Standard\bin>mongo kahana.mongohq.com:10071/app2852
6900 -u admin -p ********
MongoDB shell version: 2.6.4
connecting to: kahana.mongohq.com:10071/app28526123
set-53864ec05c993f32d3002f62:PRIMARY> db.task.insert({title:"create a web app th
at uses Mongodb",status:"in progress",context:"today"})
WriteResult({ "nInserted" : 1 })
set-53864ec05c993f32d3002f62:PRIMARY>
```

**Comment by MinusRave** [comment]
thank you @umassthrower 

"I was getting various errors so I threw some debug prints in the native mongo npm and saw that it was trying to make all connections I had specified in connections.js. Once I removed connections that didn't make sense for heroku (like my localhost mongodb connection) I was able to connect."

This sentence made my day. Even if everything was properly configured, my sails app somehow connected to the local disk. And it properly started on heroku (but not worked)!!! Only removing the useless connection I've been able to actually connect to mongolab.

I also harcoded the connection string insted of using the connection variable, now I will try again with  the connection variable.

**Comment by masumeEbhami** [comment]
does has difference between mongolab and mongohq  in my sails app?

**Comment by jcaspian** [comment]
@umassthrower Thanks for pointing out. Finally managed to get the app running on heroku by removing connections used for local development. Could you share how did you debug the native mongo npm with mongolab?

**Comment by umassthrower** [comment]
@MinusRave, @derekbasch, @lucj, and @jcaspian Glad I could help

@jcaspian How did I debug the npm? I just went into the package source and temporarily modified it.  It's all just JS.

**Comment by vishnumishra** [comment]
I'm trying to connect mongolab with sails, but it fails to connect.
My user name and password are correct.

**Comment by bonhomie** [comment]
I'm having the same issue connecting to Mongolab.com when I use the url: to connect does anyone have a solution?

**Comment by praveenaj** [comment]
@umassthrower Removing those multiple connections from connections.js did the trick. Thanks a lot! I've been pulling my hair out all day :confused:

**Comment by thewaterbear** [comment]
Just echoing the fact that I'm having the same issue in Sails 11.2, I fixed it more specifically by removing all other mongoDB connections from connections.js. Thanks for the help everyone

**Comment by jossemarGT** [comment]
Bumping this thread, just as @thewaterbear I had exactly the same issue and it worked with the same workaround, now I'm wondering why does sails-mongo misbehave like that? Or if exist a better way to set different configurations per environment?

My connections.js used to be like this one:

```javascript
   // Production configuration
   mongo: { 
     adapter: 'sails-mongo',
     host: process.env.MONGO_PORT_27017_TCP_ADDR,
     port: process.env.MONGO_PORT_27017_TCP_PORT
   },

  // development configuration
  localMongo: {
    adapter: 'sails-mongo',
    host: process.env.DOCKER_HOST ? process.env.DOCKER_HOST.match(/\d+\.\d+\.\d+\.\d+/)[0] : 'localhost',
    port: 27017
  }
```
Now I need to comment in/out one of those to run the application and revert it before building a docker image of it.

Any suggestion?

**Comment by astw** [comment]
I am using the latest sails 0.12.9,  and sails-mongo 0.12.1.  I have the same issue when trying to connect to mongo lab.   My user name and password are correct.

Any other adapters?
