### ISSUE TITLE
ability to define models programmatically

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails#2125]
http://stackoverflow.com/questions/21085624/how-to-create-a-normal-sails-model-without-being-in-the-models-folder

That answer scared me into considering the possibility that creating sails.js models using `Waterline.Collection.extend()` programmatically is really inconvenient and crazy, which is antithetical to everything else sails.js seems to offer. I'm generating my Waterline Collections from an existing database schema using [waterline-pg-json-import](https://github.com/tjwebb/waterline-pg-json-import) and [pg-json-schema-export](https://github.com/tjwebb/pg-json-schema-export).

In Waterline, I can successfully create the Collections and setup the database using [`waterline.initialize`](https://github.com/tjwebb/waterline-pg-json-import/blob/master/test.js#L35). How difficult is this to incorporate into sails.js?

**Comment by givanse** [comment]
This issue should be open, syntax like this:

    sails.Model.create({ identity: ..., attributes: ... });

would be very helpful also for testing

**Comment by anrym** [comment]
Uajskz

**Comment by anrym** [comment]
Putang ina mo?
