### ISSUE TITLE
Form Populate

### ISSUE THREAD

**Issue by marceloboeira** [balderdashy/sails#2129]
What's the right way to populate forms?

I have an html form, and every time the user post some data that is not correct, the form comes back empty, I want that it keeps the user data. 

Something like:
http://framework.zend.com/manual/1.12/en/zend.form.forms.html#populate

**Comment by CWyrtzen** [comment]
@marceloboeira did you find an answer to this over time or in another forum? Can we close this up?

**Comment by marceloboeira** [comment]
@CWyrtzen unfortunately not.

**Comment by CWyrtzen** [comment]
@marceloboeira thanks for responding, I'm sorry the support wasn't handled in a timely manner. I am going to post it in the google group and perhaps someone will have an answer to post for posterity/search results but we will go ahead and close it up for now. Thanks again~
