### ISSUE TITLE
Associations not populated in socket update data

### ISSUE THREAD

**Issue by xjpro** [balderdashy/sails#2136]
I have a model like this:

```
module.exports = {
  attributes: {
    customer: {
      model: 'Customer'
    },
    status: {
        type: 'integer',
        defaultsTo: 1
    }
    // etc...
  }
};
```

When I retrieve the model the customer field is populated with user data as expected. However, when I update the model the socket update message comes to my client as:

```
{
  verb: 'updated',
  id: '14',
  data: {
    id: 14,
    customer: 2,
    status: 2
  },
  previous: {
    id: 14,
    customer: {
      id: 2,
      nameFirst: 'Test'
    },
    status: 1
  }
}
```

Note that the customer association, which was working on the first GET and is still populated in the previous portion of the message, is merely set to an id (i.e. not populated) in the data of the message.

**Comment by GuillaumeLeclerc** [comment]
Any news about this ? Here the values are not populated at all (even during the first GET). 

The result of the same query is different if sent through AJAX rather than socket.io. I think it is a problem. Am I wrong ?

**Comment by skstudios** [comment]
If you are using sockets you also need to populate it on the socket update:
(This was a chunk i used.. i don't see your full code )

function onSave(socket, doc, cb) {
  Calendar.populate(doc, {path:'provider',select:'name'}, function(err, calendar) {
      socket.emit('calendar:save', doc);
  });
}

**Comment by DiegoZoracKy** [comment]
Nothing new about this?
