### ISSUE TITLE
Package.json dependency hook throws warn when grunt is not present

### ISSUE THREAD

**Issue by lyxell** [balderdashy/sails#2144]
Currently, when "grunt" is removed as a dependency from package.json the following is thrown when issuing "sails lift":
```
warn: The package.json in the current directory does not list Sails as a dependency...
warn: Are you sure `DIRNAME` is a Sails app?
```
This happens even if the .sailsrc -> hooks.grunt is set to false and both "sails", "rc" and "include-all" is listed in package.json -> dependencies

**Comment by dustinbolton** [comment]
Just confirming for anyone else having this (similar to asmcad) that having an extra trailing comma in the package JSON anywhere will throw this off.  This did not occur until I updated NodeJS from an old version so I guess it has become more picky about proper JSON formatting.

Before:
  "dependencies": {
    "sails": "~0.10.5",
    "bcrypt": "0.8.2",
    "sails-disk": "~0.10.0",
  },

After:
   "dependencies": {
    "sails": "~0.10.5",
    "bcrypt": "0.8.2",
    "sails-disk": "~0.10.0"
  },
