### ISSUE TITLE
Option to automatically create routes for actions on nested model / controllers?

### ISSUE THREAD

**Issue by leejt489** [balderdashy/sails#2147]
Associations and blueprints are awesome!  Is it possible to automatically expose the actions for controllers associated with a nested model?  For example, I have a `Pet` and `Owner` models (and controllers) with a Many-to-One relationship.  Suppose `OwnerController` has an action `isComingHomeSoon` that returns whether or not the `Owner` is coming home soon.  Is it possible to set some configuration such that `http://root/pets/[petId]/owner/isComingHomeSoon/` calls the `OwnerController.isComingHomeSoon` action and that the ID of the `Owner` is available in `req.param("id")`?  i.e., it has the same behavior as `http://root/owners/[id]/isComingHomeSoon`.

When I hit `GET http://root/pets/[petId]/owner` I get the JSON for the `Owner` (provided it already exists and is associated).
When I hit `GET http://root/pets/[petId]/owner/isComingHomeSoon` I get a 404 with the message "specified record ([petId]) is missing relation 'owner'", which comes from `blueprints.populate`.  `GET http://root/pets/[petId]/owner/` returns the `Owner`, so the relation is there.

This is related to an issue that I would expect I could hit `PUT http://root/pets/[petId]/owner` with some parameters and call `OwnerController.update`, or `POST http://root/pets/[petId]/owner` to create a new `Owner` and associate it with the `Pet`, but in both cases I get an empty 404 response.  I was expecting this because you can hit `POST http://root/owners/[ownerId]/pets` to create a new `Pet` and associate it with the `Owner` automatically, so why not the other way around?

Is the behavior I am describing as designed, or is this a bug or maybe my own error?

If it is as designed, then I think this would be a good Feature, so that parent models could be called in the context of the child without manually setting up the routes.  Without this you would have to  `GET http://root/pets/[petId]` and pull out `owner.id` and then make a call to `http://root/owners/[ownerId]/iscomingHomeSoon`.  Or is there a way to do this with wildcard routing without making all sorts of incorrect routes map to controllers and actions that don't exist?

**Comment by sgress454** [comment]
Hi @leejt489, this functionality is not built into Sails, and there's not currently plans for it.  It's interesting, but without a whole lot of requests for it, it feels a bit bloaty to put in core.  However, if you (or someone) submitted a PR for it (with tests!) we'd certainly take a look.

For a DIY approach, you could try a route like `/root/pets/:petId/owner/*` that mapped to a policy that looked up the correct owner based on the petId, and then reset `req.url` to

```
"/root/owners/" + ownerId + "/" + req.param('0')
```

before calling `next()`.  `req.param('0')` will give you the value of `*` from the original url.

**Comment by leejt489** [comment]
That is a good suggestion for an approach. Thanks for the tip!
