### ISSUE TITLE
Can't create a project: error: No generator called `new` found

### ISSUE THREAD

**Issue by srisy** [balderdashy/sails#2151]
I can't create a new app with `sails new testProject`

```
E:\My Projects>sails new testProject
error: No generator called `new` found; perhaps you meant `sails generate api ne
w`?

E:\My Projects>
```

I had  try to doing that :
 `npm -g remove sails` 
`npm cache clear`  and then 
`npm -g install sails` 
nothing help!

**Comment by 1mike12** [comment]
I have sails 0.11.4 and getting the same issue

**Comment by mikermcneil** [comment]
@1mike12 btw really appreciate you taking the time to create a backlink :+1:
