### ISSUE TITLE
Session secret

### ISSUE THREAD

**Issue by RWOverdijk** [balderdashy/sails#2161]
I've wondered this for a while.. But why does sails generate the session secret to `config/session.js`? I'm planning on publishing some of my applications open source, but I think it's not very smart to publish my session secret. Same reason I don't put my db credentials in `config/connections.js` but in `config/local.js.dist`.

**Comment by loicsaintroch** [comment]
Hey @RWOverdijk. Sorry for the delay but as you know things were pretty difficult for the past few months on Sails. We'll work on it soon or feel free to right a PR, I'll be glad to merge it. Closing this for now.
