### ISSUE TITLE
Create support to helpers -> ejs/filters

### ISSUE THREAD

**Issue by marceloboeira** [balderdashy/sails#2162]
At the api folder, could be created a "helpers" folder, allowing the us to create helpers based on EJS filters.

http://stackoverflow.com/questions/21064365/where-to-access-and-store-ejs-helpers-sailsjs 

So, /api/helpers/dateHelpers.js

``` js
var moment = require('moment');

module.exports = {
   formatDate: function(date) {
      return moment(date).format('MMM Do YYYY');
   }
   fromNow: function(date) {
       return moment(date).fromNow();
   }
}
```

at some view:

```
<%=: post.createdAt | fromNow %>
```

**Comment by keynertyc** [comment]
No Work for Sails.js

sails --version
0.11.0

config/http.js

//
locals: {
    filters: {
      formatDate: function(date) { 
        return moment(date).format('MMM Do YYYY');
      }
    }
  }

config/bootstrap.js

_.extend(sails.hooks.http.app.locals, sails.config.http.locals);

views/layout.ejs

<% formatDate %>

-----
error:

formatDate is not defined
 >> 53|             <% formatDate %>
formatDate is not defined]

-----
Please, help me. Thanks.

**Comment by randallmeeker** [comment]
I just put view helpers in as services. The same as above just in services.

**Comment by keynertyc** [comment]
It works for me:

Sailsjs v. 0.11.0

config/http.js

var helpers = require('express-helpers')();

module.exports.http = {
.....
locals: {
    "date_tag" : helpers.date_tag,
    "form_tag" : helpers.form_tag,
    "form_tag_end" : helpers.form_tag_end,
    "hidden_field_tag" : helpers.hidden_field_tag,
    "input_field_tag" : helpers.input_field_tag,
    "link_to" : helpers.link_to,
    "submit_link_to" : helpers.submit_link_to,
    "link_to_if": helpers.link_to_if,
    "link_to_unless" : helpers.link_to_unless,
    "password_field_tag" : helpers.password_field_tag,
    "select_tag" : helpers.select_tag,
    "single_tag_for" : helpers.single_tag_for,
    "start_tag_for" : helpers.start_tag_for,
    "submit_tag" : helpers.submit_tag,
    "tag" : helpers.tag,
    "tag_end" : helpers.tag_end,
    "text_area_tag" : helpers.text_area_tag,
    "text_tag" : helpers.text_tag,
    "text_field_tag" : helpers.text_field_tag,
    "url_for" : helpers.url_for,
    "img_tag" : helpers.img_tag,
  }
.....
}

**Comment by gadidev** [comment]
sails v0.11.2

This `_.extend(sails.hooks.http.app.locals, sails.config.http.locals);` etc.  worked for me, (ie, it added filters), however  the default filters (capitalize) etc, because undefined.   
My work around was to define the filters using:

to create the file `config/helpers.js` with:

`var ejs = require('ejs');`
`ejs.filters.formatDate = function (date) { };`

**Comment by levelsuphk** [comment]
can't we format inside <% %>
