### ISSUE TITLE
The ability to specify the many to many middle table name

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#2172]
do we have now?
or i would like to request this feature.

**Comment by jdcauley** [comment]
@calidion can you clarify the question.

You're asking to be able to set the name of the table in a many to many association.

Ex. 

User <- -> Account
Where name in date is AccountUsers?

**Comment by calidion** [comment]
yes

**Comment by jdcauley** [comment]
@calidion is this a feature you would be interested in developing or just a general request?
