### ISSUE TITLE
Using moduleLoaderOverride to change the depth of the services folder.

### ISSUE THREAD

**Issue by DavidEBest** [balderdashy/sails#2181]
I'm working on converting a sails .9 app to sails .10. This app has sub-folders in the services folder, which doesn't work for the way services are used in the current version.

loadServices in hook/moduleLoader currently limits the depth to 1. Based on my understanding of the code, it appears that I should be able to update this value by defining an sails.config.moduleLoaderOverride which overrides the loadServices method. I can't seem to get this to work. The moduleLoaderOverride is undefined when moduleLoader.configuration is called, but becomes defined later in the start up process.

What is the intended/expected way to update the moduleLoader buildDictionary calls?

**Comment by irobayna** [comment]
@loicsaintroch @Enkows  @DavidEBest I would like to load services from subfolders too.  With this solution: https://github.com/DavidEBest/midas/blob/devel-sailsupgrade/config/bootstrap.js
 it seems the services are not exported automatically and I have to reference them via ```sails.services.```

For instance if I have a new xyz folder under services the call would look something like this: ```sails.services.xyz.myService.myfunction()```

This does what I need( thanks!!), would be perfect if the services would be accessible in the globally. 
Any way to export these services under subfolder globally as regular services do ?
