### ISSUE TITLE
[Feature Request] Prefix Policies

### ISSUE THREAD

**Issue by mewben** [balderdashy/sails#2194]
Hello everyone, wondering if putting policies in prefixed routes is feasible?

Use case: Would it be much easier if
```
'/api/v1' : ['sessionAuth']
```
rather than define each controller and implement a policy?

Just a thought. :)

**Comment by CWyrtzen** [comment]
Thanks for marking this is FR, sorry it didn't generate discussion at this time. I am going to close it as an "issue" but it is marked and searchable as a feature request, it can be reopened at any time, and new discussion is always welcome~
