### ISSUE TITLE
i`m using angularjs i need some help

### ISSUE THREAD

**Issue by foobar1123** [balderdashy/sails#2203]
XMLHttpRequest cannot load http://127.0.0.1:1337. Request header field Authorization is not allowed by Access-Control-Allow-Headers. 

Sails js
module.exports.cors = {
  allRoutes: true,
  origin: '*',
  credentials: true,
  methods: 'GET, POST, PUT, DELETE, OPTIONS, HEAD',
  headers: 'content-type'
};

angularjs

  .factory('AuthInterceptor', function($q, $injector) {
    var LocalService = $injector.get('LocalService');
    return {
      request: function(config) {
        var token;
        if (LocalService.get('auth_token')) {
          token = angular.fromJson(LocalService.get('auth_token')).token;
        }
        if (token) {
          config.headers.Authorization = 'Bearer ' + token;
        }
        return config;
      },
      responseError: function(response) {
        if (response.status === 401 || response.status === 403) {
          LocalService.unset('auth_token');
          $injector.get('$state').go('anon.login');
        }
        return $q.reject(response);
      }
    }
  })
  .config(function($httpProvider) {
    $httpProvider.interceptors.push('AuthInterceptor');
  })

**Comment by Clan-Utility** [comment]
Same problem happened here! I use angular-jwt

    .config(function ($httpProvider, jwtInterceptorProvider) {
        jwtInterceptorProvider.tokenGetter = ['$localStorage', function($localStorage) {
            return $localStorage.token;
       }];
       $httpProvider.interceptors.push('jwtInterceptor');
    })
