### ISSUE TITLE
Sailsjs grunt .svn error during lifting

### ISSUE THREAD

**Issue by pawankorotane** [balderdashy/sails#2208]
Hi Guys,

I have imported my project in svn when I did a checkout and ran the app I got this error I am using sailsjs-0.10.5. I think it is to do with the grunt I am not able to find any solution it works fine in mac not in linux I set the permissin to 0777 even though it is not working here is the error.

```
verbose: Grunt :: Loading "Gruntfile.js" tasks...
verbose: Grunt :: ERROR
verbose: Grunt :: >> TypeError: Property '.svn' of object #<Object> is not a function
verbose: Grunt :: Warning: Task "default" not found. 
error: ** Grunt :: An error occurred. **
error: 
------------------------------------------------------------------------
Aborted due to warnings.
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Property '.svn' of object #<Object> is not a function
Warning: Task "default" not found. 
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error: 
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error: 
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error: 
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/var/hosts/chating_room/.tmp` ?
error: 
error:      If you think this might be the case, try running:
error:      sudo chown -R YOUR_COMPUTER_USER_NAME /var/hosts/chating_room/.tmp

```

**Comment by shanelau** [comment]
I'm also facing the same issue. Any solution ?

**Comment by Nishchit14** [comment]
I have a same problem.

FIXED by

Simply deleting  .svn folder from task/.svn, config/.svn & register/.svn

**Comment by tonychenc** [comment]
Make changes to Gruntfile.js, find `loadTasks` function, add `excludeDirs :  /^\.(git|svn)$/`:

Original:

    function loadTasks(relPath) {
            return includeAll({
                    dirname: require('path').resolve(__dirname, relPath),
                    filter: /(.+)\.js$/
            }) || {};
    }

After:

    function loadTasks(relPath) {
            return includeAll({
                    dirname: require('path').resolve(__dirname, relPath),
                    filter: /(.+)\.js$/,
                    excludeDirs :  /^\.(git|svn)$/
            }) || {};
    }

**Comment by nuxman** [comment]
I had to delete .tmp inside the folder project and it is work for me

**Comment by mikermcneil** [comment]
@tonychenc @nuxman I'll change this in the defaults
