### ISSUE TITLE
Using ECT or Nunjucks engines

### ISSUE THREAD

**Issue by jjude** [balderdashy/sails#2223]
When I use extends with either ECT or Nunjuncks, sails throws an error, 

`template not found: default.html`

`default.html` is the base template.

While going through the issues list (ref: #1757), I understand it might have to do with how these engines handle absolute paths. So how do you go about using these engines? Is something need to be fixed in sails or can we pass some parameters as part of res.view to make it work?

(I raised this question in google groups & stackoverflow. But raising it here assuming, it might need a code-fix as this issue is for more than one view engine)

**Comment by jhechtf** [comment]
I am trying to use ECT for my app's template engine, but I can't figure out where that code in that PR linked by @jjude is? Can anyone help me really quickly on _where_ that file is.
