### ISSUE TITLE
Compress middleware

### ISSUE THREAD

**Issue by TonyG-git** [balderdashy/sails#2235]
Hi!
Somebody know how to corretly switch off compress? 
I comment it in config/http.js but it continue compress my SSE answers until I comment it in node_modules/sails/lib/hooks/http/index.js

What I real need - stop compressing my "text/event-stream" responses.

Some ideas?

**Comment by gotmikhail** [comment]
+1

This seems very inconsistent to me. Meaning, I have it commented it out in `config/http.js`, but on one server I'm getting a compressed response and on another instance I'm not.

I also noticed that it never compresses in develop mode, and I don't see that documented anywhere. It may be somewhere, but I've looked and haven't found it.

**Comment by woollybogger** [comment]
You just have to add `compress: false` to the `middleware` object in `config/http.js`.

**Comment by loicsaintroch** [comment]
Thank you for your answer @woollybogger.
