### ISSUE TITLE
Unique field seeing NULLs as equal values

### ISSUE THREAD

**Issue by parnurzeal** [balderdashy/sails#2239]
I have set `unique:true` on some fields in the model.  
When using, sails accepts multiple NULL values without any problem.

But if I restart sails, it will check the equality of all unique fields and will give me following errors:

```
info: Starting app...

One or more existing records in your database violate a new uniqueness constraint
on `hostname` in your `server` model.

Should we automatically remove duplicates?

** WARNING: DO NOT TYPE "y" IF YOU ARE WORKING WITH PRODUCTION DATA **
```
 
I am using MariaDB as my DB and any null values will be validate as different null. 
You can see more details here (https://mariadb.com/kb/en/sql-99-complete-really/20-sql-constraints-and-assertions/constraint_type-unique-constraint/)
So, I think it's sails that need to be fixed to not to see multiple NULLs as same value.

I am using both sails and sails-mysql v0.10.0-rc7

**Comment by CWyrtzen** [comment]
Did this get cleared up?

**Comment by parnurzeal** [comment]
I guess. I didn't work on this anymore.
Let's just close this issue.

**Comment by CWyrtzen** [comment]
thanks, take care~
