### ISSUE TITLE
there needs to be a way to override forced production safe migration

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails#2240]
https://github.com/balderdashy/sails/blob/76339cf9d38d217f9d365143880d331de8b49b38/lib/hooks/orm/normalize-model.js#L55

It's quite confusing since in `production` logging is likely not set to verbose, so you'll never see that message. If you've explicitly set migrate to something other than `safe`, sails should either dutifully carry out your wishes, or it should totally halt and shut down. Silently ignoring this is harmful.

**Comment by CWyrtzen** [comment]
Any updates here?
