### ISSUE TITLE
"alter" for the model migration having problem.

### ISSUE THREAD

**Issue by Lujaw** [balderdashy/sails#2244]
Whenever the sails is lifted using alter migration mode, it shows the following error.
'Details:  Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1"

checked, but there are no issues.
The same app lifts, when using "drop" and "safe" migration mode..

**Comment by jdcauley** [comment]
Its probably worth noting that Alter is still an "Experimental Feature".

Can you provide any additional info re model structure etc?

**Comment by Lujaw** [comment]
its a simple user table with only first  name and last name .

**Comment by jdcauley** [comment]
@Lujaw did you ever get through this, can you include the controller action creating the user?
