### ISSUE TITLE
Angular routing / sails routing question

### ISSUE THREAD

**Issue by Karnith** [balderdashy/sails#2245]
Before I dig into the code for the sails routing system I have a question to see if my idea is even sound.

Is it possible to create a custom hook that would act as a navigator and catch requests before they hit the sails routing system?

I ask this because I find using a dummy controller to render a view to render an angular page a cumbersome solution that traverses the the framework when it isn't needed.

 My ides is to create a feature that acts as a buffer between the client and sails when requests are sent. This buffer, or navigator, would examine the prefix for the api system in blueprints and either return the index.html in the public folder or forward the request to the api in sails. This would then negate the need to specify all angular routes in routes.js, dummy controllers and the loopback that is currently needed when angular is used with sails.

Thoughts?

**Comment by tarlepp** [comment]
@blah238 just noticed this... Thanks for that reference, I hope that "boilerplate" has help you people.
