### ISSUE TITLE
Remove invoking grunt:prod on production mode

### ISSUE THREAD

**Issue by konstantinzolotarev** [balderdashy/sails#2270]
Hi all. 
It's more a question to community.
May be we could remove invoking grunt when running sails in production mode and run grunt commands manually ?

Problem for me is this: 
I'm using sails.js v0.10.5 in production on live website.And using CI service. 
Also my application has lot of jade, js and css files for frontend.
So when I need to restart my app or make a small change into sources it it compiles all this resources every time even if I don't need it. 

For my installation I made a hook and disabled grunt for production. 
But might be it will be a good way to for this for others ?

What do you think ?

**Comment by jdcauley** [comment]
@konstantinzolotarev or @m-bodmer are either of you interested in submitting this as a PR?

**Comment by konstantinzolotarev** [comment]
@jdcauley DO we really need it ? Because as I see from conversation and PR comments we could disable it using `.sailsrc` file like this: 
```javascript
{ 
  "hooks": { 
    "grunt": false 
  },
  "paths": {
    "public": "assets"
  }
}
```

**Comment by jdcauley** [comment]
@konstantinzolotarev if you're happy I'm happy
