### ISSUE TITLE
Bind update action for each `collection` associations

### ISSUE THREAD

**Issue by cshenoy** [balderdashy/sails#2293]
Blueprints automatic route binding is great for model associations. I know there's already `POST` and `DELETE` methods for the associations. Is there a reason an update `PUT` method has not been added?

https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/index.js
Lines 325-326 are:

    _bindRoute( _getAssocRoute('post %s/:parentid/%s/:id?'), 'add', opts );
    _bindRoute( _getAssocRoute('delete %s/:parentid/%s/:id?'), 'remove', opts );

I'm thinking of adding:

    _bindRoute( _getAssocRoute('put %s/:parentid/%s/:id'), 'modify', opts );

And then obviously creating the associated `modify.js` action to facilitate an update to the child model. Just want to make sure I'm not overlooking why it wasn't created in the first place.

**Comment by CWyrtzen** [comment]
Is this resolved?

**Comment by cshenoy** [comment]
Seems like the core team doesn't agree with my thoughts so I've just put it in as a custom hook. Feel free to close this if you don't see it being added to core.

**Comment by CWyrtzen** [comment]
Ok @cshenoy your efforts are greatly appreciated. I will close it up--it can always be reopened for discussion--and it will, of course, be here on record and searchable for the future. thanks again~
