### ISSUE TITLE
Allow custom view extensions

### ISSUE THREAD

**Issue by mrfishie** [balderdashy/sails#2303]
Currently, the extension of a view file needs to be the same as the name of the templating engine. This is annoying for engines with a long name (e.g. Nunjucks).

It is possible to configure the extension by setting the `sails.config.views.engine` config property to an object, but this requires that the engine render function be provided as well, whereas Sails normally does this automatically when a string is provided.

By adding the `sails.config.views.extension` property, custom file extensions can be provided.

I have already created a PR which implements this: https://github.com/balderdashy/sails/pull/2304

**Comment by sgress454** [comment]
Merged #2304 on 12/1/2014...
