### ISSUE TITLE
Create versioned API without blueprint

### ISSUE THREAD

**Issue by kai23** [balderdashy/sails#2305]
Hello,

I'm trying to figure out how to create a versionned API for my application.
According to this issue https://github.com/balderdashy/sails/issues/322 , I have to use blueprint, but all blueprint is deactivated in my project (a wish from my boss).

I want to be able to have any URL like `http://myapi.com/v1/my-custom-route` , and so on for any version.

So far, the best way I've found is to duplicate all controller to something like `v322AuthController.js` and to map all routes like 

    'POST /v3.2.2/se-connecter'              : 'v322AuthController.perform_signin'

But I think that's an ugly trick. I'm currently using Nginx and all my code is versionned with git

Thank you if you have any idea

Kai23

**Comment by jdcauley** [comment]
@kai23 I assume you want to avoid writing custom routes for every endpoint.

**Comment by nikhiljohn10** [comment]
Try `$ sails generate controller v3.2.2 se-connecter`

This create a controller called v3.2.2.js with se-connecter as action. Thus you get the route `/v3.2.2/se-connecter`

Just a random solution.
