### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by pavlo** [balderdashy/sails#2314]
Hey! I am writing an Angular app that talks to a sailsjs backed backend (sails version is 0.10.4). At some point the Angular app issues a GET request to a blueprint API endpoint:

    $http.get('http://my.server.com/stuff').then(...) 

Here's what it receives (prints in console of the angular app):

    XMLHttpRequest cannot load http://my.server.com/stuff. 
    No 'Access-Control-Allow-Origin' header is present on the requested resource. 
    Origin 'http://localhost:1337' is therefore not allowed access. 
    The response had HTTP status code 401.

Here's how config/cors.js is looking like:

    allRoutes: true,
    origin: '*',
    headers: 'Content-Type, Authorization, X-Requested-With, Cache-Control, Accept, Origin, X-Session-ID,Access-Control-Allow-Origin'

It is worth to mention that I have Nginx behind http://my.server.com, it just proxies everything to the sails app on server that is listening 1337 port.

Could you please see if there's any obvious mistakes or things I overlooked here?

Thank you!
Pavlo

**Comment by loicsaintroch** [comment]
Thank you for your help @handleror.
