### ISSUE TITLE
Question: how can I subscribe on websocket event in any service?

### ISSUE THREAD

**Issue by AndrewEastwood** [balderdashy/sails#2319]
I'm going to create api/services/dummy.js
and there I wanna do smth like this:
```
socket.on('my_msg', function () {});
```
Would you please help me with this?

**Comment by jdcauley** [comment]
@AndrewEastwood did you figure this out or are you still needing help?

If I don't hear back in the next couple of days I'm going to close this.

**Comment by AndrewEastwood** [comment]
okay. You can close this case.
