### ISSUE TITLE
TypeScript support on server-side

### ISSUE THREAD

**Issue by Diullei** [balderdashy/sails#232]
How do I can contribute adding TypeScript support to server-side?

I guess the [`renderBlueprint(blueprint, data)`](https://github.com/Diullei/sails/blob/master/bin/sails.js#L597) is a good **start point** to implement the template language to be used to generate the sources files, however, I do not know what the best way to tell Sails which target language (`javascript` or `typescript`) I want to use.

Thoughts?

**Comment by Vadorequest** [comment]
I've built an open source Sails dummy project to show you how I used TS on the server side with Sails.

https://github.com/Vadorequest/sails-typescript

Discussion is here: https://groups.google.com/forum/#!topic/sailsjs/XoxiE8CiFTE
