### ISSUE TITLE
Lift after every change sucks

### ISSUE THREAD

**Issue by ryasmi** [balderdashy/sails#2321]
I don't want to and don't think I should have to stop my server and run `lift` every time I change code when I'm developing. It makes developing slower and more tedious. I don't know the solution here, but I do know that "lifting" every time is annoying the hell out of me.

**Comment by kevinburke** [comment]
The "specific Sails thing" that makes this frustrating may be the ~6-10 seconds it takes Sails to start a server. It's not clear what is going on.

**Comment by particlebanana** [comment]
@kevinburke 6-10 seconds sounds extreme. If you have `migrate: alter` on and a lot of test/development data I can see it taking a while but in that case you want to turn on `migrate: safe` so it's not touching your data. 

Could you have a bootstrap file that is taking a while to run? If you want to see what's happening set the log level to `silly` mode and it will log everything in the startup process.

**Comment by kevinburkeshyp** [comment]
Here's the test file (note migrate is off):

https://gist.github.com/kevinburkeshyp/6a772c9f6a8367e6ae6a

Connecting to a Postgres instance running on my local machine.

Here is a gif of the startup process (timing output at the very bottom):

<img src="http://i.gyazo.com/938c1bf2e8868bff2f7268a384f00b60.gif" />

On Fri, Jan 30, 2015 at 11:26 AM, Cody Stoltman <notifications@github.com>
wrote:

> @kevinburke <https://github.com/kevinburke> 6-10 seconds sounds extreme.
> If you have migrate: alter on and a lot of test/development data I can
> see it taking a while but in that case you want to turn on migrate: safe
> so it's not touching your data.
>
> Could you have a bootstrap file that is taking a while to run? If you want
> to see what's happening set the log level to silly mode and it will log
> everything in the startup process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails/issues/2321#issuecomment-72255740>.
>



-- 
kevin

**Comment by kevinburkeshyp** [comment]
Here's the test file (note migrate is off):

https://gist.github.com/kevinburkeshyp/6a772c9f6a8367e6ae6a

Connecting to a Postgres instance running on my local machine.

Here is a gif of the startup process (timing output at the very bottom):

<img src="http://i.gyazo.com/938c1bf2e8868bff2f7268a384f00b60.gif" />

**Comment by particlebanana** [comment]
@kevinburkeshyp looks like it's all in the model loading. Do you have a large number of models? It takes a bit to parse them all and build out schemas and associations.

**Comment by kevinburke** [comment]
```
find api/models -type f | wc -l
      44
```

is this an unexpectedly large number?

**Comment by particlebanana** [comment]
@kevinburke I guess it depends on how many attributes and associations are in each one. Remember it has to keep all these in memory so it has to loop through all the keys on lift and turn them into WL models. I'm sure that loading process could be a lot better in Waterline though.

**Comment by kevinburkeshyp** [comment]
hm. any obvious ideas? how would i profile the load performance?

On Fri, Jan 30, 2015 at 12:12 PM, Cody Stoltman <notifications@github.com>
wrote:

> @kevinburke <https://github.com/kevinburke> I guess it depends on how
> many attributes and associations are in each one. Remember it has to keep
> all these in memory so it has to loop through all the keys on lift and turn
> them into WL models. I'm sure that loading process could be a lot better in
> Waterline though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails/issues/2321#issuecomment-72263038>.
>



-- 
kevin

**Comment by kevinburkeshyp** [comment]
Did some profiling and wrote up the results here: https://kev.inburke.com/kevin/node-require-is-dog-slow/

node takes 2.5 seconds to require 30 model files. No way to parallelize `require`, since the operation is synchronous. Possible benefit from rewriting all imports to be relative to the `node_modules` folder, since that would help avoid a bunch of extraneous `open()`/`stat()` calls.
