### ISSUE TITLE
Trying to '.add()' an instance which already exists!

### ISSUE THREAD

**Issue by billyshena** [balderdashy/sails#2327]
Hello sailers !

I'm currently encountering issues with Trying to '.add()' an instance which already exists! when I try to use .add => .save

ex: User.find(1).populate('pets') => user[0].pets.add(1) ; user[0].save(function()...}); => Add the relation (many-to-many) between Pet and the User.

1) Is there a way to avoid this error printed?
2) I'm using blueprints action to do that like .post('/user/1/pets/1') => How can I set a policy to that blueprint action? 

Best regards,

**Comment by CWyrtzen** [comment]
@billyshena has you question been answered somewhere else?

**Comment by stuk88** [comment]
just make save with function that dont do anything :
    Model.save(function(err) {})

**Comment by CWyrtzen** [comment]
If this is still an issue we can open it back up~
