### ISSUE TITLE
Question: can I use db replication?

### ISSUE THREAD

**Issue by AndrewEastwood** [balderdashy/sails#2331]
I want to use two connections at the same time: one connection is being used when whatever I save, and the other when I read data. Is this possible?

**Comment by CWyrtzen** [comment]
@AndrewEastwood did you ever find an answer or resolution to your issue?

**Comment by AndrewEastwood** [comment]
nope. I've just switched to another framework :grin:

**Comment by CWyrtzen** [comment]
Ok, take care. If someone else has the same issue, please feel free to reopen and reignite the discussion. For now I'm gonna close it up~

**Comment by odnarb** [comment]
I think I need something akin to this. However, I am wanting to use AWS Elasticache, which handles replication automicatlly, and I have a basic 3 redis node setup. I want to be able to define those 3 in sails.js such that if one redis node goes down the app will cycle through and use another for its connection.

This might be more of a sails-redis adapter specific question but maybe waterline needs to support this first? Not sure how the acrhitecture goes but my gut says it's the adapter that defines how connections are handled.

Am I way off?

Thanks

**Comment by odnarb** [comment]
@sgress454 @mikermcneil Any thoughts on this?

**Comment by irlnathan** [comment]
@odnarb Howdy,  Please take a look at the new [contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions) and possibly open a new issue. Thanks!

Best, Irl
