### ISSUE TITLE
How to set a policy to blueprint actions like: /user/1/pets/1 (Many to many relation)

### ISSUE THREAD

**Issue by billyshena** [balderdashy/sails#2335]
Hello sailers! I'm currently using a lot of blueprints action to add new rows in my JOIN TABLE using blueprints.

ex: $http.post('/user/1/pets/1') => Add the relation between Pet (id = 1 ) and User (id = 1)

How can I set a policy to this specific blueprint action?
Any docs related?

Regards

**Comment by CWyrtzen** [comment]
If this is still an unresolved issue, please feel free to reopen it. If you found a solution, please post it. @irlnathan has also produced a number of sailscast tutorials including several addressing blueprints: https://www.youtube.com/user/ponzicoder ~Cheers!
