### ISSUE TITLE
How can I use ascending or decending in model ?

### ISSUE THREAD

**Issue by bhushano7** [balderdashy/sails#2337]
Hey,

I want my data sort by "createdAt" column . Sometime in ascending order and also descending order also. I am using mongo db .

Currently, I have created app which have feature like Users data can be sorted by admin request. Admin can view data in ascending order or by descending order.

I have tried option by using sort parameter which gives me data every time in same order. How can I change as admin per admin request.

Please review below that I have tried.

               var options = {
			limit: request.body.limit || undefined,
			skip: request.body.skip || undefined,
			sort: request.body.sort || "createdAt",
			where: request.body.where  || undefined
		};

		Users.find(options, function (err, Users) {
			if (Users === undefined) {
				return response.json({message: "No data Found"});
			}
			else if (err) {
				return response.json({message: err});
			} else {
				return response.json({data: Users});
			}
		});

**Comment by CWyrtzen** [comment]
@bhushano7 did you get an answer to your question?

**Comment by bhushano7** [comment]
I found out solution.

**Comment by CWyrtzen** [comment]
Ok, I'm going to close this. It would be great if you could post the solution or link to the answer just in case someone else has the same problem. Thanks!
