### ISSUE TITLE
Empty list of associated models when defaultLimit is -1

### ISSUE THREAD

**Issue by davodesign84** [balderdashy/sails#2352]
When trying to retrieve a collection of a model with an association, the list returned is empty if defaultLimit is set to -1 in config/blueprint.js.
Retrieving individual records work fine as well as querying Model.find().populateAll()

**Comment by CWyrtzen** [comment]
@davodesign84 did this get resolved or addressed in a new release?

**Comment by davodesign84** [comment]
unfortunately I haven't checked in a while.

**Comment by CWyrtzen** [comment]
Ok, thanks for sharing your work-around. I'm going to close it up and it can be reopened for discussion at any time if the problem persists. Thanks!
