### ISSUE TITLE
Sails 0.10 hangs on lift while attemt to use OrientDB

### ISSUE THREAD

**Issue by pdipietro** [balderdashy/sails#2354]
I'm using the latest sails, sails-orientdb and orientdb versions.
While attempting to start rails using the sails-orientdb connector, it remains hanging.
You will find an accurate description of the installation and startup procedure on my 
https://github.com/pdipietro/ogsn/blob/master/INSTALLATION.md

Hope someone could help.

Paolo

**Comment by dmarcelino** [comment]
Hi @pdipietro, I know this is a bit late but can you try [waterline-orientdb](https://github.com/appscot/waterline-orientdb)?

**Comment by pdipietro** [comment]
Hi @dmarcelino, I'm sorry, but as we didn't receive answers here and from other sources, we left OrientDB for the moment and moved to Neo4j.
If, in the future, OrientDB will offer an endorsed and stable support for ROR, we will try to move, but now we have more business than technical pressures.
Let me know, when something will change.
TY in any case

**Comment by CWyrtzen** [comment]
I'm sorry this wasn't resolved in time to support your project. Can we close this up? If someone else comes across the same issue we can always reopen it for discussion.

**Comment by anrym** [comment]
Fuck you

**Comment by pdipietro** [comment]
As your first and only contribution it is really fair and usefull ;-)

Il 31/05/2015 07:29, anrym ha scritto:
> Fuck you
> On 29 May 2015 16:32, "Paolo Di Pietro" <notifications@github.com> wrote:
>
> > Closed #2354 <https://github.com/balderdashy/sails/issues/2354>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/balderdashy/sails/issues/2354#event-317001614>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/balderdashy/sails/issues/2354#issuecomment-107128910>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
http://www.avast.com
