### ISSUE TITLE
association pulls all fields instead of what is in the model.

### ISSUE THREAD

**Issue by JesseChrestler** [balderdashy/sails#2357]
the database has two tables, user and note.
user has the following fields:
id, firstname, lastname

note has the following fields:
id, userid, tile, description, addedDate

however my model is

User.js (model)

    user : {
        firstname:'string',
        lastname:'string',
        notes :{
            collection:'note',
            via:"userid"
         }
    }
Note.js (model)

     note: {
	   userid:{
	        type:'string',
	        model:'user'
	   },
	  description:'string'
	}

and in my control i write something like this.

	   User.find()
	      .populate('note')
	      .exec(function(err, records){
	      res.json(records);
	    });
my response I get is:

		{
			firstname:"test",
			lastname:"test",
			notes:[{
				id:1,
				userid:1,
				title:"test",
				description:"mydescription",
				addedDate:"2014-11-02T04:00:00.000Z"
			}]
		}

should my notes only include what's in my model, and not all the columns in the table?

**Comment by loicsaintroch** [comment]
Thank you for your help @konstantinzolotarev.
