### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by naterkane** [balderdashy/sails#2358]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with sails. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable sails on @Sourcegraph by going to https://sourcegraph.com/github.com/balderdashy/sails and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by loicsaintroch** [comment]
Done. But we'll do a better management about it as soon as we moved to our new workflow. Thank you for your help guys.
