### ISSUE TITLE
Emacs autosave file cause an Error when trying to start sails.

### ISSUE THREAD

**Issue by giyyapan** [balderdashy/sails#2361]
Hi All !
I'm using Emacs to edit my files. Emacs will write some file named #filename.xx# for auto-save.
When I try to ' sails lift ' with those files , I got an error like

```
Error: ENOENT, no such file or directory '/path/to/sails/project/api/models/.#MyModel.coffee'
```

Can I add a config somewhere to filter what kind of file I want to load or avoid ?

Thanks !

**Comment by manojmo** [comment]
This is still relevant in Sails 1.1.
 at Hook.loadModels (/media/manoj/DNTFS/projects/digineeds/dn/node_modules/sails/lib/hooks/moduleloader/index.js:304:18)
Here, a regex is used to filter the model files. If we append a [^~] before the $, it will stop loading the backup files. I wasted quite some time wondering why changes to my model were not being loaded, and then realised that it was picking up the backup file. In fact, even an extension like xml works. So I feel it should be kept as restricted as possible. The tilde change is applicable to all files, not just models.
