### ISSUE TITLE
IcedCoffeeScript is supported?

### ISSUE THREAD

**Issue by friktor** [balderdashy/sails#2363]
Hi all. Im writting on CoffeeScript. But now, for convenience, I need to use IcedCoffeeScript, is there any support in the sails? And if not, whether it will be in the future. I know that the basic philosophy of Sail does not work with CoffeeScript and not really paying attention to him, but nevertheless I would like to be able to use an extended set of "Iced" in their work. If no one is familiar with the decision of this question - which file in the library of Sails, is responsible for working with CoffeeScript?

**Comment by loicsaintroch** [comment]
Feel free to write a PR like #2662. We'll be glad to merge it. Thank you for your help @friktor.
