### ISSUE TITLE
[feature] Add configuration to csrf to be able to change default /csrfToken route

### ISSUE THREAD

**Issue by konstantinzolotarev** [balderdashy/sails#2366]
Need to add a config option to `sails.config.csrf` to be able to change default route for getting _csrf parameter for forms.

Something like this: 

```javascript
module.exports.csrf = {
    route: '/api/csrfToken'
};
```

**Comment by dottodot** [comment]
At the moment it's not possible to use csrf when using a route prefix. Is there a fix or solution that can be used?

**Comment by konstantinzolotarev** [comment]
PR is still open. So you could fork repo and apply it locally.

**Comment by loicsaintroch** [comment]
Merged https://github.com/balderdashy/sails/commit/f5cf006be0fc5d32cac2e1aaad407d0a101f224c. Thank you guys.
