### ISSUE TITLE
sails-linker Grunt task doesn't honor ignored files

### ISSUE THREAD

**Issue by jfrumar** [balderdashy/sails#2375]
Using Sails 0.10.5.

I am trying to prevent specific JS files from being linked into the layout.ejs file. It seems adding a "!" to the start of a file pattern in pipeline.js has no effect (I have tried varying the ordering of the elements too).

To reproduce:

- Create a new sails app (e.g. `sails new tmpsails`)
- Edit tasks/pipeline.js and change `js/dependencies/**/*.js` to `!js/dependencies/**/*.js`
- lift sails and check layout.ejs - you'll see:

```html
    <!--SCRIPTS-->
    <script src="/js/dependencies/sails.io.js"></script>
    <!--SCRIPTS END-->
```

I expected that moving the exclusion pattern above after the inclusion `js/**/*.js` would solve the problem, but alas no - it still links in the dependencies (and other files).

**Comment by CWyrtzen** [comment]
Was the pull request ever created? Or is this even still an issue after the new release (v0.11)?

**Comment by rmckeel** [comment]
Yes - from my brief testing, it is still an issue with v0.11.0.  My test was:

```
'js/**/*.js',
'!js/**/*.js
```

**Comment by rmckeel** [comment]
Also see related SO questions: http://stackoverflow.com/questions/29327025/sails-js-specify-js-files-to-exclude-from-auto-insertion, http://stackoverflow.com/questions/12632029/grunt-minimatch-glob-folder-exclusion, http://stackoverflow.com/questions/21470128/sailsjs-linker-grunt-ignore-files-gruntfile-js.  It is a commonly requested feature / capability for Sails that Grunt should already have (http://stackoverflow.com/a/12633119/3232832).

**Comment by sgress454** [comment]
Thanks to @mitom for the fix
