### ISSUE TITLE
JS native Promise function is not define when Sails Lift 

### ISSUE THREAD

**Issue by giyyapan** [balderdashy/sails#2378]
I'm using JS native Promise.all() in some controller . Everything works just fine in my computer but when I try to run same code with "sails lift" in server , this error appear.

```
 ReferenceError: Promise is not defined
  at module.exports.index (/path-to-project/api/controllers/ArticlesController.coffee:18:7)

```

This only appear when I use 'sails lift'. not when I use 'node app.js'

I'm using the latest version of sails (v 0.10.5) and nodejs (v 0.11.14) , dose someone know what may cause this error ?  Is this a bug ?

**Comment by ethode** [comment]
Thank you - this worked great for me
