### ISSUE TITLE
how to implement a "after-route" policy

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails#2387]
I like how policies separate my controller logic from guard logic. But I need a policy to run **after** the request has been handled by the controller, but before the server responds to the client.

I have a policy use-case that requires the result of the request in order to answer the question; I'd like to run it on every request, so implementing in each controller handler isn't feasible.

**Comment by CWyrtzen** [comment]
Can anyone update this with an answer to @leejt489 ?

**Comment by leejt489** [comment]
From my understanding, `res.ok()` only takes a json object.  The JSON API spec requires that the response put the data under the key [model name], as in `{post: {...}}` or {posts: [{...},{...}]}`, which requires passing some metadata about the model.  Additional customizations such as sideloading relationships also requires model metadata.  So one way or another just using `res.ok()` doesn't enable a clean way for to customize the response.  Currently it is necessary to override blueprints or update all controller actions.  Generators or libraries like https://github.com/mphasize/sails-ember-blueprints make this easier, but the problem I see there is that it could make the application more difficult to maintain; namely by overriding blueprints, the burden of ensuring all of the rest of the code in the blueprints shifts to the developer (every time I update sails I manually go in and check to see if anything has changed in the blueprints).  Probably not the most critical issue, but I think it could be improved.
