### ISSUE TITLE
how to use 'populate where' in route

### ISSUE THREAD

**Issue by shanelau** [balderdashy/sails#2392]
I have two model `User` and `address` ,  it is One to Many

Use route `/use`  ,The result is the list of User contain address like below.

```
{
"address": [
{
"city": "zh",
"detail": null,
"owner": 7,
"id": 4,
}
],
"name": "刘兴",
"password": null,
"email": "12322@qq.com",
"id": 7,
"createdAt": "2014-11-12T09:43:15.000Z",
"updatedAt": "2014-11-12T09:43:53.000Z"
}
```
But ,I need to disable config `blueprints.js` 
```
populate: false,
```

So, req route become `http://localhost:1337/user/?populate=address`
**The result is exact**

But, I want get the users what's address attr  {city:'changsha'}

```
User.find({name: 'mx'}).populate('address',{city:'changsha'})
```

How can I release it the by edit route url ?

More than,  get the User's address list ,  address name equal `changsha`

**Comment by ralph-rush** [comment]
`/user/?populate=['address']`
