### ISSUE TITLE
Logging: framework should be quiet!

### ISSUE THREAD

**Issue by connor4312** [balderdashy/sails#2399]
Currently, sails is a very "loud" framework as far as logging goes. This is just fine for the console, but when in production we really _don't care_ about the nice long detailed explanations or recoverable, finicky errors like not being able to load cookie for the session. This is a special nuisance when using an aggregation tool like the wonderful [Sentry](https://getsentry.com/) and getting pages upon pages of "errors" like:

![](http://puu.sh/cPWwy/b769b6c57c.png)

Things like this happen... cookies get lost, mangled, corrupted. As developers we don't care about it, but the way Sails is set up they overshadow actual application errors and fill our inboxes with spam. Not to mention, the log levels seem entirely inappropriate. Why should we be "warned" that a client has to reconnect if someone has a shoddy connection or puts a computer to sleep? What are we to do about it?

To make it worse, there's no way of preventing these logs from coming in aside from registering an entirely new logger and forgoing Captian's Log altogether, just letting it flood past in the console.

It's my view that the framework should be "silent". Either:

 - Log these non-errors at a "verbose" level so that they can be filtered out.
 - Don't log any errors manually, let exceptions bubble up from unrecoverable situations until Winston's global exception handler can catch them. In production I think this is the best approach...
 - Or simply provide an easy way to filter out "framework" errors.

Thanks. Hopefully this can get resolved.

**Comment by loicsaintroch** [comment]
A lot of developers use pm2 or other tool for production with their own logging levels. Sails logging are good for development but when you want to move to production pm2 is the best tool you can have for managing all of it.
