### ISSUE TITLE
I18n doesn't work in each loop in Handlebars views

### ISSUE THREAD

**Issue by ignasbernotas** [balderdashy/sails#2402]
I love using handlebars and I've started using Sails.js which seems pretty awesome, however I've come across this issue (which is now closed for some reason): https://github.com/balderdashy/sails/issues/1798 handlebars loses context when using i18n within an each block e.g.
```javascript
{{#each posts}}
     {{ i18n type }} 
{{/each}}
```
I get the following error:

```javascript
{
  "message": "Missing helper: 'i18n'",
  "name": "Error"
}
```

I think it's an essential feature to have, since this works in EJS and other view engines. My current workaround is to register a view helper within config/views.js
```javascript
helpers: {
      t: function(text) {
          return sails.__(text);
      }
}
```
But this approach is buggy because i18n can't pull the locale from the UA and throws the following warning in the console:
**WARN: No locale found - check the context of the call to __(). Using en as current locale.**

**Comment by loicsaintroch** [comment]
Thank you for your help @websquared.

**Comment by RSSGergelyMunkacsy** [comment]
Is there any code changes for this issue, Or just @websquared helper the solution? Because I think it is not acceptable to insert a second parameter for every call.

**Comment by loicsaintroch** [comment]
Just the helper solution for now because we can't take care about every template engine on our side. But I'll be more than happy to merge a PR if you have a solution! The other solution is to write a PR for the Handlebars generators on their repositories.
