### ISSUE TITLE
req.session.save() doesn't save data sometime

### ISSUE THREAD

**Issue by giyyapan** [balderdashy/sails#2413]
Hi all.
I'm working on OAuth . 
I have two page , let's call them A and B.
In A page, user click OAuth log in button, page A will popup a new window and user do their OAuth stuffs in new window. After OAuth succeed, user browser will visit my page B,  witch is the callback page for OAuth, and in page B's controller,I have :

``` javascript
req.session.OAuthUserID =  xxx;
req.session.save();
```

In the meantime, page A will keep sending request to my server to check this OAuthUserID so that page A will know the user's OAuth log in has been succeed and to some stuff after that.
I use these codes to check:

``` javascript
if(req.session.OAuthUserID){
  res.json({user data});
}else{
  res.json( 'not log in' );
}
```

These codes works as expected most of the time,  but sometime (about once every 5 times) req.session.save() in B's controller just not save OAuthUserID into database (I've checked the database and there is the session record but no OAuthUserID fied), and of course, page A's request will keep getting 'not log in' response.

I'm now using cookies to store OAuthUserID as a workaround. But cookies is less secure then the session way.
I think this could be a bug, dose someone know what may cause this and how to fix it ?

Thanks for help :)

===UPDATE===

I've tried connect-mongo as adapter and default memory storage, both have this problem.
I don't know what exactly session.save() do but It just not saving any change sometime.

**Comment by kriceTK** [comment]
So our application is experiencing the exact same thing (Sails 0.9.16) we even tried wrapping all of our res.send's in req.session.save(function(err, status){res.send({data:data})}) and still sometimes it doesn't save. We debugged it right before the save and right after and its the same but as soon as a another request comes in (milliseconds later) it no longer has the most recent value. It is also not a race condition in our code because when we debug it we see the save happening before the call to get the value from the session.

We are using redis btw using sails-redis v 0.9

The flow is:
1. Send data to server
2. Save data on session (req.session.save)
3. On callback from the save do a res.send of the id of the data
4. On successful response client initiates a post with the id to get the data that was just saved on the session 
5. We get an error that it doesn't exist

Debugging:
1. We see the data come in
2. we see it saved to the session
3. right before the res.send we see it on the session (in the same function as the save)
4. When we view req.session it no longer has the data
5. We get the error

**Comment by lynxeyedua** [comment]
We had the same issue in 0.11.x and 0.12.1 versions. When users tried to log in, they were pushed back and forced to enter their credentials more and more. This annoying bug had happend from time to time. 

After first look up, we have found that user object have saved session (or updated it) correctly, but in a moment later this changes were not present in next policies checkings. 

Then we digging more:
- Found how session initialized in sails(express) 'node_modules/sails/lib/hooks/http/middleware/defaults.js' session method.
- Enable debug for 'express-session' module by setting debug environment variable DEBUG=express-session (sails -> express -> express-session).
- Found that EVERY http request saves session a lot of times.
- When user pressed log in button, our app showed loading modal with image. Thus it sent TWO http requests: one sent form data other loaded extra image.
- Found that options 'saveUninitialized' and 'resave' for module 'express-session' were setted to true by default in sails (look defaults.js file). This means that on every http request session middleware force to save session even if there are no changes or it is empty.
- Add params 'saveUninitialized': false, and 'resave': false to config/session.js file or you can try to rewrite session middleware in config/http.js file somehow.
- Now it saves session only when it have any changes.

Not sure that it's correct solution nor that i understand the problem. Although seems it works and i hope it may help someone else.
[https://github.com/expressjs/session](url)

**Comment by apliasun** [comment]
@lynxeyedua  Oh, thanks it's really helpful for me. Actually it seems very strange to save session every time, (even if you don't have any changes).

**Comment by edencorbin** [comment]
Very old thread but I don't see much on req.session.save() in sails 1.0+ documentation. I'm nearly certain its all handled automatically with sails default session store. However, I have recently been using connect-pg-simple, and it looks like I have to manually save the session when I update it. I may need to dig into it's working better to understand it, but is this behavior expected?

**Comment by dizhar** [comment]
In the sails v 0.12.14:
Add the following parameters in the config/session.js file

module.exports.session = {


 'saveUninitialized': false,
  'resave': false 
}

**Comment by aishtiaq7** [comment]
Sessions are not persistent for me as well, I'm using MERN. 
When I console log session, I see it is saved in one route but again its undefined in another. For example its defined in my login api route however its undefined in my dashboard api. 
I've tried to use connet-mongo as the middleware for session persistency by adding the store value as `store: MongoStore` in my app.use(), but the problem still persists. 

To my understanding I believe mongo connect should handle the middleware to make the sessions data persistent, but somehow its not working for me. 
You can read more about the problem I'm taking about in this stackoverflow thread: 
https://stackoverflow.com/questions/72750194/session-data-still-not-persistent-between-routes-even-though-session-management

**Comment by salemalem** [comment]
Sessions are not saving at all
