### ISSUE TITLE
Multiple JSON encoding with socket.emit

### ISSUE THREAD

**Issue by Vadorequest** [balderdashy/sails#2416]
I've created a SO question and one of the answer seem to lead to a Sails unexpected behavior, would you mind to take a look?

http://stackoverflow.com/questions/26930297/serialize-object-through-network-with-javascript-how-to-improve-it/26930494?noredirect=1#comment42515028_26930494

if it is a sails unexpected behavior, could you tell me how to fix it?
Thanks.

**Comment by CWyrtzen** [comment]
I'm gonna close this up since there is discussion on SO. This is still searchable, of course and if you feel it should be reopened we can do that, too. Thanks~
