### ISSUE TITLE
regarding old issue

### ISSUE THREAD

**Issue by kfir124** [balderdashy/sails#2423]
Ive been looking at this issue 
https://github.com/balderdashy/sails/issues/352
It is one year old, and I wonder what is the current state of this feature request? It is pretty commln for me to block or limit access to attributes in models

Thanks in advance

**Comment by loicsaintroch** [comment]
We are working on closing issues, merging PRs and do some crazy stuff on Sails and Waterline right now. We take care of old issues. Sorry for the delay guys.
