### ISSUE TITLE
How to use Sails-disk and sails-mysql parallely and write Models

### ISSUE THREAD

**Issue by kgrvamsi** [balderdashy/sails#2426]
I was trying for a usecase in which my workflow is like i would like to save key-pair sort data into the a temp db file and the main app data into a mariadb.

So here the question(1)

How to make use of two adapters work at the same time?will this change work and make my models route to the sails-db which are required.

config/connection.js

localDiskDb: {
    adapter: 'sails-disk'
  },

  /***************************************************************************
  *                                                                          *
  * MySQL is the world's most popular relational database.                   *
  * http://en.wikipedia.org/wiki/MySQL                                       *
  *                                                                          *
  * Run: npm install sails-mysql                                             *
  *                                                                          *
  ***************************************************************************/
  mariadblServer: {
    adapter: 'sails-mysql',
    host: 'localhost',
    user: 'root',
    password: '-----------',
    database: 'dockerstack'
  }

config/models.js
  connection: ['mariadblServer','localDiskDb']

question(2)

Can i access the .db file with a sqllite library like gorm(https://github.com/jinzhu/gorm)?

Please help me out on how to use this scenario @mikermcneil

**Comment by CWyrtzen** [comment]
Did this make it over to SO? Can we close this up?
