### ISSUE TITLE
bootstrap.js runs after orm initializes

### ISSUE THREAD

**Issue by pr1ntr** [balderdashy/sails#2439]
While trying to use dotenv i noticed that the code in bootstrap.js runs after the orm inits. 

this creates a problem when trying to do this:

```
  mongoConnection: {
    adapter: 'sails-mongo',
    schema:true,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    user: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME

  }
```

I ended up putting dotenv in my app.js but then it wont work with sails lift.

**Comment by adiffmike** [comment]
So I'm a little unsure if hooks solves this problem.  

As stated the use-case here is to set database connection parameters. However the connections.js file gets loaded during the initial bootstrap of all the modules. I don't think there's a way to get the hook to load dotenv before the connections.js file.

I guess in theory you could use the hook to override specific config settings but thats a bit kludgy.

**Comment by javm** [comment]
@adiffmike I wrote the following code in my node_modules/sails/blob/master/lib/hooks/http/index.js
file:
var dotenv = require('dotenv');

dotenv._getKeysAndValuesFromEnvFilePath('/myPath/postgresql.env');
dotenv._setEnvs();

console.log(process.env);
and I get access to the process.env vars when config/connections.js is read.

**Comment by dcbartlett** [comment]
Is there a reason that we have bootstrap firing after hooks?  Should i just create a hook for bootstrapping now?
