### ISSUE TITLE
Blueprints

### ISSUE THREAD

**Issue by joaolucas89** [balderdashy/sails#2440]
I have a file in app/api/blueprints/find.js

This file uses the functions of the "find" global and implement some variables, such as paging, number of found records, etc.

How can I execute my find.js when Im acessing the url "users/1/cars" ?

And how can I put it optional? There is other urls in which I do not need paging, so I need q run the populate.js not the find.js

**Comment by CWyrtzen** [comment]
Hi @joaolucas89 did you find an answer to your question?

**Comment by joaolucas89** [comment]
No :'(

I just use another estrategy. But my idea is very good :D

**Comment by CWyrtzen** [comment]
Ok, we'll close it up and it will be here in search results as needed, thanks!
