### ISSUE TITLE
Grunt tasks should not be coupled to NODE_ENV

### ISSUE THREAD

**Issue by gblanck** [balderdashy/sails#2447]
When I deploy to my QA environment, I want to do so with concatenated and minified javascript and css. This is desirable because I want the testing that is occurring in that environment to be testing the code that will eventually be in production. 

If we launch the app with "sails lift", then the asset files are not concatenated or minified, but our environment variables are appropriately set.
If we launch the app with "sails lift --prod", then the asset files are concatenated and minified, however the environment is set to "production" and my environment should actually be "qa".

So a solution where we could, in the configuration file or in an environment variable, identify the grunt task to execute and use that task during the lift process, would be wonderful.

**Comment by loicsaintroch** [comment]
Closing this issue in favor of your PR. Thank you for your contribution @gblanck.
