### ISSUE TITLE
Blueprints doesn't support multiple sort

### ISSUE THREAD

**Issue by Dallas62** [balderdashy/sails#2449]
Hi!

Actualiy, blueprints doesn't parse `sort` argument as json or by splitting string,
so we can't do something like:
`/model/?sort=foo ASC, bar DESC`
`/model/?sort=[ 'foo ASC', 'bar DESC']`
`/model/?sort={ 'foo': 'ASC', 'bar': 'DESC'}`
`/model/?sort={ 'foo': 1, 'bar': 0}`

His there any purpose to do it well?
Maybe a PR soon.

**Comment by sgress454** [comment]
Good idea @Dallas62.  Added support for JSON sort options in https://github.com/balderdashy/sails/commit/636284e7ebe0382c9fc5e335333de22a58135b99

Note it must be proper JSON (with double-quotes) for it to work.

**Comment by sgress454** [comment]
Somehow missed that you had a PR to do this exact thing.  Sorry about that, wasn't intentional.
