### ISSUE TITLE
Populate associations policy

### ISSUE THREAD

**Issue by dottodot** [balderdashy/sails#2460]
If for example you have a many to many association, is there a way that when you use populate you can assign a policy so the user will only see entries that say belong to them?

In my example I have 2 models Artists and Bookings. All artists are viewable by everyone, but bookings should only be visible by the user that created it.

Artist.js
```
module.exports = {
  attributes: {
    name: 'STRING',
    bookings: {
      collection: 'booking',
      via: 'artists'
    }
  }
};
``` 
Booking.js
```
module.exports = {
  attributes: {
    title: 'STRING',
    artists: {
      collection: 'artist',
      via: 'bookings'
    }
  }
};
```
So if I did the following you'd see all the bookings related to the artist and I'm unsure what the best approach is for only showing the bookings for the current user.
```
Artist.findOne(id).populate('bookings').exec(function(err, artist){
  res.send(artist);
});
```

**Comment by erkstruwe** [comment]
You can filter the populate by using `Artist.findOne(id).populate('bookings', {user: req.session.user})`. This is just an example. You need to know where to get the current user from. This is not really an issue and should be closed.
