### ISSUE TITLE
Implement services loading from subfolders

### ISSUE THREAD

**Issue by ghaiklor** [balderdashy/sails#2464]
Hi everyone.

I have issue when working with many services. I saw service loader in sails source and find that service loader doesn't support loading from sub folders.

```javascript
loadServices: function (cb) {
      buildDictionary.optional({
        dirname     : sails.config.paths.services,
        filter      : /(.+)\.(js|coffee|litcoffee)$/,
        depth     : 1,
        caseSensitive : true
      }, cb);
    },
```

But when you have big codebase in project it became headache because too many files located under one directory. Some services can be grouped in one sub folder, some else in another sub folder. So will be great if sails supports loading services from subfolders.

What you think?

**Comment by loicsaintroch** [comment]
@sgress454 is working on a `subapps` hooks that loads API and config from `node_modules` or other directories. So, you have two different options: use this hook or override the default `moduleloader`

**Comment by irobayna** [comment]
@ghaiklor Did you ever find a good answer on this?  I too would like to store services in subfolders

**Comment by loicsaintroch** [comment]
Sure, there it is: https://github.com/balderdashy/sails-hook-subapps

**Comment by ghaiklor** [comment]
@irobayna I'm using this workaround :smiley: 

```javascript
// api/services/some/module.js
module.exports = {};

// api/services/SomeService.js
var subModule = require('some/module.js');
```

**Comment by irobayna** [comment]
@ghaiklor thanks for the feedback, interesting solution.
I am not sure I like having to create the ```fake``` service as we are going to have lots of services.  And could be somewhat of a PIA to do the double typing.

Check out this, just as an FYI... just ran a quick test and it this seems to work well
https://github.com/balderdashy/sails/issues/2181 (check my comment)

**Comment by irobayna** [comment]
@loicsaintroch Thanks!, I don't want to load a sub app but rather divide my services up as we will have potentially hundreds and we thought it would be a cleaner approach.

**Comment by ghaiklor** [comment]
@irobayna This is not `fake` service. Let's say you have different ciphers and you need work with them. Here the solution how to split it to subfolders.

```javascript
// api/services/cipher/bcrypt.js
module.exports = {
    hash: function(data) {}
};
```

Then lets add whirlpool cipher:
```javascript
// api/services/cipher/whirlpool.js
module.exports = {
    hash: function(data) {}
};
```

So each module is split and located under sub-folders. It can be whatever you want: class, function, object, just make sure that you have `module.exports`.

And then create in `api/services` file named as you want, for instance `Ciphers`.
```javascript
// api/services/Ciphers.js
module.exports = {
    bcrypt: require('./cipher/bcrypt'),
    whirlpool: require('./cipher/whirlpool')
};
```

And then you can use it like this `Ciphers.bcrypt,hash('password')`. I hope you got the idea :smiley: 

I'm using services as Factory classes which create appropriate instance from sub folder. Here example from my yeoman generator - https://github.com/ghaiklor/generator-sails-rest-api/tree/dev/generators/app/templates/api/services

**Comment by irobayna** [comment]
@ghaiklor Thanks!! makes way more sense now.  Pretty cool solution!

**Comment by sgress454** [comment]
Couple of points here:

1. The reason that services are explicitly set to `depth: 1` is that people often have a `lib` or `helper` folder underneath `api/services` which they use to store support files that shouldn't be globalized
2. Remember that the globalizing of services (and models) is purely for convenience--there's nothing wrong with `require('../services/cipher/whirlpool.js')` in your controller code.

@ghaiklor you have a nice, elegant solution to the issue there that allows for easy modularization without hacking the moduleloader--good job!

**Comment by ghaiklor** [comment]
@sgress454 Thanks :smiley:  but I'm still thinking about creating Mediator which will register\unregister services. Because exposing all files from `api/services` to global can be dangerous. So I want to create one global variable like `Services` which have `register()` method. And store all services there without exposing them to global.

**Comment by Tronix117** [comment]
For those who would like this feature anyway, just put the following in `api/hooks/serviceLoader.coffee`
(Use CoffeeScript website to convert it to JS if needed, but it should work as it is)

It will expose the `api/services/DataServices/Config.coffee` file as:
* `sails.services.dataservices.config`
* `DataServices.Config` if `sails.config.globals.services` is enabled

    buildDictionary = require 'sails-build-dictionary'

    class ServiceLoader

      constructor: (sails)->
        @sails = sails

      initialize: (cb)->
        @sails.log.info 'Service Initialize'
        @cb = cb
        @loadServices()

      loadServices: ->
        buildDictionary.optional {
          dirname     : @sails.config.paths.services
          filter      : /(.+)\.(js|coffee|litcoffee)$/
          caseSensitive : true
          flattenDirectories: true
          keepDirectoryPath: true
        }, @bindToSails

      bindToSails: (err, modules)=>
        if err
          @sails.log.error 'Error occurred loading modules ::'
          @sails.log.error err
          return @cb()

        @sails.log.verbose 'Loading nested app services...'

        _.each modules, (module)=>
          # Root Services are already loaded by `moduleloader`
          return if -1 is module.identity.indexOf '/'
          module.sails = @sails
          _.bindAll(module)

          @loadModule module

        @cb()

      loadModule: (module)->
        iParts = module.identity.split('/')
        gParts = module.globalId.split('/')

        sRoot = @sails.services
        gRoot = global

        while iParts[1]
          iPart = iParts.shift()

          sRoot[iPart] = {} if not sRoot[iPart]
          sRoot = sRoot[iPart] or (sRoot[iPart] = {})

          if @sails.config.globals.services
            gPart = gParts.shift()
            gRoot = gRoot[gPart] or (gRoot[gPart] = {})

        sRoot[iParts[0]] = module
        gRoot[gParts[0]] = module if @sails.config.globals.services

        module.identity = module.identity.replace /\//, '.'
        module.globalId = module.globalId.replace /\//, '.'
        
    module.exports = (sails)->
      return initialize: (cb)-> 
        sails.after 'hook:moduleloader:loaded', ->
          (new ServiceLoader(sails)).initialize(cb)

**Comment by mikermcneil** [comment]
@Tronix117 thanks for posting your solution!  This is precisely the kind of stuff the hook system was designed to support.  As much as possible, we're hoping to keep core out of your way and expose the APIs you need to customize Sails in pretty much any way you want.

**Comment by Nick2324** [comment]
@ghaiklor does this work to you in controllers? I cannot require my service module in my controller. I've tried to use 

../service/path-to-my-service/MyService.js
../../../(as many times as folders till meet api root)/service/path-to-my-service/MyService.js
path-to-my-service/MyService.js 

and none of them simply work
