### ISSUE TITLE
batch delete with waterline?

### ISSUE THREAD

**Issue by hybrisCole** [balderdashy/sails#2469]
is this possible? like sending an id array to Model.destroy();

Regards

**Comment by sgress454** [comment]
`destroy` uses the same [Waterline query language](http://sailsjs.org/#/documentation/concepts/ORM/Querylanguage.html) as the rest of the model methods.  If you want to batch delete models by ID, set the `id` criteria to an array:

```
Model.destroy({id: [array of ids]}).exec(...);
```
