### ISSUE TITLE
[Question] Better way to implement blueprint prefix configuration.

### ISSUE THREAD

**Issue by konstantinzolotarev** [balderdashy/sails#2473]
Hello. 
I want to enchase blueprint configs a little and add an ability to set prefix for rest actions. 

For now we have `prefix` option into [blueprint config](http://sailsjs.org/#/documentation/reference/sails.config/sails.config.blueprints.html) but it set prefix for all blueprint actions including controller.action, shortcuts and rest.

But In my application I need to be able to use controller.action without any prefix but RESTful routes should be prefixed with `/api/` prefix. 

I could add a new option named `restPrefix` with same logic as `prefix` but only for RESTful routes.  But if someone will use both of this options. for example: 

```javascript
module.exports.blueprints = {
  prefix: '/prefix',
  restPrefix: '/api'
}
```

How should application route this ? 
Should all RESTful routes be accessible via `/api/...` or it should be accessible  via `/prefix/api/...` ?

**Comment by kyle-schmidt** [comment]
@konstantinzolotarev this isn't working properly on Windows as path.normalize converts / into \ on Windows, making the routes not work correctly.  Works great otherwise.

**Comment by konstantinzolotarev** [comment]
@kyle-schmidt Fix is there. waiting for merge.
https://github.com/balderdashy/sails/pull/2666
