### ISSUE TITLE
Base URL with appended 'directory'

### ISSUE THREAD

**Issue by robgrimball** [balderdashy/sails#2477]
We have a situation where we have our app being basically hosted via nginx to a specific single server configuration.  This server configuration is using 'locations' to shuttle off to various other applications.

What we basically have is this, a sails app hosted at https://somenginx.com:9999/sailsapp which points to (via a proxy_pass) https://localhost:1337

The problem is, all the links/resources/etc that are being requested subsequent to that initial page are not using the /sailsapp part as their base URL.  

Does anyone know of a way to get sails to add this to the base URL?  I tried putting in a proxyHost and proxyPort (even using "9999/sailsapp" as the proxyPort out of despeartion), but I haven't found a way to do this yet.  

Thanks for any help!

**Comment by tjwebb** [comment]
I think this should be solved in front of node; e.g. you should be hosting node behind nginx or apache anyway; those will have more robust URL rewrite features available.
