### ISSUE TITLE
Add support for dotenv, allowing reading of project specific environment variables from a .env file

### ISSUE THREAD

**Issue by davesag** [balderdashy/sails#2481]
I've been trying to add support for [dotenv](https://github.com/motdotla/dotenv) to my Sails project but it really needs to be run sooner in the startup process than `config/bootstrap.js` 

Adding

```
  var dotenv = require('dotenv')
  dotenv.load()
```

to `sails.lift()` makes the most sense to me.

**Comment by sgress454** [comment]
I doubt this will make it into core, but you can always add it to your `app.js` file!

**Comment by aug-riedinger** [comment]
Putting it in `app.js` doesn't load the environment variables when opening the console...
