### ISSUE TITLE
Socket subscribe events do not call toJSON

### ISSUE THREAD

**Issue by nickeddy** [balderdashy/sails#2484]
I'm using sails v0.10.5, and subscribing on model events that have a toJSON seem to indicate that the toJSON is only called for blueprint update actions (see https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actions/update.js#L72 - this is the only spot I could find to do with pubsub that calls toJSON).
I'm pretty sure this isn't expected behavior, but maybe I'm wrong? Why would only updates send back a message with toJSON invoked, but nothing else does?

**Comment by tjwebb** [comment]
@nickeddy Would you mind submitted your PR? We can work with you more easily from there to get some tests in.

**Comment by nickeddy** [comment]
Submitted the PR for you @tjwebb. Let me know if you need anything else.
