### ISSUE TITLE
How to change the default path of view files?

### ISSUE THREAD

**Issue by lolenko** [balderdashy/sails#2489]
next code in config directory does not reinit views path

      module.exports.paths = {
        views: __dirname + '/../views/pages'
      }

**Comment by sgress454** [comment]
See [this StackOverflow question](http://stackoverflow.com/questions/27453064/how-to-change-the-default-path-of-view-files-in-a-sails) (in general this is the place for support questions; the Github issues forum is for reporting bugs in core).  @Josebaseba's solution above is the correct one.
