### ISSUE TITLE
Websocket url undefined 

### ISSUE THREAD

**Issue by Nishchit14** [balderdashy/sails#2492]
I am using sails 0.10.5 and in angular frontend with angular-sails .

It gives an error like below on server side Whenever an api call by $sails.get

<pre>
error: Error: 
res.redirect() :: [socket.io] ::
Cannot redirect socket to invalid location :: 'ws://www.undefinedhttp://192.168.1.191:1337/admin/v1/users/subscribe'
    at Object.Err.invalidRedirect (C:\wamp\www\i-phone\i-phone\node_modules\sails\lib\hooks\sockets\lib\interpreter\interpret.js:33:14)
    at ResStream.doRedirect (C:\wamp\www\i-phone\i-phone\node_modules\sails\lib\hooks\sockets\lib\interpreter\interpret.js:310:31)
    at C:\wamp\www\i-phone\i-phone\node_modules\sails\lib\hooks\sockets\lib\interpreter\saveSessionAndThen.js:23:7
    at C:\wamp\www\i-phone\i-phone\node_modules\sails\lib\hooks\session\index.js:59:17
    at C:\wamp\www\i-phone\i-phone\node_modules\connect-mongo\lib\connect-mongo.js:269:25
</pre>

My stackoverflow question is http://stackoverflow.com/q/27498291/2837412

**Comment by Dallas62** [comment]
Hi,

Solve on stackoverflow.

@sgress454 can be closed.
