### ISSUE TITLE
afterUpdate fires multiple times

### ISSUE THREAD

**Issue by dottodot** [balderdashy/sails#2503]
I have noticed that afterUpdate on one of my models is firing 4 times and I can't understand why this is happening. Could it be anything to do with the associations I have on that model?

**Comment by tjwebb** [comment]
superseded by #2735

**Comment by aboveyou00** [comment]
The referenced issue has nothing to do with this...

**Comment by RWOverdijk** [comment]
@aboveyou00 The reason is the way these get triggered. When you're using associations, the id gets updated multiple times. I made a PR for that here https://github.com/balderdashy/waterline/pull/1048 a while ago
