### ISSUE TITLE
consider warning/erroring if the user passes invalid configuration keys

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/sails#2507]
say I am writing a script and mistype the command `{"models": {"migrate": "safe"}}` as `{models: {mode: "safe"}}` and the default I have is to run "alter", suddenly I'm running a migration/altering the database when I didn't want to. 

given the schema-less nature of configuration objects, this type of mistake is easy to make & easy to miss when you're trying to debug. it would be nice if sails warned about invalid keys.

**Comment by RWOverdijk** [comment]
@kevinburke You can't (shouldn't) expect sails to limit the options you can set on any configuration object. It's your job to make sure it's set to what it should be.

Always default to the safest option. **Don't set your default to alter**, that's asking for it. In stead, set it to safe, and specify the mode in `local.js` to your liking. I'd recommend setting it to `safe` in `config/local.js.dist` as well, and changing it to `alter` on your development machine.

**Comment by sgress454** [comment]
Also note that `safe` is the default for the production environment; in development the assumption is that your data is not sacred.  If your situation is different, then definitely do as @RWOverdijk suggests and set your default to `safe`!
