### ISSUE TITLE
IcedCoffeeScript pull request?

### ISSUE THREAD

**Issue by internalfx** [balderdashy/sails#2513]
Is support for IcedCoffeeScript something you would consider?

I have modified `lib/hooks/moduleloader/index.js` to support `iced-coffee-script`...

I was wondering if the community would be interested in a pull request to make this part of core.

**Comment by loicsaintroch** [comment]
Yes we are interested in a IcedCoffeeScript support. We'll be glad to merge your pull request. Thank you for your idea @internalfx.
