### ISSUE TITLE
Can I downgrade socket.io to 0.9.x?

### ISSUE THREAD

**Issue by TangMonk** [balderdashy/sails#2516]
Because the [Object-C Socket.io client for socket.io 1.0](https://github.com/MegaBits/SIOSocket) is not stable.
I prefer to use the [Object-C Socket.io client for socket.io 0.9](https://github.com/pkyeck/socket.IO-objc)

**Comment by sgress454** [comment]
Socket.io 1.0 support was one of the major feature requests for Sails v0.11.x, requiring some significant alterations to the core.  If you want to stick with socket.io v0.9.x, I would suggest not upgrading to Sails v0.11.x.
