### ISSUE TITLE
Use webpack instead of sails-linker?

### ISSUE THREAD

**Issue by andyhu** [balderdashy/sails#2518]
IMO webpack is much more advanced and convenient than sails-linker. Is it any possibility to replace sails-linker with webpack in the future version of sails? Any thoughts?

**Comment by CWyrtzen** [comment]
Thanks for bringing this up, sorry it didn't generate discussion at this time. I am going to close it as an "issue" but it is marked and searchable with a "feature" label, it can be reopened at any time, and new discussion is always welcome~
