### ISSUE TITLE
 How to give a name to a collection (generated automatically when we map many to many relationship)?

### ISSUE THREAD

**Issue by mahendrabagul** [balderdashy/sails#2527]
Hi,

I am new to Sails js. I was trying for Customer and Account relationship(Many to Many).
I am able to create relationship between them. The joined collection which gets created when I insert first record, takes 'modelname1_attributename_ modelname2_attributename.

Can we give custom name to it as it will be easy to work with it further?.

I come from JAVA and Hibernate background and there is annotation in Hibernate which does the task I want. 

Please help me to sort out this problem.

**Comment by sgress454** [comment]
Hi @mahendrabagul, thanks for using Sails! This forum is for reporting bugs in the Sails core. In the future, for feature requests, please read our feature request guide. For support queries, please post on StackOverflow or in our Google Group.

--

As for your specific question, please see [this StackOverflow question](http://stackoverflow.com/questions/23795389/one-to-many-associations-using-existing-join-table/23819001#23819001)!
