### ISSUE TITLE
Allow policies for actions on all controllers

### ISSUE THREAD

**Issue by ProLoser** [balderdashy/sails#2528]
Right now there's either a `'*'` globally for every action and controller, a `controller: { '*' }` for all actions in one controller and `controller: { 'action' }`. Why is there no way to specify policies for any controller but a specific action?

```js
module.exports.policies = {
    // Default policy for all controllers and actions
    '*':                ['authenticated'],
    // example global action
    'create':           ['authenticated', 'createdByUser'],
    'update':           ['authenticated', 'updatedByUser'],
    'destroy':          ['authenticated', 'isCreator'],

    // alternative global action declaration
    '*': {
        '*':           ['authenticated'],
        'create':      ['authenticated', 'createdByUser'],
        'update':      ['authenticated', 'updatedByUser'],
        'destroy':     ['authenticated', 'isCreator']
    }
};
```

**Comment by sgress454** [comment]
Interesting.  It honestly hasn't come up before, but feel free to make a PR to [our roadmap](https://github.com/balderdashy/sails/blob/master/ROADMAP.md), or even better, a PR implementing this feature, and we'll be happy to take a look at it!
