### ISSUE TITLE
Socket Client Error: "Transport unknown" when migrating to the  0.11.0-rc5 branch

### ISSUE THREAD

**Issue by Arsca** [balderdashy/sails#2529]
First of all, thanks for such a great framework! 

FYI:
I updated from 0.10.5 -> latest 0.11.0.rc5 branch an noticed that the migration doc does not clearly state that the transport option has also changed. So, if you get this error at your client side:

**{"code":0,"message":"Transport unknown"}**

this means that you should modify the config/socket.js  as follows: 
```javascript
transports: [
  'websocket',
  'htmlfile',
  'xhr-polling',
  'jsonp-polling'
  ]
```
to the following
```javascript
transports: [
  'websocket',
  'htmlfile', 
  'polling'
  ],
```

Regards,

**Comment by sgress454** [comment]
Hi @Arsca, thanks for pointing this out.  Actually the best thing to do if you don't actually have customizations in your `config/socket.js` file is to just comment it out entirely and let the Sails defaults do their magic :).  We'll take a look at how to word this in the migration guide.
