### ISSUE TITLE
cache ejs view

### ISSUE THREAD

**Issue by martingg88** [balderdashy/sails#2530]
anyone who know any nice/best method to cache the ejs view that its content is most on static one. 

Thanks.

**Comment by sgress454** [comment]
Hi @martingg88 , thanks for using Sails!  This forum is for reporting bugs in the Sails core.  For feature requests, please read our [feature request guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#requesting-features).  For support queries, please post on StackOverflow or in our [Google Group](https://groups.google.com/forum/#!forum/sailsjs).
