### ISSUE TITLE
Define global _hookTimeout

### ISSUE THREAD

**Issue by japel** [balderdashy/sails#2532]
On development environment, -at least when starting sails using webstorm in debug mode- the whole lifting process takes much more time than just lifting.
It would be awesome if there was a way to define a global _hookTimeout for all hooks and don't have to define it for every single one to be able to easily switch between dev/test/prod envs.

Best regards,

Jan

**Comment by sgress454** [comment]
Hi @japel, thanks for reaching out.  Agreed that this would be a good feaure--added to [roadmap](https://github.com/balderdashy/sails/blob/master/ROADMAP.md).
