### ISSUE TITLE
models.js migrate setting of 'alter' takes many minutes to complete on large tables, hanging `sails console` for that long - this should at least be documented.

### ISSUE THREAD

**Issue by chr15m** [balderdashy/sails#2534]

**Comment by sgress454** [comment]
From [the `sails-disk` README](https://github.com/balderdashy/sails-disk):

> A local disk adapter for the Sails framework and Waterline ORM. Functions as a persistent object store which works great as a bundled, starter database (with the strict caveat that it is for non-production use only).

`sails-disk` is not optimized in any way and is not intended to process huge amounts of data.  Once you have your schema pretty stable, it's a good idea to start developing against whatever database you plan on using in production.  In the meantime, you can always use `migrate: safe` to speed things up, and only switch to `alter` when you actually do a schema change.

**Comment by chr15m** [comment]
Hello! We are not using sails-disk. We are using sails-mongo and the sails console still hangs without telling us what is going on because we have a large data set. Enjoy my pull request on sails-docs.
