### ISSUE TITLE
Selectable themes

### ISSUE THREAD

**Issue by pyrokinetiq** [balderdashy/sails#2536]
I can't seem to find any easy way to globally prefix views/assets paths with a variable. I'm trying to implement a theming system in my application, which essentially would function like Sails naturally does except the contents of `views`, `assets` etc. will live in a second level directory of the theme name. For example, a default theme would use `/views/default/layout.ejs`, a clean theme would use `/views/clean/layout.ejs` and so on.

I've tried setting a `global.theme = 'default'` in `config/bootstrap.js` yet this variable seems to be unavailable later on such as in `config/routes.js` (trying to set the `/` route to use `global.theme + '/homepage'`).

Any suggestions on how I could achieve this with Sails would be appreciated.

**Comment by sgress454** [comment]
Hi @pyrokinetiq , thanks for using Sails! Just FYI this forum is for reporting bugs in the Sails core. In the future, please post support queries on StackOverflow or in our Google Group.

---

You probably don't want to implement this by modifying your `config/routes.js` file; instead, in your controller actions, use the theme name in your call to `res.view`, e.g. `res.view(req.session.theme + '/someView', {theme: req.session.theme})`.  Then in the view itself, use `<%= theme %>` to prefix paths to assets.

**Comment by pyrokinetiq** [comment]
Hi @sgress454, while that solution would work (and I did implement that prior to reading your post), it doesn't allow one to keep their code DRY as they would have to have every single controller do a check for the selected theme, and every call to `res.view()` will need to account for this. I was hoping for a way to do it once and have the theme's path prefixed to any `res.view()` calls.

I intended this to be more of a feature request for sails, though I understand how it would have been interpreted as me just asking for help on how to implement this in my own project, the feature I'm requesting being the ability to set a global prefix for the paths used by the view engine.

I'm not sure if Sails allows for some kind of output buffering, if it does then one could leverage this to scan for paths in the compiled view HTML and prepend a prefix to said paths  before sending the response to the client.

**Comment by sgress454** [comment]
You can also use [custom responses](http://sailsjs.org/#/documentation/concepts/Custom-Responses) for this--so instead of `res.view`, you could do `res.theme` (for example) which would automatically display the desired view with the theme prefix.  This would be a little less repetitious.

**Comment by pyrokinetiq** [comment]
Awesome, that's exactly what I was after, thanks! I should probably read the docs more often, I don't think I've looked at them since I was using Sails `0.9.x`.

**Comment by RubensTen** [comment]
Greetings, I try to do the same
@pyrokinetiq  What was your solution?
