### ISSUE TITLE
A feature to reload config

### ISSUE THREAD

**Issue by parnurzeal** [balderdashy/sails#2537]
Hi, 
I think all sails.config are loaded in when starting sails app.
I am now creating my own config file under config folder and wish to reload it if someone make a change or reload it without restarting.

Would it be nice to have this feature?

**Comment by sgress454** [comment]
This sounds like a great idea for a hook (aka Sails plugin).  The upcoming v0.11.x has greater support for installable hooks.  You can poke around in the docs [here](https://github.com/balderdashy/sails-docs/tree/v0.11/concepts/extending-sails/Hooks), and see an example of a similar hook [here](https://github.com/sgress454/sails-hook-autoreload) that reloads the ORM when API files are changed.  Have fun, and if you come up with something useful make sure to announce it in the [Google Group](https://groups.google.com/forum/#!forum/sailsjs)!
