### ISSUE TITLE
Ubuntu - Controller Action default view path incorrect

### ISSUE THREAD

**Issue by Nitemaeric** [balderdashy/sails#2545]
Sails Version: 0.10.5
Problem: Ubuntu is requesting lowercased string names for all default views for actions.

Controller:

```
{
    action: function(req, res){
        res.view({ a: 10, b: "Hello World"});
    },

    actionNumberTwo: function(req, res){
        res.view({ a: 15, b: "Hello Action 2"});
    }
}
```

'action' will perform perfectly. 'actionNumberTwo', for some reason on Ubuntu, will request the view named: 'actionnumbertwo.ejs'...

This definitely feels like an issue to me. But if I'm oblivious to something, I apologise.

There is a simple workaround to it, I'm just worried no one knows about the issue.

**Comment by sgress454** [comment]
Sails always lowercases the action names internally; it's not an Ubuntu thing.  My guess is that you have your Ubuntu filesystem set up to be case-sensitive.  The workaround, which it sounds like you've probably already discovered, is to just have those view filenames be lowercased as well!

**Comment by Nitemaeric** [comment]
Oh thanks. I'm developing on a Mac and have now learned that Mac's filesystem isnt case-sensitive. Thanks for the information. :+1:
