### ISSUE TITLE
Coffeescript Support

### ISSUE THREAD

**Issue by sayanriju** [balderdashy/sails#2546]
Just did the following to get Sails to work with Coffeescript:

```bash
$ sails -v
0.10.5
$ sails new testProject --coffee 
$ cd testProject
$ sails generate api test
error: Error: Generator Error: Failed to load "sails-generate-model-coffee"... (Error: Cannot find module '/tmp/test/node_modules/sails-generate-model-coffee')
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:264:7)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:647:13)
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:651:23
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:47:16
    at parseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:192:16)
    at tryToParseTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:44:7)
    at Object.async.until (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:647:13)
    at generateTarget (/usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/target.js:39:9)
    at /usr/local/lib/node_modules/sails/node_modules/sails-generate/lib/generate.js:143:15
 [Error: Generator Error: Failed to load "sails-generate-model-coffee"... 
 (Error: Cannot find module '/tmp/testProject/node_modules/sails-generate-model-coffee')]

$ npm install --save sails-generate-model-coffee
$ npm install --save sails-generate-controller-coffee
$ sails generate model test method1 method2 method3
$ sails generate controller test method1 method2 method3
$ sails lift
info: Starting app...


/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:216
      throw helpers.updateSyntaxError(err, stripped, filename);
                    ^
/tmp/testProject/api/models/Test.coffee:11:17: error: unexpected indentation
        method1:
```

Everything _almost_ worked as expected.
**BUG** Noticed: In api/models/Test.coffee, the line containing 'method1' has TWO extra levels of indentation, which obviously doesn't compile as valid coffeescript. If I manually change that, sails lifts just fine. 

Another suggestion, maybe when creating new project with the --coffee flag, package.json should already include the two required modules sails-generate-model-coffee & sails-generate-controller-coffee, so that a _npm install_ should be enough to get going!

**Comment by sgress454** [comment]
@sayanriju, thanks for pointing this out.  Sounds like maybe an issue in `sails-generate-model-coffee`?

**Comment by sayanriju** [comment]
@sgress454 Yes indeed. I've already made a pull request to ```sails-generate-model-coffee``` repo: https://github.com/nyamadori/sails-generate-model-coffee/pull/1
Apparently, it was a minor fix.

Another question, ain't ```sails-generate-model-coffee``` _official_ part of sails?

**Comment by sgress454** [comment]
> Another question, ain't sails-generate-model-coffee official part of sails?

Kinda sorta--there's built-in support for calling the generator when `--coffee` is used on the command line, but the generator itself is not maintained by the core team.
