### ISSUE TITLE
i give up :(

### ISSUE THREAD

**Issue by ralph-rush** [balderdashy/sails#2549]
sails is good but waterline is ugly
nothing works in waterline, i tried mysql redis and cannot work with this
sails is not product for use in any scenario already
i dont know why people are so excited about
ther are so many bugs in waterline...
try many-to-many or many-to-many-through... nothing works
nightmare... 3 days spend to maybe fix some bugs but... there is bug after bug... this is tragedy :(

**Comment by leobudima** [comment]
This kind of commentary can be of some (rather limited) usefulness to others, but if you are not willing to invest time in properly reporting problems you encountered, so at least others (if not you) can potentially fix them, you're not doing anyone a service by writing in this form...

Sails / Waterline is indeed ugly in some parts, but it is also beautiful and powerful in others. If you want to have the good stuff Sails has that you can't find packaged like this elsewhere, you can either wait and hope some more mature project will do it, or help improve Sails.

You can help by spending a couple of minutes going through the issues list of Sails / Waterline and seeing if problems you encountered are already reported - and report them if not...

Good luck on your project, though, I hope you'll find a good and quick platform that suits you.

**Comment by ralph-rush** [comment]
if somebody tell me that i could not use orm relationship in some framework i will be happy becaouse of time i spent to making things happen
write somewhere with big letters that this is not yet version you can work with
this save time a lot of peaople it will be useful i think

**Comment by leobudima** [comment]
I agree with you that things that can (at least to some extent) be expected from a full-blown ORM and framework, and are not yet working fully in Sails / Waterline, should be noted in a prominent place.

It would help a lot of people get a better sense when deciding.

**Comment by ralph-rush** [comment]
Sails is the most popular MVC framework for Node.js. It is designed for building practical, **production-ready** Node.js apps in a matter of weeks - not months
:D:D:D

**Comment by sgress454** [comment]
@ralph-rush, sorry you had a bad experience.  The `sails-redis` adapter hasn't received as much attention as some of the others--as an open-source project, we tend to focus our time on the things that people are using the most--but that's a separate issue from Sails and Waterline in general which are pretty solid.  We're always looking for like-minded folks to take over development on the adapters, like @tjwebb has for [sails-postgresql](https://github.com/balderdashy/sails-postgresql).  In any case, thanks for reaching out, we'll try to have someone take a look at those issues with `sails-redis`.
