### ISSUE TITLE
Call findOne from controller results in error: syntax error at or near "undefined" 

### ISSUE THREAD

**Issue by danielgranat** [balderdashy/sails#2552]
I encountered this issue while creating a new controller, but this is not the first one i have created and never encountered it before.

The controller has an action to read a model from postgresql db.
This is how the controller looks like:
``` javascript
module.exports = {
	
	view: function(req, res) {
        var solutionToken = req.param('solutionToken');
        if( ! solutionToken ){
        	sails.log.warn("Missing argument for the solution token");
        	return res.send(400);
        }

        Solution.findOne({token: solutionToken}, function(err, solution){
        	if(err){
        		sails.log.error("Fail to get solution for: %s. error: %s",solutionToken,err);
        		return res.send(500);
        	}
        	if(!solution){
        		sails.log.warn("Fail to get solution for: %s",solutionToken);
        		return res.send(404);
        	}

        	return res.view('editor/review', {
                'token': solution.publicationToken,
                'solutionToken': solution.token
            });
        });
    },

    assessmentInfo: function(req,res){
    	var solutionToken = req.param('solutionToken');
        if( ! solutionToken ){
        	sails.log.warn("Missing argument for the solution token");
        	return res.send(400);
        }

        Solution.findOne({token: solutionToken}, function(err, solution){
        	if(err){
        		sails.log.error("Fail to get solution for: %s. error: %s",solutionToken,err);
        		return res.send(500);
        	}
                ...
       });
    }

};
```

Now the first methos 'view' works without any problems. The second one is called later from the client, the endup with the following error:
``` shell
error: Fail to get solution for: { token: 'FfPJDZ87QlLX' }. error: Error (E_UNKNOWN) :: Encountered an unexpected error
error: syntax error at or near "undefined"
  at [object Object].Connection.parseE (/home/daniel/dev/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
  at [object Object].Connection.parseMessage (/home/daniel/dev/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
  at Socket.<anonymous> (/home/daniel/dev/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)


Details:  error: syntax error at or near "undefined"

```
Other heaving the exact same code work in one method and not in another, i have wrapped the assessmentInfo code in a service, and called it from the controller, and directly from cli (using sails console). The controller call failed again and the direct call succeeded. 
Last try to understand better i changed from the using the passed parameter token and used hardcoded value. This time it worked from the controller, but that success left me confused as to what's the cause of this.

I am using sails 10.5,  running with nodejs 0.10.32.

What am i doing wrong?
Can you advice on how i can debug such an error (i am using node-inspector)?

**Comment by danielgranat** [comment]
Found the problem. I was sending the wrong post parameter. Instead of sending just the token value:
"FfPJDZ87QlLX"
I send:
{token: "FfPJDZ87QlLX"}

While i suspected it ws something to do with my code, the error really confused me and didn't help find it. 
Could i have found it faster?
Why did i get this- error: syntax error at or near "undefined"?

As far as i am concerned this can be closed, but i think it's better to try to address this error output.

**Comment by sgress454** [comment]
The error you're seeing is due to PostgreSQL trying to execute a bad SQL query; agreed that the message could be a bit more clear.  Feel free to post this in the [sails-postgresql](https://github.com/balderdashy/sails-postgresql) forum.

**Comment by kevinburke** [comment]
You can go further than improving the message though right? It's known at
query time that the query will fail; there's no need to wait for the
database to confirm this.


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com
