### ISSUE TITLE
Disable CRUD verbs

### ISSUE THREAD

**Issue by gotmikhail** [balderdashy/sails#2557]
Is there an option to disable specific verbs on a controller?

For example, let's say I have a `Comment` model w/ the `CommentController` and I want to allow `GET` and `POST`, but not allow `PUT` or `DELETE`. I understand I can disable `REST` routes altogether, either on the app or `controller` level and selectively define in `config/routes.js`, but it seems like it would be much better to be able to specify which verbs are used, not just an all or nothing approach.

**Comment by jacqueslareau** [comment]
You can control controller access through policies out of the box.

in api/config/policies.js:
```js
module.exports.policies = {
    'CommentController': {
        '*': false,
        find: true,
        findOne: true,
        create: true
    }
};
```

**Comment by randallmeeker** [comment]
Or just pop the action in your controller and return res.notFound(). It will override blueprints.

**Comment by sgress454** [comment]
@jacqueslareau @randallmeeker both excellent suggestions.  A third option is in your `config/routes.js`:

    "POST /comment": {response: "notFound"}

All of these are equally valid; the most important thing is to pick one method and stick to it so you're not searching three different places if something goes wrong :smile:

**Comment by randallmeeker** [comment]
@sgress454 I like your method the best. I did not know you could specify that response key in routes. Its the cleanest and is only one line!

**Comment by sgress454** [comment]
All sorts of gems tucked in the [custom routes documentation](http://sailsjs.org/#/documentation/concepts/Routes/RouteTargetSyntax.html?q=response-target-syntax)...
