### ISSUE TITLE
stable version

### ISSUE THREAD

**Issue by joaopereirasimoes** [balderdashy/sails#2558]
Hi guys, i know that maybe people has asked u this a lot of times however can u tell when will be a stable version of 0.11?

**Comment by Josebaseba** [comment]
I think that they will talk about that tomorrow -> https://plus.google.com/events/cejeiik709kvk9aeo7pqtg5embk

**Comment by Dallas62** [comment]
Close?

**Comment by loicsaintroch** [comment]
The v0.11 is stable and published on npm.
