### ISSUE TITLE
Model Validation against database

### ISSUE THREAD

**Issue by paragshar** [balderdashy/sails#2562]
I create a custom validation type like below to validate if the input category_id is a valid one or not: 
    
       module.exports = {
           types: {
                isValidCategoryId: function(id, cb){
                   return Category.findOne({id: id}).exec(function(err, user){
                       if(err || user)
                          return cb(false);
                      else{
                          return cb(true);
                      }  
                 });
              }
          },

          attributes: {
  	        category_id: {
                     isValidCategoryId: function(result){return result},
                     required : true
             },
          }

      }

The above code just hangs the script. 

How should I do model validations where certain attributes are to be checked for valid values against the db?

**Comment by Josebaseba** [comment]
I think that validations don't work with async methods.

Try this: 

```javascript
   module.exports = {
      attributes: {
        category_id: {
            required : true
         },
      },
      // that will be triggered in create and update actions
      beforeValidate: function(params, next){
         if(!params.category) return next();
         Category.findOne(params.category).exec(function(err, category){
            if(err || category) return next('custom error'); else return next();
         });
       }

    };
```

Check all the lifeCycleCallback here: http://sailsjs.org/#/documentation/concepts/ORM/Lifecyclecallbacks.html

**Comment by sgress454** [comment]
@Josebaseba is correct; custom validation functions must be synchronous.

**Comment by psi-4ward** [comment]
Heres a async subdocument valitation hack: https://github.com/balderdashy/sails/issues/314#issuecomment-70387544

probably the ugliest i've ever writte ;)
