### ISSUE TITLE
Pubsub event does not message listeners on manual model.update

### ISSUE THREAD

**Issue by andrewcarreiro** [balderdashy/sails#2563]
Pubsub fires to all listening clients in SailsJS when one POSTs data to http://localhost:1337/foo/1, but does not fire when one tries to update the model via code directly:

    Foo.update(1).exec(function(err,result){console.log(result);});

I've created a github repo with a fresh install of Sails and a single commit of my changes to illustrate the issue: https://github.com/andrewcarreiro/sails-pubsub-test/commit/4213da374f364ff91e586f57d21a2536b1dbf09b

I'd like to know if this is intentional, a bug, or if I'm doing something incorrectly.

Thanks!

**Comment by Dallas62** [comment]
Hi!

You have to publish the update with .publishUpdate() method:

refer to: http://sailsjs.org/#/documentation/reference/websockets/resourceful-pubsub/publishUpdate.html

**Comment by andrewcarreiro** [comment]
Thanks, @Dallas62! That looks correct to me.
