### ISSUE TITLE
disable autoCreateAt/autoUpdateAt as default

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#2564]
it is very weird to have all the table defined with autoCreateAt: false, and autoUpdateAt: false.
when i need it , i just turn it on.
if it is not need, it should not bother.

**Comment by Dallas62** [comment]
Hi,

What happen if you put `autoCreateAt: false` and `autoUpdateAt: false` in `config/connections.js`?

refer to: http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html

**Comment by sgress454** [comment]
Actually, the correct place to do this would be in `config/models.js`--settings from `sails.config.models` are used as the default for all models.
