### ISSUE TITLE
JWT (Json web token) with sails

### ISSUE THREAD

**Issue by rickdana** [balderdashy/sails#2565]
Hello everyone, 
Please does somebody knows any tutorial on how to use JWT (Json web token) with sailsJs?

**Comment by Josebaseba** [comment]
Check this: http://waterlock.ninja/

https://github.com/waterlock/waterlock

**Comment by psi-4ward** [comment]
Heres my solution with socket-support BUT theres no expire time yet!

**Comment by sgress454** [comment]
Thanks @Josebaseba @psi-4ward!
@rickdana, in the future try [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat](https://gitter.im/balderdashy/sails) for support questions--we try to keep this forum strictly for bug reports on the Sails core.
