### ISSUE TITLE
Can I make multi update with "where"  ?

### ISSUE THREAD

**Issue by bahout** [balderdashy/sails#2569]
For example a PUT like:
PUT : http://localhost:1337/api/test?where={"age":30}
with params: {age: 27}

thanks.

**Comment by Dallas62** [comment]
https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actions/update.js#L48

blueprints update only one record by request.

Add a specific action in the controller is the best way to do a multiple update.

(Or update one by one but it's ugly)

**Comment by sgress454** [comment]
@Dallas62 is correct; blueprint updates are by primary key, so just one record at a time.
