### ISSUE TITLE
Missing grunt-cli on sails 0.10.05

### ISSUE THREAD

**Issue by leosuncin** [balderdashy/sails#2575]
When I execute `sails lift --verbose` appear the next error, I already have installed globally *grunt*
```bash
error: Grunt :: module.js:340
    throw err;
          ^
Error: Cannot find module 'node_modules/sails/node_modules/grunt-cli/bin/grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```
To fix this, ``cd node_modules/sails && npm install grunt-cli && cd -``

**Comment by sgress454** [comment]
Hm, you may just have to `npm cache clean`; can't reproduce this and it hasn't been reported elsewhere.
