### ISSUE TITLE
How to disable express static middleware?

### ISSUE THREAD

**Issue by slavafomin** [balderdashy/sails#2578]
Hello!

I'm sorry for posting the question here, but still, is it possible to disable Express's static middleware?

There is a question on SO, but it's still has no answer:
http://stackoverflow.com/questions/27338521/disable-sails-js-static-asset-serving

I can't see this middleware in `http.middleware.order`, probably it's enabled internally somehow?

Thank you!

**Comment by sgress454** [comment]
Answered on SO.  The `www` middleware serves the static assets, and is documented on the [Sails Middleware page](http://sailsjs.org/#/documentation/concepts/Middleware).

**Comment by slavafomin** [comment]
Oh, sorry, my bad. I think I were just confused by the name )

Thank @sgress454 you for your great contribution and your help!

**Comment by gotmikhail** [comment]
It'd be nice if you could enable / disable specific middleware without having to overwrite everything.
