### ISSUE TITLE
Consider implementing controller- or ORM-level caching

### ISSUE THREAD

**Issue by secrettriangle** [balderdashy/sails#2579]

**Comment by randallmeeker** [comment]
+100

**Comment by mikermcneil** [comment]
I'm interested in integrating https://www.npmjs.com/package/cache-manager with https://github.com/node-machine/machine -- which then would make it easy for wl to leverage that (lets continue the discussion here: https://groups.google.com/forum/?hl=en#!forum/node-machine)
