### ISSUE TITLE
Asset Injection Per View

### ISSUE THREAD

**Issue by kdelmonte** [balderdashy/sails#2581]
Is there any way to specify a target view for asset injection?

I want to put the assets that I share between views in the layout but there are some other views where I only need certain assets that would not apply for the rest of the views. 

Is this doable?

**Comment by loicsaintroch** [comment]
Depends on your template engine but you probably can do it using partials if I understand correctly your question. GitHub issues are for issues about the framework. We try to keep it clean and focus, please use StackOverflow instead for this kind of question.
