### ISSUE TITLE
`bower install` has to be run before additional `sails lift` runs

### ISSUE THREAD

**Issue by paulmenzel** [balderdashy/sails#2582]
With Sails v0.10.5 and Grunt 0.4.5, running `sails lift`, quitting it and then running `sails lift` again, the following error shows up.

        $ sails lift

        info: Starting app...

        info:
        info:
        info:    Sails              <|
        info:    v0.10.5             |\
        info:                       /|.\
        info:                      / || \
        info:                    ,'  |'  \
        info:                 .-'.-==|/_--'
        info:                 `--'-------'
        info:    __---___--___---___--___---___--___
        info:  ____---___--___---___--___---___--___-__
        info:
        info: Server lifted in `/home/joey/myprojects/myawesomeproject`
        info: To see your app, visit http://localhost:1337
        info: To shut down Sails, press <CTRL> + C at any time.

        debug: --------------------------------------------------------
        debug: :: Fri Jan 23 2015 13:36:37 GMT+0100 (CET)

        debug: Environment : development
        debug: Port        : 1337
        debug: --------------------------------------------------------
        error:
        ------------------------------------------------------------------------
        Fatal error: Arguments to path.join must be strings
        Running "bower:install" (bower) task
        >> Cleaned target dir /home/joey/myprojects/myawesomeproject/assets/vendor
        ------------------------------------------------------------------------

        error: Looks like a Grunt error occurred--
        error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
        error: Or if you're stuck, check out the troubleshooting tips below.

        error: Troubleshooting tips:
        error:
        error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
        error:
        error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
        error:
        error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
        error:      e.g., `/home/joey/myprojects/myawesomeproject/.tmp` ?
        error:
        error:      If you think this might be the case, try running:
        error:      sudo chown -R 2222 /home/joey/myprojects/myawesomeproject/.tmp

Running `bower install` manually and then `sails lift` again, it works.

**Comment by sgress454** [comment]
This isn't an issue with the Sails core.  The default Grunt tasks are provided to get you started with a Sails project, but they can't be held accountable for things you add yourself, like running `bower install`!  Try Googling for `bower install arguments to path.join must be strings` and [see what you come up with](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bower%20install%20arguments%20to%20path.join%20must%20be%20strings).
