### ISSUE TITLE
sails 0.11.0-rc8: Models overwrite global names

### ISSUE THREAD

**Issue by pichlermi** [balderdashy/sails#2583]
I had a model named "File" that overloaded global.File and sails crashed when i used io.socket.get() in the client, because in ..../has-binary-data/index.js it uses  "instanceof File" and File is no longer a class( constructor function ) or undefined.

**Comment by sgress454** [comment]
It's [well documented](http://sailsjs.org/#/documentation/concepts/Globals) that Sails globalizes your models by default.  Sounds like your use case conflicts with Socket.io 1.0 in this case.  If renaming your model isn't an option, I'd suggest [turning off Sails globals](http://sailsjs.org/#/documentation/concepts/Globals?q=disabling-globals)--you can always re-globalize the other ones besides `File` in your [bootstrap](http://sailsjs.org/#/documentation/reference/sails.config/sails.config.bootstrap.html) if you life.

**Comment by pichlermi** [comment]
The globalization in the application is perfectly ok, but i think it's very dangerous, when the system itself breaks, how do you now that the names of your models doesn't conflict? In this case it crashed, so i could find it, but in general, there could be more subtile effects. I think there should be some namespace protection, maybe using node-modules as a barrier between the sails-api and the application.
