### ISSUE TITLE
.exec() within forloop can't work

### ISSUE THREAD

**Issue by holyxiaoxin** [balderdashy/sails#2584]
i have a model something like this:

```
\**
* user.petIds = ["1","2","3","4"];
*\
getPets: function(users){
    var response = [];
    for(var i=0;i<users.length;i++){
      Pet.find(users[i].petIds).exec(function(err, pets){
        if(err) return null;
        console.log("index: "+i);
        response.push({ name: users[i].name, pets: pets});
      });
    }
    return response;
  }
```

I want to get every pets from an array of pet ids for an array of users. However, an exec only executes after a callback which in this case causes console.log("index: "+i); to print 2, which throws an undefined error for users[i].name.

Is there anything in Sails which solve this problem? Otherwise it's impossible to use a for loop to query.

**Comment by holyxiaoxin** [comment]
I have tried to use a forEach instead:

```
getPets: function(users){
    var response = [];
    users.forEach(function(user){
      Pet.find(users[i].petIds).exec(function(err, pets){
        if(err) return null;
        console.log("index: "+i);
        response.push({ name: users[i].name, pets: pets});
      });
    });
    return response;
  }
```

but this is still asynchronous. response is returned before the queries are completed.

**Comment by sgress454** [comment]
Hi @holyxiaoxin and thanks for using Sails.  This forum is for posting about bugs in the Sails core; for support please try [StackOverflow](http://stackoverflow.com) (looks like you [already posted there](http://stackoverflow.com/questions/28114475/sailsjs-exec-within-forloop-doesnt-work)) or our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [Gitter chat](https://gitter.im/balderdashy/sails) or IRC channel at irc.freenode.org/sailsjs.  I'll close this now and answer on SO.
