### ISSUE TITLE
as a plugin

### ISSUE THREAD

**Issue by wiseguy12851** [balderdashy/sails#2585]
I have an existing project that's rather complicated in setup because of the package setup and uses gulp intensively. 

I really want to get started right away with sails as it looks very active and promising. Is there any way I can just add sails as a dependency in node and install it locally in the node_modules folder and integrate it that way.  Or does it have to be used in a fresh project. 

I'm willing to rearrange my folders a bit and add any required config files. So is there anyway I can do this and if so, how?

**Comment by loicsaintroch** [comment]
You can use Sails as a node module (dependency) and start your application the way you want on top of the framework but I don't see the point here. You will be more productive if you completely use Sails. You can use Sails with Gulp and it works fine! Here is an example: https://www.npmjs.com/package/sails-generate-new-gulp.
