### ISSUE TITLE
Issue with policies

### ISSUE THREAD

**Issue by icaliman** [balderdashy/sails#2588]
I applied a policy to all the routes from my app:

```js
module.exports.policies = {
  '*': 'localize'
}
```

But when I access some routes from browser this policy is not applied.

I found that the policy is applied only if routes are defined in this way:

```js
  'get /': 'AppController.index'
```

If routes are defined in this way policy is not applied:

```js
'get /': {
    view: 'app/index',
    locals: {
      layout: 'app/layout'
    },
    controller: 'AppController',
    action: 'index'
  }
```

**Comment by sgress454** [comment]
The route definition you've used is not valid--you can use the [view target syntax](http://sailsjs.org/#/documentation/concepts/Routes/RouteTargetSyntax.html?q=view-target-syntax) or the [controller-action target syntax](http://sailsjs.org/#/documentation/concepts/Routes/RouteTargetSyntax.html?q=controller-%2F-action-target-syntax), but not both.  The view syntax just binds the route directly to a view, and [policies don't apply to views](http://sailsjs.org/#/documentation/concepts/Policies?q=overview).  

Easiest thing here is to remove the `view` and `locals` parts of the route configuration, and inside the `index` method of `AppController.js` do `res.view({layout: 'app/layout'})`.
