### ISSUE TITLE
Changed routes in the documentation broke all incoming Google links (and probably all older links)

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/sails#2594]
The URL structure of the documentation changed suddenly without any thought for existing links to older pages, including from Google. From my experience at Twilio, about 50% of traffic to our documentation came from Google; breaking Google is a big deal. It's also, at least for this user, incredibly frustrating to get promised a focused page by Google and then get redirected to a generic page. 

Here are some examples of queries which get redirected to a generic homepage.

- "sails policies"
- "sails controllers"
- "sails i18n"
- "sails models"
- "sails services" (Doesn't promise a custom page, but doesn't find the Services page either)
- "sails routes"
- "sails log[ging]"
- "sails roadmap"
- "sails csrf"

Here's what you see in Google:

<img src="https://api.monosnap.com/rpc/file/download?id=bbmIrA2Ij1zxd5A892XjBXE1xuOKuv" />

When I click that link, I expect to get a page that explains how models work, how to use them, how to write them etc. 

Here's what you see when you reach the documentation (word "models" appears once in a list with 20 items): 

<img src="https://api.monosnap.com/rpc/file/download?id=JmjiHBGU2DvFhrujneXaCfRBm4ehlf" />

(For some reason it also takes two clicks of the "Back" button to get back to Google from the clicked link, though this is a separate issue).

I don't have any information about referrer links (I didn't see a Google Analytics link, your server logs may have more information), but my guess is that a lot of the incoming referrer links are also broken.

I gave a talk about documentation hierarchy & finding things in docs which might be useful, available here: https://www.youtube.com/watch?v=cC67PzBgRYE

**Comment by dylanpyle** [comment]
+1

**Comment by kevinburke** [comment]
I found 56,000 more broken links to the Sails docs:

https://github.com/search?utf8=%E2%9C%93&q=%22http%3A%2F%2Fsailsjs.org%2F%23%21documentation%22&type=Code&ref=searchresults

**Comment by sgress454** [comment]
Hi @kevinburke, thanks for pointing this out.  It sounds like it's been a pretty frustrating experience to navigate to the docs you need.  Yo've uncovered a couple of issues here that we need to address separately:

1. The system we use to crawl the docs site and provide pre-rendered content to Google is not working properly, resulting in Google searches still resulting in old links.
1. We need redirects from the old content to the new.

Both the core team and the Sails community at large have put a ton of work into the docs over the past year, and we're really happy with the resulting content, so I share your frustration that it's not as accessible as it needs to be.  Thanks again for your feedback and support!

**Comment by kevinburkeshyp** [comment]
Some more examples of broken links (from searching last week)

- "sails log levels"
- "sails.config.environment"
- "sails grunt"

**Comment by mikermcneil** [comment]
Ok guys, we're working on this, see https://github.com/balderdashy/www.sailsjs.org/issues/50

**Comment by dougblack** [comment]
Is there justification for why this was closed?

**Comment by randallmeeker** [comment]
because its open here https://github.com/balderdashy/www.sailsjs.org/issues/50

**Comment by mikermcneil** [comment]
@kevinburke @dougblack @randallmeeker Hey guys, just for posterity want to mention that this is all fixed up now.
