### ISSUE TITLE
how can i simply add a route with id parameter to a function in a REST API?

### ISSUE THREAD

**Issue by clodio** [balderdashy/sails#2597]
Is there a better and quicker way to do that (with blueprint?) ?

GET http://localhost:1337/user/:id/fullName

GET http://localhost:1337/user/12345678/fullName

*// config/routes.js*

    module.exports.routes = {
        'GET /user/:id/fullname': 'UserController.fullname'
    }

*// api/controller/UserController.js*

    module.exports = {
        fullName :function (req, res) {
            // Get the id parameter from the route
            if ( req.param('id') ) {
                // Use it to look up a different field
                User.findOne(req.param('id')).exec(function (err, theUser) {
                    if (err) {return console.log(err);res.serverError()};
                    if (!theUser) return res.notFound();
                    return res.json({ fullName: theUser.fullName()});
                });
            }
            else {
                return res.notFound();
            }
    }

*// api/models/User.js*

    module.exports = {
        attributes: {
            firstName: {
                type: 'string',
                required: true
            },
            lastName: {
                  type: 'string',
                  required: true
            },
            // Attribute methods
            fullName: function (){
              return this.firstName + '' + this.lastName;
           }
        }
    };

**Comment by Dallas62** [comment]
If you always want your fullname in your response, you can do:
```
        toJSON: function() {
            var obj = this.toObject();
            obj.fullname = obj.fullname();
            return obj;
        }
```

**Comment by loicsaintroch** [comment]
Thank you for your help @Dallas62.
