### ISSUE TITLE
Better Routing Required

### ISSUE THREAD

**Issue by kennysmoothx** [balderdashy/sails#2601]
In a big application I see myself having to write routes for every single end-point.. Is there a better way or something I'm missing?

Something like the following should be available: 

```
'get /account/:action': {
    controller: 'AccountController',
    action: ':action'
  }
```

Is there a way to simplify routes as such so that I don't have to write a route for every end point?

**Comment by Dallas62** [comment]
http://sailsjs.org/#/documentation/reference/blueprint-api

**Comment by sgress454** [comment]
Bingo, @Dallas62.  Thanks!
