### ISSUE TITLE
old table is not destroyed if i define a tableName in Model.js with migrate : drop

### ISSUE THREAD

**Issue by prisonier** [balderdashy/sails#2602]
I have a model named 'Order' and for some reason i need to make a raw SQL query with Model.query('SELECT ......', cb)

As 'order' is a keyword in MySQL & PGSQL, i need to escape the table name in my query.

I'm testing on both system (mysql & postgre) and unfortunately, escape rules for them are different.
I want to stay DB agnostic (at least SQL agnostic) so i wanted to define a tableName that is not a keyword in my model.

```
module.exports = {
  tableName : 'orders',
}

```

In /config/models.js, i have set migrate : drop but when i lift, both order table and orders table are there. 

If i change the tableName again and lift, i will have 3 tables. I can create an infinity of tables, they are never droped.

I've tried in MySQL & Postgre. I need to manually drop the table and when i lift again, i only have the table defined by tableName.

This is not a critical error as you will never put migrate: alter || drop in production but i think it is a bug.

**Comment by tjwebb** [comment]
This is expected behavior. `drop` only drops the tables that sails is aware of. If you change the tableName from `x` to `y`, sails is no longer aware of table `x`.

**Comment by prisonier** [comment]
Yes i realized that if you have an existant database and sails drop everything, it might be a problem.
