### ISSUE TITLE
[Feature Request] Additional global view locals

### ISSUE THREAD

**Issue by pyrokinetiq** [balderdashy/sails#2607]
It'd be nice if there were a simple way to inject a library (or anything) to all views.

For example, I want to have moment available to all my views because it's used in them frequently, currently I have to do something like:

`res.view('path/to/view', {moment: require('moment')});`

For every view.

It'd be nice if there were a way to include libraries to view locals globally, perhaps this functionality is already available? If so it doesn't seem to be documented.

I was thinking something like the following would be quite elegant:

`config/views.js`
````
module.exports.views = {
    engine: 'ejs',
    locals: {moment: require('moment'), is: require('is')},
    layout: 'layout'
}
````

**Comment by M3kH** [comment]
You can add locals to ```config/http.js -> locals``` but I can agree I didn't found it in the documentation or at least not in the same way I'm using, maybe the correct way is using http://sailsjs.org/#/documentation/concepts/Globals

**Comment by sgress454** [comment]
Hi @pyrokinetiq, the code snippet you posted already works--did you try it?  Adding `locals` to your `sails.config.views` config will [merge them into every view](https://github.com/balderdashy/sails/blob/master/lib/hooks/views/res.view.js#L153).

**Comment by pyrokinetiq** [comment]
Oh wow honestly I didn't even try actually running it, I just wrote that snippet for an example.
