### ISSUE TITLE
Prefix all routes

### ISSUE THREAD

**Issue by Kikobeats** [balderdashy/sails#2609]
At this moment I want to prefix all routes of my api, so I have in blueprints this:

```coffee
blueprints:
  actions: false
  shortcuts: false
  prefix: '/v1'
```

Works fine, but only prefix blueprints methods (obviously).

Exist a way to prefix all routes? I know that in express 4 is possible prefix easily with:

```
app.use('/v1', routerObject);
```

I know that is possible write a policie, but just I want to set up in the config...

Sorry if is  possible to prefix now, but I don't see nothing in the documentation.

**Comment by sgress454** [comment]
Hi @Kikobeats, it's not entirely clear what you're trying to do here--if you put `actions` back to `true`, then all of your routes mapped automatically to controller actions will have the prefix.  Routes that you define in `config/routes.js` won't ever be prefixed, because you are after all explicitly stating what you want the path to be!

**Comment by Kikobeats** [comment]
@sgress454 exactly I want to do is something to avoid explicity prefix the routes in `config/routes.js` and prefix all routes (like is possible in blueprints with `prefix` option, but out of blueprints as well).

why? because when you are creating different versions of the same API (`/v1`, `/v2/`, ...) can be useful for streamline the process just changing one value that define the global prefix instead of all individuals routes.

Do you think that can be useful?

**Comment by swelham** [comment]
Would be nice to have something similar to [rails namespaces](http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing) for this

**Comment by sgress454** [comment]
I actually worked on this on a flight a few weeks ago, then lost it and forgot to post.  So, here it is:

You can do this with policies--just not with the `config/policies.js` file.  Instead, you need to inject the policy directly into `config/routes.js` as a wildcard:

```
'/*': {policy: 'selectApiVersion', skipAssets: true},
```

Then in `api/policies/selectApiVersion`:
```
module.exports = function(req, res, next) {

  // Alter the URL based on the desired API version
  req.url = "/v" + (sails.config.apiVersion || 1) + req.url;
  return next();

};
```

At the time, there was an issue where `skipAssets` wouldn't work with the policy route syntax.  That's been [patched on master](https://github.com/balderdashy/sails/commit/0990fc10709520a9f6c55923b991708d5eaf8aa0), so the above will work, but we'll need to push out a patch release of Sails to make it available on NPM.

**Comment by Kikobeats** [comment]
Sounds good! thanks for the clarification :-)
