### ISSUE TITLE
Docs: model attribute type json can also be object

### ISSUE THREAD

**Issue by 0x80** [balderdashy/sails#2611]
This confused me. For a while I was doing stringify/parse on values in/out of the model, and defaultsTo with a proper json string, but later I found that you can just pass objects! 

Are the objects are just a convenience thing and is everything converted to JSON behind the scenes? In any case I think this should be in the documentation. There is nothing on the attribute values themselves.

**Comment by 0x80** [comment]
I will create a PR later probably...

**Comment by sgress454** [comment]
@0x80 thanks, please do put a PR on the [sails-docs](https://github.com/balderdashy/sails-docs) repo!
