### ISSUE TITLE
Print hook status in the CLI

### ISSUE THREAD

**Issue by Kikobeats** [balderdashy/sails#2612]
Because is possible to disable hooks in `.sailsrc`, what about print in the CLI a checklist with the hook status?

Also in 0.11.x where is possible load external hook can be useful tool to get all information of any sails project.

**Comment by sgress454** [comment]
Good idea @Kikobeats, I'd be down for this in `verbose` or `silly` mode.  Feel free to add it to [the roadmap](https://github.com/balderdashy/sails/blob/master/ROADMAP.md). This would also be a great addition to [sails-hook-dev](https://github.com/balderdashy/sails-hook-dev).
