### ISSUE TITLE
Should be possible to detect a permissions issue

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/sails#2614]
If grunt fails, the error message says in part

    Or maybe you don't have permissions to access the `.tmp` directory?

It should be possible to determine this by attempting to open `.tmp` and checking for an OS-level error.

**Comment by sgress454** [comment]
Possible enough....for a PR?!?!

@kevinburkeshyp, meet @boogerlad, recent creator of [sails-hook-grunt](https://github.com/boogerlad/sails-hook-grunt).  Go make beautiful :musical_note: together for us to :dancer: to!
