### ISSUE TITLE
Docs: thoroughly explain why asynchronous attribute methods are bad

### ISSUE THREAD

**Issue by ellipticmatt** [balderdashy/sails#2615]
From http://sailsjs.org/#/documentation/concepts/ORM/Models.html

> You should avoid writing your own asynchronous attribute methods. While built-in asynchronous attribute methods like .save() and .destroy() can be convenient from your app code, writing your own asynchronous attribute methods can sometimes have unintended consequences, and is not the most efficient way to build your app.

The explanation following this paragraph does not show any clear advantages for `Person.marry` over `personA.marry`. Intuitively, `personA.marry` seems like the proper OO way to do what we want. Please provide actual code showing a situation in which the attribute method approach fails or is "less efficient" than the model method alternative.

**Comment by sgress454** [comment]
Hi @ellipticmatt thanks for the observation--please post this in the [sails-docs](https://github.com/balderdashy/sails-docs) issues if you like!  The point that we're attempting to make in the explanation is that `Person.marry` could take as arguments either full model instances *or* just IDs or other identifiers, and the internal implementation could sort out loading the models if necessary.  This makes the implementation for something like `POST /people/marry` a lot clearer.
