### ISSUE TITLE
Sails v0.11.0-rc10 (and 0.11.0) assets loading timeout

### ISSUE THREAD

**Issue by swarthy** [balderdashy/sails#2616]
After upgrade to v0.11.0-rc10, sometimes, random assets (both css and js) loading takes a long time. Does anyone has same problem?

Firebug
![Firebug screen](http://s11.postimg.org/e8g2t45z7/image.png)
Chrome dev tools
![Chrome dev screen](http://s14.postimg.org/az3yhu9bl/image.png)
![(sort by status)](http://s29.postimg.org/czs2elyyf/image.png)

P.S. All grunt tasks has completed successful
P.S.S Sorry for my english

**Comment by sgress454** [comment]
Hi @swarthy, your English is fine :)

Have you verified that this problem goes away if you go back to Sails v0.10?  It could just be a coincidence.  As far as I know we haven't changed anything about how assets load in the newest code.

**Comment by norf33rus** [comment]
Yep, I have same problem. After upgrading sails from 0.10.5 to 0.11.0  Console show me the following " Uncaught Error: Load timeout for modules: ..."

**Comment by angelix** [comment]
I can confirm the same behavior to a newly generated project based on v0.11 .
I cannot recognize a pattern, it happens randomly.

**Comment by sgiatrakis** [comment]
Unfortunately have the same issue on 0.11rc-9. 
I thought that something wasn't right, when many times while i was reloading the page to see the changes i've been made, a blank page appears and reloads constantly.

**Comment by crackTheCode** [comment]
I also have the same problem I have to reload the browser twice to see my page, but sometimes I have to do this 3 or 4 times and other times it works correctly, so as mentioned above there seems to be no pattern.

**Comment by sgress454** [comment]
Can you all try uninstalling Sails completely, clearing npm cache, and reinstalling?

`sudo npm uinstall -g sails`
`npm cache clean`
`sudo npm install -g sails`

This will ensure that all dependencies are up-to-date.  Nothing regarding asset delivery has changed in this version, but perhaps there's an older Grunt version or some other old dependency hanging around, mucking up the works...

**Comment by norf33rus** [comment]
Solved this problem by updating nodejs to the latest version

**Comment by swarthy** [comment]
Clearing cache doesn't help, but updating node to v0.12 solved problem.

**Comment by norf33rus** [comment]
Solved this problem by updating nodejs to the latest version.

**Comment by sgress454** [comment]
Good to know--any idea exactly what version you were on previously?  I was looking with v0.10.28 and didn't see it, but there's plenty of other versions.

**Comment by swarthy** [comment]
I updated from 0.10.5 to 0.11.0-rc10

**Comment by martingg88** [comment]
yes. issue solved with node v0.12. 

FYI. i had this issue with node v0.10.28

**Comment by CBridgman** [comment]
Hi, I'm also having this problem, but unfortunately, it didn't go away entirely after updating node. I'm using node 0.12.2. The front end of my app has a lot of asset files when running in development mode (currently 86 files).

If I do a Ctrl-F5 load, the load timeout issue happens quite consistently in Firefox, with 1-4 of the files timing out, but only happens very occasionally in Chrome and IE. (Before moving from node 0.10.x to 0.12.2, it happened more often in Chrome too) It also seems that the issue is more likely to occur when there's a large amount of assets. I could not get the problem to happen with a newly created sails 0.12.2 project.

For now, I have rolled the app back to sails 0.10.5, and the issue is gone on Firefox, Chrome and IE.

**Comment by marclr** [comment]
I have the same situation as CBridgman. The versions that I have are Sails 0.11.0 and Node 0.10.5, I upgrade Node to 0.12.2 but it fails so I decide to downgrade Sails to 0.10.5 and it works like a charm.  So now, my configuration is Sails 0.10.5 and Node 0.12.2

**Comment by CWyrtzen** [comment]
Is this still going on?

**Comment by swarthy** [comment]
Sometimes with big assets count. Windows 7/8.1, Sails 0.11.0, node 0.12.7.
Browserify bundling makes me happy ;)

**Comment by martingg88** [comment]
any update to solve this issue for node version before 0.12.7?

**Comment by martingg88** [comment]
can treat this issue as highest priority?

**Comment by martingg88** [comment]
i hope you can follow the steps to produce the issue. 

1. use node v0.10.36 and sails v0.12.0 version. 
2. try to load more .js files (ex: 30 to 50). 
3. disable your browser cache or press F5 to refresh. Then you may notice the traffic to getting any one or two or even more .js file from server get stuck there. 

Let me know if you can't produce the issue again. 

thanks.

**Comment by martingg88** [comment]
is that possible v0.10.36  limit 5 maxsocket connections per host that cause this issue?

**Comment by crh3675** [comment]
Simply put, it is ExpressJS.  I didn't dig too deep into it but 3.16.0 was the issue as the upgrade fixed all woes. Bump the Express version to 3.20.2 and your troubles will fade away.

**Comment by sgress454** [comment]
Thanks a bunch @crh3675.  Version already bumped in master branch, so next release will solve the issue for good.  In the meantime, updating the Express dependency in an existing Sails v0.11.x install should be fine.

**Comment by mikermcneil** [comment]
@crh3675 @sgress454 Thanks guys.  I've definitely seen this now-- but reliably replicating it is difficult.  It does seem to be the same issue from inside Express though.  At this point, I'm like 75% sure it's resolved on `0.11.2` (latest stable) and `0.12-rc2` (only reason I'm not 100% is that I can't replicate it either way at this point...)

**Comment by IshantAgarwal** [comment]
Hi @mikermcneil 
I have tried with multiple versions of sails(10.5, 11.0, 0.12-rc2) but there seems to be no respite. My files(js css image) are still not getting loaded. Can you please suggest any particular  changes, that can help me ??
Even if I try to load a single file by hitting its url in browser it doesn't get loaded 99% of times.
I am using sails for some serious production framework. Any help is much appreciated .

**Comment by crh3675** [comment]
@IshantAgarwal try rc-3.  That is the version that worked for me.

**Comment by IshantAgarwal** [comment]
@crh3675 did you change the express version as well, and what is you node version ?

**Comment by IshantAgarwal** [comment]
It is just no getting loaded, the only log message that I get is as following in running log mode as silly.
Serving view at rel path:  login
View root:  /opt/jiesenberg/views
Rendering view: "login" (located @ "/opt/jiesenberg/views/login")
• using configured layout:: layout (located @ "/opt/jiesenberg/views/layout").

Looks like I have to move away from sails, and try using express directly.

**Comment by IshantAgarwal** [comment]
This is absolutely stupid, wasting so much time on sails. SAD it is !

**Comment by IshantAgarwal** [comment]
Moreover can anyone tell me how much time should it take ideally for a file as big as 183 kb html to be loaded, as I tried to load html file by moving every javascript file to *.html page.

**Comment by crh3675** [comment]
I don't see any situation where 183kb file would take a minute to load.  Also note, the Sails rc-3 bumps the Express version so there is no need to "also" do that.

You also might have some other NPM cache issues or modules installed globally that are causing some sort of mismatch.

I have been using SailJS very successfully for many years so I am concerned about your frustration

**Comment by IshantAgarwal** [comment]
Okay thanks for the help @crh3675 , so basically I went to res.view.js file inside sails, and it prints the html file perfectly  just before res.send(renderedViewStr) and also "res.send(renderedViewStr) is also able to send the file, but somehow the file is not getting received at the browser end. So as I read that res.send() is terminal command, does it mean since res.send() seems to be working fine, the issue should be outside nodejs ?? Moreover just to give some more insight, CURL request is working perfectly !

**Comment by mikermcneil** [comment]
@IshantAgarwal @crh3675 or anyone else reading this:  

I remember seeing this a while back, but was never able to reproduce it consistently.  Now using Node 0.10.26 and the latest stable version of sails (0.11.4), I haven't seen it at all.  So as far as I can tell, this is a timing issue that was present in older versions of Node and is solved now-- but I want to make sure about that.

If you're still seeing this problem in 0.11.4, would you **open a new issue** and link to this one? That'll help make sure we see it.  In that issue, would you also include your node version and any other relevant info?  (see https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions for some tips)

If we can't figure it out from there, we should pursue trying to recreate this in a clean Sails app to rule out any race conditions related to sessions (see "Allow disabling session mw for static assets" [here](https://github.com/balderdashy/sails/blob/master/ROADMAP.md)).  It's also possible it could be coming from Grunt, so if you open up that new issue, if you'd also specify whether or not NODE_ENV is "production", that'd be helpful.

Thanks!
