### ISSUE TITLE
sails.io.js relative url

### ISSUE THREAD

**Issue by boogerlad** [balderdashy/sails#2617]
I'm trying to do a post request with a relative url "hi/something" and it doesn't seem to be working. Looking at the source code, it seems like there's no support for a relative url in there. Am I correct?

**Comment by MBrouns** [comment]
i'm not sure if this is what you mean but if you set io.sails.url to an absolute location where your sails instance can be reached you can use for example this

    io.sails.url = "http://localhost:1337"
    
    io.socket.post('/user/create/', item, function (data) {
    }

**Comment by boogerlad** [comment]
if the url provided is say 'user/create' without the leading slash, this won't work. I have a function that if someone wants to do a pull request for `sails.io.js` they can. It works for my needs

```
function relative_absolute_url(relativeURL)
{
	var a = document.createElement('a');
	a.href = relativeURL;
	return a.pathname;
}
```
