### ISSUE TITLE
Auto generate index route with disabled blueprints actions

### ISSUE THREAD

**Issue by udanpe** [balderdashy/sails#2619]
1.
blueprints {actions: false, shortcuts: false}
get /tests {controller: 'TestController', action: 'index'}

/test (without s) working too.
why sails generate this route?

2.
Why /test/update/:id ?
maybe better /test/:id/update ?

3.
npm install sails@beta
./node_modules/.bin/sails new test (without cd test)
./node_modules/.bin/sails generate model test (create new dir app/..)
./node_modules/.bin/sails generate controller test (error: only be used in the root directory)

4.
I want db seeding with faker

**Comment by MBrouns** [comment]
(1) pluralization of blueprint routes can be turned off in the blueprints config (http://sailsjs.org/#/documentation/reference/sails.config/sails.config.blueprints.html)

(2) The convention of REST url's as far as I know is '/parent/id/active' which is the version Sails implements.

(4) you should be able to implement faker.js in your sails application and call it form for example the config/bootstrap.js to create fake data when lifting

**Comment by udanpe** [comment]
I know about pluralization but its for all route. I don't understand why sails generate index if other route disabled.
Sails use /parent/active/:id when shortcuts:true and rest (without edit)
sails generate seed active title:string description:string
sails seed, sails seed refresh and other

**Comment by sgress454** [comment]
Hi @udanpe, thanks for pointing out the issue with `sails generate model`; it should also restrict itself to working in Sails root folders.  As far as the `/test` route, there's a separate `blueprints.index` setting for that that you can turn off:

```
blueprints {actions: false, shortcuts: false, index: false}
```

Thanks @MBrouns for answering the other questions!
