### ISSUE TITLE
Maybe new website design?

### ISSUE THREAD

**Issue by tostr** [balderdashy/sails#2620]
Guys, how about a new website design, actual one seems a bit old and dark. 
And maybe some more in-depth docs?
This is just an idea, looking at Laravel's new website, I wonder if Sails can get one even better.
If you need some help, I'm ready to take part in that.

**Comment by randallmeeker** [comment]
I have a new sails drinking game. Take a drink when someone mentions updating the Docs and take a drink when someone mentions Laravel as a comparison!!! 

@tostr both points are valid and are part of a larger discussion. GitHub is for bugs and stuff, you should chat this up over at the Google groups https://groups.google.com/forum/#!forum/sailsjs
