### ISSUE TITLE
Localization validation message

### ISSUE THREAD

**Issue by udanpe** [balderdashy/sails#2622]
if validation error we have object with en message
i want support translation in config/locales/xx.json
{
  "error": "E_VALIDATION",
  "status": 400,
  "summary": "3 attributes are invalid",
  "model": "User",
  "invalidAttributes": {
    "name": [
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: ''"
      }
    ],
    "email": [
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: ''"
      }
    ],
    "password": [
      {
        "rule": "required",
        "message": "\"required\" validation rule failed for input: ''"
      }
    ]
  }

**Comment by udanpe** [comment]
auto complete fields and return error message? 
return res.redirect('/back')
.with({
message:message,
input:input
});

**Comment by sgress454** [comment]
Hi @udanpe, thanks for using Sails.  This forum is for reporting bugs in the Sails core.  For support and questions about implementation, try our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [StackOverflow](http://stackoverflow.com) or our [Gitter chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).  Try to keep it to one question at a time and be as descriptive as possible about what you're trying to do!
