### ISSUE TITLE
Forever start not working

### ISSUE THREAD

**Issue by vanbungkring** [balderdashy/sails#263]
Hi ,i love this engine when first time using it :) thanks...

but i've problem when starting it with forever

app/testProject# forever start .app.js 
info:    Forever processing file: .app.js

but when i check it to browser, its not running, it just running when i use

sails lift, 

is that any other tips?

**Comment by GeneralTyres** [comment]
I'm having this problem now on a Ubuntu VPS. What was your solution?

**Comment by GeneralTyres** [comment]
Just going to leave this here. https://stackoverflow.com/questions/35240039/sails-js-is-not-working-with-forever
