### ISSUE TITLE
How do I enable es6 --harmony support?

### ISSUE THREAD

**Issue by sochka** [balderdashy/sails#2631]
If I start my app with `sails lift --harmony` - it doesn't work. `node --harmony app.js` doesn't work either. I'm using node 0.11 and testing `let` scoping.

**Comment by boogerlad** [comment]
I've had much better success with iojs

**Comment by sochka** [comment]
Ok, the problem was that `let` is not implemented even in `node.js` and `iojs` latest versions.

**Comment by boogerlad** [comment]
It is. Im using let right now with iojs.The regular harmony flag isnt sufficient afaik

**Comment by sochka** [comment]
Yeah, I see now, it requires strict mode + some magic.
