### ISSUE TITLE
Self reference in controllers.

### ISSUE THREAD

**Issue by Bartinger** [balderdashy/sails#2632]
Is there a reason why ```this``` in controllers and probably in other modules as well references the global window (or sails) object instead of the object itself? For example

```javascript
module.exports = {

	//Default options
	options: {
		sort: 'desc',
		test: 'base'
	},

	
	find: function (req, res) {
		console.log(this);
		return res.ok('Test');
	}
}
```
Prints the window/sails object instead of itself, so there is no way to access ```this.options```

**Comment by blah238** [comment]
http://stackoverflow.com/questions/23278857/how-can-i-call-a-sails-js-controllers-function-from-another-function-of-the-sam

**Comment by sgress454** [comment]
Hi @Bartinger, this should be [fixed in the master branch of Sails](https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L497); you can try it with `npm install sails@beta`.
