### ISSUE TITLE
Sails multiple models associate

### ISSUE THREAD

**Issue by vlatkodrljin** [balderdashy/sails#2637]
I have following models:

Comment.js

    module.exports = {
        attributes: {
            id : {
                type : 'integer',
                primaryKey : true
            },
            objectId : {
                type : 'string',
                required : true
            },
            comment : {
                type : 'string',
                required : true
            }
        }

    };

Image.js and Video.js are the same:

     module.exports = {
        attributes: {
            id : {
                type : 'integer',
                primaryKey : true
            },
            name : {
               type: 'string'
            },
            comments : {
                collection : 'comment',
                via : 'objectId'
            }

         }

     };

When i try populate comments with Video or Image model array is always empty (some comments are inserted for both)..

    Image.find({id: 1}).populate('comments').exec(function(err, image) {
       console.log(image);
    });

Or this...

    Video.find({id: 1}).populate('comments').exec(function(err, video) {
       console.log(video);
    });

I want to separate video and image models, and for comments i want use combined table.

Tnx

**Comment by Dallas62** [comment]
If your `id` is an `integer`, try with an `integer` on `objectId`

**Comment by randallmeeker** [comment]
http://stackoverflow.com/questions/28435383/sails-multiple-models-associate

**Comment by sgress454** [comment]
Hi @vlatkodrljin, thanks for posting this on SO.  We try to keep this forum for bug reports only.  I'll close this in favor of the SO link (thanks @randallmeeker for posting)
