### ISSUE TITLE
Move Sails project to new Github organization

### ISSUE THREAD

**Issue by kievechua** [balderdashy/sails#2639]
As Sails grow bigger and bigger I think it make sense to do so.
Right now I see many repo is not Sails related but Balderdash related, I think it will confuse new user who trying to look through the project repos.

I understand Sails project is created and maintained by Balderdash company and I really appreciated it, but I think the credit should be in documents.

What do you guys think?

**Comment by particlebanana** [comment]
@kievechua we are working on it. We are partnering with an open foundation to move the project into a permanent home. There should be more information as it gets lined up.

**Comment by kievechua** [comment]
Good to hear that, good job guys. :)
