### ISSUE TITLE
Incorrect error message when res.view(...) view has the '.ejs' suffix

### ISSUE THREAD

**Issue by bingomanatee** [balderdashy/sails#2642]
When in my controller I use the form 

    res.view('story/edit.ejs', {story: story})

the error message 

````
{
message: "Could not render view "/story/edit.ejs". Tried locating view file @ "/Users/dave/Documents/repos/wonderland/views/story/edit.ejs". Layout configured as "layout", so tried using layout @ "/Users/dave/Documents/repos/wonderland/views/layout")",
code: "E_VIEW_FAILED",
status: 500,
view: {
name: "/story/edit.ejs",
root: "/Users/dave/Documents/repos/wonderland/views",
defaultEngine: "ejs",
ext: ".ejs"
}
}
````

appeared. 

I cut and pasted that path into terminal and that file indeed existed. I thought at first the problem was the '.ejs' suffix in the res.view and removed it; at that point I got my page view correctly. I then re-inserted the .ejs suffix and could not recreate the problem.

**Comment by rudeluv** [comment]
I believe this is expected behavior. This way if you change your view engine, you don't have to go changing all of your explicit view paths.

**Comment by sgress454** [comment]
If you re-inserted the suffix and couldn't recreate the problem, I'm thinking it was something outside of Sails.  If it reappears and you can recreate reliably, let us know!
