### ISSUE TITLE
Bypass policy by using populate in URL

### ISSUE THREAD

**Issue by erkstruwe** [balderdashy/sails#2643]
Anyone who is allowed to findOne may also populate. Even if there is a populate policy to restrict that.

blueprints.js
```
populate: false
```

policies.js
```
UserController: {
  findOne: true,
  populate: false
}
```

```GET /user/1/secrets``` (populate blueprint action) --> 403 Forbidden
```GET /user/1?populate=[secrets]``` (findOne blueprint action with populate query) --> 200 OK

This was introduced by https://github.com/balderdashy/sails/pull/1695 .

**Comment by erkstruwe** [comment]
Security precautions:

policies.js
```
UserController: {
  findOne: ['preventPopulate'],
  populate: false
}
```

policies/preventPopulate.js
```
module.exports = function(req, res, next) {
  if (!req.param('populate')) {
    return next();
  }
  return res.forbidden();
};
```

**Comment by tjwebb** [comment]
> populate: false

This is not a policy, this is just a default setting for whether to return pre-populated associations. It should not be used for any sort of security.

**Comment by erkstruwe** [comment]
@tjwebb: I don't think so. In the ```policies.js``` file, ```populate: false``` inside of a Controller section is a policy. Maybe you mixed that up with ```populate: false``` in ```blueprints.js```?

**Comment by tjwebb** [comment]
The main problem you're seeing is that populate is not a controller action. 

> GET /user/1?populate=[secrets] --> 200 OK

populate is part of the query. I'm not sure that this is a problem. You developed a policy to disallow populating. Is it that you just would like an easier way?

**Comment by erkstruwe** [comment]
Hm, in a way, populate is both a contoller action (the blueprint action) AND part of the query of the findOne blueprint action. I guess I just found it misleading that I actively prevent people from using the populate blueprint action, but they can still populate associations by using the findOne blueprint action with populate query.

Today, I see that the policy for the populate blueprint action should not really influence what happens in the findOne blueprint action. However, I'm missing a "global" way of preventing people from accessing associations through any route/action. My current solution does what I want it to do, indeed. It feels a bit hacky, though.
