### ISSUE TITLE
Sails.sockets.emit v Sails.sockets.io.emit?

### ISSUE THREAD

**Issue by ezmiller** [balderdashy/sails#2651]
When trying to emit a message to a room, we used the syntax in the documentation, which is the following:

```
sails.sockets.emit( 'abc', function(msg) {
    console.log(msg);
}
```
This however did not work. When we changed our code slightly like so:
```
sails.sockets.io.emit( 'abc', function(msg) {
    console.log(msg);
}
```
it worked! 

Can someone explain what is going on here?

**Comment by sgress454** [comment]
Not sure what documentation you're looking at, but that's not the right syntax for `sails.sockets.emit`!  It should be:

```
sails.sockets.emit( socketIds, [event], data)
```

See the [reference here](http://sailsjs.org/#!/documentation/reference/websockets/sails.sockets/sails.sockets.emit.html).
