### ISSUE TITLE
Global Policy in 0.11

### ISSUE THREAD

**Issue by gregbty** [balderdashy/sails#2652]
It seems as though the global wildcard is overriding all of the lower rules. For example:

~~~nodejs
module.exports.policies = {
  '*': false,
  'AuthController:': {
    '*': true
  },
  'MainController': {
    '*': 'isAuthenticated',
    'admin': ['isAuthenticated', 'isAdmin']
  }
};
~~~

The above snippet is causing a post to AuthController.login to return with a forbidden response. If I remove the wildcard policy then everything works properly. Is this a bug or am I missing something here?

**Comment by MBrouns** [comment]
It seems to me that the name of your AuthController policy is wrong. The colon at the end probably shouldn't be there

```
module.exports.policies = {
  '*': false,
  'AuthController': {
    '*': true
  },
  'MainController': {
    '*': 'isAuthenticated',
    'admin': ['isAuthenticated', 'isAdmin']
  }
};

```

**Comment by gregbty** [comment]
Thanks, I completely missed that!
