### ISSUE TITLE
Wildcard Route not Working as expected

### ISSUE THREAD

**Issue by kgrvamsi** [balderdashy/sails#2655]
Problem

I have a requirement where i need to create a view page based upon id and render the details of it in a special page (its a view page)

example -  get /commercial/electronics/:electronicid : Commercialcontroller.electronicdetails

i save this in the config/routes.js file and i create the view file in 

views/commercial/electronics/electronicdetails.ejs

in Commercial.js file in api/controller
```
module.exports = {

electronicdetails:function(req,res){

            res.view('commercial/electronics/electronicdetails');
}

}
```
But i get the 404 error and here is the output

Error:
```
verbose: Sending 404 ("Not Found") response
silly: View override argument passed to res.view():  404
silly: Serving view at rel path:  404
silly: View root:  /opt/dockerstack-dashboard/views
```

I have referenced all the documents,stackoverflow and google but i dont get a clear understanding on this so can you please help me out on this for better understanding.

Reference Urls

https://github.com/balderdashy/sails/issues/2069
https://github.com/balderdashy/sails/issues/247
https://github.com/balderdashy/sails/issues/1021
https://github.com/balderdashy/sails/issues/454
https://gist.github.com/mikermcneil/5737561

https://gist.github.com/mikermcneil/5737561

**Comment by Josebaseba** [comment]
In controllers folder the name of the controller should be:  CommercialController.js instead of Commercial.js. Because in the routes you are calling to: CommercialController.electronicdetails.

**Comment by kgrvamsi** [comment]
Sorry i didnt given that convention of that file name properly and yes i have the file name with CommercialController.js in controller folder.
