### ISSUE TITLE
can i use es6 in sails

### ISSUE THREAD

**Issue by ckken** [balderdashy/sails#2657]
like yeild promise   i run it in iojs and goes well bug i want use es6 like koa

**Comment by Kikobeats** [comment]
this depend of the node es6 compatibility, at this moment is a [little poor](https://kangax.github.io/compat-table/es6/#node).

Under iojs is much better, but I'm not sure about how would be if sails works fine under it.

On the other hand you can use a pre-compiler that convert your es6 code into es5 compatibility code. See [babel project](https://babeljs.io/).

**Comment by sgress454** [comment]
All that's really important is whether IO.js can run Sails; early reports are that it can.  Sails itself doesn't use ES6 in core.

**Comment by ckken** [comment]
i make koa waterline together and it goes well

**Comment by Messilimeng** [comment]
@ckken 大哥啊 我用你那个knode  升级到4.0 nodejs 现在 路由不能用了啊 看看呀  貌似人家不理你啊

**Comment by RWOverdijk** [comment]
lol

**Comment by Messilimeng** [comment]
@RWOverdijk  I want to play LOL .

**Comment by Wizzercn** [comment]
@Messilimeng I played three years Teemo..

**Comment by Messilimeng** [comment]
@Wizzercn  I have already played 3500 games.
