### ISSUE TITLE
Normalise rest path prefix breaks blueprint routes on Windows

### ISSUE THREAD

**Issue by erkstruwe** [balderdashy/sails#2658]
@konstantinzolotarev Usage of `nodepath.normalize()` for `baseRestRoute` breaks routes on Windows machines, because "/" characters are replaced by "\" characters. This results in routes like `\model/...`. I currently solved that by adding `baseRestRoute = baseRestRoute.replace(/\\/g, '/')` in the line after.

Sails v0.11.0
Introduced by e277fac41076c976f63c805de77fe008fd9ec0eb

**Comment by konstantinzolotarev** [comment]
Oh. Ok. will fix today.

**Comment by tjwebb** [comment]
@konstantinzolotarev is this resolved?

**Comment by konstantinzolotarev** [comment]
@tjwebb Yes PR was merged about 10 hours ago. So fix will be applied with a new version published in npm.

**Comment by loicsaintroch** [comment]
Thanks for the update @konstantinzolotarev.
