### ISSUE TITLE
/api/responses/ folder is missing some default responses

### ISSUE THREAD

**Issue by tarlepp** [balderdashy/sails#2660]
I just noticed that sails 0.11.0 has some new responses in [/lib/hooks/responses/defaults/](https://github.com/balderdashy/sails/tree/master/lib/hooks/responses/defaults) directory and when creating new sails app with ```sails new AwesomeApp``` that application ```/api/responses/``` folder doesn't contain all of those.

This is kind of misleading, why just partion of those default responses are copied under application and not all of those?

**Comment by CWyrtzen** [comment]
@tjwebb is this truly a bug?

**Comment by tarlepp** [comment]
If not a bug why does those default responses exists then?

**Comment by tjwebb** [comment]
My guess is that it's a bug in the generator. If the generator is purposefully not including them, then I agree that having them in a folder called `defaults` is very confusing.

**Comment by sgress454** [comment]
I'd say that the absence of the new "created" response is an issue that should be addressed in the generator.  We've purposely left `negotiate.js` out because it's a bit more advanced.

**Comment by tarlepp** [comment]
And again imho that should contain _all_ the default responses. If some of those are "advanced" than others, so what?

**Comment by sgress454** [comment]
> If some of those are "advanced" than others, so what?

We try to strike a balance between making things easy to customize and hard to screw up.   This is one of those compromises.

**Comment by tarlepp** [comment]
ok, what you think about ```sails new-advanced``` then? That will generate with _all_ responses, globals and shortcuts disabled?

**Comment by mikermcneil** [comment]
@tarlepp open to something like that as part of core.  Would you hit me up in gitter some time about it? (or if you have time, a proposal to kick things off would be even better)  Thanks!
