### ISSUE TITLE
/api/hooks/ folder is missing after creating new sails application

### ISSUE THREAD

**Issue by tarlepp** [balderdashy/sails#2661]
Other folders are created as they should, but this ```hooks``` folder is missing.

Also it would be great if all those api folders contains README.MD with link to proper section of the docs.

**Comment by sgress454** [comment]
`api/hooks` has never been included with the default app created by `sails new`; you create it if you have the need for user hooks (many folks won't).  The README.MD file is an interesting idea, though.
