### ISSUE TITLE
Sails JS : Blueprint API : Get Many to Many Relationship by ID is not working

### ISSUE THREAD

**Issue by rasekar2000** [balderdashy/sails#2664]
Hello Team,

 I have given more details in the stak overflow as well as 
http://stackoverflow.com/questions/28572810/sails-js-blueprint-api-get-many-to-many-relationship-by-id-is-not-working

 captured the information in the Google Doc for the issue, I am talking about.. 
https://docs.google.com/document/d/1frEGpdapa2vndq5ibLCZcpeGjiX7tq-NJ41DzDVjSr8/edit#heading=h.rvv2znfihuk 

Followed the documentation to create Users to Pets - Many to Many Relationship in Sails JS V10.5 - BluePrint API with MongoDB v2.6

Yet http://localhost:1337/user/54e38754b27f02212458e68e/pets?name=Pinkie%20Pie Finding the Owner's Pet by Name  works ..

{ "name": "Pinkie Pie", "color": "pink", "createdAt": "2015-02-17T18:24:20.720Z", "updatedAt": "2015-02-17T18:24:20.720Z", "id": "54e38754b27f02212458e691" }

But when the same pet is accessed via its ID http://localhost:1337/user/54e38754b27f02212458e68e/pets?id=54e38754b27f02212458e691 , the REST API is not returning any value.

Can you please let me know, how to enable additional logs to troubleshoot this basic Blueprint REST API access?

**Comment by erkstruwe** [comment]
Are you developing on Windows? Then this could be related to https://github.com/balderdashy/sails/issues/2658 . Please set your log level to ```silly``` and see if you have route bindings starting with ```\``` instead of ```/```. The referenced issue gives a temporary solution until this is solved.

**Comment by rasekar2000** [comment]
Hi Erk Struwe,

 Nope..  I am using Mac OS X - 10.10.2 . Sails Version 10.5. MongoDB Version 2.6
 http://pastebin.com/3ue0SzNH
 Yes. you can see the server startup trace in Silly Level config in the above PasteBin URL.
 
 Entire details with screenshot as well captured in 
 https://docs.google.com/document/d/1frEGpdapa2vndq5ibLCZcpeGjiX7tq-NJ41DzDVjSr8/edit#

Thanks and Regards,
Raj

**Comment by erkstruwe** [comment]
I answered on SO.
Route syntax is `GET /user/54e38754b27f02212458e68e/pets/54e38754b27f02212458e691`. To add/remove pets you can also use `POST`/`DELETE` methods on the same URL.

**Comment by rasekar2000** [comment]
Yes. That one is not working .. Thats the problem. Detailed out in 
https://docs.google.com/document/d/1frEGpdapa2vndq5ibLCZcpeGjiX7tq-NJ41DzDVjSr8/edit#heading=h.rvv2znfihuk

**Comment by rasekar2000** [comment]
Hi,
Sample Source code is uploaded to my google drive https://drive.google.com/file/d/0B0fs0t6Bg6GGQ05SajJrMHpMYmc/view?usp=sharing 
To Test the same. If you have MongoDB, please create DBS - company1 ( as you can see in  connection.js ). 
To Generate sample data between user & pets just enter http://localhost1337/user/hello. This function will load few users & pets and link them together. Then you will be able to access   localhost:1337/user/54e38754b27f02212458e68e/pets/54e38754b27f02212458e691 

If this is not working then how do we enable the debugger for Blueprint to troubleshoot this issue. Please let me know. Thanks in advance.

**Comment by rasekar2000** [comment]
I have downloaded the latest 0.11.0 version and this particular exercise worked..

http://localhost:1337/user/54e5503cd507bb334a8bd0ab/pets/54e5503cd507bb334a8bd0ad

So, I guess something wrong in the older stable version 0.10.5 .

 :-)

Regards,
Raj
