### ISSUE TITLE
Oracle Adapter is not officially supported by Sails.js

### ISSUE THREAD

**Issue by jasonw401** [balderdashy/sails#2668]
It seems that the Oracle Adapter is not officially supported by Sails.js. Is there a plan for balderdash to put Oracle Adapter officially into Sails.js/waterline?

**Comment by tjwebb** [comment]
No. We do not intend to "officially" support every adapter out there. We rely on the community to take leadership on things like this.

**Comment by sgress454** [comment]
@jasonw401 On the one hand, no one on the core SailsJS team has any Oracle expertise.  On the other hand, as @tjwebb alluded to, the SailsJS community is large and diverse!  I would judge any module (such as a database adapter) by how actively it is maintained and what you can glean from its contributors, not by its status as "officially maintained".  That is to say, the maintainers of an "unofficial" adapter may be rockstars who put the core team to shame :wink:

**Comment by jasonw401** [comment]
Thanks a lot for your guys. I understand the situation.

**Comment by tjwebb** [comment]
Companies occasionally will sponsor a feature that they need, and maintain it: https://github.com/cnect/sails-sqlserver. If you can do this, great. You could also hire Balderdash or another firm to build/maintain something.
