### ISSUE TITLE
async problem

### ISSUE THREAD

**Issue by Midako** [balderdashy/sails#2672]
Sails: 0.10.5
im new to sails and javascript aswell.

      Player
        .findOne()
        .where({email: email})
        .exec(function(err, player) {
          if(err) {
            return res.send(500, err);
          }

          if(typeof player === "undefined") {
             // if player doesn't exist create player
            Player.create({email: email}, function(err, user) {
              if(err) {
                return res.send(500, err);
              }
              player = user;
              console.log(user);
            })
          }

            //do something
            console.log(player);

        });

how it should:
He search for the Player, if player doesn't exist he create a player with the email put the callback user in player and after it he does something with the callback of the new created player.

how it is:
he search for the Player, if player doesn't exist he start to create one but goes already to the //do something part 
//do something console.log(player) is outputed with undefined and after this 
console.log(user); is outputed.

how to do it right ?

**Comment by Dallas62** [comment]
`Player.create()` is Asynchrone so you last console.log doesn't receive the new player when `.create()` is called


You can do something like that:
```
 
  var doSomething = function( player ) {
    sails.log.info(player);
  }

  Player
    .findOne()
    .where({email: email})
    .exec(function(err, player) {
      if(err) {
        return res.send(500, err);
      }

      if(typeof player === "undefined") {
         // if player doesn't exist create player
        Player.create({email: email}, function(err, user) {
          if(err) {
            return res.send(500, err);
          }
          doSomething(user);
        })
      } else {
        doSomething(player);
      }
    });
```

**Comment by sgress454** [comment]
Thanks @Dallas62, looks good.

@Midako just FYI this forum is for bug reports on the Sails core; if you have support questions please see our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [StackOverflow](http://www.stackoverflow.com) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
