### ISSUE TITLE
Install error !!

### ISSUE THREAD

**Issue by florindumitru** [balderdashy/sails#2673]
npm install -g sails
/
> sails@0.11.0 preinstall /root/.node/lib/node_modules/sails
> node ./lib/preinstall_npmcheck.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.node/lib/node_modules/sails/lib/preinstall_npmcheck.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "sails"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sails@0.11.0 preinstall: `node ./lib/preinstall_npmcheck.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the sails@0.11.0 preinstall script 'node ./lib/preinstall_npmcheck.js'.
npm ERR! This is most likely a problem with the sails package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/preinstall_npmcheck.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sails
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by tjwebb** [comment]
Don't install as root.

**Comment by mateeyow** [comment]
Any solution for this aside from the one answered?

**Comment by tjwebb** [comment]
btw, the root issue is with npm, not sails. I'm guessing you're also running into problems running npm as root? If so, not installing as root will solve the problem.

**Comment by mateeyow** [comment]
Yeah, I already solved it. I was installong .nvm using root. All other modules installed properly aside from sails. So I installed a nvm as sudo.

**Comment by tjwebb** [comment]
Yea, `nvm` relies on a ton of environment things and you're going to run into issues there as well if you're doing stuff as root. That sails happened to not work is totally random. Next week, some other module is going to fail to install for confusing and annoying reasons. I maintain both https://github.com/tj/n and https://github.com/xtuple/nvm (nvm-global) so I know a little bit about this topic.

In general, running code you download from the internet as root really isn't something you want to be in the habit of.
