### ISSUE TITLE
Call one service from another on initialization

### ISSUE THREAD

**Issue by Firfi** [balderdashy/sails#2674]
Hey,

I use one service inside another and do it on init step. To archive that I use require() as another service object isn't accessible yet on that stage. Problem is in that case this service initialized two times. First on require, then on standard Sails initialization. I use this for several services so wondering if there's good solution.

Thanks,
Igor

**Comment by tjwebb** [comment]
> I use one service inside another and do it on init step. 

I have no idea what this means.

**Comment by Firfi** [comment]
Service1.js

```
console.log('service1');
module.exports = {
methodINeed: function() {}
};
```

Service2.js 

```
// Service1 object isn't accessible here yet 
var Service1 = require('./Service1');
console.log('service2');
// call methodINeed here
```

Output:

```
Service1
Service2
Service1
```

Is that clear enough?

**Comment by Dallas62** [comment]
FirstService.js
```

// Your stuff to initialize once

module.exports = {
    methodINeed: function() {
    }
};
```

SecondService.js
```
// Your stuff to initialize once

var initialized = false;

module.exports = {
    initialize: function() {
        if(!initialized){
             initialized = true;

             // Stuff with FirstService.methodINeed();
        }
    }
};
```

bootstrap.js
```

// Add this line before cb();
SecondService.initialize();

```

**Comment by tjwebb** [comment]
> Problem is in that case this service initialized two times. **First on require,** then on standard Sails initialization.

What does initialized on require mean? If it's a service, you should just be exporting an object.

**Comment by Dallas62** [comment]
He wants to initialize a service (by calling another one) on sails lift.
But in his case, sails already load the service one time when he tries to initialize it (with an inappropriate require).

So I wrote him an example, that should work in his case.
