### ISSUE TITLE
Server-side Typescript support

### ISSUE THREAD

**Issue by jjrv** [balderdashy/sails#2676]
lib/hooks/moduleloader/index.js has support for CoffeeScript by requiring coffee-script/register and including "coffee" in file extension filters. For TypeScript support it's easy to add 'typescript-require' in the beginning of the Gruntfile.js, but moduleloader filters need patching to include the .ts extension.

The most future-proof fix might be to allow configuring the file extensions recognized by moduleloader, to support any similar language in controllers, policies etc.

**Comment by sfakir** [comment]
+1 for Typescript in Backend

**Comment by loicsaintroch** [comment]
Feel free to write a PR like #2662. We'll be glad to merge it. Thank you for your help @jjrv.
