### ISSUE TITLE
error: Error: The hook `orm` is taking too long to load.

### ISSUE THREAD

**Issue by VikramTiwari** [balderdashy/sails#2677]
When i lift a new project, it prompts me to choose a migrate strategy. While i am reading the message the prompt breaks with error.

Why would callback be hooked with a timeout? If there is a prompt which requires an action and can not be skipped, it must wait as long as user doesn't make the choice. There can be no preset to it.

Error Dump:
`
info: Starting app...

-----------------------------------------------------------------

 Excuse my interruption, but it looks like this app
 does not have a project-wide "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)
 
 In short, this setting controls whether/how Sails will attempt to automatically
 rebuild the tables/collections/sets/etc. in your database schema.
 You can read more about the "migrate" setting here:
 http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html?q=migrate

 In a production environment (NODE_ENV==="production") Sails always uses
 migrate:"safe" to protect inadvertent deletion of your data.
 However during development, you have a few other options for convenience:

 1. safe  - never auto-migrate my database(s). I will do it myself (by hand) 
 2. alter - auto-migrate, but attempt to keep my existing data (experimental)
 3. drop  - wipe/drop ALL my data and rebuild models every time I lift Sails

What would you like Sails to do?

info: To skip this prompt in the future, set `sails.config.models.migrate`.
info: (conventionally, this is done in `config/models.js`)

warn: ** DO NOT CHOOSE "2" or "3" IF YOU ARE WORKING WITH PRODUCTION DATA **

prompt: ?:  error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (/usr/local/lib/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
`

**Comment by adrianocola** [comment]
I'm with the same issue, but with the uglify grunt task! ( This task is only executed in production mode)

Sails lift with verbose log:

```sh
...
Grunt :: File .tmp/public/concat/production.css created.
Grunt :: Running "uglify:dist" (uglify) task
Lowering sails...
Sent kill signal to child process (53526)...
Shutting down socket server...
Shutting down HTTP server...
HTTP server shut down successfully.
```

If I change the grunt task config ugligy.js to the following, it works

```js
/**
 * Minify files with UglifyJS.
 *
 * ---------------------------------------------------------------
 *
 * Minifies client-side javascript `assets`.
 *
 * For usage docs see:
 * 		https://github.com/gruntjs/grunt-contrib-uglify
 *
 */
module.exports = function(grunt) {

	grunt.config.set('uglify', {
        //added this option to make uglyfication faster
        options: {
            compress: false
        },
		dist: {
			src: ['.tmp/public/concat/production.js'],
			dest: '.tmp/public/min/production.min.js'
		}
	});

	grunt.loadNpmTasks('grunt-contrib-uglify');
};

```

**Comment by greergan** [comment]
I have the same ORM error. Sails won't lift when there are models. Appears that config/orm.js is missing?

**Comment by greergan** [comment]
I uncommented config.models.migrate and things lifted.

**Comment by sgress454** [comment]
I suppose it is a bit odd for the timer to be running while the prompt is on the screen, but I think the bigger takeaway here is that the prompt is too long and no one is reading it, because it clearly says `To skip this prompt in the future, set sails.config.models.migrate.   (conventionally, this is done in config/models.js)`.  

If someone wants to make a pull request that deactivates the timeout while the prompt is up, that's fine, but consider that it will then just hang forever instead of quitting.  Either way, you're not getting your Sails app lifted without making a decision (the right one is to quit and set your migration config!)  This prompt solves the much greater problem of not choosing a migration strategy and being surprised when interesting things happen to your development data.

**Comment by greergan** [comment]
This happened to me under some circumstance where the prompt timed out immediately....

**Comment by phishy** [comment]
I get this error with no other output. Why is grunt running in production at all? Seems like doing this in production would lead to temporary downtime..

Error: The hook `grunt` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (/broad/bussys/bit-qa/app/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15) { [Error: The hook `grunt` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)] code: 'E_HOOK_TIMEOUT' }

**Comment by toledosteve** [comment]
Why is this closed?  My migration config IS set and I still receive the same error above - mine being related to "The hook `orm` is taking too long to load".  Sails was lifting just fine yesterday, no code changed, and today it won't lift due to the timeout.

**Comment by particlebanana** [comment]
@toledosteve do you have your migrate setting set to `alter`? If so as your development database grows it will take longer and longer to start until it eventually times out. You can increase your timeout or set the migrate method to `safe`. In the latest version of Waterline @dmarcelino added a `create` migrate interface so it won't migrate data but will crate new columns as you add attributes. Might be useful for you.

**Comment by toledosteve** [comment]
@particlebanana Thanks for the update!  I actually have the migrate setting to 'safe', but I did get it working by setting the hookTimeout in development.js to a higher value...setting it to 40000 worked for me.  Initially I tried setting the hookTimeout for each config - orm first, but then it squawked on views.  I set it for views and then it squawked on pubsub. I changed it for pubsub and it then it worked.  I decided to just change the hookTimeout globally as defined (http://sailsjs.org/#!/documentation/reference/sails.config/miscellaneous.html?q=sailsconfighooktimeout) here and that seemed to do the trick.

**Comment by gilesbutler** [comment]
@toledosteve I'm seeing this in production, it just randomly happened today, so just to double check, in my production.js do I add ````sails.config.hookTimeout: 40000```` or just ````hookTimeout: 40000````?

**Comment by toledosteve** [comment]
What my issue ended up being was running sails within a vagrant machine using the default synced folders...so it was independent of sails.  But setting a higher hookTimeout did allow the application to load beforehand before I discovered the vagrant issue.

Use the latter ... hookTimeout: 40000 within production.js.

**Comment by gilesbutler** [comment]
Excellent, thanks @toledosteve!

**Comment by Shekharrajak** [comment]
add this to config//orm.js 

module.exports.orm = {
  _hookTimeout: 100000 // I used 100 seconds as my new timeout
};

and may be after that you get same error for pubsub,then you need a pubsub.js in config folder

module.exports.pubsub = {
  _hookTimeout: 100000 // I used 100 seconds as my new timeout
};

**Comment by NavalKK** [comment]
Hi there, same issue is arsing whenever i am lifting my sails project. It gives the same error 'The hook `orm` is taking too long to load'. I have tried all the solutions described here but nothing changed.
Here are the full error. 

info: Starting app...

error: Grunt :: /home/naval/.gem/ruby/2.4.0/gems/sass-3.4.23/lib/sass/util.rb:1109: warning: constant ::Fixnum is deprecated
error: Grunt :: /home/naval/.gem/ruby/2.4.0/gems/sass-3.4.23/lib/sass/util.rb:1109: warning: constant ::Fixnum is deprecated
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at Timeout.tooLong [as _onTimeout] (/home/naval/PV/provakil/sails/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

please help me out.
