### ISSUE TITLE
Multiple database connections

### ISSUE THREAD

**Issue by joaolucas89** [balderdashy/sails#2681]
It's possible to have a mysql connect for each registered and authenticated client ?

For example:

I need to have a different database for each client and I wonder if you can do this with the sailsjs.

**Comment by arun057** [comment]
Its definitely possible, although it will feel a little hacky. You could do something along these lines:

https://stackoverflow.com/questions/21866476/how-to-set-database-connection-string-in-waterline-orm

You would store the database creds for each client in the master db your app is connected to and the rest of your models can connect to the client db. It might be a good idea to build a service to wrap the config change up in.

**Comment by particlebanana** [comment]
There is a [PR](https://github.com/balderdashy/waterline/pull/787) in Waterline for supporting mult-tenant databases but I'm working on moving it out into the adapter's connection logic. For now a good place to start is to override the `spawnConnection` function in mysql [here](https://github.com/balderdashy/sails-mysql/blob/master/lib/connections/spawn.js#L23) to take a config for the client and make the connection. It's not supported out of the box just yet.

**Comment by joaolucas89** [comment]
I love this guys <3

**Comment by joaolucas89** [comment]
Sailsjs, best nodejs framework <3
