### ISSUE TITLE
How to do migrations?

### ISSUE THREAD

**Issue by aaronshaf** [balderdashy/sails#2683]
How does one do migrations in sails? This isn't clear from the documentation, and the latest link via Google is down:

http://sailsjs.org/#!documentation/Migration-Guide

**Comment by joaosa** [comment]
I have the impression that link used to point to sails' version migrations and not DB ones.

**Comment by particlebanana** [comment]
@aaronshaf checkout https://github.com/BlueHotDog/sails-migrations
