### ISSUE TITLE
Supporting JavaScript Standard Style

### ISSUE THREAD

**Issue by ksaitor** [balderdashy/sails#2684]
What do you guys think about https://github.com/feross/standard ?

**Comment by tjwebb** [comment]
http://xkcd.com/927

I like standards, but most standards are not actually standards, they are just preferences that someone had the time to write down on paper. I appreciate the thought, but we haven't really had too much of an issue with coding standards clashing to a point that degrades comprehension. Do you have any examples of problems you've noticed?
