### ISSUE TITLE
Bad links in generated Sails app

### ISSUE THREAD

**Issue by scippio** [balderdashy/sails#2685]
I think there is a bad links in Sails generated pages.
Like: http://sailsjs.org/#/documentation/concepts/ORM/Models.html
But right it's: http://sailsjs.org/!#/documentation/concepts/ORM/Models.html

(sorry I don't know how to fix now (and send pull request...))

**Comment by sgress454** [comment]
Hi @scippio, good catch--you can make a PR in the [https://github.com/balderdashy/sails-generate-model](sails-generate-model) repo.  Thanks!

**Comment by scippio** [comment]
It's wrong url... I find it there: https://github.com/balderdashy/sails-generate-views/pull/6
