### ISSUE TITLE
res.body ignore empty value

### ISSUE THREAD

**Issue by martingg88** [balderdashy/sails#2689]
how to make res.body include the empty value as well?

**Comment by tjwebb** [comment]
This is not nearly enough information for us to help you with whatever it is you're trying to do.

**Comment by martingg88** [comment]
i mean res.body will ignore the empty field value when you submit the form.

here is the example.

form
---------------------------------
username : 'ck'
age : ''

finally, we will only have "username" in req.body as empty field value (etc: age) will be ignored.

**Comment by tjwebb** [comment]
You're explaining this like I've been a developer on your project team for the last 2 years. What form? Where? What does "ignore" mean? I have no idea what you're trying to do. Please post your code.

The value of `age` is an empty string. That's the value. If you don't want `age` there at all, then don't send it to the server in the body.

**Comment by martingg88** [comment]
1. form refer to "html form". 

2. age field is not compulsory. user may leave it with empty value or key in some value.
   
3. res.body must have all the submitted fields and their value (including empty value as well). 
 
    here is what i have for now when user submit html form. 
     {"username" : 'ck' }

    By right. i should have following req.body structure when user submit html form. 
    {"username" : 'ck' , 'age' : ' '}

**Comment by sgress454** [comment]
@martingg88 `req.body` should certainly include any fields submitted via a regular HTML form, empty or not.  I would check whether your fields are being sent to Sails at all.  If this is an AJAX query, it may be the case that the empty fields are being scrubbed out on the client before actually being sent to the server.

**Comment by martingg88** [comment]
Here is my request payload at client side. As based on the following request payload, i believe the all fields including empty one as well are sending to server size. 

------WebKitFormBoundaryFA2BgJN8K140BfaZ
Content-Disposition: form-data; name="username"

ck

------WebKitFormBoundaryFA2BgJN8K140BfaZ
Content-Disposition: form-data; name="age"

**Comment by martingg88** [comment]
any update?

**Comment by sgress454** [comment]
@martingg88 I was never able to reproduce this--what version of Sails are you using?

**Comment by tjwebb** [comment]
> Content-Disposition: form-data; name="username"

Where is `age`? It looks like you're just not sending the data that you say you're sending.

**Comment by martingg88** [comment]
@sgress454  i'm using 0.10.5 version. 
@tjwebb Yes. age is empty value. I want the age to be sent over the server even if user leave it empty.

**Comment by tjwebb** [comment]
No, age didn't even appear in the thing you pasted. It wasn't there at all
which means you're not sending it to the server. This is an issue with how
you're validating your form values and is not related to sails.

**Comment by sgress454** [comment]
Ah, I see now--you're using multipart encoding on the form instead of regular form encoding.  I can reproduce the same issue now.  This may in fact be an issue in Skipper.  If you don't need to send a file upload with the same form, I'd just switch to regular form encoding (`application/x-www-form-urlencoded`) and be done with it.

**Comment by tjwebb** [comment]
@sgress454 Good call. I was thinking this was a standard html form, and I also didn't expect that skipper would use multipart encoding for a form that has no file upload, so I hadn't considered that.

**Comment by martingg88** [comment]
yes...But it doesn't parse the data into json if you submit data with application/x-www-form-urlencoded.
really strange skipper behaviour

**Comment by martingg88** [comment]
checked with this https://github.com/balderdashy/skipper/pull/61/commits. 
They are trying to include empty value field..
