### ISSUE TITLE
Android emit event issue sails0.11

### ISSUE THREAD

**Issue by lhernandez772** [balderdashy/sails#2690]
Hi people, I need to use sailsjs with an app in android, my controller have this action:
	join: function(req,res) {
		//var room = req.param('room');
		if (req.isSocket) {
			console.log("Hi");
		}else {
			console.log("chao");
		}
	}

and my app tries to emit an event to server:

            String url = "http://my_host/tablet/join";
            obj.put("url", url);
            obj.put("method", "get");
            mSocket.emit("get",obj);

But the server crash with this error: 

 Error (SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ):: Failed to parse incoming socket.io request.

details: details: 'Sails v0.11.x is not compatible with the socket.io/sails.io.js client SDK version you are using (0.9.0). Please see the v0.11 migration guide on http://sailsjs.org for more information.' }

someone has the same problem?.....

**Comment by tic2000** [comment]
Did you tried to run <code>sails generate sails.io.js --force</code>?

**Comment by lhernandez772** [comment]
The sails.io.js is a client file ? Or a server file ?

if it is a client file I think not that solves the problem because what I try to do is make a similar request like socket.get but since android

**Comment by khawerrind** [comment]
I have found the issue and answered it [here](https://github.com/balderdashy/sails/issues/2640). I hope they will fix it.

**Comment by mikermcneil** [comment]
@khawerrind @lhernandez772 @tic2000 thanks guys- look for a patch release on NPM today with a fix to the generator.  Merging this issue w/ @khawerrind's (https://github.com/balderdashy/sails/issues/2640#issuecomment-76247359)
