### ISSUE TITLE
updateOneByName

### ISSUE THREAD

**Issue by albertpeiro** [balderdashy/sails#2694]
Hi there,

I think it'd be nice to have an updateOne and updateOneByName that returns a single model or null, instead of an array (updateByName).

- In mongodb it seems it'd be a matter of stubbing the native update with multi:false and then caring for responses.
http://docs.mongodb.org/manual/reference/method/db.collection.update/

- In postgress there's no native so maybe allow only over PK fields?
http://stackoverflow.com/questions/11432155/limiting-postgresql-update-command

I wanted to start a conversation as it'd be a great addition and have seen some interest:
https://github.com/balderdashy/waterline/issues?q=updateOne

What are your thoughts?
Thank you.

**Comment by particlebanana** [comment]
An `updateOne` command might be nice. It would have to only accept a primary key as a criteria though. Would you mind opening this up as an issue on the [Waterline Repo](https://github.com/balderdashy/waterline) where it can be discussed as a possible addition to the next release?
