### ISSUE TITLE
install sails failed use npm -g install sails 

### ISSUE THREAD

**Issue by M-smilexu** [balderdashy/sails#2697]
I type  npm -g install sails  and hit Enter, after a moment , It's Stuck like this , I wait like 10 minutes , nothing happend after then. ![](http://s17.mogucdn.com/b7/pic/150227/nihao_ieytqnbxgq3tomlbmyytambqmeyde_810x564.jpg),is there a solution?

**Comment by mikedevita** [comment]
what OS, and what version of nodejs? Initial global install takes a bit of time.
