### ISSUE TITLE
issue installing sails on osx

### ISSUE THREAD

**Issue by mastermind1981** [balderdashy/sails#2699]
Hi,

I have tried to install sails via npm but i have the same problem described in this issue [2678](https://github.com/balderdashy/sails/issues/2678).
My OS version is 10.10.2 and my npm version is 2.5.1, node 0.12.0. when i launch sails i got -bash: sails: command not found.
Thanks in advance.

**Comment by kriswill** [comment]
did you use sudo to install node?  if so, uninstall and install nvm (node version manager), then install node `nvm install node`, then install sails `npm -g i sails`, no `sudo` required.

**Comment by mastermind1981** [comment]
thank you for your quick response, but i had always the same problem : during the installation it fails on installing ws.
Here is the log :

sails@0.11.0 preinstall /Users/dev/.node/lib/node_modules/sails
> node ./lib/preinstall_npmcheck.js

Sails.js Installation: Checking npm-version successful
npm WARN deprecated node-switchback@0.0.4: The 'node-switchback' NPM module is now simply 'switchback'. See https://github.com/node-machine/switchback for latest docs.
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
npm WARN deprecated node-switchback@0.0.2: The 'node-switchback' NPM module is now simply 'switchback'. See https://github.com/node-machine/switchback for latest docs.
 
> ws@0.5.0 install /Users/dev/.node/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> ws@0.4.31 install /Users/dev/.node/lib/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)`

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/Users/dev/.node/bin/sails -> /Users/dev/.node/lib/node_modules/sails/bin/sails.js
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/npm requires ini@'~1.2.0' but will load
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/ini,
npm WARN unmet dependency which is version 1.1.0
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/npm requires mkdirp@'~0.5.0' but will load
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/loopback-workspace/node_modules/loopback requires inflection@'~1.3.8' but will load
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/inflection,
npm WARN unmet dependency which is version 1.2.7
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler requires inflection@'~1.3.7' but will load
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/inflection,
npm WARN unmet dependency which is version 1.2.7
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/loopback-workspace/node_modules/express requires debug@'~2.1.1' but will load
npm WARN unmet dependency /Users/dev/.node/lib/node_modules/strong-cli/node_modules/loopback-workspace/node_modules/debug,
npm WARN unmet dependency which is version 1.0.4
sails@0.11.0 /Users/dev/.node/lib/node_modules/sails
├── sails-build-dictionary@0.10.1
├── cookie@0.1.2
├── cookie-signature@1.0.4
├── grunt-contrib-copy@0.5.0
├── mock-res@0.1.0
├── connect-flash@0.1.1
├── mock-req@0.1.0
├── commander@2.1.0
├── sails-stringfile@0.3.2
├── merge-defaults@0.1.4
├── colors@0.6.2
├── pluralize@0.0.12
├── grunt-sails-linker@0.9.6
├── node-uuid@1.4.2
├── async@0.9.0
├── uid-safe@1.1.0 (base64-url@1.2.1, native-or-bluebird@1.1.2)
├── grunt-contrib-concat@0.3.0
├── reportback@0.1.8 (node-switchback@0.0.4)
├── grunt-contrib-clean@0.5.0 (rimraf@2.2.8)
├── semver@2.2.1
├── rc@0.5.5 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.3.3, minimist@0.0.10)
├── fs-extra@0.8.1 (jsonfile@1.1.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── method-override@2.3.1 (methods@1.1.1, vary@1.0.0, parseurl@1.3.0, debug@2.1.1)
├── anchor@0.10.2 (validator@3.22.2)
├── ejs-locals@1.0.2
├── ejs@0.8.8
├── grunt-cli@0.1.13 (findup-sync@0.1.3, nopt@1.0.10, resolve@0.3.1)
├── grunt-sync@0.0.8 (promised-io@0.3.3)
├── sails-disk@0.10.7 (waterline-errors@0.10.1, async@0.2.10, waterline-criteria@0.11.1, waterline-cursor@0.0.5)
├── captains-log@0.11.11 (rc@0.3.5)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── i18n@0.5.0 (sprintf@0.1.5, debug@2.1.1, mustache@1.1.0)
├── grunt-contrib-coffee@0.10.1 (chalk@0.4.0, coffee-script@1.7.1)
├── grunt-contrib-cssmin@0.9.0 (chalk@0.4.0, clean-css@2.1.8, maxmin@0.1.0)
├── grunt-contrib-jst@0.6.0 (chalk@0.4.0, grunt-lib-contrib@0.7.1)
├── include-all@0.1.6 (underscore.string@2.3.1)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, utile@0.2.1, winston@0.8.3)
├── sails-generate@0.12.2 (sails-generate-api@0.10.0, sails-generate-gruntfile@0.10.10, sails-generate-new@0.10.18, async@0.2.10, sails-generate-generator@0.10.11, sails-generate-adapter@0.10.4, sails-generate-views-jade@0.10.3, sails-generate-views@0.10.3, sails-generate-sails.io.js@0.11.5, sails-generate-backend@0.12.0, sails-generate-frontend@0.11.2, sails-generate-model@0.10.9, sails-generate-controller@0.10.7)
├── lodash@2.4.1
├── grunt-contrib-uglify@0.4.1 (chalk@0.4.0, maxmin@0.1.0, uglify-js@2.4.16)
├── sails-util@0.10.4 (json-stringify-safe@5.0.0, node-switchback@0.0.2, optimist@0.6.1, underscore.string@2.3.3)
├── grunt-contrib-watch@0.5.3 (tiny-lr@0.0.4, gaze@0.4.3)
├── waterline@0.10.18 (switchback@1.1.3, waterline-criteria@0.11.1, waterline-schema@0.1.17, bluebird@2.9.13, deep-diff@0.3.0)
├── express@3.16.0 (basic-auth@1.0.0, merge-descriptors@0.0.2, escape-html@1.0.1, range-parser@1.0.0, fresh@0.2.2, vary@0.1.0, media-typer@0.2.0, parseurl@1.2.0, methods@1.1.0, buffer-crc32@0.2.3, depd@0.4.4, debug@1.0.4, commander@1.3.2, proxy-addr@1.0.1, send@0.8.1, mkdirp@0.5.0, connect@2.25.0)
├── grunt@0.4.2 (which@1.0.9, dateformat@1.0.2-1.2.3, eventemitter2@0.4.14, getobject@0.1.0, async@0.1.22, hooker@0.2.3, nopt@1.0.10, rimraf@2.0.3, exit@0.1.2, minimatch@0.2.14, glob@3.1.21, lodash@0.9.2, coffee-script@1.3.3, underscore.string@2.2.1, iconv-lite@0.2.11, findup-sync@0.1.3, js-yaml@2.0.5)
├── skipper@0.5.5 (string_decoder@0.10.31, dot-access@0.0.3, skipper-disk@0.5.4, async@0.2.10, debug@2.1.1, multiparty@3.2.10, connect@2.25.10)
├── express-handlebars@1.0.3 (graceful-fs@3.0.5, promise@5.0.0, semver@3.0.1, glob@4.4.1, handlebars@2.0.0)
├── grunt-contrib-less@0.11.1 (async@0.2.10, chalk@0.4.0, maxmin@0.1.0, less@1.7.5)
└── sails-hook-sockets@0.11.20 (semver@4.3.1, machinepack-urls@3.1.1, socket.io@1.3.4)`

**Comment by kriswill** [comment]
@mastermind1981 it doesn’t look like you’re using nvm, unless you have it installed into ~/.node
nvm will automatically prepend the node bin path for the installed modules
I use homebrew to install nvm, so:
```sh
kris git[master] ~/src/oss/sane 
→ type npm && type node
npm is hashed (/Users/kris/.nvm/versions/io.js/v1.4.1/bin/npm)
node is /Users/kris/.nvm/versions/io.js/v1.4.1/bin/node
```
as you can see, nvm has made both npm and node available on the path.
similarly, after installing sails to global modules:
```sh
kris git[master] ~/src/oss/sane 
→ type sails
sails is /Users/kris/.nvm/versions/io.js/v1.4.1/bin/sails
```
one thing to check for is if you have a filed called ~/.npmrc, sometimes people have been instructed to manipulate this file. If you have, then it might break how npm works when installed with nvm.

**Comment by mastermind1981** [comment]
It's properly installed 
```
type npm && type node
npm is hashed (/Users/dev/.nvm/versions/node/v0.12.0/bin/npm)
node is hashed (/Users/dev/.nvm/versions/node/v0.12.0/bin/node)
``` 
and a ls in my  .~/node/bin displays 

``` 
lrwxr-xr-x  1 root  staff    35B 17 fév 17:07 bower -> ../lib/node_modules/bower/bin/bower
lrwxr-xr-x  1 dev   staff    39B 17 fév 03:16 grunt -> ../lib/node_modules/grunt-cli/bin/grunt
lrwxr-xr-x  1 root  staff    36B 17 fév 17:07 gulp -> ../lib/node_modules/gulp/bin/gulp.js
lrwxr-xr-x  1 root  staff    44B 27 fév 15:48 node-gyp -> ../lib/node_modules/node-gyp/bin/node-gyp.js
lrwxr-xr-x  1 root  staff    38B 27 fév 18:38 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x  1 root  staff    38B 28 fév 00:23 sails -> ../lib/node_modules/sails/bin/sails.js
lrwxr-xr-x  1 root  staff    33B 17 fév 17:07 yo -> ../lib/node_modules/yo/lib/cli.js
``` 
and here is the content of my .npmrc

``` 
prefix = /Users/dev/.node
prefix = /Users/dev/.node
prefix = /Users/dev/.node
prefix=/Users/dev/.node
```

**Comment by kriswill** [comment]
Right, nvm doesn't know anything about ~/.node.
```sh
$ rm -rf ~/.npmrc ~/.node
```
and now you should be able to properly install sails.

**Comment by mastermind1981** [comment]
it works great thanks you very much . 
Could you explain to me the solution why removing the folders makes it work?

**Comment by kriswill** [comment]
the .npmrc setting prefix key was causing npm to symlink the `bin/*` for any modules to `~/.node/bin/*`, when they should have been `~/.nvm/versions/{node|io.js}/v{version}/bin/*`.  nvm will set the path to the current node's global node_modules.  npm will create the symlink when installing a module that has a bin, if the .npmrc is incorrect, it will to symlink to a nonexistent file.

nvm maintains separate node_modules and npm versions for each version of node that it has installed.  so, if you were to switch node versions, the installed modules would be stable to that version.  The reason for this is that some node modules use native compilation, like bcrypt.  Each version of node has slight variations in how native interfaces are exposed, so nvm keeps your installed modules separate to compensate.

I hope that answers your question.

**Comment by mastermind1981** [comment]
Very clear so the maximum of people will profit of this explanation. Thank you once again for your reactivity. chapeau

**Comment by KennedyTedesco** [comment]
Thank you @kriswill. It works like a charm for me. =)

**Comment by bmwertman** [comment]
I'm having a similar issue when I run npm update from the project root directory. I got the following error;

    grunt-contrib-less@0.11.1 node_modules/grunt-contrib-less
    ├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
    ├── async@0.2.10
    ├── maxmin@0.1.0 (pretty-bytes@0.1.2, gzip-size@0.1.1)
    ├── lodash@2.4.1
    └── less@1.7.5 (graceful-fs@3.0.6, mime@1.2.11, source-map@0.1.43, mkdirp@0.5.0, clean-css@2.2.23, request@2.40.0)
    npm ERR! Darwin 14.1.0
    npm ERR! argv "/Users/Brad/.nvm/versions/node/v0.12.0/bin/node" "/Users/Brad/.nvm/versions/node/v0.12.0/bin/npm" "update"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! path /Users/Brad/Documents/synchro/synchroApi/node_modules/sails/node_modules/grunt-contrib-jst/node_modules/chalk/node_modules/.bin/strip-ansi
    npm ERR! code EEXIST
    npm ERR! errno -17

    npm ERR! EEXIST, symlink '/Users/Brad/Documents/synchro/synchroApi/node_modules/sails/node_modules/grunt-contrib-jst/node_modules/chalk/node_modules/.bin/strip-ansi'
    File exists: /Users/Brad/Documents/synchro/synchroApi/node_modules/sails/node_modules/grunt-contrib-jst/node_modules/chalk/node_modules/.bin/strip-ansi
    Move it away, and try again. 

My $PATH;
`/Users/Brad/.nvm/versions/node/v0.12.0/bin:`
`/Users/Brad/.nvm/versions/node/v0.12.0/bin:`
`/Users/Brad/.npm-packages/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/.npm-packages/lib/node_modules:`


Here is a link to the npm-debug.log  https://gist.github.com/bmwertman/8e8b943e7608c36286af/revisions

**Comment by mastermind1981** [comment]
have you tried this?

rm -rf ~/.npmrc ~/.node

**Comment by bmwertman** [comment]
I have and have since found that this issue was stemming from upgrading my node version to 0.12.0 using nvm while my npm version was still several versions behind. rolling node back to 0.10.34 cleared this up.
