### ISSUE TITLE
generate controller code issues when specifiying actions in command line

### ISSUE THREAD

**Issue by csharpgeek** [balderdashy/sails#2700]
Generate controller command doesn't appear to work as expected when using sailsjs v0.11.0
Issue and repro steps:
When executing the following command
![controller-command](https://cloud.githubusercontent.com/assets/11237066/6422711/8f2eada8-bed3-11e4-8340-0abac4bb5c3b.JPG)

The generated code looks like this
![generated-code](https://cloud.githubusercontent.com/assets/11237066/6422723/bd0500b0-bed3-11e4-89b6-930f427ee4f1.JPG)

The issue does not occur when no action is specified

**Comment by sgress454** [comment]
Works For Me™
Maybe your copy of `sails-generate-controller` is corrupted somehow?  You can try re-installing sails:

`sudo npm uninstall -g sails`
`npm cache clean`
`npm install -g sails`
