### ISSUE TITLE
No generator called `xxxx` found

### ISSUE THREAD

**Issue by cadrogui** [balderdashy/sails#2701]
Hello, im trying to create a generator using 
```
sails generate generator
```
sails says "info: Created a new generator!", but when i try to run the generator i get this: error: No generator called `xxxx` found; perhaps you meant `sails generate api xxxx`?

im using v 0.10.5

how can i fix this?

regards

**Comment by tvuotila** [comment]
You must first link it. Simple example:

    sails generate generator foo
    npm link ./foo
    sails generate foo faa

See ![npm docs](https://docs.npmjs.com/cli/link) for information what link command does.

**Comment by cadrogui** [comment]
thanks :smile:
