### ISSUE TITLE
Update sails model without trigger lifecycle?

### ISSUE THREAD

**Issue by pewh** [balderdashy/sails#2702]
How to update Sails model without trigger lifecycle event?
Is there any method like ```model.save({ silent: true }, callback);```?

**Comment by sgress454** [comment]
No, this isn't supported.  You can always create a model class method instead of using the lifecycle callback system!

**Comment by pewh** [comment]
Thanks for your response. Forgive me that I really don't understand what you mean. Can you explain with a code snippet?
