### ISSUE TITLE
Broken default page links

### ISSUE THREAD

**Issue by Abul22** [balderdashy/sails#2706]
Minor issue, but still.

On the 'A brand new app' default page after creating a new sails app... The links to the website are broken.

Eg. http://sailsjs.org/#/documentation/reference/blueprint-api

Clearly just missing the part /#!/ ... But yea. Fixing it might make it a tad more noob friendly :D

**Comment by sgress454** [comment]
Thanks @Abul22, fixed by https://github.com/balderdashy/sails-generate-views/commit/3e0566ca3d770a5dc41052b4b54a34d0910457e2
