### ISSUE TITLE
Unable to use sails.io.js when cross-origin. CPU meltdown.

### ISSUE THREAD

**Issue by 0x80** [balderdashy/sails#2711]
For a project I would like to keep my frontend and backend completely separated, meaning Sails will be API only and serve data over the websocket. I tried to link the sails.io.js file in my client page, but it results in my browser going nuts. It immediately starts maxing out the CPU and printing and endless stream of engine.io debug messages like this
```
sails.io.js:4 engine.io-client:polling-xhr xhr data null +0ms
sails.io.js:4 engine.io-client:polling polling got data ok +1ms
sails.io.js:4 engine.io-client:socket socket receive: type "error", data "parser error" +0ms
sails.io.js:4 engine.io-client:polling polling +0ms
sails.io.js:4 engine.io-client:polling-xhr xhr poll +1ms
sails.io.js:4 engine.io-client:polling-xhr xhr open GET: http://localhost:3000/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_s…ls_io_sdk_language=javascript&EIO=3&transport=polling&t=1425244294384-8536 +0ms
sails.io.js:4 engine.io-client:polling-xhr xhr data null +0ms
sails.io.js:4 engine.io-client:polling polling got data ok +1ms
sails.io.js:4 engine.io-client:socket socket receive: type "error", data "parser error" +1ms
sails.io.js:4 engine.io-client:polling polling +0ms
sails.io.js:4 engine.io-client:polling-xhr xhr poll +0ms
sails.io.js:4 engine.io-client:polling-xhr xhr open GET: http://localhost:3000/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_s…ls_io_sdk_language=javascript&EIO=3&transport=polling&t=1425244294386-8537 +0ms
```
I included the sails.io.js file by placing the script tag in the body of the client page like this
```
<script src="http://localhost:1337/js/dependencies/sails.io.js"></script>
```
I'm using a default fresh "sails new" install with no modifications.

**Comment by 0x80** [comment]
I have done some debugging in sails.io.js. Part or the problem seems to be that isXorigin() returns false, when it clearly shouldn't. This is because SailsSocket.url (self.url) at line 385 is undefined.

To be absolutely sure that my client server is not messing things up I served the app with `python -m SimpleHTTPServer` (defaults to port 8000), and here is the full html:
```
<html>
  <head>
    <title>Sample App</title>
  </head>
  <body>
  <script src="http://localhost:1337/js/dependencies/sails.io.js"></script>
  </body>
</html>
```

**Comment by 0x80** [comment]
Then I found this comment in the source:
```
// io.socket
    //
    // The eager instance of Socket which will automatically try to connect
    // using the host that this js file was served from.
    //
    // This can be disabled or configured by setting properties on `io.sails.*` within the
    // first cycle of the event loop.
    //
```
From this I understand that the url will be automatically set to http://localhost:1337 in my case, because that is where the sails.io.js is served from. 

So I tried to set this explicitly by adding this to my index.html:
```
 <script>
    /* globals io */
    io.sails.url = "http://localhost:1337";
</script>
``` 

This seems to solve the problem for me. Is it intended like this or should we consider it a bug that the url is not implied by the sails.io.js server url?

**Comment by sgress454** [comment]
I think the comment you're referring to is misstating the way the script works.  It will try to connect to whatever server the *client file which loaded `sails.io.js`* lives on; the comment isn't considering that you might host `sails.io.js` elsewhere.  I don't think it would even be possible for an externally-loaded  Javascript file to know what server it was loaded from.  It can only know which server the page with the `<script>` tag is on.  Incidentally, setting the connection URL to another domain is [covered in the sails.io.js docs](https://github.com/balderdashy/sails.io.js#cross-domain).

All that being said: nothing should be maxing out your CPU and making things go haywire, so if you think it's due to some problem with sails.io.js, please [post an issue in that forum!](https://github.com/balderdashy/sails.io.js/issues).

**Comment by 0x80** [comment]
Thanks I didn't know there was separate documentation for sails.io.js. This stuff is not in the compiled docs afaik. I've reported the issue balderdashy/sails.io.js#47
