### ISSUE TITLE
how can I get xml data from request in sails.js?

### ISSUE THREAD

**Issue by cage1618** [balderdashy/sails#2714]
how can I get xml data from request in sails.js?

thanks!

**Comment by MBrouns** [comment]
I dont think sails supports this out of the box but I guess you could override the default toJSON method of your model to return xml instead of json.

**Comment by randallmeeker** [comment]
http://stackoverflow.com/questions/28464786/custom-xml-response-in-sails-js-blueprint-for-a-model

**Comment by cage1618** [comment]
oh, I think we have some differences understanding about this question, I does't want to do a xml response.

I use sails create my server-side, some out request will post some data to my api with xml format, so I want to get this xml data in my api controller.

thanks!

**Comment by cage1618** [comment]
Don't hass anyone answer this question? 

I got an error in the req object:

 _fileparser:
   { req: [Circular],
     next: [Function],
     options: { maxTimeToWaitForFirstFile: 10000, maxTimeToBuffer: 4500 },
     upstreams: [],
     textParams: [],
     form:
      { _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        error: [Error: unrecognized content-type: text/xml],
        finished: false,
        autoFields: false,
        autoFiles: false,
        maxFields: 1000,
        maxFieldsSize: 2097152,
        maxFilesSize: Infinity,
        uploadDir: '/tmp',
        encoding: 'utf8',
        hash: false,
        bytesReceived: 0,
        bytesExpected: 52,
        openedFiles: [],
        totalFieldSize: 0,
        totalFieldCount: 0,
        totalFileSize: 0,
        flushing: 0,
        backpressure: false,
        writeCbs: [],
        handleError: [Function: handleError] },
     _events: { firstFile: [Object], warning: [Function] },
    ``_multipartyError: [Error: unrecognized content-type: text/xml]``,
     _hasPassedControlToApp: true },

**Comment by sgress454** [comment]
@cage1618 Thanks for using Sails!  FYI this forum is for posting bugs in the Sails core.  In the future please post support queries to [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [Gitter Chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
Sails doesn't support parsing XML bodies natively (nor does Express).  However, you can do it fairly easily by configuring some things in `config/http.js`.  First install an XML body parser:
```
npm install express-xml-bodyparser --save
```
then install Skipper for everything that's *not* XML:
```
npm install skipper --save
```
then in your `config/http.js` add:
```
  bodyParser: function(opts) {
    // Get an XML parser instance
    var xmlParser = require('express-xml-bodyparser')(opts);
    // Get a Skipper instance (handles URLencoded, JSON-encoded and multipart)
    var skipper = require('skipper')(opts);
    // Return a custom middleware function
    return function(req, res, next) {
      // If it looks like XML, parse it as XML
      if (req.headers && (req.headers['content-type'] == 'text/xml' || req.headers['content-type'] == 'application/xml')) {
        return xmlParser(req, res, next);
      }
      // Otherwise let Skipper handle it
      return skipper(req, res, next);
    };

  }
```
You can add this as a key directly under `module.exports.http`.  That should get you parsing both XML and other requests.

**Comment by LiuZeming** [comment]
thanks!

**Comment by simbacai** [comment]
@sgress454 awesome, i met this issue also, thx for your sharing

**Comment by moisesfr** [comment]
Hello,

It seems this error still persists (Node.js v4.2.3, Sails.js v0.11.3).

We've tried the proposed workaround (and a bunch more) but they didn't solve it.
Any more ideas or this is just with us?

**Comment by sgress454** [comment]
Hi @moisesfr, the underlying issues with Sails config that required different bodyparser workarounds have been fixed as of version 0.12.2.  You can check out an example of doing XML parsing at https://github.com/sails101/use-xml-body-parser.

**Comment by cybercow** [comment]
Hi all, im trying to do as suggested and used the https://github.com/sails101/use-xml-body-parser repository as example but when i lift sails i get error that the skipper module is not present:

`info: Starting app...
module.js:340
    throw err;
    ^
Error: Cannot find module 'skipper'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports.http.middleware.bodyParser (/var/www/current/use-xml-body-parser/config/http.js:79:21)
    at Object.<anonymous> (/var/www/current/use-xml-body-parser/config/http.js:91:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/local/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/usr/local/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
`

I'm on Debian 8, and using sails 0.12.3.Also tried to install skipper "manually" but that didn't helped either. Any help would be appreciated. Thank you.

**Comment by cybercow** [comment]
OK, i did overlook this part commented in **config/http.js** 

> Note that Sails uses an internal instance of Skipper by default; to override it and specify more options, make sure to "npm install skipper"  in your project first.  You can also specify a different body parser or a custom function with req, res and next parameters (just like any other middleware function). 

My first though was that as skipper is built-in by default, no extra install would be needed ... so i was confused should i install it manually or not.
