### ISSUE TITLE
Sails 0.11Websocket error with Amazon AWS EC2

### ISSUE THREAD

**Issue by m0g** [balderdashy/sails#2717]
Hi there,

I'm having trouble with using websockets on my Amazon AWS instance. I'm using Sails.js 0.11 and Socket.io 1.2.1 on both front and backend.

I'm having this error message on firefox

```
Firefox can't establish a connection to the server at ws://54.172.242.XXX/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket&sid=8T_sNPSIIJIkb9BtAAAM.
```

My ```config/sockets.js``` is basically a blank file.

I'm precising that this problem does not occur on my local development environment.

Thanks for your help

**Comment by lovemyjs** [comment]
Do you have a live example to showcase this? It'd reduce the time to attempt to try and recreate the issue.

**Comment by particlebanana** [comment]
If you are running behind ELB it doesn't support websockets and http. You can get around this by changing the `http` to `tcp` in the load balancer settings but this will have some side effects. You can read up on ELB and websockets and make a decision if that will work for you. If not socket.io should fall back to long polling.
