### ISSUE TITLE
Error: Can't set headers after they are sent in sails.js v0.11

### ISSUE THREAD

**Issue by chandradeochakravarti** [balderdashy/sails#2718]
I have upgraded my project from sails v0.9.8 to sails v0.11. When do i try to retrive data, it gives this error.

Error: Can't set headers after they are sent. at ServerResponse.OutgoingMessage.setHeader (http.js:690:11) at ServerResponse.appendHeader (/usr/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/patch.js:94:33) at ServerResponse.res.setHeader (/usr/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/patch.js:125:19) at ServerResponse.res.set.res.header (/home/abc/xyz/git/propgod-internal-V0.11/clients/web/node_modules/sails/node_modules/express/lib/response.js:577:10) at ServerResponse.res.cookie (/home/abc/xyz/git/propgod-internal-V0.11/clients/web/node_modules/sails/node_modules/express/lib/response.js:650:8) at Request.callback [as _callback] (/home/abc/xyz/git/propgod-internal-V0.11/clients/web/api/services/DataService.js:51:34) at Request.self.callback (/home/abc/xyz/git/propgod-internal-V0.11/clients/web/node_modules/request/request.js:123:22) at Request.emit (events.js:98:17) at Request. (/home/abc/xyz/git/propgod-internal-V0.11/clients/web/node_modules/request/request.js:1047:14) at Request.emit (events.js:117:20) at IncomingMessage. (/home/abc/xyz/git/propgod-internal-V0.11/clients/web/node_modules/request/request.js:998:12) at IncomingMessage.emit (events.js:117:20) at _stream_readable.js:944:16 at process._tickDomainCallback (node.js:486:13)

.

How can i enable cors for my application? 

Note : I'm loading scripts and styles using Gruntfile.js.
          I have separate modules for client and server side.

Please help me out !!!

**Comment by randallmeeker** [comment]
Please don't cross post http://stackoverflow.com/questions/28854361/error-cant-set-headers-after-they-are-sent-in-sails-js-v0-11

**Comment by sgress454** [comment]
Thanks @randallmeeker 

@chandradeochakravarti StackOverflow is a better place for questions like these.  This forum is for bug reports on the Sails core.  This is probably an implementation issue in your code, or else we'd be seeing it posted a lot more.  Also, try to ask one question per post! (CORS is a totally separate issue, and it is also [pretty well documented](http://sailsjs.org/#!/documentation/concepts/Security/CORS.html)).
