### ISSUE TITLE
sails command not found after install

### ISSUE THREAD

**Issue by lacivert** [balderdashy/sails#272]
Hello, I am using Mac and I can use npm global installations like express etc. But today I tried to install Sails globally, never was successful. Actually installation looks like ok but sails command cannot be found on terminal. How can I understand what is wrong and/or what can I do to understand the situation better?

**Comment by jaswinderwadali** [comment]
if you are on Linux / ubuntu 
run these two commands for me it works 
> alias sails="/usr/lib/node_modules/sails/bin/sails.js"
> ~/.bashrc
