### ISSUE TITLE
createdAt / updatedAt when "create" is called

### ISSUE THREAD

**Issue by stherman42** [balderdashy/sails#2721]
Hello,

Today, i was browsing on my application when my attention was catched by theses lines:

```
Creation date: 2014-12-18T13:19:26.009Z
Last update: 2014-12-18T13:19:26.010Z
```

I use sails-mongo and the document inserted has two date (createdAt and updatedAt) that are differents (this document never has been updated).

I do not have problems actually with that, but if someone want to check if a document never has been modified it can go bad.

Thanks for the attention.

**Comment by sgress454** [comment]
Thanks for the heads-up @stherman42.  Mind posting this in the [sails-mongo](https://github.com/balderdashy/sails-mongo) forum?  Thanks!

**Comment by stherman42** [comment]
No problem
