### ISSUE TITLE
Sort and Limit Parameters Blueprint Routes

### ISSUE THREAD

**Issue by mpduffey** [balderdashy/sails#2723]
When I try to set limit=-1 and a sort value in the http get request (http://my-url.com/terms?sort=title%20ASC&limit=-1) using the blueprint routes, the server responds with an empty array. Setting the limit equal to -1 as a standalone parameter works great (http://my-url.com/terms?&limit=-1), as does setting the sort parameter as a standalone (http://my-url.com/terms?sort=title%20ASC). Setting the limit parameter to a positive value along with the sort parameter also works (http://my-url.com/terms?sort=title%20ASC&limit=40). It is only when I try to set the limit value to -1 to remove any limit along with a sort parameter that I get an empty array. Am I doing anything wrong in implementing the blueprint routes?

Thanks,
Mike

**Comment by tjwebb** [comment]
> It is only when I try to set the limit value to -1 to remove any limit

Did you see this feature in the documentation?

**Comment by plabonislam** [comment]
http://my-url.com/terms??sort=title desc&limit=6
for ascending order, you don't need to mention desc  .as limit is 6 so it will return 6 data
