### ISSUE TITLE
Sails try to access production database in development

### ISSUE THREAD

**Issue by Kikobeats** [balderdashy/sails#2725]
I have different connections declared in `config/connections`. one of them is accessible only from a production environment, so basically in development I have a `localDiskDb`, `localMongoDb` and, in production I have an especial connection endpoint. I setup this in the `env` files.

I detect that in the sails bootstrapping process sails intend to connect with the production database, even though I do not use in development. I detect this because basically is not possible to access and finally the boostrapping process report a timeout:

```
verbose: Loading adapter ( sails-mongo ) for client  from `node_modules` directory...
verbose: Starting ORM...
silly: Registering model `client` in Waterline (ORM)
silly: Registering model `member` in Waterline (ORM)
verbose: Lowering sails...
verbose: Shutting down HTTP server...
error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
  at [object Object].tooLong [as _onTimeout] (/MY-APP-PATH/node_modules/sails/lib/app/private/loadHooks.js:92:21)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
 { [Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)] code: 'E_HOOK_TIMEOUT' }
```

Just works if I comment the production connection, so is not a real solution.

Is it the expected behavior of the ORM boostrapping? Why is trying to connect with production database even if I don't use in development?

my `config/models` is setup as `module.exports.models = {}`. The configuration is declared in `env` files.

**Comment by sgress454** [comment]
What exactly is in your `config/env` folder?

**Comment by Kikobeats** [comment]
in `config/connections`:

```coffee
module.exports.connections =
  localDiskDb:
    adapter  : 'sails-disk'
  localMongoDb:
    adapter  : 'sails-mongo'
    database : pkgJSON.name
    host     : 'localhost'
    port     : 27017
  # mongoProd:
  #   adapter  : 'sails-mongo'
  #   database : pkgJSON.name
  #   host     : 'SECRET_IP'
  #   port     : SECRET_PORT
```
In `config\env`:

```coffee
module.exports =
  models:
    connection : 'localMongoDb' #'localMongoDb' # 'localDiskDb'
    migrate    : 'safe' # drop
    schema     : true

  blueprints:
    actions   : true
    shortcuts : false
    prefix    : '/v2'

  log:
    level     : 'silly'
```

**Comment by sgress454** [comment]
If you have multiple accessible connections configured on the same adapter, they will all be loaded at lift time.  This is a [documented issue](http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.connections.html?q=multiple-connections-for-an-adapter).  The solution is to make a `config/env/production.js` file and store your production connection config in there; then it won't be accessible unless you lift in the `production` environment, so it won't be loaded in development.

**Comment by Kikobeats** [comment]
oh, thanks! :-)
