### ISSUE TITLE
Unable to use globally installed adapters

### ISSUE THREAD

**Issue by irobert91** [balderdashy/sails#2726]
Hello

I have been trying to launch several sails applications, all on the same machine using the same database adapter. I installed sails-mongo globally, but after I create models in an app and lift it I get an error saying that the adapter wasn't found and it should be installed in the sails app's directory.
Is there a specific reason why sails apps can't use globally installed adapters?

**Comment by tjwebb** [comment]
They are loaded dynamically at runtime, so I think you need to set your `NODE_ENV` properly to where ever your global modules are installed.

**Comment by particlebanana** [comment]
Each app will use it's own connection pool so having the adapter installed globally shouldn't make a difference. You can try and get the module_loader to load it from the globally installed location but adding the dependencies to the project will be a lot easier.

**Comment by irobert91** [comment]
Isn't this related? https://github.com/balderdashy/sails/blob/dfe6f45f900547d303e692addae4c2866b924636/lib/hooks/orm/backwards-compatibility/upgrade-datastore.js#L65

**Comment by irobert91** [comment]
I would like to be able to install sails-mongo globally and not do `npm install` in each new sails app that I create. I don't want to do other complicated settings and config to achieve that.
All I am asking is if there is a reason for the adapter to be required by it's absolute path and not just by it's name. Maybe @mikermcneil knows since he is the one that has written that code.

**Comment by loicsaintroch** [comment]
It's an issue from the ORM hook which loads the adapters from the `sails.config.appPath`. Each module uses its own `appPath`. It should load adapters from `process.cwd()` instead.

**Comment by irobert91** [comment]
But still, what happened if lines 65 to 73 (from original sails) were removed and on line 77 the adapter was required with `require(moduleName)`?

**Comment by loicsaintroch** [comment]
Didn't try but it should work fine. Do you mind writing a PR with your solution? I'll be glad to merge it. Closing this for now. Thank you for your help @irobert91.

**Comment by tjwebb** [comment]
> It should load adapters from process.cwd() instead:

What if you manually set `appPath` to something else?

**Comment by irobert91** [comment]
I would like to make a PR, but I'm not sure how to write tests for this.

**Comment by irobert91** [comment]
@tjwebb This is what I was thinking: https://github.com/irobert91/sails/commit/c9459815955f104c20088210ea21b366a310eea4

So you can install the adapter in a parent directory of the app or in the NODE_PATH and it will work.
