### ISSUE TITLE
Link broken on Read Me

### ISSUE THREAD

**Issue by pratik60** [balderdashy/sails#2733]
The following link on the read me doesn't work.....

v0.11 upgrading guide => http://sailsjs.org/#/documentation/concepts/Upgrading

An angular error in the console is what I can make out. I'd recommend you integrate http://trackjs.com/ which really helps in reporting angular errors, which otherwise can easily go unnoticed. For an open source project, you could contact them for a free plan as well.

**Comment by mikemastah** [comment]
The link appears to be missing a '!'. I made a quick pull request for this here: #2746

**Comment by efx** [comment]
This also affects links throughout the source (e.g. config/models.js) and the info message about migration settings when running `sails lift`. That message links to  http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html?q=migrate.

**Comment by tjwebb** [comment]
@rachaelshaw @mikermcneil can you check this out right quick?

**Comment by CWyrtzen** [comment]
I'll get someone to take a closer look, here is a better link: http://sailsjs.org/#!/documentation/changelog/0.11

**Comment by rachaelshaw** [comment]
@pratik60 thanks for pointing this out and for the tip about TrackJS -- I'll have to take a look at it. (And thanks @CWyrtzen for finding the link that works). Updated the readme.
