### ISSUE TITLE
Many to many relationship get by id is not working

### ISSUE THREAD

**Issue by Anandapriyan** [balderdashy/sails#2734]
I tried to create a user & pet model in Many to Many relationship using mongoDB and sailsJS, db creation and loading the data's are just fine i checked in mongoDB for dbs and collection it exists. when i try to get the user list and pet list its showing me the contents but when i try to GET a single pet by its iD under user by his iD i'm not getting result

It shows "Response does not contain any data."

I tried to get PET like this "http://localhost:1337/user/54ffd28e9d9ee93c166c7500/pets/54ffd28e9d9ee93c166c7503"

I also tried to display the pet by its name instead of iD its also not working

my sails version is 0.11.0.. my OS is Win7 64 bit

**Comment by Anandapriyan** [comment]
Hello @erkstruwe , it looks there is not problem in MAC as in https://github.com/balderdashy/sails/issues/2664 .. but still a problem in Win7. Can you please guide me to troubleshoot..

**Comment by erkstruwe** [comment]
See if this fix (taken from https://github.com/balderdashy/sails/issues/2658) helps. https://github.com/konstantinzolotarev/sails/commit/877ab3243dbcdfb3808cf52a20f0a0b8233cacb7

**Comment by Anandapriyan** [comment]
@erkstruwe  yea that fix's the bug

Thanks and regards
Anandapriyan
