### ISSUE TITLE
"Controller" suffix required?

### ISSUE THREAD

**Issue by ItsLeeOwen** [balderdashy/sails#2738]
Is it possible to run sailsjs w/out the required "Controller" suffix on controller filenames in the controller dir?

Using blueprint actions "Hello.js" with a hi method doesn't generate /hello/hi.  But the endpoint is generated when I rename the file to "HelloController.js".

I'd prefer not to use the suffix, but please update docs for clarity either way.
http://sailsjs.org/#!/documentation/reference/blueprint-api

ps.  Loving what I see so far in the framework so far!

**Comment by randallmeeker** [comment]
Ya, I often wondered why controllers have the suffix, but models, services, and policies ect . ..  don't

**Comment by tjwebb** [comment]
@ItsLeeOwen yes, the suffix is required. Maybe we'd could consider everything in controllers/ to be a controller with a route named after the module (file) name.

**Comment by loicsaintroch** [comment]
I agree with all of you guys, this suffix is pretty useless. Do you mind writing a PR @ItsLeeOwen please? I'll be happy to merge it as soon as it works.

**Comment by markelog** [comment]
Hi there, was such pr proposed? If not, would it be accepted if done correctly?
