### ISSUE TITLE
methodOverride doesn't work with '_method' param

### ISSUE THREAD

**Issue by 1tu** [balderdashy/sails#2739]
In this [file](https://github.com/balderdashy/sails/blob/master/lib/hooks/http/middleware/defaults.js), 179 line.

```
// Allow simulation of PUT and DELETE HTTP methods for user agents
// which don't support it natively (looks for a `_method` param)
methodOverride: (function() {
  if (sails.config.http.methodOverride) {
    return sails.config.http.methodOverride();
  }
})(),
```

Probably should be `return sails.config.http.methodOverride('_method');`

**Comment by ghaiklor** [comment]
@1tu by default method located in `X-HTTP-Method-Override` header. It's not an issue, just default value :smiley:

**Comment by urielhdz** [comment]
Is this available as a configuration option?
