### ISSUE TITLE
Default routes

### ISSUE THREAD

**Issue by jurajpetrik** [balderdashy/sails#2742]
So provided I have created a UserController sails automatically generates CRUD methods for me. 
E.g . 

       GET /user/:id 
       POST /user/
  
Now I want to bind this methods to functions in the UserController I created. Is there a default name sails accepts so I don't have to spell them out in config/routes?

Something like 

    var UserController = {
         	getUser : function(req, res){
                 //gets called automatically for request GET /user/:id
              }
    }

**Comment by sgress454** [comment]
There are!  They are listed in the documentation under [blueprint actions](http://sailsjs.org/#!/documentation/reference/blueprint-api?q=blueprint-actions).
