### ISSUE TITLE
ERROR cant install sails

### ISSUE THREAD

**Issue by ilyago** [balderdashy/sails#2748]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\engine.io\node_modules\ws
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

**Comment by tjwebb** [comment]
> gyp ERR! node -v v0.11.9

This is an unstable, year and a half old node release. I would try upgrading to a current node version, either 0.10.37 or 0.12.
