### ISSUE TITLE
Sails JS : Service to do json2json Conversion

### ISSUE THREAD

**Issue by rasekar2000** [balderdashy/sails#2752]
<b>Sub</b> : JSON to JSON Conversion as part of service in Sails.js . <b>Details</b> : Let us consider the simple use case that 1 User can have Many (M) Pets. Basically 1 to M entity relationship. By calling the REST API - http://localhost:1337/user/1 , we will be able to get the User and the Pet information in REST JSON format. But my Client Side --> Angular JS or jQuery requires the JSON in another format .. For e.g. to display in a Tree Structure https://github.com/aexmachina/jquery-json-list/blob/master/example.json, looking forward the best practice. <b>Thinking of this as a Solution</b> : I wanted to have a <u>server side json 2 json convertor</u>. To achieve this for e.g have additional custom methods in User Controller that can call the Sails Service ( NodeJS service) to do the JSON2JSON conversion. Considering this json-formatter to perform this conversion.. https://github.com/evenemento/json-reformatter/blob/master/test/simple.test.js Can I please know, how this Sails JS Community achieve a better server side solution? Thanks in advance.

**Comment by rasekar2000** [comment]
https://github.com/dregenor/jsonMapper is also looks clean.. Evaluating this as well for Json2Json conversion / mapping

**Comment by tjwebb** [comment]
I created a toolkit to help me map from one type of JSON *structure* to another: https://github.com/tjwebb/bijection. It's simple and clean and fast.

It currently has no feature that allows for transforming values in transit. I'd be open to extending it with this feature, though.

**Comment by rasekar2000** [comment]
Hi @tjwebb , Thanks very much for the invitation.  I was evaluating these 5, which are already in the similar objective. 

i)	json2json
https://github.com/joelvh/json2json is written in CoffeeScript and designed to run in a Node.js environment. It can be easily converted to JavaScript to be used in a browser as well. 

ii) 	json-reformatter
https://github.com/evenemento/json-reformatter/blob/master/test/simple.test.js
	→ Looks promising in javascript based conversion 

iii) 	jsonMapper 
	https://github.com/dregenor/jsonMapper
           --> Much better

ii)	NPM Json
	https://www.npmjs.com/package/json-map
	Utility to map one JavaScript object to another

iii)	JOI Format (https://github.com/hapijs/joi) @ WalmartLabs 

 Should we improvise some of them unless you have compelling performance improvement. .. Congratulations for your contribution in Github in many projects and for your blog..

Regards,
Raj

**Comment by randallmeeker** [comment]
Curious...  How are these libraries different from lodash ?

**Comment by rasekar2000** [comment]
Hi @randallmeeker ,

 Thanks very much for the pointer. I reviewed lodash documentation. It provides detailed library..
    http://stackoverflow.com/questions/25562706/use-lodash-to-transform-this-nested-json-data
     gave the confidence as well. Will evaluate and come back if required.

Thanks and Regards,
Raj

**Comment by tjwebb** [comment]
@rasekar2000 how are things going? Do you want to keep this issue open?

**Comment by rasekar2000** [comment]
Hi Travis Webb,

 Technically we can close this ticket. I moved forward with LoDash. But this provides an opportunity for an enhancement requirement for SailsJS. I mean the REST API into some other  Client Specific JSON formats.  We do have JSON Schema(http://json-schema.org/ or http://jsonschema.net) , similar to XML Schema.

   But again, I don't think, this will be highest priority, but you may consider low priority future enhancement. According to your thought, you can close this and have a separate Json2Json conversion feature issue for later action.

Thanks and Regards,
Raj

**Comment by tjwebb** [comment]
Ok thanks for your input. I'll close, and we'll revisit if this comes up again
