### ISSUE TITLE
sails-mongo native query 

### ISSUE THREAD

**Issue by lhernandez772** [balderdashy/sails#2754]
Hello people, there any way to perform a native-mongo query in sails and the objects that responds are subscribed to a socket ?

**Comment by luish26** [comment]
Hello.
 
To run a native query sails-mongo and subscribe to one socket  is NECESSARY  have the "id" key in the response object, for example, if your answer is an object with this structure {_id: 1, description: 'hello'} simply you need change the "_id" key to "id". 

The model should have this structure at the end: {id: 1, description: 'hi'}, and now you can use the subscribe method:

Model.subscribe(socketObject, {id: 1, description: 'hi'})
