### ISSUE TITLE
npm list errors

### ISSUE THREAD

**Issue by angel1st** [balderdashy/sails#2762]
Hi there,
I have application in development using Sails. These days I had to add new npm module. Doing that, I have noticed npm warning and just typed:
> npm list
for my project and I saw several unmet dependencies within Sails project.
Just to make sure this is not my fault, I have created brand new Sails project and found the same errors. Here they are:

    npm ERR! missing: lodash@~2.4.1, required by sails-disk@0.10.7
    npm ERR! missing: fs-extra@~0.8.1, required by sails-disk@0.10.7
    npm ERR! missing: lodash@~2.4.1, required by waterline-criteria@0.11.1
    npm ERR! missing: include-all@~0.1.2, required by waterline-criteria@0.11.1
    npm ERR! missing: lodash@~2.4.1, required by waterline-cursor@0.0.5
    npm ERR! missing: colors@~0.6.2, required by grunt@0.4.2
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-copy@0.5.0
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-clean@0.5.0
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-concat@0.3.0
    npm ERR! missing: lodash@~2.4.1, required by grunt-contrib-jst@0.6.0
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-jst@0.6.0
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-watch@0.5.3
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-uglify@0.4.1
    npm ERR! missing: grunt@~0.4.1, required by grunt-contrib-cssmin@0.9.0
    npm ERR! missing: commander@2.1.x, required by clean-css@2.1.8
    npm ERR! missing: lodash@^2.4.1, required by grunt-contrib-less@0.11.1
    npm ERR! missing: grunt@^0.4.0, required by grunt-contrib-less@0.11.1
    npm ERR! missing: node-uuid@~1.4.0, required by request@2.40.0
    npm ERR! missing: lodash@~2.4.1, required by grunt-contrib-coffee@0.10.1
    npm ERR! missing: grunt@~0.4.0, required by grunt-contrib-coffee@0.10.1

How can I solve all these? Is it possible they to affect my application especially in production mode?

**Comment by crh3675** [comment]
npm list is a global command, not specific to SailsJS.  Have you done an

```
npm install
```
Within the project directory? How did you install npm and sails? (global vs local)  Perhaps you have mixed installs somehow.  I typically install global:

npm
sails
mocha

**Comment by angel1st** [comment]
Hi @crh3675 I am aware that npm list is a global command. I am also aware that sails project is nothing but npm packed project. Therefore, as long as you use `npm insall` for installing the sails project, you can use `npm list` to check if the project meets all node modules' dependencies.
Answering your specific questions - all modules pointed by you above (npm, sails, mocha, forever) have been installed globally prior doing `sails new <my-project-name>`.
Even for brand new sails project I did the following:
1. `sails new my-test-project`
2. `cd my-test-project`
3. `npm install` - after that I have got:

    npm WARN unmet dependency /var/nodes/sails-ttt/node_modules/sails-disk/node_modules/waterline-criteria requires lodash@'~2.4.1' but will load
    npm WARN unmet dependency undefined,
    npm WARN unmet dependency which is version undefined
    npm WARN unmet dependency /var/nodes/sails-ttt/node_modules/sails-disk/node_modules/waterline-cursor requires lodash@'~2.4.1' but will load
    npm WARN unmet dependency undefined,
    npm WARN unmet dependency which is version undefined

so I did:
4. `npm list` and I have got the error list mentioned above in my report. For me it looks like not all node modules have successfully installed their dependencies. For instance if I look at `ejs` module, look what `npm` reports:

    ├── ejs@0.8.8 -> /usr/lib/node_modules/sails/node_modules/ejs
    ├─┬ grunt@0.4.2 -> /usr/lib/node_modules/sails/node_modules/grunt
    │ ├── async@0.1.22
    │ ├── coffee-script@1.3.3
    │ ├── UNMET DEPENDENCY colors@~0.6.2

So my understanding for the above report is that `grunt` which becomes `ejs` dependent module is missing `colors` module dependency.
What do you think?

**Comment by crh3675** [comment]
Verify those unmet dependencies are not deDependencies for each submodule by looking at package.json files for each submodule.  NPM won't install devDependencies for submodules as typically they aren't required to have the modules run correctly
