### ISSUE TITLE
I'd like to save my logging to file 

### ISSUE THREAD

**Issue by jyoungrok** [balderdashy/sails#2763]
I'm using the sails.log function 
I'd like to save this logging to file 

I've found out that i can customize config/log.js but i think it doesn't work properly
How can i save logging to file ?

**Comment by ghaiklor** [comment]
@jyoungrok you can use `custom` property in `config/log.js`. Here is example how I done this in generator - https://github.com/ghaiklor/generator-sails-rest-api/blob/dev/generators/app/templates/config/log.js#L89

```javascript
module.exports.log = {
    custom: new winston.Logger({
        transports: [
            new winston.transports.Console(module.exports.log),
            new winston.transports.DailyRotateFile(module.exports.log.dailyRotate)
        ]
    });
}
```

**Comment by jyoungrok** [comment]
thanks

**Comment by loicsaintroch** [comment]
Close this for now, feel free to reopen if you need.
