### ISSUE TITLE
use of _.each on objects 

### ISSUE THREAD

**Issue by DimitarChristoff** [balderdashy/sails#2767]
Reference: https://stackoverflow.com/questions/29161112/sails-hook-controllers-bad-register

Usecase: they have mootools/mootools-core loaded on the backend, which augments native prototypes, as well as adding hidden props to Objects constructed by Class protos like `$caller`, `$constructor` etc

https://github.com/balderdashy/sails/blob/master/lib/hooks/controllers/index.js#L90

```
					// Register this controller's actions
					_.each(controller, function(action, actionId) {
```

Controller is an object, `_.each` is array. Maybe this should be a `_.forOwn` as a comment states unwanted actions should go hidden on the proto or something. at least a mechanism for ignoring props may be an option.

**Comment by tjwebb** [comment]
> Controller is an object, _.each is array. 

`_.each` is equally applicable to objects as it is to arrays, and there's nothing wrong with this. From lodash docs:

https://lodash.com/docs#forEach
>> collection (Array|Object|string): The collection to iterate over.


> which augments native prototypes, as well as adding hidden props to Objects constructed by Class protos
If mootools is tacking junk onto `Object.prototype` in server-side node.js you're just going to have a bad time. I don't know of any

**Comment by tjwebb** [comment]
re your StackOverflow post:

> yeah, this is a problem with sails. _.each is meant to be used for iterating Objects but it will work on Arrays because they are really Objects with Array-like properties. It should get changed to _.forEach.

This statement is simply false. In lodash, _.each and _.forEach are the same thing. The lodash API docs and source code confirm this.
