### ISSUE TITLE
Maximum call stack size exceeded on blueprint route update or delete action

### ISSUE THREAD

**Issue by kmartinezmedia** [balderdashy/sails#2772]
When I try to use blueprint action's update or delete using the built in rest or shortcut routes I get this error.. I have mongodb and socket-io-redis adapters.
![screen shot 2015-03-21 at 10 35 30 pm](https://cloud.githubusercontent.com/assets/6308123/6767750/a2f2d3c0-d01a-11e4-97fb-fc4dd69125b1.png)

**Comment by weblogixx** [comment]
@kmartinezmedia:
This is a bug that I encountered, too. It has to do with toJSON methods on models that should NOT expose a toJSON method when returning the object.

Please see https://github.com/balderdashy/waterline/issues/891 for an answer.
The short way:

```
// In your model:
module.exports = {
  attributes: {
    toJSON: function() {
      var obj = this.toObject();
      obj.item = 'something';

      // #toObject does return an object that has a toJSON method, which will get called recursively in msgpack (only when using with socket.io-redis)
      // To make it work, insert the next line before returning your object
      // Note! This is a ugly workaround, I will try to dig deeper in this and maybe find a nicer solution
      obj.toJSON = null;
      return obj;
    }
  }
};
````

**Comment by kmartinezmedia** [comment]
great thank you!

**Comment by CWalig** [comment]
@kmartinezmedia @weblogixx thanks 👍 
I will keep an eye on the other issue.

**Comment by tjwebb** [comment]
Yep, moving over to balderdashy/waterline#891.
