### ISSUE TITLE
Assets are not being reloaded with new content. Getting 304 response

### ISSUE THREAD

**Issue by arcoirislabs** [balderdashy/sails#2777]
While using the framework in Windows 7, new assets are not being loaded. If any changes are made in  any JS file present in assets, the changes are not downloaded. After numerous refresh requests, still getting 304 response for JS and CSS files after editing them.

**Comment by cyrilchapon** [comment]
Hello,

> While using the framework in Windows 7
You mean you lifting from W7 or browsing from W7 ? Both ?
If browsing, which browser it is ? Did you try another ?

**Comment by arcoirislabs** [comment]
While doing both. Happens in Google Chrome Version 41.0.2272.101. No I haven't tried on another browser.

**Comment by sgress454** [comment]
Sounds like something is preventing the Grunt "watch" task from running.  You can lift your app with:

```
sails lift --verbose
```

then change a file in your assets folder and see if Grunt responds.

Without more info on this (or other reports of users seeing similar behavior) there's not much that can be done.  If more info comes to light, please re-open.
