### ISSUE TITLE
SailsJs Stable 0.9.16

### ISSUE THREAD

**Issue by crh3675** [balderdashy/sails#2781]
We actively use https://github.com/balderdashy/sails/releases/tag/v0.9.16
The main reason is because it is labeled "stable".  Understanding migration plans to 0.1x would be probably some heavy lifting at this point, we are quite happy with 0.9.16.  Do you plan to change the "stable" version anytime soon? Would we benefit from "a lot" or just inherit code cleanup and code consolidation behaviors?

As a software dev myself, I hesitate to change "what works" and 0.9.16 works for us.  I just want to make sure all bases are covered so I can reiterate to other team members that although we run version 0.9.16, it is functionally equivalent to more recent versions.

**Comment by tjwebb** [comment]
0.10 is the latest stable release; perhaps we're not as clear as we could be on this. Migration from 0.9 to 0.10.x should be fairly straightforward.

Have you tried to migrate anything yet? Let me know if we can help.

**Comment by CWyrtzen** [comment]
@crh3675 have you tried migrating yet?

**Comment by crh3675** [comment]
I have a test instance running. No migration as our version is still pretty stable. I will probably build our new project on the latest version.  Thanks for checking up!

**Comment by tjwebb** [comment]
As of today, 0.11 is the latest stable release.
