### ISSUE TITLE
I wonder if i can configure specific setting in Blueprint api 

### ISSUE THREAD

**Issue by jyoungrok** [balderdashy/sails#2782]
Ive found that using Blueprint API is very convenient way to develop sails server
However, if i set "rest" to true in config/blueprint.js, i should block some Restful api i didn't develop  by using config/policy.js.

If i coud set Resful API to only enable the route api i defined,  it would be very convenient
For example, if i make User model and define "find" and "create" actions in UserController.js , only POST and GET routes should be enabled

Are there any way i mentioned above ?
If there are not, do you have any plan to develop that?

**Comment by tjwebb** [comment]
You can do this with the sails routes config: http://sailsjs.org/#!/documentation/concepts/Routes
