### ISSUE TITLE
io.socket._raw undefined in production

### ISSUE THREAD

**Issue by angel1st** [balderdashy/sails#2786]
I have already post this in SailsJS group. As long I I didn't get real explanation, I will just post it here as well: https://groups.google.com/forum/?hl=en#!topic/sailsjs/wVW-bGB9c-0
Regarding the above inquiry - my bottom line question is:

***How can I obtain raw socket.io from the io.socket sails instance, when it is already initialized?***

**Comment by tjwebb** [comment]
@mikermcneil do you have any quick insight on this?

**Comment by sgress454** [comment]
@angel1st Google Groups was the right place to post this; I answered your question there.  This forum is for bugs in Sails core.  If you think you've found a bug in sails.io.js, there's a [repo for that too!](https://github.com/balderdashy/sails.io.js).
