### ISSUE TITLE
Blueprint actions not capturing data

### ISSUE THREAD

**Issue by lmchawla** [balderdashy/sails#2790]
Blueprint actions are not capturing data, even when it returns 201, creates a resource with only createdAt, updatedAt timestamps and _id but no other params are captured.
sails -v 0.11.0.

I then tried to create a create controller myself and noticed that req.params.all() gave output as true which is not the expected output.
 Then I tried replacing req.params.all() with req.allParams() and it gave the expected output

I noticed that definition of actionUtil.parseValues has a line..
var values = mergeDefaults(req.params.all(), _.omit(req.options.values, 'blacklist'));
Replacing req.params.all() with req.allParams() solves the issue.

**Comment by tjwebb** [comment]
> not capturing data
Please help me with what "capturing data" means.
