### ISSUE TITLE
Using Services modifies constructor functions

### ISSUE THREAD

**Issue by bberry6** [balderdashy/sails#2791]
Example Code: https://bpaste.net/show/7c80367ce3a9

I know printing \_\_proto\_\_ isnt exactly best practices, but it serves my purpose here.  

When using a service to create, for example, an errors object, that constructs specific Errors for me.  In practice, I use this in bluebird promises `.catch()` to catch specific errors, like

```javascript
.catch(ErrorService.MyFirstError, function(err){ 
   // handle error
});
```

However, it appears that using a service to return constructors removes the prototype, and returns the basic object instead.

For now, we have put our error service in a separate file and are using `require()`.

Is this is intentional by sails to disallow constructor functions in Services?

**Comment by nozer** [comment]
+1

**Comment by tjwebb** [comment]
> it appears that using a service to return constructors

Yea, a service is expected to be an object, not a function.

**Comment by tjwebb** [comment]
```
module.exports = (function(){
   _.each(ErrorService, function(item, k){

      ErrorService[k].prototype = Object.create(Error.prototype);
      ErrorService[k].prototype.constructor = item;
   });
   return ErrorService;
}());
```
This is abstract and complicated. A service is designed to just be an object of static functions. What are you trying to accomplish here?

**Comment by bberry6** [comment]
Essentially, we're just trying to pass an object that contains a set of constructor functions.  A very simple version might be....

```javascript
// sails/api/services/EmployeeService.js

// constructor function for Employee
function Employee(title){
   this.title = "Janitor";
}

module.exports = {Employee: Employee};
```

and then in a controller...

```javascript
// /sails/api/controllers/FooController.js


var EmployeeRequired = require('../some/path/EmployeeService.js');
// this is the same file as above, but outside of the services directory


module.exports = {
   foo: function(req, res){
      // this uses sails services
      var person = new EmployeeService.Employee('Janitor');
      console.log(person instanceof EmployeeService.Employee); // false
      return res.send(200);
   }
   bar: function(req, res){
      // this uses a require'd file
      var person = new EmployeeRequired.Employee('Janitor');
      console.log(person instanceof EmployeeRequired.Employee); // true
      return res.send(200);
   }
}
```

**Comment by tjwebb** [comment]
Ok I see. @mikermcneil any thoughts on this?

**Comment by tjwebb** [comment]
@bberry6 @nozer could either of you submit a PR with a fix for this?
