### ISSUE TITLE
model.native, aggregate function

### ISSUE THREAD

**Issue by ivan-koval** [balderdashy/sails#2795]
Aggregate function does not work.

Sails version 0.11.0

What am I doing:

    test: function (q, s) {
        Test.create([{name: 'one', g: 'g1'}, {name: 'two', g: 'g2'}]).exec(function (err, test) {
          Test.native(function (err, collection) {
            collection.aggregate({$group: {_id: "$g"}}).toArray(function (err, tests) {
              s.json(tests);
            });
          });
        });
      }

Test model has 'name' and 'g' attributes.

collection.aggregate returns undefined.

**Comment by crh3675** [comment]
Do you mean the results of "tests" in the callback are undefined?  Can you verify your Mongo version is compliant with the query logic?  Also, does "aggregate" use the Promise structure or a callback? If it uses  the callback, you would need to pass that as the final function in your function call.

```
test: function (q, s) {
    Test.create([{name: 'one', g: 'g1'}, {name: 'two', g: 'g2'}]).exec(function (err, test) {
      Test.native(function (err, collection) {
        collection.aggregate({$group: {_id: "$g"}}, function(err, results) {
          results.toArray(function (err, tests) {
             s.json(tests);
          });
       });
      });
    });
  }
```

**Comment by ivan-koval** [comment]
I meant, when `collection.find` returns object, `collection.aggregate` returns undefined.

I read documentation one more time carefully. It uses callback. It works as expected, maybe I just did something wrong in the first time.
[This](http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#aggregate) worked for me. It was my mistake.
