### ISSUE TITLE
custom 'updatedAt' ignored

### ISSUE THREAD

**Issue by OriTheMan** [balderdashy/sails#2800]
sails version: 0.11.0

i configured in the model: 
updatedAt: {
			type: 'datetime',
			defaultsTo: function (){ return Math.round(new Date().getTime() / 1000); }
		}
but its continue insert json date value.

**Comment by Josebaseba** [comment]
Try with this model setting: 
```javascript
autoUpdatedAt: false
```
More info here: http://sailsjs.org/#!/documentation/concepts/ORM/model-settings.html

**Comment by OriTheMan** [comment]
Now it's not updated because its disable the auto action.

**Comment by Josebaseba** [comment]
in the model.js file:

```javascript

beforeUpdate: function(values, next){
     values.updatedAt = Math.round(new Date().getTime() / 1000);
     return next();
}

```

**Comment by tjwebb** [comment]
Does this help? http://stackoverflow.com/a/24562385/291180

**Comment by Josebaseba** [comment]
It's just the same solution that I said. It works fine, I think that we can close this issue.
