### ISSUE TITLE
Blueprint actions not binding if corresponding model doesn't exist

### ISSUE THREAD

**Issue by jurajpetrik** [balderdashy/sails#2802]
$ sails generate api Image
     //inside of ImageController.js
     find: function(req,res){
        	res.send('so you want some image');
      }
     $ sails lift
     $ curl localhost:1337/image
     $ so you want some image%                               
     $ rm api/models/Image.js
     $ sails lift
     $ curl localhost:1337/image
     $ 404

Is this the expected behaviour? Sure doesn't seem so.

**Comment by tjwebb** [comment]
If there's no `Image` model but you're requesting it anyway, what do you expect the server to return?

**Comment by jurajpetrik** [comment]
I'm expecting the server to forward the GET request to /image to ImageController.find()

**Comment by tjwebb** [comment]
Did you implement your own find method? The default find method queries the
model, which doesn't exist.

**Comment by jurajpetrik** [comment]
yes, I mentioned it in the first post, you must've missed it:

      $ sails generate api Image
       //inside of ImageController.js
       find: function(req,res){
              res.send('so you want some image');
        }

**Comment by tjwebb** [comment]
What about if you access /image/find?

**Comment by jurajpetrik** [comment]
That one works correctly

**Comment by tjwebb** [comment]
Do you have shortcuts enabled in blueprints?

**Comment by jurajpetrik** [comment]
yes, I didn't touch blueprint. If you create a new sails project and follow what I wrote in the first comment, I'm sure you will be able to reproduce the bug.

**Comment by sgress454** [comment]
This is the expected behavior.  CRUD blueprints are intended to link models and controllers; without a model, Sails doesn't assume that "find" has a special meaning for you.  You can always bind the route yourself in `config/routes.js`.

Note that the `ImageController.index` action (if it exists) will still be automatically bound to `/image` route in this case.
