### ISSUE TITLE
sailsjs.org not working in mac firefox

### ISSUE THREAD

**Issue by udanpe** [balderdashy/sails#2805]
Reference doc not working.

**Comment by tjwebb** [comment]
If you're able to be more descriptive, we can look into it.

**Comment by udanpe** [comment]
Navigation on documentation not working. When you go to website from google you see only title list and nothing more. When you click for some menu you have error. When I readed site two month ago i sing you dont have documentation)

mozilla firefox 36.0.4
macos 10.10.2

window.controllers is deprecated. Do not use it for UA detection. nsHeaderInfo.js:412:0
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] like.php
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. production.js:3:0
window.controllers is deprecated. Do not use it for UA detection. nsHeaderInfo.js:412:0
"Error: [$location:ihshprfx] http://errors.angularjs.org/1.2.16/$location/ihshprfx?p0=http%3A%2F%2Fsailsjs.org%2F%23%2Fdocumentation%2Fconcepts%2FPolicies&p1=%23!
d/<@http://sailsjs.org/min/production.js:6:29036
_a/this.$$parse@http://sailsjs.org/min/production.js:9:4238
db/this.$get</</<@http://sailsjs.org/min/production.js:9:5937
qb/this.$get</k.prototype.$eval@http://sailsjs.org/min/production.js:9:16569
qb/this.$get</k.prototype.$digest@http://sailsjs.org/min/production.js:9:15137
db/this.$get</<@http://sailsjs.org/min/production.js:9:6050

**Comment by udanpe** [comment]
Sorry. Not working with plugin "live http headers"

**Comment by tjwebb** [comment]
> Not working with plugin "live http headers"

What does that mean?

**Comment by udanpe** [comment]
with this extension site not working
https://addons.mozilla.org/En-us/firefox/addon/live-http-headers/
