### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by rachaelshaw** [balderdashy/sails#2806]
I suggest changing the name of the framework, because it's not clear where the S in Sails comes from. IMO the framework would be a lot friendlier-sounding if it had a name that alliterates with the technologies it's built on top of, such as:

Nails.js (because Node.js)
Jails.js (because JavaScript)

**Comment by mikermcneil** [comment]
Good idea

**Comment by mikermcneil** [comment]
Send a pr

**Comment by particlebanana** [comment]
<april fools joke>

**Comment by RWOverdijk** [comment]
A bit late for an april fools joke. :)

**Comment by tjwebb** [comment]
just straight up call it rails.js and see what happens.

**Comment by rachaelshaw** [comment]
good idea.
