### ISSUE TITLE
Ignoring defaultLimit in controller config extending

### ISSUE THREAD

**Issue by swarthy** [balderdashy/sails#2809]
Hi, everyone!
Extending config in controller
` _config:
defaultLimit: 100
`
does not work.
Seems like [this](https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actionUtil.js#L284) is reason.

**Comment by tjwebb** [comment]
What version of sails are you using?

**Comment by swarthy** [comment]
sails v0.11.0
failing test example:
I have User model in api/models/User.js
and controller api/controllers/UserController.js
`module.exports = {
    _config: {
      defaultLimit: 2
    }
}`
Request to /user returns 30 (default in sails.config.blueprints.defaultLimit) users, not 2.

**Comment by tjwebb** [comment]
@swarthy interested in offering a PR with a fix?

**Comment by swarthy** [comment]
https://github.com/balderdashy/sails/pull/2846

**Comment by swarthy** [comment]
Solution: https://github.com/balderdashy/sails/pull/2846#issuecomment-94244592
