### ISSUE TITLE
How to use Array attributes in sailsjs model

### ISSUE THREAD

**Issue by Anandapriyan** [balderdashy/sails#2810]
Hi i am a new bee to sails and trying to get a model api that finally gives output as follows

[ 
  { 
    "icon" : [ 
      {"name":"ico1", "ico_typ":"fb", "ico_content_URL":"someLocation"},
      {"name":"ico2", "ico_typ":"tw", "ico_content_URL":"someLocation"},
      {...}
      ]
      "createdAt":
      "updatedAt":
     
  } 
]

I thought i can achieve this by passing the icon attribute as an Array but the problem is it passes the whole Array as string when i load it in REST CLIENT also i could not use the validation for values inside Array like without ico_type and URL the data should not be loaded into database. So, any suggestion about use of the 'array' where i'm wrong is very appreciated, thanks so much! Sails_v0.11.0 MongoDB_3.0.1

**Comment by jurajpetrik** [comment]
Your question isn't clear to me. I assume you have a model can contain many icons? If so, than you should define a one to many association. See here
https://github.com/balderdashy/waterline-docs/blob/master/associations.md

**Comment by Anandapriyan** [comment]
Yea it's one to many association so that we can acehive it by two model.js

**Comment by Anandapriyan** [comment]
yes it can be achieved through one to many association but my aim is since sails attributes can be passed as array and json can we do validation for the values inside array or json like we do in plain models?

**Comment by jurajpetrik** [comment]
Let's say the encompassing object to Icon is Image.


       icons = [ 
       {"name":"ico1", "ico_typ":"fb", "ico_content_URL":"someLocation"},
       {"name":"ico2", "ico_typ":"tw", "ico_content_URL":"someLocation"}];
     Image.findOne(someId).exec(function(err,image){
        if (err) throw err;
        image.icons.add(icons);
        image.save();
     });

Now all the validations will be done on the Icon attributes.

**Comment by crh3675** [comment]
It looks more to me of a Model with an attribute called "icon" with type "json"

```
module.exports = {
    attributes : {
        icon : {
            type  : 'json'
        }
    }
}
````

**Comment by tjwebb** [comment]
You'll just want to write a validator function that inspects the json object. This is an option that might help with that: https://github.com/tjwebb/congruence

**Comment by Anandapriyan** [comment]
ty @tjwebb
