### ISSUE TITLE
Irregular pluralisation support?

### ISSUE THREAD

**Issue by tibotiber** [balderdashy/sails#2811]
Hi, I couldn't find mentions about the support of irregular plurals when settings `pluralize: true` on the blueprints. Is that supported? Thanks.

**Comment by tjwebb** [comment]
Pluralization support is handled through https://www.npmjs.com/package/pluralize.

Do you have a specific example?

**Comment by tibotiber** [comment]
So pluralize is taking care of irregular plurals automatically? I did observe that say "currency" was well pluralized to "currencies". What if I need to use specific technical vocabulary down the road and pluralize does not respond properly? Is there any way to manual specify the plural? Sorry I don't really have a example offhand.

**Comment by Globegitter** [comment]
@tibotiber IF you look here in the code https://github.com/blakeembrey/pluralize/blob/master/pluralize.js#L235 you can see that a lot of irregular verbs are being taken care of, as well as a lot of different rules. In case an english word that does get pluralised wrong it is probably best to PR there and then update the module here in sails.

Hope that clarifies your question. Let me know if you need anything else.

**Comment by tibotiber** [comment]
That's great. Thank you @Globegitter.
