### ISSUE TITLE
CSRF Mismatch after restart

### ISSUE THREAD

**Issue by ryanfields** [balderdashy/sails#2812]
Restarting the Sails server causes socket clients to receive a CSRF mismatch error.

Before each request, I'm performing an ```io.socket.get('/csrfToken', ...)```.  This works fine until the Sails server is restarted.  When the socket reconnects, calls to /csrfToken receive valid-looking tokens, but those tokens are refused.  The only way to fix the error is to refresh the browser client.  This makes socket-reconnecting useless, since the app cannot continue to operate without a page refresh.

**Comment by tjwebb** [comment]
What version of sails are you using?

**Comment by crh3675** [comment]
Is your session handler persistent (mongo, mysql, etc) or memory?

**Comment by ryanfields** [comment]
@tjwebb Using 0.11.0.

@crh3675 Memory, but according to the Sails log I've established a new session before I make the GET /csrfToken request.  I'm puzzled as to why a fresh session and a subsequent fresh CSRF token would fail.

Here's how it looks in the logs.

Restart Sails
```
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Users/crimsonfox/Development/Projects/JavaScript/gatestaff2-api`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue Apr 07 2015 22:55:30 GMT-0400 (EDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

<...some unrelated stuff removed from here...>

verbose: A socket is being allowed to connect, but the session could not be loaded.  Will create an empty, one-time session to use for the life of the socket connection.  Details:
 Error: Session could not be loaded
    at _createError (/usr/local/lib/node_modules/sails/lib/hooks/session/index.js:271:21)
    at Immediate._onImmediate (/usr/local/lib/node_modules/sails/lib/hooks/session/index.js:274:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17) { [Error: Session could not be loaded] code: 'E_SESSION' }
```

And then my next request:

```
verbose: Receiving incoming message from Socket.io:  { method: 'get', headers: {}, data: {}, url: '/csrfToken' }
verbose: Interpreting socket.io message as virtual request to "get /csrfToken"...
```

Gives me token ```XbNtrH1Y-SMdVM9g20ik2BNFJfJXAnHjsfmw```.
With that token, I make a request:

```
verbose: Receiving incoming message from Socket.io:  { method: 'post',
  headers: {},
  data: 
   { email: 'test',
     password: 'pass',
     _csrf: 'XbNtrH1Y-SMdVM9g20ik2BNFJfJXAnHjsfmw' },
  url: '/auth/local' }
verbose: Interpreting socket.io message as virtual request to "post /auth/local"...
verbose: Sending 403 ("Forbidden") response: 
 CSRF mismatch
```

From the logs, it looks like I have a new session, and I'm fetching a fresh CSRF token before making my next request.  Is there something special about the one-time session that invalidates all CSRF tokens?

**Comment by ryanfields** [comment]
I switched over to Mongo as my session store and the problem goes away.  It appears to be limited to the default session store.

**Comment by tjwebb** [comment]
You mean redis?

**Comment by crh3675** [comment]
@ryanfields Good to hear.  The in memory session storage doesn't persist between restarts as it uses a global Javascript object during startup.  When the NodeJS process stops, garbage collection releases all runtime variables.

**Comment by tjwebb** [comment]
Ah I see now where they say they're using sails-memory. Yea that's not persisted, and you'll definitely get a new session on restart. Thanks everyone for following up.

**Comment by ryanfields** [comment]
The issue wasn't about session persistence though.  I know that the session is wiped between restarts.  The question is why do CSRF tokens issued AFTER the restart get treated as invalid.  Sails restarts, I get a new session, and THEN I ask for new CSRF tokens.  Why are they rejected?
