### ISSUE TITLE
sails.io.js errors with l __getcookie net::ERR_CONNECTION_CLOSED trying to connect to my Sails API

### ISSUE THREAD

**Issue by bmwertman** [balderdashy/sails#2818]
I'm running Sails v0.11.0 for an API to my AWS relataional database.

 I have installed sails.io.js via bower. sails.io.js installed at v0.11.5

I'm serving my Ionic application with sails.io.js installed from localhost:8100. It has the following script tags in index.html;

    `<script src="lib/socket.io-client/socket.io.js"></script>
    <script src="lib/sails.io.js/sails.io.js"></script>
    <script>io.sails.url = 'https://localhost:1337/';</script>`

I serve my sails API from localhost:1337.

As soon as I start my Ionic server with the Sails server running I get an error in the console.

`GET https://localhost:1337/__getcookie net::ERR_CONNECTION_CLOSED sails.io.js:205`

If I remove the '<script>io.sails.url = 'https://localhost:1337/';</script>` from my index.html it repeatedly tries to connect to localhost:8100 with the following error;

`GET                                                                                                                             socket.io.js:2919 
http://localhost:8100/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_s…sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1428417501863-3 404 (Not Found)
17.Request.createsocket.io.js:2842 Requestsocket.io.js:2773 17.XHR.request    socket.io.js:2803 
17.XHR.doPollsocket.io.js:3192 18.Polling.pollsocket.io.js:3136 socket.io.js:2919
18.Polling.doOpensocket.io.js:2313 
14.Transport.opensocket.io.js:1743 
13.Socket.opensocket.io.js:1625 
Socketsocket.io.js:1560 
Socketsocket.io.js:299 
3.Manager.open.Manager.connectsocket.io.js:564 (anonymous function)
sails.io.js:136  
        Socket is trying to reconnect to Sails...
_-|>_-  (attempt #4)`

**Comment by tjwebb** [comment]
> It has the following script tags in index.html;

Are these inside of `<head>` ?

**Comment by bmwertman** [comment]
Yes in the head tag.

I think the problem may be solved though. See [my SO post](http://stackoverflow.com/questions/29440979/make-web-socket-connection-between-ionic-app-to-sails-api-with-sails-io-js/29455389?noredirect=1#comment47107883_29455389). Matan suggested adding `io.sails.useCORSRouteToGetCookie = false` in the script tag in the `<head>`  

It now connects with no errors. I was able to make a request with `io.socket.get('/', function(){console.log(results)});`

But @sgress454 mentions [here](https://github.com/balderdashy/sails.io.js/issues/15) "If you don't need socket support, just set io.sails.useCORSRouteToGetCookie to false." 

Does that mean this somehow isn't a true socket connection?

**Comment by tjwebb** [comment]
Ok thanks for following up. I'm going to close since you've figured out the issue, but I'd still like to see what insight @sgress454 has to offer on this.
