### ISSUE TITLE
connect-redis 1.4.5 adapter causing sails crash

### ISSUE THREAD

**Issue by danscan** [balderdashy/sails#2819]
I've been experiencing a crash on the event of a subsequent request after creating a new session on my sails API.  I've been using the redis adapter (`connect-redis 1.4.5`), and it's been crashing every time.

Here are logs for context: https://gist.github.com/danscan/ddfc66398218940c02c8

Any ideas?

**Comment by tjwebb** [comment]
The whole trace is inside new relic code; can you post your code so we can see where this occurs?

**Comment by danscan** [comment]
Which code would you want me to post?  

Sails Version: 0.11.0
Node Version: 0.12.0

Running on a Deis PaaS (very similar to Heroku, but private).  The redis instance I'm using is a deployment on Compose.  When I switched to the default memory adapter for sessions, I no longer encountered the crash, but obv can't keep this in production.

**Comment by tjwebb** [comment]
Um, good point. Is your project public? Have you tried a different redis host?

**Comment by danscan** [comment]
My project isn't public.  It's my company's new api.  We're loving sails btw ;).  Haven't tried a different redis host yet either.  I'll give it a shot and report back.

**Comment by tjwebb** [comment]
Ok, try anothe redis host and let me know. It's hard to help debug without the source; if you'd like to discuss further in private, feel free to drop me a line: tjwebb@balderdash.co.

Glad you're loving sails.js! We <3 sails as well.

**Comment by danscan** [comment]
@tjwebb Hey, I got to the bottom of this.  It was actually an uncaught error from the http-proxy module that couldn't be caught in a promise chain.  The logs were getting lost in the abyss of the new relic agent, and so I was only observing that it would go down after express-session would save a session instance.

Ironically, I only figured it out after disabling new relic ;)

**Comment by danscan** [comment]
Btw, I'm referring to my application's implementation of http-proxy, not anything in Sails.
