### ISSUE TITLE
npm install sails tries to install less at version 1.7.5

### ISSUE THREAD

**Issue by bmwertman** [balderdashy/sails#2826]
I'm installing sails on Ubuntu with; 
node -v 0.12.2 
and npm -v 2.7.4.

`npm install sails` errors with
> sails@0.11.0 preinstall /home/ubuntu/sails/node_modules/sails
> node ./lib/preinstall_npmcheck.js

>Sails.js Installation: Checking npm-version successful
>npm WARN deprecated node-switchback@0.0.4: The 'node-switchback' NPM module is now simply 'switchback'. See https://github.com/node-machine/switchback for latest docs.
>npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
>npm WARN deprecated node-switchback@0.0.2: The 'node-switchback' NPM module is now simply 'switchback'. See https://github.com/node-machine/switchback for latest docs.
>npm WARN optional dep failed, continuing uglify-js@2.3.6
>npm ERR! Linux 3.16.0-5-generic
>npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "sails"
>npm ERR! node v0.12.2
>npm ERR! npm  v2.7.4
>npm ERR! file /home/ubuntu/.npm/less/1.7.5/package/package.json
>npm ERR! code EJSONPARSE

>npm ERR! Failed to parse json
>npm ERR! No data, empty input at 1:1
>npm ERR! 
>npm ERR! ^
>npm ERR! File: /home/ubuntu/.npm/less/1.7.5/package/package.json
>npm ERR! Failed to parse package.json data.
>npm ERR! package.json must be actual JSON, not just JavaScript.
>npm ERR! 
>npm ERR! This is not a bug in npm.
>npm ERR! Tell the package author to fix their package.json file. JSON.parse

>npm ERR! Please include the following file with any support request:
>npm ERR!     /home/ubuntu/sails/npm-debug.log

Seems to be pointing at an old version of less 1.7.5. I'm able to `npm install less` at 2.5

**Comment by bmwertman** [comment]
It looks like bumping grunt-contrib-less to version 1.0.1 and grunt to version 0.4.5 in Sails' package.json solves this

**Comment by bmwertman** [comment]
I forked sails, made the version bumps on grunt and grunt-contrib-less and attempted npm install with the tarball url. 

No, error on less, but similar error on socket.io-parser

    npm ERR! Linux 3.16.0-5-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "https://github.com/bmwertman/sails/tarball/master"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! file /home/ubuntu/.npm/socket.io-parser/2.2.4/package/package.json
    npm ERR! code EJSONPARSE

**Comment by tjwebb** [comment]
Are you sure this isn't an issue that's local to your machine? Have you tried this anywhere else?

**Comment by bmwertman** [comment]
It seems to be particular to the EC2 Ubuntu instance I'm running on Amazon Web Services. But, I'm able to install other packages there through npm without issue. 

I tried `npm install sails`  = errors about less 

I bumped the versions of grunt and grunt-contrib-less on a sails fork and `npm installed tarball url`  = errors about socket.io-parser 

I` npm install sails --no-frontend` = errors about less

I `npm instal`l bumped grunt/grunt-contrib-less tarball url = errors bout socket.io-parser

`npm install less` = works no problem

`npm install grunt` = works no probelm

**Comment by particlebanana** [comment]
Hey @bmwertman do you the build essentials package installed? I think the socket.io-parser compiles some stuff. Just a shot in the dark.

```
sudo apt-get install build-essential
```

**Comment by bmwertman** [comment]
Hey @particlebanana build-essential package installed. Just ran the command again to be sure. 

I get the same error on less running `npm install sails` and the socket.io-parser error on `npm install` of my forked repo with versions of grunt and grunt-contrib-less bumped.

 For reference I was following [this blog post](https://saintcoder.wordpress.com/2014/05/29/deploying-sails-js-web-application-on-aws-ec2-instance/#comment-248) to get my environment setup.

**Comment by tjwebb** [comment]
> git clone https://github.com/joyent/node.git

Are you really using the `master` branch of node? I would not do this. I'd recommend installing [**n**](https://github.com/tj/n) to manage versions, and use stable releases.

**Comment by bmwertman** [comment]
No sorry @tjwebb. I followed [this](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager)  for the node install.

**Comment by tjwebb** [comment]
Alright. @bmwertman go ahead and follow up here (http://stackoverflow.com/q/29542752/291180) since I don't think this is a sails.js issue.

**Comment by Christianjuth** [comment]
Error code `EJSONPARSE` is an issue with the `package.json`. When you install a node package it stores the `package.json` file in a `.npm` folder. It seems you have a corrupted less 1.7.5 package file downloaded in your `.npm` folder.

Run the following command:
```shell
sudo rm -rf /home/ubuntu/.npm/less/1.7.5/
```

This removed the local less `package.json` file on your computer so it pulls from NPMs servers. Now you can try installing Sails again.
