### ISSUE TITLE
Error: model.update()

### ISSUE THREAD

**Issue by Oldwo1f** [balderdashy/sails#2828]
Hi,
 i got a strange error when i try to update one instance of my model. 

```
Imagearticle.findOne(img.id).exec(function (err,result) {
	if(err) console.log(err);
        result.rank =4444;
        Imagearticle.update(img.id,result).exec(function(err,result2) {
		if(err) console.log(err);	
		 console.log(result2);							
	})
})
```
Where i log the result2, i got no error and the expected result coming from waterline (the instance of my model with the new value: rank = 4444) But in the database, nothing happends.

some more info:

- If i try to update a field that doesnt exist it will add that field correctly.

- This model is a intermediary model like explaine in [sailsdoc](http://sailsjs.org/#!/documentation/concepts/ORM/Associations/ThroughAssociations.html)

-  I even try with migrate 'alter' option but nothing want to update.

- I post you my model
```
module.exports = {

  	schema: true,
  	migrate: 'alter',
    attributes: {
  		rank : {type:'string'},
  		image:{model:'image'},
  		article:{model:'article'},
  		titi:{type:'string'},
  		
    },
};
```

Any idea of whats happend here?

**Comment by tjwebb** [comment]
>         rank : {type:'string'},
>         result.rank =4444;

Those two lines aren't consistent. Are you sure it doesn't throw a validation error?

**Comment by Oldwo1f** [comment]
yes i am sure.
i tryed with another filename and a new field

**Comment by Oldwo1f** [comment]
i also tryed with "int" type and with real string value in string type

**Comment by tjwebb** [comment]
Ah, ok I see what's going on. Just use `.save()`, like this: https://github.com/tjwebb/sails-permissions/blob/master/api/hooks/sails-permissions.js#L66-L71

**Comment by Oldwo1f** [comment]
```
Imagearticle.findOne(img.id).exec(function (err,result) {
                 if(err) console.log(err);										
		result.rank ='0000'
		result.save(function(err,result2){
                        console.log('result2',result2);
                });											
})
```
Once again, i got the result2 correct, but nothing in database

**Comment by tjwebb** [comment]
Do other `.update()` statements in your app work? Have you tried a different adapter? Something else is going on here.

**Comment by Oldwo1f** [comment]
ok, i figured it out.

I was my async.parallel() , who saved the full Article with the associated Imagearticle collection.
So each time i saved my article, it was resaved with the old content.

Replacing .parallel() by .series() fixed my problem.

you can close this issue
