### ISSUE TITLE
sails.sockets.join - invalid number of arguments

### ISSUE THREAD

**Issue by herghost** [balderdashy/sails#2837]
Using v0.11.0

When trying to subscribe to a room like 
sails.sockets.join(req.socket,"batches");

I get an invalid number of arguments message, the room is created but the socket is not subscribed to it, the only room subscibed is named the same as the sails.sockets.id(req.socket) result.

This code block:

subscribe: function(req, res) {

        if (!req.isSocket) {
            return res.badRequest();
        }
        else {

            var socketId = sails.sockets.id(req.socket);
            console.log("Socket Connected! id: " + socketId);
            sails.sockets.join(req.socket,"batches");
            console.log(JSON.stringify(sails.sockets.rooms()));
            var roomnames = JSON.stringify(sails.sockets.socketRooms(req.socket));
            console.log("Rooms: " + roomnames);
            res.json({
                status: 200
            });
        }
    },

results in

Socket Connected! id: VsrDWZIC5ZGoyvEsAAAB
["RwbReOKf7x4rnyCcAAAA","VsrDWZIC5ZGoyvEsAAAB","batches"]
Rooms: ["VsrDWZIC5ZGoyvEsAAAB"]

**Comment by herghost** [comment]
After a bit of further investigation I can confirm that the room is actually joined, its just not picked up by the sails.socket.rooms() function at first, I assume this is because the add to room code has not completed in time for it to be picked up.

Therefore my only error is that the designer (IntelliJ IDEA) in my case gives a warning for invalid amount of arguments (expecting 0:1) for sails.sockets.join()

**Comment by CWyrtzen** [comment]
Are you still getting this error? Did you find a workaround?

**Comment by herghost** [comment]
Yeah, its just a warning in Intellij so I just ignore it!

**Comment by CWyrtzen** [comment]
well okey, dokey then - - thanks! official advice: #ignoreit
