### ISSUE TITLE
Distributed Denial of Service (DDOS)

### ISSUE THREAD

**Issue by Geocloud** [balderdashy/sails#2839]
Hello,

I don't found a solution for DDOS attack with Sailsjs.
Do you have a solution for this big issue ?

Thank you

**Comment by kevinburkeshyp** [comment]
hey! in general, if DDOS requests are making it to the application layer, you're already consuming too many resources to try and fight it - even if your node app is super thin and super fast at responding to queries, you are going to be getting too many queries to adequately fight them off in your application.

a lot depends on the nature of the DDOS - whether the traffic follows a specific pattern, or is only to a given route, which makes it easier to filter. you might want to look at something like the `limit_conn` directive in nginx: http://nginx.org/en/docs/http/ngx_http_limit_conn_module.html#limit_conn

alternatively, you can route your traffic through a provider like CloudFlare or Akamai that offer a level of DDOS protection.

**Comment by randallmeeker** [comment]
This is a hosting provider thing and not a sails thing. I do like AWS for this http://aws.amazon.com/security/

**Comment by Geocloud** [comment]
Thank you Gentleman. I will see with the Cloud provider.

**Comment by tjwebb** [comment]
No node.js application should ever be hosted naked. Something like nginx and apache should always be used to proxy requests.
