### ISSUE TITLE
'/*' route causes assets to be served as the HTML page

### ISSUE THREAD

**Issue by woollybogger** [balderdashy/sails#2841]
#### Steps to reproduce

1. `sails new testProject && cd testProject`
2. change the `'/'` route to `'/*'` in `config/routes.js`
3. `sails lift`
4. open [`localhost:1337`](http://localhost:1337)
5. notice that `/js/dependencies/sails.io.js` is served as text/html and is in fact the same as the HTML page you are viewing (the same is also true for `importer.css`)

#### Reproduced on

+ Windows
+ Ubuntu

#### Sails versions tested

+ 0.10.5
+ 0.11.0

**Comment by mikemastah** [comment]
You should add the `skipAssets: true` property to your route [as per the docs](http://sailsjs.org/#!/documentation/concepts/Routes/RouteTargetSyntax.html?q=route-target-options).

Example:
```
'/*': {
    controller: 'IndexController',
    skipAssets: true
}
```

**Comment by woollybogger** [comment]
@mikemastah You're right, that fixes the problem. Thank you!
I think I'll try contributing to the docs repo to make this a little more obvious.
