### ISSUE TITLE
Can't find 'lodash/Lang/isObject' directory name is incorrect

### ISSUE THREAD

**Issue by TayHobbs** [balderdashy/sails#2842]
Running on a Mac OS 10.10.3 case sensitive system I get this error:

    error: Error: Cannot find module 'lodash/Lang/isObject'

This is unsurprising because the path should be:

    lodash/lang/isObject

**Comment by Globegitter** [comment]
@TayHobbs is that an error just with sails? Or where you using https://github.com/artificialio/sane?

**Comment by papodaca** [comment]
I am seeing this also, from what I can tell it has to do with the dev hook. Removing it and installing a working version fixes this:
```
npm uninstall sails-hook-dev
npm install sails-hook-dev@0.2.2
```

**Comment by TayHobbs** [comment]
@Globegitter I am using sane, I was trying to find the best place to put this issue. Sorry if I chose incorrect.

**Comment by TayHobbs** [comment]
@papodaca Thanks!

**Comment by Globegitter** [comment]
@TayHobbs no worries, it happens ;)
