### ISSUE TITLE
How to bypass the "protected" validation and return all attributes for a model instance

### ISSUE THREAD

**Issue by albertpeiro** [balderdashy/sails#2844]
I've got an attribute that needs protection in general. Its model attribute has validation "protected": true so it's not returned on the public website.

Backoffice needs to read and modify this attribute from one specific controller.

How can I achieve this?

What I've tried:
- Override toJSON to deliver the whole object. It bypasses the protected validation but there's no control and I can't inject variables - I don't know how/ docs don't tell me.
- Create a new toUnprotectedJSON under model/attributes. Call it from my Backoffice controller before returning. I use res.ok and the attribute is still removed and treated as if it was "protected".
- BackofficeController return item.toObject(); still same issue treated as "protected"
- From my Backoffice controller:

        console.log(_.isPlainObject(item.toUnprotectedJSON()));
        //false
        console.log(_.isPlainObject({yo:'yo'}));
        //true

I'm sure there's a dead simple way to convert to a plain object to get this working. Still wanted to post here in case there's another Sails way of achieving it easily.

Any help appreciated!
Thank you!

**Comment by albertpeiro** [comment]
I just found a way of making this work:

    model.findOneById(id)
            .then(_.clone) // Bypass 'protected' attrs
            .then(res.ok)
            .catch(res.badRequest);

If wrapped by a service and using promises it can be used as quite a low impact solution with fair maintainability.

**Comment by sgress454** [comment]
Hi @albertpeiro, thanks for using Sails!  Just FYI, we try to keep this forum for reporting bugs on the Sails core, so in the future if you have support questions please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
<hr/>
Re: a workaround for `protected: true`, the solution you came up with is perfectly reasonable!
