### ISSUE TITLE
Cant deploy Sails project to OpenShift

### ISSUE THREAD

**Issue by Behukob** [balderdashy/sails#2848]
Why did you require version of npm>=1.4 in the package.json?
  "engines": {
    "node": ">= 0.10.0",
    "npm": ">= 1.4.0"
  }
Is any critical issue with this?
Its not possible to deploy to Openshift, becouse it has only 1.3.4

**Comment by tjwebb** [comment]
Can you not install whichever version of node/npm you want on OpenShift?

**Comment by Behukob** [comment]
I cant update version of npm on Openshift. I dont know how to do this.
Same question unanswered:
http://stackoverflow.com/questions/22743585/updating-npm-on-openshift

**Comment by Behukob** [comment]
I make it!
application with Sails 0.11 started on Openshift
you need to create Openshift application with this repository https://github.com/ryanj/nodejs-custom-version-openshift
than ssh to openshift, check node -v, npm -v, manually update npm if needed 
than cd app-root, cd repo, npm install sails
than make what writen on this page https://gist.github.com/mdunisch/4a56bdf972c2f708ccc6
than git push
