### ISSUE TITLE
get a list of all routes incl. blueprints

### ISSUE THREAD

**Issue by nor-bu** [balderdashy/sails#2849]
hey

how can i get a list of all routes incl. blueprints?
sails.config.routes give only a list of custom routes.

thanks for help

**Comment by kevinburkeshyp** [comment]
If you turn on the silly log level it should generate a list

-kevin

On Apr 20, 2015, at 07:55, norbu89 <notifications@github.com> wrote:

hey

how can i get a list of all routes incl. blueprints?
sails.config.routes give only a list of custom routes.

thanks for help

—
Reply to this email directly or view it on GitHub
<https://github.com/balderdashy/sails/issues/2849>.

**Comment by norbu89** [comment]
thanks for help.

silly log level?

**Comment by loicsaintroch** [comment]
You can do it with `$ sails lift --silly`.

**Comment by norbu89** [comment]
can i get this list in a controller?

i want to create a app like loopback explorer.

**Comment by tjwebb** [comment]
@norbu89 we are working on implementing this feature with swagger: https://github.com/balderdashy/sails/issues/1094. Interested in helping out?

**Comment by norbu89** [comment]
ah ok, would be the first time i for me.
swagger looks nice ;-) yes swagger is exactly this that i looking for!

yes i interested -  do you have more inforamations?

**Comment by renanvieira** [comment]
@tjwebb how can I help implement this feature? :)

**Comment by tjwebb** [comment]
Hey @renanvieira, you're interested in working on the swagger implementation? Let's move over to https://github.com/balderdashy/sails/issues/1094
