### ISSUE TITLE
new static folder

### ISSUE THREAD

**Issue by norbu89** [balderdashy/sails#2851]
hey,

how can i add a new static folder to my app?

example:
i have a folder 'newstatic'.
when i serve /newstatic/examplefile.html i want to serve the file.

how can i do this?

regards and thanks for help

**Comment by masumeEbhami** [comment]
can i ask what you need to insert on newstatic folder?because sails anatomy is complete for every thing that you need to insert :-))

**Comment by norbu89** [comment]
yes thats right sails is completly ;-)
sorry i was yesterday very tired.

my idea was , i will secure  a new separte assets folder.
after a littlebit of sleep i have the solution for my idea.

sorry for this post

**Comment by masumeEbhami** [comment]
Dear norbu89 Dont worry about your choose. all thing is Ok :-)))))))) 
i hope to successful for you
