### ISSUE TITLE
`sails console` reports "Server doesn't appear to be starting", it has started

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/sails#2852]
Steps to reproduce:

1. type `sails console`

2. observe a console appears: `sails>`

3. Sails logs an error message across several lines, "Server doesn't seem to be starting..."

This is on sails 0.10.5, possible it's been fixed, I tried searching for "Troubleshooting" in the issues & didn't see anything matching.

**Comment by kevinburkeshyp** [comment]
may be related: https://github.com/balderdashy/sails/issues/2321#issuecomment-94385268

**Comment by tjwebb** [comment]
I'm not seeing this on 0.11. Have you tried on 0.11.x?

**Comment by CWyrtzen** [comment]
Did we confirm this as an error and does it still exist in the new release?

**Comment by kevinburkeshyp** [comment]
Turns out we didn't have the timeout set high enough - we needed to set it to ~35 seconds. Closing.
