### ISSUE TITLE
Is it possible to serve sails under subcategory

### ISSUE THREAD

**Issue by EloB** [balderdashy/sails#2856]
I can't find anywhere. I have nginx in front of sails and I will proxy the request to the sails server under a subcategory. See example below. Is that possible?

http://domain.tld/sails/socket.io -> http://localhost:1337/socket.io
http://domain.tld/sails/model -> http://localhost:1337/model
Etc.

**Comment by kevinburkeshyp** [comment]
You should be able to rewrite the URL with nginx pretty easily, search for internal rewrite

**Comment by kevinburkeshyp** [comment]
(or post on StackOverflow, someone should prolly be able to give you the right config)

**Comment by EloB** [comment]
I managed it by nginx. Thanks! I was just wondering if it was possible through sails.
