### ISSUE TITLE
Write sails core on es6 / babel

### ISSUE THREAD

**Issue by listepo** [balderdashy/sails#2857]
This will attract more developers and adds more features, native support for iojs and transpiler js from babel for nodejs

**Comment by loicsaintroch** [comment]
I agree but this is not urgent. Our top first priority is to release Sails 1.0.0. We'll write Sails on ES6 as soon as we are more stable on our side. Thanks for the feedback, we appreciate.

**Comment by timpler** [comment]
So around 15 months passed...

**Comment by koolay** [comment]
+1
