### ISSUE TITLE
Create Blueprint Doesn't accept Arrays

### ISSUE THREAD

**Issue by alexmuro** [balderdashy/sails#2860]
If I post an array of objects to the create blueprint, 
say 
```
[{name:'a'},{name:'b'}]
```
https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/actions/create.js#L25
 returns an object
```
{'0':{name:'a'},'1':{name:'b'}}
```
which isn't accpeted by waterline.create

here is my client side request code:
```
       d3.json('/'+type)
          .header("Content-Type", "application/json")
          .post(JSON.stringify(data),function(err,resData){
       
             ServerActionCreators.receiveData(type,[resData]);
        });
```

**Comment by tarlepp** [comment]
So the actual issue was the payload format which should be like

```
{[{name:'a'},{name:'b'}]}
```

The docs about this should be clearer imho, with more examples actual usages.
