### ISSUE TITLE
the memory would has been big?

### ISSUE THREAD

**Issue by lvsenlin** [balderdashy/sails#2870]
I create a new project,If I visit the default page:localhost:1337,the memory will been big.
why it doesn't release?

node:v0.10.30
sailsjs:0.11.0

**Comment by tjwebb** [comment]
I'm not sure what you're asking here. Are you having a problem launching sails?

**Comment by lvsenlin** [comment]
https://github.com/balderdashy/sails/issues/2779 , just like this question

**Comment by lvsenlin** [comment]
![3a7cd133-0fc6-4901-a605-d00b35dbff1b](https://cloud.githubusercontent.com/assets/3062415/7331044/257dee88-eb32-11e4-91c2-9a8d4198716b.png)
my server,2GB memory,sailjs is in docker.

**Comment by tjwebb** [comment]
Yes, node is using a lot of RAM. There's no possible way for us to diagnose why this might be just a screendump of `top`.

**Comment by lvsenlin** [comment]
heapsnapshot：http://pan.baidu.com/s/1kTL1I9T

var heapdump = require('heapdump');
setInterval(function() {
  var file = 'test/myapp-' + process.pid + '-' + Date.now() + '.heapsnapshot';
  heapdump.writeSnapshot(file, function (err) {
    if (err) console.error(err);
    else console.error('Wrote snapshot: ' + file);
  });
},1000*30);
启动后30秒，我什么也没做。然后我点击登录、还有一些其它功能

**Comment by tjwebb** [comment]
sails.js has no known memory leaks, and 100% of the time a memory leak issue is filed, it turns out to be not related to sails.js

A heapdump without source code is useless. If you'd like Balderdash to work with you in a professional services engagement, we can help you debug your memory leak.

**Comment by lvsenlin** [comment]
OK，I will send the git address to you by Twitter.

**Comment by tjwebb** [comment]
Just email me: tjwebb@balderdash.co

**Comment by lvsenlin** [comment]
I use bitbucket.org,do you have a account?

**Comment by lvsenlin** [comment]
https://senlinlv@bitbucket.org/ruanwen100/ruanwen100.git
lvsenlin@lvsenlin.org
KRbkIVOOcK[A
 
 
------------------ 原始邮件 ------------------
发件人: "Travis Webb"; 
发送时间: 2015年4月28日(星期二) 上午9:32
收件人: "balderdashy/sails"; 
抄送: "lvsenlin"; 
主题: Re: [sails] the memory would has been big? (#2870)

 

Just email me: tjwebb@balderdash.co

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here:
https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
