### ISSUE TITLE
Access db object

### ISSUE THREAD

**Issue by Oldwo1f** [balderdashy/sails#2871]
Hi, i would like to access the mongodb oject used by waterline, in order to use some native mongo function. (like stats, or dump)

Does anyone know how can i achieve that.

Thanks

**Comment by masumeEbhami** [comment]
look this maybe be useful
http://stackoverflow.com/questions/25699097/native-update-in-sails-with-mongo-does-not-work-with-objectid

**Comment by jpwilliams** [comment]
Just accessing the collection for use for base Mongo functions you can use `Model.native`. So say I have a model called `User`:

```javascript
User.native(function (err, collection) {
    // Use 'collection' however you wish, e.g. collection.distinct, collection.findOne
});
```

Is that what you mean?

**Comment by Oldwo1f** [comment]
I would like to use the mongodump cli function on the global database.

I think i ll use a module like this one [https://github.com/punkave/mongo-dump-stream](https://github.com/punkave/mongo-dump-stream) but i still have a problem to send result to client. I posted an issue [https://github.com/punkave/mongo-dump-stream/issues/4](https://github.com/punkave/mongo-dump-stream/issues/4) but none answered

**Comment by sgress454** [comment]
Hi @Oldwo1f, just a reminder:  this forum is for reporting bugs in the Sails core.  If you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
