### ISSUE TITLE
Improve policy syntax

### ISSUE THREAD

**Issue by Siecje** [balderdashy/sails#2875]
My use case is to have anonymous users be able to read objects but not modify them.

Currently I have 

```JavaScript
module.exports.policies = {

  LoginController: {
    isLoggedIn: 'sessionAuth'
  },

  UserController: {
    'addPicture': 'currentUserAuth',
    'update': 'currentUserAuth',
    'destroy': 'currentUserAuth',
  },

  ModelOneController: {
    'create': 'adminAuth',
    'update': 'adminAuth',
    'destroy': 'adminAuth',
  },
  ModelTwoController: {
    'create': 'adminAuth',
    'update': 'adminAuth',
    'destroy': 'adminAuth',
  },
  //...
```

It would be nice to do 

```JavaScript
module.exports.policies = {
  'create': 'adminAuth',
  'update': 'adminAuth',
  'destroy': 'adminAuth',
```

Or 
```JavaScript
'*': adminAuth,
'*.create': true
```
Or 
```JavaScript
'*': {
  'find': true,
  'findOne': true
}
```

**Comment by tjwebb** [comment]
Have you looked at [**sails-permissions**](https://github.com/tjwebb/sails-permissions)? I believe it will do what you need.

**Comment by Siecje** [comment]
Wow thanks!

I already have a user and role based system in place. How would you create a config to match controller methods?

I still think it would be beneficial to have a default for a controller method especially when you are using blueprints.

**Comment by tjwebb** [comment]
You can look at the sails-permissions `User` and `Role` objects, and just make sure they have the same attributes and functions, and then run the sails-permissions generator. Everything should fall into place. (you might have to use `-f` on the generator and then restore your files).

If you have further question feel free to start a discussion in https://gitter.im/balderdashy/sails. Hope that helps!
