### ISSUE TITLE
jsonWebTokens.tokenProperty name doesn't align with property required in requests from clients

### ISSUE THREAD

**Issue by kodayashi** [balderdashy/sails#2879]
In the waterlock.js config, you can set this property:

```
    // set the name of the jwt token property
    // in the JSON response
    tokenProperty: 'token',
```

With this set to token, the query parameter (or HTTP header) required in requests to the server *still* must be access_token, or the client's request will be denied with "No access token present".

I'd suggest aligning these two values (e.g. if the tokenProperty is 'token', then that's the property the server will accept).

**Comment by tjwebb** [comment]
I think you filed this in the wrong repository. We didn't build waterlock.

http://waterlock.ninja/

**Comment by kodayashi** [comment]
Indeed I did! Sorry about that, too many github tabs open :/

**Comment by tjwebb** [comment]
> too many github tabs open :/

You're doing it right.
