### ISSUE TITLE
Timezone for mongoDB ?

### ISSUE THREAD

**Issue by dogrocker** [balderdashy/sails#2880]
Hello, I've problem about timezone.
on my `sails lift` it show
`debug: :: Mon Apr 27 2015 01:29:27 GMT+0700 (ICT)`
but on my mongoDB it `UTC` so I search about mongoDB timezone and I found that mongoDB alway save time as `UTC`

now Question is did sails have some function to set timezone in application?

**Comment by lvsenlin** [comment]
set the os's timezone

**Comment by dogrocker** [comment]
@lvsenlin as i said my OS timezone is set to +7 gmt

debug: :: Mon Apr 27 2015 01:29:27

**Comment by sgress454** [comment]
Hi @dogrocker , thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core.  If you need support in the future, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).   
<hr/>
There's no 100% reliable way to set the default timezone in a Node JS app; you can Google it to see what I mean.  Your best bet is to use a library like  [timezone-js](https://github.com/mde/timezone-js) or [moment](http://momentjs.com/) if that's really important to your project.
