### ISSUE TITLE
blueprint prefix, route wildcard, and params not cooperating

### ISSUE THREAD

**Issue by stebl** [balderdashy/sails#2883]
I think these are all the relevant steps...
1. Turn on the blueprints prefix, ex 'v1'
2. to work around prefixing in routes, I did 'get /v*/myModel/:id/someRoute': 'myController:someRoute'
3. call the route GET /v1/myModel/8/someRoute
4. req.params.all() returns { '0': '8', id: '1' }

**Comment by sgress454** [comment]
I'm not sure what you're going for with the `/v*`.  Are you trying to do API versioning?  Does [this issue](https://github.com/balderdashy/sails/issues/2609) help?

**Comment by stebl** [comment]
Yes, sorry for the lack of clarity.

I was trying to do versioning with the URL.  I wanted to avoid re-writing the routes file in a version bump, so I was using the wildcard.  

Yes I believe that issue is a workable solution.  Will try and implement that this week.

**Comment by sgress454** [comment]
Very good.  As for the issue with `req.params.all`, that is...odd, but seems like a general Express router issue, so I'll close this one out.
