### ISSUE TITLE
Version Upgrade from 10 to 11 Error

### ISSUE THREAD

**Issue by frostme** [balderdashy/sails#2886]
Trying to upgrade from sails 0.10.5 to 0.11 on a secure network. We use a private npm, and don't have access to public GitHub. Currently can't install sails 0.11.0 because of the following dependency tree

sails 0.11
--> sails-hook-sockets
--> --> socket.io
--> --> --> socket.io-client
--> --> --> --> engine.io-client

In the engine.io-client module, there is a dependency that is listed to a github URL. Because of this, we cannot upgrade (especially scale our servers) to sails 0.11. There are three issues in engine.io-client, but it looks that we are dead in the water (pun :) ) in upgrading to sails 0.11

Referenced issues
[engine.io-client issue 384](https://github.com/Automattic/engine.io-client/issues/384)
[engine.io-client issue 358](https://github.com/Automattic/engine.io-client/issues/358)
[engine.io-client issue 348](https://github.com/Automattic/engine.io-client/issues/348)

Referenced engine.io-client package.json
[engine.io-client package.json](https://github.com/Automattic/engine.io-client/blob/master/package.json)

**Comment by Karnith** [comment]
I had to make a fork of all of them including sails repo and then update the package.json references to get to work.

**Comment by tjwebb** [comment]
> In the engine.io-client module, there is a dependency that is listed to a github URL. Because of this, we cannot upgrade 

Using a github url in a package.json is a perfectly legit thing to do, which is why npm supports it, and tons of projects use this feature. This sounds like it's an annoying problem, but it's not a problem with sails.js, and unfortunately it's not something we're going to be able to help you solve.

**Comment by sgress454** [comment]
Ditto @tjwebb; I feel your pain, but we can't really control what goes on inside of engine.io.  Hopefully they upgrade to the version of xmlhttprequest that's on NPM soon.

**Comment by frostme** [comment]
Completely understandable. Thanks for the responses, I'll just keep pushing on the engine.io-client repository!
