### ISSUE TITLE
auto increment in mongodb in sails project

### ISSUE THREAD

**Issue by masumeEbhami** [balderdashy/sails#2890]
hello
i have a problem in auto increment field.i need to have a user id that be auto increment .i know this problem is about mongo but i want to help one that use auto increment in sails app with mongodb.
Thanks

**Comment by udanpe** [comment]
+1 I need too
  beforeCreate : function(item, next) {
    Counter.native(function(err, collection) {
      if (err) console.log(err);
      collection.findAndModify(
        { _id: "user" },
        null,
        { $inc: { seq: 1 } },
        { new:true, upsert:true },
        function(err, object){
          if (err) console.log(err);
          item.id = object.seq;
          next();
        }
      );
    });
  }

**Comment by masumeEbhami** [comment]
udanpe Thanks
