### ISSUE TITLE
Controller action called multiple times with odd data

### ISSUE THREAD

**Issue by maddogawl** [balderdashy/sails#2891]
I am using SailsJS 10.5 running on Windows 7 for development.

I have ran into a weird issue where I have the following route setup:

'/enter/:contestid': 'ContestController.enterContest',

Basically I pass in something like /enter/7 for example and then I load the appropriate data for that contest.

Now here is the weird part, so I can be on a page /enter/7 and refresh the page, and I get several calls to that controller action. Sometimes 3 or more, but generally at least 2 calls.  Only one of the calls will have the correct parameter passed in.

Here is my controller code (it is very simple to show the issue)
		
               //Save this to the session for retrieval later
		var contestid = req.param('contestid');
		if( parseFloat(contestid) == contestid ){
                        console.log("Valid contest id passed: " + contestid );
			req.session.currentContest = req.param('contestid');
		}
		else {
			console.log("Not a valid contest id sent to controller, not updating: " + contestid);
		}	
		res.view("contestenter");

Now my log will look something like this the first time and most subsequent times:

-Valid contest id passed: 7
-Not a valid contest id sent to controller, not updating: {{player.profilepic}}

So I found this problem because I use the contestid later on, and I was saving the last value passed in and for some reason it is one of my angular variables which is only ever referenced in an img tags.

Any ideas why this is happening?

**Comment by sgress454** [comment]
This is usually indicative of some client-side code calling a route via Ajax or sockets.  We haven't had any reports of the Sails router executing a controller action multiple times.  It could also possibly happen if you have a [policy](http://sailsjs.org/#!/documentation/concepts/Policies) that calls `next()` multiple times, though I haven't tested that...

**Comment by maddogawl** [comment]
Thanks for replying, here is the the only policy I have on that controller action.

module.exports = function (req, res, next) {

  if(!(req.session && req.session.user) ){
  	req.session.backURL = ('/lobby');
    return res.redirect('/login');
  }
  // If we made it all the way down here, looks like everything's ok, so we'll let the user through
  next();
};

I think you may have led me down the right path though, i'll keep you posted, but it might be something weird where angular activates later and it tries to resolve a url from the img as {{player.profilepic}}

**Comment by sgress454** [comment]
Sounds good @maddogawl.  I'm going to close this for now as it doesn't sound like it's a bug in the Sails core.  If you find out otherwise, please re-open!
