### ISSUE TITLE
How to set secure cookie?

### ISSUE THREAD

**Issue by fundon** [balderdashy/sails#2893]
I use `connect-redis-v1.4.5`.

**Comment by David-Melo** [comment]
+1

**Comment by aato** [comment]
I could be wrong but are you referring to this?

    res.cookie('chocolatechip', 'Yummy', {signed:true});
    req.signedCookies.chocolatechip;
    // "Yummy"

(from http://sailsjs.org/#!/documentation/reference/req/req.signedCookies.html)

**Comment by sgress454** [comment]
Hi @fundon, thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core.  If you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).    

@aato that's right, thanks!

**Comment by fundon** [comment]
@aato @sgress454 @tjwebb 
I think that it is not a good solution.
First the `session` middleware will generate the session-cookie(not secure).
So if I want secure it, I need another `secureSession` middleware to modify the `session-cookie`.
