### ISSUE TITLE
CATASTROPHIC SAILS MONGO FAILURE

### ISSUE THREAD

**Issue by knight-of-design** [balderdashy/sails#2894]
FYI MY SAILS MONGO PROJECTS ARE CATASTROPHICALLY FAILING. PLEASE REVERT PACKAGE.JSON VERSION OF SAILS MONGO 0.10.5 NOT 0.10.6 THANKS!

**Comment by brandtheisey** [comment]
Can you post some detail so people can see what's happening?

**Comment by knight-of-design** [comment]
All I have is this: 
When I try to access a Sails Blueprint route with sails-mongo v.0.10.5, the route completely freezes.

After reverting to sails-mongo v 0.10.5 everything is fine again.  So clearly, the package.json file needs to exclude sails-mongo v 0.10.6

**Comment by slin1202** [comment]
Agree, seems to be related to the sails-mongo issue balderdashy/sails-mongo#266

**Comment by particlebanana** [comment]
Unpublished `0.10.7` and moved it to `0.11.0` which requires mongo 2.4 or higher to use. I also unpublished `0.10.7` from npm so no one else gets it. Sorry about that guys didn't realize the driver wouldn't work on certain versions of mongo! You should be good with sails-mongo `0.10.6` or `0.10.8`.
