### ISSUE TITLE
Angular js:  $location  retreiving nothing

### ISSUE THREAD

**Issue by torresl** [balderdashy/sails#2900]
Hi,

I use an Angular js Controller for pagination:
app.controller('PaginationController',['$http','$log','$scope','$location',function($http,$log,$scope,$location){.....
$http, $scope retreive something, but $location retreive nothng.
How to solve the problem ?.

Thanks

**Comment by sgress454** [comment]
Hi @torresl, this forum is for reporting bugs in the Sails core.  If you're having an issue with Angular you might try searching or posting in their [Google Group](https://groups.google.com/forum/#!forum/angular) for assistance!
