### ISSUE TITLE
This is Scary now > Records Dropped from the Database

### ISSUE THREAD

**Issue by sahanDissanayake** [balderdashy/sails#2901]
Hi All,

I had about 11,500 records and I just took the sailsJS server from --prod to run normal dev mode,

In that split second my Sails server deleted all the data in the Venue table,

Ohh noo,, nay thoughts on this please ?

Im using sails v0.10.5
@sgress454 @mikermcneil

**Comment by tjwebb** [comment]
> to run normal dev mode,

What is your migrate setting? Yea, the differentiation between "production" and "development" is very important, and we do not recommend running on a production database in development mode.

**Comment by sahanDissanayake** [comment]
Config/models.js

settings is set to 'alter' on my dev, but on my prod server it was running with the --prod at the end of the command..

Al I wanted to do was to add the new fields to the table so that the new functions can be used, but never thought to loose all the data :cry:

**Comment by sahanDissanayake** [comment]
When you change the Model.js the table fields change accordingly in alter mode this is what I wanted to do on my prod server tables

How different should have I done this ? Should I have manually created new fields in the table using phpmyadmin or something similar ?

**Comment by tjwebb** [comment]
@sahanDissanayake I think I answered your question on StackOverflow: http://stackoverflow.com/questions/29997983/best-way-to-migrate-table-changes-to-production-sailsjs-tables/29998429#29998429

**Comment by sahanDissanayake** [comment]
Appreciated @tjwebb  :)

**Comment by sahanDissanayake** [comment]
@tjwebb this is all good and all, but how can I migrate the database table changes, Im struggling a little here,, 

I went with https://github.com/building5/sails-db-migrate

**Comment by particlebanana** [comment]
Hey @sahanDissanayake we recently added a `migrate: create` setting that sounds like it might work for you. If you are using a sql database there is always [sails-migrations](https://github.com/BlueHotDog/sails-migrations) as well.

**Comment by sahanDissanayake** [comment]
Hey @particlebanana ,, 
I will have to updated sails to get the migrate:create ? 
Right now im on V0.10.5

Yes, I am using mysql db

**Comment by sahanDissanayake** [comment]
@particlebanana , I changed the `migrate: create` on the mode.js but it did not change anything on the production server, Nothing changed basically,

Is this code supposed to only create tables or alter tables aswell ?

Thanks

**Comment by sahanDissanayake** [comment]
@particlebanana The migrate:create does not seems to be working :sob: 

get this error
```javascript
error: A hook (`orm`) failed to load!
error: Error: Invalid `migrate` strategy defined for collection. Must be one of the following: drop, alter, safe
    at Query.sync (/var/www/myapp/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:75:11)
...... etc
```
