### ISSUE TITLE
0.11.1 can't login using Mongo and 0.11.0 throws an error

### ISSUE THREAD

**Issue by hellowin** [balderdashy/sails#2904]
I create a new Sails app using sails new (after I download using `npm install sails -g`) it gives 0.11.1 version. At that version I can't login both using `sails-generate-auth` or `sails-permissions` when using Mongo. I decided to downgrade to 0.11.0 but it gives me an error:
```
module.js:340
    throw err;
    ^
Error: Cannot find module '../../../../sails-hooks'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Workspace\Hellowin\bhgk\node_modules\sails\lib\app
\private\loadHooks.js:11:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
The main problems is, I can't do any authentication when using Mongo (but it works well if using localDb). Either use 0.11.0 or 0.11.1 is not a problem as long as I can login using Mongo. When I use 0.11.1 the error is not shown even I use `verbose` logging. My PC is Windows 8.1 64bit running node.js 0.10.36 (it also show warn about npm thing at sails installation).

Anyone has any tought?

**Comment by fenos** [comment]
I'm expecting the same issue, i didn't understand the cause yet

**Comment by tjwebb** [comment]
When does the error occur? "I can't login" doesn't tell us anything. Tell us what controller/route/action you are accessing and exactly what data you are sending.

> it also show warn about npm thing at sails installation

Mind sharing what the warning is so we don't have to guess?

**Comment by hellowin** [comment]
After some of research now I have some findings. I will describe my chronology.
Let's say I have project A and B. Before I create I always do `npm install sails -g` and `npm update sails -g`. Project A is developed about a month ago, and B about 3 days ago. I found that there is any different at Sails's version. A is 0.11.0 B is 0.11.1. As I know that Sails's stable version is 0.11.0 so I downgrade B manually to 0.11.0, but error happend (at top of my post). So I don't mind and still work with 0.11.1 version.

At some point project B needs authentication, so I decided to use `sails-permissions`. It works perfectly, with `sails-disk` adapter. So I choose to change it to use `sails-mongo`. It can't even login or register. Here is my [login.dust](https://gist.github.com/hellowin/707dfe29fe7187e136e6), I just follow `sails-generate-auth`'s way. It also successful with `sails-disk` adapter. When I doing login or register, nothing happen, even with verbose logging.

So I try the same way to project A that use `sails-generate-auth`. A actually doesn't need Mongo, so I did not addressed that before. And the result is just the same. It works fine with `sails-disk` but error with `sails-mongo`.

And with an `warn` at installation, it said sails need npm v2 but mine just 1.4. But the weird thing is I can't reproduce again that warning after reboot and fresh install anything from node.js until sails it self.

**Comment by hellowin** [comment]
Here the `warn` that I told before, it's shown again when I move to Vagrant.
```
npm WARN engine sails-auth@1.0.9: wanted: {"node":">= 0.10","npm":">= 2.3"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine sails-permissions@1.0.16: wanted: {"node":">= 0.10","npm":">= 2.3"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
```

**Comment by hellowin** [comment]
Here I cloned whole of my project (project B as I described before). https://github.com/hellowin/sails-permissions-mongo-error clone, install, and run it. It's alo thrown an error in Vagrant that running Ubuntu.

**Comment by hellowin** [comment]
Thanks God, it's solved. Because I also have some issue with different project that use `sails-mongo` that guide me to [this reference](http://stackoverflow.com/questions/29959602/mongoerror-topology-was-destroyed-sailsjs).

So `sails-mongo` needs to downgrade to version `0.10.8` and that's works like a charm. I think somethings not good at sails-mongo 0.11.

**Comment by tjwebb** [comment]
@hellowin FYI: https://github.com/tjwebb/sails-permissions/issues/200
