### ISSUE TITLE
How to access file from dropzone.js??

### ISSUE THREAD

**Issue by nikhiljohn10** [balderdashy/sails#2905]
I can't access the files uploaded from client through dropzone. I was migrating my site from php to sails. I'm stuck. req.files is undefined when i checked it. Please someone help.

I need something like following.
my file drops are send as POST to /drop/dropped

**api/controllers/DropController.js**
```js

module.exports = {
	dropped: function(req, res) {
		// Get the file and process it ( This is the part i'm stuck )

		// Save the file

		// Return unique File ID
	},
}
```

**Comment by nikhiljohn10** [comment]
@tjwebb  please help

**Comment by nikhiljohn10** [comment]
Solved
```js

module.exports = {
    dropped: function(req, res) {
        req.file('design').upload({
            maxBytes: 10000000
        }, function whenDone(err, files) {
            console.log(files);
        }
    }
}

```

I had issues with paramName. All working now.

**Comment by tjwebb** [comment]
Glad you figured it out! (btw I have no idea what dropzone is)
