### ISSUE TITLE
Blueprints and PUT

### ISSUE THREAD

**Issue by isuvorov** [balderdashy/sails#2908]
method |  route       |  result
---------|-----------------------|--------------
POST |   /rest/model       |  OK
GET |   /rest/model?id=:ID  | OK
GET  |  /rest/model/:ID     | OK
DELETE  | /rest/model?id=:ID  | OK
DELETE| /rest/model/:ID     | OK
PUT  |  /rest/model/:ID     | OK

But!
PUT    /rest/model?id=:ID  -> 404

Is it correct blueprints logic? or bug?

**Comment by tjwebb** [comment]
> PUT /rest/model?id=:ID -> 404

This is not supposed to work. Do you see this documented somewhere that it should work?
