### ISSUE TITLE
Can't run tests on remote server

### ISSUE THREAD

**Issue by LouisBarranqueiro** [balderdashy/sails#2923]
When i'm tryin to execute tests for the first time (I open my IDE and run ```npm test```), i have an error :  
``` xml
<testsuite name="Mocha Tests" tests="0" failures="2" errors="2" skipped="-2" timestamp="Mon, 11 May 2015 12:47:21 GMT" time="2.005">
<testcase classname="" name="&quot;before all&quot; hook" time="2"><failure><![CDATA[timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.]]></failure></testcase>
<testcase classname="" name="&quot;after all&quot; hook" time="0"><failure><![CDATA[Cannot call method 'lower' of undefined
TypeError: Cannot call method 'lower' of undefined
    at Context.&lt;anonymous&gt; (test/controllers/UserController.spec.js:78:11)]]></failure></testcase>
</testsuite>
```
For each test written, a sails server is lifted with ```bootstrap.spec.js```file and killed with done callback.

If I run ```sails lift``` and kill the server with ```CTRL+C``` and execute my tests again, it's works. But i have to start the server one time before. Why?  
And if I set a remote database, i doesn't work. It only work in local with a local database

In local, it's not a problem but on Travis-CI, I can't start the server with ```sails lift``` and kill this process with ``CTRL + C`` and after execute tests then the build failed with the error above.  

Sails : 0.11

**Comment by tjwebb** [comment]
I think you need to post your code. This isn't an issue I've encountered before.

**Comment by LouisBarranqueiro** [comment]
I rename the issue, because the real problem is linked to the remote database connection. If I execute tests in a local MySQL server, even for the first time. It works fine but not on a remote server with the same version of MySQL (5.5.42).
The error message is the same.
Here is concerned files of my project :  

connections.js
``` javascript
module.exports.connections = {
    developmentMysqlDatabase: {
        adapter:  'sails-mysql',
        host:     'localhost',
        port:     8889,
        user:     'user',
        password: 'password',
        database: 'database'
    },

    testingMysqlDatabase: {
        adapter:  'sails-mysql',
        host:     'remoteserver.com',
        port:     3306,
        user:     'user',
        password: 'password',
        database: 'database'
    }
};
```
  
Bootstrap.spec.js
``` javascript
var Sails = require('sails');
var sails;

before(function(done) {
    Sails.lift({}, function(err, server) {
        sails = server;
        if (err) {
            return done(err);
        }
        done(err, sails);
    });
});

after(function(done) {
    sails.lower(done);
});
```
I noticed that when I start the server with a remote database connection. Tables are not created into. I think these 2 problems are linked.

**Comment by LouisBarranqueiro** [comment]
The problem was caused by short timeouts in mocha configuration (2000ms), with higher timeouts, it works fine.
