### ISSUE TITLE
Socket events not filtered after a REST get subressource

### ISSUE THREAD

**Issue by cyrilchapon** [balderdashy/sails#2931]
Requesting `GET /bean/1/carrots` through my socket doesn't subscribes my socket to "*carrots that belong to bean 1*", but to "*every carrots*", and that's very surprising. Is that the way it's supposed to be ?

Thus, making some

```
io.socket.on('carrot', function(msg) {
  //msg "created" triggered
});

io.socket.get('/bean/1/carrots', function serverResponded (body, JWR) {
  //something
});
```

and `POST /bean/2/carrots` makes the `on` callback called with a "created" verb and the data

**Comment by sgress454** [comment]
If you have `sails.config.blueprints.autoWatch` set to `true` (the default), then anytime you access an entity via sockets, you'll be subscribed to all `create` events on that entity's model.  That's the intended behavior.  But you can also get notifications when something has *added to*.  For example, if you're subscribed to the bean with ID 2, you'll get a notification after `POST /bean/2/carrots` with the verb set to `addedTo` and information about the carrot that was added.
