### ISSUE TITLE
Support custom environments

### ISSUE THREAD

**Issue by slavafomin** [balderdashy/sails#2932]
Hello!

According to the configuration docs you can have multiple custom environments, however, there are only two arguments for `sails lift` CLI that allows to run app in `dev` (`--dev`) or `prod` (`--prod`) environments.

Maybe we should add a more generic option like: `--env=prod`?

Thanks!

**Comment by randallmeeker** [comment]
This might help

https://github.com/balderdashy/sails/issues/2912

**Comment by sgress454** [comment]
The `--dev` and `--prod` options are there for convenience, but the main way to change the environment at lift time is through the `NODE_ENV` environment variable.

```
NODE_ENV=mycoolenv sails lift
```

`NODE_ENV` has become pretty standardized across Node modules, which is why it's good to get into the habit of using it.

**Comment by slavafomin** [comment]
Thank you! I think we should add it to the docs.

Or maybe we should introduce `--dev=env` for convenience as well? )

**Comment by sgress454** [comment]
@slavafomin would be happy to merge in a PR to the https://github.com/balderdashy/sails-docs repo :)
