### ISSUE TITLE
Can we apply pseudo policy on some Actions?

### ISSUE THREAD

**Issue by rohit-choudhary-jabong** [balderdashy/sails#2934]
Hi, 

I am facing a situation where I am creating a authController using passport. I need to call logout method when req.user is not empty and other actions like login, signup etc when req.user is empty. 

I want to create only one policy and I need to apply it on action I need to apply and opposite of it on all other action in that controller. Is there any options available or do I have to write a new policy again?

**Comment by sgress454** [comment]
Hi @rohit-choudhary-jabong, thanks for using Sails!  FYI, this forum is for reporting bugs in the Sails core.  For support in the future, please use our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [Gitter chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com/questions/tagged/sails.js?sort=newest&pageSize=50).
<hr/>
There's no support for "pseudo-policies" in Sails, but you do have access to information about the caller via `req.options.controller` and `req.options.action`, so you could branch your policy code to act differently depending on the action that triggered it.
