### ISSUE TITLE
Sails.js memory leak

### ISSUE THREAD

**Issue by kaduev13** [balderdashy/sails#2937]
Well, I have sails.js application, and have found that it has some memory leak. I'm using pm2 monit command for testing application memory usage. My application using postgresql as database back-end and redis as sessions storage. I try to open static page (default sails homepage), and each time I have opened it, used memory size increased by 80-90 KB. Of course it is production environment. Any ideas?
(the same closed issue here: https://github.com/balderdashy/sails/issues/1880)

**Comment by kaduev13** [comment]
Just tested with new project (but using dev environment):
```
sails new memoryleak
cd memoryleak
pm2 start app.js
pm2 monit
```
Now, go to 127.0.0.1:1337 and refresh it 2-3 times. Memory size (in pm2 monit) will increase.

**Comment by Dallas62** [comment]
+1

**Comment by kaduev13** [comment]
Ok, I found, that it's not Sails problem. This is problem of node.js garbade collector, I think. If you interested - look at this issue https://github.com/joyent/node/issues/5345

**Comment by tjwebb** [comment]
Yes; a more comprehensive thread on the matter is in this thread also: https://github.com/balderdashy/sails/issues/2779

**Comment by mikermcneil** [comment]
For future reference, there's more information and tips on diagnosing memory leaks in Node apps, and on reproducing+reporting suspected memory leaks in Sails here:
https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
