### ISSUE TITLE
The error " A hook (`orm`) failed to load!" will raise if you did not comment out "someMongodbServe"

### ISSUE THREAD

**Issue by xm1999** [balderdashy/sails#2941]
I am using "sails": "~0.11.0"  , I found if you did not comment out the "someMongodbServe" block in connections.js file, even if you have changed the development.js  to use another  "devMongodbServer".
The sails will still use the database 'your_mongo_db_name_here'， this will raise a error" A hook (`orm`) failed to load!" . This issue tooke me a lot of time to learn more mongo 3.0

connections.js
.........
...........................
someMongodbServer: {
    adapter: 'sails-mongo',
    host: 'localhost',
    port: 27017,
    // user: 'username',
    // password: 'password',
    // database: 'your_mongo_db_name_here'
  },
devMongodbServer: {
    adapter: 'sails-mongo',
    host: 'localhost',
    port: 27017,
    user: 'username',
    password: 'password',
    database: 'devDatabase'
  },
.........................
...............

**Comment by sgress454** [comment]
Yes, this is mentioned in the [connections docs](http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.connections.html?q=multiple-connections-for-an-adapter).  Multiple connections for the same adapter will always be loaded regardless of usage.

**Comment by gayanhewa** [comment]
👍
