### ISSUE TITLE
Upgrade sails with the last version of warterline

### ISSUE THREAD

**Issue by ameilland** [balderdashy/sails#2942]
Hi,

Would it be possible to add a support for the last version of waterline?

It has some great features like the select projection I would like to use.

Thanks,

**Comment by listepo** [comment]
https://github.com/balderdashy/sails/pull/2920

**Comment by sgress454** [comment]
Thanks for the input @ameilland, the next release of Sails will use the latest Waterline.

**Comment by ameilland** [comment]
Would you have an idea of the release date?
