### ISSUE TITLE
augmentModels Function Lodash Error

### ISSUE THREAD

**Issue by scott-wyatt** [balderdashy/sails#2943]
Sails currently has a dependency of lodash ~2.4.1, I'm running lodash 2.4.2

At about 22 models (or at least in my app) it seems lodash begins to struggle with bindAll through the augmentModels function and throws a TypeError. 

```js
//sails/lib/hooks/pubsub/index.js
augmentModels: function() {
      // Augment models with room/socket logic (& bind context)
 
      for (var identity in sails.models) {
        var AugmentedModel = _.defaults(sails.models[identity], getPubsubMethods(), {autosubscribe: true} );
        _.bindAll(AugmentedModel,
          'subscribe',
          'watch',
          'introduce',
          'retire',
          'unwatch',
          'unsubscribe',
          'publish',
          'room',
          'publishCreate',
          'publishUpdate',
          'publishDestroy',
          'publishAdd',
          'publishRemove'
        );
        sails.models[identity] = AugmentedModel;
      }
    }
  };
```
Has anyone seen this before? I haven't been able to track down if it's one of my models or if it's a lodash error.

**Comment by tjwebb** [comment]
>       for (var identity in sails.models) {

You should never use `for (var ... in)`. I don't know if this is causing your issue, but I'd start with using `_.each` instead.

**Comment by scott-wyatt** [comment]
I agree. I've tried switching the loop to _.each, but it still fries on the _.bindAll method. Just making sure it's not one of my Models...

**Comment by scott-wyatt** [comment]
Found it! Okay one of my models had an attribute called 'subscribe'  as it turns out, if you are using pubsub, that name is reserved.  I think that their should be some sort of model script that runs and throws and error if any models are trying to use reserved attributes.  For example:
```js
          'subscribe',
          'watch',
          'introduce',
          'retire',
          'unwatch',
          'unsubscribe',
          'publish',
          'room',
          'publishCreate',
          'publishUpdate',
          'publishDestroy',
          'publishAdd',
          'publishRemove'
```
Are bad model attribute names. @tjwebb should I do a feature request or implement a strategy and do a PR?
