### ISSUE TITLE
POST params with file does not found if it posted after file (Tested in ubuntu )

### ISSUE THREAD

**Issue by Nishchit14** [balderdashy/sails#2945]
If association key set  before file then it works fine as shown in image.

![image](https://cloud.githubusercontent.com/assets/5078921/7675065/3ad0b3d4-fd51-11e4-9dbe-ecf4e9f191e8.png)

But any params set after file then they dont found in req.

**Comment by Nishchit14** [comment]
Ok Try this....

1) set reqest in multipart

file     : image.jpg
name : Nishchit
age    : 22

In your controller console req.allParams() or req.params.all();

you will find " { } " printed out in console.

Now send this


name : Nishchit
age    : 22
file     : image.jpg

then re console request.

You will get 

{
  name : Nishchit
  age    : 22
}


-ND

**Comment by sgress454** [comment]
This is [pretty well documented](https://github.com/balderdashy/skipper#text-parameters) in the Skipper README.  Text parameters *must* be sent after the file.
