### ISSUE TITLE
Allow i18n to work with several locale files for the same locale ?

### ISSUE THREAD

**Issue by YoanTh** [balderdashy/sails#2946]
Hi,

Is it possible to allow i18n to work with several locale files for the same locale ?
The locale files would be stored in a hierarchy which is mapped with the sails hierarchy. For example:

- /config/locales/
  - defaults/
    - en.json
    - de.json
  - views/
    - user/
      - defaults/
        - en.json
        - de.json
      - index/
        - en.json
        - de.json

For a german translation of /views/user/index.ejs, i18n would extract the word:
1. in config/locales/views/user/index/de.json (if the word is defined)
2. or in config/locales/views/user/defaults/de.json (if the word is defined)
3. or in config/locales/defaults/de.json (if the word is defined)
4. else the word is not translated

Thank you !

**Comment by sgress454** [comment]
Hi @YoanTh, thanks for using Sails!  FYI, this forum is for reporting bugs in the Sails core.  For support in the future, please use our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [Gitter chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com/questions/tagged/sails.js?sort=newest&pageSize=50).
<hr/>
Sails uses the [i18n](https://github.com/mashpie/i18n-node) package for localization, so it supports whatever that package supports.  You'll have to look at their docs for more info but I believe localization files are restricted to one location.
