### ISSUE TITLE
Socket Bug from different app.

### ISSUE THREAD

**Issue by Oldwo1f** [balderdashy/sails#2947]
Hi sails team,
I would like to report a bug:

According to the [doc](http://sailsjs.org/#!/documentation/reference/websockets/resourceful-pubsub/publishCreate.html) publishCreate methode should subscribe all socket watching the collection to the new model instance we just creadted. And that works greats **inside one app**. 

The bug appear when i try to publishCreate() from another app (its just a duplicate of the first, with the same models). 
PublishCreate() correctly send the create event to all sockets watching the model but **it doesn' t subscribe** socket from other applications to the new model instance.

*some more info*
* *blueprints autowatch is set to False in both app*
* *i use 'socket.io-redis' adapter*

**Comment by sgress454** [comment]
Hi @Oldwo1f--not sure what you mean by "another app".  If you're trying to distribute the *same* app among several servers, this should certainly work (we'd had applications running on 20 servers with no problems).  You'll have to post a link to some code to determine whether this is a bug or a problem with your specific app.

**Comment by Oldwo1f** [comment]
By other app i mean that i have 2 app, one for the website administration, and one for the website itself.

Its not exactly a duplicate but all models are same betwen both apps and for testing my error i used the same controller function in both app.

-on administration side, it works
-on website side  it fail

this is my controller method in both app the same

```javascript
	addCommentProj:function(req,res,next) {

		Project.findOne(req.params.itemid).exec(function (err,project) {
			Comment.create({
				author:req.body.name,
		  		email:req.body.email,
		  		content:req.body.message,
		  		status:'new',
		  		project:req.params.itemid
	  		}).exec(function (err,coment){
									console.log(err)
				if(err)
					res.status(400).send(err)
				else{

				Notification.create({type:'projectcomment',status:'todo',info1:project.title,info2:'par '+coment.author,item:'project',itemid:req.params.itemid}).exec(function (err,notif){
						console.log(err)
						console.log(notif)
						 Notification.publishCreate(notif);
			    	res.status(200).send(coment)
				});
				}
			});
		})
	},
```

**Comment by Dallas62** [comment]
If your 2 apps aren't working on the same Sails Project, you can't share sockets update between your 2 apps.
Because sockets are shared on the same instance project (for InMemory socket).

**Comment by Oldwo1f** [comment]
Thanks for this answer.

can you please give me more details.

1. why it work for **create** and not for **update**?
1. How can i work around that to share update between 2 different apps (eg: One site and one Administration)

Thanks by advance

**Comment by Dallas62** [comment]
@Oldwo1f 
Mistake:
> If your 2 apps aren't working on the same Sails Project, you can't share sockets ~~*update*~~ between your 2 apps.

Are you running your two sites on the same sails project? (How many times you run `sails lift` to get your two sites UP?)

You can try to attach *Redis* to your sails project, but I'm not sure that will work in your case.

**Comment by sgress454** [comment]
@Dallas62 @Oldwo1f stated that he's using the socket.io-redis adapter, so this should actually work fine.    @Oldwo1f sorry I haven't had time to dig into it further, but are you certain that *any* sockets are being subscribed to the new instance?  Pubsub issues can be tricky to test because it's easy to forget what the expected behavior is.  To test:

1. Open up two browser tabs pointing to the *same* app, 
2. In tab 1, do a socket request for all instances of your model using the blueprint "find" (e.g. `io.socket.get("/comment")`.  
3. In tab 1, add a socket message handler (e.g. `io.socket.on("comment",console.log.bind(console))`)
4. In tab 2, create a new model instance (using `io.socket.post`, AJAX or any other means)
5. In tab 2, update that instance (again, using any means)

If tab 1 doesn't log anything on the update, then the problem has nothing to do with using two different apps.  Also, note that if you're not using the blueprint "find", `autowatch` doesn't do anything; you'll have to call `.watch()` yourself to make sure that the requesting socket is subscribed to new instances.

**Comment by Oldwo1f** [comment]
Thank for answer.

I ll spend the night (i am from France ) on that problem.

I ll let you know whats happening

**Comment by Oldwo1f** [comment]
I comfirm the probleme : 

In my  tab 1
 i fetch notification, i subscribe to that notifications instance and i watch the Notification Collection
i use Ajax to call this controller method
```javascript
subscribeNotif:function(req,res,next) {
		// 

		console.log('NOTIF');
		Notification.watch(req);
		Notification.find().populate('users').sort('createdAt DESC').exec(function (err,notifications) {
			if(err)
				res.send(err)
			_.remove(notifications, function(val) { 
				for(var i in val.users){
					if(val.users[i].id == req.user){
						return true; 
					}
				}
				return false;
			});
			Notification.subscribe(req.socket,notifications);
			res.status(200).send(notifications);
		})


	},
```

When i use the route bellow on the "main" app it works perfectly
my tab 1 is notified when and new notification is created and when it change on server side, the tab 1 is also notified for that change like for all notification already present when you subscribe at start of tab1.

This is the route use on both app to create and pusblish a notification
*this is a testing route with static info*
```javascript
	addCommentArticle:function(req,res,next) {

console.log('createComment');
		Article.findOne('554b3b8599b60b4a4248c23a').exec(function (err,article) {
			Comment.create({author:'nom de l auteur',
	  		email:'totot@tttt.fr',
	  		content:'ceci est un commentaire',
	  		status:'new',
	  		article:'554b4c0efdc6c85659eac47f'
	  		}).exec(function (err,coment){
									console.log(err)
									console.log(coment)
				Notification.create({type:'articlecomment',status:'todo',info1:article.title,info2:'par '+coment.author,item:'article',itemid:'554b3b8599b60b4a4248c23a'}).exec(function (err,notif){
						console.log(err)
						console.log(notif)
						 Notification.publishCreate(notif);
			    		// res.status(200).send(created);
			    	res.status(200).send(notif)
				});
			});
		})
	},
```

But when i use the exact same route in exact same controller from another app, it publish the creation (that works), but it does not subscrib my tab 1 to the new notification instance created

**Comment by Oldwo1f** [comment]
Ok i got some new test here.

#### TEST

I created a new sails app named testdebug1.
I installed  sails-mongo  and  socket.io-redis
I that app i got only one model and one controller.
In that controller i got 4 method:
* **/homepage** for rendering homepage
* **/createNotif** for creating a New notification
* **/editNotif/:id** for editing a notification
* **/subscribeNotif** the last one is used by the homepage client side to subscribe to Notification

With that app few browser tab i could test the problem explained before.

#### RESULT

I got the same problem as before. The thing works great on one app
but when i clone the app, change the port and lift this seconde instance of my app,
**the publishCreate() methode does not subscribe** the new instance created to socket allready watching Notification. ( but on the same app it works great )

#### TEST IT YOURSELF

I published a new repository with that little app.

1. git clone https://github.com/Oldwo1f/testdebug1.git
2. npm install 
3. change the port and the mongo-db name in sails config files
4. lift the app
5. test the routes mention before to create and update a notification with your browser tab
6. SEE IT WORK
7. Clone the app under another directory
8. repeat 2 and 3 and 4 with the same mongo-db informations but with a different port
9. Now you can test with the homepage of the first app to get some New notification created by the sconde app.
10. IT WORKS great again.
11. and now the Bug: Try to update a notification that was sended by the second app.
           FAIL, nothing recieved about update for this instance. thats because **we are not subscribe to that instance**. But why? We used publishCreate() so it should subscribe existing socket watching the collection to that new created instance. *(and it works inside one app)*

*(you can even try updateMethod on app1 or app2, its the same. If the notification was sended by different app, the new instance sended is not subscribed)*


#### MY REFLEXION

* i really doubt there can be a bug like this in sails.js
* Maybe its a problem with mongo version or redis version or one dependencie version.


MongoDB shell version: 3.0.3
redis-cli 2.8.4

package.json
    "sails-mongo": "^0.11.2",
    "socket.io-redis": "^0.1.4"





Big thanks if someone can give me a tips to find it out

**Comment by Oldwo1f** [comment]
I got news:

One of my friend tested this 'testdebug1' app with a fresh install of redis and a fresh install of mongo.

I appear that he got the same problem.

testdebug1 is a fresh generate sails project with only the thing needed to see the bug.

So i think of a **sails bug** or a bug in **socket.io-redis**

**Comment by Oldwo1f** [comment]
I forgot to mention that you need to open browser console in the index page to see notification coming

**Comment by sgress454** [comment]
@Oldwo1f, there's a clue here:

> i use Ajax to call this controller method

If you're calling the controller method with AJAX, then neither the `Notification.watch(req);` nor the  `Notification.subscribe(req.socket,notifications);` are going to have any effect.  You're trying to subscribe a socket to certain events, but you're not connecting over a socket--you're connecting over HTTP.  So how would it know which socket to connect?  In fact, if you look in your console you should see a warning like:

```
warn: `Model.subscribe()` called by a non-socket request. Only requests originating from a connected socket may be subscribed. Ignoring...
```

You need to call this controller method with `io.socket.get()` instead.

Just to test and make sure things are working, I created the minimum possible test case for this:

1) Created a fresh Sails app called `testredis1`
2) Created a second app called `testredis2`
3) Ran `sails generate api user` on both
4) Ran `npm install socket.io-redis` on both
5) Set `config/sockets.js` settings on both to:
```
  adapter: 'socket.io-redis',
  host: '127.0.0.1',
  port: 6379,
  db: 'sails',
```
6) Ran `npm install sails-mongo` on both
7) Set `config/connections.js` settings on both to:

```
  someMongodbServer: {
    adapter: 'sails-mongo',
    host: 'localhost',
    port: 27017,
    // user: 'username',
    // password: 'password',
    database: 'testredis'
  },
```

8) Set `config/models.js` on both to:

```
  connection: 'someMongodbServer',
  migrate: 'alter'
```

9) Started a local redis server on port 6379 (the default)
10) Started a local mongo server on port 27017 (the default)
11) Ran `sails lift` on `testredis1`
12) Ran `sails lift --port=1338` on `testredis2`
13) Opened a browser tab to `http://localhost:1337`
14) Opened another browser tab to `http://localhost:1338`
15) In both tabs Javascript consoles ran `io.socket.get("/user", console.log.bind(console))`
16) In both tabs Javascript consoles ran `io.socket.on("user", console.log.bind(console))`
17) In `testredis1` tab ran `io.socket.post("/user",{"name":"joe"},console.log.bind(console))`
18) Saw `Object {verb: "created", data: Object, id: "556bc165d0ed1fb98117035b"}` in tab for `testredis2`
19) In `testredis1` tab ran `io.socket.put("/user/556bc165d0ed1fb98117035b",{"name": "vlad"}, console.log.bind(console))`
20) Saw `Object {verb: "updated", data: Object, id: "556bc165d0ed1fb98117035b", previous: Object}` in tab for `testredis2`
<hr/>
This lets me know that the two separate apps which share the same Redis and Mongo connections do in fact get subscribed to the same instances when using socket requests, using the blueprint routes.  It should be no different with custom controller routes provided you are careful to call `.watch()` and `.subscribe()`, which you are.  You just need to make sure that when requesting routes that have the effect of doing socket subscriptions, that you actually make the request using a socket!

**Comment by Oldwo1f** [comment]
It still doesnt works for me..

I followed step by step your test but i got an error on step 19
```
/media/terra1/www/testsocket1/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
RangeError: Maximum call stack size exceeded

```

I am pretty sure its a versionning bug, but i can t find it out.

here is the package.json file of one app i created with your recipe above
```
{
  "name": "testsocket",
  "private": true,
  "version": "0.0.0",
  "description": "a Sails application",
  "keywords": [],
  "dependencies": {
    "ejs": "~0.8.4",
    "grunt": "0.4.2",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-coffee": "~0.10.1",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-jst": "~0.6.0",
    "grunt-contrib-less": "0.11.1",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-sails-linker": "~0.9.5",
    "grunt-sync": "~0.0.4",
    "include-all": "~0.1.3",
    "rc": "~0.5.0",
    "sails": "~0.11.0",
    "sails-disk": "~0.10.0",
    "sails-mongo": "^0.11.2",
    "socket.io-redis": "^0.1.4"
  },
  "scripts": {
    "start": "node app.js",
    "debug": "node debug app.js"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/alexis/testsocket.git"
  },
  "author": "alexis",
  "license": ""
}

```

**Comment by Oldwo1f** [comment]
Some news 

i installed the latest sails version (beta).
```
npm install sails@beta --save
```
It solve the "RangeError: Maximum call stack size exceeded" but i doesnt solve my original problem.

When i create a new instance model it push notification on other tab, but when i try to update an instance juste created, the tabs which just recieved 'Create notification' does not recieve 'update notification'

**Comment by Oldwo1f** [comment]
I update sails globaly to sails@beta and I tryed again, to create a new app with just you test example.

the test **fail again** when it comme to update Notification.

It works for 2 tabs open on same port (1337)
But it dosnt if i start one tab on port 1337 and one tab on port 1338. (I lifted the exact same app with just a User api generated by sails )

It a MAJOR BUG

**Comment by Oldwo1f** [comment]
@sgress454 

I did test your solution above few times on differents sails versions ( installed globally : each time i created an empty sails app with generator "new")
I followed your 18 steps but i never worked for me. I can t see any update event unless i refresh a browser tab..

I even tryed on latest BETA version @~0.12.0-rc1

Can you please comfirm me that when you make this test yourself it work for you. If yes, can you tell me wich version of mongoDB and Redis you are currently using.

Thanks

**Comment by sgress454** [comment]
Hi @Oldwo1f, I'm not sure how I was getting that test to work before.  I've confirmed that this is an issue.  Going to track this on #3008 which has a more specific description of the problem, so keep an eye on that one, I'll be posting some stuff today.  Thanks for being patient and diligent with this!

**Comment by Oldwo1f** [comment]
Thanks for your answer, i ll look on #3008
