### ISSUE TITLE
Hiding console messages in production

### ISSUE THREAD

**Issue by nonpc** [balderdashy/sails#2953]
The browser console fills up quite quickly on app restarts even when in production.
There should be a setting to remove the browser console messages when in production.

**Comment by sgress454** [comment]
What browser console messages are you referring to?

**Comment by nonpc** [comment]
Sorry for the late response.

I'm talking about the default browser console messages like:

>  |>    Now connected to Sails.
> \___/   For help, see: http://bit.ly/1DmTvgK
>        (using browser SDK @v0.11.0)

,

> Socket is trying to reconnect to Sails...
> _-|>_-  (attempt #1)

And others. I can see that they're hardcoded to the sails.io.js file.

**Comment by sgress454** [comment]
Those messages should be suppressed in production.  Are you sure your app is lifted in the production environment?  Does it says `Environment : production` beneath the sailboat after you run `sails lift`?

**Comment by nonpc** [comment]
Just installed a new sails app and it seems that you are right.
Apparently, --production (only --prod does) does not start the production version :(

**Comment by sgress454** [comment]
Ok then!  Glad that's cleared up :)
