### ISSUE TITLE
[Question] Is there a 'sails lift' webserver log?

### ISSUE THREAD

**Issue by ogrotten** [balderdashy/sails#2957]
I'm having a random (and I mean random) lock up with 'sails lift' where the server stops responding to web requests. sometimes it's between link clicks as I'm running around on the projects (< 2s), or, I just now left it idle for 15m and it continued to work... for a while, anyway.

I'm using nodemon which makes restarts easy, but it does it even without nodemon.

If there's a log somewhere, or that can be enabled, I'd be able to start troubleshooting.

**Comment by brandtheisey** [comment]
If you change the logging level to 'silly' you will see all the routes getting loaded, grunt tasks, config files etc. It's probably the best way to see whats going on.

You can add this section to your config/local.js file
```
  log: {
    level: 'silly',
}

or this to your config/log.js if you aren't using local.js:
module.exports.log = {
  level: 'silly',
};

**Note: this will create a torrent of output.**

**Comment by ogrotten** [comment]
yeah i've seen silly logs.

Thanks for the answer *and the specifics of how to set it*
