### ISSUE TITLE
Combining Sails with Aurelia

### ISSUE THREAD

**Issue by RobertDiebels** [balderdashy/sails#2962]
Hi guys,

This is not really an issue, but I couldn't submit anything in the Sails101 repo-list.

However, I would like to submit something you may find useful. I just created a Gist on how to set up a Dev environment for SailsJS to serve an Aurelia app.

It's over here: https://gist.github.com/RobertDiebels/f5f76b874bd8ecfe1e9b

If you can please punch some holes in it. If not, feel free to use it. Any feedback is welcome.

Thanks, Robert.

**Comment by ChrisClayton** [comment]
@RobertDiebels Awesome gist. You'd probably get more feedback by sharing it on [gitter.im/balderdashy/sails](https://gitter.im/balderdashy/sails) or on the [google group](https://groups.google.com/forum/#!forum/sailsjs)

**Comment by tjwebb** [comment]
That looks really cool; if you can package that up in its own repo, maybe the sails101 folks would like to add it? cc @loicsaintroch

**Comment by RomainLanz** [comment]
Thanks @RobertDiebels, it's what I've looking for!
