### ISSUE TITLE
Filter input data

### ISSUE THREAD

**Issue by joaolucas89** [balderdashy/sails#2970]
is there any way to filter incoming data? For example:

"      hello Lucas    " -> "hello lucas" - Like string trim

I need stringtrim, striptags, another one, etc. U have strategy for this situations ?

But I need this proccess automatically. :+1:

**Comment by Josebaseba** [comment]
I've created a hook for that, maybe it's not what you want but it can give you an idea about what you can do.

https://github.com/Josebaseba/sails-hook-validator

**Comment by joaolucas89** [comment]
Almost there, you have a good work :+1: 

module.exports = {
attributes:{},
filters: {
name: ['toLower','striptags'],
age: ['toInt']
}
}


Just an example :+1:  amazing idea yeah ?

**Comment by joaolucas89** [comment]
I'm talking about model :D

**Comment by Dallas62** [comment]
@joaolucas89 This is not implemented, but you can do it by your own:

https://github.com/balderdashy/waterline-docs/blob/master/models.md#callbacks-on-create

**Comment by sgress454** [comment]
Thanks for the discussion all.  @joaolucas89, just FYI we try to restrict this forum to reports on bugs in the Sails core, just to keep it manageable.  Support requests and feature discussions are better off in the [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Gitter Chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
For input filtering, I'd suggest using [policies](http://sailsjs.org/#!/documentation/concepts/Policies) that assign the altered parameters to keys in [req.options](http://sailsjs.org/#!/documentation/reference/req/req.options).  That way you can access them from your controllers without having to mutate the original request data.
