### ISSUE TITLE
Can't create custom blueprint action

### ISSUE THREAD

**Issue by snowcxt** [balderdashy/sails#2979]
I created a custom blueprint action as per https://github.com/balderdashy/sails-docs/blob/master/reference/blueprint-api/blueprint-api.md. But turn out to be "Ignoring attempt to bind route" error.

**Comment by sgress454** [comment]
Hi @snowcxt, you'll have to post some code.  The portion of your `config/routes.js` file that points to your custom blueprint would help, along with the full error message you're getting.

**Comment by snowcxt** [comment]
Sure, I created count.js under api/blueprints and code is:
```javascript
module.exports = function (req, res) {
    res.ok("{ count: response }");
};
```

Here is the routes.js
```javascript
module.exports.routes = {
  '/': {
    view: 'homepage'
  },

  'GET /myRoute': { blueprint: 'count' }

};
```

Then I ran `sails lift` and got error:

![image](https://cloud.githubusercontent.com/assets/1463415/7940764/bcc4a1e0-0907-11e5-9509-e2119c7d6c2d.png)

**Comment by sgress454** [comment]
@snowcxt The error message gives you a big clue!  See the [documentation for the blueprint route target syntax](http://sailsjs.org/#!/documentation/concepts/Routes/RouteTargetSyntax.html?q=blueprint-target-syntax) for more details.  Custom blueprints aren't automatically bound to every model like the CRUD ones are.  You have to add those routes yourself, and you need to either explicitly declare in the route binding which model you want to work with, or use the model name as the first part of the path.  So:

```
'GET /user/myRoute': { blueprint: 'count' }
```
or

```
'GET /myRoute': { blueprint: 'count', model: 'user' }
```
and then in `count.js`, something like:

```
module.exports = function (req, res) {
    sails.models[req.options.model].count(function(err, count) {
      return res.send("There are " + count + " instances of " + req.options.model + ".");
    });
};
```

**Comment by snowcxt** [comment]
Thank you. But  `GET /myRoute': { blueprint: 'count', model: 'user' }` is not working for me. `'GET /user/myRoute': { blueprint: 'count' }` will give me a 404 error when I use url http://localhost:1337/user/myRoute

**Comment by sgress454** [comment]
Works fine for me...do you have a model named User?  In `api/models/user.js`?

**Comment by snowcxt** [comment]
Yes I have. BTW, I'm using sails 0.11.0

On Mon, Jun 8, 2015 at 4:13 PM, sgress454 <notifications@github.com> wrote:

> Works fine for me...do you have a model named User? In api/models/user.js?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/balderdashy/sails/issues/2979#issuecomment-110168688>.
>



-- 
Thanks,
Thomas

**Comment by sgress454** [comment]
Can you post a link to your repo?
