### ISSUE TITLE
bash sails command not found

### ISSUE THREAD

**Issue by AaronJin2013** [balderdashy/sails#2981]
Hi,

I use the MacBook, OSX Yosemite. node v0.12.2.

Now, I use "npm -g install sails", it's looked success, only prompt 
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib

And then, I want to run sails, but not ok.
-bash: sails: command not found.
I want to which it ,but 'which sails' is nothing.

Maybe I lost someting? Who can help me? I have no clue.

**Comment by AaronJin2013** [comment]
It's list like this


-
> sails@0.11.0 preinstall /Users/aaron.jin/training/node_modules/sails
> node ./lib/preinstall_npmcheck.js

Sails.js Installation: Checking npm-version successful
npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
 
> ws@0.5.0 install /Users/aaron.jin/training/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
 
> ws@0.4.31 install /Users/aaron.jin/training/node_modules/sails/node_modules/sails-hook-sockets/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
sails@0.11.0 ../node_modules/sails
├── sails-build-dictionary@0.10.1
├── cookie@0.1.2
├── cookie-signature@1.0.4
├── grunt-contrib-copy@0.5.0
├── mock-res@0.1.0
├── mock-req@0.1.0
├── connect-flash@0.1.1
├── commander@2.1.0
├── sails-stringfile@0.3.2
├── merge-defaults@0.1.4
├── colors@0.6.2
├── pluralize@0.0.12
├── grunt-sails-linker@0.9.6
├── node-uuid@1.4.3
├── async@0.9.2
├── uid-safe@1.1.0 (base64-url@1.2.1, native-or-bluebird@1.1.2)
├── grunt-contrib-concat@0.3.0
├── reportback@0.1.9 (switchback@1.1.3)
├── grunt-contrib-clean@0.5.0 (rimraf@2.2.8)
├── semver@2.2.1
├── rc@0.5.5 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.3.3, minimist@0.0.10)
├── fs-extra@0.8.1 (jsonfile@1.1.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── ejs-locals@1.0.2
├── method-override@2.3.3 (methods@1.1.1, vary@1.0.0, parseurl@1.3.0, debug@2.2.0)
├── anchor@0.10.2 (validator@3.22.2)
├── ejs@0.8.8
├── grunt-cli@0.1.13 (findup-sync@0.1.3, nopt@1.0.10, resolve@0.3.1)
├── grunt-sync@0.0.8 (promised-io@0.3.3)
├── sails-disk@0.10.8 (waterline-errors@0.10.1, async@0.2.10, waterline-criteria@0.11.1, waterline-cursor@0.0.5)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── i18n@0.5.0 (sprintf@0.1.5, debug@2.2.0, mustache@2.0.0)
├── grunt-contrib-coffee@0.10.1 (chalk@0.4.0, coffee-script@1.7.1)
├── grunt-contrib-cssmin@0.9.0 (chalk@0.4.0, clean-css@2.1.8, maxmin@0.1.0)
├── grunt-contrib-jst@0.6.0 (chalk@0.4.0, grunt-lib-contrib@0.7.1)
├── include-all@0.1.6 (underscore.string@2.3.1)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.6, winston@0.8.3, utile@0.2.1)
├── sails-generate@0.12.3 (sails-generate-api@0.10.0, sails-generate-gruntfile@0.10.10, sails-generate-new@0.10.19, async@0.2.10, sails-generate-adapter@0.10.5, sails-generate-generator@0.10.11, sails-generate-views-jade@0.10.3, sails-generate-views@0.10.5, sails-generate-sails.io.js@0.11.5, sails-generate-backend@0.12.2, sails-generate-frontend@0.11.5, sails-generate-model@0.10.10, sails-generate-controller@0.10.8)
├── lodash@2.4.2
├── captains-log@0.11.11 (rc@0.3.5, lodash@2.4.1)
├── grunt-contrib-uglify@0.4.1 (chalk@0.4.0, maxmin@0.1.0, uglify-js@2.4.23)
├── sails-util@0.10.6 (json-stringify-safe@5.0.1, switchback@1.1.3, optimist@0.6.1, underscore.string@2.3.3)
├── grunt-contrib-watch@0.5.3 (tiny-lr@0.0.4, gaze@0.4.3)
├── grunt@0.4.2 (which@1.0.9, dateformat@1.0.2-1.2.3, eventemitter2@0.4.14, getobject@0.1.0, async@0.1.22, hooker@0.2.3, rimraf@2.0.3, nopt@1.0.10, exit@0.1.2, minimatch@0.2.14, glob@3.1.21, lodash@0.9.2, coffee-script@1.3.3, underscore.string@2.2.1, iconv-lite@0.2.11, findup-sync@0.1.3, js-yaml@2.0.5)
├── skipper@0.5.5 (string_decoder@0.10.31, dot-access@0.0.3, skipper-disk@0.5.4, async@0.2.10, debug@2.2.0, multiparty@3.2.10, connect@2.25.10)
├── express@3.16.0 (basic-auth@1.0.0, merge-descriptors@0.0.2, escape-html@1.0.1, range-parser@1.0.0, fresh@0.2.2, vary@0.1.0, media-typer@0.2.0, parseurl@1.2.0, methods@1.1.0, buffer-crc32@0.2.3, depd@0.4.4, debug@1.0.4, commander@1.3.2, proxy-addr@1.0.1, send@0.8.1, mkdirp@0.5.0, connect@2.25.0)
├── waterline@0.10.23 (async@1.0.0, bluebird@2.9.27, deep-diff@0.3.2, switchback@1.1.3, waterline-criteria@0.11.1, waterline-schema@0.1.17, lodash@3.9.3)
├── express-handlebars@1.0.3 (graceful-fs@3.0.8, promise@5.0.0, semver@3.0.1, glob@4.5.3, handlebars@2.0.0)
├── sails-hook-sockets@0.11.21 (semver@4.3.6, machinepack-urls@3.1.1, socket.io@1.3.5)
└── grunt-contrib-less@0.11.1 (chalk@0.4.0, async@0.2.10, maxmin@0.1.0, less@1.7.5)

**Comment by nikhiljohn10** [comment]
Must be something to do with the node version. i have node 0.10.36 in my centos & fedora. It is working smooth with sails 0.11.0.

**Comment by sgress454** [comment]
I'm guessing you changed the default npm install directory but didn't add it to your `$PATH`.  Any custom install path would be set in your `~/.npmrc` folder as `prefix`; make sure you add that to your path in your `~/.profile` or `/etc/paths` file.

**Comment by dashmug** [comment]
I was just setting up sails on a fresh Ubuntu development server and got this error as well.

I don't think there's a problem with my paths since bower, grunt, etc. are working.

**Comment by dularion** [comment]
I had the same issue just now, and the npm version from both yesterday and today are the same. So yesterday: 
npm -v //2.11.3
npm install -g sails //worked fine
sails //command found

today:
npm -v //2.11.3
sails //command not found

**Comment by PhGeek** [comment]
Why is this issue closed as it seems no one got it solved?

I saw in some internet posts that nvm should be the right way of dealing with node installations nowadays. So the proposed path setup would not be the solutions as I'll be dealing with some different versions and paths.

I'm complaining because it was closed in less than 1 day with the argument of being "guessing". And no one said it was "solved" instead more people come here looking for a solution.

**Comment by PhGeek** [comment]
I'm using ubuntu and nvm and got same error today.
Could get it working by nvm way wich would be the correct. Hoping to work through different node versions.

In command line:
    `$ export NVM_SYMLINK_CURRENT=true`

You may need to re-enter `$ nvm use 0`... 0 is the short for node v0.12.7 which I'm using for sails.

Hope it helps.

**Comment by jeff-ofobrukweta** [comment]
this helped me : npm install npm@latest -g
