### ISSUE TITLE
how to use the database not depend on the ORM

### ISSUE THREAD

**Issue by funkyLover** [balderdashy/sails#2982]
I got a mysql database,
the table and data is already existed,
I am afraid of using sails' ORM will change the table's structure
but I truely need the built-In model methods

such as I got a mysql table named 'groups'
```
CREATE TABLE IF NOT EXISTS `groups` (
  `id` int(11) NOT NULL,
  `creater_user_id` int(11) NOT NULL,
  `conv_id` varchar(63) NOT NULL,
  `icon_path` varchar(255) CHARACTER SET ascii DEFAULT NULL,
  `subject` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
  `intro` varchar(255) CHARACTER SET utf8mb4 DEFAULT NULL,
  `tags` varchar(255) CHARACTER SET ascii DEFAULT NULL,
  `state` int(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL
)
```
what should I do with my model `groups` so that I can use the build-in method like `Groups.create()`?

In addition the table `groups` structure maybe change later,
is there someway can make that model adapt to the table's structure?

**Comment by sgress454** [comment]
Hi @funkyLover, thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core; for support queries please try our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live Gitter chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com/questions/tagged/sails.js?sort=newest&pageSize=50).
<hr/>
To use an existing DB without any danger of changing the structure, you can use the `migrate: safe`.  See [the ORM docs](http://sailsjs.org/#!/documentation/concepts/ORM/model-settings.html?q=migrate) for more details.  As far as having Sails automatically build a model around your table's structure, there's nothing built in to the core for that, but I believe there may be some community members working on such a project.
