### ISSUE TITLE
MAJOR BUG with publishUpdate()/publishCreate() accross multiple apps

### ISSUE THREAD

**Issue by Oldwo1f** [balderdashy/sails#2990]
Hi sails team.

I found a bug in sails. I opened a new issue referencing that bug with some complete example and test.

But you closed my issue before its resolved so i have no other choice to make a new.

In few words: **publishCreate() does not subscribe** sockets watching one collection to the new instance created. But it fail only when we are under multiple apps. (I use 'socket.io-redis' see previous issue for details)

This is the reference of previous issue with test case and details: [#2947](https://github.com/balderdashy/sails/issues/2947#issuecomment-107288237)

**Comment by RWOverdijk** [comment]
Your sentences are really difficult to understand. What could help, is supplying a repository with instructions on how to reproduce this bug.

**Comment by Oldwo1f** [comment]
sorry for my english . . .

There is a repository that reproduce this bug.
You can also find instructions to reproduce this in [#2947](https://github.com/balderdashy/sails/issues/2947#issuecomment-107288237)
Also sgress454 explained me a way to test the problem (details in [#2947](https://github.com/balderdashy/sails/issues/2947#issuecomment-107288237)) But his way do not work for me

**Comment by Oldwo1f** [comment]
go see #3008 

and i close this
