### ISSUE TITLE
Force model to alter even in production mode

### ISSUE THREAD

**Issue by mateeyow** [balderdashy/sails#2991]
Is there a way to force model to alter even in production mode? Also does the individual model `alter` settings supersede the configuration of the model under **config** folder?

**Comment by tjwebb** [comment]
the way to do this is to temporarily change your NODE_ENV value, if that's really what you want to do. Setting migrate to alter in production mode is impossible. The check is hardcoded

**Comment by mateeyow** [comment]
Thanks a lot @tjwebb
