### ISSUE TITLE
What version of Sails to use? 0.11.0? 0.11.1? 0.11.1-rc1?

### ISSUE THREAD

**Issue by Vadorequest** [balderdashy/sails#2998]
I'm wondering if the version `0.11.1` and `0.11.1-rc1` are stable enough to be used.

I believe the `0.12.0-rc1` is still under development?

Similar question asked there but didn't get any answer: https://groups.google.com/forum/#!topic/sailsjs/1Fi74H3zw6U

**Comment by CWyrtzen** [comment]
I'll find out for sure and update when I get the answer~

**Comment by tjwebb** [comment]
Yes, 0.11.0 is the latest stable release.

**Comment by CWyrtzen** [comment]
great tip from @sgress454 

The latest stable version of Sails is v0.11.0.  You can always tell the latest version by doing `npm show sails` and looking at the "latest" tag version, or by going to https://github.com/balderdashy/sails/tree/stable and checking the version there.

**Comment by tjwebb** [comment]
There have been a number of questions on this topic I think because only the release candidate was listed in the Github release page. I've since updated this: https://github.com/balderdashy/sails/releases
