### ISSUE TITLE
Unable to reset model instance attribute

### ISSUE THREAD

**Issue by juanpasolano** [balderdashy/sails#3002]
Before we start: I have made a very small git repo with seed data and two REST endpoints to test this issue here: https://github.com/juanpasolano/sails-nested-test

So I have 3 models: `Appointment` which has many `procedure` which has one to one `procedureItem`.
Since there is not nested population in sails I am getting `procedures` with `procedureItem` by hand using something like:

```
Appointment.find(1).exec(function(err, appointments){
			if(err) return res.negotiate(err);
			async.eachSeries(appointments, function(appointment, cb){
				Procedure.find({appointment: appointment.id}).populate('procedureItem').exec(function(errP, procedures){
					if(errP) return cb(errP);
					appointment.procedures = procedures;
					appointment.proceduress = procedures;
					cb()
				})
			}, function(errE){
				if(errE) return cb(errE);
				res.ok(appointments)
			
```

So the issue is when I want to replace the `procedures`attribute with the new array procedures (which has the nested depth i need), but if you hit the endpoint, there is no procedure attribute available.   
As a test I have attached the same new procedures array to `proceduress` (double s) attribute and this one gets properly set.   
I have tried using the `.toObject()` method with no luck.  
Have tried sails 0.10.5 and 0.11.0 with no luck.

**Comment by CWyrtzen** [comment]
Hi @juanpasolano - did you find a resolution or answer for this problem?

**Comment by juanpasolano** [comment]
Not a proper solution, more like a workaround.
I had to get the appointments and do a foreach and clone each item using `_.clone()` and push them to a new array. And then everything worked.

Are you having the same issue?
Have a look at [this stackoverflow question](http://stackoverflow.com/questions/30695922/unable-to-reset-model-instance-attribute-in-sailsjs) i made. Upvote it to get more people to see it.

**Comment by sgress454** [comment]
@juanpasolano it's not a bug, but it's also not the easiest thing to wrap your head around.  I posted on your SO question, hope that helps!

**Comment by juanpasolano** [comment]
Thanks for the answer
I did try `toObject()` and it didn't work. I have and endpoint doing that in the demo.
