### ISSUE TITLE
req.ip format error on saving with waterline

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#3009]
sails version 0.10.5.

in controller
var ip = req.ip;
> ::ffff:127.0.0.1

in waterline will get an error:
>  • `undefined` should be a ip (instead of "::ffff:127.0.0.1", which is a string)

**Comment by RWOverdijk** [comment]
What does the model definition look like?

**Comment by calidion** [comment]
```javascript
register_ip : 'ip'
```

**Comment by RWOverdijk** [comment]
https://github.com/chriso/validator.js/pull/399

**Comment by particlebanana** [comment]
Looks like @RWOverdijk patched this up in Validator and the latest version of Anchor has it up to date. Calling this one closed.
