### ISSUE TITLE
start chrome after started sails

### ISSUE THREAD

**Issue by masnatacion** [balderdashy/sails#3010]
how can i run google chrome after started sails ?

**Comment by tjwebb** [comment]
This really needs clarification. I'm guessing you're not asking how to double click on the Chrome icon on your desktop. But I don't really know what you want.

**Comment by CiscoKidxx** [comment]
LOL

**Comment by masnatacion** [comment]
@tjwebb ok, I finally run chrome after started sails.

In our file config/bootstrap.js I wrote this:

var exec = require('child_process').exec,
    child;

module.exports.bootstrap = function(cb) {

  	// It's very important to trigger this callback method when you are finished
  	// with the bootstrap!  (otherwise your server will never lift, since it's waiting on the bootstrap)
  	cb();

  	var chrome = "exec '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'  --kiosk http://localhost:1337";

  	if(/^win/.test(process.platform))
  		chrome = 'start "Chrome" chrome --kiosk http://localhost:1337';


	child = exec(chrome,
	  function (error, stdout, stderr) {
	    console.log('stdout: ' + stdout);
	    console.log('stderr: ' + stderr);
	    if (error !== null) {
	      console.log('exec error: ' + error);
	    }
	});

  
};

**Comment by tjwebb** [comment]
Awesome! I have no idea why you'd ever want to do this, but thanks for posting the solution in case anyone else runs across here.

**Comment by masnatacion** [comment]
@tjwebb because, I will want to run sails and chrome when started my pc like a kiosk
