### ISSUE TITLE
Do you have sails 0.10.5 sourcecode packages ?

### ISSUE THREAD

**Issue by tanchun** [balderdashy/sails#3011]
amazing work!
i need sails 0.10.5 sourcecode packages, do you have it? or where i can got ?
because i have error install sails
"
npm ERR! error installing sails@0.8.895 Error: No compatible version found: forever@'>=0.10.0- <0.11.0-'
npm ERR! error installing sails@0.8.895 Valid install targets:
npm ERR! error installing sails@0.8.895 ["0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.6.8","0.6.9","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.9.0","0.9.1","0.9.2"]

"

sorry,my english is not good , please

**Comment by tjwebb** [comment]
> sails@0.8.895

First, `0.8.895` is not a version. That's why npm is complaining. Just run `npm install sails` and it will install the latest version.

**Comment by zieglar** [comment]
@tanchun `npm install sails@0.10.5` 加油
