### ISSUE TITLE
Links to Documentation don't work as intended

### ISSUE THREAD

**Issue by dyeje** [balderdashy/sails#3016]
When you google something such as 'sails assets' you are given a google result with the link:

http://sailsjs.org/#!/documentation/assets

When you click on the link, you are redirected to the Table of Contents instead.  This is disorientating and frustrating for the user.

**Comment by kevinburkeshyp** [comment]
unfortunately this has been broken for about a year now. see for example https://github.com/balderdashy/sails/issues/2594

**Comment by dyeje** [comment]
Ah yes, that is exactly the issue.  It is rather disappointing to see that this has been known for months and not yet fixed.  It is a very serious usability problem.

**Comment by tjwebb** [comment]
fwiw, we're getting ready to deploy a new sailsjs.org website to solve this very problem, among others: https://github.com/balderdashy/www.sailsjs.org/tree/v1.0

**Comment by dyeje** [comment]
Awesome, sounds good.
