### ISSUE TITLE
Can't use local mongodb

### ISSUE THREAD

**Issue by snowcxt** [balderdashy/sails#3020]
I tried to connect to my local mongodb. But I got this error:
![image](https://cloud.githubusercontent.com/assets/1463415/8237945/8479bd3c-15a7-11e5-8d12-6c84ba625f0c.png)

I tried to fix it by this approach: http://stackoverflow.com/questions/28651028/cannot-find-module-build-release-bson-code-module-not-found-js-bson#answers

But still not working
![image](https://cloud.githubusercontent.com/assets/1463415/8238103/72456c82-15a8-11e5-9658-1ef4c55b4c29.png)

My config:
connections.js
```javascript
module.exports.connections = {
  localMongodbServer: {
    adapter: 'sails-mongo',
    url: 'mongodb://localhost/test'
  }
};
```
models.js
```javascript
module.exports.models = {
    connection: 'localMongodbServer',
    migrate: 'alter'
};
```

**Comment by snowcxt** [comment]
I just found that I have to config the connections.js in this way for the local mongodb.

```javascript
localMongodbServer: {
    adapter: 'sails-mongo',
    host: 'localhost', 
    port: 27017,
    database: "test"
  }
```

**Comment by nikhiljohn10** [comment]
try the following
```
$ rm -rf node_modules
$ npm cache clean
$ npm install
```
see if the error still exists.

**Comment by tjwebb** [comment]
@snowcxt this might be better asked in the sails-mongo project.
