### ISSUE TITLE
Sails email validator rejecting valid emails

### ISSUE THREAD

**Issue by Andrew-Max** [balderdashy/sails#3034]
using sails 0.11.0

I'm really not sure where the specific code for this validator lives or whether or not it is in waterline and not the sails core.

My tests are failing becuase of a line in a user model which validates that emails must be of type email.

My user model includes: 

```
  attributes: {
    email: {
      type: 'string',
      email: true
    },
  }
```

When I run a test that instantiates a user I get the error:
 
```
Invalid attributes sent to User:
 • email
   • "email" validation rule failed for input: 'testUser@test.com'
```

This exact same line is passing for other people but I am getting no indication as to what about it is actually failing for me.

I may just need to be pointed to the actual validator code so I can see what about this is actually failing but this seems like odd behavior

**Comment by marclr** [comment]
I'm using Sails 0.10.5, but it should be the same syntax. The error is that type should be 'email', so the correct model is:
```javascript
  attributes: {
    email: {
      type: 'email'
    }
  }

**Comment by tjwebb** [comment]
@Andrew-Max any updates?

**Comment by Andrew-Max** [comment]
@tjwebb  I think this may be more of a documentation error.

Another team member had added this code based of  off the documentation at: http://sailsjs.org/documentation/concepts/models-and-orm/validations#/validation-rules
under the email rule.

After looking at some online examples I got it working trying @marclr 's way  but the docs make it appear that the first way would be valid and indeed did work for my coworker with sails 0.10

**Comment by kevinburkeshyp** [comment]
I suddenly just hit this edge case in tests, after code that had been working (or silently accepting invalid emails) had been working for a year plus. the thing that changed is I just reinstalled dependencies. did something waterline or sails depend on suddenly update to change this behavior?

**Comment by particlebanana** [comment]
Looks like [validator changed their email handling](https://github.com/chriso/validator.js/issues/404) and it's causing issues for gmail addresses. We did bump the validator dependency about a month ago.

**Comment by RWOverdijk** [comment]
@particlebanana The fix has been applied to validator. 3.41.2 contains the fix.

**Comment by particlebanana** [comment]
Ok I'll update Anchor to use the latest version.

**Comment by ahmadthd** [comment]
change it to >>

  email: {
      type: 'string',
      email: {}
    },

**Comment by amyjhg** [comment]
Using sails 0.11.0
I had exactly the same problem.
And finally it work when I change 
attributes: {
    email: {
      type: 'string',
      email: true
    },
  }
to:
attributes: {
    email: {
      type: 'email',
    },
  }
The point is change the type to 'email' and delete "email: true".

**Comment by mschraeder** [comment]
Thanks!

Changing it to type:'email' fixed it for me.

**Comment by livin** [comment]
When updating project to sails v0.11.3 from v0.10 our automatic test caught the issue.

Updating email field type fix helped me too.

Thanks!
