### ISSUE TITLE
sailsjs.org is down

### ISSUE THREAD

**Issue by gunish** [balderdashy/sails#3037]
The main website is down and an application error is displayed. 

![screen shot 2015-06-26 at 14 10 57](https://cloud.githubusercontent.com/assets/1183862/8377892/3123bfcc-1c0d-11e5-988a-a28b9ad90410.png)

**Comment by AlexSwensen** [comment]
Someone must have pushed the button, as its back online now.

**Comment by tjwebb** [comment]
Yep, sorry about that. We've been updating the website recently. Thanks for pointing this out.
