### ISSUE TITLE
Websocket get not working

### ISSUE THREAD

**Issue by mwils-bp** [balderdashy/sails#3040]
I'm having a strange issue when using the websocket, when the below is in the console, everything works:

      |>    
    \___/  

    sails.io.js:200  `io.socket` connected successfully.
    (for help, see: http://sailsjs.org/#!documentation/reference/BrowserSDK/BrowserSDK.html)

But if not nothing happens, you can view this happening here: http://ngsnipp.com/

**Comment by tjwebb** [comment]
We need to see how your configuration is set up in the code. What version of sails and sails.io are you using?

**Comment by mwils-bp** [comment]
M issue was that I had upgraded to v0.11.0 but my sails.io wasn't the latest.

Please close this issue, sorry!
