### ISSUE TITLE
sails still tries to load ejs module even when views hook is disabled

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails#3041]
If I disable the "views" hook, I still get this error when lifting the app:

```sh
Could not find module: ejs
```

It's benign, but looks scary. Trying to set config.views.engine to null causes worse problems.

**Comment by lucasconstantino** [comment]
How can I reproduce it? I tried to simple set `hooks.views = false` at *.sailsrc* on a fresh project and I did not get this message on lifting.

**Comment by tjwebb** [comment]
@lucasconstantino You need to remove the `ejs` module from node_modules and package.json

**Comment by tjwebb** [comment]
Well I just tried to reproduce this and setting views: false does seem to disable the hook. Either way, I'm working on refactoring/cleaning up the views hook slightly.
