### ISSUE TITLE
How can I disabled grunt watch in production?

### ISSUE THREAD

**Issue by cage1618** [balderdashy/sails#3048]
How can I disabled grunt watch in the production env? The grunt process consume a lot of memory in my production env but it is useless!

thanks!

**Comment by jeffjewiss** [comment]
Grunt watch shouldn't be running in production by default. How is your app deployed, do you have the NODE_ENV set to production? Are you modifying files in production and seeing grunt tasks executing or are you just seeing what looks like high memory usage? How much memory is being used by your app?

**Comment by tjwebb** [comment]
Yea, if you're running sails with `NODE_ENV=production`, grunt watch won't be running.
