### ISSUE TITLE
use npm version to tag releases

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails#3054]
@sgress454 @mikermcneil can you guys use `npm version` to tag releases, and then just `git push --tags`? It looks like 0.12-rc2 is published to npm, but there's no corresponding tag on github. It makes it difficult to search and debug issues in untagged releases.

**Comment by sgress454** [comment]
Yup, sorry about that.  Pushed tags for v0.12.0-rc1 and v0.12.0-rc2.
