### ISSUE TITLE
error: Invalid usage of publishCreate() :: Values must have an `id`, instead got ::

### ISSUE THREAD

**Issue by visitsb** [balderdashy/sails#3060]
Hey guys,
I get `error: Invalid usage of publishCreate() :: Values must have an `id`, instead got ::` on sails@0.11.0

After digging through issues, it looks like [this was already posted and resolved](https://github.com/balderdashy/sails/issues/2105). One related [issue mentioned that you shouldn't use `id`](https://github.com/lynnaloo/yacht-rock/issues/8), so that this error goes away.

I posted a comment which looks like [there might be a cornercase](https://github.com/balderdashy/sails/commit/fc6a8f03d6e9453035cedddb80719ac4bf1ba7f0#diff-79fa3070e98dd5fb8c972eb97e075ebaR1077) in the way the check for raising this error message is handled.

For convenience, the comment is copied below mentioned specifically against [the offending check](https://github.com/balderdashy/sails/blob/master/lib/hooks/pubsub/index.js#L1097) :-)

If `values[this.primaryKey]` turns out to be `0`, then is the behavior _still_ correct? 

To me, it is not apparent if this check needs 
- a PK to exist ([_.isUndefined?](https://lodash.com/docs#isUndefined)), or 
- an actual value for a PK to be available ([_.isFinite?] (https://lodash.com/docs#isFinite))

?

**Comment by CWyrtzen** [comment]
Are you still getting this error? Was your questioned answered in the other issue?

**Comment by visitsb** [comment]
Yes, it is still open. 

`values[this.primaryKey]` is (going to) give this error no matter if I use `id` attribute or not.
