### ISSUE TITLE
Gulp integration natively

### ISSUE THREAD

**Issue by Karnith** [balderdashy/sails#3061]
I am currently working on integrating gulp natively within sails. I plan on creating a switch, something like --gulp for the sails new command. Any ideas on the best way to do this so that it adheres to sails best practices?

Although I'm doing this for myself, if I get everything sorted and working appropriately would this be a candidate for pr integration into sails master?

~Karnith

**Comment by sgress454** [comment]
Hi @Karnith, we probably wouldn't merge something like this into Sails core, since we're actively trying to *reduce* the features in core.  But we'd love it if it were implemented as a [hook](http://sailsjs.org/documentation/concepts/extending-sails/hooks)...

**Comment by Karnith** [comment]
@sgress454 I already have a hook for this, but I find it cumbersome to have the hook and all the other generators (gulp file, new, backend) just to use gulp. Since there is a demand to use gulp I'm going to split off the branch and convert entirely to gulp. If, at a later date, the team want to merge branches we can. I, for one, find it far easier and effective to use gulp instead of using grunt. I have the framework almost totally converted already. It only took me a little bit of time to convert.

**Comment by tjwebb** [comment]
You can combine all the functionality you need into a single hook, and have the hook handle everything. Can you be more specific about what your pain points are with using hooks currently?

**Comment by Karnith** [comment]
Hi All,

I just released the first version of my sailsgulpify machine pack

https://github.com/Karnith/machinepack-sailsgulpify

What this machine pack does is add gulp to a project and allow you to toggle between gulp and grunt engines. The machine pack will also add all the gulp dependencies needed to run.

For those that know of or used my generators in the past, they are now depreciated and will no longer be developed. This is the new way to add gulp to your projects.

TODOS:

Find a way to add the toggleEngine.js to the root of the project after machine pack is installed

I will be converting my angular generatoes to machine pack also, so keep an eye out for them.

~Karnith
