### ISSUE TITLE
Question: How to specify criteria when using model.subscribe

### ISSUE THREAD

**Issue by zoell** [balderdashy/sails#3063]
Hi,

I am trying to use the model.subscribe to subscribe socket clients to specific events:
http://sailsjs.org/documentation/reference/web-sockets/resourceful-pub-sub/subscribe

But is there any way to subscribe a socket client to only created items with a specific criteria?

For example I have a Message model:

attributes:
- type
- owner
- message
- id
-createdAt
-updatedAt

Is there any way to subscribe only Messages created with owner 1 or 2?

I tried this:
```
Message.find({owner: 1}).exec(function(e, messages){
     Message.subscribe(req.socket, messages, ['create']);
});
```
In the log I received something like:

```
2015.07.06 16:05:29 SILLY Subscribed to the Message with id=3   (room :: sails_model_message_3:create)
2015.07.06 16:05:29 SILLY Subscribed to the Message with id=4   (room :: sails_model_message_4:create)
2015.07.06 16:05:29 SILLY Subscribed to the Message with id=5   (room :: sails_model_message_5:create)
2015.07.06 16:05:29 SILLY Subscribed to the Message with id=6   (room :: sails_model_message_6:create)
2015.07.06 16:05:29 SILLY Subscribed to the Message with id=7   (room :: sails_model_message_7:create)
```

But when create a new Message with owner=1, my subscriber socket does not receive the event.

Create code:
```
Message.create(data).exec(function(error, data){
    Message.publishCreate({id: data.id, owner: data.owner, message : data.message , type: data.type});
});
```

Or maybe watch is better? I could use watch but there I could not specify any criteria. http://sailsjs.org/documentation/reference/web-sockets/resourceful-pub-sub/watch

**Comment by sgress454** [comment]
Hi @zoell , thanks for using Sails.  Just FYI, this forum is for reporting bugs in the Sails core.  For support in the future, please visit [StackOverflow](http://stackoverflow.com/questions/tagged/sails.js), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
Interesting question--there's no way to do this currently with the built-in logic.  You do need `.watch()` to watch for created instances, but it will send out notifications when _any_ instance of that model is created, not just certain ones based on criteria.  Your best bet would be to create a custom `MessageController.create` action that accepts the data from the request, creates the new instance with `Message.create`, and notifies interested parties using lower-level socket methods like `sails.sockets.join` and `sails.sockets.broadcast` (see [docs for `sails.sockets`](http://sailsjs.org/documentation/reference/web-sockets/sails-sockets)).
