### ISSUE TITLE
Socket Id changes always

### ISSUE THREAD

**Issue by torresl** [balderdashy/sails#3064]
Hi,

   I try to create a chat application. So, i need to know the socket id of the person.  But the socket id always changes .
In my cfig/bootstrap.js, i have this script:
```
module.exports.bootstrap = function (cb) {
	var passport = require('passport'),
    initialize = passport.initialize(),
    session = passport.session(),   
    http = require('http'),
    methods = ['login', 'logIn', 'logout', 'logOut', 'isAuthenticated', 'isUnauthenticated'];
	
  sails.removeAllListeners('router:request');
  sails.on('router:request', function(req, res) {
    initialize(req, res, function () {
      session(req, res, function (err) {
        if (err) {
          return sails.config[500](500, req, res);
        }
        for (var i = 0; i < methods.length; i++) {
          req[methods[i]] = http.IncomingMessage.prototype[methods[i]].bind(req);
        }
        sails.router.route(req, res);
      });
    });
  }); 
  
  sails.io.on('connect', function (socket){
	  console.log(sails.sockets.id(socket));
  });

  cb();
};
```
I should have one socket id displayed in the console.
But this value always changes . The result: 
"
FK27GROQcLu5EnzJAAAr
9g_wxoefQ9Kp2EAvAAAs
A5EcRPX0LJZPmzTqAAAt
PPeggxEFoeGiD-tfAAAu
1uOMUAxaivskwOxgAAAv
rV8GaEU4Hpb8OjRdAAAw
bG6X_wSffC8UEkSLAAAx
awQqASE-ni1nr73FAAAy
MTXiltDd8lwKZYwGAAAz
Sb_Ddk7gjhKi_KnxAAA0
_ZQxJxTG1Kz7qnN0AAA1
0YUs1XBwhQ39o94JAAA2
T807XvHCCv_Ltfb5AAA3
jX3EKeIuxU4j6GtsAAA4
IAmebE9oXI__NBg4AAA5
6Zcm_gjBr0uhSBq9AAA6
p2p_r70T-19Q4kHFAAA7
VSRnhJsygnbbt7LqAAA8
Vk7EHHY17Pld1BSTAAA9
V5H9rq8E4bVa7j4OAAA-
LEnaKkKxNuRIvciAAAA_
r_SEvTPv6NB9dXnqAABA
cDcIO5oKe94z2OQwAABB
"
. So, what to do to not have the socket id always changing ?.

Thanks for advance.

**Comment by sgress454** [comment]
Hi @torresl, thanks for using Sails.  This forum is for reporting bugs in the Sails core.  For support in the future, please visit [StackOverflow](http://stackoverflow.com/questions/tagged/sails.js), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
First of all, by deliberately subverting the Sails router you're kind of defeating the purpose of using the framework at all.  But as for your question about socket IDs, you're logging every time a new socket connects, so of course they'll always have a new ID.  You may be confused about how websockets work--they're not like browser sessions, which use cookies to maintain state across requests to the same site by the same browser.  Sockets last only as long as the client--i.e. a single browser window or tab--is open.  They die when a window or tab is closed *or refreshed*.

**Comment by torresl** [comment]
Thanks for your response.  I created a chat application.  I use the sails.sockets.blast(eventName, data); method and my eventName parameter is the  userid i want to send a message. It works well. But i suppose, as this method sends the event to all users, if there are a lof users , it may have performance problems. what do you think about it ?. Probably, it's better for performance reasons to use the sails.sockets.emit( socketIds, [event], data) method. You just have to pass the socketId of the user you want to send a message. But as the socket id always changes, you need always to save in a database like redis the  new association userid and socketid when the socketid changes. Are there risks to have bugs ?.  What is your point of view about it ?.

**Comment by sgress454** [comment]
You will rarely if ever use `emit` or `blast`.  The most common methods for chat are `join`, `leave` and `broadcast`: subscribe each socket to a user "room", and then broadcast messages for that user to that room.  This allows for a single user to have multiple sockets (i.e. multiple windows/tabs) open.  You can use Sails' models and built-in pub/sub functionality to make this easier.  See the [SailsChat](https://github.com/balderdashy/sailschat) sample app for details, as well as the [resourceful pub/sub documentation](http://sailsjs.org/documentation/reference/web-sockets/resourceful-pub-sub).
