### ISSUE TITLE
Sails "lower" hook's cleanup function

### ISSUE THREAD

**Issue by cheplv** [balderdashy/sails#3067]
As I see now there is no cleanup possibility in sails.lower - i.e. for example cleanup connections for http service or other possible situations.

Maybe need to add "uninitialize" function handler in hook api?

**Comment by sgress454** [comment]
You can listen for the `lower` event:

```
sails.on('lower', function(){...do some stuff...});
```

**Comment by cheplv** [comment]
When you need to cleanup resources used by system on shutdown simple listener for "lower" event is not usable for some complex logic. In "sails.lower" there is dirty hack to just close sockets and http servers, but cannot gracefully for example disconnect from some services or other things. To correct this seems to need override default process signal listeners (lib/app/private/initialize.js) with own function with sails.lower. I.e. make custom sails hook. Thank you for your answer.

**Comment by mikermcneil** [comment]
@cheplv Addressed this recently with a lifecycle callback

**Comment by cheplv** [comment]
@mikermcneil Does anoyone have looked at this issue - due to case gracefuly disconnect from some system which has persistent connection (example RabbitMQ, ActiveMQ)?
