### ISSUE TITLE
OR logic for policies

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#3068]
currently in policies configuration file, we can only got AND logic for all policies.
But in many cases, we need an OR logic for these policies.

let we think about this case.
A door allows only dog.
A door allows only cat.
A door allows only  pig.
A door allows only rabbit.
A door allows both dog and cat.
A door allows both dog and rabbit.
A door allows both cat and rabbit.
A door allows both cat and pig.
A door allows both rabbit and pig.
A door allows both rabbit and pig and dog.
...

we can see that there are only four animals for we will write more policies for these simple or logic combination of them.

policies can be in AND logic.

But it seems OR logic is far more general than AND logic.

Still I haven't had any requirements for AND logic but OR logic.

so I think OR logic is much general logic in policies and should be supported.

**Comment by RWOverdijk** [comment]
You could check if your policy applies to a request, and if not skip it. This means that the next policy has to either allow or deny the request (the final choice).

An alternative approach, is creating a policy which you require yourself in a different policy and call yourself. So you write your own `or` policy.

**Comment by calidion** [comment]
@RWOverdijk 
do you mean this will not be officially supported?

**Comment by RWOverdijk** [comment]
@calidion That's not up to me to decide, but I think it already is. Currently, when your policy is called, you get a response object. If you call res.forbidden() for instance, the response itself will be finished.

You have all the utilities needed to make your own OR policy. You could even call next() with an argument (or use options) for a assessment policy.

**Comment by sgress454** [comment]
As @RWOverdijk said, you can implement this yourself--in any case, there's already an [issue open for it as feature request](https://github.com/balderdashy/sails/issues/1571).
