### ISSUE TITLE
sails.lift returns undefined

### ISSUE THREAD

**Issue by dbkaplun** [balderdashy/sails#3070]
I think `sails.lift()` should return an object I can use and lower... does that make sense? Should I use `sails` as a singleton instead? Come to think of it, can I lift multiple apps at once?

**Comment by RWOverdijk** [comment]
First off, funny profile pic. Second, the answers are no, yes and sort of, respectively.

Sails is currently doing global stuff a lot by default... So there are no application instances. I could give you my opinion on the matter but that'd take ages.

Sails does [use an instance under water](https://github.com/balderdashy/sails/blob/master/lib/index.js#L5) ([which you could use, too](https://github.com/balderdashy/sails/blob/master/lib/index.js#L14)) but that really isn't being advertised anywhere. You could write up your own app.js (I recommend doing that anyway) where you start these instances yourself. If you do decide to go down this road, don't forget to disable all globals in `config/globals.js` or you'll get clashes. Come to think of it, chances are that you'll encounter some issues when lifting multiple instances in the same process anyway. Share your findings with us, I'd love to know how it goes. I'm also curious what you're trying to do :)

**Comment by sgress454** [comment]
`sails.lift` returns an instance of the lifted app in the callback:

```
require('sails').lift(options, function(err, app) {
   app.lower();
});
```

You can absolutely raise and lower multiple instances.  You'll want to make sure you 1) use the Sails constructor to get new instances and 2) turn off globals in the apps' settings, as @RWOverdijk intimated:

```
// Use the .Sails() constructor to create two separate instances
var sails1 = require('sails').Sails();
var sails2 = require('sails').Sails();
sails1.lift({globals: false}, function(err, app1) {...}
sails2.lift({globals: false}, function(err, app2) {...}
```

If you don't turn globals off in the apps, then you can end up with collisions in the global space with models, controllers, etc.  With globals turned off, you'll still have access to the app's Sails instance in controllers, services, etc. as `this.sails`, and in controller actions as `req._sails`.  Models are then available under `sails.models[<model identity>]`.

**Comment by dbkaplun** [comment]
Thanks @sgress454!
