### ISSUE TITLE
Find by computed property

### ISSUE THREAD

**Issue by tbitowt** [balderdashy/sails#3071]
I'm writing API in sails.js and I have one problem with finding objects.

I have model with attributes:

      attributes: {
        firstName:{
          type:"string",
          required:true,
          minLength: 2
        },
    
        lastName:{
          type:"string",
          required:true,
          minLength: 2
        },
        
        getFullName: function (){
          var fl =  this.firstName + " " + this.lastName;
          return fl;
        },
      }

And right now I would like to find a object with getFullName startsWith "xyz qwe"

How can I do it?

I have tried:

`Patient.find({ getFullName: { 'startsWith': 'Tomas' }}).exec(console.log)`

and

`Patient.find({ getFullName(): { 'startsWith': 'Tomas' }}).exec(console.log)`

and both are not working.

Can I access computed property like getFullName in find() function?

Of course this query is working:

`Patient.find({ firstName: { 'startsWith': 'Tomas' }}).exec(console.log)`

**Comment by RWOverdijk** [comment]
That's not possible. You can only query properties that reside in your database.You could split the name (var names = name.split(' ')) and if .length > 1, say firstname=names[0] and lastname startsWith names[1].

**Comment by tbitowt** [comment]
and maybe there is a way to pass my custom function to find method like
```
isNameMatch: function (patient, givenName) {
    var fullName = patient.firstName + ' ' + patient.lastName;
    return fullName.startsWith(givenName);
}
```
? I think it isn't, but I have to ask.

My problem is this function will be more complex, and I have no idea how it can be written in this `query language`

**Comment by RWOverdijk** [comment]
Some databases allow you to do this (cursors and aggregates in mongo for example) but most do not. Sorry.

**Comment by particlebanana** [comment]
Use a `beforeUpdate` to build the `fullName` property and cache it on the record.

**Comment by tbitowt** [comment]
@particlebanana is `beforeUpdate` called on Patient.find()? could you post quick sample how can i handle that?

**Comment by particlebanana** [comment]
You would need to actually store `fullName` in the database, the query would become:

```javascript
Patient.find({ fullName: { 'startsWith': 'Tomas' }}).exec(console.log)
```

You can use `beforeCreate` and `afterUpdate` to make sure its always up to date without having to manually set it. Or get creative with the lifecycle callbacks if you want to try and do it without the update query.

```javascript
{
  attributes: {
    firstName:{
      type:"string",
      required:true,
      minLength: 2
    },

    lastName:{
      type:"string",
      required:true,
      minLength: 2
    },

    fullName:{
        type: "string"
    },
  },

  beforeCreate: function(values, cb) {
      values.fullName = values.firstName + ' ' + values.lastName;
      cb();
  },

  afterUpdate: function(values, cb) {
      var fullName = values.firstName + ' ' + values.lastName;
      User.update({ id: values.id })
      .set({ fullName: fullName })
      .exec(cb);
  }
}
```
