### ISSUE TITLE
REST GET response is inconsistent

### ISSUE THREAD

**Issue by shaunc** [balderdashy/sails#3074]
With a GET request such as `/foos?bar=1`, sails returns an array. However, with GET request `/foos?id=1` it returns a single record, not an array.

This is still a plural request (unlike `/foos/1`) -- sails shouldn't create exceptions. Also what happens when primary key has different name? Will it also return singular items for other unique keys?

**Comment by tjwebb** [comment]
> With a GET request such as /foos?bar=1, sails returns an array. However, with GET request /foos?id=1 it returns a single record, not an array.

Yea, I see your point, but I also see equal arguments for both sides. Sails returns what you ask for. If you give it the primary key of a model, you are necessarily querying a single record. ``/foo?id=1` and `/foo/1` are both equivalent to `/:model/:id`.

**Comment by shaunc** [comment]
Hmm... but isn't it a question of the type of response for a given route? `/foo?...` is a query for multiple things, of which there will only be one, of course, if there is a selection on a attribute which is unique.

I think you are opening a can of worms. What about `/foo?id=[1,1]` or `/foo?name=joe&id=1` or `/foo?name=`joe` when `name` is unique, or `/foo?first='joe'&last='smith'` when first and last are unique together? (You don't support unique together now, but perhaps you might.) Can you figure out all of these cases and return a single record ... or do you turn a singleton array returned by the adapter into a single record all the time? 

You've done a lot of good work, for which I am grateful so I shouldn't quibble... but my advice is to give methods consistent return types and not create exceptional cases unnecessarily.

**Comment by shaunc** [comment]
... or by analogy, in javascript code, I have written expressions like `foo.slice(-1)[0]` often. So should `slice` return an individual element if there is necessarily only one? In fact this would be error prone, as if the parameter passed to slice might be a variable.

So too here, the query dictionary may be generated programmatically by the front end. It will be easy to forget to check for the case (cases?) where the query dictionary is "necessarily" for a singleton.
