### ISSUE TITLE
Mixins in model?

### ISSUE THREAD

**Issue by kaermorchen** [balderdashy/sails#3077]
Hello.

How can I make mixins for models?
I found a [solution](http://irlnathan.github.io/sailscasts/blog/2013/09/15/sailscasts-answers-ep1-question-about-using-a-service-to-allow-inheritance-in-a-model/), but now it doesn't work.

//api/mixins/likesBase.js

    module.exports = {
    	attributes: {
    		likes: {
    			type: 'integer',
    			defaultsTo: 0
    		}
    	}
    };

//api/models/Article.js

    var likesBase = require('../mixins/likesBase');
    
    module.exports = _.merge(likesBase, {
    	attributes: {
    		name: 'string',
    		alias: 'string',
    		body: 'text',
    		teaser: 'text'
    	}
    });

**Comment by aars** [comment]
What exactly doesn't work? I've got a similar setup running smoothly. Only difference is I first `_.cloneDeep` the `baseModel` since otherwise you also modify your base object (https://lodash.com/docs#merge).

**Comment by kaermorchen** [comment]
Article not found in GET /api/v1/articles, but it exist in DB.

With 

    _.merge(_.cloneDeep(likesBase), { 

began to work as it should
