### ISSUE TITLE
Multi module apps

### ISSUE THREAD

**Issue by messageboxstock** [balderdashy/sails#3092]
Is there smth like Symfony Bundles system http://symfony.com/doc/current/book/bundles.html in Sails ?

**Comment by justsml** [comment]
Not strictly a sails answer, however, I've tackled this 'componentization' pattern in the NodeJS/Browser lands with browserify.

If you need to generate a CJS/RequireJS/UMD bundle? try the `--standalone` option.
There are other interesting options like `--node` :+1:  useful when mixing tons of granular client and server modules.
