### ISSUE TITLE
Use RESTful routes, but not all of them?

### ISSUE THREAD

**Issue by mmiller42** [balderdashy/sails#3100]
I was wondering if it is possible to create a configuration for a controller that uses some of the RESTful routes, but not all of them. I don't want to turn off the REST routes because I like all the functionality of `find` and `findOne` (in terms of search criteria, sorting, etc.) and I don't want to copy that code; however, I have certain resources that are "readonly."

Right now, I have the REST routes enabled and am simply doing this in my controller:

```js
module.exports = {
	create: deny,
	update: deny,
	add: deny,
	populate: deny,
	remove: deny,
	destroy: deny
};

function deny (req, res) {
	res.notFound();
}
```

Is there a cleaner way to do this, i.e. perhaps something in the `_config` object of the controller? I see in the documentation/comments that it's simply a true/false, but I was wondering if it is able to interpret any other values. Otherwise, I'd like to suggest this as a feature enhancement -- something like : `_config.rest = [ 'find', 'findOne' ];`.

Thanks!

**Comment by Bazze** [comment]
Instead of setting your controller actions to a `deny` function, you should use policies to turn them off. In your `config/policies.js` file, do something like this:
```
module.exports.policies = {
    MyController: {
        create: false,
        update: false,
        add: false,
        populate: false,
        remove: false,
        destroy: false
    }
};
```

**Comment by mmiller42** [comment]
Much better solution. Thanks, appreciated!
