### ISSUE TITLE
I've got myself a question regarding associations in Sails.js version 0.11. I've been building an app in which multiple models are associated to one another, and I've arrived at a point where I need to get to nest associations somehow.

### ISSUE THREAD

**Issue by anil-codewave** [balderdashy/sails#3105]
hi all,

i am new to sails js. and i got a problem with deep associations in sails js using populate method.  I am using sails js with mongodb. I am trying since last 3 days but failed to achieve this. so I raised my question on stackoverflow. here is question: 

http://stackoverflow.com/questions/31562861/deep-associations-in-sails-mongo-using-populate-method/31575774#31575774

please help me with this.

thanks in advance.

**Comment by particlebanana** [comment]
It's not currently supported in Waterline - the ORM used by default in Sails. There is a proposed PR that could be included in the next version of Waterline, https://github.com/balderdashy/waterline/pull/1052 that you could try out if you like. Otherwise it will require multiple queries.
