### ISSUE TITLE
How to asset revisioning by using file content hashing?

### ISSUE THREAD

**Issue by fundon** [balderdashy/sails#3106]
https://www.npmjs.com/package/grunt-filerev

**Comment by fundon** [comment]
ping @particlebanana

**Comment by fundon** [comment]
ping @sgress454 Do you have the better solution?

**Comment by sgress454** [comment]
Hi @fundon.  I'm not sure what you're asking here--this forum is for reporting bugs in the Sails core.  You may have better luck in the [chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [Google Group](https://groups.google.com/forum/#!forum/sailsjs).

I haven't used the `grunt-filerev` package before, but it seems very popular, so I say give it a shot.  You can add new Grunt tasks to your project underneath the `tasks` folder.
