### ISSUE TITLE
Is there any way to access to unmodifiable tables in mysql?

### ISSUE THREAD

**Issue by FreCap** [balderdashy/sails#3107]
I have tables from a mysql source I can't modify because I have no rights, but I'd like to access, to them. Another example could be mysql views

**Comment by richdunajewski** [comment]
This might be better asked over at the sails-mysql adapter repo [here](https://github.com/balderdashy/sails-mysql). 

Off the top of my head, you should be able to read a table if you have read rights only, but make sure your model has `migrate: safe` to ensure Sails doesn't try to modify that table:
http://sailsjs.org/documentation/concepts/models-and-orm/model-settings

You could also run raw SQL queries by using the Model.query() method, which will allow you to access tables or views by "passing through" the ORM: http://sailsjs.org/documentation/reference/waterline-orm/models/query

**Comment by particlebanana** [comment]
If you can read from them then Waterline can execute find queries just fine. If you are having issues lifting Sails do as @richdunajewski said and set `migrate: 'safe'` so that it won't attempt to run any migrations.
