### ISSUE TITLE
Is it possible to connect sails to (pub/sub) broker?

### ISSUE THREAD

**Issue by iboumedien** [balderdashy/sails#3110]
Hi everybody,

I hope you are doing well. Is it possible to connect natively to broker (rabbitMQ, RedisMS ...etc) with sails. Or we have to develop it.

Best regards

Ismael

**Comment by jamesjwarren** [comment]
You can use rabbitMQ the same as in any Node.js app, using a library like http://www.squaremobius.net/rabbit.js/.

If instead you are referring to the existing sockets system in sails, you can configure an adaptor to use for the socket storage backend, like Redis for example, in `/config/sockets.js`.

**Comment by sgress454** [comment]
Thanks @jamesjwarren.

@iboumedien, thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core.  Support questions are more appropriate for our our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), our live [Gitter chat room](https://gitter.im/balderdashy/sails), or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js).  In fact, I answered nearly this exact question on StackOverflow [last year](http://stackoverflow.com/questions/25231657/rabbitmq-and-sails-js/25235481#25235481)!

**Comment by iboumedien** [comment]
@sgress454 @jamesjwarren Thanks booth your reponse.
