### ISSUE TITLE
with un sync query,what should i do like that??

### ISSUE THREAD

**Issue by hia** [balderdashy/sails#3112]
hi everyone 
i have a code like that:

```javascript
/**
            checkData={
                activityId:1,
                checkStates:[{
                    "gameServerId":1,
                    "checked":"true"
                },{
                    "gameServerId":2,
                    "checked":"false"
                }]
            }
        */
        var checkData = req.body;
        for (index in checkData["checkStates"]) {
            var serverCheck = checkData["checkStates"][index];
            var para = {
                "activityId": checkData.activityId,
                "gameServerId": serverCheck.gameServerId
            };
            ActivitySyncState.find(para).exec(function(err, records) {
                if (records.length > 0 && serverCheck.checked == "false") {
                    ActivitySyncState.destroy(para).exec(function(err) {});
                    ActivityRemoveState.find(para).exec(function(err, records) {
                        if (records.length == 0) {
                            ActivityRemoveState.create(para).exec(function(err, created) {});
                        };
                    });
                } else if (records.length == 0 && serverCheck.checked == "true") {
                    para["state"] = 0;
                    ActivitySyncState.create(para).exec(function(err, created) {});
                };
            });
        };
```
the callback function can`t called serverCheck data opportune because query is un sync,what shoud i do can fix this problem?

**Comment by sgress454** [comment]
Hi @hia, thanks for using Sails!  Just FYI, this forum is for reporting bugs in the Sails core.  If you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).   
<hr/>
In your case, your best bet is to replace your `for (index in checkData["checkStates"]) {` usage with a call to `async.each(checkData["checkStates"], ...)`, which allows you to loop through an array *asynchronously*.  See the [documentation for async.each](https://github.com/caolan/async#each) for more info.

**Comment by hia** [comment]
@sgress454  sorry about that,next time i will on ohter place~ 

and thaks you answer,i think i konw what should i do~~ 

very thaks~
