### ISSUE TITLE
errors are always on line 9

### ISSUE THREAD

**Issue by unsign3d** [balderdashy/sails#3113]
Every times I don't handle the error is always on line 9
```
Unhandled rejection TypeError: Cannot read property 'id' of undefined
    at null.<anonymous> (/data/api/controllers/v1-0/ListController.js:9:4269)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    [...]
```

I'm pretty sure that is not on line 9 because I don't have a line 9

```
/**
 * ListController
 *
 * @description :: Server-side logic for managing Lists
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */

'use strict';
// that's line 9 LOL
var errors = require('../../services/errors');

module.exports = {
  _config: {  // Disable default blueprint actions for this controller

```

**Comment by sgress454** [comment]
Hi @unsign3d, this isn't a Sails issue; those errors come straight from Node.  I would suggest turning off `use strict` and seeing if you get any better feedback.  Also make sure you're looking at the right file--looks like you may have more than one API version, in subfolders.
