### ISSUE TITLE
Get object after save

### ISSUE THREAD

**Issue by mhipo1364** [balderdashy/sails#3121]
Hi

I have a problem, I want to get object after save and work with it, how can I do that?

**Comment by Josebaseba** [comment]
You should read the docs: http://sailsjs.org/documentation/concepts/models-and-orm/lifecycle-callbacks

You can use the afterCreate method in your model.

**Comment by rhpwn** [comment]
```javascript
model.save(function(err, savedModel) {
  //work with savedModel;
});
```

**Comment by mhipo1364** [comment]
Really thanks guys
