### ISSUE TITLE
Policies are not applied to routes without a controller

### ISSUE THREAD

**Issue by slavafomin** [balderdashy/sails#3122]
Hello!

I've stumbled into a problem where global policy is not executed when route has no controller.

I wanted to augment all views of my application using a policy, like suggested here: http://stackoverflow.com/a/23118039/1056679, however policy wasn't working until I've created a controller for a route. I can see why it's not working, but I do think that this is a misleading behavior.

Probably "no controller" should be equal to an "empty controller". I think this is a serious matter, cause policies are security related.

**Comment by sgress454** [comment]
This is [pretty well documented](http://sailsjs.org/documentation/concepts/policies#?overview).  But you can apply a policy directly to a controller, using the [policy target syntax](http://sailsjs.org/documentation/concepts/routes/custom-routes#?policy-target-syntax).
