### ISSUE TITLE
sails: command not found

### ISSUE THREAD

**Issue by Fyb3roptik** [balderdashy/sails#3124]
I have uninstalled the brew version of node. Installed node via the pkg file for os x Yosemite. 

I have tried npm install sails -g as well as sudo. NEITHER WORK!

PLEASE FIX THIS!

**Comment by tjwebb** [comment]
This sounds like an issue with homebrew. `npm install -g sails` works the same way it always has.

**Comment by itranga** [comment]
I try to install sails.js in my mac 

Rangas-MacBook-Air:htdocs rangapathmasiri$ node -v
v6.10.1
Rangas-MacBook-Air:htdocs rangapathmasiri$ sails
-bash: sails: command not found
Rangas-MacBook-Air:htdocs rangapathmasiri$

**Comment by devmfouad** [comment]
same problem with me
