### ISSUE TITLE
modify an excel file (xlsx) with sailsjs

### ISSUE THREAD

**Issue by edohkodjo** [balderdashy/sails#3139]
i am trying to modify an excel file with sails js but until now i have not succeeded to do it. In fact what i want to do is to add content to an existing excel file. This is my code:

    var Excel = require("exceljs");
    var options = {
    filename: "./liste.xls", // existing filepath
    useStyles: false, // Default
    useSharedStrings: true // Default
    };
    var workbook = new Excel.stream.xlsx.WorkbookWriter(options);
    var sheet = workbook.addWorksheet("Product Build");
    var worksheet = workbook.getWorksheet("Product Build");
    worksheet.columns = [
      { header:"Id", key:"id", width:10 },
      { header:"Name", key:"name", width:32 },
      { header:"D.O.B.", key:"DOB", width:10 }
     ];

     worksheet.addRow({id: 1, name: "John Doe", dob: new Date(1970,1,1)});
     worksheet.addRow({id: 2, name: "Jane Doe", dob: new Date(1965,1,7)});
     worksheet.commit(); // Need to commit the changes to the worksheet

     workbook.commit(); // Finish the workbook
  
}

This code allows to create a new file with the sheet "Product Build" but me what i want is to overwrite an existing file "liste.xls" containing the sheet "liste.xls". Please, is there anyone who has an idea of how to solve my problem? Thanks in advance

**Comment by crh3675** [comment]
Where is this code? Controller? Service? Perhaps SailsJs is not the problem in your scenario as you are having an issue with the Excel NodeJs library, not Sails

**Comment by edohkodjo** [comment]
this is a controller server side.

**Comment by Josebaseba** [comment]
That's not an issue with Sails, you should try to ask for help in the exceljs repository.
