### ISSUE TITLE
How do you save multiple records in SailsJS in one action?

### ISSUE THREAD

**Issue by Solmen** [balderdashy/sails#3140]
I am wondering what the best practice would be for saving multiple records in an action that makes changes, particularly add and remove, to multiple records. The end goal is to have one function have access to all of the changed data in the action. Currently I am nesting the saves in order for the innermost saves to have access to the data in all the updated records. Here is an example of how I am saving:

    record1.save(function (error, firstRecord) {
      record2.save(function (erro, secondRecord) {
       record3.save(function (err, thirdRecord) {
        res.send({recordOne: firstRecord, recordTwo: secondRecord, recordThree: thirdRecord});
        });
      });
    });
With this structure of saving, recordOne, recordTwo, and recordThree display the expected values on the server. However, checking localhost/1337/modelName reveals that the models did not properly update and have incorrect data.

Here is a link to the [stackOverflow](http://stackoverflow.com/questions/31861944/how-do-you-save-multiple-records-in-sailsjs-in-one-action)

Thanks,
Solmen

**Comment by crh3675** [comment]
Use Async, Promises or lifecycle callbacks https://sailsjs-documentation.readthedocs.org/en/latest/concepts/Lifecyclecallbacks/

**Comment by Solmen** [comment]
Thanks for the response.  After looking at the documentation it looks like it doesn't actually deal directly with add or remove and therefore doesn't use saves.  As for promises, I tried using them as well but to no avail.  Below is an example code of my use of promises:

    var promiseOne = new Promise(function (resolve, reject) {
      thief.save(function (error, savedOne) {
        resolve(savedOne);
      });
    });

    var promiseTwo = new Promise(function (resolve, reject) {
      victim.save(function (error, savedTwo) {
        resolve(savedTwo);
      });
    });

    var promiseThree = new Promise(function (resolve, reject) {
      rune.save(function (error, savedThree) {
        resolve(savedThree);
      });
    });

    Promise.all([promiseOne, promisTwo, promiseThree])
      .then(function (values) {
    });

This makes the data that is received by the data and the server wrong but they match.  Is the issue the specific way that I am saving?

**Comment by Josebaseba** [comment]
```javascript
async.map([record1, record2, record3], function saveEachRecord(record, next){
   return record.save(next); 
}, function taskCompleted(err, results){
    if(err){
        sails.log.error(err);
        return res.serverError(err);
    }
    return res.ok({record1: results[0], ... });
});
```

If you have some kind of error you will see the error description in the log.
