### ISSUE TITLE
Action blueprints adding :id? param when they shouldn't

### ISSUE THREAD

**Issue by murhum1** [balderdashy/sails#3150]
Tried this in version v10.5, but the relevant pieces of code are also present in current master.

Bumped into this today where my Model.findOne() query failed to find results due to the added field. Basically in a policy of mine that is run on an action blueprint request, I've got something along the lines of:

    module.exports = function(req, res, next) {
        var params = req.allParams();    
        console.log(params);
        
        MyModel.findOne()
            .where(params)
            .exec(function(err, foundModel) {
                if (typeof foundModel === 'undefined') {
                    return res.view('404');
                }
                else {
                    return next();
                }
            });
        }
    };

Here the params included the field `id: undefined`, which was not sent from my frontend or any policies of mine. This caused the query to return no results and to return the 404 view.

I started digging around the sails source, and found this from ` sails/lib/hooks/request/params.all.js`:

    ////////////////////////////////////////////////////////////////////
    // The check below is deprecatable since action blueprints
    // will no longer automatically receive the :id? param in their route.
    //
    // // Make sure `id` is omitted if it's undefined
    // // (since action blueprint routes name an optional :id)
    // if (typeof req.param('id') === 'undefined') {
    //    delete req.params.id;
    // }
    //////////////////////////////////////////////////////////////////

However, I then found this in ` sails/lib/hooks/blueprints/index.js` (line 260 in current master):

    // Bind a route based on the action name, if `actions` shadows enabled
    if (config.actions) {
        var actionRoute = baseRoute + '/' + actionId.toLowerCase() + '/:id?';
        sails.log.silly('Binding action ('+actionId.toLowerCase()+') blueprint/shadow route for controller:',controllerId);
        sails.router.bind(actionRoute, controller[actionId.toLowerCase()], null, opts);
    }

with `var actionRoute = baseRoute + '/' + actionId.toLowerCase() + '/:id?';` being the important part. 

Apparently the `:id?` param is still being added despite the other file claiming it's not. Both uncommenting the part in `params.all.js` and removing the ` + '/:id?'` from `index.js` caused my original query to work and the `id:undefined` to disappear.

Do what you will with this info, but I'd at least love the comment not to contradict other code causing unnecessary frustration :p

**Comment by mikermcneil** [comment]
@murhum1 The code comment about the :id param being removed from action blueprints is leftover from when we were going to remove that back in 0.9 for the sake of simplicity (unfortunately, it caused issues for folks who were relying on it, and based on the feedback from the community we decided to keep it indefinitely).  Thanks for the heads up!  I'll clean that out.

**Comment by mikermcneil** [comment]
@murhum1 and either your query should really work :/  But I think the right way to do it is by laying off all the hasOwnProperty checks in Waterline criteria dictionaries.  I've spent more hours than I'd care to admit working on this recently in the [`rttc`](https://github.com/node-machine/rttc) project, and learned that the most consistent way to handle things for both users and implementors is for `{}` and `{ foo: undefined, bar: undefined, baz: undefined }` to be equivalent.

cc @particlebanana 



P.S @murhum1 in case it's helpful, you can use `require('rttc').dehydrate(req.allParams())` to take care of this in the mean time (docs: https://github.com/node-machine/rttc#dehydratevalue-allownullfalse-dontstringifyfunctionsfalse)

**Comment by mikermcneil** [comment]
@murhum1 https://github.com/balderdashy/sails/commit/0d52ac01d19c692a551ba05ad8ba0dad1b0cea64
