### ISSUE TITLE
How can I update the async node module in sails?

### ISSUE THREAD

**Issue by cage1618** [balderdashy/sails#3153]
Sailsjs use async with v0.9.2, But the newest version of async add some new method such as forEachof and so on. This is a very useful method for me, so how can I update it to the newest version? 

thanks!

**Comment by tjwebb** [comment]
If you'd like to use a different version of `async` in your Sails application, you can install async in your project and require() it, and disable it in config/globals.js

**Comment by mikermcneil** [comment]
> If you'd like to use a different version of async in your Sails application, you can install async in your project and require() it, and disable it in config/globals.js

:+1: couldn't agree more 

```bash
npm install async --save
```

```js
foo: function (req, res) {
  var async = require('async');
  // ...
}
```


@cage1618 and if you're very fond of the automatic `async` globalization, follow TJ's instructions and then globalize your own version of `async` in your `config/bootstrap.js` file.

**Comment by mikermcneil** [comment]
@cage1618 good luck :)
