### ISSUE TITLE
Cannot use lodash in console

### ISSUE THREAD

**Issue by LitleCarl** [balderdashy/sails#3156]
Sails version:0.11.0
Node version:0.12.7
When I enter console mode with command: sails console.
console.log(_ ) // output:{ [Function: lodash]...}
console.log(_ ) // This time output: undefined
which is strange,can anybody tell what's the problem?

**Comment by Josebaseba** [comment]
Take a look: https://github.com/balderdashy/sails/issues/1811 

_ is reserved in console, it's not a bug related with Sails

**Comment by tjwebb** [comment]
Interesting @Josebaseba, thanks for the info.
