### ISSUE TITLE
route to assets/index.html for React-Router

### ISSUE THREAD

**Issue by joshbedo** [balderdashy/sails#3158]
I'm trying to setup React-Router in a SailsJS project but can't seem to figure out how to point a route to `assets/index.html`. I was hoping someone would know how i can make that happen :)

**Comment by Josebaseba** [comment]
Take a look here: http://sailsjs.org/documentation/concepts/assets

**Comment by jeffjewiss** [comment]
Hey Josh, by default the assets get served with full paths, so it's likely accessible at `localhost:1337/index.html` in a dev environment.

However, it sounds like using a view would work best for your case. If you move your `index.html` file to the `views` directory and change the extension to `ejs` (if you're using the default template setup) you should be able to then use a route.

You can either set it up as a view in your `config/routes.js`:
```
{
  'get /': {
    view: 'index'
  }
}
```

or if you need to do something in a controller first, you could setup the route like this:

```
{
  'get /': {
    controller: 'AppController',
    action: 'index'
  }
}
```

and have your `AppController render the view:

```
module.exports = {
  index: function (req, res) {
    return res.view();
  }
}
```

**Comment by joshbedo** [comment]
Awesome i'll give this a shot.

**Comment by tjwebb** [comment]
@joshbedo any updates here?

**Comment by sgress454** [comment]
Hey all, closing this as it's not related to a bug in Sails core.  Thanks for working it through!  @joshbedo in the future don't hesitate to direct support requests to our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [StackOverflow](http://stackoverflow.com).
