### ISSUE TITLE
Hbase

### ISSUE THREAD

**Issue by jimmyjamieson** [balderdashy/sails#3161]
I'm looking into hadoop hbase, and wondering if anyone has info on connecting it with sails. 
Ideally I need the ORM to slow migrate from mysql to hbase over several months.

**Comment by tjwebb** [comment]
@jimmyjamieson the best way to integrate hbase with sails would be to build a Waterline Adapter. More info on how to do that is here: http://sailsjs.org/documentation/concepts/extending-sails/adapters

The core team hasn't built an hbase adapter yet, but I would ask around the community to see if anyone is interested in helping you out. Our gitter room is also a great way to discuss this type of thing: https://gitter.im/balderdashy/sails

**Comment by jimmyjamieson** [comment]
Thanksfor the reply, my best guess was an adapter. I'll have to spend some more time with hbase/waterline and see what I can come up with. I see there's already a Cassandra adapter, so hbase would definitely be worth pursuing.

**Comment by tjwebb** [comment]
@jimmyjamieson awesome, if you end up building something let us know and we'll link to it.
