### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by kennysmoothx** [balderdashy/sails#3164]
So I had an existing project I converted from Sails 0.10 to 0.11 which has been on production and everything was **perfect**.

I recoded this project from a fresh configuration on sails 0.11 and I pushed this up to production today and I am coming across a memory leak (600mb +).

My sails application uses Sockets HEAVILY.. no less than 100-200 active connections at any given moment and my application's memory jumped to 550MB range within 5 minutes. Then trickles on upwards at about 6-10mb/minute...

I believe this is caused by Sockets due to the nature of how fast the memory shoots up to that range (Sockets reconnecting back with sails may be causing this memory to increase).

I use Redis for my Sessions however not for Sockets... Any idea where my memory leak can be coming from? Maybe I forgot to configure some aspect of the Sails App?

Any help is appreciated.

**UPDATE:**

Going over my router logs there is a significant number of "Polling" requests taking upward of 25+ seconds to respond, some of which cause heroku timeouts (those that take longer than 30s).

```
heroku[router]: at=info method=GET path="/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1440016503005-19337&sid=Lpzc6wgYY9yGFMPlAAIA"
host=OMITTED request_id=d725d339-5d64-4ee4-8a27-99ed08132d0f 
fwd="OMITTED" dyno=web.1 
connect=0ms service=25048ms status=200 bytes=207
```

Will continue investigating..

Might be related to #3099 even without cluster mode.

**Comment by mikermcneil** [comment]
We've seen something a lot like this on sailsjs.org. Thanks so much for posting- looking forward to hearing more. Will take a closer look in the meantime. Afaik performance is otherwise unaffected, but please let us know ASAP if you have a different experience.

**Comment by sgress454** [comment]
If you're using sockets on Heroku, you are doing clustering, unless it's on a single dyno.  You should turn off polling as a transport.  See http://sailsjs.org/documentation/concepts/deployment/scaling#?configuring-your-app-for-a-clustered-deployment.

**Comment by sgress454** [comment]
Also, try installing the latest version of sails-hook-sockets in your Sails installation!  If you've installed it globally, `sudo npm update -g sails` should do it.

**Comment by kennysmoothx** [comment]
@sgress454 I do currently only have a single dyno, thank you for the link!

I have disabled transport both on my server and on my client code.

I have also added `socket.io-redis` adapter to my sockets configuration.

At the moment because of the disabling of polling on my server, it is currently still experiencing about 4k 404 requests per minute so I'll need to wait a few hours before I can get more accurate readings however the general trend of increasing memory still seems to be there...

**Comment by kennysmoothx** [comment]
So the memory leak has been persistant and it makes it's way passed 1GB. I took a series of Heapdump and different times of the day and they all have a single glaring similarity:

![image](https://cloud.githubusercontent.com/assets/6720728/9510113/01802946-4c36-11e5-920b-3d91af15dbd2.png)


![image](https://cloud.githubusercontent.com/assets/6720728/9510117/1747989a-4c36-11e5-92fb-9a0da8739c25.png)


Now I have a really hard time reading heap dumps so if there is any more information you need from this please feel free to ask! I can post back with any more information.

Also 'Featured' is a sails model I have. It really is only referenced twice in my code and there are only two queries and there is nothing out of the norm about them.

**Comment by AlejandroJL** [comment]
Hi, in my case are having the same problem in sails 0.11. Us for now happens in a single instance. Any idea to solve this temporarily?

**Comment by kennysmoothx** [comment]
Okay I have some updates! I have been analyzing heap dumps for the past 2 weeks believe I found what the memory leak is doing. Now please bare with me as I explain what is happening in these heap dumps:

Doing a comparison of two heap dumps (taken 10 minutes apart) one at 450mb of memory (referenced as heap_1) the other roughly at 900mb (referenced as heap 2):

Heap 1:
![image](https://cloud.githubusercontent.com/assets/6720728/9568801/44f756fa-4f23-11e5-90a7-bfdc9c65016c.png)


Heap 2:
![image](https://cloud.githubusercontent.com/assets/6720728/9568803/4a7459ac-4f23-11e5-8767-6cb94aee1528.png)

So starting with this Array, we see this has doubled in size!! So lets take a look at whats inside step by step:

![image](https://cloud.githubusercontent.com/assets/6720728/9568812/c7eb4620-4f23-11e5-8110-91e5fd0d5e5a.png)

![image](https://cloud.githubusercontent.com/assets/6720728/9568814/d6475fc4-4f23-11e5-984d-a1e4be0fc5d3.png)

Each of these `_` have what appears to be the same thing inside:

![image](https://cloud.githubusercontent.com/assets/6720728/9568815/e007945c-4f23-11e5-98cc-39c8964f9033.png)

Okay now all these [0] objects we see here at all of my models! Let take a look inside of one of them:

![image](https://cloud.githubusercontent.com/assets/6720728/9568822/42940c18-4f24-11e5-83cb-05182124e556.png)

This is my `Featured` model and it appears to be copied over and over and over and over......:

![image](https://cloud.githubusercontent.com/assets/6720728/9568835/9b5d5322-4f24-11e5-8d9d-82764da66d4b.png)

![image](https://cloud.githubusercontent.com/assets/6720728/9568848/21dfe89c-4f25-11e5-832b-d6948875550d.png)

![image](https://cloud.githubusercontent.com/assets/6720728/9568856/4b85e50c-4f25-11e5-832b-b5f9238f6bc1.png)


These [4]'s carry on about 600 times per model..... and each '_' we saw before has all of my models with 600 references to themselves with [4]'s as well...

I believe this is the root cause of the memory leak...

Now to be quite frank I suck at reading heap dumps so I'm not entirely sure the significance of this or what may be causing this but I'm open to work through it! 

Please let me know what other information may be of help...

@sgress454 @mikermcneil

**Comment by AlejandroJL** [comment]
Thanks @kennysmoothx! For my part, if I can help in any tell me.

**Comment by kennysmoothx** [comment]
Like I said I'm still not entirely sure if that is indeed what's causing the link however each [4] in those heapdumps are actually waterlines dynamicfinders (eg. `findByCreatedAt`).

Possibly something we can look at.

**Comment by AlejandroJL** [comment]
Hello @kennysmoothx In my case using mongoldb (sails-mongo). In your case use mongodb?

**Comment by AlejandroJL** [comment]
Hello again @kennysmoothx . What are you using to get the heap dumps? Thanks!

**Comment by AlejandroJL** [comment]
I'm watching the status of the RAM in our instance to Heroku. In these tests there is no device connected to the backend (socket).
![captura de pantalla 2015-09-01 a las 12 43 49](https://cloud.githubusercontent.com/assets/14291/9602252/3054eb88-50a7-11e5-8d77-81da27905cfc.png)

**Comment by kennysmoothx** [comment]
Hello @AlejandroJL the heap dumps I get are using 

https://github.com/Factr/node-offworld-heapdumper

Basically I have an Amazon S3, and I created an endpoint on sails so when I hit the end point it creates a heapdump and puts it on my S3 server. Then I download the .heapdump file and open it using node-inspector

https://github.com/node-inspector/node-inspector

**Comment by particlebanana** [comment]
@kennysmoothx a good test would be to create a control with no models and see what you get. I've spent some time tracking it down and my guess was it's something in the web sockets interpreter but like you I don't really have the best idea of how to read heapdumps.

**Comment by sgress454** [comment]
You can also try rolling back `sails-hook-sockets` in case it's something to do with connecting to the new message bus.  In your project folder, just do:

`npm install sails-hook-sockets@0.11.21`

The local hook will override the default one used by Sails.

**Comment by kennysmoothx** [comment]
Hey @sgress454 just following up with you, I rolled backed sails-hook-sockets as you suggested and unfortunetaly I see no difference..

I've reduced the amount of requests made to the server significantly, so the memory leak has slowed down, but the memory is not freed and it increases over time.

**Comment by AlejandroJL** [comment]
Hey @kennysmoothx look this: https://github.com/balderdashy/sails/issues/3099#issuecomment-139594709

**Comment by particlebanana** [comment]
@kennysmoothx tried the same app on node `0.10.x` and `0.12.x`. Worked fine on `0.10.x` but leaked memory on `0.12.x`. Haven't tried with any iojs releases or node 4.0 yet. So that's something we need to dig deeper into.

**Comment by sgress454** [comment]
Hey all, closing this in favor of the continued discussion at #3099.  Thanks for everyone's work on this.

**Comment by mikermcneil** [comment]
For future reference, I wrote an update with more info and tips here:
https://github.com/balderdashy/sails/issues/3782#issuecomment-238679052
