### ISSUE TITLE
Using Services - Best practices 

### ISSUE THREAD

**Issue by Geocloud** [balderdashy/sails#3169]
Hi team, 

I have a background service and in my service, i insert a record in database. 
The Service used one thread, right or not ?
The service used a Global Database connection or not ? 
If i run the service 1000 times, do i have a time out or not ?

Thank you

**Comment by Geocloud** [comment]
I found a solution :)

**Comment by tjwebb** [comment]
@Geocloud would you mind sharing the answers to your questions?
