### ISSUE TITLE
Example for one-to-one association is incorrect

### ISSUE THREAD

**Issue by pcguru** [balderdashy/sails#3172]
https://github.com/balderdashy/waterline-docs/blob/master/models/associations/one-to-one.md

"This will add a key to each model returned that contains an object with the corresponding record. Because we set the association on both sides above you could use populate on either side."

That is not true. You can only use populate from the model that holds the foreign key. The example does not work when run.

See: http://stackoverflow.com/a/27752329/129808 for more information on the Waterline missing feature.

**Comment by particlebanana** [comment]
@pcguru the example in the docs is correct. After setting one side of the association the other side is set in the callback so both sides have a foreign key that can be populated.

The wording may be a bit confusing though.

```javascript
Pet.create({
  breed: 'labrador',
  type: 'dog',
  name: 'fido',

  // Set the User's Primary Key to associate the Pet with the User.
  user: 123
})
.exec(function(err, pet) {
  if(err) // Handle Error

  // Here the other side of the association is set
  User.update(123, { pet: pet.id }).exec(function(err, user) {});

});
```

**Comment by pcguru** [comment]
A yeah, that trick is below the text that says "Now that both models know about each other you can query the association from both sides" which is only true if you populate the key on both sides, that's why I stumbled on this.
