### ISSUE TITLE
findOne filtering

### ISSUE THREAD

**Issue by Hanifb** [balderdashy/sails#3174]
So the `req.options.where` and `req.options.values`, are a gift for restricting access to data by policy, for example, i can restrict **update**, **create** and **find** to objects that are created by the user. 

But **findOne** only looks for a primary key, therefore restriction by policy becomes much harder and custom blueprints/controllers must be created.

This problem is easily corrected by adding a `.where( actionUtil.parseCriteria(req) )` in the default blueprint of the findOne action.

**Comment by Hanifb** [comment]
You can of course override the default blueprint, but it seems wierd that findOne should not feature this easy and versatile option.

**Comment by sgress454** [comment]
@Hanifb Seems like a good idea.  Please check out the new policy for features below--if you add this feature to the Roadmap in a PR I'll merge it!
<hr/>
The issue queue in this repo is for verified bugs with documented features only, please; no feature requests, questions, or commentary-- and also no bug reports about undocumented features or unofficial plugins. Please review [our contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#requesting-features) for our process for feature requests and questions.  In the future for support requests please visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Thanks so much for your help!
