### ISSUE TITLE
Update from Express3 to Express4

### ISSUE THREAD

**Issue by Josebaseba** [balderdashy/sails#3175]
Hi guys,

```

Express 3.x support is ending soon

This series will continue to receive only security updates and bug fixes until July 2015. It is highly recommended to upgrade to Express 4.x.
```

So, I've tried to update by myself the dependency, you can take a look: https://github.com/Josebaseba/sails

Almost all the test are passing, just four of the CORS tests are giving me some problems and the layouts aren't working yet (don't know why, the test are passing).

All the Connect dependencies are gone, I've added Express packages to replace them: ```express-session, csurf, cookie-parser``` and ```compression.```

But the biggest changes are related to the Router, to both of them (the internal and the external), in express4 the Router works pretty different. 

More info: https://github.com/strongloop/express/wiki/Migrating-from-3.x-to-4.x and http://expressjs.com/4x/api.html#router

Before following working in that way I think that I need some light or help, am I following the correct path? Should I open a Pull Request or something?

Any kind of help is welcome!

**Comment by Aweary** [comment]
A lot of the utilities within Express are being broken out into (or implemented in) modules under [pillarjs](https://github.com/pillarjs), such as the router. If Sails is only utilizing parts of Express it should really just implement these modules directly.

**Comment by listepo** [comment]
+1, I began to migrate but I need help with a router https://github.com/listepo/sails/blob/next/lib/router/index.js#L219

**Comment by Josebaseba** [comment]
@listepo I've all the router changes working: https://github.com/Josebaseba/sails/blob/master/lib/router/index.js#L48

I'm looking for some help with the res.view layouts and few tests with the CORS to finish the migration.

**Comment by listepo** [comment]
@Josebaseba, I try to help.

**Comment by listepo** [comment]
@Josebaseba, can get specific examples that not work?

**Comment by Josebaseba** [comment]
Sure!

Related with the CORS the test are passing here: https://github.com/Josebaseba/sails/blob/master/test/integration/hook.cors_csrf.test.js#L74

The lines that don't work are commented (the first five tests), the problem is that I'm getting a 404 instead of a 200, but all the headers are perfectly. I spend a lot of time trying to find the reason but with no luck.

And the other problem is that the layout is no been injected when you call to the res.view method. In this case I haven't spend so much time trying to fix it. Looking at this comment it looks like the already have this problem updating to express3 newer versions: https://github.com/Josebaseba/sails/blob/master/lib/hooks/views/res.view.js#L330

In this case all the test are passing but if you use this repository in a Sails project you will see that the layout is not being used.

Thanks for you help!!

**Comment by vinyll** [comment]
+1.
I guess express3 beeing abandoned is good enough to justify an upgrade.
I'm not sure right now wether to start projects with sails as it gets highly based on an outdated core.

**Comment by tjwebb** [comment]
hey @listepo, sorry it took me so long to get to this. We really appreciate the work you're doing. What can I do to help you?

**Comment by listepo** [comment]
@tjwebb, thanks. On the weekend, I want to debug the code and trace with Spy-js(Webstorm). Any news about the Sails.js v1? The new version is based on code from the master or written anew? I want to understand that the time for refactoring and tests will be time well spent.

**Comment by Josebaseba** [comment]
Hey @listepo did you see my repo with the express update? What do you think, did you see any problem?

And @tjwebb, do you think that I should keep working to fix the last problems (the few CORS tests and res.view layouts problem) or you've planned another thing to the sails migration and I shouldn't expend more time on this? 

Actually I've a really good time working on this update, I learn a lot, and I don't have any problem if you think that it's not the best way to update the dependency. I'll keep the fork there, just if someone wants to look something. 

In the other hand, if you think that it can work, I'll be happy to explain in detail all the changes that I made, and what are missing to end the update.

Thanks guys!

**Comment by listepo** [comment]
@Josebaseba, I did not see the error, but I think it is worth trying to change the code to work with the cors on https://github.com/expressjs/cors.

**Comment by listepo** [comment]
@Josebaseba , It did not work to resolve quickly. Maybe we should do the PR has not been lost to work?

**Comment by Josebaseba** [comment]
@listepo this week I've a lot of work to do, but my intention is setting the repo up to date to new commits, after that I'll create a pull request trying to explain point by point al the changes.

**Comment by listepo** [comment]
:+1:

**Comment by Josebaseba** [comment]
I've done the pull request: https://github.com/balderdashy/sails/pull/3235

So I'm going to close this issue. Thanks!

**Comment by mikermcneil** [comment]
> A lot of the utilities within Express are being broken out into (or implemented in) modules under pillarjs, such as the router. If Sails is only utilizing parts of Express it should really just implement these modules directly.

That's the plan- some of the first steps are detailed in ROADMAP.md.
