### ISSUE TITLE
sails fails with npm3 flatten deps

### ISSUE THREAD

**Issue by valery-barysok** [balderdashy/sails#3176]
due to flatten dependencies sails fails to lift application. It can be easily fixed by replacing `express/node_modules/connect` with just `connect` in two places. but I do not know if it is right solution.

```js
[32minfo: [39m[90mStarting app...[39m

module.js:338
    throw err;
          ^
Error: Cannot find module 'express/node_modules/connect'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (...\node_modules\sails\lib\hooks\session\index.js:25:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at ...\node_modules\sails\lib\app\configuration\index.js:63:34
    at ...\node_modules\sails\node_modules\lodash\dist\lodash.js:3741:15
    at forOwn (...\node_modules\sails\node_modules\lodash\dist\lodash.js:2106:15)
    at Function.reduce (...\node_modules\sails\node_modules\lodash\dist\lodash.js:3738:9)
    at Configuration.defaultConfig (...\node_modules\sails\lib\app\configuration\index.js:58:18)
```

**Comment by amyspark** [comment]
I got the same error, as a workaround please go to the `express` folder in `node_modules` and run `node install` there.

**Comment by Alaneor** [comment]
Just FYI - npm 3 is now marked as *latest*, meaning it is out of beta. People who use Sails.js and upgrade npm **will break** their deps. Perhaps a patch release for 0.11 would save the day?

Also see the npm 3 announcement [here](http://blog.npmjs.org/post/129378362260/npm-weekly-29-npm-3-out-of-beta-nick-out-of-the).

I tried to disable the hooks which use the offending statement (session, csrf), but it seems they are loaded even though they are not used.

**Comment by tjwebb** [comment]
> People who use Sails.js and upgrade npm will break their deps

Is this issue caused merely by using npm 3?

**Comment by Alaneor** [comment]
They need to install their dependencies using npm 3. That would cause the deps to be flattened and the modules mentioned previously will simply not be at the specified path.

**Comment by adambiggs** [comment]
Can confirm Sails is broken when installing with NPM v3.3.3

**Comment by shaunstanislaus** [comment]
yup sails is broken with NPM V3.3.3

**Comment by shaunstanislaus** [comment]
@amyspark when you do sails new myapp, it does not install express module FYI.

so how do you even begin with going toe express folder and into the node_modules to do 

```bash
$ node install
``l`

**Comment by amyspark** [comment]
@shaunstanislaus npm 3 flattens dependencies, that's why it ends up on `node_modules`.

**Comment by adambiggs** [comment]
The main issue seems to be that sails `require()`s nested dependencies from within it's own dependency's `node_modules` (which no longer exist in that location as of NPM v3).

I found [this line](https://github.com/balderdashy/sails/blob/f84ad6b579148a9b18cf4703b97b6207394a9370/lib/hooks/csrf/index.js#L80) but I'm not sure if there's more.

**Comment by sgress454** [comment]
The lines causing the issue are documented well by @amyspark above.  Testing out a patch now.

**Comment by adambiggs** [comment]
Oh ya I  missed that.

**Comment by sgress454** [comment]
Ok, I've patched this on the [stable branch](https://github.com/balderdashy/sails/tree/stable), if someone wants to pull that and verify with their NPM install I'd appreciate it!

**Comment by Alaneor** [comment]
Confirmed working. Steps taken to verify:

1. Upgrade to npm 3: `npm i -g npm@latest`
1. Create a new app in new directory: `sails new testapp`
1. Delete *node_modules* folder and change `sails` target in *package.json* to: `github:balderdashy/sails#stable`
1. Install deps: `npm i`
1. Generate a new API, just for fun: `sails generate api user`
1. Run the app: `node app.js`
1. Visit homepage, visit */user* endpoint

No crashes.

**Comment by sgress454** [comment]
@Alaneor thanks--to be double sure, try turning on CSRF support in `config/csrf.js` before hitting the `/user` endpoint...

**Comment by Alaneor** [comment]
Still good!

I only did this, hope it's enough to enable csrf:

```js
// config/csrf.js
module.exports.csrf = true
```

**Comment by sgress454** [comment]
Yup, that'll do.  Thanks again!

**Comment by sgress454** [comment]
Ok, thanks everyone.  Published patch with Sails v0.11.2.  Also includes patch to make it work w/ Node 4.

**Comment by valery-barysok** [comment]
@sgress454, can you do the same for 
```
    "sails": "0.12.0-rc3",
```
?

**Comment by faustor21** [comment]
@valery-barysok in the case of **sails 0.12.0-rc3** all I did was go **express** *folder* inside the **node_modules** directory and did a
```
$ node install
```

Now it's working fine so far.

**Comment by shaunc** [comment]
+1 for patch in 0.12.0-rc3 (which btw is otherwise working fine for me). The workaround works (npm install in express) but clean install would be nicer. :)

**Comment by mkeremguc** [comment]
+1 for 0.12.0-rc3 as it breaks the CI and deployment flow atm

**Comment by ArekSredzki** [comment]
+1 for 0.12.0-rc3

**Comment by sgress454** [comment]
Understood, working on it now.  FYI there has been a _lot_ of merging into Sails since rc3, so I'll likely just cherry patch these changes onto the rc3 tag for rc4--it won't have many other updates, if any.

**Comment by sgress454** [comment]
Ok!  v0.12.0-rc4 is out.  As stated above, it is pretty much exactly rc3, plus the changes necessary to get it to work w/ NPM 3+ and Node 4+.

**Comment by irobayna** [comment]
@sgress454 Thank you!
