### ISSUE TITLE
Asynchronous config values

### ISSUE THREAD

**Issue by evansolomon** [balderdashy/sails#3178]
Is there a preferred (or at least possible) way to populate configuration values asynchronously? I was hoping to be able to do this in config/boostrap, but it looks like before the bootstrap file runs Sails expects the database connection config to be available.

My particular use case is that some of my app's configuration data is encrypted, and the decryption is an asynchronous process. Ideally I'd be able to setup my data before anything internal to Sails expects to be ready.

An alternative solution would be to handle this setup in the host environment/start script and provide the data as environment variables, but if possible I think it would be simpler/better to do it within the app.

Is this possible within Sails?

**Comment by evansolomon** [comment]
I also tried using hooks to solve this, but I ran into the problem where another hook (orm) is trying to access the configuration data in parallel. There is `sails.after` to allow hooks to wait for other hooks. I tried to find something like `sails.before` to force other hooks to wait for mine, but it looks like that doesn't exist.

**Comment by evansolomon** [comment]
For now I've modified the app.js file that sails generated to load my configs before calling sails.lift, then pass the result into `rc`. This seems to work well enough. I'll leave this open in case there is a better idea. Feel free to close this issue if that is actually the best way to do it.

**Comment by evansolomon** [comment]
For now I'm modifying the app.js file that sails generated to load my config and pass it into sails.lift().

**Comment by sgress454** [comment]
@evansolomon Great question.  At the moment the answer is no, Sails doesn't support asynchronous configuration, so your workaround is the best solution.  Definitely something we'll keep in mind.  Thanks for using Sails!

**Comment by evansolomon** [comment]
Okay, thanks for letting me know. Would definitely be a nice thing to support eventually, even some kind of reallyBeforeEverythingEvenDatabaseConnectionsYoureOnYourOwnWildWest place to hook into the app starting process would probably get most of the job done.
