### ISSUE TITLE
I can't create more than 63 Socket connections from a single device for testing.

### ISSUE THREAD

**Issue by AlejandroJL** [balderdashy/sails#3179]
Hello everyone!

I'm trying to perform some tests to try redis behaviors to simulate a 8,000 - 15,000 connections using socket.io. But I can not with *sails.js 0.11*.

Currently using *nodejs 0.12.7* and I've seen that since *0.12.0* by default to *agent.maxSockets* is 'Infinity'.

If I think an example with express 4 and socket.io don't have any problem to create over 7,000 sockets.

Does anyone know what may be happening?

Thanks a lot!

**Comment by Josebaseba** [comment]
Can you upload your app/tests to Github or somewhere? I don't know the reason but maybe if I see the app and the tests I can help you to find the reason...

What is the error that is throwing the app?

**Comment by AlejandroJL** [comment]
Hello @Josebaseba!

Thank you for answering.

Watch the test is simple. You create a new project with Sails and in my case I can not exceed 63 sockets from a computer.

But if I think a simple application with Express 4 and socket.io have no problems. Some security setting or something I understand there will be by sailsjs. But I don't know.

**Comment by Josebaseba** [comment]
But to connect the 63 sockets are you using some kind of script or something?

**Comment by AlejandroJL** [comment]
Yes. In my case, I've created a simple app for OS X using the Socket.io client for iOS/OS X.

https://github.com/socketio/socket.io-client-swift

**Comment by AlejandroJL** [comment]
Hello @Josebaseba is it possible that there is a setting to prevent DDOS attacks?

can you disable temporarily for testing?

Thanks!

**Comment by mikermcneil** [comment]
@AlejandroJL sounds like this is the ole connection limit issue on the client.  Have a look at: https://github.com/socketio/socket.io/issues/1393#issuecomment-32442188   :)

If that works for you, I'd really appreciate it if you could send a PR to https://github.com/balderdashy/sails-docs/blob/master/FAQ.md with your question and answer.
