### ISSUE TITLE
socketio request, req.logIn is not a function when using passport

### ISSUE THREAD

**Issue by yesvods** [balderdashy/sails#3189]
It seems that there have been lots of tops about this issus. There are some tricks fit for v0.10 version. 
https://github.com/kasperisager/sails-generate-auth/issues/11#issuecomment-49125634
http://stackoverflow.com/questions/17365444/sails-js-passport-js-authentication-through-websockets

Howerver, the tricks didn't work anymore in v0.11.Is there anybody encounter this problem in v0.11?

```
process: function(req, res){        
    passport.authenticate('local', function(err, user, info) {
      if ((err) || (!user)) {
        return res.send({
        message: 'login failed'
        });
        res.send(err);
      }
      
      req.logIn(user, function(err) {
        if (err) res.send(err);
        return res.send({
          message: 'login successful'
        });
      });
    })(req, res);
  }
```

**Comment by lalarsson** [comment]
I've got a similar problem. I've got the snippet above (with some additional modifications) to work but the session will not stick to the socket (req.session.passport is not defined). I can see the session in the req.sessionStore but I'm unable to access it...

Would greatly appreciate help with this! I really don't want to downgrade sails to be able to use authenticated sockets...

**Comment by tjwebb** [comment]
FWIW, [sails-auth](https://github.com/tjwebb/sails-auth) is tested working with socket.io.

Also note that sails-generate-auth is no longer maintained:
>  OBS: This generator is not currently actively maintained as I simply do not have the time. I'd be more than happy to add willing bodies as collaborators though!

**Comment by mikermcneil** [comment]
In case it's helpful:

+ Some explanation of the challenges of using passport here: https://github.com/sails101/using-passport
+ Much simpler tutorial of how to build login without passport: https://github.com/sails101/basic-login

Closing this issue to keep tidy.  Please feel free to pick up this discussion on StackOverflow, IRC, Gitter, or the Google Group.  Thanks guys.

**Comment by Juliaandavid** [comment]
Hi @mikermcneil, after more than 2 years ago this is not solve, after all this time you have some guide to follow to integrate Sails.io.js with Passport? I am ashamed to write you in this issue but I'm seriously desperate with this.

Hope you answer and help me.
Regards.
