### ISSUE TITLE
Where criteria in blueprints

### ISSUE THREAD

**Issue by mhipo1364** [balderdashy/sails#3190]
Hi

I need some help, I want to send where param using url in `find` blueprint. I have this condition:

```javascript
where: {
    or: [
        {verified:1},
        {verified:-1},
        {verified:0},
    ]
{
```

I mean, I wanna get objects which have verified with 0, -1 , 1 value. 

How can I send it?

**Comment by particlebanana** [comment]
`{ verified: [1, -1, 0] }`

**Comment by mhipo1364** [comment]
@particlebanana : Works like a charm. Thanks pal :+1:
