### ISSUE TITLE
More than 2 environnements

### ISSUE THREAD

**Issue by jaumard** [balderdashy/sails#3193]
Hi,

I want to add more of 2 environnements on a sails project. As I see it's not possible cause of sails.hook.grunt who do this : 

```
initialize: function (cb) {

      sails.log.verbose('Loading app Gruntfile...');

      // Start task depending on environment
      if(sails.config.environment === 'production'){
        return this.runTask('prod', cb);
      }

      this.runTask('default', cb);
    },
```
And sails who use this : 
https://github.com/balderdashy/sails/blob/a210b48667708bea687dd5ec61ce9e07ffc0c005/lib/app/configuration/load.js#L73

It would be nice to remove --prod parameter (or keep it for compatibility) and add --env=production (or another env) instead.
And for sails.hook.grunt to change it to : 
```
initialize: function (cb) {

      sails.log.verbose('Loading app Gruntfile...');

      // Start task depending on environment
      if(sails.config.environment != 'development'){
        return this.runTask(sails.config.environment, cb);
      }

      this.runTask('default', cb);
    },
```
prod.js task have to be rename in production.js but like this we can add environnement easily and add custom config file in config/env.
Also we can check if there a task name like sails.config.environment to be sure and if it's not run default one.

What do you think ? Is there another thing to do ? 
Maybe I can find some time to make all the PR with some help/directive if anyone want.

**Comment by sgress454** [comment]
You can use as many environments as you want.  Just set the `NODE_ENV` environment variable to the environment you wish to use.  For example, to lift in the `test` environment, do:

```
NODE_ENV=test sails lift
```

The `--prod` command-line setting is just a shortcut for `NODE_ENV=production`.

As far as Grunt, it has special tasks it runs in production mode, but that doesn't prevent you from adding other environments.

**Comment by jaumard** [comment]
Thanks I understand the NODE_ENV for setting any environment but if I want specific tasks how I can do this ? Cause grunt hook play default or prod tasks and nothing else... 
If I set NODE_ENV=test and create a tasks/register/test.js tasks it wasn't play it's the default one.

**Comment by sgress454** [comment]
True, but that default task is just a JavaScript file like everything else--if you want different tasks to run  for different environments, you can edit `tasks/register/default.js` and put in log that configures the task differently depending on the value of `process.env.NODE_ENV`.
