### ISSUE TITLE
Question: What is the canonical way to set up ssl for a sails app?

### ISSUE THREAD

**Issue by ksylvan** [balderdashy/sails#3196]
I don't see anything in the official documentation and I do see this issue: https://github.com/balderdashy/sails-docs/issues/71

Looking at the sources, it looks like what's needed is to set `config.ssl.key` and `config.ssl.cert` to point to some file paths.

What is the right way to set this up for a production environment?

Thanks.

**Comment by richdunajewski** [comment]
I recommend using an HTTP proxy in front of Sails in a production environment, such as Nginx or Apache. This will make it easier to secure in production than to have Node exposed to the outside world. For SSL, I let Nginx handle the termination and Nginx forwards the request internally to Sails unencrypted over HTTP. Another benefit to this approach is using Nginx to load balance multiple Sails instances with only one certificate having to be installed.

If running on Amazon EC2, you may wish to set up an Elastic Load Balancer (ELB) to do this for you, and terminate the SSL at the load balancer. If you plan to use Websockets, there is a workaround you need to do to get the load balancer to pass the Websockets through to Sails, but it's doable.

**Comment by tjwebb** [comment]
> I recommend using an HTTP proxy in front of Sails in a production environment, such as Nginx or Apache

Sails does support SSL out of the box, however I agree with @richdunajewski that as a general rule, in production you don't want node.js *naked* and facing the world directly. I'd recommend setting up nginx in front of node.js (Sails) and managing the SSL with nginx.
