### ISSUE TITLE
JSON Schema to define entities

### ISSUE THREAD

**Issue by heruan** [balderdashy/sails#3197]
Why not use JSON Schema (json-schema.org) to define entities? I understand JSON Schema does not cover all the needed metadata, but it could be easily extended with a schema for Sails/Waterline.

**Comment by sgress454** [comment]
I'm not sure exactly what you're asking...could you elaborate?

**Comment by tjwebb** [comment]
@sgress454 I think he wants to use the ES5 way of defining object properties instead of using the Waterline way. 

@heruan The sounds like an add-on you could write for waterline, but that's not a feature we're going to pull into the core. If you do something like that, let us know.
