### ISSUE TITLE
req.options.populate set in policy has no effect for Blueprints

### ISSUE THREAD

**Issue by kestuxg** [balderdashy/sails#3198]
Blueprint API checks req.options.populate value if it should populate or not. But setting this value from policy doesn't work. I guess Blueprint API gets populate overwritten with default value.
As if I set to true, BP API sees it false (my default value in configuration). All other values like where, criteria goes through to BP API, but not populate.

It would be really nice be able turn on/off populate in policies.
For now I just will be adding my own find methods, but it kills the purpose of having BP api.

**Comment by sgress454** [comment]
Thanks for the report @kestuxg, looking into it.

**Comment by sgress454** [comment]
Looks like there was a bug keeping certain properties of `req.options` from overriding the defaults. Patched here: https://github.com/balderdashy/sails/commit/166e77255dc2860f92bc5cce23dc3878a1e5627f.  Thanks again for the post!
