### ISSUE TITLE
Do we need to use ppa:chris-lea/node.js?

### ISSUE THREAD

**Issue by cacrookes** [balderdashy/sails#3201]
Hi, I'm trying to get sails working on an Ubuntu Trusty 64 box I set up with Vagrant. If I follow the directions on the sailsjs.org site to install sails, using ppa:chris-lea/node.js to install node and npm, everything works. However it uses Node 0.10 and NPM 1.4. I would like to use more recent versions, so I used `curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -` as my source for node and npm on another vagrant box. Sails always fails to install when I try this though.

Every guide I've found online about setting up sails on Ubuntu uses the ppa:chris-lea/node.js repository. Has anyone had success using deb.nodesource.com?

**Comment by BraveKenny** [comment]
I also use `deb.nodesource.com` as my repo for node 0.12.7 on my hosts (mint 17 and debian jessie) and I have no trouble installing  and running sails with them.

Actually I did not know that `ppa:chris-lea/node.js` was advised in most tutorials. I do think people should use `deb.nodesource.com` instead.

**Comment by cacrookes** [comment]
It seems to work if I use the `--allow-root` argument. Thanks!

**Comment by tjwebb** [comment]
Just use n and you'll never run into any of these problems: https://www.npmjs.com/package/n
