### ISSUE TITLE
Similarly Named Environments are all loaded

### ISSUE THREAD

**Issue by samlroberts** [balderdashy/sails#3203]
I have an interesting problem. I had three environments defined in `config/env/`:
+ `development.js`
+ `heroku-development.js`
+ `production.js`

in `heroku-development.js` i was using a heroku environment variable that wasn't on my local machine, but since my machine is the development i thought this would be fine. However both config files `development` and `heroku-development.js`  were loaded into sails on lift. After some digging i found that the culprit is here: https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/index.js#L246

That RegExp matches anything ending in the environment name, which in this case was just development. Not sure if this is the intended behavior. It's simple to avoid, with just some more careful naming of environments. However I hadn't seen anything about it in the docs. 

One fix would be to replace that line with 
    `filter    : new RegExp("^"+env + ".(" + sails.config.moduleloader.configExt.join('|') + ")$"),`

(I'm actually using Sail 0.11.0 so for me the fix was to line [206](https://github.com/balderdashy/sails/blob/v0.11.0/lib/hooks/moduleloader/index.js#L206)
    `filter    : new RegExp('^'+env + '.(js|json|coffee|litcoffee)$'),`
but it looks like the newer version is different).

Another fix would be to update the docs. I'd be having to make a pull request for either fix, depending on what the intended behavior is.

**Comment by sgress454** [comment]
Great catch @samlroberts!  This was definitely a bug.  Added a patch + tests here: https://github.com/balderdashy/sails/commit/417d772735cbfab5d6ecd1d2c06b9a9008e63d22
