### ISSUE TITLE
One way association populated with data that doesn't belong to it.

### ISSUE THREAD

**Issue by dottodot** [balderdashy/sails#3204]
sails v0.11.1 
sails-mongo v0.11.2

I have the following Product Model set up

```
module.exports = {
  attributes: {
    title: 'string',
    main_image: {
      model: 'image'
    },
    listing_image: {
      model: 'image'
    }
  }
};
```
```
Product.findOne({slug:slug}).populate('main_image').populate('listing_image').then(function(product){
			if (!product) return res.send(404);
			res.ok(product);
		});
```
If I create a Image Model and add it's ID to either of the image attributes when I get the product and populate both image attributes they show the same model in each even though I've only added the Image Model to one of them. What's also even stranger is if I create a new Product without any images that too is populated with the same Image.

I don't understand how this can be happening when the attributes don't even have a value.

**Comment by ioisup** [comment]
We got the same issue.

**Comment by RWOverdijk** [comment]
Sounds serious. @dmarcelino @tjwebb @devinivy

**Comment by ioisup** [comment]
For more information, in mongoDB the data was correct.

**Comment by devinivy** [comment]
What version of waterline is being used?  Is there a simple failing test that could be written?

**Comment by RWOverdijk** [comment]
@devinivy Seeing how there's no 0.11.1 of sails, I'll assume he meant 0.11.0, which uses waterline ~0.10.17

**Comment by devinivy** [comment]
Ah, this is likely a result of https://github.com/balderdashy/waterline-cursor/issues/1, which was patched in waterline-cursor 0.0.5.  sails-mongo has this fix on master.  Does someone mind verifying that sails-mongo master branch corrects this problem?  If so, @particlebanana can we expedite a sails-mongo patch release?

**Comment by dottodot** [comment]
@RWOverdijk My installed sails clearly states v0.11.1 in package.json and when I lift I get the same version number and this uses waterline v0.10.19

**Comment by RWOverdijk** [comment]
@dottodot That's cool. I can't find it. What's the commit ref?

**Comment by ioisup** [comment]
My package.json in waterline-cursor shows   "version": "0.0.5"

**Comment by devinivy** [comment]
Try the sails-mongo adapter version that's currently only available on the master branch.  It should pull in waterline-cursor 0.0.6 with the relevant patch.

**Comment by dottodot** [comment]
So far the updated master branch seems to work

**Comment by tjwebb** [comment]
related:
- https://github.com/balderdashy/waterline-cursor/pull/8
- https://github.com/balderdashy/sails-mongo/issues/320
