### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by olalonde** [balderdashy/sails#3206]
Getting this error when trying to connect to a secure websocket with `wss://chatws.mydomain.com` but it works fine with `ws://chatws.mydomain.com`. Https is correctly configured for the app. I assume this is an issue with Nginx configuration? `dokku logs someapp` indicates that nginx never actually forwards the request to my app when using the `wss` scheme.

**Comment by sgress454** [comment]
Hi @olalonde, this forum is for reporting bugs in the Sails core.  You might have better luck posting a question like this in our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).

**Comment by olalonde** [comment]
Oops posted in wrong issue tracker haha sorry.
