### ISSUE TITLE
Blueprint update of associated records, delete instead of unlink?

### ISSUE THREAD

**Issue by Bazze** [balderdashy/sails#3207]
Hello!

When updating associated records on a model through the `update` blueprint function, disassociated records are unlinked (the ID value is replaced with `NULL` and the record sticks around). Is there a simple way to make it delete the disassociated records instead?

**Comment by sgress454** [comment]
There isn't built-in support for cascading delete at this time, but you can implement it yourself using the [`afterDestroy` lifecycle callback](http://sailsjs.org/documentation/concepts/models-and-orm/lifecycle-callbacks#?callbacks-on-destroy) on your model.

**Comment by Bazze** [comment]
I understand. The thing is that when the record is unlinked it doesn't call `afterDestroy`, it just NULLs out the parent id column. I was thinking maybe I could do use the `afterUpdate` hook and then do my stuff if the parent id column is `null`, but even for records that aren't unlinked the blueprint seems to first set the id to `null` in one update and then in another update it sets the id back to what it was before. This behaviour makes it impossible for me to do some sort of cascading delete since I don't really know if it was unlinked or not.
