### ISSUE TITLE
pm2 start app.js -x -- --prod is not working

### ISSUE THREAD

**Issue by BipinBhandari** [balderdashy/sails#3209]
`pm2 start app.js -x -- --prod` always start the script in development mode. It works fine on forever and sails lift. 
PM2 version is 0.14.7
Sails version is 0.11.0
node: v0.12.7

**Comment by sgress454** [comment]
Works for me™.  We're not maintainers of pm2, though we try to help where we can.  You may have better luck on their forums than here, though--this isn't a problem with Sails.  You can also try setting the environment in a different way:

```
NODE_ENV=production pm2 start app.js -x
```

**Comment by varunachar** [comment]
This seems like a sails issue cause sails cause i'm unable to lift sails either.

I have a sailsjs app which starts up fine when run using `sails lift` or `node app.js` commands. When I run the app via pm2 using `pm2 start app.js`, the app isn't available at the configured ports. 

Neither does the following combo work `pm2 start app.js -x -- --prod`

I'm using sails 0.11.2, node v4.1.0, pm2 0.15.9.

What's the issue?

**Comment by xhallix** [comment]
bump - same issue here

**Comment by mikermcneil** [comment]
@xhallix haven't played with pm2 in a while personally, but just a hunch: maybe drop the `-x`?  (basing that off https://github.com/Unitech/pm2/issues/1738#issuecomment-153276352)

**Comment by xhallix** [comment]
@mikermcneil nvm, sorry forgot to delete it, I was just dump.
Looking at the pm2 logs always help when messing up things in your custom code, sorry for the confusion

**Comment by mikermcneil** [comment]
@xhallix no problem, thanks for sharing the tip!
