### ISSUE TITLE
Invalid usage of publishCreate() :: Values must have an `id`, instead got

### ISSUE THREAD

**Issue by jetsonjohn** [balderdashy/sails#3210]
I need to generate id manually not auto generate. My model definition is as follows and in `beforeValidate` callback I am manually setting the `id` value

```
module.exports = {
  attributes: {
    id: {
      type: 'integer',
      primaryKey: true,
      unique: true,
      columnName: 'UserId',
      autoIncrement: true
    },
    name: {type: 'string' }
  },
  beforeValidate: function(values, cb) {
    values.id = generatePk();
    cb();
  }
}
```

After creating the instance I am getting this error

```
error: Invalid usage of publishCreate() :: Values must have an `id`, instead got ::
{ name: 'joe',  id: 0 }
```

Why is this happening. It is correctly entered in the database . The values I have set in `beforavalidate` callback is saved in the database but the `id` in the `newInstance` is 0.  Is there any other configuration I need to set?

**Comment by sgress454** [comment]
Can you post the code for `generatePk()`?  Also, are you calling `publishCreate` directly, or are you seeing this error using the blueprint `create` route?

**Comment by jetsonjohn** [comment]
I have created a new sails app and it doesn't have the issue that I have mentioned. May be it will be issue with in somewhere in my code.
