### ISSUE TITLE
Sails fails to run / install on Node 4.0.0

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/sails#3211]
```
tjwebb@latitude:/.../workspace/balderdashy/node4test $ node -v
v4.0.0-rc.5
tjwebb@latitude:/.../workspace/balderdashy/node4test $ sails generate new node4test
info: Created a new Sails app `node4test`!
tjwebb@latitude:/.../tjwebb/workspace/balderdashy $ cd node4test/
tjwebb@latitude:/.../workspace/balderdashy/node4test $ sails lift

info: Starting app...

Segmentation fault (core dumped)
tjwebb@latitude:/.../workspace/balderdashy/node4test $ 
```

**Comment by tjwebb** [comment]
@mikermcneil @particlebanana @sgress454 you guys might be interested in this. I'll take a look today and see if I can locate a quick fix.

**Comment by sgress454** [comment]
Try `sails lift --silly`?

**Comment by tjwebb** [comment]
```
$ sails lift --silly

info: Starting app...

verbose: Setting Node environment...
verbose: moduleloader hook loaded successfully.
verbose: Loading app config...
verbose: userconfig hook loaded successfully.
verbose: Exposing global variables... (you can disable this by modifying the properties in `sails.config.globals`)
verbose: Loading user hooks...
verbose: userhooks hook loaded successfully.
Segmentation fault (core dumped)
tjwebb@latitude:/.../workspace/balderdashy/node4test $ 
```

I'm walking through the debugger now.

**Comment by tjwebb** [comment]
versions:
```
tjwebb@latitude:/.../workspace/balderdashy/node4test $ sails -v
0.12.0-rc3
tjwebb@latitude:/.../workspace/balderdashy/node4test $ node -pe 'process.versions'
{ http_parser: '2.5.0',
  node: '4.0.0-rc.5',
  v8: '4.5.103.30',
  uv: '1.7.3',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '46',
  openssl: '1.0.2d' }
```

**Comment by tjwebb** [comment]
Ok, I'm doing a fresh re-install of sails, and everything involving node-gyp compilation fails. So probably dependency upgrades will do the trick. Testing that out now...

```
> utf-8-validate@1.1.0 install /home/tjwebb/workspace/balderdashy/sails/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/tjwebb/workspace/balderdashy/sails/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../src/validation.cc:10:0:
/home/tjwebb/.node-gyp/4.0.0-rc.5/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/tjwebb/.node-gyp/4.0.0-rc.5/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/tjwebb/.node-gyp/4.0.0-rc.5/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/tjwebb/.node-gyp/4.0.0-rc.5/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
validation.target.mk:92: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/home/tjwebb/workspace/balderdashy/sails/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-26-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tjwebb/workspace/balderdashy/sails/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.0.0-rc.5
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN engine debug@0.7.4: wanted: {"node":"*"} (current: {"node":"4.0.0-rc.5","npm":"2.14.2"})
npm WARN engine amdefine@1.0.0: wanted: {"node":">=0.4.2"} (current: {"node":"4.0.0-rc.5","npm":"2.14.2"})
npm WARN engine wordwrap@0.0.3: wanted: {"node":">=0.4.0"} (current: {"node":"4.0.0-rc.5","npm":"2.14.2"})
```

**Comment by sgress454** [comment]
ah, ok.  is there anything besides socket.io that still needs to be compiled?

**Comment by tjwebb** [comment]
Right now I'm seeing issues with socket.io and microtime. I have no idea why microtime is a dependency of sails.

**Comment by particlebanana** [comment]
Looks similar to: https://github.com/socketio/socket.io/issues/2213

**Comment by tjwebb** [comment]
Ok microtime is a devDependency. `process.hrtime()` is built into node, I'm not sure why we aren't using that.

https://nodejs.org/api/process.html#process_process_hrtime
> The primary use is for measuring performance between intervals.

**Comment by tjwebb** [comment]
Removed microtime; remaining install failures related to socket.io: https://gist.github.com/tjwebb/2e01d91fce5899eb0f7b

**Comment by jldec** [comment]
a temporary workaround would be to re-direct the dependency

>  "socket.io-client": "github:gsklee/socket.io-client#e50c1cc"

see https://github.com/socketio/socket.io/issues/2213
another alternative is to prevent installs under node v4.0 while the dependencies catch up.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by misterjt** [comment]
As i realise, i cant use sailsjs in nodejs v4.0.0 now?

**Comment by mikepaggi** [comment]
i'm getting the same start up error about Seg fault.  Had to switch back to using node 0.12.7

**Comment by maxmaht** [comment]
i've the same error, sails lift -silly give me :

`info: Starting app...`
`verbose: Setting Node environment...`
`verbose: Please run `npm install coffee-script` to use coffescript (skipping for now)`
`silly: Here's the require error(s):  Error: Cannot find module 'coffee-script/register'`
`    at Function.Module._resolveFilename (module.js:336:15)`
`    at Function.Module._load (module.js:286:25)`
`    at Module.require (module.js:365:17)`
`    at require (module.js:384:17)`
`    at Hook.defaults (/usr/lib/node_modules/sails/lib/hooks/moduleloader/index.js:44:9)`
`    at Hook.bound [as defaults] (/usr/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)`
`    at applyDefaults (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:70:22)`
`    at Object.async.series.moduleloader (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:125:11)`
`    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:620:25`
`    at iterate (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:146:13)`
`    at Object.async.eachSeries (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:162:9)`
`    at Object.async.series (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:619:19)`
`    at initializeHooks (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:117:11)`
`    at /usr/lib/node_modules/sails/lib/app/load.js:127:9`
`    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:607:21`
`    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:246:17 { [Error: Cannot find module 'coffee-script/register'] code: 'MODULE_NOT_FOUND' } Error: Cannot find module '/`home/maxoux/rhproject/ll/node_modules/coffee-script/register'
`    at Function.Module._resolveFilename (module.js:336:15)`
`    at Function.Module._load (module.js:286:25)`
`    at Module.require (module.js:365:17)`
`    at require (module.js:384:17)`
`    at Hook.defaults (/usr/lib/node_modules/sails/lib/hooks/moduleloader/index.js:48:11)`
`    at Hook.bound [as defaults] (/usr/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)`
`    at applyDefaults (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:70:22)`
`    at Object.async.series.moduleloader (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:125:11)`
`    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:620:25`
`    at iterate (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:146:13)`
`    at Object.async.eachSeries (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:162:9)`
`    at Object.async.series (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:619:19)`
`    at initializeHooks (/usr/lib/node_modules/sails/lib/app/private/loadHooks.js:117:11)`
`    at /usr/lib/node_modules/sails/lib/app/load.js:127:9`
`    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:607:21`
`    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:246:17 { [Error: Cannot find module '/home/maxoux/rhproject/ll/node_modules/coffee-script/register'] code: 'MODULE_NOT_FOUND' }`
`verbose: moduleloader hook loaded successfully.`
`verbose: Loading app config...`
`verbose: userconfig hook loaded successfully.`
`verbose: Exposing global variables... (you can disable this by modifying the properties in `sails.config.globals`)`
`verbose: Loading user hooks...`
`verbose: userhooks hook loaded successfully.`
`Erreur de segmentation`

**Comment by alyrik** [comment]
Updating sails package globally and locally resolved this problem for me.

**Comment by jldec** [comment]
Latest socket.io (v1.3.7) installs with node v4.0.

**Comment by camsjams** [comment]
@jldec Thanks for the info - I just tried on a fresh install of Sails and a manually bumped the socket.io version in `sails-hook-sockets` and it looks to be much improved! I will try more with an existing project, but this looks promising!

**Comment by DiegoZoracKy** [comment]
My experiences solving this problem:

OSX: 10.9.4
Updating sails global and local, but, **only on Node v4.1.0**

Ubuntu: 14.04
Updating sails global and local, but, **only on Node v4.1.0**

Windows 7: 
Worked since v4.0.0

**Comment by mikermcneil** [comment]
@rauchg just published socket.io 1.3.7  

see https://github.com/socketio/socket.io/issues/2245#issuecomment-142168909 and https://github.com/socketio/socket.io/issues/2254

If y'all wouldn't mind giving that a test, we can bump the [sio dep in sails-hook-sockets](https://github.com/balderdashy/sails-hook-sockets/blob/master/package.json#L12) and publish a patch to NPM asap.

**Comment by DiegoZoracKy** [comment]
In my case updating socket.io to 1.3.7 wasn't enough to Node v4.0. As i said in my previous comment, just when i updated my node version to 4.1 things started to work again. (osx and ubuntu)

**Comment by camsjams** [comment]
Hmm @DiegoZoracKy when I got home and tried on another project, you're comment holds true.

For me on a fresh install of Sails.js with Node 4.0.0 it appeared to work (though there was just one API controller).

On a realistic install of Sails.js with more dependencies and setup, I had to switch to Node 4.1.0 as mentioned above.

But I can confirm that with Node.js 4.1.0 that this bug is gone for me!

Thanks all!

**Comment by mikermcneil** [comment]
@camsjams @DiegoZoracKy @jldec @alyrik @ChALkeR @mikepaggi @tjwebb @sgress454 @particlebanana thanks everyone for the help!

**Comment by vielmetti** [comment]
Please note that Node.js 4.1.0 has a security issue at 

https://github.com/nodejs/node/pull/2931

which will make you want to depend on >=4.1.1 once it appears.

**Comment by camsjams** [comment]
@vielmetti noted - thanks!

**Comment by mikermcneil** [comment]
@vielmetti thanks!

**Comment by sgress454** [comment]
Patched and published Sails v0.11.2.  Thanks all!

**Comment by DigitalSkyline** [comment]
Same issue / fresh install node stable (5.0)

**Comment by sgress454** [comment]
@DigitalSkyline I was able to install Sails on Node 5 without error.  Make sure you clear your npm cache first (`npm cache clear`), and if you still experience problems, please open a new issue (this one is about Node 4) with details about your system including NPM version.

**Comment by randallmeeker** [comment]
also remove your node_modules directory for good measure.

**Comment by cScarlson** [comment]
I was dead in the H2O -- ready to move my beta from prototype/sails to beta/strapi. Here's what I did instead (because I like Sails more)...
`npm uninstall -g sails`
[nodejs get latest (4.4.n)]
`npm i -g sails`
That worked :)
