### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by donadev** [balderdashy/sails#3213]
Sorry for creating the issue, but I desperately need the transaction feature on Waterline for my project.
I found a bunch of workarounds and the better seem to be using the node-continuation-local-storage for maintaining a database connection grabbed from the connection pool and available to the transaction. Anyway, this doesn't work so well and I was wondering when a transactional-compliant version of Waterline will be provided. I think that transactional support is a feature that every ORM should have, and I'm just looking forward to see it on Sails!

**Comment by randallmeeker** [comment]
https://github.com/balderdashy/waterline/issues/755

**Comment by donadev** [comment]
Hi, I've already read that thread, but I can't find any answer to my question! 
I want to use Transactions on an ORM level.. i need all the advantages of Waterline.
Can you tell me when this feature will be released?

**Comment by randallmeeker** [comment]
I can not answer your questions directly, only that this question should be posted in the waterline repo if your intent is to use transactions with waterline.

**Comment by donadev** [comment]
ok. thank you, you are right.. I will post it here.
