### ISSUE TITLE
global variables at startup form DB

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/sails#3214]
How to load the data from the database to the global variables at startup?

I would like to add a file in the 'config' directory, through the 'model' to get the data, assign to the global variable.

**Comment by sgress454** [comment]
Hi @Wizzercn, please try posting support questions like this on our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).  In this case it would be good if you could rephrase your question with a bit more detail about what you're trying to accomplish.  Sounds like you may just need to use the [bootstrap script](http://sailsjs.org/documentation/anatomy/my-app/config/bootstrap-js).
