### ISSUE TITLE
Retrieve models given a certain many-to-many relation

### ISSUE THREAD

**Issue by JHereu** [balderdashy/sails#3215]
I have some doubts about how to perform a certain custom GET request through Sails blueprints.

Scenario:
Imagine I have a sails model called `office` and a sails model called `city`. They share a many-to-many relation between them. It is to say that one `office` can "be" in multiple cities and a `city` can hold multiple offices.

So, here is the question:
Is it possible to retrieve only the offices given a certain city with the default blueprints? I mean, customizing the where clause of the query or so, without previously having to get all the collection and populate it.

Thanks in advance.

**Comment by sgress454** [comment]
It's not entirely clear what you're asking--if it's a many-to-many relationship, then a request to `/city/123` will respond with the city with ID 123, and all of the offices associated with that city.

**Comment by JHereu** [comment]
That is right. My question is a little more concrete. I want to do this, but I'd like it to retrieve ONLY the offices associated.

I guess this functionality is not implemented yet. Thanks though.

**Comment by sgress454** [comment]
Ah gotcha.  You are correct, blueprints don't currently allow you to do projections like that.
