### ISSUE TITLE
Not able to override model connections in test config when model has overridden connection 

### ISSUE THREAD

**Issue by facultymatt** [balderdashy/sails#3216]
In the documentation for config.models http://sailsjs.org/documentation/reference/configuration/sails-config-models#?properties it states that model.config.connection will **override the default database connection on any given model will use without a configured override**. This is useful in tests when you want to switch to a test db. 

However, for models that already have an override (See below example), they ignore this setting. It should be possible to override these models connections too. 

```
var User = module.exports = {
  connection: 'specialMongoServer',
  attributes: {}
};
```

**Comment by sgress454** [comment]
If you want a particular model to have its connection be configurable, you can use a connection name _specific to that model_ and override that connection config in your environment config file (or wherever). For example:

**api/models/User.js**:
```
var User = module.exports = {
  connection: 'userConnection',
  attributes: {}
};
```

**config/env/test.js**
```
  connections: {
    userConnection: {
      adapter: 'sails-disk',
      fileName: 'test.db'
    },
  }
```
