### ISSUE TITLE
populate data from relation in blueprints

### ISSUE THREAD

**Issue by mhipo1364** [balderdashy/sails#3217]
Hi

I need to populate data in blueprints `GET` , for example I want to get `contents` which have some particular `tags`, How can I do this?

I'm so confuse about node.js ORM capabilities

**Comment by sgress454** [comment]
Hi @mhipo1364, thanks for using Sails!  Just FYI this forum is for reporting bugs in the Sails core.  In the future if you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
<hr/>
By default, if you have a `contents` model with a `tags` property that is an association to a collection of another model, the blueprint `GET` request to `/contents` should populate that `tags` property for you.  If it's not working, I'd suggest posting a question to one of the above forums with more information about your model setup.
