### ISSUE TITLE
policies for Folder

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/sails#3218]
![qq 20150910114015](https://cloud.githubusercontent.com/assets/2408114/9779670/d8393b50-57b0-11e5-8065-2bb61ce8b7fe.jpg)

Excuse me, would like to have a whole folder to the policies configuration how to write?

**Comment by Wizzercn** [comment]
Sample::
../controllers/private/sys/UnitController.js
../controllers/private/sys/UserController.js
../controllers/private/order/OrderController.js
...

**Comment by sgress454** [comment]
Hi @Wizzercn , thanks for using Sails!  Just FYI this forum is for reporting bugs in the Sails core.  In the future if you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
<hr/>
There is currently no way to use the `config/policies.js` file to protect a subfolder.  The only way to do so would be to use a blanket policy (i.e. a policy protecting `*`) which, in its implementation, checked the controller name (`req.options.controller`) and matched it against a regular expression.
