### ISSUE TITLE
Getting current locale

### ISSUE THREAD

**Issue by FabienHenon** [balderdashy/sails#3219]
I'd like to get the current locale (the one used to translate with ```req.__('to_translate');```) to send it to the plugins I use and that needs a locale.

I saw the ```req.setLocale('locale');``` to set the current locale but nothing to retrieve it. Is it normal ?

Or, do I need to send it from the client to be able to get it server-side?

**Comment by sgress454** [comment]
Hi @FabienHenon, thanks for using Sails!  Just FYI this forum is for reporting bugs in the Sails core.  In the future if you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
<hr/>
You can use `req.getLocale()` to get the current locale.  We'll add this to the docs!
