### ISSUE TITLE
forever doesn't works as specified in dev docs

### ISSUE THREAD

**Issue by pulkitnandan** [balderdashy/sails#3220]
I'm trying to follow dev doc's regarding deployment and trying to lift my app's production version live forever on port 80, but it stay where it was and nothing procceds further. Have a look at its screenshot.

![image](https://cloud.githubusercontent.com/assets/5687927/9785017/b58ec07c-57cc-11e5-9300-0fcb055c49dc.png)

**Comment by pulkitnandan** [comment]
Its strange my app is up after five minutes but I cant see any app when I do forever list.

**Comment by mrvini** [comment]
try to run it like the following, this way you'll observe the logs and see whats causing delay:
> sudo forever start app.js --prod && forever --fifo logs 0
alternatively do 
> sudo forever start app.js --prod
> sudo forever logs 0

**Comment by Josebaseba** [comment]
```
NODE_ENV=production forever start app.js
```

**Comment by sgress454** [comment]
@mrvini is correct; if you start `forever` as the root user (i.e. using `sudo`) then you have to run `forever list` as the root user as well in order to see the process you started.

**Comment by pulkitnandan** [comment]
Then certainly you must be having logic for this screenshot.

![image](https://cloud.githubusercontent.com/assets/5687927/9972081/bddbbf92-5e7e-11e5-8e02-0097a82d7800.png)

**Comment by pulkitnandan** [comment]
Quick resolution

until myserver; do
    echo "Server 'myserver' crashed with exit code $?.  Respawning.." >&2
    sleep 1
done
