### ISSUE TITLE
ExpressJS prior to Sails 0.12-rc* Candidates has Static Asset Problems

### ISSUE THREAD

**Issue by crh3675** [balderdashy/sails#3221]
We recently upgraded SailsJS from 0.11 to 0.12-rc3 because the ExpressJS version paired with 0.11 (Express 3.16.0) had a pretty serious bug with sending static files.  We would get "pending" in the browser on a regular basis which would hang rendering in development mode.

We researched the issue and were happy to find that SailsJS bumped ExpressJS to 3.20.2 which resolves the issue. To replicate, simply have about 10-15 static files (images, JS, CSS - whatever) render upon page load with Express 3.16.0.

**Comment by Ignigena** [comment]
I can confirm I was having the same issue in my Sails 0.11 app. Only noticed once I had enough third party Bower libraries in the pipeline to go above that threshold. Every few hard refreshes would result in a page stuck half-loaded. I only got around this by forcing the development environment to concat all JS and CSS assets.

**Comment by sgress454** [comment]
Ahhhhhhhhhh
@crh3675 would you be my hero and post something in about your findings in: https://github.com/balderdashy/sails/issues/2616

**Comment by crh3675** [comment]
Simply put, it is ExpressJS.  I didn't dig too deep into it but 3.16.0 was the issue.

**Comment by sgress454** [comment]
Thanks again for the post @crh3675.  This is fixed in the master branch (Express locked to 3.20.2).

**Comment by crh3675** [comment]
Glad to contribute!

**Comment by randallmeeker** [comment]
Can this be pushed into an .11.x release. This is a major bug for production environments in the .11.x version.
