### ISSUE TITLE
string primaryKey  is always length:255

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/sails#3222]
id: {
      type: 'string',
      primaryKey: true,
      size: 100
  },

in database :
varchar(255) NOT NULL

**Comment by sgress454** [comment]
Hi @Wizzercn.  If you think this is a bug, please post it in the [Waterline repo](https://github.com/balderdashy/waterline).  Thanks!

**Comment by Wizzercn** [comment]
https://github.com/balderdashy/waterline/issues/1150
@devinivy commented 17 hours ago
This is not a waterline-specific problem since the adapters are responsible for the actual table definitions– could you please open an issue with the relevant adapter?

You Buck each other, in the end who should be to solve this problem?
-----------------------------------------------------------------------

**Comment by RWOverdijk** [comment]
@Wizzercn You're right and we're sorry for that. I've moved the issue to [the relevant adapter](https://github.com/balderdashy/sails-mysql/issues/251) and also submitted [a fix for the problem](https://github.com/balderdashy/sails-mysql/pull/250), so the wheels are in motion.

**Comment by Wizzercn** [comment]
@RWOverdijk Good thank you :)
