### ISSUE TITLE
"normalized" CHANGELOG.MD

### ISSUE THREAD

**Issue by tarlepp** [balderdashy/sails#3229]
I have noticed numerious questions on IRC and gitter channel about changes of sails. Also imho current ```CHANGELOG.MD``` is a bit hard to really see what has been changed.

I recommend that you guys started to use https://github.com/skywinder/github-changelog-generator or something similar that changelog.md is generated automatic.

**Comment by kevinob11** [comment]
I'd love to see something standardized for this, including examples would be even better. I'm happy to help, but as it sits right now it is really difficult to know what the changes are in order to start the process.

**Comment by tarlepp** [comment]
Could this be used on upcoming 0.12.0 release?

**Comment by mikermcneil** [comment]
@tarlepp love it.  We'll definitely need to have a more human-curated migration guide for any releases w/ breaking changes, but this changelog would be a great stopgap.  The more stuff like this we can automate, the better.  
@kevinob11 appreciate that

**Comment by tarlepp** [comment]
Hmm, so this is coming then?
