### ISSUE TITLE
unable to get raw xml posting

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#3233]
add 
require('body-parser').raw({ type: 'text/xml' })
in http.js
will enabled parsing xml.
but will stop passing body.query.

**Comment by calidion** [comment]
solved by the following lines.
I would like to suggest sails to integrate xml rawBody support.

```js
    rawParser: function(req, res, next) {
      switch(req.headers['content-type']) {
        case 'text/xml':
          require('body-parser').raw({ type: 'text/xml' })(req, res, next);
          break;
        default :
          next();
      }
    },
    order: [
      'startRequestTimer',
      'cookieParser',
      'session',
      'myRequestLogger',
      'rawParser',
      'bodyParser',
      'handleBodyParserError',
      'compress',
      'methodOverride',
      'poweredBy',
      '$custom',
      'router',
      'www',
      'favicon',
      '404',
      '500'
    ]
```

**Comment by mikermcneil** [comment]
@calidion thanks for taking the time to share your solution here!

**Comment by acrodrig** [comment]
Question: wouldn't this solution stop middleware processing (for `text/xml` content) for all other middleware that comes after `rawParser`? I am trying to do something similar (avoid default body parsing) but have been unsuccessful so far. Thanks.
