### ISSUE TITLE
Request standards for sails app

### ISSUE THREAD

**Issue by pulkitnandan** [balderdashy/sails#3234]
I'm sure different clients request data in different ways but still how can I deduce what's wrong with my sails app if I recieve a error such as this  

http://localhost:1337/committees/create?
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: syntax error at or near ")"
    at Connection.parseE (/home/rohit/backend/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/rohit/backend/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/rohit/backend/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Details:  error: syntax error at or near ")"

null '{\n  "error": "E_UNKNOWN",\n  "status": 500,\n  "summary": "Encountered an unexpected error",\n  "raw": {\n    "name": "error",\n    "length": 83,\n    "severity": "ERROR",\n    "code": "42601",\n    "position": "27",\n    "file": "scan.l",\n    "line": "1053",\n    "routine": "scanner_yyerror"\n  }\n}'

When using wget to find something in sails based rest app or using chrome to find something or even the curl client for ubuntu.

While the query it is performing is using the curlrequest npm package which turns out to be the only way known to curl rest api's made by OpenFec as they add some voodoo their which makes it impossible to be queried using simple npm module of http, and none high level requesting npm packages work with it, some gives installation error's maybe exclusively for sails app. Very paradoxical though but its true. 

This is my code

/**
 * Module dependencies
 */
var actionUtil = require('sails/lib/hooks/blueprints/actionUtil'),
    _ = require('lodash'),
    curl = require('curlrequest');

/**
 * Find Records
 *
 *  get   /:modelIdentity
 *   *    /:modelIdentity/find
 *
 * An API call to find and return model instances from the data adapter
 * using the specified criteria.  If an id was specified, just the instance
 * with that unique id will be returned.
 *
 * Optional:
 * @param {Object} where       - the find criteria (passed directly to the ORM)
 * @param {Integer} limit      - the maximum number of records to send back (useful for pagination)
 * @param {Integer} skip       - the number of records to skip (useful for pagination)
 * @param {String} sort        - the order of returned records, e.g. `name ASC` or `age DESC`
 * @param {String} callback - default jsonp callback param (i.e. the name of the js function returned)
 */

module.exports = function findRecords(req, res) {

    // Look up the model
    var Model = actionUtil.parseModel(req);

    // If an `id` param was specified, use the findOne blueprint action
    // to grab the particular instance with its primary key === the value
    // of the `id` param.   (mainly here for compatibility for 0.9, where
    // there was no separate `findOne` action)
    if (actionUtil.parsePk(req)) {
        return require('./findOne')(req, res);
    }

    // Lookup for records that match the specified criteria
    var query = Model.find()
        .where(actionUtil.parseCriteria(req))
        .limit(actionUtil.parseLimit(req))
        .skip(actionUtil.parseSkip(req))
        .sort(actionUtil.parseSort(req));
    // TODO: .populateEach(req.options);
    query = actionUtil.populateEach(query, req);
    query.exec(function found(err, matchingRecords) {
        if (err) return res.serverError(err);

        // Only `.watch()` for new instances of the model if
        // `autoWatch is enabled.
        if (req._sails.hooks.pubsub && req.isSocket) {
            Model.subscribe(req, matchingRecords);
            if (req.options.autoWatch) {
                Model.watch(req);
            }
            // Also subscribe to instances of all associated models
            _.each(matchingRecords, function (record) {
                actionUtil.subscribeDeep(req, record);
            });
        }

console.log(matchingRecords);	     
        if (matchingRecords.length == 0){
          var mo = actionUtil.parseCriteria(req);
          var elem, suffix, values; 

          if(mo.candidate_id != undefined )
          {
		suffix = 'candidates';
            elem = 'candidate_id';
            values = mo.candidate_id
          }
	if(mo.committee_id != undefined){
            suffix = 'committees';
            elem = 'committee_id';
            values = mo.committee_id
	}
  
  var path = "https://api.open.fec.gov/v1/"+ suffix + "?api_key=DEMO_KEY&" + elem + "=" + values;
  // direct way

 curl.request(path, function(data, response){
         // parsed response body as js object
var point  = '';

if(suffix == 'candidates'){
	point += 'district_number=' + (JSON.parse(response).results[0].district_number || '0') + '&state=' + (JSON.parse(response).results[0].state || '') + 
'&candidate_id=' + (JSON.parse(response).results[0].candidate_id || '') + 
'&active_through=' + (JSON.parse(response).results[0].active_through || '') +
'&party=' + (JSON.parse(response).results[0].party || '') +
'&incumbent_challenge=' + (JSON.parse(response).results[0].incubment_challenge || '') +
'&party_full=' + (JSON.parse(response).results[0].party_full || '') + 
'&district=' + (JSON.parse(response).results[0].district || '') +
'&election_years=' + (JSON.parse(response).results[0].election_years || '') +
'&office_null=' + (JSON.parse(response).results[0].office_null || '') + 
'&office=' + (JSON.parse(response).results[0].office || '') +
'&incubment_challenge_full=' + (JSON.parse(response).results[0].incument_challenge_full || '')  + 
'&cycles=' + (JSON.parse(response).results[0].cycles || '') + 
'&candidate_status=' + (JSON.parse(response).results[0].candidate_status || '') 
;

console.log(point);
}

var newPath = 'http://' + req.headers.host + '/' + suffix + '/create?' + point;
console.log(newPath);
      curl.request(newPath , function(data, resp){
console.log(data, resp);
	//res.ok(JSON.parse(resp));
	return;
});
   // raw response
 

           });

   }
        else
res.ok(matchingRecords);
    });
};

It gives error in such a way that even the console.log is not printed when I'm getting the error, Is this a feature with sails?

**Comment by pulkitnandan** [comment]
Its due to this curlrequest module.

**Comment by pulkitnandan** [comment]
I'm trying to call a create operation of the model by using request or curlrequest npm js libs when a particular find query fails in the overidden bluprints api find.js which doesn't works and return status code 200, while using the same url I can perform the operation successfully using  browser or a curl desktop client. Does sailsjs block programmatical calls for crud op's like create from a bluprints overidden call of find method.

**Comment by mikermcneil** [comment]
> Does sailsjs block programmatical calls for crud op's like create from a bluprints overidden call of find method.

Welcome @pulkitnandan- would you please take this question to Google groups or StackOverflow?  We reserve GitHub issues for confirmed issues with the framework.  Thank you!
