### ISSUE TITLE
How to get the `sailes.config.*` in the services?

### ISSUE THREAD

**Issue by imfly** [balderdashy/sails#3239]
Hi, 
It runs well in `dev`, but I find an error when execute `sails www --prod`.

The logs:

```
user@debian:~/$ sails www --prod
/path/to/project/node_modules/sails-permissions/node_modules/sails-auth/api/services/passport.js:281
  var strategies = sails.config.passport;
                   ^
ReferenceError: sails is not defined
    at Authenticator.passport.loadStrategies (/path/to/project/node_modules/sails-permissions/node_modules/sails-auth/api/services/passport.js:281:20)
    at Authenticator.bound [as loadStrategies] (~/.npm/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.initialize (/path/to/project/node_modules/sails-auth/api/hooks/sails-auth.js:4:31)
    at Hook.bound [as initialize] (~/.npm/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/kuby/.npm/lib/node_modules/sails/lib/hooks/index.js:75:14
    at /home/kuby/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /home/kuby/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (~/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (~/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Can't call the `sails.config.*` in the services ?

Thx

**Comment by richdunajewski** [comment]
Does it work if you type `sails lift --prod` rather than www?

**Comment by imfly** [comment]
@richdunajewski ,
Hi,
It doesn't work if use `sails lift --prod` as same as `sails www --prod`. The `sails, req, res...` can't be called in the services if the env is `production`.

**Comment by imfly** [comment]
Sorry The `sails, req, res...` can be called in the services if the env is production but can be not in `gruntBuild`

**Comment by tjwebb** [comment]
@imfly is your issue resolved?

**Comment by imfly** [comment]
@tjwebb ,
Thanks for your hooks `sails-auth` and `sails-permissions`.

I have to pass the parameters `sails,req,res...`  to the methods in the services, for instance `sails.services.passport.loadStrategies(sails)...`, temporarily to resolve it.

**Comment by tjwebb** [comment]
Can you link to your code? I'm not clear on what exactly you're trying to achieve.

**Comment by imfly** [comment]
Oops, it's only a new studying project. I have achieved deploying it by using `capistrona` (ruby)  in production. so must run `sails www --prod` on the server when call `cap producton deploy`.

The `hooks/sails-permissions` code that I have changed:

```
...
module.exports = function (sails) {
  return {
    ...
    initialize: function (next) {
      ...
      sails.services.passport.loadStrategies(sails);
      ...

      sails.after('hook:orm:loaded', function () {
        // fixme there is a bug： `sails www --prod` can't get `Model,sails...`

        // Model.count()
        //  .then(function (count) {
        //    if (count == sails.models.length) return next();
            if (process.env.NODE_ENV === 'production') return next();

            return initializeFixtures(sails)
              .then(function () {
                sails.emit('hook:permissions:loaded');
                next();
              });
      //    })
      //    .catch(function (error) {
      //      sails.log.error(error);
      //      next(error);
      //    });
      //});
    });
  }
}};
...
```

**Comment by imfly** [comment]
@tjwebb ,
This repo [sails-permissions-example](https://github.com/ryanwilliamquinn/sails-permissions-example.git) has the same error in my env when I run `sails www --prod`

**Comment by imfly** [comment]
And my repo [sails-deploy-example](https://github.com/imfly/sails-deploy-example) 

problems:

* can't use `sails www --prod`;
* can't get 'sails, req' in the services ;
* can't get the `req.params('')`  correctly, so the follow code gets a `undefined` and return `res.forbidden();` for ever;

The code: https://github.com/tjwebb/sails-auth/blob/master/api/controllers/AuthController.js#L83

**Comment by mikermcneil** [comment]
@imfly:  The issue queue in this repo is for verified bugs with documented features only, please; no feature requests, questions, or commentary-- and also no bug reports about undocumented features or unofficial plugins. Please review our contribution guide for our process for feature requests and questions.  In the future for support requests please visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Thanks so much for your help!

**Comment by tjwebb** [comment]
> no feature requests, questions, or commentary-- and also no bug reports about undocumented features or unofficial plugins

What do you think github is for, anyhow?

> @tjwebb ,
> Thanks for your hooks sails-auth and sails-permissions.

@imfly Thanks for using them and providing feedback! FYI: https://github.com/tjwebb/sails-permissions/issues/200
