### ISSUE TITLE
Association "add to" returns 404 on Ubuntu Server.

### ISSUE THREAD

**Issue by glemiere** [balderdashy/sails#3247]
Hi !
I followed instruction for adding associates datas here : http://sailsjs.org/documentation/reference/blueprint-api/add-to

Postman returns a 404 error not found, it's strange because populate where works perfectly :
http://sailsjs.org/documentation/reference/blueprint-api/populate-where

Is anybody has this problem too ?

**Comment by sgress454** [comment]
Hi @glemiere, just FYI, this forum is for reporting bugs in the Sails core.  For support requests, you'll have better luck visiting our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge), [StackOverflow](http://stackoverflow.com), or our [Google Group](https://groups.google.com/forum/#!forum/sailsjs).  Be sure to gather up as much information as possible--including concrete steps to reproduce your issue, and ideally links to actual code--before asking for support!
