### ISSUE TITLE
Socket issue on AWS

### ISSUE THREAD

**Issue by zfrenchee** [balderdashy/sails#3249]
I'm building an app called Tuftslife, and when running locally it works fine, but when I put it on AWS, it works for a little, outputs a lot of errors (like those below) and then crashes a little while later and only returns 500s. Our theory is that these requests are never timing out and overwhelming the server. 

<img width="530" alt="screen shot 2015-09-22 at 12 16 19 pm" src="https://cloud.githubusercontent.com/assets/2761597/10024140/d9407ca8-6123-11e5-8814-fcf5f83cc9c0.png">

We tried turning off socket.io using this [gist](https://gist.github.com/mikermcneil/8911041) but it doesn't seem to have worked. What are we doing wrong?

**Comment by mikermcneil** [comment]
see https://twitter.com/zfrenchee/status/646377731224150021
