### ISSUE TITLE
Does `SailsJS` follow JSON API specs?

### ISSUE THREAD

**Issue by tenzan** [balderdashy/sails#3255]
Does `SailsJS` follow JSON API specs?

If yes, why don't you submit `SailsJS` at http://jsonapi.org/implementations/ ?

**Comment by RWOverdijk** [comment]
It doesn't _really_ do that. It could, but I suppose we'd have to vote on that. :) :+1: from me.

**Comment by tenzan** [comment]
I think now it's a good timing to start following `JSON API` specs :smile:

**Comment by listepo** [comment]
+1 :+1:

**Comment by ghaiklor** [comment]
:+1:

**Comment by mikermcneil** [comment]
Hi @tenzan. So of course today this can be accomplished using custom actions.  To implement a generic approach that uses JSON API, you'll want to override the blueprints hook.  Please check out CONTRIBUTION.md for our issue submission guidelines.

**Comment by tenzan** [comment]
:+1:

**Comment by cottrellio** [comment]
+1

**Comment by ghaiklor** [comment]
I'm going to override this in my Yeoman generator for Sails after stable release. You can help me out to do that - https://github.com/ghaiklor/generator-sails-rest-api/src/blueprints

**Comment by jimmyjamieson** [comment]
:thumbsup: :pray:

**Comment by jimmyjamieson** [comment]
Would this be something that could be implemented for the 1.0 release? Also, when is 1.0 due?
