### ISSUE TITLE
select and populate

### ISSUE THREAD

**Issue by Clan-Utility** [balderdashy/sails#3256]
I am using sails 0.11.0 & waterline 0.10.26

'select' criteria is not playing well with populate

These will work:

    School.find({select:['id','name']})
    School.find().populate('students', {select:['name']})

But for this:

    School.find({select:['id','name']}).populate('students', {select:['name']})

The populated students is OK with only name attributes selected. But select is not working for School any more, returning all attributes of School

**Comment by sgress454** [comment]
Hi @Clan-Utility--`select` is not actually a documented (or tested!) feature in Waterline, so I'm afraid you'll have to use it at your own risk.
