### ISSUE TITLE
Ensure Object exists when used in a relationship

### ISSUE THREAD

**Issue by Siecje** [balderdashy/sails#3257]
On creation with a reference to another object, that object doesn't need to exist.

Steps in README of https://github.com/Siecje/sails-bug

https://github.com/balderdashy/sails/issues/2822

**Comment by sgress454** [comment]
If you are up for making a pull request to [sails-postgresql](https://github.com/balderdashy/sails-postgresql) to automatically create (and remove!) foreign key restraints based on model attributes, go for it!  Otherwise, you are welcome to add those constraints to the database manually.
