### ISSUE TITLE
sails.config.views.locals not available in controller or views

### ISSUE THREAD

**Issue by stewhouston** [balderdashy/sails#3259]
Simple string value stored in config/views.js locals does not propagate to res.locals, or to the rendered view.

```
module.exports.views = {
    engine: {
        ext: 'hbs',
        fn: require("consolidate").handlebars
    },
    locals: {
        foo: 'bar'
    },
    partials: true,
    layout: false
};
```

console.log(res.locals.foo) displays 'undefined'

**Comment by mikermcneil** [comment]
Thanks for posting @stewhouston.  Are you able to access them in `res.view()`?

**Comment by stewhouston** [comment]
Thanks, Mike. The locals make their way into the template when using res.view.

First week on Sails, so I'm working past bare express idioms one by one. Take care.

**Comment by MarcDiethelm** [comment]
Why is this issue closed? Setting _global_ template vars using the documented `config.views.locals` does not seem to be working. Using Handlebars I cannot access any properties set on `config.views.locals` anywhere. Quite the dealbreaker!

See: https://github.com/balderdashy/sails/blob/master/lib/hooks/request/locals.js#L29

**Comment by MarcDiethelm** [comment]
Quick workaround:

Add this middleware callback to `config/http.js` (You may need to uncomment the `order` array and add the function name).

```js
        /**
         * Implement the global app locals mixing in that Sails promises us, yet doesn't provide
         * https://github.com/balderdashy/sails/issues/3259
         */
        mixinAppLocals: function(req, res, next) {

            _.extend(res.locals, req._sails.config.views.locals);

            next();
        }
```
