### ISSUE TITLE
Crash when refreshing browser in 4.1.0/4.1.1

### ISSUE THREAD

**Issue by robgrimball** [balderdashy/sails#3262]
Our node app seems to work fine regarding refreshing from the broser in v0.12.7 of node, even when the npm install was done on node v4.1.0, however, the same application with no other changes than switching to use v4.1.0 or v4.1.1 of node crashes nearly always when trying to do a refresh.  The crash is : 

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:474:7)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:529:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)

I am stumped from this point, not knowing the internals of sails or node well enough to know what is going on, nor whether even the problem is with sails, or with node.  Given it seems to be crashing inside _http_server.js, I am guessing that no matter what it shouldn't be doing this from any sort of request the browser might make, so I am leaning to thinking it is a problem with node.  But an opening the issue here to see if anyone has any thoughts/suggestions.

Thanks!

**Comment by robgrimball** [comment]
Found out I had a very old sails v0.10.4 installed outside of nvm which I forgot entirely about, once I removed it, all seems to be good!

**Comment by robgrimball** [comment]
Just a quick note to anyone else who might come across this issue.  The issue was actually NOT the very old sails v0.10.4 that I had lurking around I think, but rather related to this issue : #3221

This seemed to not manifest with crashes in node 0.12.7, just the browser hanging.  But when I ran under node 4.1.1, it was crashing node with the error above.  Switching to sails v0.12.0-rc3 fixed the problem, so I am imagining that the version of express used in 0.11.x of sails was the root of the problem.  Not to mention the browser no longer sometimes hangs so the application is pretty snappy on a refresh again.

**Comment by nevercast** [comment]
Just to confirm with you @robgrimball Sails works under Node 4.1.1 with v0.12.0-rc3 (and possibly higher) of Sails?

**Comment by robgrimball** [comment]
Sorry for the late reply.  I actually found we were having too many other issues with 4.1.1 and sails 0.12.0-rc3 to warrant continued use, so we backed off to node 0.12.7 and sails 0.11.2 I believe.  This crash did seem to be greatly reduced when using sails 0.12.0-rc3, but not totally eliminated, but also the problem seems to be more of an express/node issue than sails.

**Comment by randallmeeker** [comment]
related https://github.com/balderdashy/sails/issues/3221
