### ISSUE TITLE
sails generate test?

### ISSUE THREAD

**Issue by lucaspottersky** [balderdashy/sails#3264]
Is there a command to scaffold some Unit tests? I'm following the guide here http://sailsjs.org/documentation/concepts/testing

**Comment by sgress454** [comment]
Hi @lucaspottersky, just FYI, this forum is for reporting bugs in the Sails core.  In the future for support requests please visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
There is [sails-generate-test](https://github.com/balderdashy/sails-generate-test)...it looks like it hasn't been updated in over a year, and it's a 3rd-party module, but it's certainly worth a shot!
