### ISSUE TITLE
Why sails js can't run on port 80 and port 443 as a regular user

### ISSUE THREAD

**Issue by khmereshop** [balderdashy/sails#3265]
Hello
I try to run sails js on port 80 or port 443 as a regular user on mac or linux. I get error that said port is in use (Error: listen EACCES) but the port 80 and port 443 are available.

When I switch to my regular user to root, I can run sails on port 80 and port 443 fine. Does
anyone know how can I run sails on port 80 or port 443 as a regular standard user?

**Comment by baltag** [comment]
This is not a sails issue, it's a security issue from the operating system(linux / mac). You can find more info and solutions here: http://unix.stackexchange.com/questions/10735/linux-allowing-an-user-to-listen-to-a-port-below-1024

**Comment by mikermcneil** [comment]
@baltag :+1:  thanks!
