### ISSUE TITLE
In where setting to show SQL script?

### ISSUE THREAD

**Issue by Wizzercn** [balderdashy/sails#3267]
Want to print MySQL SQL script in debug mode.thanks

**Comment by sgress454** [comment]
Hi @Wizzercn, this forum is for reporting bugs in the Sails core.  If you need support, please post to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or [Stackoverflow](http://stackoverflow.com/questions/tagged/sails.js), or try our live [Gitter chat room](https://gitter.im/balderdashy/sails).
<hr/>
FYI this question has been [asked and answered](http://stackoverflow.com/questions/22401062/how-to-show-queries-in-console-log-using-sails) on StackOverflow.
