### ISSUE TITLE
Dash Documentation Support

### ISSUE THREAD

**Issue by McPants** [balderdashy/sails#3268]
Hey there,

I am just dropping in to ask for support to get documentation into dash, https://kapeli.com/dash

I am about to go on a plane ride and it would have been wonderful to have it all stored on my computer before I went, I bet others would find this useful too. No worries if its too much trouble.

For now I will just download the doc repo :)

**Comment by Kapeli** [comment]
A Sails docset for Dash is planned and should come soon-ish.

**Comment by tjwebb** [comment]
@Kapeli would you mind sharing your roadmap?

**Comment by Kapeli** [comment]
I don't have a roadmap.

**Comment by sgress454** [comment]
> A Sails docset for Dash is planned and should come soon-ish.

Thanks @Kapeli, we'll look forward to that.

**Comment by McPants** [comment]
<3

**Comment by RWOverdijk** [comment]
:+1: I totally missed this one!

**Comment by RWOverdijk** [comment]
I totally missed this one! Might I add, I have a license. Two actually :p
