### ISSUE TITLE
add jshint to sails

### ISSUE THREAD

**Issue by calidion** [balderdashy/sails#3269]
jslint can help us to write clean code.
please add jshint to sails.

**Comment by RWOverdijk** [comment]
@calidion Sails already uses [jshint](https://github.com/balderdashy/sails/blob/master/.jshintrc). Do you mean in your sails projects? Because that's really up to you. Not all teams follow the same conventions I'm afraid.

**Comment by calidion** [comment]
yes, but it would be nice to place one as a default convention.

**Comment by calidion** [comment]
And it would be nice too to use yeoman generator.

**Comment by RWOverdijk** [comment]
@calidion There is a [prototype](https://www.npmjs.com/package/generator-sails) for it. As to the default, I disagree. However, if you were to submit a PR with the changes, I would probably +1 it. I personally prefer having jshint added to my projects so I wouldn't mind.

**Comment by nahtnam** [comment]
+1 for jshint. There are pretty much no downsides to it.

**Comment by wulfsolter** [comment]
As @RWOverdijk said, Sails already uses JSHint

https://github.com/balderdashy/sails/blob/master/.jshintrc

**Comment by giyyapan** [comment]
I do thinks this shouldn't be default.
I'd have to disable it manually if it is , because I write coffee script :dog:

**Comment by mikermcneil** [comment]
Thanks for posting, @calidion.  Please review our [contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md).  The issue queue in this repo is for _verified bugs_ with documented features only, please;  no feature requests, questions, or commentary-- and also no bug reports about undocumented features or unofficial plugins.

Thanks so much for your help!
