### ISSUE TITLE
Sails does not work with NPM above 3.2.2

### ISSUE THREAD

**Issue by megakoresh** [balderdashy/sails#3270]
ANY npm commands inside a sails installation when using NPM above `3.2.2` fail with the following:
```javascript
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.5
3 info using node@v4.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack TypeError: Cannot set property 'lodash' of undefined
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:94:36
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\dezalgo\dezalgo.js:17:12
8 verbose stack     at RawTask.call (C:\Program Files\nodejs\node_modules\npm\node_modules\asap\asap.js:40:19)
8 verbose stack     at flush (C:\Program Files\nodejs\node_modules\npm\node_modules\asap\raw.js:50:29)
8 verbose stack     at doNTCallback0 (node.js:407:9)
8 verbose stack     at process._tickCallback (node.js:336:13)
9 verbose cwd D:\WebMatrix\mstest1337
10 error Windows_NT 6.1.7601
11 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
12 error node v4.0.0
13 error npm  v3.3.5
14 error Cannot set property 'lodash' of undefined
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```
It seems to only concern Sails apps: installing anything globally or in other directories works fine.
There is [already an issue in the npm repo](https://github.com/npm/npm/issues/9676#issuecomment-143727143) about this, but I thought, since it's specific to Sails, I'd post it here.

**Comment by wulfsolter** [comment]
Update npm to 3.3.4
npm install -g npm@latest

**Comment by megakoresh** [comment]
I did test it with every version before posting. 3.2.2 is the highest where this error does not occur. However it does not occur on projects that were created with 3.2.2 (with flat node_modules) and THEN when I upgrade to 3.3.4, this error does not occur. However upgrading then breaks `sails new`. It then complains `commander` could not be found.

This happens if you take a project with npm 2.14.x -style nested dependencies and then upgrade npm to a version higher than 3.2.2.

**Comment by acashjos** [comment]
+1 that

**Comment by wulfsolter** [comment]
`rm -r node_modules && npm install`  is the modern version of "Have you tried turning it off and back on again." 

Node and npm are still quite new, and occasionally there are still kinks to be ironed out. Pretty frustrating when npm's own updating tools don't catch it though!

This problem has even been memefied a few times: 
https://twitter.com/bkonkle/status/646773488263393281
https://twitter.com/matixmatix/status/601006334146957313
http://cdn.meme.am/instances/500x/50936261.jpg

**Comment by sgress454** [comment]
> rm -r node_modules && npm install is the modern version of "Have you tried turning it off and back on again."

Amen to that.  Besides venting frustration, is there anything we can actually do here, or can we close this out?

**Comment by acashjos** [comment]
Whoa, that works

**Comment by wulfsolter** [comment]
@sgress454 Afraid not really, the npm devs are aware of it and hindsight is a glorious thing. While npm is not as mature a package manager as apt/yum, I have to admit to being very impressed at how well semantic versioning has worked in practice in a very short time. Debian/RHEL have been around for ~15 years, it wasn't too long ago where an `apt-get upgrade` still broke my display manager and I'd boot to console only with no WiFi. I can't see this as being the last time npm breaks but compared to the "early days", npm has matured very rapidly.

[NodeOS](http://node-os.com/) is coming to a desktop near you /jk :p

@megakoresh Sorry for your troubles, and the threadjacking, is your issue solved? If not, we are here to help.

**Comment by megakoresh** [comment]
I have been testing it under a lot of different conditions, and yeah. Reinstalling EVERYTHING with the new npm after upgrading it with `windows-npm-upgrade` and THEN `npm install -g npm` (if you only do one of them, it still breaks), then removing node_modules (both global and local for each project), then doing `npm install` for all modules does seem to be working as intended. This seems to be a problem with npm updating not-so-gracefully so you can go ahead and close this issue, it should just remain at npm.
