### ISSUE TITLE
beforeCreate is called before checking the unique validation

### ISSUE THREAD

**Issue by jetsonjohn** [balderdashy/sails#3271]
`beforeCreate` callback is called before checking the unique validation. 

for example: 

`product.js`

```
attributes: {
  name: {
    type: 'string',
    unique: 'true'
  }
},
beforeCreate: function(values, cb) {
  console.log('beforeCreate');
  return cb();
}
```
when I run the code `beforeCreate` is called before checking the unique validation. 

I need to add some data to the elasticsearch from `beforeCreate` callback. What happened to me is that before firing the unique validation error the `beforeCreate` is called and the data is indexed to elastic. According to the docs `beforeCreate` is called only after the completing the `beforeValidate` and `afterValidate` callbacks

I am using `sails-mysql` adapter.

**Comment by particlebanana** [comment]
The `unique` validation doesn't do a query before your query is executed to check uniqueness, this would slow everything down and not be transactional anyway. When you define an attribute as unique Waterline instructs the adapter to create a unique index on that attribute. In this case you should move the call to `afterCreate` or inside your controller method.

**Comment by jetsonjohn** [comment]
@particlebanana For example `values.records`. The `records` is not saving in the sails database only to the elastic database. So it will not be available in the `afterCreate` values.

**Comment by randallmeeker** [comment]
@jetsonjohn your confusion comes from bad documentation. Technically `unique` is NOT a validation as it is merely a DB constraint. If you approach the problem with this mindset, @particlebanana suggestion makes the most sense. 

However, this issue could be re-opened as it does show a glaring omission in the documentation.
