### ISSUE TITLE
Email validation not working in v0.11.2?

### ISSUE THREAD

**Issue by robgrimball** [balderdashy/sails#3274]
I have the following model : 

module.exports = {

    attributes: {
        name: {type: 'string', required: true, unique: true, notNull: true, notEmpty: true},
        email: {type: 'string', email: true},
    },

    beforeValidate: function (onCallGroup, next) {
        if (onCallGroup.name) {
            onCallGroup.name = bleach.sanitize(onCallGroup.name);
        }

        next();
    }

};

As you can see the email is of type string with email set to true.  I make a blueprint call to create one of these models with any valid email address (ie: test@test.com, other actual email addresses), and sails is reporting back an email validation error.  

response.error.invalidAttributes.email[0].message = "email" validation rule failed for input: 'test@test.com'
response.error.error: "E_VALIDATION"

Personally always thought it should be something like error.code or error.errorCode, error.error just seems confusing.  But I guess it's a standard now everyone relies on now and is not germaine to this issue.

**Comment by snowbay** [comment]
Try this
```javascript
email: {type: 'email'},
```
instead of 
```javascript
email: {type: 'string', email: true},
```

**Comment by robgrimball** [comment]
Worked great, thanks @snowbay !
