### ISSUE TITLE
QueryString with multiple values

### ISSUE THREAD

**Issue by tiagoovieira** [balderdashy/sails#3278]
I'm making GET request to an api via curl to an endpoint with multiple querystring, like 
`/endpoint?foo=1&bar=1`

I went through the sails documentation and can't find a way to get the value of bar. Any ideas?

**Comment by giyyapan** [comment]
Not sure I got what you mean, but I guese this is what you need
```javascript
// in your controller
endpoint:function(req, res, next){
  var foo = req.param('foo');
  var bar = req.param('bar');
  //or get all params as an object
  var params = req.allParams();
}
```
Here's the doc: http://sailsjs.org/documentation/reference/request-req/req-param
and here: http://sailsjs.org/documentation/reference/request-req/req-all-params

**Comment by tiagoovieira** [comment]
I added `console.log("BAZINGA: " + foo + ", " + bar);` to that endpoint controller but what gets printed in the console is `BAZINGA: 1, undefined`

**Comment by giyyapan** [comment]
Can you post all of your code in your controller? and those in your config/routes.js if you have.

**Comment by tiagoovieira** [comment]
````endpoint: function(req, res) {
  var foo = req.param('foo');
  var bar = req.param('bar');

  console.log("BAZINGA: " + foo + ", " + bar);
  res.json({
    hey: "Hello World"
  });
}````

**Comment by giyyapan** [comment]
Strange..

Are you sure you have both foo and bar in you url? Can you `console.log(req.url)` and see if the url is correct?

I've just confirmed that req.param() will work for url like `/endpoint?foo=1&bar=1` in my environment.

**Comment by tiagoovieira** [comment]
well, I feel like an idiot, I was doing the wrong curl command `curl -XGET url/endpoint?foo=1&bar=2` and should've been `curl -XGET 'url/endpoint?foo=1&bar=2'`

**Comment by giyyapan** [comment]
Well, glad to see you figure it out  :smile_cat:

**Comment by mikermcneil** [comment]
@tiagoovieira @giyyapan :+1:
