### ISSUE TITLE
Request get repeated twice or more in many scenarios

### ISSUE THREAD

**Issue by Sokkary** [balderdashy/sails#3279]
A request to SailsJs get repeated twice or more in the following cases:
1- If the server crashed/restarted and there is pending requests that didn't return
2- If the request timeout before we send response

Reproduce scenario:
1- Create a long running method on server
2- Do request to that method
3- Ctrl + C to stop the server (or wait till request timeout before sending response)
4- Start the server again
5- Watch (after the first request timeout,  same method will get called automatically again)

Note:
- Request done by angular application via http service call
- CORS is enabled on the server

**Comment by sgress454** [comment]
Sails doesn't have any crazy request cacheing mechanism that would somehow survive server restarts, unless you built it yourself.  If your request is getting repeated, it's happening on the front end--check the network tab in your browser!

**Comment by Sokkary** [comment]
I did my checks before raising the issue. I monitored the requests going from the client and always one request is sent!

I added a timestamp param to each request (interception) and I repeated the scenario. I got the same request with same timestamp repeated twice in 2  the scenarios that I mentioned before.

Try to do sample example as I mentioned and you'll get that strange behaviour!!!

**Comment by netrevisanto** [comment]
i'm having the same problem. Request gets repeated if it runs for a while.
The answer when the request is re-processed on the server, noticed in the client as

net::ERR_EMPTY_RESPONSE

But it is processing in the server, a copy of the failed request.

**Comment by discordance** [comment]
Have exactly the same issue here for long requests. Checked network tab and only one request is sent. Also did the timestamp check.

**Comment by luispeerez** [comment]
Same problem here, because of the long response time, sails is executing my controller action twice or more.

**Comment by mikermcneil** [comment]
@netrevisanto @discordance @luispeerez Thanks for posting your experiences everyone.  Hmm... I'm having a hard time tying the cause and effect together without more context.  Would someone please recreate this in a vanilla Sails app in a repo?  Please create it as a new issue with a link to the repo, all relevant version information, and a link back to this original issue for posterity.  Thanks a lot!


> @Sokkary In case this helps, in the instructions to reproduce that you mentioned, it sounds like your browser might be automatically resending the request (see http://stackoverflow.com/a/19697278/486547)

**Comment by mikermcneil** [comment]
@Sokkary @netrevisanto @discordance @luispeerez If it turns out this is because of http://stackoverflow.com/questions/15155014/inconsistent-browser-retry-behaviour-for-timed-out-post-requests/19697278#19697278, it seems like you might want to check out https://nodejs.org/api/http.html#http_message_settimeout_msecs_callback
