### ISSUE TITLE
"sails new testProject" with latest NPM

### ISSUE THREAD

**Issue by randallmeeker** [balderdashy/sails#3281]
Windows 10
Node 4.1
Npm 3.3.5

After executing `sails new testProject`

I had to remove node_modules and run npm install inside testProject before I could install any additional modules.

**Comment by akd3vs** [comment]
Ubuntu works fine with lastest version

**Comment by randallmeeker** [comment]
Hmm, might be my stack. I'll check ios

**Comment by danielbaak** [comment]
looks like it's an issue with npm 3.3.x. I've got it on linux mint (ubuntu based)

**Comment by randallmeeker** [comment]
Just curious, does the same solution work for you? 
> delete node_modules and then run npm install

**Comment by danielbaak** [comment]
confirmed. 

npm install in sails works on npm 3.3.5 (mint 17.1 i.e. ubuntu 14.04) after doing rm -r node_modules.

**Comment by sanderboom** [comment]
> delete node_modules and then run npm install

confirmed on Arch Linux 

```bash
λ npm --version                                                                                           │
3.3.4 
λ node --version                                                                                          │
v4.1.1    
```

Thanks!

**Comment by sgress454** [comment]
Thanks y'all, we're aware of the issue and are working on it (has to do with NPM 3 and symlinks).  In the meantime the solution is to just remove the `node_modules` folder completely after doing `sails new`, and then run `npm install`.

**Comment by sgress454** [comment]
Ok, this is patched with the new version of [sails-generate-new](https://github.com/balderdashy/sails-generate-new) (v0.10.22).  New installs of Sails will get automatically, otherwise you'll need to update it.
