### ISSUE TITLE
Is there a way to auto publish changes in models?

### ISSUE THREAD

**Issue by pedropapa** [balderdashy/sails#3282]
Hello,
I wonder if there is a way to auto publish changes in models, let me give you a example:

```
competitiveServer.findOne({status: 'readyToGo'}).exec(function(err, found) {
      if(!err) {
        if(typeof found == 'object') {
            found.matchId = matchId;
            found.save(function(err, saved) {
                console.log('saved');
            } else {
                 console.log('not saved!');
            }
        }
     }
}
```

I want sails to call ```competitiveServer.publishUpdate(found[0].ID, found);```automatically when save(), update(), destroy() and create() functions in model are called.

there is a autoWatch propertie in blueprints configuration, is there like a ```autoPublish``` configuration? or I really have to call the pubsub functions in all model changes?

**Comment by pedropapa** [comment]
Searching inside blueprint code I found that in update.js, create.js, find.js and add.js files (inside node_modules/sails/lib/hooks/blueprints/actions folder) is a code block that do exactly what I want:

```
// If we have the pubsub hook, use the Model's publish method
      // to notify all subscribers about the update.
      if (req._sails.hooks.pubsub) {
        if (req.isSocket) { Model.subscribe(req, records); }
        Model.publishUpdate(pk, _.cloneDeep(values), !req.options.mirror && req, {
          previous: matchingRecord.toJSON()
        });
      }
```

how do I enable this pubsub hook?

**Comment by sgress454** [comment]
Hi @pedropapa, just FYI, this forum is for reporting bugs in the Sails core.  In the future for support requests please visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
 <hr/>
The hook is enabled by default.  Please see the [documentation for resourceful pub-sub](http://sailsjs.org/documentation/reference/web-sockets/resourceful-pub-sub).
