### ISSUE TITLE
Update doesn't updates the database

### ISSUE THREAD

**Issue by pulkitnandan** [balderdashy/sails#3284]
Certainly as per documentation of .update here http://sailsjs.org/documentation/reference/waterline-orm/models/update there's something missing which stops my model to be updated, if it would be because you didn't mentioned this http://sailsjs.org/documentation/reference/waterline-orm/records/save in updates documentation then I'm just perplexed with the nomenclature here, does .save refers to commit in sql, or this save is luxury to be used with actions such as find, create, destroy but update calls save implicitly and I have something wrong in my model.

I have usecase of using a Model with no unique key and thus had to check manually using beforeCreate whether its alreadyPresent or not, if its not present I simply do cb() .i.e. proceed with normal creation of record else do a diff between object returned in find and object which is to be inserted, if diff returns exactly same, I return error 500 .i.e. pass non null argument to cb(), but when I found a particular field which is not as returned object I assign its id to new Object and launch a update query and this paradoxically creates two object. I simply donot understand this.

**Comment by pulkitnandan** [comment]
This is my code and it certainly doesn't follow the documentation 

beforeCreate: function(values, cb) {

    Filing.find(values).exec(function(err, findRes) {

        if (err || findRes.length == 0) cb(err);
        else {


            var getOneRecord = findRes.pop();
            for (var prop in values) {
                if (values.hasOwnProperty(prop))
                    getOneRecord.prop = values.prop;

            }
            getOneRecord.save(
                function(errr, s) {
                    console.log(errr, s);
                });
        }
        cb("Duplicate");
    });

}

**Comment by pulkitnandan** [comment]
This another implementation to update the record. But doesn't works at all., both of them create new records.  beforeCreate: function(values, cb) {

     Filing.find(values).exec(function(err, findRes) {

         if (err || findRes.length == 0) cb(err);
         else {


             for (var prop in values) {
                 if (values.hasOwnProperty(prop))
                     findRes[0].prop = values.prop;

             }

             Filing.update(findRes).exec(function(errr) {
                 console.log("Error in updating", err);

             });

             cb("Diplicate");
         }
     });

 }

**Comment by pulkitnandan** [comment]
Currently I'm achieving what I want to using this

   beforeCreate: function(values, cb) {

       Filing.find(values).exec(function(err, findRes) {

           if (err || findRes.length == 0) cb(err);
           else {


               Filing.destroy(findRes.id).exec(function(errr) {
                   console.log("Error in updating", err);

               });

               cb();
           }
       });

   }

Which creates a new id, the only difference it makes.

**Comment by sgress454** [comment]
Hi @pulkitnandan, just FYI, this forum is for reporting bugs in the Sails core.  In the future for support requests please visit [StackOverflow](http://stackoverflow.com), our [Google Group](https://groups.google.com/forum/#!forum/sailsjs) or our [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
<hr/>
There's lots of issues here, and it's not really clear what you're trying to do: the `.find()` will find records with _exactly_ the values you specify, so there won't be anything that needs updating.  You're always just setting the properties of the retrieved record to the same value that they already hold.  Your use of `.update()` is incorrect; please [see the documentation](http://sailsjs.org/documentation/reference/waterline-orm/models/update) (it needs two arguments).  Also make sure you are setting [`autoPK` to `false`](http://sailsjs.org/documentation/concepts/models-and-orm/model-settings#?autopk) if you want a model with no unique ID.
