### ISSUE TITLE
OData support via sails-odata module?

### ISSUE THREAD

**Issue by htammen** [balderdashy/sails#3288]
Hi,
I'm very new to sails and found it because there was this sails-odata module which I need for my project. After setting up a project and installing sails-odata I can't get it running. When I had a look at the sources of the module it looks more like an empty shell than like a working module. 
Can you please tell me which state the module has and if it should already do it's job how I can use it?

Thanks and regards
Helmut

**Comment by sgress454** [comment]
Hi Helmut!  For support for third-party modules (rather than [officially-supported adapters](https://github.com/balderdashy/sails#compatibility)), you'll need to contact the author of the module directly--in this case @TheSharpieOne.
