### ISSUE TITLE
Does moodle support scorm 2004 sequncing and navigation ?

### ISSUE THREAD

**Issue by jigneshnavsoft** [balderdashy/sails#3291]
Does moodle support scorm 2004 sequncing and navigation ?

if yes which version and demo link.

awaiitng

**Comment by particlebanana** [comment]
Ummm what? This isn't anything related to Sails or the Sails ecosystem.

**Comment by mikermcneil** [comment]
:+1:

**Comment by randallmeeker** [comment]
take care men

**Comment by mikermcneil** [comment]
@randallmeeker hahahaha
