### ISSUE TITLE
token mismatch after session destroy 

### ISSUE THREAD

**Issue by frutality** [balderdashy/sails#3297]
Hello.

I'm trying to build very basic registration and authentication in my app.

Registration, login and logout works fine, but after logout, if I'll do ANY post-query, I'll get an error "CSRF mismatch". Also, I've tried to get "/csrfToken" after logout. It returns me correct token, but this token is also "mismatched".

More at http://stackoverflow.com/questions/32907860/sailsjs-csrf-mismatch-after-logout-and-getting-new-csrftoken

Can't solve this problem for a week already :/

**Comment by sgress454** [comment]
@frutality, looking into this for you.

**Comment by sgress454** [comment]
Answered on StackOverflow, let's continue the discussion there as this forum is for bug reports only.

**Comment by sgress454** [comment]
@frutality just FYI, looked into this and provided an actual answer on StackOverflow (just corrected).

**Comment by frutality** [comment]
@sgress454 yes, thanks, it worked. Could you please take a look at one question about your answer? It's already on SO.
