### ISSUE TITLE
Upgrade lodash

### ISSUE THREAD

**Issue by ArsalanDotMe** [balderdashy/sails#3298]
Lodash has been on the 3.x.x major version for a while now and its time its upgraded because most of the examples and documentation available online is for version 3 which does not always work the same in the version 2 that sails uses.

**Comment by sgress454** [comment]
> version 3 which does not always work the same in the version 2 that sails uses.

Yup, that's why we haven't upgraded yet.  If you don't like the version that Sails globalizes for you, you can turn it off in `config/globals.js` and install a local version of Lodash for your app!
