### ISSUE TITLE
res.view filename case sensitivity

### ISSUE THREAD

**Issue by phillee** [balderdashy/sails#3299]
I have an action in my AppController called linkJs, which renders the corresponding view in /views/app/linkJs.jade

This works fine locally (Mac), but on my production environment, an Ubuntu machine, the view doesn't get automatically found. I have to specify it with res.view('app/linkJs'). However, res.view() works with filenames that are all lowercase.

**Comment by sgress454** [comment]
Thanks @phillee, updated the [`res.view` documentation](https://github.com/balderdashy/sails-docs/commit/7faf755bf536e2910e5c153207c711e79b1f524f) with a note about saving views in lowercase.
