### ISSUE TITLE
Question: Is there a way to turn off case insensitive querying of waterline?

### ISSUE THREAD

**Issue by shamasis** [balderdashy/sails#3304]
We are in urgent need to turn off this feature of case insensitive querying. 

I see that `waterline-criteria` checks for a `caseSensitive` flag all over the place and inline docs say that this is for databases that does not support case insensitive querying.

What would be the way to turn on this flag?

PS: I am okay to fork and do the changes.

**Comment by kennysmoothx** [comment]
Have you considered manual queries? 

Per the documentation (http://sailsjs.org/documentation/concepts/models-and-orm/query-language)


> Case-sensitivity
> All queries inside of Waterline are case-insensitive. 

> This allows for easier querying but makes indexing strings tough. 

> This is something to be aware of if you are indexing and searching on string fields.

> Currently, the best way to execute case-sensitive queries is using the .native() or .query() method.

**Comment by shamasis** [comment]
Manual queries would be an anti-pattern. It would be prone to issues, will be difficult to maintain and would defeat the whole purpose of an ORM by locking the code base with a database type. 

The reason we need case sensitive queries because `LOWER` function in MySQL causes queries to slow down by a huge factor - even on indexed columns. 

Anyway, thanks for help. We've forked and edited sails-mysql to send `wlNext: {caseSensitive:true}` in `sqlOptions`. This has turned off the case sensitive querying of `waterline-sequel`.

**Comment by dkatavic** [comment]
We had the same problem, we have solved it with setting models attribute property "index" to true, example:

    email: {
        type: 'string',
        index: true
    },

If there is index property set, sails-mysql will not force `LOWER` function which breaks index

**Comment by particlebanana** [comment]
@shamasis Waterline queries are case-insensitive by default. This stems from the early days of Waterline where MySql was the only adapter and it's default collation was case-insensitive. Obviously this is not the best choice when querying databases with strings that have been indexed.

The `wlNext` flag is a way for adapters to expand their functionality without breaking existing apps. So far it is only fully implemented in the sails-postgresql adapter but could be added to other adapters with some work. 

Your usage here allows this to work in MySql with a few caveats. If you are using the default collation of `latin1_swedish_ci` with the `wlNext` flag turned on, a search for `{ name: 'sam' }` will return results for both `Sam` and `sam` but any indexes on the `name` column will be used. If you would like the actual values `Sam` and `sam` to be treated differently you will need to set the collation to something like `latin1_general_cs`.

**Comment by shamasis** [comment]
@particlebanana - super thanks for the reply. I went through the sails-mysql latest - seems like it's fully working for wlNext. I will continue to test it further and report / send PR, if anything is broken.
