### ISSUE TITLE
[Feature] GraphQL Support

### ISSUE THREAD

**Issue by iamchathu** [balderdashy/sails#3309]
How about creating easy way to develop the API as GraphQL server using SalisJS?

**Comment by Aurelsicoko** [comment]
At Strapi, we developed a [Waterline GraphQL adapter](https://github.com/wistityhq/waterline-graphql). This works with our stack, I'm pretty sure it will work with Sails too.

**Comment by crobinson42** [comment]
Outstanding!!!!

**Comment by tjwebb** [comment]
see also: https://github.com/balderdashy/waterline-docs/pull/99
