### ISSUE TITLE
Inconsistency with Fields in file upload. Seems Skipper Issue

### ISSUE THREAD

**Issue by alvajindia** [balderdashy/sails#3310]
I have a form for which enctype is multipart/form-data. I am using skipper for file upload to s3. The code works perfectly in my local system, but in EC2 instance & Azure instance where my dev & test version are hosted, i am not getting all the form fields in the controller. Top few fields are there and others are not there. I tried putting file type field at the bottom, still no luck. There is a real inconsistency in the number of fields received, sometime its firs 10, sometime first 14, or 16 or whatever...Tried removing the file input type from the form, but still the issue is there. But when i removed the enctype="multipart/form-data" attribute from the form, everything worked perfect, with no file upload. What is the issue ?

**Comment by tjwebb** [comment]
Are you using SSL? If so, this thread is worth looking at: https://github.com/balderdashy/skipper/issues/71#issuecomment-89334994

Also relevant: https://github.com/balderdashy/skipper#the-big-assumption-field-order

**Comment by alvajindia** [comment]
this cannot be closed...its not issues with neither of the above...i have tried all those possbile things..

**Comment by tjwebb** [comment]
Either way, it's an issue that belongs in the Skipper repository. Please provide a complete example, with data, stacktraces, everything. We need all the information in order to debug the issue.

**Comment by alvajindia** [comment]
This was not resolved, but unluckily, i had to go skip this method and do AJAX based file upload and just pass the returned url to save in my database.

It was quite strange that i didn't had this issue in my local system, but in 2 different servers where i had deployed the same code. Quite strange it was. The form is long with many fields and enctype was multipart.  Even when i removed the input type of file, still the issue was there. Only was it worked was when i remove multipart enctype, but then file upload won't work. Still, what's strange is what it worked on local. I tried re-installing the app in both of my servers, with different version of skippper/sails etc. but with no luck. Anyway as i didnt had the luxury of time, i had to move on. I will be back with it once i a get some freetime.
