### ISSUE TITLE
is it possibe use Mognoose insted of Waterline (ORM)?

### ISSUE THREAD

**Issue by Mirodil** [balderdashy/sails#3311]
Is it possibe use Mognoose insted of Waterline (ORM)?

**Comment by artyomtrityak** [comment]
http://laurentschaffner.com/blog/from-waterline-to-mongoose-in-sails/

**Comment by Mirodil** [comment]
thanks very useful article, but I can assume it(in the arcile) disable the main features which I what to use.

**Comment by tjwebb** [comment]
It is possible, but not without writing some code. If you'd like to use the Waterline Adapter system to build a Mongoose adapter, then you can use Mongoose directly with Sails.

If there are some particular features in Mongoose that you'd like to see supported by the Waterline MongoDB adapter, feel free to file an issue here: https://github.com/balderdashy/sails-mongo

**Comment by mikermcneil** [comment]
@artyomtrityak thanks for posting that article!

@Mirodil I'm working on an example override and core hook documentation as part of v0.12 release at the end of this month.  A lot of folks have asked for this, and I think it provides some much needed flexibility and comfort.  Plus, even when you are using Waterline, it is helpful to be able to try out different versions of the ORM or experimental features by shimming the hook.  The rest of the team and I spent a long time working through our v1 plans last week, and long term, we see the ORM hook taking over some of Waterline's more mundane responsibilities, including auto-migrations.  We'll post updates at http://blog.sailsjs.org.

**Comment by mikermcneil** [comment]
@Mirodil @artyomtrityak OK!  Took me longer than expected, but at last here we are.  Here is an override of the ORM hook that uses Mongoose:  https://github.com/mikermcneil/sails-hook-orm-mongoose  The README file has install instructions, and at the bottom, there's a link to a really simple example app in a separate repo that uses the hook.
