### ISSUE TITLE
Defaulting configuration to `development` leads to possible catastrophe

### ISSUE THREAD

**Issue by LeBlaaanc** [balderdashy/sails#3313]
It seems quite easy to fall under a trap where you could inadvertently wipe/alter your whole database because you did not specify `NODE_ENV=production` and explicitly set `sails.config.models.migrate = safe` in production.js if you were to set `sails.config.models.migrate = drop/alter` in development.js when running sails on a production server.

I'd rather no files in /configs/env/xxx.js are read unless an environment is explicitly defined (via CLI or NODE_ENV).

**Comment by tjwebb** [comment]
> and explicitly set sails.config.models.migrate = safe

This is not needed, migrate: safe is hardcoded when NODE_ENV=production.

Moreover, when migrate is not set, Sails will not even boot until you explicitly set a migrate setting. There are multiple safeguards in place to prevent data loss.

> because you did not specify NODE_ENV=production 

Yea, if you don't configure things correctly, then things aren't configured correctly. And if you don't back up your data in production, then your data isn't backed up. These conditions can certainly lead to major problems. There's only so much Sails can do to save you from yourself.
