### ISSUE TITLE
Server crashing on file upload s3, req aborted and uncaught unspecified error occuring frequently.

### ISSUE THREAD

**Issue by vbharatha** [balderdashy/sails#3315]
We are facing an issue on using skipper for uploading files, server being crashed on file upload randomly by 2 ways as follows
* request aborted ( this being fixed in skipper v0.5.4 but the current version what we are using sails v11.0 had skipper version of 0.5.5 ) but still we are facing this issue
* uncaught unspecified error which is being occured sometimes. 

NOTE: we are using skipper-s3 
Could you please address the issue, we are facing a huge problem on production server.

**Comment by tjwebb** [comment]
You've provided nowhere near enough detail for us to diagnose whatever problem you're having. Moreover, please file this in the skipper or skipper-s3 repositories.
