### ISSUE TITLE
start up is slow

### ISSUE THREAD

**Issue by abc306396358** [balderdashy/sails#3316]
i have more than 70 controllers , route binding takes 6 second,how can i speed up??

**Comment by crobinson42** [comment]
This is a common experience with large sails apps.

You can switch to Gulp ;-)

**Comment by crobinson42** [comment]
This is a common experience with large sails apps.

**Comment by tjwebb** [comment]
> i have more than 70 controllers , route binding takes 6 second,how can i speed up??

1. You can configure blueprints to bind fewer routes: http://sailsjs.org/documentation/reference/configuration/sails-config-blueprints

2. You can explicitly define only the routes you want to bind: http://sailsjs.org/documentation/reference/configuration/sails-config-routes

If you really do want to bind every one of those routes, then that's just how long it takes.
