### ISSUE TITLE
Cannot disable sockets hook when deps are installed with npm 3

### ISSUE THREAD

**Issue by Alaneor** [balderdashy/sails#3317]
The `sockets` hook is documented to be disable-able via a *.sailsrc* file. However, if the project dependencies are installed with npm 3, they are flattened into the project's *node_modules* folder. This causes Sails to detect it as a user hook (because it has a `"isHook": true` in its *package.json*) and **load it anyway.**

I have not checked in much detail how the hook loading works, but it seems core hooks are loaded independently of user hooks. A solution might be to treat them all equal - i.e. get the list of core hooks, get the list of user hooks, apply configuration from *.sailsrc* and load them.

As a nice side-effect, we would be able to disable installed user hooks via *.sailsrc*.

**Comment by tjwebb** [comment]
I think this is resolved in #3276

**Comment by Durindo** [comment]
The issue has been resolved on master (0.12.x I believe), but is there any plan to resolve it on stable (0.11.x) ?

**Comment by levity** [comment]
Looks like [the fix](https://github.com/balderdashy/sails/commit/6b7e64847b5fc21cd03bb4f6b848cc4bedd67f5d) didn't make it in until 0.12.0-rc5.

**Comment by dcolley** [comment]
For me `"pubsub":false,"sockets":false` in .sailsrc or sails/hooks.js is not working.

> sails v0.12.13, node v7.4.0.

I simply added this to config/sockets.js

    beforeConnect: function(handshake, cb) {
      return cb('socket connections not allowed!', false);
    },
