### ISSUE TITLE
custom blueprint does not work with prefix

### ISSUE THREAD

**Issue by wfpaisa** [balderdashy/sails#3318]
config/blueprints.js

I used a custom blueprints does not work, 

example:

```
  prefix: '/api',
``` 

route:
```
'GET /api/user/foo': {blueprint: 'foo'}
```
log:
```
verbose: Sending 404 ("Not Found") response: 
 No record found with the specified `id`.
```

**Comment by tjwebb** [comment]
The `blueprint` property in the route config should represent a real blueprint action. [One of these](http://sailsjs.org/documentation/reference/blueprint-api?q=blueprint-routes#?blueprint-actions):
- find
- findone
- create
- update
- destroy
- populate
- add
- remove

For more info, see the docs: http://sailsjs.org/documentation/concepts/routes/custom-routes#?blueprint-target-syntax
