### ISSUE TITLE
unable to overwrite sails.config.paths

### ISSUE THREAD

**Issue by japel** [balderdashy/sails#3325]
Hello there,

I'm not able to overwrite sails.config.paths.
I'm trying to overwrite it on my env config, but moduleloader hook seems to ignore my config.
What could I be doing wrong?

Thanks in advance!

japel

**Comment by japel** [comment]
This might be a bug, or just wrong documentation, but:
as opposed to https://github.com/balderdashy/sails/blob/master/lib/hooks/moduleloader/README.md
where it says:
"This hook loads modules from your configured directories in sails.config.paths."
Sails ignores any config changes and always loads default paths.

The only way to overwrite those seems to be to change them in .sailsrc file

**Comment by crobinson42** [comment]
post a gist or jsfiddle of your code so we can see what you’re doing.

**Comment by tjwebb** [comment]
Issue will be re-opened with OP can provide a complete example.

**Comment by japel** [comment]
reopening this with an easy to test repo:

https://github.com/japel/sailsConfigPathsTest

files added:

./config/paths.js
```javascript
module.exports.paths = {
  "models": "api/my/new/models/path"
};
```

api/my/new/models/path/User.js
```javascript
module.exports = {

  attributes: {
    name: 'string',
    age: 'integer',
    active: 'boolean'
  }
};
```

how to test:

- clone
- npm install
- sails console
- > console.log(sails.config.paths);

outputs:

```javascript
{ models: 'X:\\sailsConfigPathsTest\\api\\models',
  tmp: 'X:\\sailsConfigPathsTest\\.tmp',
  config: 'X:\\sailsConfigPathsTest\\config',
  controllers: 'X:\\sailsConfigPathsTest\\api\\controllers',
  policies: 'X:\\sailsConfigPathsTest\\api\\policies',
  services: 'X:\\sailsConfigPathsTest\\api\\services',
  adapters: 'X:\\sailsConfigPathsTest\\api\\adapters',
  hooks: 'X:\\sailsConfigPathsTest\\api\\hooks',
  blueprints: 'X:\\sailsConfigPathsTest\\api\\blueprints',
  responses: 'X:\\sailsConfigPathsTest\\api\\responses',
  views: 'X:\\sailsConfigPathsTest\\views',
  layout: 'X:\\sailsConfigPathsTest\\views\\layout.ejs',
  public: 'X:\\sailsConfigPathsTest\\.tmp\\public' }
```
