### ISSUE TITLE
Only "first-level" installable hook modules are loaded

### ISSUE THREAD

**Issue by mlenormand** [balderdashy/sails#3328]
Only "first-level" installable Sails hooks (installed directly in the node-modules directory of the app) are loaded by Sails but not deep hooks in the subfolders.

My app is not depending directly of the sails module but rather to a custom module (let's name it "myplatform") that depends of sails, so my installable hook is located for example in the myapp/node_modules/myplatform/node_modules/mysailshook.

I tried with an higher 'depth' parameter in the sails/lib/hooks/moduleloader/index.js#nodeModulesFolder() function
but it doesn't work, i.e. only the first-level hooks are loaded but deep hooks are not.

Note : My package.json hook files are correctly configured : 

``
  "sails": {
    "isHook": true
  },
``

How can I solve this problem ?

**Comment by tjwebb** [comment]
You should consider splitting your hook out as a separate module and requiring it as a dependency in both Sails apps.

> my installable hook is located for example in the myapp/node_modules/myplatform/node_modules/mysailshook.

In the meantime, you can specify the module to require if your hook is deep in your dependency tree. So just set this value in your .sailsrc file:

```json
{
  "hooks": {
    "myhook": "myapp/node_modules/myplatform/node_modules/mysailshook"
  }
```
