### ISSUE TITLE
Cannot set property '.(├©rigindex)' of null after re-lifting server

### ISSUE THREAD

**Issue by megakoresh** [balderdashy/sails#3335]
I purged my database, then lifted the server again after updating from the github repo and now whenever I try to lift, it crashes with this message. If I delete `localDiskDb.db` from .tmp folder, it lifts normally once, and then fails with this error again. I noticed in the localdisk DB it actually creates an null entry for whatever reason:
```javascript
"data": {
  "asset": [
    null
  ]
},
"schema": {
...
```
Removing it has the same effect: lifts once, recreates the `null`, then fails to lift next time. Noticed this problem already existed before. Seems it is back now. Error log:
```javascript
D:\WebMatrix\mstest1337\node_modules\waterline-criteria\lib\query.js:56
    tuple[INDEX_IN_ORIG_DATA] = i;
                              ^

TypeError: Cannot set property '.(├©rigindex)' of null
    at D:\WebMatrix\mstest1337\node_modules\waterline-criteria\lib\query.js:56:31
    at Function.forEach (D:\WebMatrix\mstest1337\node_modules\waterline-criteria\node_modules\lodash
\dist\lodash.js:3298:15)
    at query (D:\WebMatrix\mstest1337\node_modules\waterline-criteria\lib\query.js:55:5)
    at Database.select (D:\WebMatrix\mstest1337\node_modules\sails-disk\lib\database.js:316:19)
    at Object.module.exports.adapter.find (D:\WebMatrix\mstest1337\node_modules\sails-disk\lib\adapt
er.js:86:28)
    at module.exports.find (D:\Nodejs\node_modules\sails\node_modules\waterline\lib\waterline\adapte
r\dql.js:120:13)
    at afterDescribe (D:\Nodejs\node_modules\sails\node_modules\waterline\lib\waterline\adapter\sync
\strategies\alter.js:103:10)
    at wrapper (D:\Nodejs\node_modules\sails\node_modules\waterline\node_modules\lodash\index.js:360
2:19)
    at applyInOriginalCtx (D:\Nodejs\node_modules\sails\node_modules\waterline\lib\waterline\utils\n
ormalize.js:421:80)
    at wrappedCallback (D:\Nodejs\node_modules\sails\node_modules\waterline\lib\waterline\utils\norm
alize.js:320:18)
    at callback.success (D:\Nodejs\node_modules\sails\node_modules\waterline\node_modules\switchback
\lib\normalize.js:33:31)
    at _switch (D:\Nodejs\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\fact
ory.js:48:28)
    at D:\WebMatrix\mstest1337\node_modules\sails-disk\lib\database.js:262:5
    at Database.getCollection (D:\WebMatrix\mstest1337\node_modules\sails-disk\lib\database.js:141:3
)
    at Database.describe (D:\WebMatrix\mstest1337\node_modules\sails-disk\lib\database.js:258:8)
    at Object.module.exports.adapter.describe (D:\WebMatrix\mstest1337\node_modules\sails-disk\lib\a
dapter.js:72:28)
```
I didn't change anything in the code, by the way. Only added some frontend assets.

UPDATE: After some fiddling I determined it has to do with the database `migration: "alter"` setting. Both `safe` and `drop` do not exhibit this behaviour.

UPDATE#2: It also happens when `hook-autoreload` triggers regardless of what migration setting is used. It creates null entries every time I try to either lift, or when autoreload occurs.

UPDATE#3: It also happens after every update and delete operation (i.e. in creates that null entry at the start of data and the end of it, essentially surrounding valid entries with these nulls, which then causes the crash).

**Comment by megakoresh** [comment]
Ok I figured this out, it seems a rather complicated problem. It had to do with a function polyfill in one of my custom modules. Specifically `Array.includes(value)`. The polyfill I directly copied from MDN, here it is:
```javascript
if (!Array.prototype.includes) {
  Array.prototype.includes = function(searchElement) {
    'use strict';
    var O = Object(this);
    var len = parseInt(O.length) || 0;
    if (len === 0) {
      return false;
    }
    var n = parseInt(arguments[1]) || 0;
    var k;
    if (n >= 0) {
      k = n;
    } else {
      k = len + n;
      if (k < 0) {k = 0;}
    }
    var currentElement;
    while (k < len) {
      currentElement = O[k];
      if (searchElement === currentElement ||
         (searchElement !== searchElement && currentElement !== currentElement)) {
        return true;
      }
      k++;
    }
    return false;
  };
}
```
So I assume at some point Waterline uses the same polyfill somewhere in the code responsible for `migrate.alter` operation and since `require`s are run before ORM is loaded, it overrides that polyfill and somehow makes Waterline create null entries. 

I will close this issue, but I would be extremely interested in any ideas as to what might be wrong with the polyfill and how to avoid such behaviour in the future. This took me 2 full days to find since there are no indications of why this behaviour, and it looks like a serious error that can easily appear out of nowhere. Anyone even know where the alter code is located so that I may look at what kind of polyfill it may use?

**Comment by particlebanana** [comment]
I'm not aware of any polyfills in the codebase. We do use lodash quite a bit though, including the `_.includes` method. This is quite strange that your schema ends up as an array of null.

The migration code is [here](https://github.com/balderdashy/waterline/blob/master/lib/waterline/adapter/sync/strategies/alter.js).

The schema code is [here](https://github.com/balderdashy/waterline-schema).

**Comment by tjwebb** [comment]
@megakoresh what are the other dependencies of your project? is anything modifying the `prototype` anywhere?

**Comment by megakoresh** [comment]
@tjwebb Not that I am aware of. My project is very complex (it's a sort of Youtube clone) and has quite a lot of dependencies. But only this function was causing problems.

Ok so putting that polyfill inside the alter strategy did not do anything bad. So I have to assume the `null`s are created at some earlier point (when I reproduced the error, I put a `console.log(backupData)` to see if `_.cloneDeep` was the problem, but it never did log anything, just threw the error. Where could I read about the actual process that happens when waterline boots up?

By the way, if you are looking to reproduce the problem: it's easy - just put that polyfill inside any module and then require it in some global sails file (I had it required in a Service).
