### ISSUE TITLE
Sails new projectname not creating directory

### ISSUE THREAD

**Issue by sonusindhu** [balderdashy/sails#3342]
Hello Team,

I have install sailsjs successfully but once tried to create new project with:
sails new testproject
but it return nothing and also not creating any directory/folder
Could you anyone let me know if there is any solutions.
Here is what I did:
sudo npm -g install sails
sails new testProject

Thanks
Sonu

**Comment by tjwebb** [comment]
`sails generate new` is the command you're looking for.

**Comment by particlebanana** [comment]
`sails new foobar` is a valid command. Make sure you don't have anything in that directory by the same name and that you have permissions to write to that directory.
