### ISSUE TITLE
Travis is not checking 4.x node versions?

### ISSUE THREAD

**Issue by tarlepp** [balderdashy/sails#3343]
Should travis CI also run all tests with
 - 4.0
 - 4.1
 - 4.2

Versions of node? Should be easily to just add those to ```.travis.yml```

**Comment by weyert** [comment]
And 5.0?

**Comment by mahtuag** [comment]
And 5.1 now ?

I think it is important to have someplace where users can quickly verify that the version of Node.js they are using is compatible with Sails. Having it in the .travis.yml is probably a good way to go about.

Oh and BTW why isn't there a travis badge on README.md ?

**Comment by hellowin** [comment]
And it's broken, just try it out on our fork.

**Comment by irobayna** [comment]
And ```5.3.0``` ?

....@hellowin broken?  are you pointing to v0.11.x? 
Note: I am using master against v5.3.0 and seems to work.

**Comment by hellowin** [comment]
@irobayna to version 4.x
Hmmm... weird, I tried with this config

```
language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

script:
  - "npm test"

notifications:
  irc:
    channels:
      - "irc.freenode.org#sailsjs"
    on_success: never
    on_failure: always
    template:
      - "Build by %{author} has failed:"
      - "Git Info: %{branch} - %{commit}"
      - "Travis states: %{message}"
      - "Build Details: %{build_url}"
      - "Change View: %{compare_url}"
    skip_join: true

# whitelisted branches
branches:
  only:
    - master
    - stable
    - beta
```

And it's broken.

**Comment by mikermcneil** [comment]
@tarlepp @weyert agreed on all counts. And @irobayna, thanks for the data point

@hellowin are you seeing issues w/ Node 5.x?  

> Oh and BTW why isn't there a travis badge on README.md ?

@mahtuag we keep a set of build lights [here](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#installing-different-versions-of-sails) which show the status of edge vs. beta (rc) vs. our stable release.

**Comment by mikermcneil** [comment]
@mahtuag forgot to mention you can view build status of all of our core modules, as well as some community adapters, in [MODULES.md](https://github.com/balderdashy/sails/blob/master/MODULES.md#core-modules).

**Comment by mikermcneil** [comment]
I did https://github.com/balderdashy/sails/commit/18b295b2a91fff5d80b5a4b6099d7adc507dc552#diff-354f30a63fb0907d4ad57269548329e3 and then got https://travis-ci.org/balderdashy/sails/builds/101059128.  :+1:

**Comment by mahtuag** [comment]
@mikermcneil a link from README.md would probably make it a lot more visible!

**Comment by mikermcneil** [comment]
@mahtuag appreciate your feedback, and I don't mean to offend. I've posted more details about my reasoning [here](https://github.com/balderdashy/sails/pull/3410#issuecomment-169576453) if you're curious.

Back to Sails on Node v4 and v5.  From the latest master branch, just confirmed that:
+ @tarlepp [all tests are passing on Node 4.2.4](https://travis-ci.org/balderdashy/sails/jobs/101061203)
+ @hellowin @weyert @mahtuag @irobayna [all tests are passing on Node 5.4.0](https://travis-ci.org/balderdashy/sails/jobs/101061203).

Thanks to all of you for spending the time to help QA the upcoming release. :+1:
