### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by fedojo** [balderdashy/sails#3353]
Hi,

Im trying to install sails but its not possible because of error:

npm WARN deprecated grunt-lib-contrib@0.7.1: DEPRECATED. See readme: https://github.com/gruntjs/grunt-lib-contrib
npm WARN lifecycle sails@0.11.2~preinstall: cannot run in wd %s %s (wd=%s) sails@0.11.2 node ./lib/preinstall_npmcheck.js /usr/local/lib/node_modules/.staging/sails-9a641b7408718dd159612fed6b8e114a
/usr/local/bin/sails -> /usr/local/lib/node_modules/sails/bin/sails.js

> bufferutil@1.2.1 install /usr/local/lib/node_modules/sails/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/piotrsikora/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/sails/node_modules/bufferutil/.node-gyp"
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/sails/node_modules/bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sails" "-g"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

System: OSX (El Capitan)
Node: 5.0.0
NPM: 3.3.6

Have you got any Idea how to resolve this issue?

I will be thankful for any idea.

Kind regards

**Comment by mccarvell** [comment]
Sadly I am also having installation issues. Did a fresh install of Mac OS X Yosemite and can't find the trick that worked for me last time.

I did:
sudo npm -g install sails

I get:

 sails@0.11.2 preinstall /usr/local/lib/node_modules/sails
> node ./lib/preinstall_npmcheck.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at startup (node.js:93:32)
    at node.js:963:3
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "sails"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! sails@0.11.2 preinstall: `node ./lib/preinstall_npmcheck.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sails@0.11.2 preinstall script 'node ./lib/preinstall_npmcheck.js'.
npm ERR! This is most likely a problem with the sails package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/preinstall_npmcheck.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sails
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/greg/Desktop/sails/npm-debug.log

Would really appreciate getting any advice as well.

**Comment by japel** [comment]
at https://github.com/nodejs/node-gyp/issues/454#issuecomment-58792114 people are telling that using --unsafe-perm would solve the problems:
> If npm was invoked with root privileges, then it will change the uid to the user account or uid specified by the user config, which defaults to nobody. Set the unsafe-perm flag to run scripts with root privileges.
But since in the past this wasn't an issue, either something changed with npm or bufferutil or any module needing node-gyp to compile...

**Comment by mccarvell** [comment]
That worked like a charm for me.. thank you kindly!

**Comment by fedojo** [comment]
Hi,

In my case there was needed of xcode update.
Than I needed just to accept terms and conditions which showed when I wanted to use git.

After that I could install Sails.

**Comment by animedbz16** [comment]
i would also recommend not using system node, but to use a node version
manager such as nvm which would allow you to install node as your local
user and would not require the use of sudo to install global node modules.

**Comment by japel** [comment]
I think this can be closed

**Comment by YogarajSaravanan** [comment]
sudo npm install --unsafe-perm --verbose -g sails
This one worked for me too :)
