### ISSUE TITLE
New Template Engine for Sails

### ISSUE THREAD

**Issue by behzadeshan** [balderdashy/sails#3358]
Hi,
I have released a new template engine named `Middle Gear`, I hope Sails team try it and add it to their view engines.
Thanks.
https://github.com/intellibits/middle-gear

**Comment by jledentu** [comment]
Hi,
The link gives me a 404 error. I can't find your project, I guess you deleted it?

**Comment by behzadeshan** [comment]
Hi Jérémie,
Yes I have deleted it because of some sorts of refactoring the entire framework, I was published it at the first place for getting a few feedbacks. Now I am working on it to improve it. But if you want to check or use it, I can send you the latest version and its readme. Do you want to use it in sails or what? We already use it with sails in our enterprise products(means not small website), I have used and improved it since one years ago in a real products so it's bug-less. But it will be changed, I mean it's API and method names. But it's not a big deal, since those method are being used once in each page, it means if you have 10 pages, after final version you will have to change only 10 lines of your code.

**Comment by jdcauley** [comment]
Its difficult to make a decisions about supporting or using a new tempting system if there isn't coherent documentation or information about that tempting system.

**Comment by behzadeshan** [comment]
Nice, I asked this 17 days ago. I have moved Middle Gear from github to another repository 3 days ago, there was a part in document about how to integrate Middle Gear with sails, but I changed the part to how to integrate Middle Gear with consolidate, since sails uses consolidate for integrating view engine, there is nothing that should be supported by sails anymore. Thank you.
