### ISSUE TITLE
Auto migrations even after configuring: migrate: 'safe'

### ISSUE THREAD

**Issue by tarunjadhwani** [balderdashy/sails#3359]
I've a model 'Order.js' file in models

```
module.exports = {
  autoPK       : true,
  autoCreatedAt: true,
  autoUpdatedAt: true,
attributes   : {
    purchaseDate: {
      type: 'datetime'
    }
 }
}
```

My model.js in config is:

```
module.exports.models = {

  connection: 'mysql_db',
  migrate: 'safe'

};
```

So even after having migrate: 'safe' in my config file, a table for order is created in the database. I don't want any auto migrations to run. I believe thats what the migrate: 'safe' does.

**Comment by tarunjadhwani** [comment]
Please comment, if someone can help me out with this issue.

**Comment by wulfsolter** [comment]
I have each of my models configured with migrate property so I can easily adjust new ones while production ones stay stable

Example `api/models/user.js`

```
module.exports = {
    migrate: 'safe',
    // migrate: 'alter',

    connection: 'defaultMysql',

    attributes	: {
        name: 'STRING',
        ....
        }
    }
};
```

**Comment by tarunjadhwani** [comment]
Thanks. Adding migrate: 'safe' in each model has resolved this issue. But I'm still confused why migrate: 'safe' in config file is not working the same way.
