### ISSUE TITLE
Automatic generation of API documentation for models/controllers

### ISSUE THREAD

**Issue by ryanseys** [balderdashy/sails#336]
I don't know if this is a terrible suggestion or not so feel free to bash it down if necessary (or maybe it already exists and I just overlooked it) but anyway... 

It would be really neat to be able to have some nice clean documentation of the API (for my app) be automatically generated for the models and controllers I have created for my app. They could be either web accessible via the app web frontend by default or just generated on the side to read, but I think it could be a really powerful tool for developers so they can see how their own models could be used in context.

**Comment by camsjams** [comment]
@leejt489  any update on your generator package?

**Comment by tilomitra** [comment]
Any update on this?

**Comment by RWOverdijk** [comment]
@leejt489 https://github.com/Barque/CrowsNest/blob/master/api/controllers/DocsController.js

I was going to pick this back up, but if you're already on it you can go for it.

**Comment by JumpLink** [comment]
I use [dox](https://github.com/tj/dox) to generate my docs and have made good experiences with it.
Currently it is strong in development, but [already looks very good](http://cms.jumplink.eu/).
If interested, we could outsource my [DocsController](https://github.com/JumpLink/cms/blob/master/api/controllers/DocsController.js) to a separate module, together :)

**Comment by pmoelgaard** [comment]
@JumpLink I'm interested in what you did, is it still something you are doing ?

**Comment by joshuamarquez** [comment]
maybe an integration with [RAML](http://raml.org/) or [API Blueprint](https://apiblueprint.org/)

**Comment by simonmilz** [comment]
+1

**Comment by irjencup** [comment]
+1

**Comment by abhisheksoni27** [comment]
Any news?
