### ISSUE TITLE
npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.

### ISSUE THREAD

**Issue by wulfsolter** [balderdashy/sails#3362]
Reinstall of npm modules results after node upgrade (Error: Module version mismatch. Expected 47, got 46) produces
`npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.`

Sails and MongoDB access still work fine it seems.

Not sure if related/caused by https://github.com/christkv/mongodb-core/commit/a18e2490d2e25ef3c602acefab51dba1ccb2d53c

**Comment by FuzzySockets** [comment]
I'm getting the same error.

**Comment by wulfsolter** [comment]
@FuzzySockets It's only a warning ;)

**Comment by aug70** [comment]
This is causes heroku deployment rejected.

```
remote: npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.
remote: redrum-sails@0.0.5 /tmp/build_7d7ed083b02ac12973c56cb392df29e5
remote: └── (empty)
remote:
remote: npm WARN EPEERINVALID mongodb-core@1.2.21 requires a peer of kerberos@~0.0 but none was installed.
remote: npm ERR! code 1
remote:
remote:  !     Push rejected, failed to compile Node.js app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to {myApp}.
remote:
To git@heroku.com:{myApp}.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by wulfsolter** [comment]
@aug70 Add manually to your package.json for now until fixed upstream.

```
    "kerberos": "~0.0.17",
```

**Comment by alexandrubau** [comment]
Thanks @wulfsolter. I had the same problem.

**Comment by AshKyd** [comment]
For anyone landing on this from Google, it's [covered in the MongoDB installation docs](http://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/#troubleshooting) including why it's happening & how to work around it.

> However don’t worry. You only need the kerberos module if intend to use kerberos. In the case you need to you can add it to your package.json

**Comment by mikermcneil** [comment]
@AshKyd @alexandrubau @wulfsolter @aug70 @FuzzySockets Thanks everyone.  If you think of a clean way to explain this warning in our docs for other folks stumbling upon this from search results in the future, would you mind sending a pull request to sails-docs?

It wouldn't be a bad idea to add a new folder and page (perhaps under http://sailsjs.org/documentation/concepts/models-and-orm) which includes different pages covering special considerations for the five core adapters (`sails-disk`, `sails-postgresql`, `sails-mysql`, `sails-mongo`, and `sails-redis`).  If you anyone wouldn't mind volunteering to help out with content, Rachael, Irl, or I can set it up (cc @rachaelshaw @irlnathan)

**Comment by waynejuckts** [comment]
"kerberos": "~0.0.17", in package works for me ;)

**Comment by mikermcneil** [comment]
@AshKyd thanks for the link!  What's weird about the mongo docs is that they show it as a warning... I wonder if there was an unintended issue w/ peer deps on particular npm versions?

**Comment by mikermcneil** [comment]
Ok added a note here: https://github.com/balderdashy/sails-docs/commit/9445fb5e73560e8e300481f4c16f7f3a27842f90

**Comment by zjdschnappi** [comment]
g
