### ISSUE TITLE
Captain's Log causes HTTP Request timeout

### ISSUE THREAD

**Issue by smith64fx** [balderdashy/sails#3374]
I have a really weird problem.

I'm currently testing my adapter and there is one command that is not working. 

I use [restler](https://github.com/danwrong/restler) to make calls to my endpoint. Everything worked fine so far. But when I make a HTTP request including multipart data I get a timeout!

So I need a lot of time figuring out the problem. When I make the request in a single script it worked like charm but in my adapter I always get a timeout.

*So I found out what's the problem*

In the test runner for the adapter, we have captain's log enabled with this syntax.
With this syntax I get a timeout for my http request.
```
var log = new (require('captains-log'))();
```

With this syntax, everything works fine! (But the logger is not working anymore)
```
var log = require('captains-log');
````

So the only solution for now to make my adapter work seems to deactivate captains logger on my whole Sails application :-( Maybe someone have an idea how this weird bug arises?

Thank you so much!
Michael

**Comment by japel** [comment]
would you post a non working ready to test example? maybe as a gist or just as a repo to clone?

**Comment by smith64fx** [comment]
Thanks for your answer!
I solved this problem using a external script call.

```
var response = exec('node', arguments).toString()
```


I created a gist for you for testing it anyway. 
https://gist.github.com/smith64fx/15ba4018b583e8d42e90

When you remove the captains-log it works! But why?


You just need to install stardog before:
www.stardog.com

1. Download
You get an E-Mail with the binaries + the license file
2. Install:
```
unzip stardog-x.x-x.zip
mv stardog-x.x-x /opt 
cd /opt
ln -S stardog-x.x.x stardog
```
3. Create Home Dir
```
mkdir -p /var/db/stardog
```
4. Create Env Variables
```
export STARDOG=/opt/stardog
export STARDOG_HOME="/var/db/stardog"
export PATH="/opt/stardog/bin:$PATH"
 ```
5. Install License
```
mv stardog-license-key.bin $STARDOG_HOME
```
6. Run!
```
stardog-admin server start
```

Now you can see the interface on localhost:5820 and run the test script!

**Comment by japel** [comment]
so this is not really sails related but captains-log?
perhaps this repo is more suitable: https://github.com/balderdashy/captains-log

**Comment by crobinson42** [comment]
+bump - move this to captains-log repo issues.

**Comment by smith64fx** [comment]
Already moved! (Created a new issue) Please Close

**Comment by mikermcneil** [comment]
@japel @crobinson42 @smith64fx thanks you guys!
