### ISSUE TITLE
[TypeError: Cannot read property 'id' of undefined] from req.session.id

### ISSUE THREAD

**Issue by OwaysisApp** [balderdashy/sails#3376]
I am getting the error above  and a 500 server errror when I visit my route for my localhost:1337/user/:id/newsfeed.  Can you help me with this error? It's driving me to madness..

User.js 

    module.exports = {

	schema: true,

	//User attributes
	attributes: {
		facebookId: {
			type: 'string',
			unique: true,
			notNull: true,
			required: true
		},
		friends : {
			 collection: 'user',
   		  	  via: 'id'
   
		},
      }

routes.js

     'get /user/:id/newsfeed': {
        controller: 'UserController',
         action: 'newsfeed'
      }

UserController.js

       module.exports = {
        newsfeed: function (req, res) {
         var userId = req.session.id;
        sails.log("Searching for user's friends: " + userId);

       User.find({ userId: userId })
       .populate('friends')
      .populate('posts')
      .exec(function (err, found) {
        if (err) return res.status(err).json(400);
        res.status(found).json(found);
      });
   }  
  };

Any help would be greatly appreciated!  Also using mongo database, redis and deploying to heroku.

**Comment by OwaysisApp** [comment]
CORRECTION ^^:  I meant to put id not user in user model as shown below.
 friends : {
         collection: 'user',
          via: 'id'
    },

**Comment by OwaysisApp** [comment]
Actually I think I got this working by changing it around some.  If it looks like just a syntax error please close it.  But can you guys put out some more documentation!!!!! Or where is that book McNeil's working on???

**Comment by foobar8675** [comment]
I don't see the error just by eyeballing, but i just came across an area I thought the docs were light. I ended up sending a PR on https://github.com/balderdashy/sails-docs. Pretty painless process.

**Comment by mikermcneil** [comment]
Thanks @foobar8675!

**Comment by mikermcneil** [comment]
@OwaysisApp going to go ahead and close this- but as an aside in case this helps, my hunch is that the connect session adapter can't access your session store.  Be sure and check that you're using the right version of connect-redis/connect-mongo, that the session is configured correctly in `config/sessions.js` and any other relevant config files / env vars, and that the session hook is enabled.  If you come across stuff that would be useful for us, it would be awesome if you could send a PR to sails-docs.  Thanks!

**Comment by arthurmoises** [comment]
Don't know if this is the right thread to post, but when attempting to do "req.session.id = docs_id" today, it didn't updated the req.session, but when I changed "id" to "userId", i.e: "req.session.userId = docs_id", it worked!! Don't know why, though..
