### ISSUE TITLE
Can't find where grunt is called from my mocha unit tests

### ISSUE THREAD

**Issue by foobar8675** [balderdashy/sails#3379]
When running my mocha unit tests (via web storm) , i keep getting a grunt error. I don't use grunt, and I removed all the references to grunt i could find and removed grunt from my .sailsrc file. If there are any suggestions, it would be appreciated.

    /usr/local/bin/node --debug-brk=55975 /Users/user/Desktop/betatest-sails/node_modules/mocha/bin/_mocha test/bootstrap.test.js test/unit/**/*.test.js --timeout 259200000 --ui bdd --reporter /Applications/WebStorm.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /Users/matthewchung/Desktop/betatest-sails/test

````
Debugger listening on port 55983
error: Grunt :: Error: listen EADDRINUSE :::55983
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Agent.Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Agent.Server.listen (net.js:1366:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:9)
    at node.js:961:3
````

**Comment by jledentu** [comment]
Did you add `grunt: false` in your hooks config?

For instance, what I do in my `bootstrap.test.js`:

```js
before(function(done) {

  Sails.lift({
    hooks: {
      grunt: false // Here I disable Grunt hooks
    },
    models: {
      connection: 'test',
      migrate: 'drop'
    }
  }, function(err, server) {
    if (err) {
      return done(err);
    }

    // Load fixtures, etc.
    
    return done();
  });
});
```

**Comment by foobar8675** [comment]
I had not been but I am now. Thanks Jérémie!
