### ISSUE TITLE
Get the frame length in a request

### ISSUE THREAD

**Issue by elssar** [balderdashy/sails#3381]
I would like to log the request and response sizes in my sails app. With HTTP requests, it's fairly simple, I use the content length header of both the request and response. But with websockets, it's not as trivial.

Is there a way to get the frame length for both the request and the response?

**Comment by shamasis** [comment]
+1 - Google has nothing on it (at least for me). Maybe the corresponding issue on socket-io repository would have some answer soon - https://github.com/socketio/socket.io/issues/2318

**Comment by sgress454** [comment]
Thanks for posting this to socket.io.  If they come up with something, we'll be able to integrate it into [sails-hook-sockets](https://github.com/balderdashy/sails-hook-sockets).
