### ISSUE TITLE
When using the "add to" blueprint, is there a way to fetch a newly created resource?

### ISSUE THREAD

**Issue by iit-federico-bozzini** [balderdashy/sails#3382]
Let's take the [official documentation page](http://sailsjs.org/documentation/reference/blueprint-api/add-to).

According to the spec I should be able to do

    POST /:model/:record/:association/:record_to_add?

where record_to_add is optional.

Following the example in the page this would mean that I should be able to do something like

    POST /employee/7/involvedInPurchases/

with a new item.

This works indeed as excepted but the response is the complete primary record where I've just added my purchase

```
{
  "involvedInPurchases": [
    {
      "amount": 10000,
      "createdAt": "2014-08-03T01:50:33.898Z",
      "updatedAt": "2014-08-03T01:51:08.227Z",
      "id": 47,
      "cashier": 7
    }
  ],
  "name": "Dolly",
  "createdAt": "2014-08-03T01:16:35.440Z",
  "updatedAt": "2014-08-03T01:51:41.567Z",
  "id": 7
}
```

In case I already have multiple purhcases, what is the proper way to get back my newly created item? At the moment this seems to require an overwriting the blueprint or some sort of hack.

**Comment by mikermcneil** [comment]
@iit-federico-bozzini if you're in a time crunch, what I'd do is a client-side sort of the populated records by `updatedAt` (obviously that's not a sustainable solution though).

No, the real approach I'd recommend is writing a custom action.  Really, when in doubt, we suggest _always_ overriding the blueprint with a custom action (blueprint routing will still work).  Whether or not you use blueprint routes is a separate decision based on your routing needs (one of those unfortunate naming collisions :/)  Hope that helps!
