### ISSUE TITLE
Goodbye Grunt, totally!

### ISSUE THREAD

**Issue by shamasis** [balderdashy/sails#3383]
Sails Version: 0.11.2

Hi,

I was trying to totally get rid of grunt in our sails server since we are not serving any views. I did the following:

1. Removed assets, tasks and views folder
2. Ensured no routes point to any view
3. Deleted Gruntfile.js from root.

All was okay till this.

Now I wanted to get rid of package.json dependencies so that things become cleaner. As such, we removed all grunt* dev dependencies and dependencies.

Thus runs fine when we do `sails lift`. But, shows an annoying error while running our mocha tests.

```
-----------------------------------------------------------------------
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started

------------------------------------------------------------------------

Looks like a Grunt error occurred--
Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
Or if you're stuck, check out the troubleshooting tips below.
```

Our mocha tests perform Sails.load() before starting the test and that seems to be the culprit

```javascript
Sails.load(function (err) {
    if (err) { return done(err); }
    sails.config.bootstrap(done);
});
```

Any clue how this can be fixed? **Or is there any major side effect if we completely remove Grunt?** (PS: We do not use grunt watchers at all.)

Introducing `grunt` in dependencies fixes the problem.

**Comment by mikermcneil** [comment]
Hi shamasis- try turning off the grunt hook   (easiest way to do this is in your .sailsrc file)

```
hooks: { grunt: false }
```

**Comment by Josebaseba** [comment]
You can create a new sails project using: 

`sails new testProject --no-frontend` and then .sailsrc -> `hooks: { grunt: false }`

And that's it!

**Comment by randallmeeker** [comment]
Those instructions `sails new testProject --no-frontend` because it does not adequately inform people how to do it to an existing app.

**Comment by mikermcneil** [comment]
@Josebaseba @randallmeeker both useful points -- thanks guys

**Comment by shamasis** [comment]
Would appreciate if you reopen the issue @mikermcneil - the suggestion you provided works when we lift the server, but like I mentioned, it fails when we do `Sails.load` within our mocha bootstrap specs.

**Comment by shamasis** [comment]
@Josebaseba @randallmeeker @mikermcneil - I am sure that there's a misunderstanding. This is not a simple issue of me not reading the documentation.

There seems to be a **bug**. Please reopen.

Doing `hooks: { grunt: false }` still calls grunt when using Sails programatically via `Sails.load`. Sails lift works just fine.

**Comment by Josebaseba** [comment]
@shamasis but in your lift you aren't passing the grunt false info to Sails.

Look, when you lift you application sails internally load the .sailsrc config: `sails.lift(rc('sails'));`

If you are doing a Sails lift in other place, such as the tests, you need to pass that info when you load the app, take a look to my test config:

```javascript 

Sails.lift({
    // Configuration for testing purposes
    port: process.env.port || 1992,
    log: {level: process.env.log || 'warn'},
    hooks: {grunt: false},
    globals: {async: false, services: false, models: false}
  }, function(err, sails) {
    // Start the tests
    if(err) return done(err);
    done(err, sails);
  });
});

```

**Comment by shamasis** [comment]
Ah yes. Super thanks for spending time on this. This was an overlook from my side. Passing configuration is just what I needed.

**Comment by mikermcneil** [comment]
@Josebaseba @shamasis thanks for the follow up y'all
