### ISSUE TITLE
Blueprint routes with /controller/:name instead of /controller/:id

### ISSUE THREAD

**Issue by adampietrasiak** [balderdashy/sails#3386]
I want api urls to be more user friendly.

I've got unique `name` field in my model and I'd like to use it instead of object id for routes. Is it possible without rewriting all routes (including associations) myself? 

Example result route could be `http://localhost:1337/api/users/johnny/posts`

**Comment by hellowin** [comment]
You can overwrite existing blueprint with your own. [example](http://stackoverflow.com/questions/22273789/crud-blueprint-overriding-in-sails-js)

**Comment by jdcauley** [comment]
@adampietrasiak Looks like @hellowin wrapped this up
