### ISSUE TITLE
Undefined Reference issues while accessing models outside controller

### ISSUE THREAD

**Issue by smrutimandal** [balderdashy/sails#3387]
I am trying to create a hashmap of "itemID"/"model" pairs. I am able to do this inside the controller, however as I don't want to create this map for every action, I am trying to build this map inside a config file and I intend to export it to be used in the controller.

But I am not able to access the models outside controller to create this hashmap.

I found a 2 year old discussion on this regard in SO.

http://stackoverflow.com/questions/18617716/how-can-i-access-my-models-in-sailsjs-outside-a-controller

However, the suggested methods are not working.

    var map = new Map();
    map.set('item1', Foo)
    module.exports.modelMap = {
        productMap: map;
    }
Below are the various syntax I tried and their corresponding errors:

    map.set('item1', Foo)           --> ReferenceError: Foo is not defined
    map.set('item1', sails.models.Foo)  --> ReferenceError: sails is not defined
    map.set('item1', sails.models['Foo'])   --> ReferenceError: sails is not defined
FYI, model attribute in config/globals.js is set to true.

Making model names lower case, yields the same errors.

    firstuser@ubuntu:~/project-dir$ npm --version sails
    2.14.7
    firstuser@ubuntu:~/project-dir$ sails --version
    0.11.2
    firstuser@ubuntu:~/project-dir$ 
This feature is supposed to work out-of-the-box. Can someone please advise if I am using an incorrect syntax.

**Comment by aars** [comment]
When/where are you running this code?

Try putting it in `config/bootstrap.js` and listening for the `lifted` event:

```
// config/bootstrap.js
module.exports.bootstrap = function (cb) {
  // .... 

  sails.on('lifted', function () { 
    console.log(sails.models); // Is now populated.

    // Your Magic Goes Here 
  });

  cb();
};
```

**Comment by aars** [comment]
Another option is to use a hook. Make sure you wait for `hook:orm:loaded` so your models are populated.

http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification/initialize

**Comment by smrutimandal** [comment]
Hi Aars,

I am trying to create a global map of models as "key"/"model" pairs. I need this map to be global as the controller action will be picking the appropriate model based on a passed key. I undertand, this is a very crude form of multi-tenanacy, but it is the best I have got so far.

So, my earlier code was in a module(modelmap) under sails.config and the map was exported with module.exports.map which was accessible from controller as sails.config.modelmap.map. But as you pointed out, the models aren't loaded while my modelmap module in config is being run, hence the reference errors.

I made the changes suggested by you and here is how it looks like now;

    module.exports.bootstrap = function(cb) {

    var map = new Map();
    sails.on('lifted', function () { 
        console.log('Sails has been lifted.'); // Is now populated.

        map.set('item1', Item1Model);
        map.set('item2', Item2Model);

        console.log('map has been populated');
        });

        cb();
    };

Now I am not getting any errors while lifting sails. However, while accessing the map, I do get an error.

Controller code to access the map:

    console.log("[ItemController] Model in question is", sails.config.bootstrap.map.get('item1'))

Error being thrown:

    console.log("[ItemController] Model in question is", sails.config.bootstrap.map.get('item1'))
										                                           ^
    TypeError: Cannot read property 'get' of undefined

Could you please suggest how can I access this map as a global variable from controller module.

Thanks.

P.S. I haven't looked into the hooks suggestion yet.

**Comment by smrutimandal** [comment]
I see the problem with the config module approach. As model objects aren't loaded when the config module is running, it is throwing the reference error. I tried the hooks approach and have been able to create the map. 

When sails is lifted in verbose;

    verbose: Length of the created Map is 2
    verbose: modelmapper hook loaded successfully.

But right now I am struggling with accessing the map. 

<b>api/hooks/modelmapper/index.js</b>

    module.exports = function modelMapper(sails) {
        return {
   	            initialize: function(cb) {
                this.testvar = 123;
   			    sails.on('hook:orm:loaded', function() {
   				    this.map = new Map();

   				    this.map.set('tenant1', tenant1Items);
   				    this.map.set('tenant1', tenant1Items);
                    sails.log.verbose("Length of the created Map is", this.map.size)
				    return cb();
			    });
   		    }
   	    }
    }

<b>Controller Code and Outout/Error</b>

    console.log(sails.hooks.modelmapper.testvar); --> 123
    console.log(sails.hooks.modelmapper.map.size); --> TypeError: Cannot read property 'size' of undefined

Could you please help with the correct syntax to access the map methods.

Thanks again for the assistance.

**Comment by smrutimandal** [comment]
Thanks @aars
