### ISSUE TITLE
Unwanted 'return' in Sails

### ISSUE THREAD

**Issue by bhanuV** [balderdashy/sails#3392]
Hello I have been using Sails for a month and find it is really wonderful framework to work with. Currently I am using 0.11.3 version of Sails.

I find the 'return' weird on a callback function, response object or middleware(that is next()) since they are all function calls.  

For instance,
return cb(); // in config/sockets.js 
return res.forbidden('You are not permitted to perform this action.'); // in api/policies/sessionAuth.js
return next(); // in api/policies/sessionAuth.js

If I am wrong please do correct me.
Thanks.

**Comment by foobar8675** [comment]
I've gotten in the habit of doing that, especially in the cases where i don't want the rest of the function to execute. imagine a case where you call a callback which returns a http response, but then control flow goes back to the original function where you have logic to return an http response.

**Comment by bhanuV** [comment]
Oh! I understand now. Thanks for explaining this, I was just curious about this idea.
