### ISSUE TITLE
sails.io.js - nodejs - Resourceful PubSub not receiving model events

### ISSUE THREAD

**Issue by CiscoKidxx** [balderdashy/sails#3400]
sails -v : 0.11.2
sails.io.js -v :0.11.7
socket.io-client -v : 1.3.7

I use the code below to subscribe a nodejs application to model events in sails. I do not receive any updates on the client console when a new model "agent" is created nor when an existing is modified. 

```javascript
var socketIOClient = require('socket.io-client'),
    sailsIOClient = require('sails.io.js');

var io = sailsIOClient(socketIOClient);

io.sails.url = 'http://localhost:1337';

io.socket.on("agent", function(event) {
  console.log(event);
})

io.socket.get("/agent", function(resData, jwres) {})
```

Sails Console Output:
https://gist.github.com/CiscoKidxx/e5af93ebcc24702ba4f8

More Info (client code):
http://stackoverflow.com/questions/33926792/sails-io-js-nodejs-resourceful-pubsub-not-receiving-model-events

**Comment by sgress454** [comment]
Looks like this has been answered in StackOverflow (which is the appropriate place for questions like this; this forum is specifically for reporting bugs on the Sails core).
