### ISSUE TITLE
sails generate sails.io.js provides older socket.io-client

### ISSUE THREAD

**Issue by shamasis** [balderdashy/sails#3401]
Hello,

Was wondering if anybody noticed that [`sails generate sails.io.js`](https://github.com/balderdashy/sails-generate-sails.io.js) creates a file with socket.io-client version `1.2.1` while the socket.io server in sails hooks is `1.3.7` (as on Sails 0.11.x)?

**Comment by tjwebb** [comment]
It's been like that for a year. See: https://github.com/balderdashy/sails/issues/3429

**Comment by shamasis** [comment]
Pinging here so that @sailsbot does not auto close it.

**Comment by sgress454** [comment]
This has been updated to 1.4.0.  Thanks!
