### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by bismark64** [balderdashy/sails#3404]
Hi guys.. I'm trying to install sails using standard npm install command, but I'm getting an odd error:

```bash
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sails@0.12.0-rc3" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.0
npm ERR! path /usr/local/lib/node_modules/.staging/colors-5905414904236147fa08d725faf5dc1f
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-5905414904236147fa08d725faf5dc1f' -> '/usr/local/lib/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/colors'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/colors-5905414904236147fa08d725faf5dc1f' -> '/usr/local/lib/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/colors'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! code 1
```

Obviously `'/usr/local/lib/node_modules/.staging/colors-5905414904236147fa08d725faf5dc1f'` does not exist.. Any ideas how to solve this? Thanks

**Comment by RomainLanz** [comment]
Dear @bismark64,

Can you answer to these questions:

1. Which OS are you using?
2. Does it throw the same error when you install the stable version? (`npm install -g sails`)

**Comment by bismark64** [comment]
Sorry @RomainLanz , I'm using OSX El Capitan. Node and NPM versions are there in the log. And yes it's failing with the stable version.. might it be related to an old colors package version (I believe ~0.6.2)?

**Comment by RomainLanz** [comment]
You can try to clean the npm cache.

```shell
$ npm cache clean
```

**Comment by bismark64** [comment]
sorry, didn't work.. same error..

**Comment by jdcauley** [comment]
@bismark64 

This is an NPM error rather than a Sails.js error.

There are several issues including some about Sails.js in their issues.
https://github.com/npm/npm/issues/9793
