### ISSUE TITLE
Is there a RethinkDB Adapter for Sails?

### ISSUE THREAD

**Issue by sabersalv** [balderdashy/sails#3406]

**Comment by RomainLanz** [comment]
Some searchs will not kill you.

* [jmdobry/waterline-rethinkdb](https://github.com/jmdobry/waterline-rethinkdb)
* [Rethinkdb adapter for Waterline/Sails.js](https://github.com/rethinkdb/rethinkdb/issues/3727)
* [sails-rethinkdb](https://www.npmjs.com/package/sails-rethinkdb)
* [Google Search](https://www.google.ch/search?q=RethinkDB+Adapter+Sails)
