### ISSUE TITLE
no frontend and images

### ISSUE THREAD

**Issue by soniram** [balderdashy/sails#3411]
I've created my project with the no-frontend option. Everything works fine but I cannot access images uploded to assets/images folder . 

As far as I can understand with the no-frontend option grunt tasks are not installed so there is no assets pipeline to .tmp when sails lifts.

Am I right ?
Any work around ?

**Comment by internalfx** [comment]
@soniram Assets are served from `.tmp/public` when you run sails lift.

Without grunt that folder likely doesn't exist.

I think the `no-frontend` option is for API servers or people who want to build their own asset pipeline.

**Comment by soniram** [comment]
@internalfx searching all issues with "assets" found an alternative to gunt-.tmp solution.
Adding this property to .sailsrc

  "paths": {
    "public": "assets"
  }

you can assign "public" wherever you want.
I cannot comment on how elegant/appropriate this solution is, but it works.
More experienced member could enlight  us on this.

**Comment by rachaelshaw** [comment]
@soniram Thanks!  That's a good approach, we've used it a few times. Just make sure and add that config in your .sailsrc as opposed to later (by the time the files in the `config/` directory are loaded, the paths have already been decided-- because the `config/` directory is one of those paths)
