### ISSUE TITLE
Issue with 400 Bad Request on websocket call.

### ISSUE THREAD

**Issue by shamasis** [balderdashy/sails#3413]
Hi,

We are facing a scenario where a good percentage of requests going to /Socket.io/?... is returning with 400.

Default nginx access log results are littered with:

```
10.0.0.82 - - [04/Dec/2015:11:43:27 +0000] "GET /socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket HTTP/1.1" 400 45 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
```

The requests are not even reaching our overlying SailsJS server. We suspect something going wrong at socket-io layer. Any thoughts?

**Comment by shamasis** [comment]
Posted a temp solution on socket-io repository - https://github.com/socketio/socket.io/issues/2333#issuecomment-162240158

**Comment by sgress454** [comment]
Hi @shamasis, thanks for following up--closing this as it doesn't seem like a Sails issue, but please keep us updated if it turns out that something needs to be done on our end.
