### ISSUE TITLE
Sailsjs console convert any number to a string, validation fails

### ISSUE THREAD

**Issue by adrien-candiotti** [balderdashy/sails#3414]
With sails console.

When i try to create a new model with a number, i get a validation error:
```Test.create({number: 0})```

\>\>\>

``` `undefined` should be a number (instead of "0")" which is a string.```

**Comment by sgress454** [comment]
Hi @adrien-candiotti.  This forum is for reporting bugs on the Sails core.  For support, please see our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).  You'll need to provide a lot more information than you have here (such as your `Test` model code) if you expect a useful reply!

**Comment by Josebaseba** [comment]
@adrien-candiotti set in your model -> `number: {type: 'integer'}` instead of type number.
