### ISSUE TITLE
Typo in console command

### ISSUE THREAD

**Issue by bountyx** [balderdashy/sails#3415]
https://github.com/balderdashy/sails/blob/master/bin/sails.js#L99

Should be "console" not "consloe".

**Comment by dexxtan** [comment]
This is not a typo since its an alias that defaults to the original function of the "console" command.

**Comment by tjwebb** [comment]
https://github.com/balderdashy/sails/pull/3352

**Comment by bountyx** [comment]
Looks like I missed the original command. Makes sense.
