### ISSUE TITLE
Raw query does not return a promise

### ISSUE THREAD

**Issue by icodeforlove** [balderdashy/sails#3418]
I'm not sure if this is a waterline issue or a sails issue, but this seems rather inconsistent considering all the other model methods support them.

**Comment by HomeLH** [comment]
I have the same problem. I do as http://stackoverflow.com/questions/21886630/how-to-use-model-query-with-promises-in-sailsjs-waterline/34132904#34132904, but it does not work well. 

I use promise as follows:

`var Promise = require('bluebird');
 var patientQueryAsync = Promise.promisify(Patient.query);`

but it does not work. It returns `ReferenceError: Patient is not defined`, has anyone meet the same problem? Thank you very much!

**Comment by icodeforlove** [comment]
As a hack you can monkeypatch this for now in your bootstrap

```javascript
module.exports.bootstrap = function(cb) {
	var Promise = require('bluebird');

	Object.keys(sails.models).forEach(function (key) {
		if (sails.models[key].query) {
			sails.models[key].query = Promise.promisify(sails.models[key].query);
		}
	});

	cb();
};
```

**Comment by HomeLH** [comment]
@icodeforlove  Thank you very much! It works well, but I can not understand how it works...

**Comment by icodeforlove** [comment]
@HomeLH It traverses all your models that have a `.query` method and promisifies that method.

**Comment by crh3675** [comment]
Monkey patch?  That is a raw query.  I don't see a bug, just a misunderstanding of expectations and a lack of JS knowledge.

**Comment by icodeforlove** [comment]
@crh3675 It's an inconsistency in the API. Can explain why the raw query method should not support promises?

**Comment by RWOverdijk** [comment]
@icodeforlove The "raw" part talks to the underlying adapter, which works with callbacks. Either way, making it a promise yourself is very simple.

**Comment by particlebanana** [comment]
It doesn't return a promise because you are talking directly to the underlying adapter and can be running anything in the callback. We can return a promise in the predefined methods because the code lives in Waterline not your user code. When you use the raw method you are responsible for dealing with the connection and returning the data.
