### ISSUE TITLE
Server-side socket events

### ISSUE THREAD

**Issue by dhcole** [balderdashy/sails#3421]
Hey team Sails, hope things are well. Wondering... is there a way to listen for server-side  socket event? My end goal is to notify all clients subscribed to a room when a client leaves or enters the room. To do so, I figured I would have the server broadcast connect and disconnect events, but I'm not sure how to listen for / respond to those events. Any ideas on how to handle something like this?

Thanks!

**Comment by sgress454** [comment]
Hi @dhcole!  FYI, this forum is strictly for bug reports on the Sails core.  For support in the future, please use our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).
<hr/>
You can get the underlying [socket.io](http://socket.io) instance via `sails.io`, giving you access to `sails.io.on()` and `sails.io.emit()`.  However, this isn't the recommended method of handling client "presence".  Instead, you can use Sails' [resourceful pubsub](http://sailsjs.org/documentation/reference/web-sockets/resourceful-pub-sub) methods to notify all subscribers to a "room" model whenever a client connects or disconnects.  For a simple example of using resourceful pubsub (and some of the lower-level [`sails.sockets.*` methods](http://sailsjs.org/documentation/reference/web-sockets/sails-sockets)), see [SailsChat](https://github.com/balderdashy/sailschat).

**Comment by joaolucas89** [comment]
I cant do it :'(

**Comment by particlebanana** [comment]
@joaolucas89 sorry to hear that. Can you create a repo that demonstrates the issue you have?
