### ISSUE TITLE
Route magic

### ISSUE THREAD

**Issue by RWOverdijk** [balderdashy/sails#3422]
Good day!

Just checking out the routes currently registered and found double routes, and routes I can't explain. I've also found methods I can't explain.

### Methods
Sails console:

```
sails> Object.keys(sails.router._privateRouter.routes)
[ 'checkout',
  'connect',
  'copy',
  'delete',
  'get',
  'head',
  'lock',
  'm-search',
  'merge',
  'mkactivity',
  'mkcalendar',
  'mkcol',
  'move',
  'notify',
  'options',
  'patch',
  'post',
  'propfind',
  'proppatch',
  'purge',
  'put',
  'report',
  'search',
  'subscribe',
  'trace',
  'unlock',
  'unsubscribe' ]
```

Is this something express adds, or something sails adds? And are these perhaps just default listeners that will check if there are actual routes? I'd like to understand what's happening here :)

### Double routes
Type `sails console` and do:

```javascript
var ld = require('sails/node_modules/lodash');
ld.pick(sails.router._privateRouter.routes, ['put']);
```

For me, this gives two things I'm curious about. First, double routes:

```javascript
{ path: '/company/:id',
       method: 'put',
       callbacks: [Object],
       keys: [Object],
       regexp: /^\/company\/(?:([^\/]+?))\/?$/i },
     { path: '/company/:id',
       method: 'put',
       callbacks: [Object],
       keys: [Object],
       regexp: /^\/company\/(?:([^\/]+?))\/?$/i },
```

Why has this route been registered twice? This is consistent across all my routes.

Secondly:
```javascript
{ path: '/*',
       method: 'put',
       callbacks: [Object],
       keys: [],
       regexp: /^\/(.*)\/?$/i },
     { path: '/*',
       method: 'put',
       callbacks: [Object],
       keys: [],
       regexp: /^\/(.*)\/?$/i },
     { path: '/*',
       method: 'put',
       callbacks: [Object],
       keys: [],
       regexp: /^\/(.*)\/?$/i },
```

This makes no sense at all to me. Why are there three catch-all put routes?

This is my blueprints config:

```javascript
{ actions: false,
  shortcuts: false,
  index: true,
  rest: true,
  prefix: '',
  restPrefix: '',
  pluralize: false,
  populate: true,
  autoWatch: true }
```

**Comment by sgress454** [comment]
Hi @RWOverdijk.  

As far as the methods, those come with Express.  It has a dizzying array of unheard-of methods.

As far as the duplicate routes, they're probably _not_ duplicates--just the same URL being bound to different handlers (note the `callbacks` property).  If you start sails with `--silly`, you'll see every binding that Sails makes, e.g.:

```
silly: Binding route ::   /user/find (POLICY: alwaysAllow)
silly: Binding route ::   /user/find (BLUEPRINT: findRecords)
```

which will result in two entries in the router.

**Comment by RWOverdijk** [comment]
I see. Thanks
