### ISSUE TITLE
Multiple layouts with different dependencies (js, css) minified

### ISSUE THREAD

**Issue by daniel79** [balderdashy/sails#3424]
Hi
Is there an easy option to have multiple layouts files with different dependencies (js and css) minified? 
Configuring two pipelines seams overwhelming.

**Comment by eriksape** [comment]
Hi, did you see this? https://github.com/jayfar/sails.js-use-different-layout-with-different-javascript-files

**Comment by sgress454** [comment]
@eriksape thanks for the link!

@daniel79 Thanks for using Sails!  FYI, this forum is for reporting bugs on the Sails core.  Please direct future support requests to our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [chat room](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).

**Comment by daniel79** [comment]
@eriksape thanks!
