### ISSUE TITLE
"sails generate model" from outside of sails project directory

### ISSUE THREAD

**Issue by FurkhatKasymov** [balderdashy/sails#3426]
Let's say I'm in home directory
And I create new sails project with:
    `sail new testProject`
When I type:
    `sails generate model smth`
Then I see message:
    `info: Created a new model ("Usd") at api/models/Usd.js!`.
Thats create api directory with model file in my home directory. But should not. I think there should be an error, as when I try to create controller:
```
$ sails generate controller smth
error: Sorry, this command can only be used in the root directory of a Sails project. 
```
My sailsjs version 0.11.2

**Comment by Josebaseba** [comment]
After `sails new testProject` you need to go to the project folder `cd testProject` and then `sails generate model smth` or `sails generate controller smth`

**Comment by FurkhatKasymov** [comment]
@Josebaseba issue is not about this.
When creating a controller from outside of the sails project, **you receive an error message**. But when you create a model from outside of the sails project **you are not receiving**.

There should be the same error message for model!

**Comment by sgress454** [comment]
Thanks @FurkhatKasymov.  Mind posting this in [sails-generate-model](https://github.com/balderdashy/sails-generate-model) and closing here?

**Comment by FurkhatKasymov** [comment]
@sgress454 Thanks. Done ([here](https://github.com/balderdashy/sails-generate-model/issues/10)).
