### ISSUE TITLE
timeout exceeded { [Error: socket hang up] code: 'ECONNRESET' }

### ISSUE THREAD

**Issue by madhurangaonbit** [balderdashy/sails#3427]
HI 
Im Getting above issue when initiating a http request from 'requestify' add on.
I used below all options to get rid of that.
But no luck so far.

requestify.request(urls.ACCOUNT_AUTHENTICATION, {
method: 'POST',
body: reqParams,
headers: {
Authorization: config.AUTHORIZATION_KEY,
'Content-Type': 'application/json',
'Content-Length': Buffer.byteLength(reqParams)
},
timeout : 10000,
dataType: 'json'
})

Any help ??

**Comment by sgress454** [comment]
Hi @madhurangaonbit.  Thanks for using Sails.  This forum is reserved for reporting bugs on the Sails core; for support queries like this you'll have better luck on our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).  I'd also try hitting that endpoint using something other than Requestify to narrow down the issue before you post it again.
