### ISSUE TITLE
Having problem with Skipper stream-uploading to S3

### ISSUE THREAD

**Issue by super-iterator** [balderdashy/sails#3428]
Trying to stream-upload to S3 using skipper and skipper-s3 using this code

```
image_upload : function  (req,res) {

		// depends on bodyparser:skipper in confing/http.js

		console.log("Uploading image .. ");

		req.file('image')
			.upload({
				adapter: require('skipper-s3'),
				key: KEY,
				secret: SECRET,
				bucket: 'mybucket',
                                tmpdir: 'tmp/s3-multiparts'

			}, function whenDone(err, uploadedFiles) {
				if (err){
					return res.negotiate(err);
				} else {
					dict=	{
						files: uploadedFiles,
						textParams: req.params.all()
					}
					return res.ok(dict);
				}
			}

		);
```

**I have 2 problems**
**First**: when I try to upload some file, I can see that this file buffers in memory, instead just buffering to the disk (path added to options).

Actually this is a big problem, as my memory will fill up so quickly when having many users concurrently uploading

**Second**: my application crashes when upload is bigger than 5MBs, giving me this error

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Request aborted
    at IncomingMessage.onReqAborted (~Desktop/myApp/node_modules/sails/node_modules/skipper/node_modules/multiparty/index.js:175:17)
    at IncomingMessage.emit (events.js:104:17)
    at abortIncoming (_http_server.js:279:11)
    at Socket.serverSocketCloseListener (_http_server.js:292:5)
    at Socket.emit (events.js:129:20)
    at TCP.close (net.js:485:12)
```

What shall I do with those 2 problems?

**Comment by sgress454** [comment]
Hi @super-iterator, I believe I answered your first issue here: https://github.com/balderdashy/sails/issues/3384#issuecomment-164082117.

Closing this as it's been opened in the more appropriate skipper-s3 issues forum here: https://github.com/balderdashy/skipper-s3/issues/42.
