### ISSUE TITLE
Can not create sails skeleton

### ISSUE THREAD

**Issue by morow93** [balderdashy/sails#3430]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a.chepurnoy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! path C:\Users\a.chepurnoy\arra\ororo\node_modules\sails\node_modules\.bin\tiny-lr.cmd
npm ERR! code EEXIST

npm ERR! Refusing to delete C:\Users\a.chepurnoy\arra\ororo\node_modules\sails\node_modules\.bin\tiny-lr.cmd: containing path C:\Users\a.chepurnoy\arr
a\ororo\node_modules\sails\node_modules\tiny-lr isn't under npm's control
npm ERR! File exists: C:\Users\a.chepurnoy\arra\ororo\node_modules\sails\node_modules\.bin\tiny-lr.cmd
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a.chepurnoy\arra\ororo\npm-debug.log
error: 1

**Comment by RWOverdijk** [comment]
Is this using `sails new`? Is the directory you're trying to use actually empty? What version are you using? Did you change something to the default installation?

**Comment by morow93** [comment]
yes, i'm using "sails new". yes, directory is empty. versions - node v5.2.0, npm v3.5.2. no, just update npm and node to latest. i think, no

**Comment by crh3675** [comment]
Looks like an arbitrary permissions problem on the workstation.  Not Sails related.

**Comment by morow93** [comment]
You're right! It was problem with c++ redistributable. The error occured even on sails installation

**Comment by mikyjpeg** [comment]
Hi, how did you solved it? I'm facing the same problem..

**Comment by morow93** [comment]
Very simple - I changed windows 10 to ubuntu.

**Comment by mikyjpeg** [comment]
Oh, ok. Sounds good, but I already have a sailsjs installation working on my osx machine. Unfortunately not all my company developers have an unix machine, I was assuming that it could works also on windows. Thank you.
