### ISSUE TITLE
Recompile ejs view when changing 

### ISSUE THREAD

**Issue by Jonatthu** [balderdashy/sails#3431]
How can I configure sails for make that the view recompile each time that I made a change without I need to restart the server, like razor in asp.net?

**Comment by metzuda** [comment]
https://www.npmjs.com/package/livereload-js

**Comment by sgress454** [comment]
Livereload is a fine option, but you shouldn't need it for views in your `/views` folder; those aren't cached so any changes you make to them should be available simply by reloading the page.  You can verify this yourself by generating a new Sails app, lifting it, altering the `views/homepage.ejs` file and reloading the page.
