### ISSUE TITLE
Data gets corrupted during development

### ISSUE THREAD

**Issue by slavafomin** [balderdashy/sails#3432]
Hello!

We're developing a Sails.js application and we've started to encounter some weird issues with it. We're using PostgreSQL as a database for our app data. Here's my usage scenario:

1. Create new empty PostgreSQL database
2. Lift Sails.js application
3. Create 1' 000 new random users programmatically
4. Work with the application (start/stop/issue requests)
5. At some point in time, half of the users got lost from the database table for no apparent reason

After another such event I've got the following error in the console:

```
error: Ignored attempt to bind route (/api/users/field-values) to unknown controller.action :: user.fieldvalues
Waterline encountered a fatal error when trying to perform the `alter` auto-migration strategy.
In a couple of seconds, the data (cached in memory) will be logged to stdout.
(a failsafe put in place to preserve development data)

In the mean time, here's the error:

Error (E_UNKNOWN) :: Encountered an unexpected error
error: relation "user" does not exist
    at Connection.parseE (/home/sfomin/testdrive/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/sfomin/testdrive/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/sfomin/testdrive/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Details:  error: relation "user" does not exist



================================
Data backup:
================================

...

```

I really afraid for our production data right now, so I can't deploy another release.

What could be the reason for this? Have you ever encountered a similar issues?

Thank you.

**Comment by particlebanana** [comment]
You need to modify your auto-migration setting. Setting `migrate: 'create'` should only create new columns in the database when you modify your model or set `migrate: 'safe'` to prevent any migrations.

In production with `NODE_ENV=production` the `safe` setting will automatically get set.

**Comment by slavafomin** [comment]
Hello @particlebanana ! Thank you for a quick response!

There is no `create` migration strategy according to the [official docs](http://sailsjs.org/documentation/concepts/models-and-orm/model-settings), is it safe to use the un-documented feature?

**Comment by kevinburkeshyp** [comment]
@slavafomin I'd also check the raw Postgres queries that are being made.

`alter` will auto-generate schema and attempt to create tables every time you lift Sails. Sometimes the generated schema is not great, for example if you ask for an index on a text table, the index is placed on the normal column value, but Sails/Waterline will issue queries against the LOWER("columnName") value, so the index won't hit. It also might not match the Postgres schema you're running in production, which caused at least one outage.

we dropped it completely in favor of `migrate: 'safe'` about 3 months ago, we just save our prod schema to a file and load that via `psql < schema.sql` before test runs.

**Comment by wulfsolter** [comment]
@slavafomin Most likely cause is the `migrate: alter` which drops and rebuilds the table on each startup. I found in my own dev cycle, I'd be running PM2 with a `watch` flag, and mid-way through the startup rebuild, I would've saved again and the startup DB rebuild gets killed by PM2.

**Comment by slavafomin** [comment]
Thank you for all the comments.

I've set `sails.config.models.migrate` to `safe`, but I'm still getting periodic deletion of items from the database table. There is no error messages most of the time. Everything seems to work normal, but when I look into database table, most of the records are gone.

How's that even possible?

Thanks.

**Comment by kevinburkeshyp** [comment]
are you running an old version? maybe pre - the "Waterline truncated a JOIN table" issue? not sure when that was patched

**Comment by slavafomin** [comment]
It looks like I'm running the latest version of Sails and Waterline. I think I will try to look into the issue from the PostgreSQL side of things in order to understand what is going on. Will let you know ;)

**Comment by kevinburkeshyp** [comment]
one other thing I noticed recently... if you have Model.update(id:
id).where(condition: true), the `id` clause gets dropped, all rows might
get updated.


-- 
kevin

**Comment by mikermcneil** [comment]
> How's that even possible?

@slavafomin I've definitely run into problems like this in the past... only to realize they were timing issues in my app level code :sheep:.  However, as @kevinburkeshyp @wulfsolter and @particlebanana pointed out, this sort of thing oftentimes comes from `migrate: 'alter'` too.  Realistically, it's hard to say until you have some more diagnostics on the weird queries you're seeing, etc.  Thanks for taking the time to get to the bottom of it!

@kevinburke re: the id clause-- just to clarify, you mean usage like:  `SomeModel.update(criteria).where(anotherCriteria).exec(..)`?

**Comment by mikermcneil** [comment]
@slavafomin I'm going to go ahead and close this issue to stay organized.  If you experience unexpected behavior from Waterline or sails-postgresql in the future, please @particlebanana or I know by [opening an issue](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md) in either [waterline](https://github.com/balderdashy/waterline) or [sails-postgresql](https://github.com/balderdashy/sails-postgresql).

**Comment by slavafomin** [comment]
Thanks Mike! I've decided to switch to Sequelize for now.

Why by the way aren't you using it in Sails? It takes a lot of effort to create yet another ORM especially when there's a decent one already.
