### ISSUE TITLE
update i18n to latest version

### ISSUE THREAD

**Issue by martingg88** [balderdashy/sails#3435]
can we update i18n to latest version so it can support notation configuration. thanks

**Comment by sgress454** [comment]
Looks like it's on the [latest version](https://www.npmjs.com/package/i18n) (0.5.0) in the [master branch](https://github.com/balderdashy/sails/blob/master/package.json#L61).

**Comment by martingg88** [comment]
FYI. the latest version is 0.6.0 that could support for notation customization. Thank

**Comment by sgress454** [comment]
0.6.0 hasn't been published to NPM, so we can't use it.  The latest published version is [0.5.0]
(https://www.npmjs.com/package/i18n).

**Comment by martingg88** [comment]
too bad. wait for them to publish then. thanks

**Comment by martingg88** [comment]
fyi. i18n version 0.7 has already been published to npm. Please update it at your side. thanks.

**Comment by irlnathan** [comment]
Howdy @martingg88,

Please open up a new issue and link back to this one. Thanks!

Best, Irl

**Comment by martingg88** [comment]
Done!
