### ISSUE TITLE
Sails www - problem with globals (0.12?)

### ISSUE THREAD

**Issue by muradaliyev** [balderdashy/sails#3436]
When running **sails www**, services and hooks that relay on globals (such as sails) in their code, will raise error and exit the app. Currently noticed such behavior with sails-auth, and custom service

Looks like setting globals to false in sails-www.js, is causing this problem. Disabling this option in global /local sails, fixes the problem

I am currently using 0.12RC3 in my project, not sure if this problem occurs in previous versions

```javascript
// node_modules\sails\bin\sails-www.js

var sails = Sails();
  sails.load(_.merge({}, rconf, {
    hooks: {
      grunt: false
    },
//    globals: false <-- cause of problem
  }), function sailsReady(err) {
```

**Comment by sgress454** [comment]
Thanks for the report @muradaliyev, looking into it!

**Comment by mikermcneil** [comment]
@muradaliyev To clarify these are custom hooks, right?  None of the core hooks should be relying on globals.  That aside, I think it's fine/sensible to enable globals here.

**Comment by muradaliyev** [comment]
HI @mikermcneil, yes it happened with hook in sails-auth module. 

But also it throws error if sails global var is referenced in any service under api\services.

For example, In new sails project I created test.js under **api\services**, with 1 line: **console.log(sails)**

Now, if I run **sails www**, script will throw error **sails is not defined** and exit
In contrary, **sails lift** command will run without any problem

I am not sure, if this is intended, but to me it is a bit inconsistent behavior

**Comment by mikermcneil** [comment]
@muradaliyev agreed- it doesn't fit our conventions.  Thanks for the follow up!

**Comment by mikermcneil** [comment]
@muradaliyev Would you give it a go with dfada3b66d9e49258bce8205cfb43a8240ffd163?

**Comment by muradaliyev** [comment]
Hi @mikermcneil, I've the replaced global sails dir with the latest repo clone, and can confirm, that **sails www** is now loading without problems. 

Should I close this issue or it will be done via commit?

Thanks a lot for the support and also for the great product!

**Comment by chenweiyj** [comment]
I met the same problem of running `sails www`, which produces `sails is not defined` error.
