### ISSUE TITLE
jst.js is not being generated in .tmp\public folder, on app startup

### ISSUE THREAD

**Issue by muradaliyev** [balderdashy/sails#3437]
Not sure exactly why this is happening, but moving 'jst:dev' under 'copy:dev' in compileAssets.js fixes the problem. Noticed on 0.12RC3

```javascript

//tasks\register\compileAssets.js

module.exports = function (grunt) {
	grunt.registerTask('compileAssets', [
		'clean:dev',
		'less:dev',
		'copy:dev',
		'jst:dev',  // <-- moved after copy:dev
		'coffee:dev'
	]);
};
```

**Comment by einfallstoll** [comment]
I figured out, that the server has to be lifted twice, because it tries to create the templates, but they're not there yet. After this step they'll get moved and/or created.

**Comment by muradaliyev** [comment]
Not sure about this. I've noticed, that jst.is is generated "on the fly", I.e. when sails is started and template file is being saved, but not at the moment of actual server lifting.
Will try to check this again.

**Comment by muradaliyev** [comment]
Just found the same issue a bit down the list:

https://github.com/balderdashy/sails/issues/3367

**Comment by sgress454** [comment]
Thanks @muradaliyev, closing in favor of #3367.
