### ISSUE TITLE
How to use wateline to execute Stored Procedure ?

### ISSUE THREAD

**Issue by Messilimeng** [balderdashy/sails#3438]
Hi I want to use the Waterline Query Language and mysql, but I don't know how to execute stored procedure in Mysql DB.

**Comment by foobar8675** [comment]
I've not done it, but you could try executing it like a normal query

**Comment by crh3675** [comment]
Model.query(sql, []. function(err, result) {
    });

Note that *Model* means nothing when running the query method

**Comment by Messilimeng** [comment]
thanks @crh3675 @foobar8675
