### ISSUE TITLE
Unable to set bodyParser option

### ISSUE THREAD

**Issue by LobeTia** [balderdashy/sails#3441]
Hello everyone, I'm using sails 0.11.3

In some of my view there're file input that are optional, I didn't found a way to handle not uploaded file so I wanna lower maxTimeToBuffer of the bodyParser

I've got a problem with _config.http.middleware_
I'm trying to set maxTimeToBuffer to the default bodyParser but it seems to not work

        bodyParser: {
            fn: require("skipper"),
            options:{
                maxTimeToWaitForFirstFile: 100,
                maxTimeToBuffer: 500
            }
        }

It seem's that Sails isn't passing the options info to the bodyParser constructor
Any idea about this?

Thank you

**Comment by ericnograles** [comment]
@LobeTia It looks like you're not returning skipper in the block of code above.  Try this?

```
bodyParser: (function () {
    var opts = {
        maxTimeToWaitForFirstFile: 100,
        maxTimeToBuffer: 500
    };
    var fn;

    fn = require('skipper');
    return fn(opts);
})
```

**Comment by crh3675** [comment]
@ericnograles good feedback.  How would one figure out how to integrate correctly?

**Comment by mikermcneil** [comment]
@LobeTia I'll assume the approach suggested by @ericnograles work for you-- let us know if you run into any further problems.  Thanks everyone for their help.

**Comment by garrettjoecox** [comment]
Still not able to get this working, tried the solutions above and on the docs.. Frustrating..
