### ISSUE TITLE
Running sails.js in Xvfb

### ISSUE THREAD

**Issue by sriducati** [balderdashy/sails#3446]
Iam using nightmare script which should be executed through xvfb always...

      xvfb-run node cnn.js 

how do I implement the same in sails js?I assume sailsjs Implement

     node cnn.js
to process the request ...but this does not outputs anything...I have to use the same script to fetch the output through ajax and display it on UI,Do i need to make changes in app.js or settings?

**Comment by sgress454** [comment]
HI @sriducati, thanks for using Sails!

This forum is for reporting bugs in the Sails core.  For questions like this, please try our [Google Group](https://groups.google.com/forum/#!forum/sailsjs), [live chat](https://gitter.im/balderdashy/sails?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [StackOverflow](http://stackoverflow.com).
