### ISSUE TITLE
sails no-frontend creates EJS warning

### ISSUE THREAD

**Issue by crh3675** [balderdashy/sails#3455]
I was running a Sails application using `--no-frontend`. Upon startup, this message occurs:

```
Could not find module: ejs in path: /opt/wx-api/node_modules
```
I updated the `config/views.js` as follows to supress:

```
engine: { ext : 'null', fn : function(){} },
```
Everything works fine just questioning if there is another way.

Also, when running Mocha using `sails.lift()` from within tests, the application complains that it can't find Grunt.  I installed as a devDependency but would like to remove if I can.

<pre><code>
var Sails = require('sails');

process.chdir(APPLICATION_PATH);

before(function(done){

   this.timeout(5000);

   Sails.lift({
       port : 12345,
       log: {
           level: 'error'
       }

   }, function(err, app) {

       sails = app;
       
       if (err) return done(err);

       done(err, sails);
   });
});
</code></pre>

**Comment by crh3675** [comment]
Update: I just added

```
hooks : { grunt : false }
````

to Sails.lift(options) and was able to remove

**Comment by mikermcneil** [comment]
@crh3675 re: grunt-- spot on.  You can also stick that in your .sailsrc file or configure it via env variables (e.g. `sails_hooks__grunt=false sails lift`).  

re: views, what version of NPM and Sails are you using?  We were relying on the nested node_modules structure prior to NPM 3 (i.e. to symlink the `ejs` dep in sails so you don't have to `npm install` when running `sails new`).  The latest 0.12 rc just sticks copies the dependency down, but I'm curious if there's a bug there that's only showing itself when the no-frontend option is enabled.

Thanks!

**Comment by mikermcneil** [comment]
This issue was moved to balderdashy/sails-generate-new#21

**Comment by cyrilchapon** [comment]
sails-generate-new has no "issues", has it ?

**Comment by renegat59** [comment]
I confirm, created a project with --no-frontend, the .sailsrc gets:
`{
  "hooks": {
    "grunt": false
  }
}`
but the error persists. Sails 0.12.8, npm 3.5.2. Any workaround for this?

**Comment by fortil** [comment]
I have the same problem, but I don't know how solve it
