### ISSUE TITLE
Constant File

### ISSUE THREAD

**Issue by umair321** [balderdashy/sails#3456]
I need to add some constants in my project. Can you please tell me where is constant file and how can I use it?

**Comment by aars** [comment]
sailsjs does not support ES6 and therefor constants out of the box. There is a babel hook you can install to use ES6 features like constants. https://github.com/artificialio/sails-hook-babel

But considering your question for a constants *file* this might not be what you want/need.

There a a couple of config files in `/config` that might be of interest.

**Comment by umair321** [comment]
Thanks for your reply, I have solved in this way:
Made a new file "constants.js" in config
then add this code there:

module.exports.constants = {
    jwt_seceret: 'ssshhh'
     server_info: {
       url: "foo"
     }
};

now call it using:

sails.config.constants.jwt_seceret

etc

**Comment by aars** [comment]
I'd suggest putting the JWT secret in an environment variable instead of a file for security reasons. But apart from that, good! Could you close this issue?

**Comment by umair321** [comment]
yes, sure. I respect your suggestion.

**Comment by mikermcneil** [comment]
@aars thank you!

@umair321 the config approach works great for these sorts of credentials but as @aars, it's usually not the best idea to check in credentials such as these into your repository (unless you're fine with everyone with access, and everyone who might ever have access, being able to see them-- which is ok sometimes too.)

**Comment by umair321** [comment]
I am agree with both of you and will take care about it from my next projects.
