### ISSUE TITLE
Extend req object

### ISSUE THREAD

**Issue by adampietrasiak** [balderdashy/sails#3458]
I'd like to add methods to req object to be reusable later on in controller actions.

I was trying to do it in config/bootstrap.js file with 

    require('http').ClientRequest.prototype.permit = function(){
  	    //custom code
    };`

But .permit method is still not avaliable inside actions as req.permit

Where should I do that?

**Comment by dudemelo** [comment]
Try [Hook](http://sailsjs.org/documentation/concepts/extending-sails/hooks) or [Policies](http://sailsjs.org/documentation/concepts/policies).

**Comment by crh3675** [comment]
Policies are the easiest:

````
module.exports = function hasPermission(req, res next) {
   req.permit = function() {
      return true;
   }
   next();
}
```

**Comment by mikermcneil** [comment]
Great feedback from @crh3675 and @dudemelo, thanks y'all.  @adampietrasiak something else to keep in mind is that if you modify the core `req` prototype, it will only affect HTTP requests (not virtual websocket requests), and it will leak into any other dependencies/middleware you hook up.  I'd add that you probably want to start with a policy, and then if you find yourself needing more flexibility, switch to a hook.  Good luck!

**Comment by adampietrasiak** [comment]
@crh3675 I was aware of this solution, but it assign function on each request, while it should be attached only once during boot up, thats why I was looking for access to request class prototype, not to single request instance.

**Comment by Josebaseba** [comment]
@adampietrasiak https://github.com/Josebaseba/sails-hook-validator/blob/master/index.js
