### ISSUE TITLE
The static js file in ./tmp/public folder is different from the js file serving in web browser?

### ISSUE THREAD

**Issue by vucuong12** [balderdashy/sails#3465]
I have above problem. I guess it is because of the grunt-rename task I use, but I am not quite sure about that. The static files in ./tmp/public folder are always the same as the files serving in the web browser, aren't they?

**Comment by sgress454** [comment]
I'm not sure I quite understand the issue you're having, but the files in `.tmp/public` are the static files that  are served by Sails, yes.  Under normal circumstances, if you put a `foo.txt` file in the `/assets` subfolder of a Sails project, then when you do `sails lift`, that file will be copied to `.tmp/public/foo.txt`, and will be available at `http://localhost:1337/foo.txt`.  If you have a task that renames files before they're copied to `.tmp/public`, then the new name is what will be served.

Closing this for now as it's doubtful that this is a bug in Sails core.  If you believe you're experiencing a bug in Sails, please post a link to your project here, along with info about your Sails and Node version, and we'll take a look!

**Comment by Wizzercn** [comment]
static path ....
config/http.js

module.exports.http = {
  customMiddleware: function (app) {
    app.use('/upload', require('../node_modules/sails/node_modules/express')['static'](require('path').normalize(__dirname + '/../upload')));
  },
