### ISSUE TITLE
How to set up query params to search in object properties?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [balderdashy/sails#3467]
I can create my own method to search items by object property. Like  this.
```
sails.models.hackers.find({'about.rank': 500}).exec(function(err, found){
     res.json(found)
})
```
And it works great. But I didn't find the way to set up ***get*** params. 
I tried to make it via url encoding, like this
```
http://95.213.199.70/api/hack/find?where%3D%7B%22about%22%3A%7B%22rank%22%3A500%7D%7D
which is 
http://95.213.199.70/api/hack/find?where={"about":{"rank":500}}
```
And tried without ***where***
```
http://95.213.199.70/api/hack/find?about%3D%7Brank%3A500%7D%7D
which is 
http://95.213.199.70/api/hack/find?about={rank:500}}
```
```
http://95.213.199.70/api/hack/find?about.rank=500
```

**Comment by japel** [comment]
@AlexanderKozhevin 
The right way to query subobject attributes is same as mongodb, you have to pass them as dot-notated strings:
so your get request would look like this:
http://95.213.199.70/api/hack/find?where={"about.rank":500}
check if that solves your issue.

**Comment by japel** [comment]
btw. your api is publicly accessible, do you really want that?

**Comment by AlexanderKozhevin** [comment]
@japel Thanx.
Yeap. That's good. Strange, it doesn't with url encoded. 
Yes, the server is public right now. But i'm using it just for minor test.
