### ISSUE TITLE
Error: Cannot find module 'buffer-crc32' on Sails install

### ISSUE THREAD

**Issue by parkeragee** [balderdashy/sails#3472]
Missing a module on a clean Sails install.

`Error: Cannot find module 'buffer-crc32'`

**Comment by mikermcneil** [comment]
@parkeragee looking into it-- 0.11.4?

**Comment by mikermcneil** [comment]
@parkeragee ran this test on different machines in different locations on different versions of Node and NPM and couldn't replicate this exact problem.  However there do seem to be some anomalies going on with NPM at the moment (we noticed other issues that were intermittent).

**Comment by mikermcneil** [comment]
@parkeragee would you mind trying again and letting us know if you still see the issue?

**Comment by mikermcneil** [comment]
https://twitter.com/parkeragee/status/687814979882500096

**Comment by parkeragee** [comment]
Installing the package solves the issue. Not sure if it was a Sails issue or El Capitan upgrade issue.
