### ISSUE TITLE
Issue with middleware?

### ISSUE THREAD

**Issue by zaiddag** [balderdashy/sails#3477]
I'm pretty sure this is just a docs problem or something, but I added morgan logging middleware, and the middleware is never hit

I added the middleware funcs to config.http.middleware and added their keys to middleware.order

```javascript
var morgan = require('morgan')
var fs = require('fs')

module.exports.http = {
  middleware: {

    'morganfile':function(req, res, next) {
      console.log('got middleware hit')
    },
    'morganconsole':morgan('combined'),

    order: [
       'startRequestTimer',
       'cookieParser',
       'session',
       'myRequestLogger',
       'bodyParser',
       'handleBodyParserError',
       'compress',
       'methodOverride',
       'poweredBy',
       '$custom',
       'router',
       'www',
       'favicon',
       '404',
       '500',
       'morganfile',
       'morganconsole',
       'maybefail'
     ],
};
```

**Comment by mikermcneil** [comment]
Hey @zaiddag, we'll take a look at this asap.

**Comment by mikermcneil** [comment]
@zaiddag Update: I wasn't able to replicate any issue with middleware itself on the latest stable release (v0.11.4) using a simplified acceptance test (i.e. it logged once per request):

```javascript
module.exports.http = {

  /****************************************************************************
  *                                                                           *
  * Express middleware to use for every Sails request. To add custom          *
  * middleware to the mix, add a function to the middleware config object and *
  * add its key to the "order" array. The $custom key is reserved for         *
  * backwards-compatibility with Sails v0.9.x apps that use the               *
  * `customMiddleware` config option.                                         *
  *                                                                           *
  ****************************************************************************/

  middleware: {


    foobar: function (req, res, next) {
      console.log('Ran foobar HTTP middleware!');
      return next();
    },


  /***************************************************************************
  *                                                                          *
  * The order in which middleware should be run for HTTP request. (the Sails *
  * router is invoked by the "router" middleware below.)                     *
  *                                                                          *
  ***************************************************************************/

    order: [
      'startRequestTimer',
      'cookieParser',
      'foobar',
      'session',
      'myRequestLogger',
      'bodyParser',
      'handleBodyParserError',
      'compress',
      'methodOverride',
      'poweredBy',
      '$custom',
      'router',
      'www',
      'favicon',
      '404',
      '500'
    ],
};
```

**Comment by sgress454** [comment]
Hi @zaiddag, anything you put after `404` in the `order` array is unlikely to be run.  The `404` middleware catches all requests that don't match anything else.

**Comment by mikermcneil** [comment]
@zaiddag taking a closer look though, it appears that you have this after your final handler middleware--- ah @sgress454 beat me to it

**Comment by sgress454** [comment]
:clap: tag team!

**Comment by mikermcneil** [comment]
@sgress454 :house:  :bread: 

@zaiddag if you you try moving morgan up to where `myRequestLogger` is, I think you'll get the desired effect.

More docs available here:
+ http://sailsjs.org/documentation/concepts/middleware
+ http://sailsjs.org/documentation/reference/configuration/sails-config-http#?properties


@zaiddag ^^ however I noticed after looking over those docs that none of them really properly explain what the `order` is really doing.  Basically, the way http middleware works in Sails/Express is this:

1. an HTTP request comes in
2. plop into the first middleware (`startRequestTimer`)  When that middleware calls `next()`...
3. plop down down to the next middleware in the configured `order` -- i.e. `cookieParser()`.  When that middleware calls `next()`...
... and so forth.

The reason why 500 is at the very end is an artifact of how express handles the middleware chain.  If an HTTP middleware function has a fourth argument after `next()`, it is understood to be a catchall error handler.  In our order, we put 500 at the very end for clarity.  Right above it is `404`, a normal middleware (3 arguments), that is the very last normal middleware in the `order`.  This is used when absolutely nothing matches a requested URL (e.g. if you're maintaining an e-commerce API for a doorknob manufacturer, the `404` middleware might run if someone is sending requests `POST /portholes/37/break?with=hammer` or `DELETE /kleenexbox/1048`).

**Comment by mikermcneil** [comment]
@zaiddag One other quick example to help clarify what the `order` config is really doing (going with the `order` shown in the docs [here])(http://sailsjs.org/documentation/concepts/middleware#?adding-or-overriding-http-middleware):  

When an HTTP request comes in, first Sails takes a snapshot of the current `new Date()` and stores it on the [snowballing](http://prezibase.com/wp-content/uploads/2015/05/snowball-effect-animated-prezi-template-downhill.gif) request object for later use when determining how long it took to respond to this request.  Next, the `cookieParser` runs, which takes the raw cookie string from the HTTP request header and crumbles it into a delicious dictionary called `req.cookies`.  Next the session middleware runs.  This has a lot of things in it (and wow this story is getting out of hand quickly) but basically it takes care of adding the `.session` property to `req` (using the conventional sails.sid cookie that was made available on `req.cookies` when the cookieParser ran).  I'll stop here before this story gets any stranger, but hopefully that helps communicate the idea of how the placement of these middleware within `order` affects the behavior of your incoming HTTP requests.

If anyone has any ideas on how to make this more understandable from reading the docs without using my horrible meandering story, it'd be awesome to have some clearer language explaining how this stuff works in sails-docs ([conceptual](https://github.com/balderdashy/sails-docs/blob/master/concepts/Middleware/Middleware.md)) ([reference](https://github.com/balderdashy/sails-docs/blob/master/reference/sails.config/sails.config.http.md)).

Thanks!

**Comment by zaiddag** [comment]
Wow lol I'm retarded ty :)
