### ISSUE TITLE
Who is behind Sails?

### ISSUE THREAD

**Issue by Verdier** [balderdashy/sails#3478]
Hi, looks like there is some trouble concerning Balderdash?! I see in many recent commits that copyright move from Balderdash to @mikermcneil. What is http://balderdash.co/ vs http://balderdash.io/ and who is @tjwebb and what is trails? 

We use sails in production and we would be a bit reassured if we could understand the actual situation. 

Thanks!

**Comment by RWOverdijk** [comment]
@Verdier I'm not going to share the specifics, as it's not my place. I'm sure @mikermcneil will do that.

What I can tell you, is that sails is sails. I was in doubt for a while, too. But I got reassured and I'm still here. There was a minor misunderstanding with a short-term sails contributor (that's where @tjwebb comes in), who then decided to start trails (which isn't affiliated to, and has nothing to do with, sails). Sails is alive and kicking and this little misunderstanding has mostly been cleared up.

You can sleep in peace :)

**Comment by mikermcneil** [comment]
Thanks @RWOverdijk!
@Verdier see also https://github.com/balderdashy/sails/issues/3429#issuecomment-168801414

**Comment by mikermcneil** [comment]
@Verdier also, to answer your question directly, `balderdash.io` is a domain owned by Travis Webb.  It is not affiliated with Balderdash, Treeline, or [our team](https://github.com/balderdashy/sails#team).  Unfortunately, misleading statements have been made about the Trails fork which caused some major confusion in our community. The updates I've made recently to our README and contribution guide are to help clarify the facts:
+ Trails is not affiliated with Sails or our team.
+ Only one person left the Sails.js project to create Trails: Travis Webb; someone who joined the Sails project fairly recently as a [contributor](https://github.com/balderdashy/sails/graphs/contributors) in 2015.
+ The [core team](https://github.com/balderdashy/sails#team) and I are 100% committed to the continued development and support of Sails and Waterline.  We currently use the latest stable release of Sails in production, as do many other companies and developers all over the world.

I hope that helps provide some closure for you guys and other folks landing on this issue in the future from search engines.  If you still have concerns about the health of the community, the status of the project, the future of the framework, or any other strategic questions about Sails, our team, or our mission, please [don't hesitate to contact me directly](mailto:mission@treeline.io).
