### ISSUE TITLE
[0.11] Error using connect-mongo as session adapter

### ISSUE THREAD

**Issue by commandline** [balderdashy/sails#3486]
With v0.11.4, getting this on lifting:
```
error: A hook (`session`) failed to load!
verbose: Lowering sails...
verbose: Shutting down socket server...
verbose: Shutting down HTTP server...
error: Could not load Connect session adapter :: connect-mongo
(If this is your module, make sure that the module has a "main" configuration in its package.json file)
Error from adapter:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at Hook.SessionHook.initialize (/Users/cmdln/src/git/tower/service/node_modules/sails/lib/hooks/session/index.js:162:48)
    at Hook.bound [as initialize] (/Users/cmdln/src/git/tower/service/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /Users/cmdln/src/git/tower/service/node_modules/sails/lib/hooks/index.js:74:14
    at /Users/cmdln/src/git/tower/service/node_modules/async/lib/async.js:451:17
    at /Users/cmdln/src/git/tower/service/node_modules/async/lib/async.js:441:17
    at _each (/Users/cmdln/src/git/tower/service/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/Users/cmdln/src/git/tower/service/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Do you have the Connect session adapter installed in this project?
Try running the following command in your project's root directory:
npm install connect-mongo
(Note: Make sure the version of the Connect adapter you install is compatible with Express 3/Sails v0.10)
```
connect-mongo is installed, version 1.1.0. The problem seems to stem from lib/hooks/session/index.js where it is loading the package file for connect-mongo then attempting a path.resolve on the ```main``` property on that require. ```main``` is undefined.

Looking at master, the session code looks different so apologies if this is/will be resolved in v0.12. Downgrading connect-mongo to 0.8.2 seems to have resolved this so it appears to be a dependency interaction rather than specifically a Sails problem.

**Comment by mikermcneil** [comment]
Thanks for the detailed notes @commandline - looking into it now.

**Comment by mikermcneil** [comment]
Ok, so after chatting with @sgress454 about https://github.com/balderdashy/sails/commit/72fb1d6b5e7ee4604ef15df2a2f8a490150f5b9d, we're pretty sure what you're seeing is because the new version of connect-mongo does not have a `main` in its package.json file.

In the mean time, I'll update http://sailsjs.org/documentation/reference/configuration/sails-config-session for the docs currently online so that folks know to use connect-mongo@0.8.2.

@commandline Thank you!

**Comment by mikermcneil** [comment]
Sorry! Just realized I didn't even clarify the most important part in my comment- **yes** this is fixed in 0.12.  @commandline would you mind giving this a go with the latest release candidate of Sails, v0.12.0-rc5 (`npm install sails@beta`), to verify that this works w/ connect-mongo 1.1.0 for you?

**Comment by mikermcneil** [comment]
I just updated the [session config docs](https://github.com/balderdashy/sails-docs/commit/fdad9983f9cd1300886b66f4facb67af18a93fb0), and we'll merge and deploy to the Sails website in the next few hours.  @commandline I believe we're ready to close this issue if/when we hear back from you confirming that everything is ship-shape in the 0.12 prerelease release I published earlier (rc5).  Thank you!

**Comment by commandline** [comment]
I will try to get you feedback on a test with connect-mongo@1.1.0 and sails@0.12.0-rc5 later today. Thanks for the quick response!

**Comment by commandline** [comment]
Oh, and any ETA on 0.12.0 going live? We'll need to keep connect-mongo pinned regardless of the fix as we don't use beta, even rc code, in production. Would be nice to have a sense when we can update both packages.

**Comment by mikermcneil** [comment]
@commandline we cracked into some work on the sockets hook and we want to make sure gets done before releasing 0.12, but I'd say it's still almost certainly looking like it'll be before the end of the month.  And don't worry, definitely wouldn't suggest using any -rc in production!  Just good to have some outside verification to rule out any issues we're missing on this side.  Appreciate your help.

Side note re: pinning dependencies:  you may already be doing this, but just a suggestion: I'd keep your connect-mongo pinned in production regardless even after the update (it's way too easy to end up inheriting a problematic/accidental breaking change in a dependency when you deploy).

**Comment by commandline** [comment]
Yeah, we have two projects, one already uses npm-lockdown for exactly this reason. The other we just haven't had the time, so we don't have to manually pin each dependency, we can just local an entire graph based on a known good set.

**Comment by commandline** [comment]
I am having some npm caching issues that clearing the cache isn't solving. I will try to get the latest rc installed, tomorrow, and get you that feedback.

**Comment by mikermcneil** [comment]
@commandline thanks for the help! There are some tips on busting the npm cache to get a clean dep. install in the [new contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#opening-an-issue).

Beyond what's there, I've had to go and delete modules from `usr/local/lib/**` and `~/.npm/**` in the past to solve caching issues related to different npm versions (especially due to symbolic links).  Not sure if that helps here, but it's a start anyway.  Good luck!

**Comment by commandline** [comment]
The original problem does not recur with connect-mongo@1.1.0 and sails@beta (which at time of testing was rc6.) I am running into a problem with one of my models later on in the start up, though, but I think that is separate from what I original reported here.

**Comment by mikermcneil** [comment]
@commandline ok, great to hear (mostly!)  Really appreciate the follow-up.

btw still paused on the docs redeploy to sailsjs.org for a bit longer (we're about halfway through fixing the formatting on the conceptual overview for generators) but hoping to get them up soon.  Sorry about the delay (updating GitHub in the mean time).

**Comment by mikermcneil** [comment]
(btw @commandline if you still see that separate model issue, please let us know)

**Comment by mikermcneil** [comment]
@commandline also to wrap up re: 0.12:  we quietly published yesterday. The migration guide and 0.12 docs are live now, and we'll be following up with patches / doc improvements in the coming days.  We're planning to post some more background info on the changes (particularly re: socket methods) as well as some improved documentation for scaling a Sails app that uses sockets (as well as for scaling socket.io in general).

**Comment by commandline** [comment]
I am having all kinds of problems with sane/sails-hook-babel and both 0.11.5 and 0.12.0. I have opened issues but am completely stymied as to what and why this broke when all I did was a fresh install at first which picked up 0.11.5 because apparently 0.11.4 is no longer available.

https://github.com/sane/sails-hook-babel/issues/13
https://github.com/balderdashy/sails/issues/3576

**Comment by mikermcneil** [comment]
@commandline Sorry to hear you're having problems. You can install 0.11.4 by running `npm install sails@0.11.4 --save --save-exact`.  Hope that helps!
