### ISSUE TITLE
sails.sockets.broadcast() causes pingTimeout on SSL sockets

### ISSUE THREAD

**Issue by odnarb** [balderdashy/sails#3491]
I've tested this with nginx SSL termination as well as normal/native sails.js SSL.

Server
-------------------
ubuntu 14.04
node: v5.3.0
npm: v3.3.12
Clean install of sails@0.11.4
Nginx proxy setup with ip_hash defined in upstream app and with
    location / {
        client_max_body_size 1000M;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://myapp;
    }

Client
--------------
socket.io-client@1.4.4
sails.io.js@0.12.2
Client is a node.js script initiated with:
```
var socketIOClient = require('socket.io-client');
var sailsIOClient = require('sails.io.js');
var io = sailsIOClient(socketIOClient);
io.sails.url = 'https://mydomain.com';
io.sails.environment = 'production';
io.socket.on('connect', function(data){
            io.socket.get('/joinroom', function (cpx, JWR) {
});
```

I have the client socket join a room via the `/joinroom` controller with `sails.sockets.join(req.socket, 'foo');`

When I use a non-SSL connection and then the server performs a broadcast, the connection on both ends are stable and stay alive.

When I use an SSL connection (self-signed), the server performs the broadcast successfully, received by the client just fine, and after a minute the server dumps the client, without letting the client know..or at least that's what it seems like on the client side, it seems to just stay open, thinking the connection is okay.

What seems to happen is a pingTimeout is triggered with the pingTimeoutTimer function in what seems to be engine.io.

Any insight might be helpful. I'm happy to expand on specifics.

Thanks!

**Comment by mikermcneil** [comment]
@odnarb thanks for the detailed info.  Looping in @sgress454 on this since he's currently working on the sockets hook.  In the mean time, to troubleshoot a bit here: have you had any issues with this on older versions of Sails, or is 0.11.4 the first version in which you've tried this?  No worries either way, but it'll help to know.  Thanks!

**Comment by mikermcneil** [comment]
@odnarb also, which `transports` do you have configured?

**Comment by sgress454** [comment]
@odnarb Just to clarify, are you only seeing this issue after doing a broadcast?

**Comment by mikermcneil** [comment]
@odnarb one more thing (sorry to blow up your inbox!) to help in your debugging efforts:

We [default the `pingTimeout` to 60s](https://github.com/balderdashy/sails-hook-sockets/blob/master/lib/defaults.js#L95) which is also the [implicit default for engine.io](https://github.com/socketio/engine.io#methods-1).  Assuming this is happening even on a single instance using built-in sails/express/socket.io SSL support, it could be that some intermediate proxy is causing issues and increasing this timeout config would help (however with secure sockets, this isn't normally a problem). Here's [how you do that](http://sailsjs.org/documentation/reference/configuration/sails-config-sockets#?advanced-configuration) just in case.  But if this is happening when you have multiple node processes or servers and/or are using the cluster module, then it's probably unrelated.

**Comment by odnarb** [comment]
Thank you for the replies!

Addressing them in order:
@mikermcneil I will have to confirm if this issue is on any older versions of sails. I just did an upgrade on a branch to sails v0.11.4. The earliest I can go back to since there really weren't any changes to my codebase pertaining to this functionality is about 9-10 months. That might be in the 0.10.x stack. Not sure. If that helps I will be happy to do so, but I think my time at work is running short for hunting this down.

@mikermcneil Both polling and websockets are configured on sails, but the current thing that seems to work for this client setup I'm using is polling. If I exclude polling from the sockets.js config my client simply cannot connect.

@sgress454 I haven't tried .emit() or other ways to communicate. Which others shall I try for degbugging purposes?

@mikermcneil I'm using a Windows machine for the socket client and an Ubuntu VM on the same host for the server. It's a bridged network adapter. So yea, I hope there's no proxy! This also happens with a setup where I have multiple sails instances (non-forked) lifted and sitting behind the nginx proxy (on the same server of course)

Thanks again!

**Comment by sgress454** [comment]
@odnarb re: using other methods, I was more wondering whether the server disconnects the socket after timeout regardless of whether _any_ communication has taken place.  That is, if you have a client connection and you just let it sit there for 60 seconds and don't do _anything_, does it stay connected or does it disconnect?  Trying to determine whether this actually has anything to do with socket _communication_, or just a problem with the connections in general.

**Comment by odnarb** [comment]
This is definitely only happening after the fact something is sent. If I just let it stay there, the connection is stable and stays open.

**Comment by odnarb** [comment]
Well, I tracked it down to some bad code on my end. Thanks for the replies, they were very helpful.

I really thought this was an issue since I thought I had tested my previous code thoroughly.

**Comment by sgress454** [comment]
@odnarb Glad you worked it out. Feel free to post any relevant details if you think someone else might encounter a similar issue!
