### ISSUE TITLE
sails@0.12.0-rc6  plus sails-mongo@0.11.5 causes Error: The connection o specified in model_menu does not exist!

### ISSUE THREAD

**Issue by rasekar2000** [balderdashy/sails#3492]
in sails model

      module.exports = {
	   schema : true,
	   connection: 'mongoDB',
	   attributes: {
	   	user_id: 'string',
           }
      }

in config/connections.js

    mongoDB: {
    adapter: 'sails-mongo',
    host: process.env.MONGO_DB_HOST ||'localhost',
    port: process.env.MONGO_DB_PORT || 27701,
    user: process.env.MONGO_DB_USER ||'',
    password: process.env.MONGO_DB_PWD ||'',
    database: process.env.MONGO_DB_NAME ||'mdb'
  },

This is causing an error

      Thu Jan 14 2016 20:27:23 GMT+0000 (UTC) silly: Registering model `user` in Waterline (ORM)
      /home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:101
        throw new Error(msg);
            ^
      Error: The connection o specified in model_menu does not exist!
        at            /home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:101:13
    at Array.forEach (native)
    at _getConnections      (/home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:96:35)
    at new module.exports (/home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:23:32)
    at loadCollection (/home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline.js:111:18)
    at /home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at /home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:230:13
    at _arrayEach (/home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at _each (/home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (/home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (/home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
    at Array.async.auto.loadCollections (/home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline.js:125:13)
    at /home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (/home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at Object.async.auto (/home/sails/mysite/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:552:9)
    at Waterline.initialize (/home/sails/mysite/node_modules/sails/node_modules/waterline/lib/waterline.js:121:9)
sails@15c51190e134:~/mysite$ pwd      

And hence reviewed the installation 

      ├── sails@0.12.0-rc6 (cookie-signature@1.0.6, cookie@0.1.2, grunt-contrib-copy@0.5.0, connect-flash@0.1.1, pluralize@1.2.1, mock-req@0.2.0, mock-res@0.3.0, consolidate@0.12.1, colors@1.1.2, uid-safe@1.1.0, semver@5.1.0, commander@2.9.0, walk@2.3.9, async@1.5.0, rc@1.0.1, express-session@1.12.1, method-override@2.3.5, glob@5.0.15, ejs@2.3.4, i18n@0.5.0, ejs-locals@1.0.2, fs-extra@0.18.4, grunt-contrib-cssmin@0.9.0, sails-build-dictionary@0.10.1, prompt@0.2.14, sails-stringfile@0.3.2, merge-defaults@0.2.1, reportback@0.1.9, connect@2.30.0, grunt-cli@0.1.13, captains-log@0.11.11, sails-hook-sockets@0.13.0, express@3.21.2, skipper@0.5.9, sails-util@0.11.0, grunt-contrib-uglify@0.7.0, express-handlebars@2.0.1, sails-generate@0.12.4, grunt-contrib-less@1.1.0, anchor@0.10.5, waterline@0.10.30)
          └   

older configuration

    "sails": "~0.12.0-rc3",
    "sails-disk": "~0.10.7",
    "sails-hook-autoreload": "^0.11.5",
    "sails-hook-winston": "^0.2.0",
    "sails-mongo": "^0.11.2",
    "sails-redis": "^0.10.3",

reverted back to exact configuration and it works fine .. 

        "sails": "0.12.0-rc3",
        "sails-disk": "0.10.7",
        "sails-hook-autoreload": "^0.11.5",
        "sails-hook-winston": "^0.2.0",
        "sails-mongo": "0.11.2",
        "sails-redis": "0.10.3",

Please review and let me know , if this is an issue or works fine for everyone else.

Thanks.

**Comment by mikermcneil** [comment]
Hi @rasekar2000 - thanks for taking the time to test w/ both versions and reproduce the issue in an isolated way, that helps a lot.  Looking into it.

**Comment by mikermcneil** [comment]
@rasekar2000 would you mind trying this out with the versions pinned to sails `0.12.0-rc6` and sails-mongo `0.11.2`  (i.e. no `^` or `~`)?  That'll help figure out whether the issue you're seeing is coming from sails-mongo, sails, or an interaction of both.

(btw, I just added some updated info for troubleshooting / doing sanity checks on versions from npm installs [here](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#opening-an-issue) in case that's helpful)

**Comment by mikermcneil** [comment]
Just took a look, and while there was a minimum patch release bump of the Waterline dep between [rc3](https://github.com/balderdashy/sails/blob/v0.12.0-rc3/package.json#L82) and [rc6](https://github.com/balderdashy/sails/blob/v0.12.0-rc6/package.json#L82), since the semver range in Sails' package.json was using `~`, the same version of Waterline _should_ be getting npm installed regardless.  So based on that, my hunch is that this is something that changed in sails-mongo  (the results of the experiment in my previous comment should give us the final answer there).

**Comment by rasekar2000** [comment]
@mikermcneil  Let me review.

**Comment by rasekar2000** [comment]
Testing with **sails 0.12.0-rc3** & **sails-mongo@0.11.5** as it was released few months back .. This installs **waterline@0.10.30** and it **worked fine** .. more details below..

in package.json 

        "sails": "0.12.0-rc3",
        "sails-disk": "0.10.7",
        "sails-hook-autoreload": "^0.11.5",
        "sails-hook-winston": "^0.2.0",
        "sails-mongo": "0.11.5",
        "sails-redis": "0.10.3",

on installation

    sails@0.12.0-rc3 node_modules/sails
	├── sails-build-dictionary@0.10.1
	├── cookie-signature@1.0.6
	├── cookie@0.1.2
	├── pluralize@1.1.6
	├── connect-flash@0.1.1
	├── mock-req@0.2.0
	├── mock-res@0.2.1
	├── sails-stringfile@0.3.2
	├── merge-defaults@0.2.1
	├── consolidate@0.12.1
	├── node-uuid@1.4.7
	├── uid-safe@1.1.0 (native-or-bluebird@1.1.2)
	├── async@0.9.2
	├── commander@2.7.1 (graceful-readlink@1.0.1)
	├── walk@2.3.9 (foreachasync@3.0.0)
	├── reportback@0.1.9 (merge-defaults@0.1.4, switchback@1.1.3)
	├── colors@1.0.3
	├── semver@4.3.6
	├── ejs-locals@1.0.2
	├── method-override@2.3.5 (methods@1.1.1, vary@1.0.1, parseurl@1.3.0, debug@2.2.0)
	├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
	├── i18n@0.5.0 (sprintf@0.1.5, debug@2.2.0, mustache@2.2.1)
	├── fs-extra@0.18.4 (jsonfile@2.2.3, graceful-fs@3.0.8, rimraf@2.5.0)
	├── grunt-cli@0.1.13 (resolve@0.3.1, nopt@1.0.10, findup-sync@0.1.3)
	├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.8.3, utile@0.2.1)
	├── lodash@2.4.2
	├── captains-log@0.11.11 (merge-defaults@0.1.4, colors@0.6.2, rc@0.3.5, lodash@2.4.1)
	├── sails-util@0.10.6 (json-stringify-safe@5.0.1, switchback@1.1.3, fs-extra@0.8.1, underscore.string@2.3.3)
	├── express@3.20.2 (basic-auth@1.0.0, merge-descriptors@1.0.0, utils-merge@1.0.0, methods@1.1.1, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.3, vary@1.0.1, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.1.3, etag@1.5.1, proxy-addr@1.0.10, mkdirp@0.5.0, send@0.12.2, connect@2.29.1)
	├── skipper@0.5.9 (string_decoder@0.10.31, dot-access@1.0.0, async@1.4.2, colors@1.1.2, debug@2.2.0, semver@5.0.3, skipper-disk@0.5.4, multiparty@3.2.10, connect@2.30.2)
	├── express-handlebars@2.0.1 (graceful-fs@3.0.8, promise@6.1.0, object.assign@1.1.1, handlebars@3.0.3)
	├── sails-generate@0.12.4 (sails-generate-api@0.10.0, merge-defaults@0.1.4, sails-generate-gruntfile@0.10.10, async@0.2.10, sails-generate-adapter@0.10.5, sails-generate-generator@0.10.11, sails-generate-views-jade@0.10.3, sails-generate-views@0.10.6, sails-generate-sails.io.js@0.12.3, fs-extra@0.8.1, sails-generate-backend@0.12.3, sails-generate-frontend@0.11.6, sails-generate-controller@0.10.8, sails-generate-model@0.10.10, sails-generate-new@0.10.24)
	├── sails-hook-sockets@0.11.29 (machinepack-urls@3.1.1, socket.io@1.3.7, socket.io-client@1.3.7)
	├── anchor@0.10.5
	└── waterline@0.10.30 (deep-diff@0.3.3, bluebird@2.9.34, async@1.2.1, switchback@2.0.0, waterline-criteria@0.11.2, lodash@3.9.3, waterline-schema@0.1.20, anchor@0.11.0)

And at the same time 

	sails-mongo@0.11.5 node_modules/sails-mongo
	├── waterline-errors@0.10.1
	├── async@1.4.2
	├── validator@4.5.0
	├── waterline-cursor@0.0.6 (async@0.9.2, lodash@2.4.2)
	└── mongodb@2.1.4 (es6-promise@3.0.2, readable-stream@1.0.31, kerberos@0.0.17, mongodb-core@1.2.32)

This combination worked fine. .Now going to change sails@0.12.rc6 Will keep you posted.

**Comment by mikermcneil** [comment]
:+1:

**Comment by rasekar2000** [comment]
This time with **sails@0.12.rc6** , **sails-mongo@0.11.5** with **waterline@0.10.30**


        sails-mongo@0.11.5 node_modules/sails-mongo
	├── waterline-errors@0.10.1
	├── async@1.4.2
	├── validator@4.5.0
	├── waterline-cursor@0.0.6 (async@0.9.2, lodash@2.4.2)
	└── mongodb@2.1.4 (es6-promise@3.0.2, readable-stream@1.0.31, kerberos@0.0.17, mongodb-core@1.2.32)

	sails@0.12.0-rc6 node_modules/sails
	├── cookie-signature@1.0.6
	├── cookie@0.1.2
	├── connect-flash@0.1.1
	├── mock-req@0.2.0
	├── grunt-contrib-copy@0.5.0
	├── pluralize@1.2.1
	├── mock-res@0.3.0
	├── consolidate@0.12.1
	├── colors@1.1.2
	├── uid-safe@1.1.0 (native-or-bluebird@1.1.2)
	├── semver@5.1.0
	├── commander@2.9.0 (graceful-readlink@1.0.1)
	├── walk@2.3.9 (foreachasync@3.0.0)
	├── async@1.5.0
	├── rc@1.0.1 (ini@1.3.4, strip-json-comments@0.1.3, deep-extend@0.2.11, minimist@0.0.10)
	├── method-override@2.3.5 (methods@1.1.1, vary@1.0.1, parseurl@1.3.0, debug@2.2.0)
	├── express-session@1.12.1 (utils-merge@1.0.0, on-headers@1.0.1, uid-safe@2.0.0, parseurl@1.3.0, cookie@0.2.3, depd@1.1.0, crc@3.3.0, debug@2.2.0)
	├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
	├── ejs@2.3.4
	├── i18n@0.5.0 (sprintf@0.1.5, debug@2.2.0, mustache@2.2.1)
	├── ejs-locals@1.0.2 (ejs@0.8.8)
	├── fs-extra@0.18.4 (jsonfile@2.2.3, graceful-fs@3.0.8, rimraf@2.5.0)
	├── grunt-contrib-cssmin@0.9.0 (chalk@0.4.0, clean-css@2.1.8, maxmin@0.1.0)
	├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, winston@0.8.3, utile@0.2.1)
	├── reportback@0.1.9 (merge-defaults@0.1.4, switchback@1.1.3, lodash@2.4.2)
	├── sails-stringfile@0.3.2 (lodash@2.4.2)
	├── sails-build-dictionary@0.10.1 (lodash@2.4.2)
	├── merge-defaults@0.2.1 (lodash@2.4.2)
	├── sails-disk@0.10.8 (waterline-errors@0.10.1, async@0.2.10, waterline-criteria@0.11.2, fs-extra@0.8.1, waterline-cursor@0.0.6, lodash@2.4.2)
	├── connect@2.30.0 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, fresh@0.3.0, on-headers@1.0.1, pause@0.0.1, response-time@2.3.1, content-type@1.0.1, vhost@3.0.2, basic-auth-connect@1.0.0, parseurl@1.3.0, cookie-parser@1.3.5, depd@1.0.1, http-errors@1.3.1, connect-timeout@1.6.2, serve-favicon@2.3.0, qs@2.4.2, debug@2.2.0, morgan@1.6.1, finalhandler@0.4.0, express-session@1.11.3, serve-static@1.10.0, type-is@1.6.10, multiparty@3.3.2, csurf@1.8.3, errorhandler@1.4.2, compression@1.5.2, body-parser@1.13.3, serve-index@1.7.2)
	├── captains-log@0.11.11 (merge-defaults@0.1.4, colors@0.6.2, rc@0.3.5, lodash@2.4.1)
	├── grunt-cli@0.1.13 (resolve@0.3.1, nopt@1.0.10, findup-sync@0.1.3)
	├── sails-hook-sockets@0.13.3 (uid2@0.0.3, semver@4.3.6, machinepack-urls@3.1.1, socket.io@1.4.4, socket.io-client@1.4.4, lodash@2.4.2)
	├── express@3.21.2 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, utils-merge@1.0.0, methods@1.1.1, fresh@0.3.0, range-parser@1.0.3, vary@1.0.1, basic-auth@1.0.3, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.10, send@0.13.0, mkdirp@0.5.1, connect@2.30.2)
	├── skipper@0.5.9 (string_decoder@0.10.31, dot-access@1.0.0, async@1.4.2, node-uuid@1.4.7, debug@2.2.0, semver@5.0.3, skipper-disk@0.5.4, multiparty@3.2.10, lodash@2.4.2)
	├── sails-util@0.11.0 (json-stringify-safe@5.0.1, fs-extra@0.8.1, underscore.string@2.3.3, switchback@1.1.3)
	├── grunt-contrib-uglify@0.7.0 (uri-path@0.0.2, chalk@0.5.1, lodash@2.4.2, maxmin@1.1.0, uglify-js@2.6.1)
	├── express-handlebars@2.0.1 (graceful-fs@3.0.8, promise@6.1.0, object.assign@1.1.1, handlebars@3.0.3)
	├── sails-generate@0.12.4 (sails-generate-api@0.10.0, merge-defaults@0.1.4, sails-generate-gruntfile@0.10.10, async@0.2.10, sails-generate-adapter@0.10.5, sails-generate-generator@0.10.11, sails-generate-views-jade@0.10.3, sails-generate-views@0.10.6, sails-generate-sails.io.js@0.12.3, fs-extra@0.8.1, sails-generate-backend@0.12.3, sails-generate-frontend@0.11.6, sails-generate-controller@0.10.8, sails-generate-model@0.10.10, lodash@2.4.2, sails-generate-new@0.10.24)
	├── grunt-contrib-less@1.1.0 (async@0.9.2, chalk@1.1.1, less@2.5.3)
	├── anchor@0.10.5
	└── waterline@0.10.30 (deep-diff@0.3.3, bluebird@2.9.34, async@1.2.1, switchback@2.0.0, waterline-criteria@0.11.2, lodash@3.9.3, waterline-schema@0.1.20, anchor@0.11.0)


Sorry to say the test result is **not** in favor of **sails@0.12.rc6**  


	Fri Jan 15 2016 02:25:26 GMT+0000 (UTC) silly: Registering model `user` in Waterline (ORM)
	/home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:101
	      throw new Error(msg);
	            ^
	Error: The connection o specified in model_menu does not exist!
	    at /home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:101:13
	    at Array.forEach (native)
	    at _getConnections (/home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:96:35)
	    at new module.exports (/home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:23:32)
	    at loadCollection (/home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline.js:111:18)
	    at /home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:162:20
	    at /home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:230:13
	    at _arrayEach (/home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
	    at _each (/home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:72:13)
	    at Object.async.forEachOf.async.eachOf (/home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:229:9)
	    at Object.async.forEach.async.each (/home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
	    at Array.async.auto.loadCollections (/home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline.js:125:13)
	    at /home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:590:38
	    at _arrayEach (/home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
	    at Object.async.auto (/home/sails/lb4b/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:552:9)
	    at Waterline.initialize (/home/sails/lb4b/node_modules/sails/node_modules/waterline/lib/waterline.js:121:9)
	sails@1f5ecf9443e2:~/lb4b$

Please note that I have only this much detail even though the sails log is in silly mode 
Let me know, if you need any more details.

Thanks ,
Raj

**Comment by mikermcneil** [comment]
Thanks @rasekar2000.  @particlebanana or I will look into this asap and determine whether this is an issue in the ORM hook or in Waterline/sails-mongo.

**Comment by rasekar2000** [comment]
Thanks

**Comment by particlebanana** [comment]
@rasekar2000 submitted a PR that patches this in master

**Comment by rasekar2000** [comment]
:thumbsup:

**Comment by mikermcneil** [comment]
Thanks again for your help in getting to the bottom of this @rasekar2000.  We'll get a new RC out with this patch some time before this coming Tuesday (hoping to include a few other tweaks as well).  Reopening this issue in the mean time (if you merge a PR that mentions an issue, GH just closes the issue automatically)

cc @sgress454 (so we're on the same page)


@rasekar2000 if you need to get this going locally in the mean time, you can install from the master branch: https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#installing-different-versions-of-sails

**Comment by rasekar2000** [comment]
@mikermcneil  & @particlebanana , Thank you very much for quick response and fix. Will test tomorrow.

**Comment by japel** [comment]
@mikermcneil & @particlebanana I tested this here: https://github.com/balderdashy/waterline/issues/1282
and can confirm that in sails master this is solved.

**Comment by rasekar2000** [comment]
sails@0.12.0-rc6 node_modules/sails
├── cookie-signature@1.0.6
├── cookie@0.1.2
├── grunt-contrib-copy@0.5.0
├── mock-req@0.2.0
├── connect-flash@0.1.1
├── pluralize@1.2.1
├── mock-res@0.3.0
├── consolidate@0.12.1
├── colors@1.1.2
├── uid-safe@1.1.0 (native-or-bluebird@1.1.2)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── walk@2.3.9 (foreachasync@3.0.0)
├── semver@5.1.0
├── async@1.5.0
├── rc@1.0.1 (strip-json-comments@0.1.3, ini@1.3.4, deep-extend@0.2.11, minimist@0.0.10)
├── method-override@2.3.5 (vary@1.0.1, methods@1.1.2, parseurl@1.3.1, debug@2.2.0)
├── express-session@1.12.1 (utils-merge@1.0.0, on-headers@1.0.1, uid-safe@2.0.0, parseurl@1.3.1, cookie@0.2.3, depd@1.1.0, crc@3.3.0, debug@2.2.0)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── ejs@2.3.4
├── i18n@0.5.0 (sprintf@0.1.5, debug@2.2.0, mustache@2.2.1)
├── ejs-locals@1.0.2 (ejs@0.8.8)
├── grunt-contrib-cssmin@0.9.0 (chalk@0.4.0, clean-css@2.1.8, maxmin@0.1.0)
├── fs-extra@0.18.4 (jsonfile@2.2.3, graceful-fs@3.0.8, rimraf@2.5.0)
├── prompt@0.2.14 (revalidator@0.1.8, read@1.0.7, pkginfo@0.3.1, utile@0.2.1, winston@0.8.3)
├── sails-build-dictionary@0.10.1 (lodash@2.4.2)
├── sails-stringfile@0.3.2 (lodash@2.4.2)
├── merge-defaults@0.2.1 (lodash@2.4.2)
├── reportback@0.1.9 (merge-defaults@0.1.4, switchback@1.1.3, lodash@2.4.2)
├── connect@2.30.0 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, fresh@0.3.0, on-headers@1.0.1, pause@0.0.1, parseurl@1.3.1, response-time@2.3.1, vhost@3.0.2, basic-auth-connect@1.0.0, content-type@1.0.1, cookie-parser@1.3.5, depd@1.0.1, http-errors@1.3.1, connect-timeout@1.6.2, serve-favicon@2.3.0, qs@2.4.2, debug@2.2.0, morgan@1.6.1, finalhandler@0.4.0, csurf@1.8.3, express-session@1.11.3, serve-static@1.10.2, type-is@1.6.10, multiparty@3.3.2, compression@1.5.2, errorhandler@1.4.3, body-parser@1.13.3, serve-index@1.7.2)
├── captains-log@0.11.11 (merge-defaults@0.1.4, colors@0.6.2, rc@0.3.5, lodash@2.4.1)
├── grunt-cli@0.1.13 (nopt@1.0.10, resolve@0.3.1, findup-sync@0.1.3)
├── sails-hook-sockets@0.13.5 (uid2@0.0.3, semver@4.3.6, machinepack-urls@3.1.1, socket.io@1.4.4, socket.io-client@1.4.4, lodash@2.4.2)
├── skipper@0.5.9 (string_decoder@0.10.31, dot-access@1.0.0, async@1.4.2, node-uuid@1.4.7, debug@2.2.0, semver@5.0.3, skipper-disk@0.5.4, multiparty@3.2.10, lodash@2.4.2)
├── express@3.21.2 (escape-html@1.0.2, cookie@0.1.3, merge-descriptors@1.0.0, utils-merge@1.0.0, methods@1.1.2, fresh@0.3.0, range-parser@1.0.3, basic-auth@1.0.3, vary@1.0.1, parseurl@1.3.1, content-type@1.0.1, etag@1.7.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.10, send@0.13.0, mkdirp@0.5.1, connect@2.30.2)
├── grunt-contrib-uglify@0.7.0 (uri-path@0.0.2, chalk@0.5.1, lodash@2.4.2, uglify-js@2.6.1, maxmin@1.1.0)
├── sails-util@0.11.0 (json-stringify-safe@5.0.1, fs-extra@0.8.1, underscore.string@2.3.3, switchback@1.1.3)
├── express-handlebars@2.0.1 (graceful-fs@3.0.8, promise@6.1.0, object.assign@1.1.1, handlebars@3.0.3)
├── sails-generate@0.12.4 (sails-generate-api@0.10.0, merge-defaults@0.1.4, sails-generate-gruntfile@0.10.10, async@0.2.10, sails-generate-adapter@0.10.5, sails-generate-generator@0.10.11, sails-generate-views-jade@0.10.3, sails-generate-views@0.10.6, sails-generate-sails.io.js@0.12.5, fs-extra@0.8.1, sails-generate-backend@0.12.3, sails-generate-frontend@0.11.7, sails-generate-model@0.10.10, sails-generate-controller@0.10.8, lodash@2.4.2, sails-generate-new@0.10.24)
├── grunt-contrib-less@1.1.0 (async@0.9.2, chalk@1.1.1, less@2.5.3)
├── anchor@0.10.5
└── waterline@0.10.30 (deep-diff@0.3.3, async@1.2.1, bluebird@2.9.34, switchback@2.0.0, waterline-criteria@0.11.2, lodash@3.9.3, waterline-schema@0.1.20, anchor@0.11.0)

sails-mongo@0.11.6 node_modules/sails-mongo
├── async@1.4.2
├── validator@4.5.1
├── waterline-errors@0.10.1
├── waterline-cursor@0.0.6 (async@0.9.2, lodash@2.4.2)
└── mongodb@2.1.4 (es6-promise@3.0.2, readable-stream@1.0.31, kerberos@0.0.18, mongodb-core@1.2.32)

While the **npm install sails@0.12rc6** *didn't* bring the latest fix during the installation, the code pack was manually updated and tested. It worked.
So, keeping this ticket open for the next iteration like sails@0.12rc7 or higher version.

**Comment by japel** [comment]
@rasekar2000 yeah, thats because npm install sails@0.12.0-rc6 does not install master, if you wanted to install master you would have to:
npm install git+https://github.com/balderdashy/sails

**Comment by rasekar2000** [comment]
@japel Thanks for note. Will review asap...

**Comment by particlebanana** [comment]
`0.12.0-rc7` was published yesterday which includes this patch.

**Comment by rasekar2000** [comment]
@particlebanana  Thanks.. :+1:
