### ISSUE TITLE
Sockets:  `sails.sockets.subscribers()` returns unexpected results when using socket.io-redis

### ISSUE THREAD

**Issue by chrizz1001** [balderdashy/sails#3494]
I build up a socket connection between server and client (website). The Socket gets up and running, communication is ok. When I try to join a user to a room, the room gets created but remains empty (no users inside). Broadcasting global works.

config:

```
// proxy setup as it will run in cluster mode/LB later
  port: process.env.PORT || 4000,
  host: '0.0.0.0',
  explicitHost: '0.0.0.0',

  proxyHost: 'my_sails_server.de',
  proxyPort: 4000,

// SSL driven, but same behavior without
  http: {
    serverOptions: {
      key: require('fs').readFileSync('/etc/httpd/ssl/my_sails_server.de.key'),
      cert: require('fs').readFileSync('/etc/httpd/ssl/my_sails_server.de.crt')
    }
  },
  ssl: {
    key: require('fs').readFileSync('/etc/httpd/ssl/my_sails_server.de.key'),
    cert: require('fs').readFileSync('/etc/httpd/ssl/my_sails_server.de.crt')
  },

  sockets: {
     //adapter: 'memory' // with this config it works
     adapter: 'redis' // not working
  },
```

Controller Action:
```
module.exports = {
  setSocket: function (req, res) {
      var globalRoomName = 'globalRoom123';

      sails.sockets.join(req.socket.id, globalRoomName);
//      sails.sockets.join(req.socket, globalRoomName); // same behavior

      console.log('Subscribers in the global room:', sails.sockets.subscribers(globalRoomName)); // adapter 'memory': ["socket_id_of_user"]  |  adapter 'redis': []
  }
}
```

I am using:

    "sails": "~0.11.4",
    "sails-redis": "^0.10.6",

on a CentOS 7.2 mashine running node 5.4.1 (also tested with 4.x, 0.12.x, same behavior)
and on os x El Capitan node 5.4.1 (also tested with 4.x, 0.12.x, same behavior)

Tested with one instance (`sails lift`)

**Comment by DaRo0** [comment]
This solved my problem!!! Thank you, now i can sleep quiet!!

**Comment by chrizz1001** [comment]
Would be awsome if someone can confirm this! Still trying to get to work with redis, because shipping everything out to memory is not the best solution with hundreds of thousands of sockets...

**Comment by mikermcneil** [comment]
@chrizz1001 @DaRo0 Hmm.. you shouldn't need sails-redis (that's a waterline adapter for using Redis for one or more of your models).  Two other things to note:
- you should be sure and send a response from that controller action, eg. with res.ok()
- you should use the `sails.sockets.id(req)` method to parse the socket id (or better yet, just pass in req).  

Are you seeing different behavior than when using the sio memory adapter?   Thanks!

**Comment by chrizz1001** [comment]
@mikermcneil Thanks for your advice! Actually I do send a response. I will later put the user in other rooms, so I return a JSON response with room names. The app will later run in cluster mode with 8 workers and a lot (A LOT) of users connetced to it. they will run all on the same mashine for the beginning, so I try to avoid using the memory storage... sails doc sais I should be able to use redis for this thing...

**Comment by chrizz1001** [comment]
Ok, checked everything and changed accordingly. With adapter "memory" it is working. not with "redis". The thing is, if the server restarts and the client is not connecting to exactly the same worker, it loses its socket. I can reconnect all rooms to make it work but in case the client connects to the same worker like before, my client events get triggered twice.... So I think I really need redis as socket storage. Any Ideas anyone?

**Comment by mikermcneil** [comment]
Thanks for the detailed follow-up, @chrizz1001!

We're currently using socket.io-redis in production, and I haven't been able to replicate any problems associated with this locally.  Would you set up a repo that reproduces this in a new sails app real quick?

e.g.:
```bash
# Start from a clean Sails app
sails new sails-issue-3494
cd sails-issue-3494

# Set up a repo
git init
hub create  # or use the GitHub UI to create the repo and `git remote add` it manually
git add .
git commit -am 'Initial commit- attempting to reproduce https://github.com/balderdashy/sails/issues/3494'
git push -u origin master

# Now make whichever are the simplest/quickest changes which reproduce the issue.
# When you are sure you have the issue isolated, be sure you include the exact version
# of any dependencies you are using in the repro app in your package.json file-- e.g.
npm install socket.io-redis --save

# When you're sure the app reproduces your issue:
hub browse # or open the repo in your browser manually
# Then copy the URL of the new repo and paste it as a comment on this issue.
# We'll check it out, and since this way we'll be able to experience the problem
# ourselves, we should have no problem getting to the bottom of it.
```

On a separate note, I updated the title of this issue to help keep better track of it-- see the [updated contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions) for a few quick tips on how to write issue titles that are most helpful for our team.  Let me know if the new title misses the point.

Thanks again!

**Comment by mikermcneil** [comment]
re: subscribers() in particular -- we did notice some issues using this cross-instance in Socket.io-- see https://github.com/balderdashy/sails-hook-sockets/issues/19

**Comment by chrizz1001** [comment]
@mikermcneil  Thanks for the note, that is exactly my case! reading over the other thread...
