### ISSUE TITLE
feature request - way to explicitly generate the default blueprints CRUD ops into new Controller

### ISSUE THREAD

**Issue by arcseldon** [balderdashy/sails#3497]
Hi. Apologies in advance if raising an issue for a feature request isn't the way to raise a feature request.

Very briefly, I have been using SailsJS since v0.10.x Great framework, and easy way to get up and running fast. Can't wait to see treeline asap either.

Anyhow, with 2 years experience, one feature that I feel is blatantly missing is the ability to do something like  "**sails generate api/controller Name --scaffold**"   and it creates the controller but with explicit blueprint like code for each of the find, findOne, create, update, destroy functions inserted into the newly created Controller. Presumably, the generated code follows best practices too, and inserts all the error checking etc too. Then customization becomes trivial based on code templates, and it is simple to just delete any of the functions you don't actually want declared.

Is this something you would consider for the upcoming 0.12 release?  Certainly be interested to hear what others think? (and if there is already a feature for doing what I describe, then I'd be happy to be educated and marvel at my ignorance :smile: )

**Comment by mikermcneil** [comment]
>  Apologies in advance if raising an issue for a feature request isn't the way to raise a feature request.

Hi @arcseldon!  We just updated the contribution guide last week actually-- would you please give the [new process for proposals](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements) a read and follow the instructions there? Thank you!
