### ISSUE TITLE
Websockets, Amazon's ELBs and Proxy Protocol support

### ISSUE THREAD

**Issue by fidian** [balderdashy/sails#3505]
I have an environment running in Amazon's AWS.  They support load balancers (ELBs) that are happy to forward web traffic and inject a header into the request so you know the originating IP.  One flaw is that the ELBs don't support websockets when operating in HTTP/HTTPS mode.  In order for an HTTP stream to be upgraded to a socket connection you must switch the ELB to TCP/SSL mode and forward the raw traffic.

When the traffic is forwarded this way, a new TCP stream is created.  The original packet's source IP is lost and a new packet is created with the data.  This is application-level forwarding of the traffic to the destination.

I want to log accesses with the correct IP address.  Amazon supports enabling [Proxy Protocol](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html) on the ELBs.  This protocol, designed by [HAProxy](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) allows the source IP (among other details) to be forwarded with the traffic by including it as the very first line in the TCP stream.  After that, the stream is passed along verbatim.

There's a [node module](https://github.com/findhit/proxywrap) that lets you handle data with Proxy Protocol information.

Because of the above, I feel that Sails is currently unable to work in any AWS environment when you also want to use websockets.

It looks like one could easily add support with code in `lib/hooks/http/initialize.js`, perhaps roughly at line 50.  I don't know if this follows the same coding method as you, so I present it here for your review instead of in a pull request.

    if (sails.config.proxyProtocol == true){
        var httpConnectionElement = usingSSL ? require('https') : require('http');
        var proxiedHttp = require('findhit-proxywrap').proxy(httpConnectionElement);
        createServer = proxiedHttp.createServer;
    }

For this code to work, I was told that `connectSailsClient()` in `lib/hooks/sockets/lib/initialize.js` (about line 130) needed to be commented out, though I don't know the details and can not elaborate on why this is the case.

**Comment by mikermcneil** [comment]
Hi @fidian, thanks for posting, and in particular for providing so much information your use case (it's very helpful).  To add a feature like this to the http hook, we would need to make relevant changes to the documentation. Would you please have a read of our [contribution guide](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md) and then close this issue and submit it as a proposal instead?  You don't need to necessarily spec everything out yourself in the PR to ROADMAP.md; if there's anything that would still need to be specced, please just explicitly clarify what parts you weren't able to get to (more on that in the contribution guide).  Thanks!

**Comment by fidian** [comment]
I've attempted to submit a pull request that follows the contribution guide.  Closing this issue.
