### ISSUE TITLE
Feature Request .populate() and .populateAll() functions available on create()

### ISSUE THREAD

**Issue by Sathras** [balderdashy/sails#3509]
Is it somehow possible to make the populate() and populateAll() functions available on create()? Would be very helpful and save an extra step.
Great Framework btw.! :)

**Comment by mikermcneil** [comment]
Thanks @Sathras!  Would you mind closing this issue and [submitting this as a proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements)?
