### ISSUE TITLE
sails v0.12.0-rc6 join-room error

### ISSUE THREAD

**Issue by robgrimball** [balderdashy/sails#3512]
When I try to join a room via socket-io I get : 

```
01/21/2016 09:13:29 - info: info: Error:  TypeError: async.each is not a function
    at Object.joinRoom [as join] (/home/me/nodejs/sails-app/node_modules/sails-hook-sockets/lib/sails.sockets/join-room.js:29:11)
    at /home/me/nodejs/sails-app/api/controllers/MyController.js:169:35
    at next (native)
    at Suspender.next [as nextOrThrow] (/home/me/nodejs/sails-app/node_modules/suspend/lib/suspend.js:231:60)
    at Suspender.resume (/home/me/nodejs/sails-app/node_modules/suspend/lib/suspend.js:270:8) [TypeError: async.each is not a function]
```

Seems like some sort of version issue with async lib.  I noticed the async in node_modules is v0.1.22, yet the one in the devDependencies for sails-hook-sockets is like 0.9.x, there is no explicit version for it in the dependencies section.

**Comment by robgrimball** [comment]
A little further information.  I had an older install of the application (days older) which still used v0.12.0-rc6, but found it was working fine, and seemed to be using sails-hook-sockets v0.13.0.  The one in the latest npm installs is sails-hook-sockets v0.13.5, so something in the transition seems to have broken down.

**Comment by mikermcneil** [comment]
@robgrimball would you mind checking to see if this is happening on the latest stable release (0.11.4) as well? (pretty sure it's not because the tests are passing, but just checking to be sure)

cc @sgress454  : This looks like an issue with an upgrade to the version of the `async` dep.

**Comment by robgrimball** [comment]
100% certain it is not affecting 0.11.4 without even looking.  That is where we run the same code and I reverted back down to it for now for further development while 0.12 is being worked on.  So 0.11.4 is working fine and always has.  For this particular issue, even 0.12-rc6 was working fine up until some change, likely a dependency as you mentioned.

**Comment by sgress454** [comment]
Hm, scratching my head a bit on this one.  I did see that `async` was listed as a `devDependency` of `sails-hook-sockets`, and it needs to be a required dependency, so I'm updating the `package.json` (and the `lodash` and `async`  versions) and publishing a new version.  But that should have manifested itself as the `require('async')` failing.  My best guess is that the many upgrades and downgrades while working through these issues (thanks for bearing with us, @robgrimball) made for some interesting NPM cache conditions.

**Comment by mikermcneil** [comment]
> So 0.11.4 is working fine and always has. For this particular issue, even 0.12-rc6 was working fine up until some change, likely a dependency as you mentioned.

@robgrimball Appreciate the help.  We're about to switch to 0.12.0-rcx in production ourselves, so give us a few days and we should have the rest of the kinks worked out soon.

**Comment by mikermcneil** [comment]
This issue was moved to balderdashy/sails-hook-sockets#21
