### ISSUE TITLE
Model createdAt time mismatch

### ISSUE THREAD

**Issue by selenir** [balderdashy/sails#3516]
Let's say you have model called Account, which has beforeCreate callback:

    beforeCreate: function (values, cb) {
      var passwordHash = createSuperSecureHash(values.password);
      values.password = passwordHash;
      cb();
    }

Now let's create new object and compare data returned by callback with data stored in database

    Account.create({ /* data here */ }, function (err, created) {
      request
        .get('account/' + created.id)
        .expect(function (res) {
          assert.equal(res.body.createdAt, created.createdAt);
        })
        .end();
    });

And boom:
`AssertionError: '2016-01-21T18:11:00.000Z' == '2016-01-21T18:11:00.574Z'`

Mismatch is small and this may be a minor bug, but it ruins my unit tests.
My suggestion is that `createdAt` should be assigned after `beforeCreate`, it would make sense as long as model is not considered as "created" until `beforeCreate` finishes.

**Comment by mikermcneil** [comment]
Thanks for the thorough analysis @selenir.  Would you mind opening an issue for this in the [Waterline repo](https://github.com/balderdashy/waterline) instead?  It'll help us keep organized.

cc @particlebanana

**Comment by selenir** [comment]
Done!
