### ISSUE TITLE
sails debug is not compiling importer.less

### ISSUE THREAD

**Issue by skavinvarnan** [balderdashy/sails#3517]
Any changes made to the importer.less is not getting reflected when running sails in debug mode.

Works well when: sails lift
Doesn't work when: sails debug

Sails version: 0.11.4
node version: 4.2.2
OS: Mac 10.11.1

**Comment by mikermcneil** [comment]
Thanks for the heads up, @skavinvarnan.  We'll take a look and attempt to reproduce ASAP.

**Comment by sgress454** [comment]
Hi @skavinvarnan, there are [known issues](https://github.com/balderdashy/sails/issues/2670) with `sails debug` and Grunt on Sails v0.11.  It's been patched in the upcoming release, so your options are to use the beta version of Sails (`npm install -g sails@beta`) or patch your 0.11 version by replacing your Sails' `/lib/hooks/grunt/index.js` file with the contents of https://raw.githubusercontent.com/balderdashy/sails/88ffc0ed9949f8c74ea390efb5610b0e378fa02c/lib/hooks/grunt/index.js.
