### ISSUE TITLE
Can't run sails new, No generator called`new` found

### ISSUE THREAD

**Issue by 1mike12** [balderdashy/sails#3524]
I'm on windows, sails version 0.11.4, npm 2.14.12. I found a very similar issue https://github.com/balderdashy/sails/issues/2151, and even tried installing 0.10.5, but that still didn't work. 

Tried these steps from other issue: 
npm -g remove sails 
npm cache clear and then 
npm -g install sails 

Also tried reinstalling all of node, npm,

**Comment by mikermcneil** [comment]
Hey @1mike12, thanks for reporting this.  I'll take a look momentarily and see if I can replicate the problem locally.

In the mean time, in case this helps troubleshoot:  when this has happened in the past, it's usually an issue with a mismatched version of sails-generate-new or sails-generate which is linked, globally installed, or _locally installed_- but in the default location (on unix systems it's `~`, the home folder-- not sure about on Windows).

**Comment by karimdag** [comment]
@1mike12 @mikermcneil Everything works fine here.
OS : Win10 x64
Node : 4.2.4
NPM : 3.5.3
Sails : 0.11.4

**Comment by mikermcneil** [comment]
Thanks @karimdag!

@1mike12 any luck?

**Comment by 1mike12** [comment]
I am having the same exact problems on my Mac as well. I will keep trying and see if I have those mismatched packages, but I ran `npm -g upgrade` on both machines, which I'm starting to think might have something to do with it. I'm a node noob so not sure how that may be related.

**Comment by 1mike12** [comment]
I figured out the problem. I used to use sails generate new gulp https://www.npmjs.com/package/sails-generate-new-gulp and an optional part of that involved adding a global .sailsrc in my user directory. After removing it, I could generate things fine!
