### ISSUE TITLE
grunt-contrib-watch@0.6.1 ignoring deeply nested changes

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#3526]
It seems that there are other issues with [grunt-contrib-watch](http://npmjs.org/package/grunt-contrib-watch) @ version `0.6.1`.  Changes to deeply nested files are not noticed-- switching to `grunt-contrib-watch@0.5.3` solves the problem.

Will need to dig deeper into this grunt plugin to see if there are any related issues there (otherwise we'll have to revert to 0.5.x as the generated dep version in new sails apps or figure something else out)

Tested with:
```
    "sails": "0.11.3",
    "grunt": "0.4.5",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-coffee": "0.13.0",
    "grunt-contrib-concat": "0.5.1",
    "grunt-contrib-copy": "0.5.0",
    "grunt-contrib-cssmin": "0.9.0",
    "grunt-contrib-jst": "0.6.0",
    "grunt-contrib-less": "1.1.0",
    "grunt-contrib-uglify": "0.7.0",
    "grunt-contrib-watch": "0.6.1",
    "grunt-sails-linker": "0.10.1",
    "grunt-sync": "0.2.4",
```

```
∑ npm -v
2.8.4
∑ node -v
v0.10.26
```

**Comment by mikermcneil** [comment]
For the record (since it's mattered re: filesystem watching in the past) I'm on OS X 10.10.5.

If anyone has a moment to try out this version of grunt-contrib-watch on Node 4 or another OS, and report their findings, that'd be awesome.

**Comment by sgress454** [comment]
I think reverting to 0.5.3 should be fine.  There wasn't anything in [the changelog](https://github.com/gruntjs/grunt-contrib-watch/blob/master/CHANGELOG) that would particularly apply to Sails; I mostly bumped it because it "remove deprecated grunt.util libs" sounded like something that would give us a few less NPM warnings in our install.

**Comment by mikermcneil** [comment]
This will be changed back to 0.5.3 (_and pinned_) in 0.12 (so this issue should never affect apps using a stable version of Sails)
