### ISSUE TITLE
Relative big table select

### ISSUE THREAD

**Issue by Brendan92** [balderdashy/sails#3530]
Hi everyone,

I'm quite new to sails, enjoying is very much but having a small problem though.

The problem I'm having is selecting a table with only four columns, but about 50 000 rows. I'm lifting sails in production environment, when my frontend app hits the route for that specific table is tries the full select for a min or so, then it "kills" itself. only output I'm getting is "Killed". I'm doing the full table select using the mysql adapter to a locally hosted MySQL server.

The behaviour is inconsistent though, sometimes it goes through with no complaint and sometimes this problem occurs. What could be the cause or a possible solution, as the table will only get bigger in time.

**Comment by theocoria** [comment]
+1

**Comment by japel** [comment]
@Brendan92 would you mind posting your code or any code similar to what you are doing (as a gist or even better a git repo) so that we can reproduce it?

**Comment by japel** [comment]
@Brendan92 and besides that:
which version of sails?
which version of sails-mysql?
which version of node?
which os?
which version of mysql server?

**Comment by Brendan92** [comment]
@japel thanks for the quick response, we found the problem as it was hardware constraints from the host.
