### ISSUE TITLE
Sails is very limitful

### ISSUE THREAD

**Issue by jasalazar** [balderdashy/sails#3535]
I am so excited about learning and working with Sails, but i'm finding it limitful.

What is the point of working the MVC way if you cant call actions or model methods directly from the view?

There are plenty of things that can happen in the front end side but Sails cant handle them.

Please, @mikermcneil and @sailsstaff consider this humble opinion from a Sails enthusiast.

**Comment by particlebanana** [comment]
@jasalazar thanks for the comments. Sails is a backend framework so it only serves data or renders a server rendered view. Your views have access to whatever data you pass into it. You can read more about the View handling in the [docs](http://sailsjs.org/documentation/concepts/views) or checkout the Sails tag on [StackOverflow](http://stackoverflow.com/tags/sails.js/) if you have questions.

**Comment by mikermcneil** [comment]
> What is the point of working the MVC way if you cant call actions or model methods directly from the view?

@jasalazar also, if you have other ideas about how you'd like to see this work based on your experience with other frameworks, etc., please let us know in the form of a proposal.  Thanks!

**Comment by jasalazar** [comment]
I'm honored to have the opportunity to offer you a proposal @mikermcneil

It would be very helpful for every SailsJS user (newbie, like me, or more experienced) to be able to call controller's actions from the view.

I guessed, without having read the documentation, it could be something like <% MyController.action %>, since i feel confident using EJS sintax.

Thanks for the opportunity.

**Comment by mikermcneil** [comment]
@jasalazar replied to your PR :)
