### ISSUE TITLE
"Duplicate" entries in sails cli?

### ISSUE THREAD

**Issue by borestad** [balderdashy/sails#3539]
sails@^0.12.0-rc9

Console, consle, consloe. Is this intended for people that can't spell to "console"? :-)

![image](https://cloud.githubusercontent.com/assets/286455/12782834/16320c4e-ca7e-11e5-8fbf-5ee5c2281459.png)

**Comment by mikermcneil** [comment]
@borestad indeed- aliases shouldn't be displaying when you run `sails --help` though!  I'll look into it.

**Comment by mikermcneil** [comment]
@borestad will be in v0.12
