### ISSUE TITLE
Error page (404) nested in layout.ejs

### ISSUE THREAD

**Issue by netlander** [balderdashy/sails#3542]
When a non existant URL is requested the 404 error page shows which is great. But when I look at the source I see the 404 page nested in the layout page resulting in two nested \<html\>, \<head\>, \<body\>, etc.. tags. This has to be a bug.

**Comment by mikermcneil** [comment]
> This has to be a bug.

Hey @netlander, by default all of your HTML views are served wrapped in `layout.ejs`.  You can disable layouts and use partials instead.

**Comment by mikermcneil** [comment]
(See http://sailsjs.org/documentation/reference/configuration/sails-config-views for more info on disabling layouts)
