### ISSUE TITLE
v0.11.4 JST not written issue 

### ISSUE THREAD

**Issue by NizarBlond** [balderdashy/sails#3545]
I defined an html file under assets/templates/ to compile for JST use.  I get the following error when doing "sails lift --verbose": 

```
verbose: Grunt :: Cleaning .tmp/public...
verbose: Grunt :: OK
verbose: Grunt :: Running "jst:dev" (jst) task
**>> Destination not written because compiled files were empty.**
```

What am I required to do other than defining HTML files under assets/templates/?

**Comment by mikermcneil** [comment]
Hi @NizarBlond, can you provide some more information?  From what I can tell, this is a question rather than a bug report, but I want to be sure.  See our [**contribution guide**](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions) for info about the information to submit when creating an issue.

**Comment by mikermcneil** [comment]
@NizarBlond by the way, re: your question:

> What am I required to do other than defining HTML files under assets/templates/?

I went and did some cleanup work in our default-generated task config files recently-- here's a link in case it's helpful: https://github.com/balderdashy/sails-generate-frontend/blob/master/templates/tasks/config/jst.js#L6

**Comment by mikermcneil** [comment]
Another tip for you, in case this gets you on the right track:  Once you've gotten one or more HTML files in your client-side templates folder  (e.g. `assets/templates/foo.html`) and put some content therein (e.g. `<div>hi</div>`), then try running the following in the browser:

```javascript
console.log(window.JST);
```

**Comment by NizarBlond** [comment]
That's what I did, there is no jst.js file generated. 
Also, I obviously put the /foo.html under assets/templates/ with content. NOTHING.

Am I missing something in the instructions on how to enable this feature? I don't guess so, it should be enabled by default. 

I started a brand new project to test it from scratch and NOTHING.

Can you please chec the feature?

**Comment by NizarBlond** [comment]
I guess I found the bug

I did the following change in tasks/config/jst.js and BOOM, it works!

`			files: {
				// e.g.
				// 'relative/path/from/gruntfile/to/compiled/template/destination'  : ['relative/path/to/sourcefiles/**/*.html']
				// '.tmp/public/jst.js': require('../pipeline').templateFilesToInject,
				'.tmp/public/jst.js': ['assets/templates/**/*.html']
			}`

Then, in tasks/pipeline.js we have

`var templateFilesToInject = [
  'templates/**/*.html'
];

module.exports.templateFilesToInject = templateFilesToInject.map(transformPath);

function transformPath(path) {
  return (path.substring(0,1) == '!') ? ('!' + tmpPath + path.substring(1)) : (tmpPath + path);
}`

So, I printed the "require('../pipeline').templateFilesToInject" inside .jst 

`console.log("blabla: ", require('../pipeline').templateFilesToInject);
`
and I get the **BUG HERE**

    blabla:  [ '.tmp/public/assets/templates/foo.html' ]

The path explains it all, why do we even have .tmp/public here?
Also, you may need to add assets/ as the default dir doesn't seem to be this (assets)


Cheers

**Comment by mikermcneil** [comment]
Alright, thanks @NizarBlond!  This should be resolved if you do a fresh install of sails-- just published a patch release of sails-generate-frontend (more details [here](https://gitter.im/balderdashy/sails?at=56b4c6d465d6cbe729045777))

**Comment by sgress454** [comment]
Could this be related to https://github.com/balderdashy/sails/issues/3367 as well?

**Comment by mikermcneil** [comment]
@sgress454 perhaps, not entirely sure (replied in #3367)

@NizarBlond I'm going to go ahead and close this issue since it's been resolved.  Please open a new issue (with a link back here) if you continue to see problems.  Thanks!

**Comment by SpaceG** [comment]
i have a problem with sails.js and gruntjs ?!.. 
whzat the henk.? really, nothing works fine.. for everything ins sails you have to write shit ... sy, nerving a bit.. these tousend of errors.! eee??? its a a framework.? !!... what can i do with this bull shit.? 

```

Running "jst:dev" (jst) task
>> Destination not written because compiled files were empty.

```

**Comment by SpaceG** [comment]
okey, fixed :) thanks to Mike description  ! need your Brain!
