### ISSUE TITLE
Node.js Getting Error when saving session in database in Sails.js using sails-mongo module?

### ISSUE THREAD

**Issue by kuldeepmobinett** [balderdashy/sails#3547]
i have gone through the sails doc http://sailsjs.org/documentation/reference/configuration/sails-config-session db configuration is

  adapter: 'sails-mongo',
  host: 'localhost',
  port: 27017,
  db: 'sails',
  collection: 'sessions',
Getting error -->

A hook (session) failed to load! error: Could not load Connect session adapter :: sails-mongo installed "sails-mongo" by using npm install sails-mongo

**Comment by mikermcneil** [comment]
Hey @kuldeepmobinett, would you try:

```bash
npm install sails-mongo@0.8.4 --save --force
```

And then restart your server and give it a go?  If that solves it for you, please come back here, give us the thumbs up and close the issue.  If that _doesn't_ do the trick, please provide some more information about the version of node, NPM, and Sails that you're currently using (see https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions for details)

Thanks!

**Comment by mikermcneil** [comment]
@kuldeepmobinett wow- just realized there is a typo in our docs, sorry about that!  Should say `connect-mongo` (not `sails-mongo`).  This is my bad; I recently updated the docs to reflect the appropriate version and ended up with a copy/paste error.

I also noticed you'll want to change your adapter config to `'connect-mongo'` or `mongo` (instead of "sails-mongo").  Hope that helps!

**Comment by mikermcneil** [comment]
Just updated the docs -- will redeploy shortly!  (https://github.com/balderdashy/sails-docs/commit/6f74633578b9f47ca9a7e85b0cd686637f88d9e6)

**Comment by kuldeepmobinett** [comment]
i was trying to install "npm install connect-mongo@0.8.4 --save --force" 
I sure hope you know what you are doing.
npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "sails-mongo@0.8.4" "--save" "--force"
npm ERR! node v0.10.25
npm ERR! npm  v3.3.8

npm ERR! No compatible version found: sails-mongo@0.8.4
npm ERR! Valid install targets:
npm ERR! ["0.12.0","0.11.7","0.11.6","0.11.5","0.11.4","0.11.3","0.11.2","0.11.1","0.11.0","0.10.9","0.10.8","0.10.6","0.10.5","0.10.4","0.10.3","0.10.2","0.10.1","0.10.0-rc5","0.10.0-rc4","0.10.0-rc3","0.10.0-rc2","0.10.0-rc1","0.9.8","0.9.7","0.9.6","0.9.5","0.9.4","0.9.3","0.9.2","0.9.1","0.9.0","0.0.3","0.0.2","0.0.1"]
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by mikermcneil** [comment]
@kuldeepmobinett another doc mistake, sorry!  That should say `1.1.0`  See https://github.com/balderdashy/sails/issues/3486#issuecomment-172649454 for more info.  Fixing the docs now.

**Comment by mikermcneil** [comment]
```bash
npm install connect-mongo@1.1.0 --save --force
```

**Comment by mikermcneil** [comment]
@kuldeepmobinett I'm going to go ahead and close this as resolved-- please open a new issue and link back here if you see any other related problems.  Thank you!

**Comment by kuldeepmobinett** [comment]
Still facing same problem
