### ISSUE TITLE
.tmp problem and grunt sass

### ISSUE THREAD

**Issue by ivan-vilches** [balderdashy/sails#3548]
I installed sass , now when i start the server ' sails lift' i get this:

```
error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error:
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.

error:
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error:
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `C:\sails\dashboard\tasks\register\.tmp` ?
error:
error:      If you think this might be the case, try running:
error:      sudo chown -R YOUR_COMPUTER_USER_NAME C:\sails\dashboard\tasks\register\.tmp
```

i am using windows 8, thanks for any help.

**Comment by mikermcneil** [comment]
Hi @ivan-vilches, would you mind recreating this from an off-the-shelf sails project and sharing the repo?  This is the kind of thing that's really hard to replicate without seeing exactly how the Grunt task was set up-- and the easiest way to get to the bottom of it is via a repo.

For reference, here's an example of how you might do it:

```bash
sails new sails-issue-3548
cd sails-issue-3548
# Now make whichever are the simplest/quickest changes which reproduce the issue,
# and when you for sure have the issue isolated, run:
git init
hub create  # or use the GitHub UI to create the repo and `git remote add` it manually
git add .
git commit -am 'Reproduces https://github.com/balderdashy/sails/issues/3548'
git push -u origin master
hub browse # or open the repo in your browser manually
# Then copy the URL of the new repo and paste it as a comment on this issue.
# We'll check it out, and since this way we'll be able to experience the problem
# ourselves, we should have no problem getting to the bottom of it.
```

> (btw: not sure if the `hub` cli tool works on Windows, but if not, you can do those parts in the browser)

**Comment by mikermcneil** [comment]
Also @ivan-vilches, if you wouldn't mind providing your Node, NPM, and Sails versions for posterity, that'd be really helpful.  To quickly get that, please run the following and post the output as a comment on this issue:

```bash
sails -v
#     => your version here (e.g. 0.12.0-rc9)
node -v
#      => your version here (e.g. v0.10.26)
npm -v
#      => your version here (e.g. 2.8.4)
```


Thank you!

**Comment by revic1993** [comment]
I am facing the same issue when running mocha tests on sails. 
I have created sails project with --no-frontend flag . 
Sails lift works fine.

**Comment by mikermcneil** [comment]
@ivan-vilches I'm going to go ahead and close this issue, but if you're still seeing problems w/ Grunt+SASS on windows, please open a new issue and link back here, k?  Thank you!
