### ISSUE TITLE
Select Specific Fields with Non-Primary Key Values fails in latest version

### ISSUE THREAD

**Issue by Anandapriyan** [balderdashy/sails#3551]
Hi,
     The following `controller/service` code returns body of the message from message collection matches with the id passed to it in previous sails-mongo  ("sails-mongo": "0.11.2") but in new version of sails-mongo ("sails-mongo": "^0.11.2")  it returns all the data. i have attached the response for each version of sails-mongo below here. 
	 
      
 `Message.find({id:id},{body:1})`
		`.then(function(response){`
			`return [response];`
		`})`
		`.spread(function(messageInfo){`
			`console.log('success');`
			`res.send(messageInfo);`
		`})`
		`.fail(function(error){`
			`console.log('error');`
			`res.send(error);`
		`})`
​
​
sails response for sails-mongo 0.11.2
​
`[
    {
       "body": "HelloWorld",
       "createdAt": "2016-02-05T15:55:06.476Z",
       "updatedAt": "2016-02-05T15:56:49.501Z",
       "id": "56b4c5da50a6ae150c5ebc53"
    }
]`
​
​
​
sails response for sails-mongo 0.10.5
​
`[
    {
       "body": "HelloWorld",
       "id": "56b4c5da50a6ae150c5ebc53"
    }
]`
​
Please confirm , if this bug needs a fix?
​

**Comment by rasekar2000** [comment]
Thanks Anand.. It worked in 11.2.. Let me take it from here  to test in 11.5, 11.6, 11.7 and 12.0

**Comment by mikermcneil** [comment]
@Anandapriyan @rasekar2000  Hi guys- this usage isn't supported in Waterline at the moment (it's something we're working on for the future).

**Comment by mikermcneil** [comment]
(see also https://github.com/balderdashy/waterline/issues/919)

**Comment by rasekar2000** [comment]
**1) Concern :** When this sails-mongo is specific to MongoDB connectivity and MongoDb very well supports this feature, I think, this requirement can be prioritized. Thanks for the note.
**2) Workaround :** For now, once we retrieved the DATA from Mongo DB , we are using lodash (map / filter / pluck) like functionality to arrive at the data that needs to be transferred from Sails to the Frontend Application. (to avoid sending more data)

**Comment by mikermcneil** [comment]
See also https://github.com/balderdashy/sails/issues/3837#issuecomment-251794006
