### ISSUE TITLE
Sails generate controller with arguments 0.12

### ISSUE THREAD

**Issue by udanpe** [balderdashy/sails#3555]
sails generate controller Users index create show..  creates new file with error inside
generate model with arg works without problem

module.exports = {
	function (obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape, __j = Array.prototype.join;
function print() { __p += __j.call(arguments, '') }
with (obj) {

need change sails-generate-controller package.json file and set "lodash": "~2.4.0" with >=2.4.x not work

or rewrite module and update all to lodash 4.

**Comment by mikermcneil** [comment]
Hi @udanpe, do you know what version of `sails-generate-controller` you have installed?  Also would you please include your version of NPM and node?

**Comment by udanpe** [comment]
sails-generate-controller@~0.10.7 mac brew npm 3.3.12
>= not current. x works. change to ~2.4.0 it's default and work always and also  works ">=2.4.x <2.5.x"
 ">=2.4.x" as npm install lodash@>=2.4.x load many file with many functions

**Comment by sgress454** [comment]
Thanks @udanpe.  Fixed and published `sails-generate-controller` v0.10.9.  Easiest way to get it is just to re-install Sails:

```
npm uninstall -g sails
npm cache clean
npm install -g sails
```

**Comment by udanpe** [comment]
https://docs.npmjs.com/getting-started/semantic-versioning
    Patch releases: 1.0 or 1.0.x or ~1.0.4
    Minor releases: 1 or 1.x or ^1.0.4
    Major releases: * or x
and else work ">=2.4.0 <2.4.2" (but docs nothing say about this)
">=2.4.x" - install latest version because don't understand syntax.
and when module will be change sails don't work because incorrect syntax
if you change "lodash": "~2.4.1" why not change  "merge-defaults": ">=0.1.0" in this file?)

**Comment by sgress454** [comment]
`merge-defaults` is a package we maintain, so we know what we're doing ;)
