### ISSUE TITLE
"A promise was created in a handler but was not returned from it" calling model.find()

### ISSUE THREAD

**Issue by dottodot** [balderdashy/sails#3556]
Just trying v0.12.0 and getting the following warning when making request to controller

> Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)

It seems to be something to do with my code as if I remove my code so the default find is used I don't get the error.

```
find: function(req, res) {
    Product.find().populate('inventory').then(function(products) {
      return res.send(products);
    }).catch(function(err) {
      return res.serverError(err);
    });
  }
```

**Comment by mikermcneil** [comment]
Hi @dottodot- could you provide your node and npm version? Also if you could tell me what adapter you're using, and run `npm ls waterline` that'd be helpful. Thanks!

**Comment by dottodot** [comment]
Yes it's 

node v4.2.3
npm 2.14.7
waterline@0.11.0

**Comment by mikermcneil** [comment]
Thanks @dottodot.  Would you try:

```javascript
  find: function(req, res) {
    Product.find().populate('inventory').exec(function(err, products) {
      if (err) {
        return res.serverError(err);
      }
      return res.json(products);
    });
  }
```

to double-check that this is an issue with promises and not anything else that might be going on with dependency versions, etc?

cc @particlebanana

**Comment by sgress454** [comment]
Also, if you're upgrading your Sails from a previous version, would you mind trying a fresh install?
```
npm uninstall -g sails
npm cache clean
npm install -g sails
```
(depending on your system you may need to put `sudo` in front of each command)

**Comment by dottodot** [comment]
OK I uninstalled sails both globally and in app, cleared the cache and reinstalled and the issue is still there. Using the following works though

```
  find: function(req, res) {
    Product.find().populate('inventory').exec(function(err, products) {
      if (err) {
        return res.serverError(err);
      }
      return res.json(products);
    });
  }
```

Also just so you know it doesn't seem to stop anything from working.

**Comment by zeluis9** [comment]
Can you show the complete stack trace?

**Comment by dottodot** [comment]
```
    at /Users/marcus/hosts/bailey/api/controllers/ProductController.js:42:17
    at tryCatcher (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/promise.js:617:18)
    at /Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/release/nodeback.js:42:21
    at wrapper (/Users/marcus/hosts/bailey/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:417:80)
    at wrappedCallback (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at returnResults (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:392:9)
    at /Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:277:16
    at /Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:78:46
    at wrapper (/Users/marcus/hosts/bailey/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:417:80)
    at wrappedCallback (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/Users/marcus/hosts/bailey/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at Cursor.attachRecords (/Users/marcus/hosts/bailey/node_modules/sails-mongo/node_modules/waterline-cursor/cursor/cursor.js:117:10)

**Comment by zeluis9** [comment]
With waterline@0.11.0, sails@0.12.0 and sails-disk I cannot reproduce this issue. Maybe something related to the adapter you're using. Can you tell which one is?

**Comment by dottodot** [comment]
I'm using sails-mongo 0.12.0

**Comment by sgress454** [comment]
Thanks for the update @dottodot.  I'm still unable to reproduce using sails-mongo 0.12.0, Node 4.2.6 and NPM 2.14.12 (so not exactly the same as your environment, but close).  At this point if you're no closer to figuring out the issue, I think the best thing would be to create a repo that reproduces the problem that we can check out.  Here's some instructions (you can get the `hub` tool from [here](https://hub.github.com/)):

```
sails new sails-issue-3556
cd sails-issue-3556
# Now make whichever are the simplest/quickest changes which reproduce the issue,
# and when you for sure have the issue isolated, run:
git init
hub create  # or use the GitHub UI to create the repo and `git remote add` it manually
git add .
git commit -am 'Reproduces https://github.com/balderdashy/sails/issues/3556'
git push -u origin master
hub browse # or open the repo in your browser manually
# Then copy the URL of the new repo and paste it as a comment on this issue.
# We'll check it out, and since this way we'll be able to experience the problem
# ourselves, we should have no problem getting to the bottom of it.
```

Often we find that the act of going through the steps to reproduce the problem from scratch reveals the solution (for instance a configuration setting or policy that was affecting the response).  If not, having a repo that we can clone to reproduce makes it a lot more likely that we can figure out what's going on!

**Comment by luislobo** [comment]
The same is happening to me, when trying to upgrade one of our projects to 0.12. From http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it: 

> This usually means that you simply forgot a return statement somewhere which will cause a runaway promise that is not connected to any promise chain.

I'm trying to find the issue on my project and how to fix it all the way. If I find something I'll share it here.

**Comment by luislobo** [comment]
In that same article, it says:
If you know what you're doing and don't want to silence all warnings, you can create runaway promises without causing this warning by returning e.g. null:

```js
getUser().then(function(user) {
    // Perform this in the "background" and don't care about it's result at all
    saveAnalytics(user);
    // return a non-undefined value to signal that we didn't forget to return
    return null;
});
```

that might help you

**Comment by sgress454** [comment]
@luislobo Can you provide a repo or more info?  Are you using sails-mongo as well?

**Comment by luislobo** [comment]
I have just been able to reproduce the issue in a repo.
The problem is when for example you have a Policy that uses a model and a .then
and then in you controller you also do another query with an other promise.

Since in the policy you just return with next()... Bluebird "detects" that there is a pending Promise, that was not chained to the new one... (or something like that).

This is not an issue, but besides disabling the warning, I don't know of a way to pass the promise back in the next() chain and if it even makes sense doing it.

I'll push the repo so that you can test.

**Comment by luislobo** [comment]
https://github.com/luislobo/sails-issue-3556

**Comment by luislobo** [comment]
Same issue happening to other people in the same situation... check https://github.com/petkaantonov/bluebird/issues/928

**Comment by luislobo** [comment]
And here explains how to supress the warning using code: https://github.com/petkaantonov/bluebird/issues/903#issuecomment-162244729

**Comment by luislobo** [comment]
Finally, Bluebird has an option to specifically disable the check on forgotten return: 
https://github.com/petkaantonov/bluebird/commit/8b6834f3a0ce1ff32e3d2058cebf2cc10bf570c0

**Comment by luislobo** [comment]
And this also could be a pattern to be used to remove the warning: https://github.com/petkaantonov/bluebird/issues/871#issuecomment-157646342

**Comment by sgress454** [comment]
Thanks for the updates, @luislobo.  I cloned your repo and can reproduce now--looks like it indeed is due to the policy.  Doing:

```
    next();
    return true;
```

instead of simply `next();` removes the warning, but it looks weird and hunting that down everywhere sounds tedious.

If this just started with the latest Sails upgrade, I'm guessing it must be due to a new version of Bluebird being used.  We could suppress the warnings by configuring Bluebird [when we first require it in Waterline](https://github.com/balderdashy/waterline/blob/master/lib/waterline/model/index.js#L7).  Not sure if we want to be suppressing all warnings though.  I'll let @particlebanana weight in on that.

**Comment by luislobo** [comment]
Yes, this behavior is in the 3.x version of Bluebird, I was thinking on the same solution, about setting the warnings off when requiring it in waterline

**Comment by dottodot** [comment]
OK the above has help me realise where my issue is. I'm using [sails-auth ](https://github.com/tjwebb/sails-auth) and [sails-permissions](https://github.com/tjwebb/sails-permissions) and the policies created by these is causing the warnings.

**Comment by sgress454** [comment]
Ok!  Looks like we've tracked this down pretty well.  After talking it over with @particlebanana, we don't think just turning the warnings off in Waterline is a good idea: it's there for a reason, because you really should be returning a value in your handler.  That's easy to say when you have control over the code; I understand that in some cases (like @dottodot 's), the problem may be in a third-party package that you're using.  In that case, you need to create an issue with the maintainers of that package (especially if it's the Sails team!).  

In the meantime, if the warning is getting you down and the maintainers of that third-party package are giving you the cold shoulder, take heart:  Bluebird hears your woes and offers this environment variable to melt your cares away:

```
BLUEBIRD_W_FORGOTTEN_RETURN=0 sails lift
```

and all your (bluebird promise with forgotten return) warnings will disappear.

**Comment by luislobo** [comment]
you can also add that this to your bootstrap.js file
```js
// Keep Bluebird warnings but don't
// show those about forgotten returns.
// They are not nice to have when using promises
// on policies + controllers + other
process.env.BLUEBIRD_WARNINGS = 1;
process.env.BLUEBIRD_W_FORGOTTEN_RETURN = 0;
```

**Comment by kpturner** [comment]
I am getting these issues when using the sails-postgresql adaptor.   I know I can suppress the warnings, but I am not entirely sure if I should.  I have not yet fathomed out if it is my code causing the issue or not. 

As a newb, can I clarify something:   Does each .then() have to return something - even if it is just null?

**Comment by irlnathan** [comment]
Howdy @kpturner,

This would be a good question for StackOverflow.
Thanks!

Best, Irl

**Comment by luislobo** [comment]
It is not necessary to always return. That is a Bluebird thing, more than a
Sails or Waterline thing.

**Comment by kpturner** [comment]
I decided not to switch off the warning as it was my code that had the issue.  Instead I ploughed through the lot making changes until I had no more warnings (its still a development project so I have licence to do this :) )

I was surprised how many nested promises I had that broke the return chain.

**Comment by aayush-practo** [comment]
I am getting the same warnings using sails-mysql@0.11.3 adapter, and for promises like
``` javascript
Model1.findOne().then(function (m1){
    var condition
     // some checks
     if (condition === true){
          Model1.update({}).then(function (m2){
               return res.json(200, {updatedValue: m2[0]}) 
         }).catch(function (error){
              return res.json(400, {error: error.message})
         })
     }
}).catch(function (error){
    return res.json(400, {error: error.message})
})
```
Here first promise does not return anything if condition is true, however adding a return true after if does not give the warning. It does not seem to be a valid solution. Any other possible solution besides setting warnings to false and returning true or null?

**Comment by MychaelZ** [comment]
You might have to return the Promise from the find method.

```(javascript)
find: function(req, res) {
    return Product.find().populate('inventory').then(function(products) {
      return res.send(products);
    }).catch(function(err) {
      return res.serverError(err);
    });
  }
```

**Comment by MtDalPizzol** [comment]
I'm seeing this with the following code:

```javascript
module.exports = {

  findProduct (req, res, next) {
    let productId = req.params.id
    let userId = req.user.id

    return Product
      .findOne({
        id: productId,
        owner: userId
      })
      .populate('pictures')
      .then(user => res.ok(user))
      .catch(err => res.badRequest(err))
  }

}
```

Sails version: 0.12.3
Node version: 6.11.0
NPM version: 4.3.0
Operating system: Linux Mint 17.3 Cinnamon 64-bit

**Comment by shiolovesgod** [comment]
I couldn't get around the errors.  I had to default to the `exec()` syntax to get it working
