### ISSUE TITLE
publishCreate() generates error after upgrading to v.0.12

### ISSUE THREAD

**Issue by metalaureate** [balderdashy/sails#3558]
After upgrading https://github.com/maangalabs/socket-in-sails to v.0.12, when I call

`Chat.publishCreate({id: data_from_client.id, message : data_from_client.message , user:data_from_client.user},req);`

I get error

> /Users/shill/Projects/socket-in-sails-master/node_modules/sails/lib/hooks/pubsub/index.js:1069
>           self.publishCreateSingle(values.toJSON(), req, options);
>                                           ^
> TypeError: undefined is not a function
>     at /Users/shill/Projects/socket-in-sails-master/node_modules/sails/lib/hooks/pubsub/index.js:1069:43
>     at arrayEach (/Users/shill/Projects/socket-in-sails-master/node_modules/sails/node_modules/lodash/index.js:1289:13)
>     at Function.<anonymous> (/Users/shill/Projects/socket-in-sails-master/node_modules/sails/node_modules/lodash/index.js:3345:13)
>     at publishCreate (/Users/shill/Projects/socket-in-sails-master/node_modules/sails/lib/hooks/pubsub/index.js:1068:11)
>     at wrapper [as publishCreate] (/Users/shill/Projects/socket-in-sails-master/node_modules/sails/node_modules/lodash/index.js:3095:19)
>     at /Users/shill/Projects/socket-in-sails-master/api/controllers/ChatController.js:21:11

This also happens if I port the code to a fresh v.0.12 sails project.

**Comment by metalaureate** [comment]
It works if I remove `toJSON()` from the instruction in /node_modules/sails/lib/hooks/pubsub/index.js:1069

but I do not know what side-effects this causes or why toJSON() is being used vs JSON.stringify

**Comment by sgress454** [comment]
Thanks @metalaureate, we'll check it out and post here if we need more info.

**Comment by metalaureate** [comment]
I think the problem is that I am not passing _bona fide_ sailsjs model to the publishCreate. It works with this kludge:

`payload.toJSON=function () { return payload};`

Is there a more elegant way to construct my payload that inherits the toJSON() method from sails?

**Comment by sgress454** [comment]
> Is there a more elegant way to construct my payload that inherits the toJSON() method from sails?

No, and you shouldn't need to.  The `publishCreate` method _should_ let you send in anything you want, as long as it has a primary key.  Looks like I merged in a PR that broke that functionality :flushed: 

I'll look into a fix and some tests to ensure that it doesn't happen again.

**Comment by metalaureate** [comment]
You guys are awesome thank you.

**Comment by sgress454** [comment]
0.12.1 has been released with this fix!
