### ISSUE TITLE
reference help: creating new adapter

### ISSUE THREAD

**Issue by jonscyriac** [balderdashy/sails#3560]
I would like to create an adapter for a schemaful (sql-ish) database service... can anyone advice me with something to start with? im a newbie..  and i find it difficult to follow the documentations available....

**Comment by mikermcneil** [comment]
Hi @jonscyriac- we could definitely use some more formal documentation on the website about this (I'll move this issue to sails-docs).  In the mean time, check out https://github.com/balderdashy/sails-docs/blob/master/contributing/intro-to-custom-adapters.md, and https://github.com/balderdashy/sails-docs/blob/master/contributing/intro-to-custom-adapters.md.

Also feel free to pop into Gitter for help.  Look forward to hearing about what you're working on!

**Comment by mikermcneil** [comment]
This issue was moved to balderdashy/sails-docs#637

**Comment by jonscyriac** [comment]
thank you @mikermcneil . I am trying to make a sails-documentdb adapter. any advice?
