### ISSUE TITLE
MySQL Foreign Keys and Primary Keys are Inconsistent Types

### ISSUE THREAD

**Issue by jvanalst** [balderdashy/sails#3565]
Noticed that by default when using the auto-migration stuff **Primary Key Ids are INT(10) Unsigned** by default, however **Foreign Key Ids are INT(11) Signed**.

This could cause issues in the rare case when a table reaches 100,000,000,000+ rows and was originally bootstrapped using auto-migrate.

Noticed this in sails v0.11.4

**Comment by mrvini** [comment]
+1
 noticed the same issue in the prev. versions as well with MySQL adapter, that could cause an issue if in the future Foreign keys will be allowed

**Comment by sgress454** [comment]
Thanks for the heads-up @jvanalst.  Mind posting this in the [sails-mysql](https://github.com/balderdashy/sails-mysql) repo and back-linking here?

**Comment by mikermcneil** [comment]
@mrvini @jvanalst see https://github.com/balderdashy/sails-mysql/issues/232

**Comment by mikermcneil** [comment]
(and thanks for moving the issue @jvanalst. I left https://github.com/balderdashy/sails-mysql/issues/282 open just in case, but unless you see anything that isn't covered by the other link re: unsigned vs. signed integers, would you go ahead and close https://github.com/balderdashy/sails-mysql/issues/282?)
