### ISSUE TITLE
Mongo sessions don't seem to work (error possibly unrelated)

### ISSUE THREAD

**Issue by nate-r** [balderdashy/sails#3574]
Reproduce:

1. Install sails 0.12
2. sails new test
3. cd test
4. npm install connect-mongo --save
5. npm install sails-mongo --save (probably not needed for test)
6. Edit config/session.js - uncomment lines 70 - 74
7. sails lift --verbose

Output:

> info: Starting app...

> verbose: Setting Node environment...
> verbose: moduleloader hook loaded successfully.
> verbose: Loading app config...
> verbose: userconfig hook loaded successfully.
> verbose: Exposing global variables... (you can disable this by modifying the properties in `sails.config.globals`)
> verbose: Loading user hooks...
> verbose: userhooks hook loaded successfully.
> verbose: Loading runtime custom response definitions...
> verbose: Loading app services...
> verbose: logger hook loaded successfully.
> verbose: request hook loaded successfully.
> verbose: Loading the app's models and adapters...
> verbose: Loading app models...
> verbose: Loading app adapters...
> verbose: Overriding ejs engine config with ejslocals to implement layout support...
> verbose: views hook loaded successfully.
> verbose: Loading blueprint middleware...
> verbose: blueprints hook loaded successfully.
> verbose: responses hook loaded successfully.
> verbose: controllers hook loaded successfully.
> verbose: Loading policy modules from app...
> verbose: Finished loading policy middleware logic.
> verbose: policies hook loaded successfully.
> verbose: services hook loaded successfully.
> verbose: csrf hook loaded successfully.
> verbose: cors hook loaded successfully.
> verbose: i18n hook loaded successfully.
> error: A hook (`session`) failed to load!
> verbose: Lowering sails...
> error: A hook (`session`) failed to load!
> verbose: Lowering sails...
>
>\AppData\Roaming\npm\node_modules\sails\lib\app\lower.js:81
>if (!_.isObject(sails.hooks) || !sails.hooks.sockets || (sails.io.httpServer && sails.hooks.http.server === sails.io.httpServer)) {
>                                                                 ^
>TypeError: Cannot read property 'httpServer' of undefined`

**Comment by nate-r** [comment]
So it seems like URL is actually mandatory?

Was able to see actual error by disabling socket and pubsub hooks in .sailsrc.

Error was:

> error: A hook (`session`) failed to load!
> error: A hook (`orm`) failed to load!
> error: Could not load Connect session adapter :: connect-mongo
>
> Error from adapter:
> Error: Connection strategy not found

in node_modules\connect-mongo\src\index.js line 100

Was able to get it to work by adding the following line to config/session.js:
`url: "mongodb://localhost:27017/sails",`

When I tried to match the example provided in session.js, which includes the collection name in the URL:
>url: "mongodb://localhost:27017/sails/sessions",

I got the following error:

>error: A hook (`session`) failed to load!
>error: A hook (`orm`) failed to load!
>error: Could not load Connect session adapter :: connect-mongo
>
>Error from adapter:
>Error: More than 1 database name in URL

**Comment by karsasmus** [comment]
Did you set the adapter to "sails-mongo" in line 70?

**Comment by brettimus** [comment]
I am having similar troubles! Trying to validate [the example from the docs](http://sailsjs.org/documentation/reference/configuration/sails-config-session#?using-other-connectcompatible-session-stores) that was referenced in [this issue](https://github.com/balderdashy/sails-docs/issues/641).

Switching to use the `0.8.2` version of `connect-mongo` still produced the same errors you were getting above. 

Docs will need some updating when this is resolved, so please ping me!

**Comment by greghesp** [comment]
I too seem to have this issue.  Switching to 0.8.2 or connect-mongo hasn't resolved this for me either

**Comment by reyou** [comment]
Having same problem here,
I can connect to my db through RoboMongo by sails cannot use it as session storage.
Here is some info


sails version
0.12.0

===================================================

  adapter: 'mongo',
    host: 'myhostwhatever.mongolab.com',
    port: 58548,    
    db: 'FooBarMongoLab',
    collection: 'sessions',

    /***************************************************************************
    *                                                                          *
    * Optional Values:                                                         *
    *                                                                          *
    * # Note: url will override other connection settings url:                 *
    * 'mongodb://user:pass@host:port/database/collection',                     *
    *                                                                          *
    ***************************************************************************/
    // mongodb://<dbuser>:<dbpassword>@myhostwhatever.mongolab.com:58548/FooBarMongoLab

    username: 'FooBarUser',
    password: 'FooBar',
    // auto_reconnect: false,
  //  ssl: false,
   // stringify: false   

===================================================

Debugger listening on port 7915
error: A hook (`session`) failed to load!
d:\Projects\MyApp\node_modules\sails\lib\app\lower.js:81
   if (!_.isObject(sails.hooks) || !sails.hooks.sockets || (sails.io.httpServe
                                                                    ^
TypeError: Cannot read property 'httpServer' of undefined



   
   
npm install connect-mongo@0.8.2 --save

**Comment by nate-r** [comment]
@reyou Can you try installing the latest connect-mongo, and adding a url option in your sessions.js with the connection parameters?  That got it working for me.

**Comment by reyou** [comment]
@nate-r  thanks for your quick response.
It is working now with url option.

```
 url: "mongodb://FooBarUser:fooPassword@123456789.mongolab.com:58548/FooBarMongoLab",
 stringify: false   
```

**Comment by greghesp** [comment]
@nate-r Unfortunately this one didn't work for me.

In **connections.js**
```
  mongo: {
    adapter: 'sails-mongo',
    host: '12345.mongolab.com',
    port: 59365,
    user: 'user',
    password: 'password',
    database: 'database'
  },
```
**sessions.js
**```
adapter: 'mongo',
url: 'mongodb://user:password@12345.mongolab.com:59365/database/sessions',
stringify: false
```
Oddly, if I lift it without sessions.js in verbose mode, it seems like the connection times out, but if it lift it normally it works fine.  Neither work with sessions.js though

**Comment by nate-r** [comment]
@greghesp try taking the collection name out of the url in sessions.js.  I found including it results in that multiple databases specified error.

**Comment by greghesp** [comment]
@nate-r That works perfectly.  This needs to be made a bit clearer, especially as the example includes the collection name..

**Comment by sgress454** [comment]
@nate-r Thanks for the post.  The `Cannot read property 'httpServer' of undefined` error is indeed unrelated, and will be fixed in an upcoming patch.

So is the issue then that the new version of connect-mongo only works with the `url` setting, and not with `host`, `port`, `user`, `password` and `database`?  Also, can you check whether it works if you use `url` with a _separate_ `collection` setting, e.g.:

```
url: 'mongodb://user:password@12345.mongolab.com:59365/database',
collection: 'mysessions'
```

Connect-mongo uses the `sessions` collection by default anyway, so this would be just if you want to use something else.  Just trying to comfirm if we need to update our example to not have the collection in the URL.

**Comment by nate-r** [comment]
@sgress454 Looks like it behaved as expected with this sessions.js:
```
  adapter: 'mongo',
  url: 'mongodb://localhost:27017/foo',
  collection: 'bar',
```

I see a new db called "foo" and a collection called "bar" with one document for my test page load.

**Comment by sgress454** [comment]
Thanks for the update @nate-r.  We'll go ahead and fix up the example in our `config/connection.js` file.

**Comment by sgress454** [comment]
Ok, made updates to the example in a PR, would someone more immersed in using connect-mongo mind reviewing for correctness?

https://github.com/balderdashy/sails-generate-backend/blob/fix-connect-mongo-example/templates/config/session.js

**Comment by mikermcneil** [comment]
@sgress454 @nate-r @greghesp @brettimus while you're at it, would really appreciate someone reviewing: http://preview.sailsjs.org/documentation/reference/configuration/sails-config-session#?using-other-connectcompatible-session-stores

Thanks everybody!

**Comment by mikermcneil** [comment]
@brettimus :+1: if they're working for you too, I think we can safely say the updated options are good to go for the docs (I assume we're both thinking about the sails.config.sessions reference page there yeah?)

**Comment by sgress454** [comment]
@mikermcneil I'm not sure the preview.sailsjs.org docs got updated with the latest from the repo--it still refers to 0.8.4 on the site, but I've updated the docs here: https://github.com/balderdashy/sails-docs/blob/master/reference/sails.config/sails.config.session.md#using-other-connect-compatible-session-stores

**Comment by japel** [comment]
@sgress454 @mikermcneil 
Don't know if this is related, but this also seens to happen with normal waterline connections to mongodb.

If I lift with "suspend on every uncaughtException" I get:
```javascript
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined
2016/02/26 02:41:49 ERROR uncaughtException: Cannot read property 'httpServer' of undefined

Process finished with exit code 1
```

node v0.10.41
sails v0.12.0
npm v2.14.17

**Comment by japel** [comment]
(I don't use a persistant session store)

**Comment by sgress454** [comment]
@japel This issue had to do with using MongoDb for the session store, so I don't think your issue is related.  If you can get more info together on how to reproduce (and more error info if available), I'd open a new issue.  But I'd also check against the master branch of Sails--there was an issue with `.lower()` that's been patched, which looks similar to what you're seeing.

**Comment by sgress454** [comment]
@nate-r @mikermcneil merged in the new example in sails-generate-backed, and the docs look good, si I'm closing this.  If anyone continues to see issues on Mongo sessions with the new examples, please open a new issue with more info!
