### ISSUE TITLE
Strange npm warning 

### ISSUE THREAD

**Issue by brettimus** [balderdashy/sails#3575]
A short aside, thanks for the user-friendly message that accompanies `sails-new` these-a-days!

Now, I get a handful of deprecation warnings when starting a new project, but I found the last line a little confusing (and related to the aforementioned user-friendly message).

```
npm WARN update-linked node_modules/sails needs updating to 0.12.0 from 0.12.0 but we can't, as it's a symlink
```

I'll do some digging, but I figured I would put it here for now!

![image](https://cloud.githubusercontent.com/assets/3201327/13036018/3b697c5e-d311-11e5-9c46-bf744f008843.png)

**Comment by brettimus** [comment]
O. I get it now :grin:

**Comment by mikermcneil** [comment]
:monkey_face:

**Comment by swapnarajaputra** [comment]
@brettimus 

I am getting similar message. Unable to figure out the problem.. Can you please tell me how did you fix it.

**Comment by wyoumans** [comment]
@swapnarajaputra Just `rm -rf node_modules` and then `npm install`
