### ISSUE TITLE
Enhance Sails to work with es2015 exports as well as legacy code

### ISSUE THREAD

**Issue by commandline** [balderdashy/sails#3576]
This one took a little while to understand and the comments reflect my working through it. I've kept the original description, below, and comments for reference as the symptom is non-obvious.

Basically, ```module.exports = function foo()``` is not the same as ``` export default function foo()```. The former makes the result of a require/import the function itself. In ES2016, though, the default keyword established a default namespace within the module. There are reasons, the links for which I can dig up on request, but basically this is a consequence of ES2015 modules being statically analyzable.

For things like controller modules, you just have to be sure to export named functions themselves or if you want to do some wrapping between defining your functions and exporting them as some symbol on the module, you need to use ```export const externalName = generate(myHandler)``` instead of ```export default { externalName: generate(myHandler) }```. The latter places ```externalName``` under a default key for the module which the Sails code doesn't know to examine.

The other breakage I found is with policies. Following the documentation and using module.exports, policies are single function only modules. This doesn't appear to have a direct analog in ES2015 which means you have to continue to use ```module.exports = function canWrite()```. Trying to do ```export default function canWrite()``` results in a module with the default name space and a single entry, a function named canWrite. Not the same and hence lifting fails for even less obvious reasons, complaining of a non-function controller.

*Original description:*

With 0.11.5 and 0.12, my app now completely fails to bind any of my custom routes, saying it cannot find the controllers. Even with --silly, I don't see any particular errors. I am using the babel hook and made sure that is set to the latest, 6.0.1. No idea if that has anything to do with anything. 0.11.4 worked fine but that version no longer appears to be available for installation. I am still working through my non-trivial configs to try to isolate the problem because another, smaller app works just fine with 0.11.5 but nothing in comparing them has helped me resolve this. I cannot share my sources, this is a private repo, but can answer any detailed questions about my app that might help narrow down why my controllers don't appear to be available to the router.

**Comment by commandline** [comment]
I think I have a bead on what is going on and it seems to be some change in either Babel6, the hook enabling the latest babel, or the way controllers are loaded and found.

I added some logging near here: https://github.com/balderdashy/sails/blob/master/lib/hooks/controllers/to-interpret-route-syntax.js#L150

That revealed that the controller module is found but my handlers are not properties of that object, they are instead properties of a 'default' object. This makes sense since I use ```export default { }``` to create an object with keys for my controller names and whose matching values are functions that are produced by decorator functions.

I can probably work around this, for now, though I have a fair number of controller actions.

Might it make sense to recognize the default export in this instance and fold its properties up into the controllers middleware object so that routing works as it once did with slightly older versions of the transpiler/hook/Sails combo? If so, I can work on a PR for this.

**Comment by commandline** [comment]
Augh. Changing my exports has solved one problem only to reveal another. Something about the way policies are getting bound is resulting in broken controllers.

```javascript
    In studio.loadlanding, ignored invalid attempt to bind route to a non-function controller: { hasSiteInSession: [Function: wrapper],
      identity: 'hassiteinsession',                                                                                                                                   
      globalId: 'hasSiteInSession',                                                                                                                                   
      sails:                                                                                                                                                          
                                                                                                                                                                      
         |>   [a Sails app]                                                                                                                                           
       \___/  For help, see: http://links.sailsjs.org/docs                                                                                                            
                                                                                                                                                                      
       Tip: Use `sails.config` to access your app's runtime configuration.                                                                                            
                                                                                                                                                                      
       8 Models:                                                                                                                                                      
       AuthorizedClient,Document,PublishedDocument,PublishedSite,SSOToken,Site,StockPhotos,ThemeStyles                                                                
                                                                                                                                                                      
       16 Controllers:                                                                                                                                                
       BlackListController,DocumentController,HealthController,HelpController,IconController,ImageController,PartnerStoreController,PublishController,RenderingController,SSOController,ServerLifecycleManagementController,SiteController,SitemapController,StockPhotosController,StudioController,TemplateController                      
                                                                                                                                                                      
       23 Hooks:                                                                                                                                                      
       moduleloader,logger,request,orm,views,blueprints,responses,controllers,sockets,pubsub,policies,services,csrf,cors,i18n,userconfig,session,grunt,http,userhooks,logging,babel,validator                                                                                                                                               
       ,                                                                                                                                                              
      _middlewareType: 'POLICY: hasSiteInSession' } for path:  /landing and verb: get
```

**Comment by sgress454** [comment]
@commandline I can't speak to any of the problems with `sails-hook-babel` as that's not a project we maintain.  However you should definitely be able to install Sails 0.11.4 with `npm install sails@0.11.4`.

**Comment by commandline** [comment]
One of the folks watching the hook project helped me work through this. Still not sure what exactly changed to trigger this but explicitly using the add-module-exports plugin for Babel completely resolved my issues, restoring my app's functioning to how it was on Friday with no doubt a subtly but significantly different installed set of deps.

**Comment by mikermcneil** [comment]
@commandline glad to hear things leveled out-- there was definitely a bit of funny business going on with NPM around the same time you were having these issues (at least from Austin) so that may have been related.
