### ISSUE TITLE
Sails check every connection when lift in production mode

### ISSUE THREAD

**Issue by leosuncin** [balderdashy/sails#3581]
I had problems to deploy sails to heroku with ORM connection to MongoLab:
```
{ [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }
```
First I thought was a error relative to https://github.com/balderdashy/sails/issues/939 and I used diferent connection settings in `config/env/development.js` and `config/env/production.js`
```js
// config/env/production.js
module.exports = {
    connections: {
        mongoDbDefaults: {
            adapter: 'sails-mongo',
            host: 'ds045644.mongolab.com',
            port: 45644,
            user: 'heroku_user',
            password: 'longpa55w0rd',
            database: 'heroku_db',
            schema: true
        }
    },
    models: {
        connection: 'mongoDbDefaults',
        migrate: 'safe'
    }
};
```

```js
// config/env/development.js
module.exports = {
    connections: {
        mongoDbDefaults: {
            adapter: 'sails-mongo',
            host: 'localhost',
            port: 27017,
            database: 'sails-db',
            schema: true
        }
    },
    models: {
        connection: 'mongoDbDefaults',
        migrate: 'safe'
    }
};
```
Works in local until I pushed to heroku and got the same error, after a long time I stopped my local MongoDB instance and tried again and throws the error. The problem is ORM check every connection before start even development connection when is in production mode, I think that is not the best way to follow, if run in production mode please don't check development connection.

At the end I have to make the next changes:
```js
// config/connections.js
module.exports = {
    mongoDbDefaults: {
         adapter: 'sails-mongo',
         host: 'ds045644.mongolab.com',
         port: 45644,
         user: 'heroku_user',
         password: 'longpa55w0rd',
         database: 'heroku_db',
         schema: true
    }
};
```

```js
// config/env/production.js
module.exports = {
    models: {
        connection: 'mongoDbDefaults',
        migrate: 'safe'
    }
};
```

```js
// config/env/development.js
module.exports = {
    models: {
        connection: 'mongoDbDefaults',
        migrate: 'safe'
    }
};
```
Procfile
 ```
web: node app.js --prod --verbose+ --silly
```
> sails v0.12.0-rc8
> node v0.12.9
> sails-mongo v0.11.4

**Comment by mikermcneil** [comment]
Really appreciate the detailed analysis, @leosuncin.  Would you mind posting the stack trace from the error you're seeing just for completeness?  The development env file should definitely be getting ignored in production.  How are you starting your app in production at the moment? (i.e. env vars, etc)  Thanks!

**Comment by leosuncin** [comment]
Stacktrace
```sh
error: Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
 Error details:
{ [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }
  at _createError (/home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/lib/adapter.js:103:23)
  at /home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/lib/adapter.js:106:13
  at /home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/lib/connection.js:25:20
  at /home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/node_modules/mongodb/lib/mongo_client.js:276:20
  at /home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/node_modules/mongodb/lib/db.js:224:14
  at [object Object].<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:234:9)
  at [object Object].g (events.js:199:16)
  at [object Object].emit (events.js:110:17)
  at [object Object].<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:269:68)
  at [object Object].g (events.js:199:16)
  at [object Object].emit (events.js:110:17)
  at [object Object].<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:81:12)
  at [object Object].g (events.js:199:16)
  at [object Object].emit (events.js:110:17)
  at Socket.<anonymous> (/home/leosuncin/Workspaces/github/student/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:124:49
at Socket.g (events.js:199:16)
  at Socket.emit (events.js:107:17)
  at net.js:459:14
  at process._tickDomainCallback (node.js:381:11)
```
Also I check my git changes history and looked that `connections.js` include the example connection, I didn't pay any attention until now because I didn't reference in any `model` setting.
```js
/**
 * Connections
 * (sails.config.connections)
 *
 * `Connections` are like "saved settings" for your adapters.  What's the difference between
 * a connection and an adapter, you might ask?  An adapter (e.g. `sails-mysql`) is generic--
 * it needs some additional information to work (e.g. your database host, password, user, etc.)
 * A `connection` is that additional information.
 *
 * Each model must have a `connection` property (a string) which is references the name of one
 * of these connections.  If it doesn't, the default `connection` configured in `config/models.js`
 * will be applied.  Of course, a connection can (and usually is) shared by multiple models.
 * .
 * Note: If you're using version control, you should put your passwords/api keys
 * in `config/local.js`, environment variables, or use another strategy.
 * (this is to prevent you inadvertently sensitive credentials up to your repository.)
 *
 * For more information on configuration, check out:
 * http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.connections.html
 */

module.exports.connections = {

    /***************************************************************************
    *                                                                          *
    * Local disk storage for DEVELOPMENT ONLY                                  *
    *                                                                          *
    * Installed by default.                                                    *
    *                                                                          *
    ***************************************************************************/
    localDiskDb: {
        adapter: 'sails-disk'
    },

    /***************************************************************************
    *                                                                          *
    * MySQL is the world's most popular relational database.                   *
    * http://en.wikipedia.org/wiki/MySQL                                       *
    *                                                                          *
    * Run: npm install sails-mysql                                             *
    *                                                                          *
    ***************************************************************************/
    someMysqlServer: {
        adapter: 'sails-mysql',
        host: 'YOUR_MYSQL_SERVER_HOSTNAME_OR_IP_ADDRESS',
        user: 'YOUR_MYSQL_USER',
        password: 'YOUR_MYSQL_PASSWORD',
        database: 'YOUR_MYSQL_DB'
    },

    /***************************************************************************
    *                                                                          *
    * MongoDB is the leading NoSQL database.                                   *
    * http://en.wikipedia.org/wiki/MongoDB                                     *
    *                                                                          *
    * Run: npm install sails-mongo                                             *
    *                                                                          *
    ***************************************************************************/
    someMongodbServer: {
        adapter: 'sails-mongo',
        host: 'localhost',
        port: 27017,
        // user: 'username',
        // password: 'password',
        // database: 'your_mongo_db_name_here'
    },

    /***************************************************************************
    *                                                                          *
    * PostgreSQL is another officially supported relational database.          *
    * http://en.wikipedia.org/wiki/PostgreSQL                                  *
    *                                                                          *
    * Run: npm install sails-postgresql                                        *
    *                                                                          *
    *                                                                          *
    ***************************************************************************/
    somePostgresqlServer: {
        adapter: 'sails-postgresql',
        host: 'YOUR_POSTGRES_SERVER_HOSTNAME_OR_IP_ADDRESS',
        user: 'YOUR_POSTGRES_USER',
        password: 'YOUR_POSTGRES_PASSWORD',
        database: 'YOUR_POSTGRES_DB'
    }

    /***************************************************************************
    *                                                                          *
    * More adapters: https://github.com/balderdashy/sails                      *
    *                                                                          *
    ***************************************************************************/

};
```

**Comment by sgress454** [comment]
@leosuncin There's a [note in the docs for connection configs](http://sailsjs.org/documentation/reference/configuration/sails-config-connections#?multiple-connections-for-an-adapter) about multiple connections on the same adapter:

> Note If any connection to an adapter is used by a model, then all connections to that adapter will be loaded on sails.lift, whether or not models are actually using them... It is therefore good practice to split your connection configurations up by environment and save them to the appropriate environment-specific config files, or else comment out any connections that you don't want active.

This has caused a lot of hiccups for people, enough so that we've [updated the generator](https://github.com/balderdashy/sails-generate-backend/pull/32) so that those connection examples are commented out by default.  Please try removing those examples from your `config/connections.js` and see if it resolves the issue.

If not, then the best thing to do would be to create a new repo that reproduces this issue so that we can take a closer look.  Here's some instructions (you can get the `hub` tool [here](https://hub.github.com/) to make it easier): 

```
sails new sails-issue-3581
cd sails-issue-3581
npm install sails-mongo@0.11.6 --save
# Now make whichever are the simplest/quickest changes which reproduce the issue,
# and when you for sure have the issue isolated, run:
git init
hub create  # or use the GitHub UI to create the repo and `git remote add` it manually
git add .
git commit -am 'Reproduces https://github.com/balderdashy/sails/issues/3581'
git push -u origin master
hub browse # or open the repo in your browser manually
# Then copy the URL of the new repo and paste it as a comment on this issue.
# We'll check it out, and since this way we'll be able to experience the problem
# ourselves, we should have no problem getting to the bottom of it.
```

Thanks!

**Comment by leosuncin** [comment]
`someMongodbServer` is not referred or set in any model settings. Why do sails load it anyway? why don't sails load the others examples connections? and this must throw more errors due to I don't install the others adapters.
```js
/**
 * Default model configuration
 * (sails.config.models)
 *
 * Unless you override them, the following properties will be included
 * in each of your models.
 *
 * For more info on Sails models, see:
 * http://sailsjs.org/#!/documentation/concepts/ORM
 */

module.exports.models = {

  /***************************************************************************
  *                                                                          *
  * Your app's default connection. i.e. the name of one of your app's        *
  * connections (see `config/connections.js`)                                *
  *                                                                          *
  ***************************************************************************/
  // connection: 'localDiskDb',

  /***************************************************************************
  *                                                                          *
  * How and whether Sails will attempt to automatically rebuild the          *
  * tables/collections/etc. in your schema.                                  *
  *                                                                          *
  * See http://sailsjs.org/#!/documentation/concepts/ORM/model-settings.html  *
  *                                                                          *
  ***************************************************************************/
  // migrate: 'alter'

};
```

**Comment by sgress454** [comment]
@leosuncin 

> If any connection to an adapter _is used by a model_, then all connections to that adapter will be loaded on sails.lift

Those other adapters aren't loaded because models aren't using them.  Sails isn't loading every _adapter_, it's loading every _connection_ to the `sails-mongo` adapter, because you have models that are using that adapter.  This is a known, documented issue with the way that Waterline works, with the very simple workaround of commenting out that connection.  Does commenting out the `someMongodbServer` connection resolve your issue?

**Comment by leosuncin** [comment]
https://github.com/leosuncin/sails-issue-3581
Leave models and controllers empty (no custom action or attribute)
Use enviroment variables to set mongo and redis connection

**Comment by sgress454** [comment]
@leosuncin I'm unable to reproduce the issue with your repo, because it doesn't contain any models using any of the mongo connections.  However, If I add a new model with `sails generate api user`, and then set the `connection` property in `config/models.js` to `mongoDbDefaults`, and then set the `someMongodbServer` connection config in `config/connections.js` to a non-standard port, I get an error, due to the note I mentioned above: even though my model isn't using `someMongodbServer`, Sails is loading that connection because it uses the same `sails-mongo` adapter as another connection that _is_ being loaded.  

You are probably having the same issue, and the solution is simply to comment out the `someMongodbServer` connection in `config/connections.js`.  In fact, it is recommended that you comment out _all_ of the example connections in that file, and we will soon have that as the default in new apps.  

Please comment out the conflicting configuration and confirm that this solves your issue.

**Comment by leosuncin** [comment]
I set the connection in [config/env/development.js](https://github.com/leosuncin/sails-issue-3581/blob/master/config/env/development.js#L21) and [config/env/production.js](https://github.com/leosuncin/sails-issue-3581/blob/master/config/env/production.js#L44) not in [config/models.js](https://github.com/leosuncin/sails-issue-3581/blob/master/config/models.js#L20).

I don't think that sails must load and try to connect an unused connection (in this case `someMongodbServer`), maybe follow these:
1. Load connections to memory.
2. Load adapters to memory
3. Load model settings to memory.
4. Try to connect to model connection option.
5. Run the next things.

Instead of:
1. Load connection to memory.
2. Load adapters to memory.
3. Try to connect to all connections from adapter.
4. Load model settings.
5. Run the next things.

**Comment by leosuncin** [comment]
You can see the error message in the console http://asciinema.org/a/1gokbr26v0xffu1yyti38ldcb

**Comment by sgress454** [comment]
> I set the connection in config/env/development.js and config/env/production.js not in config/models.js.

Sorry, I missed that--in any case you still need at least one model before you can reproduce the error.

> I don't think that sails must load and try to connect an unused connection

Agreed that this is not ideal, and feel free to [make a proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements) in the [Waterline repo](https://github.com/balderdashy/waterline) for how to fix this.  In the meantime, it is a known, documented issue, and the workaround (commenting out or removing the conflicting configuration) is very clear.  If the workaround fixes your specific problem, please confirm so that we can close this post!

**Comment by leosuncin** [comment]
Thanks
