### ISSUE TITLE
Redis session and connection error 

### ISSUE THREAD

**Issue by udanpe** [balderdashy/sails#3586]
When redis server not running. Sails don't show any error.
+
"developers by developers" and use memory storage as default it's not cool.
Add disk storage for session

**Comment by mikermcneil** [comment]
@udanpe I appreciate you taking the time to share your thoughts.  I wish I could help more, but I'd need [a bit more information first](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md).  I'm going to close this issue to keep the queue moving, but please feel free to open a new issue with details on how to reproduce the scenario you're seeing with the bad/absent error message.  Don't forget to include your Node, NPM, and Sails versions, as well as the version of `connect-redis` you are using.  If you see a straightforward solution for introducing a better error message, please [open a pull request with a patch](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md) to the appropriate repo.  Thanks!
