### ISSUE TITLE
"Unique" validation rule does not provide Model in error object

### ISSUE THREAD

**Issue by Mitjan11** [balderdashy/sails#3587]
I've built a service that relies on getting the model name where a create/update error occurred to build i18n string names. For example:

If a validation error occurs on the minLength rule in the username attribute of the User model, it will attempt to find an i18n string with the "user.username.minlength", and otherwise display the default error message.

Now it is all working correctly as I am able to fetch the model where the error occurred through err.model on every single validation rule. However, this value seems to be absent in the unique validation rule?

Here's a comparison of the error object of a "required" and a "unique" validation error:

_required_
{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid",**"model":"Page"**,"invalidAttributes":{"title":[{"rule":"required","message":"\"required\" validation rule failed for input: ''"}]}}

_unique_
{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid","invalidAttributes":{"title":[{"value":"New page!","rule":"unique","message":"A record with that `title` already exists (`New page!`)."}]}}

I have read in the documentation that the unique rule is different from others due to being a database constraint. Would this be the reason for this inconsistency?

**Comment by udanpe** [comment]
https://github.com/lykmapipo/sails-hook-validation

**Comment by Mitjan11** [comment]
Thanks for the reply, but I've already tried that hook and didn't get it to work properly so I started fiddling around with it myself and just ended up finding this little inconsistency.

I'm not too worried about getting this to work at all but I thought I'd report the inconsistency anyway :)

**Comment by mikermcneil** [comment]
@udanpe thanks for sharing the link!

@Mitjan11 appreciate the report.  This indeed sounds like inconsistent behavior (not how it's supposed to be working), and it's something we can improve in a patch release. Your hypothesis is probably right (i.e. that the issue stems from unique errors being handled differently).  Would you mind jotting down your version of Node, NPM, and Sails, as well as the package name and version of the adapter you're using (e.g. sails-mysql@0.11.3)?  Thanks!

@particlebanana going to go ahead and move this to the Waterline repo-- if it's happening across adapters, then it could be something that changed in core.  Apparently we used to have a failsafe that asserted that a `model` property was specified for WLValidationErrors-- but then [I removed it for some reason](https://github.com/balderdashy/waterline/commit/f63583082c63f2f5e52db037e59b99cda8ff536a).

**Comment by mikermcneil** [comment]
This issue was moved to balderdashy/waterline#1311
