### ISSUE TITLE
Attribute method save() invalid callback in sails@0.12

### ISSUE THREAD

**Issue by gdraganic** [balderdashy/sails#3595]
After migrating from sails@0.11.5 to sails@0.12.1 i have many problems because save method has an invalid callback:

```
someInstance.save(function(err, saved) {
  // returns undefined, undefined
});
```

Maybe there is the same problem on other attribute methods.

**Comment by sgress454** [comment]
Hi @gdraganic, please see the [item in the migration guide for Sails v0.12](http://sailsjs.org/documentation/concepts/upgrading/to-v-0-12#?save-no-longer-provides-a-second-argument-to-its-callback) regarding this change.
