### ISSUE TITLE
0.12.1 performance compared to 0.11.5

### ISSUE THREAD

**Issue by jgeurts** [balderdashy/sails#3602]
I recently tried an upgrade from sails 0.11.5 to 0.12.1 and noticed a pretty significant slow down. We have a set of unit/integration tests that lifts sails, runs tests, and spits out how long tests took to run after sails has lifted. With 0.11.5, the tests complete in roughly 6s. With 0.12.1, they complete in 30s. In addition lifting of sails is noticeably slower. 

I can do some digging to help narrow things down, but from a high level, we're using sailsjs with mongo as the db and redis for session management. Is this a known problem?

**Comment by jgeurts** [comment]
This may be a non-issue... I blew away the folders in node_modules and did an npm install and the timing is back where it should be

**Comment by sgress454** [comment]
Thanks @jgeurts.  If problems resurface and you have more info, please let us know.
