### ISSUE TITLE
Node js SSL error {“code”:“CERT_UNTRUSTED”}

### ISSUE THREAD

**Issue by abdulrashid9** [balderdashy/sails#3605]
I am using node version 0.12.7 with npm (2.11.3) and sails (0.11.5). So in the project i consuming REST Api using request (npm Module). API is on another domain so I enable CORS in sails, Everything is working fine On QA server but when i move my code to production (API is hosted with SSL) at API call it says

`{"code":"CERT_UNTRUSTED"}.`

Below is API call with request module.

```
request({
        url: sails.config.constant.baseApiUrl+'login',
        method: "POST",
        json: true, 
        body: data
    }, function (error, response, body){
            console.log('error:- '+JSON.stringify(error));
            console.log('response:- '+JSON.stringify(response));
            console.log('body:- '+JSON.stringify(body));


         // Other code to handle response

    });
```

*Response:-*
error:- {"code":"CERT_UNTRUSTED"}
response:- undefined
body:- undefined

Is that any way to solve this issue in sails js?

**Comment by sgress454** [comment]
@abdulrashid9 This doesn't sound like a Sails issue at all, but an issue with making a request to a secure server without providing any credentials.  See [the `request` docs](https://github.com/request/request#tlsssl-protocol) for info on how to specify a certificate to use when making a request.  You can also try adding `rejectUnauthorized: false` to the request options.
