### ISSUE TITLE
"'Uncaught TypeError: Cannot read property 'removeChild' of null'" being thrown by sails.io.js on line 200

### ISSUE THREAD

**Issue by kpturner** [balderdashy/sails#3606]
I keep getting this error every so often on the browser.  I cannot seem to track down any particular pattern.   Can anybody point me in the right direction as to when this function is likely to be called.  It doesn't seem to coincide with any user interaction.

**Comment by sgress454** [comment]
Hi @kpturner.  This is a [PhantomJS issue](https://github.com/ariya/phantomjs/issues/10522) that should be solved in PhantomJS version 2.

**Comment by sgress454** [comment]
Sorry, posted in wrong issue!

**Comment by sgress454** [comment]
@kpturner Can please you post this in the [sails.io.js issues forum](https://github.com/balderdashy/sails.io.js/issues) ) (along with your versions of Sails and sails.io.js), link back here and then close this issue?  Also please clarify "every so often on the browser": does it happen more than once per page load?  Does it happen when the page is sitting idle?  Does it happen right after the socket connects?  Any additional info will be helpful.

**Comment by kpturner** [comment]
It seems to happen when the page is idle - but I will repost
