### ISSUE TITLE
blueprints/index.js references object, does nothing

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/sails#3608]
I believe these lines are a mistake, since it seems like nothing's happening: https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/index.js#L405-L406

**Comment by sgress454** [comment]
Hm, I think this was perhaps meant for the sake of clarity, to give some context to the "Start off w/ the built-in blueprint actions (generic CRUD logic)" comment, but it's been pointed out before so I'm guessing it's not having the intended effect.

**Comment by mikermcneil** [comment]
Thanks Kevin.
