### ISSUE TITLE
request.session.id No longer in v0.12?

### ISSUE THREAD

**Issue by crobinson42** [balderdashy/sails#3609]
I upgraded from 0.11 to 0.12 and my app relied on `req.session.id` which seems to not be available in the newest release.

This isn't documented in the CHANGELOG. https://github.com/balderdashy/sails/blob/master/CHANGELOG.md

**Comment by mikermcneil** [comment]
@crobinson42 thanks for making an issue.  Would you mind adding some information about your node/npm version, as well as the specific Sails version you're using, your session configuration, and the name and version of the connect session adapter package you're using?  Thanks!

@sgress454 could this be something to do with https://github.com/balderdashy/sails/commit/329d1d75b8a563ef134230df70e3550e482859c1#diff-30772e207fff1c62d9567fb36d10e453R124?  If so, @crobinson42, I'd expect we'd only be seeing this in the 0.12.1 patch.

**Comment by crobinson42** [comment]
```
sails -v
0.12.1
node --version
v4.3.1
npm -v
2.14.12
```
I'm using connect-redis but I also get the same behavior with a fresh sails project without redis.

**Comment by crobinson42** [comment]
I also tried this in sails v0.12.0 and get the same result.

**Comment by crobinson42** [comment]
I'm unable to reproduce in fresh sails project after wiping and npm install.. will investigate more and reopen if it remains an issue.

**Comment by crobinson42** [comment]
HOLY COW! I figured out WHY someone will experience this (or at least how to replicate).

Follow these steps:
create a fresh sails project
npm install babel sails-hook-babel babel-preset-es2015

Now, add a controller:
```
module.exports = {
	session : function (req ,res) {
		res.send('session has id key: ' + req.session.hasOwnProperty('id'));
	}
};
```

There will be no session.id!

**Comment by crobinson42** [comment]
This is only happening with my code base when I install the babel packages list above. I'm unsure **why**, though. Sorry for the false alarm.
