### ISSUE TITLE
"Controller" suffix required?

### ISSUE THREAD

**Issue by markelog** [balderdashy/sails#3610]
This is a duplicate of https://github.com/balderdashy/sails/issues/2738.

Since no one answered to me in it, i decided to re-post it here - 
Was the code proposed for that issue? If not, would it be accepted if done correctly?

**Comment by sgress454** [comment]
This is now [documented as a Sails convention](http://sailsjs.org/documentation/concepts/controllers#?where-are-controllers-defined).  If you want to try your luck, the proper way would be to make a pull request adding the feature to the backlog, write up why you think it's a good idea (you can probably just copy-and-paste the relevant bits from the old thread), and open it up for comments (see the [contribution guide section on proposals](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements)).  Just note that part of the guide says:

> Please do not propose changes to the established conventions or default settings of Sails.

so you might not get too far with it, but I'll recuse myself ;-)

**Comment by markelog** [comment]
Well, that's encouraging :), thank you for the info, will try my luck.
