### ISSUE TITLE
update i18n to latest version 

### ISSUE THREAD

**Issue by martingg88** [balderdashy/sails#3611]
fyi. i18n version 0.7 has already been published to npm. Please update it at your side. thanks.

https://github.com/balderdashy/sails/issues/3435

**Comment by sgress454** [comment]
i18n 0.7.0 (and the new 0.8.0) causes the Sails tests to fail.  That's pretty disturbing.

0.6.0 seems to work alright, but I'm holding off for the moment.  It's possible that the tests failing with 0.7.0 is due to an issue in Sails core, not in i18n; either way, someone needs a patch.

**Comment by sgress454** [comment]
There's a pull request for this #3631 so I'll close this issue in favor of that.
