### ISSUE TITLE
New attribute type for multiple models

### ISSUE THREAD

**Issue by Seafnox** [balderdashy/sails#3614]
Can I create hook or service for work with my own attribute type like file or data64?
How can i create my own handler for that type?

I need to use this attribute type for multiple models.

**Comment by Seafnox** [comment]
I try to create something like that
```
module.exports = {
  attributes: {
    image: {
      type: 'file',
      defaultsTo: "http://dummyimage.com/300x200/e0e0e0/f0f0f0",
      required: true,
      sizes: {
        thumb: {
          width: 30,
          heigth: 30
        }
      }
    },
    ...
  }
}
```

**Comment by irlnathan** [comment]
Howdy @Seafnox,

StackOverflow would be a better platform for this question.
Thanks!
Best, Irl
