### ISSUE TITLE
actionUtil.parseValues returns 'id' field even if Model.primaryKey is not 'id'

### ISSUE THREAD

**Issue by swarthy** [balderdashy/sails#3625]
Model Goal.js:
```javascript
module.exports = {
  attributes: {
    hash: {
      type: 'string',
      unique: true,
      primaryKey: true
    },
    id: 'integer', // from 1 to 20 (not unique)
    active: 'boolean',
    ...
  }
}
```
Response from Google Analytics API is stored here (I want to save same field names). 
'id' is returned from Google and it is not unique (may be only 20 goals for GA counter), so I use my 'hash' field as PK 
The problem is that on update `actionUtil.parseValues` returns object like that:
```javascript
{
  hash: '<myhash>',
  id: '<myhash>',
  name: 'newName'
}
```
and it brakes my data
when I send
`PUT /goal/<myhash>` `{active: false}`
blueprint set
```javascript
{
  id: '<myhash>',
  active: false
}
```

I figured it out by overriding GoalController.update, but is there any way possible to fix this issue?
Hope, you understood what I wanted to say :smile:

**Comment by sgress454** [comment]
Thanks for the report @swarthy, we'll look into it!
