### ISSUE TITLE
res.sendFile is not a function

### ISSUE THREAD

**Issue by cperryk** [balderdashy/sails#3627]
Attempting to use `res.sendFile` on middleware will result in an error: `res.sendFile is not a function`. It appears Sails has `res.sendfile` but Express uses [res.sendFile](http://expressjs.com/en/api.html#res.sendFile). Note the capital F. The all-lowercase spelling is consistent with the spelling that appears in Sails documentation [here](http://sailsjs.org/documentation/reference/response-res), but I suspect the discrepancy with Express is not intended. The method is not documented at all in the [documentation for the response object](http://sailsjs.org/documentation/reference/).

**Comment by sgress454** [comment]
Hi @cperryk, Sails uses Express 3 as its router, which has [res.sendfile](http://expressjs.com/en/3x/api.html#res.sendfile).
