### ISSUE TITLE
populate will return all wrong association tables when has the same model or collection name

### ISSUE THREAD

**Issue by luolongzhi** [balderdashy/sails#3629]
if has attributes as below. such as owner,  upUsers, downUsers, and they has same assoiation table User model,
Then if I populate only one owner(model: 'user'), the return value will return owner, upUsers(collection: 'user'), downUsers...
but only owner is valid, the other is the empty [] , I think if I do not populate upUsers, they should not display, and if display should not empty array [], but populate owner, all other display with empty array[]

   Topic.find()
   .populate('owner')
   .then(function(ret) {
       res.json(ret);
}

this will return all upUsers, donwUsers, and I think because they has same assosasion model User

    owner: {
      model: "user",
      required: true
    },

    name: {
      type: 'string',
      required: true
    },

    desc: {
      type: 'string'
    },

    detail: {
      type: 'text'
    },

    image: {
      type: 'string'
    },

    upUsers: {
      collection: 'User',
      via: 'upTopics'
    },

    downUsers: {
      collection: 'User',
      via: 'downTopics'
    },

    favoriteUsers: {
      collection: 'User',
      via: 'favoriteTopics'
    },

**Comment by luolongzhi** [comment]
I use sails 0.12.1, and sails-mysql is 0.11.5

**Comment by luolongzhi** [comment]
I recheck this, it will happen only populate the owner(Owner is the one-many), and return upUsers, downUsers

**Comment by luolongzhi** [comment]
[api.tar.gz](https://github.com/balderdashy/sails/files/154835/api.tar.gz)
this api test code can reproduce the problem, in UserController.find(), when populate cars, will return likecars with empty []

**Comment by sgress454** [comment]
@luolongzhi In order to return `likecars` you have to populate it:

```
User.find({id:1}).populate('cars').populate('likecars').exec(console.log)
```

Works for me--please verify on your end and if this was the problem, we can close the issue!

**Comment by luolongzhi** [comment]
I means if I only User.find({id:1}).populate('car').exec(console.log) will return likecars with [], I dont want likecars, but it return.

expect only cars [xxxx] array return ,but when populate cars, the likecars keys coming with [], I dont want this key.

**Comment by luolongzhi** [comment]
And pls see the api/model/Car.js,  the user defined with: {model: 'user'}, once defined model in Car, the User.find().populate('cars') will return all assossiat keys defined in Car.js related with 'user' (model or collection)

**Comment by luolongzhi** [comment]
this is the result when I only populate('cars')
[
    {
        "cars": [],
        "likecars": [],
        "name": "aa",
        "id": 1,
        "createdAt": "2016-03-02T06:30:18.000Z",
        "updatedAt": "2016-03-02T06:30:18.000Z"
    }
]

I think the likecars should not be display, it should be like this:
[
    {
        "cars": [],
      
        "name": "aa",
        "id": 1,
        "createdAt": "2016-03-02T06:30:18.000Z",
        "updatedAt": "2016-03-02T06:30:18.000Z"
    }
]

**Comment by luolongzhi** [comment]
But if not populate('cars'), just populate('likecars'), it just return likecars, see as below
[
    {
        "likecars": [],
        "name": "aa",
        "id": 1,
        "createdAt": "2016-03-02T06:30:18.000Z",
        "updatedAt": "2016-03-02T06:30:18.000Z"
    }
]

So, I think when define in api/mode/Car.js, if the attributes define with 'model', when populate this model key, will return all relate keys;  but if define with 'collection', it only return it self

So, I think this is populate bugs when populate the 'model' defined key

**Comment by sgress454** [comment]
Hm I think I see what you mean.  So just to be clear, you're not getting incorrect _data_, but when you do `populate('cars')` you're getting the `likecars` key in the result (as an empty array), whereas if you do `populate('likecars')`, you're _not_ getting an empty `cars` key.  I'm not sure if this is a bug or just not well documented.

**Comment by luolongzhi** [comment]
yes, that is what I means. I think if I just populate('cars'), I should not get any other keys which not populate. and this only happen when 'cars' set 'model' relationships with user, if is 'collection' the result
it right and not this problem.

In my project, there are many relationship with collection in one model, and I only populate 'owner' in my project, all other keys comes out with empty[], the frontend web engineer is confusion and don't know how to process this empty array.

**Comment by luolongzhi** [comment]
@sgress454 ,hi, how is going with this issue? how can I resolve the empty keys which not needed?

**Comment by mikermcneil** [comment]
>  how can I resolve the empty keys which not needed?
Hi @luolongzhi, we use empty arrays to represent unpopulated collection associations in results from Waterline.  As for your front-end engineer, you can customize the API for him or her as you see fit by writing custom actions.  If you can think of a place in our docs where information about this would be helpful, please submit a PR to [sails-docs](https://github.com/balderdashy/sails-docs) when we can.

If there is a separate issue here I'm missing, please open a new issue to let us know.  Thanks!

**Comment by luolongzhi** [comment]
I think this is wired.  some not populate, some use empty arrays to represent unpopulate collection?
so what is the result of real populate ?  if this array is really an empty array result, should I think this is an empty results or unpopulate results?
