### ISSUE TITLE
Css background-img rule can't import asset in production

### ISSUE THREAD

**Issue by eric-burel** [balderdashy/sails#3634]
======================================================

**Sails version**: 0.11.4
**Node version**: v4.3.1
**NPM version**: v2.14.12
**Operating system**: Ubuntu

<hr/>

Hi,

I have an issue with assets and css on production. I use the following CSS rules :
`.st-bg-pattern-ticks{
    background-image : url('/patterns/ticks.png');
}`

It works fine on local, I can also access my assets when visiting http://localhost:1337/patterns/ticks.png.
It also works with sails lift --prod, the minified css file contains the rules.
However, on production, http://www.stoulou.com/patterns/ticks.png is not accessible as any other assets, even the working ones (I guess this is normal ? Doc mostly talks about html assets), and the background image does not load. There are no 404 sent.

Images directly loaded with the img tag into my html code work fine however. Just for additional infos, using @import to load Google fonts inside my CSS did not work either, I don't know if it is related.

**Comment by sgress454** [comment]
Hi @eric-burel, there's quite a few apps out there in production using lots of assets, so I think it's safe to say that this is working in the general case.  If you can create a repo that demonstrates your issue, we'd be happy to take look.  See [here](https://gist.github.com/sgress454/76be129ebcf07beb203f) for instructions.

**Comment by eric-burel** [comment]
I tried to reproduce on a basic app and indeed background-image : url('bla') does work fine in production.
I'll try to investigate if angular ui-router is responsible for this issue.

**Comment by sgress454** [comment]
Thanks for the update, @eric-burel!
