### ISSUE TITLE
request.file method

### ISSUE THREAD

**Issue by dangreen** [balderdashy/sails#3656]
**Sails version**: 0.12.1
**Node version**: 5.7.1
**NPM version**: 3.6.0
**Operating system**: OS X 10.10

<hr/>
https://github.com/balderdashy/sails/blob/master/lib/router/req.js#L125
1) `res` is undefined
~~2) why `res.send(500, 'Streaming file uploads via req.file() are only available over HTTP with Skipper.')` ? Where skipper? i mean `console.log(request.file + "")` prints `function(){res.send(500...`~~ i do `if (request.file)` in my code, now `request.file` is always exist.

**Comment by Nishchit14** [comment]
@dangreen 
Need more description

**Comment by dangreen** [comment]
@Nishchit14 in `request.file` method `res` variable is undefined.
https://github.com/balderdashy/sails/blob/master/lib/router/req.js#L125

**Comment by mikermcneil** [comment]
> https://github.com/balderdashy/sails/blob/master/lib/router/req.js#L125

@dangreen thanks for the report!  We'll take care of it in the next patch release.  We added that stub method to help make it clearer that req.file() is specific to the default setup and skipper when working on the body parser, but clearly forgot to put `res` in place.
