### ISSUE TITLE
Empty response from long query.

### ISSUE THREAD

**Issue by macleod2486** [balderdashy/sails#3658]
**Sails version**: 0.12.1
**Node version**: 5.8.0
**NPM version**: 3.8.1
**Operating system**: Linux 4.3.6

<hr/>

I'm currently running SailsJS on a Raspberry Pi and all is working well however when I execute a sails.models.nameofmodel.count() when I attempt to respond with the result I end up getting a empty response.

    getListCount: function(req,res)
        {
             var mainsource = req.param("source");

             if(mainsource)
             {
                 sails.models.gatherer.find({source: mainsource}).exec(
                         function(error, found)
                         {
                                 if(error)
                                 {
                                         return res.serverError("Error in call");
                                 }
                                 else
                                 {
                                         sails.log("Number found "+found.length);
                                         return res.ok({count: found.length});
                                 }
                         }   
                 );
         }
         else
         {
                 return res.ok("Error in parameter");
         }   
    },

I am able to see in the logs the number that was found (73689). However when responding I still get an empty response. I am using the default stock ok.js file, however I did stick in additional logging to try to debug and make sure it is going through the correct paths. I was able to confirm that the ok.js was going through this path

    if (req.wantsJSON) {
        return res.jsonx(data);
    }

I also tried adding .populate() to the call before the .exec(), res.status(200) before I sent out a res.send() instead of res.ok(). I've also tried other versions of Sails and still getting the same empty response. I've also used a sails.models.gatherer.count() call with the same result.

It takes about 5-7 minutes for it to complete and have an empty response.

I'm thinking either I'm bad at programming and have gone about this wrong, there's a setting that I am unaware of to increase the timeout and/or remove it entirely, or there's an issue with being able to respond back in a reasonable time.

**Comment by mikermcneil** [comment]
@macleod2486 well your code looks fine to me (other than potentially needing to validate `req.param('source')`, depending on what you want to allow the client to do).  Another thing I would suggest is using `.count()` instead of `.find()` and then getting the `.length` of the result set (in some adapters, the call to `.count()` is optimized).

What adapter are you using for the database?  And if you're using sails-disk, about how many records are in your **Gatherer** model?

**Comment by macleod2486** [comment]
@mikermcneil I have tried count instead of find and had the same result.

For the adapter I am using sails-redis.

**Comment by particlebanana** [comment]
@macleod2486 I'm not sure if the sails-redis adapter has an optimized count, if not the small resources of the Raspberry Pi could be limiting the response. You can try and post this issue on the sails-redis repo and see if they have any insight. If you re-create the issue using an optimized adapter (sails-postgresql for instance) please let us know!
