### ISSUE TITLE
NullPointerException pk.type for model even if you set schema to false

### ISSUE THREAD

**Issue by akhan-netfore** [balderdashy/sails#3664]
**Sails version**:0.11.0
**Node version**:4.2.1
**NPM version**:2.14.7
**Operating system**:Ubuntu 14.04

<hr/>
In my model, I have following class properties:
```javascript
schema: false,
autoPK: false
attributes: {
 name: 'string'
}
```
when I do a find on the model and pass in a criteria 'id', sails throws a NullPointerException on  normalize.js:47
```javascript
      if (context.attributes[pk].type == 'integer') {
```
If I set the schema to be false, sails should protect its

**Comment by particlebanana** [comment]
This issue was moved to balderdashy/waterline#1326
