### ISSUE TITLE
sails 0.12.1 breaks lodash _.chain(obj) and _(obj) wrapper

### ISSUE THREAD

**Issue by bobbymanuel** [balderdashy/sails#3671]
**Sails 0.12.1 breaks lodash support for _.chain(obj) and _() object wrapper.**

If lodash is directly required then the two methods are correctly exposed; however, if you access lodash via the global `"_"` or `"sails.util._"` then these methods fail silently.

**Repro steps:**

1. from within your project, invoke `_({"a":1, "b":2}).forEach(function (val) {console.log(val);});`
2. observe the object is not iterated.
3. rewrite the above to `_.forEach({"a":1, "b":2}, function (val) {console.log(val);});` and it works fine
4. add `var _ = require('lodash')` to the top of your file and retry the object wrapper based iterator from line 1 and note that it also works fine
5. also note that line 1 works on 0.11.4 without issue

**Affected code** : 

though i don't use the global `"_"` or `"sails.util._"` much in my own code, the change broke a couple of open source installable hooks that I have been using

**Sails version**: 0.12.1
**Node version**: 0.12.2
**NPM version**: 2.7.5
**Operating system**: OSX 10.10.5

<hr/>

**Comment by sgress454** [comment]
HI @bobbymanuel -- what version of Lodash are you installing locally?  I think the issue here is just that Sails v0.12 upgraded to Lodash 3, which [changed the way chaining works](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings-1).

**Comment by bobbymanuel** [comment]
Hi @sgress454 -- Sorry about the delayed response. 

_I'm running lodash 4.x._

Seems like it might be best to move sails to lodash 4.x since lodash 3.x seems to break 2.x support while 4.x supports 2.x behavior but breaks 3.x behavior.  Though this is definitely a lodash snafu not a sails snafu - in an effort to minimize broken code - its probably best to skip 3.x entirely.

I'm not closing this issue just yet - but please close it if you feel comfortable with the above.  

I've already removed the broken installable hooks and replaced the functionality with custom app hooks so I'm good either way.  I'll just refrain from using lodash in my own code and disable the lodash "_" global from globals.conf.

**Comment by bobbymanuel** [comment]
Ok... i've identified exactly what's happened.

2.x _(iterable) does not lazy evaluate
3.x _(iterable)  and _.chain(iterable) always lazy evaluates and decorates wrapped object with  .value() call to trigger evaluation
4.x _(iterable) reverts to 2.x behavior and _.chain(iterable) retains 3.x forced lazy iteration, 3.x  compatibility is completely broken, _(iterable).value() doesn't exist anymore.

definitely a lodash issue - you should probably accelerate the 4.x upgrade

**Comment by sgress454** [comment]
Thanks for the insight Bobby.  We'll take a look at it, but upgrading the version of Lodash used inside of Sails isn't a top priority for us.  It's globalized as a convenience, but third-party hooks should definitely _never_ be relying on it, since the app developer can just turn off globals and crash their hook anyway.  If you can point me at those hooks I'll post a note to that effect for the maintainers.
