### ISSUE TITLE
Connect mongo 1.0 suggested in docs but doesn't work

### ISSUE THREAD

**Issue by dottodot** [balderdashy/sails#3685]
**Sails version**: 0.12.3
**Node version**: 4.3.1
**NPM version**: 2.14.6
**Operating system**: OSX 10.11.3

<hr/>

In the docs it says For Node version >= 4.0, install connect-mongo >= 1.0 but if I install this version when I lift my app I get the following error.

```
error: A hook (`session`) failed to load!
error: A hook (`orm`) failed to load!
error: Could not load Connect session adapter :: connect-mongo

Error from adapter:
Error: Cannot find module '/node_modules/connect-mongo'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Hook.SessionHook.initialize (node_modules/sails/lib/hooks/session/index.js:163:32)
    at Hook.wrapper [as initialize] (/node_modules/lodash/index.js:3095:19)
    at /node_modules/sails/lib/hooks/index.js:74:16
    at /node_modules/sails/node_modules/async/lib/async.js:52:16
    at /node_modules/sails/node_modules/async/lib/async.js:548:17
    at /node_modules/sails/node_modules/async/lib/async.js:542:17
    at _arrayEach (/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (node_modules/sails/node_modules/async/lib/async.js:541:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Do you have the Connect session adapter installed in this project?
Try running the following command in your project's root directory:
npm install connect-mongo
(Note: Make sure the version of the Connect adapter you install is compatible with Express 3/Sails v0.10)
```

**Comment by wulfsolter** [comment]
in `config/connections.js` change 'module' to 'adapter'?

I had a similar issue recently, wasn't sure about submitting a patch to docs.

**Comment by dottodot** [comment]
I assume you mean `config/session.js` but in any case both are already using adapter.

**Comment by mikermcneil** [comment]
@dottodot hmm looks like the issue is that it is trying to require from an absolute path-- which is pretty weird.  Check out the relevant line in core:
https://github.com/balderdashy/sails/blob/master/lib/hooks/session/index.js#L163

**Comment by mikermcneil** [comment]
Wulp ok, here's what's probably going on:

+ here's connect-mongo@1.0.0: https://github.com/kcbanner/connect-mongo/tree/v1.0.0
  + There's no index.js file!  So we check package.json and see what the "main" script is.  And it turns out [it's pointed at `lib/`](https://github.com/kcbanner/connect-mongo/blob/v1.0.0/package.json#L50)... which doesn't actually exist in that version.

@dottodot could you try `npm install connect-mongo@^1.0.0 --save --save-exact`?  That'll install the latest `1.x.x` version of connect-mongo and pin it at that version in your app's package.json.  If you can confirm that works for you, I'll update the docs to suggest installing `1.1.0` and we should be good to go.

Thanks!

**Comment by dottodot** [comment]
That's not throwing any errors so think it's ok. 

Also could you confirm if it should be `adapter: 'connect-mongo'` or `adapter: 'mongo'` both seem to work

**Comment by dottodot** [comment]
Also this only works if using a url.

**Comment by karsasmus** [comment]
fyi
https://github.com/balderdashy/sails/issues/3574#issuecomment-184401426

**Comment by mikermcneil** [comment]
> Also could you confirm if it should be adapter: 'connect-mongo' or adapter: 'mongo' both seem to work

Both work currently, but the first one is preferred (the latter is for backwards compatibility).

👍

**Comment by mikermcneil** [comment]
Updated the docs again, sorry for the confusion: https://github.com/balderdashy/sails-docs/commit/6f3b7c449beafa7d8cf6357b0cd38ff4cae99d5e

**Comment by sgress454** [comment]
Sounds like this one was resolved, thanks everyone!
