### ISSUE TITLE
Blank Response in res.badRequest() in Production mode

### ISSUE THREAD

**Issue by natarajanp** [balderdashy/sails#3689]
**Sails version**: 0.12.0
**Node version**: 4.2.1
**NPM version**: 2.14.7
**Operating system**: Mac OS

<hr/>

I've been using sails for more than a year and the issue I'm facing is really strange. **res.badRequest()** is sending a blank response in **Production** mode, but in **development** mode it's working as expected.. Any thoughts.. Many Thanks

`return res.badRequest({
        success: false,
        message: 'an error occurred. please try again later'
 })`

**Comment by natarajanp** [comment]
I guess, it's because of the following and I've never tested in production mode before

`// Only include errors in response if application environment
  // is not set to 'production'.  In production, we shouldn't
  // send back any identifying information about errors.
  if (sails.config.environment === 'production') {
    data = undefined;
  }`

**Comment by mikermcneil** [comment]
@natarajanp Thanks for taking the time to explain what's going on.  This is something we're looking at changing for Sails v1.  Originally, the intended behavior was for unexpected errors to have their data squashed in production (i.e. still be logged, just not sent with the response).  The fact that this happens for other error responses was a requested feature that, looking back, is a little odd-- although there are arguments to be made for either approach.

For future reference, there's a proposal in progress related to this here: https://github.com/balderdashy/sails/pull/3568

**Comment by mikermcneil** [comment]
This is now resolved in Sails v1!
