### ISSUE TITLE
Bad behavior of migrate alter

### ISSUE THREAD

**Issue by dangreen** [balderdashy/sails#3761]
**Sails version**: v0.12.3
**Node version**: v5.11.0
**NPM version**: 3.8.6
**Operating system**: OS X

<hr/>
I have `Passport` model with 
```js
beforeCreate(passport, next) {
     hashPassword(passport, next);
}
```
where 
```js
function hashPassword(passport, next) {

    if (passport.password) {

        if (!checkPassword.test(passport.password)) {

            var err = new Error("Invalid password"); 
            err.code = 'E_VALIDATION';

            return next(err, passport);
        }

        bcrypt.hash(passport.password, 10, (err, hash) => {
            passport.password = hash;
            next(err, passport);
        });
    } else {
        next(null, passport);
    }
}
```
Recently i updated sails to v0.12.3. After that sails recreates all records in db on lifting with `beforeCreate` (`migrate: 'alter'`), it means what all password will be hashed repeatedly (truly my regexp `checkPassword` will throw error).
OK. I make (dirty) check of password length (if length equals 60 then do not touch) -  sails stop lifting on `verbose: Starting ORM...`.

**Comment by dangreen** [comment]
Waterline `initialize` callback never called.

**Comment by dangreen** [comment]
okay. mistake in my code, also because of calling `beforeCreate` while alter migration.
```
beforeCreate(user, next) {
        generateUid().then((uid) => {
            user.uid = uid;
            next(null, user);   
        });
    }
```
where
```
function generateUid() {

    var uid = makeId(32);

    return new Promise((resolve) => {

        User.findOne({ uid })
        .then((user) => {

            if (user) {
                return generateUid().then(resolve);
            }

            resolve(uid);
        })
    });
}
```
while migration models is unavailable, `User` is `undefined`.

Why this changes in minor update?

**Comment by dangreen** [comment]
I resolve my issues by
```js
    beforeCreate(passport, next) {

        if (typeof passport.createdAt != "undefined") {
            return next(null, passport);
        }

        hashPassword(passport, next);
    }
```

But i still want to know, why this changes in minor update?

**Comment by particlebanana** [comment]
@dangreen looks like an unintended consequence of an update where backwards compatibility was trying to be maintained. I unpublished Waterline `0.11.3` from the registry and will make sure that it's fixed before publishing again.
