### ISSUE TITLE
'sails' is not defined in routes.js (routes internationalization i18n)

### ISSUE THREAD

**Issue by yannp** [balderdashy/sails#3773]
**Sails version**: 0.12.3
**Node version**: v6.2.2
**NPM version**: 3.9.5
**Operating system**: OSX

<hr/>
The documentation says "you can translate from anywhere in your application using sails.__". I wanted to localize my routes and tried to use 'sails' in routes.js, this results in the error "sails is not defined". I've found this page mentioning the issue: https://gist.github.com/mikermcneil/8513795.

If there's another way to localize routes I'd be glad to learn about it.

**Comment by mdabydeen** [comment]
A quick workaround is to require sails in your routes.js file. 

````
var sails = require('sails');

module.exports.routes = { 
....
}
```

**Comment by tbjers** [comment]
What @mdabydeen is a good way of doing this, also make sure you wait for the `i18n` hook to load by wrapping your route definitions in something like:

```
sails.after('hook:i18n:loaded', function (){});
```

**Comment by yannp** [comment]
@tbjers: You are right, if I apply @mdabydeen method, i18n isn't loaded yet so calling ```sails.__()``` produces an error. I've tried to apply the ```after('hook:i18n:loaded')``` solution but couldn't make it work. I'm very new to Node and a more detailed example of how to accomplish this would help. 

But it starts to look like a hack, maybe it would just be better to use hardcoded routes for multiple languages, before a proper solution for this is introduced to Sails.

**Comment by tbjers** [comment]
@yannp Maybe add a hook that listens for the `hook:i18n:loaded` event, then uses `sails.router.bind` to add the localized routes? You could for instance iterate `sails.config.router` to get what's already defined, then wrap needed ones in `__()` and [bind the new ones](https://github.com/balderdashy/sails/blob/master/lib/router/bind.js).

**Comment by sgress454** [comment]
The `sails` global isn't typically going to be available inside of config files, since they are loaded as part of the Sails initialization.  This isn't a bug, but the documentation should probably be updated to clarify what is meant by "anywhere in your application".

In this case, what I would probably do is `npm install i18n` in your project and then `require('i18n')` directly in the `config/routes.js` file.
