### ISSUE TITLE
HTTP 501 when calling res.render after io.socket.post request

### ISSUE THREAD

**Issue by Bludwarf** [balderdashy/sails#3798]
**Sails version**:0.12.1
**Node version**:0.12.2
**NPM version**:2.7.4
**Operating system**:Windows 7 64bits

<hr/>

Hi,

I use io.socket.post to create a new item in database. Everything is fine but when I want to return the created element using partial view (to update client view based on created element) Sails sends a HTTP 501.

I looked in the file lib/router/res.js and saw that may be some code is missing. What is annoying is that the same code works when I call the POST url directly (for instance with Postman) but doesn't when using sockets.

Am I doing something wrong ?

Code :

## Client JS
```javascript
var data = _.reduce($(form).serializeArray(), function(hash, value) {
  var key = value['name'];
  hash[key] = value['value'];
  return hash;
});

io.socket.post(url, data, function(data, jwres) {
  if (jwres.statusCode != 200) return alert('HTTP '+jwres.statusCode+' : '+jwres.error.message);
  $("#div").append(data);
});
```

## Controller
```javascript
ctrl = {
  action: function(req, res) {
    Model.create({
      //...
    }).exec(function(err, created) {
      res.partial('model/partial/view...', {
        created: created
      });
    });
  }
};
```

## api/response/partial.js
```javascript
module.exports = function partial (path, data) {

  // Get access to `req`, `res`, & `sails`
  var req = this.req;
  var res = this.res;
  var sails = req._sails;

  sails.log.silly('res.partial() :: Sending 200 ("OK") response');

  // Set status code
  res.status(200);

  data.layout = false; // render only partial src : http://stackoverflow.com/a/18065991/1655155
  console.log("responses/partial call");
  return res.render(path, data);

};
```

## sails/lib/router/res.js
```javascript
    // TODO:
    // Instead of this shim, turn `sails.renderView` into something like
    // `sails.hooks.views.render()`, and then call it.
    return res.send(501,'Not implemented in core yet');
```

**Comment by Josebaseba** [comment]
You can't send a view with the sockets protocol: http://sailsjs.org/documentation/reference/response-res check the list and you'll see all the methods that you can use with a socket request.

**Comment by Bludwarf** [comment]
Thanks for your answer Jose, documentation is clear.

To achieve what I want to do I am now using static HTML string :

```javascript
res.send('<li><a href="">...</a></li>');
```

Do you know a way to load a partial/view file without calling res.view (which forbidden) ? What is the correct way if we want to send HTML content from existing partial/view ? Why is there a "TODO" in res.js ?

**Comment by Josebaseba** [comment]
```javascript

// Email templates folder relative URL
EMAIL_TEMPLATES = 'emails/';

var compileTemplate = function (view, data, done){
  // view === 'parents/welcome.ejs'
  var relPath = path.join(EMAIL_TEMPLATES, view);
 // data === {email: 'some@email.com', name: 'test name'}
  if(typeof data.layout === 'undefined') data.layout = false; // You can send the view with a layout for the emails
  sails.hooks.views.render(relPath, data, done); // sails render method
};
```

I use that function to send my email templates, I've added some comments to make it more clear, it should work via sockets too :+1:

**Comment by mikermcneil** [comment]
Thanks @Josebaseba!
