### ISSUE TITLE
Sails.js body parser cuts posted request body to 512KB?

### ISSUE THREAD

**Issue by zoell** [balderdashy/sails#3841]
**Sails version**:0.12
**Node version**:4.4
**NPM version**:2.14.20
**Operating system**:Ubuntu 14.04

<hr/>

I am trying to post a JSON object to Sails with the following ajax call:
```
$.ajax({
    url: '/the/post/url',
    type: 'POST',
    data: JSON.stringify(postData),
    contentType: 'application/json',
    dataType: 'json',
    cache: false,
    success: function(data) {
      ...
    },
    error: function(jqXHR, textStatus, err){
      ...
    }
};
```
When I receive the data and try to save it to a file in my controller:
```
var requestParams = req.params.all();
fs.writeFile("/datadir/testdata.log", requestParams.data, function(err) { ... });
```

The data gets truncated and I only get a 512KB file with the json object cut in half or so. The end of the json in the file looks like this:

`{"segment":"14440","size":3,"name":"U`

I tried to configure Sails to use body-parser with increased limit in the http.js config file like:
bodyParser:  function () { return require('body-parser')({ limit: '50mb' }) },

But it is the same happening. Am I missing something?
Many thanks,
zoell

**Comment by wulfsolter** [comment]
client_max_body_size in nginx config?

https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by zoell** [comment]
I don't have nginx. It's just Sails.

**Comment by zoell** [comment]
One correction. I am actually using the following form to post the data:

```
<form method='POST' target='_blank' action='/posttest' id='the_form'>
        <input hidden='true' id="post_test_id" type='text' name='post_test_id' value="asdf"/>
        <input hidden='true' id="post_test_data" type='text' name='data' value=''/>
</form>

$("#post_test_data").val(JSON.stringify(test_data));
$("#post_test_id").val(test_id);
document.getElementById("the_form").submit();
```

The previously mentioned ajax query is from a different branch.

**Comment by zoell** [comment]
So if anyone is interested, here is the solution:

config/http.js:
```
    bodyParser: function () {
        var opts = {limit:'50mb'};
        var fn = require('skipper');
        return fn(opts);
    },

   middleware: {
     order: [
       'startRequestTimer',
       'cookieParser',
       'session',
       'myRequestLogger',
       'bodyParser',
       'handleBodyParserError',
       'compress',
       'methodOverride',
       'poweredBy',
       '$custom',
       'router',
       'www',
       'favicon',
       '404',
       '500'
    ],
   },
```
