### ISSUE TITLE
CRSF mismatch 403 triggers Acunetix CORS failure

### ISSUE THREAD

**Issue by shackbarth** [balderdashy/sails#3862]
**Sails version**: 0.12.6
**Node version**: 6.9.0
**NPM version**:  3.10.8
**Operating system**:  Heroku Cedar-14

<hr/>

An Acunetix web vulnerability scan of my sails app returned a high-importance alert about insecure CORS configuration, which I found bewildering because I don't have CORS turned on. But then I found this:

https://github.com/balderdashy/sails/blob/520fc149c38e32def3277dcacc68d8262d05c19f/lib/hooks/security/csrf/index.js#L102-L106

My workaround was to set
```
  res.set("Access-Control-Allow-Origin", "");
  res.set("Access-Control-Allow-Credentials", false);
```
in my 403/Forbidden handler.

Of course, I do think that Acunetix is being a bit precious in complaining about the Access-Control-Allow-Origin header on a 403, but the people I'm trying to impress are not necessarily technical enough to appreciate that nuance.

**Comment by mikermcneil** [comment]
@shackbarth thanks for the heads up.  This is the case where the request is rejected due to a CSRF token mismatch- and this is mainly useful during development.  I think we can go ahead and remove this using the patch you're suggesting (unless @sgress454 sees something I'm missing there.)

**Comment by sgress454** [comment]
Makes sense.  Patched on master in https://github.com/balderdashy/sails/commit/50b06845a0075f4a45f5e2b5d66c05ea3ed62c4b

**Comment by webstacker** [comment]
Is there any way to implement this without modifying core sails or upgrading to v1.x?
