### ISSUE TITLE
Model.find().select()

### ISSUE THREAD

**Issue by joeryy** [balderdashy/sails#3880]
**Sails version**:0.12.8
**Node version**:v6.9.1
**NPM version**:3.10.8
**Operating system**:Windows 10

<hr/>

Hello,

Why is Model.find().select() not working, as far as I understand select has been implemented in Waterline v0.12.0?

I am using it like this:
`Post.find().select(['title']).populate('author', { select: ['mail']}).exec(...`
gives
`TypeError: Post.find(...).select is not a function`

Am I missing something?

**Comment by karsasmus** [comment]
sails-hook-orm uses waterline v0.11.0 (https://github.com/balderdashy/sails-hook-orm/blob/master/package.json#L32)

**Comment by joery-d** [comment]
@karsasmus Okay, is there a way to upgrade this myself? Or are there any alternatives to `select`?

I can just manually replace `/node_modules/sails/node_modules/waterline` with a newer version, is it the only option?

**Comment by joeryy** [comment]
Ofcourse I also had to update sails-mysql, sorry.

**Comment by DavidVeloso** [comment]
@JoeryDroppers How did you do change version manually ?
