### ISSUE TITLE
Erratic unsigned cookie behaviour with disabled sessions

### ISSUE THREAD

**Issue by kunagpal** [balderdashy/sails#3896]
**Sails version**: `0.12.10`
**Node version**: `4.3.0`
**NPM version**: `2.14.12`
**Operating system**: `Mac OSX 10.11.13`

<hr/>

With `sessions` set to false in `.sailsrc`, and `'sessions'` excluded from the `order` array in `config/http.js`,  deleted cookies re-appear in the response of the immediate subsequent request. This happens only **once**, subsequent response(s) do not include that cookie.

Sample repository: https://github.com/kunagpal/sails-issue-3896

Steps:
1. Clone and download sample repository
2. Install all dependencies with `npm install`
3. Start the localhost with `node app.js`
4. View cookies on `http://localhost:1337/cookies`
5. Set cookie `foo=bar` on `http://localhost:1337/cookies/set?foo=bar`
6. Delete cookie `foo` on `http://localhost:1337/cookies/delete?foo`
7. The deleted cookie re-appears right after deletion, but is removed in subsequent requests.

Expected behaviour: Deleted cookies never re-appear in response data, unless explicitly reset later.

PS: Detailed analysis revealed a `referer` header with the value of the cookie deletion url was present in the response headers for redirection to the `/cookies` endpoint.

**Comment by mikermcneil** [comment]
@kunagpal Thanks for the clear explanation and particularly for the repro!  Looking into this ASAP.

**Comment by rachaelshaw** [comment]
@kunagpal Hmm, I wonder if this might have something to do with the fact that it's using a redirect?  http://stackoverflow.com/questions/4694089/sending-browser-cookies-during-a-302-redirect

**Comment by kunagpal** [comment]
@rachaelshaw Yes, that could be the root of the problem. :thinking:

**Comment by mikermcneil** [comment]
@kunagpal hmm, here's what I'm seeing: https://www.youtube.com/watch?v=r2FzpR_S9bo&feature=youtu.be

**Comment by mikermcneil** [comment]
that's in: 
![image](https://cloud.githubusercontent.com/assets/618009/20498185/bccb43f0-aff1-11e6-9a34-f9ce20c91a82.png)

**Comment by sgress454** [comment]
@kunagpal I'm afraid I tried as well and had the same result as @mikermcneil.  I couldn't reproduce the issue.

**Comment by mikermcneil** [comment]
@kunagpal Any luck reproducing this?

**Comment by kunagpal** [comment]
@mikermcneil Not particularly, I was able to arrive at the described behavior with the sample repository.
