### ISSUE TITLE
Attribute Methods Search

### ISSUE THREAD

**Issue by AmirTugi** [balderdashy/sails#3897]
**Sails version**: 0.12
**Node version**: 6.9.1
**NPM version**: 4.0.2
**Operating system**: Win 10 64-bit

<hr/>
I'm having a problem with filtering a search by attribute methods.
I have no issue filtering by an existing column, but the attribute method returns this:
from this url: 

```
http://localhost:1337/items?where={"isBelowMin":true}
```

```
 [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: ER_BAD_FIELD_ERROR: Unknown column 'items.isBelowMin' in 'where clause'
```

This is the model:
```
module.exports = {

    attributes: {
        partNumber: {
            type: 'string',
            required: true
        },
        manufacturer: {
            type: 'string',
            defaultsTo: ''
        },
        description: {
            type: 'string',
            defaultsTo: ''
        },
        quantity: {
            type: 'integer',
            defaultsTo: 0
        },
        location: {
            type: 'string',
            defaultsTo: ''
        },
        classification: {
            model: 'classifications'
        },
        minimumQuantity: {
            type: 'integer',
            defaultsTo: 0
        },
        pictures: {
            collection: 'pictures',
            via: 'item'
        },
        isActive: {
            type: 'boolean',
            defaultsTo: true
        },

        isBelowMin: function() {
            return this.minimumQuantity > this.quantity;
        },

        hasPictures: function() {
            return this.pictures.length > 0;
        },

        // Override the default toJSON method
        toJSON: function() {
            var obj = this.toObject();
            obj.hasPictures = this.hasPictures();
            obj.isBelowMin = this.isBelowMin();
            return obj;
        }
    }
};
```

So isBelowMin is an attribute method and makes all the fuss, and isActive returns correctly.
But the problem is more general, and not necessarily boolean focused. Even strings will return `

Is this a lack of support for attribute features, as I fear it is? Or just a bug?

P.S - The api is generated by SailsJS.

**Comment by particlebanana** [comment]
Searching by attribute methods isn't supported unfortunately. If you think about how that would work it would need to run that function on every record in the database in order to determine which records to return.

I'm not sure how to write that query without dipping down to use some sort of native subquery which would also require a controller method and the use of a SQL adapter.

**Comment by AmirTugi** [comment]
Eventually, if I need the records filtered, I will do it either in the back-end or the front-end.
I tend to think it should be on the back-end to remove computing processes from the client.
As I see it, you should only run `<array>.filter(<condition>)` after you retrieve the records (unless you see a way to translate the method into an SQL query).
Do you think that filter should be applied in the front or back?
I really want to hear your opinion.
