### ISSUE TITLE
mistyped variable names in errors/warn.js

### ISSUE THREAD

**Issue by appdevdesigns** [balderdashy/sails#3901]
**Sails version**:0.12.10
**Node version**:6.6.0
**NPM version**:3.10.3
**Operating system**: Mac OS X

<hr/>

I recently attempted to upgrade sails on my local system and then encountered errors in your .badLocalDependency() method.

The errors are due to mistyped variable names.

**Comment by mikermcneil** [comment]
@appdevdesigns @Hiro-Nakamura thanks!

**Comment by mikermcneil** [comment]
@appdevdesigns would you try out `npm install sails@0.12.11-1` and verify that this is fixed for you?  All ready to publish that as soon as I get a second opinion from someone whose computer isn't `npm link`-ed every which way :)

**Comment by irlnathan** [comment]
@mikermcneil Just tested `sails@0.12.11-1 with Brushfire and it's good to go!

**Comment by mikermcneil** [comment]
@appdevdesigns @Hiro-Nakamura Alright!  Just published as latest ([0.12.11](https://github.com/balderdashy/sails/releases/tag/v0.12.11)).
