### ISSUE TITLE
xD/A joins: Populating two associations with different connections in combination with an "or" query does not work

### ISSUE THREAD

**Issue by simonmilz** [balderdashy/sails#3934]
**Sails version**: 0.12.3
**Node version**: 6.9.1
**NPM version**: 3.10.8
**Operating system**: Windows 7

<hr/>

```js
Travels.find({
  client: '57bb00b4f36d283b6d8bc133',
  or: [
    {
	title: {
	   like: '%Mein%'
	}
    }
]}).populate('countries').populate('client').exec(function (err, records) {
   console.log(records)
});
```
So i want to get all Travels with title like "Mein" for a specific Client, but records is an empty array. If i do the same query as count i get the number of matching records:

```js
Travels.count({
  client: '57bb00b4f36d283b6d8bc133',
  or: [
    {
	title: {
	   like: '%Mein%'
	}
    }
]}).exec(function (err, count) {
   console.log(count) // count is 1
});
```

If i remove the "or" from the query and search for the exact title everything works fine:

```js
Travels.find({
  client: '57bb00b4f36d283b6d8bc133',
  title: 'Meine erste Reise'
}).populate('countries').populate('client').exec(function (err, records) {
  console.log(records) // i get my expected records
});
```

```js
// Countries.js
module.exports = {

  autoPK: false,
  connection: 'staticdata',

  attributes: {
    label: {
      type: 'string'
    },

    code: {
      type: 'string',
      unique: true,
      primaryKey: true
    }
  }

};
```

Can anybody confirm this behaviour?

**Comment by simonmilz** [comment]
Okay, so i figured out that when i'm moving the countries collection to the same database everything works fine.

**Comment by mikermcneil** [comment]
@simonmilz thanks for the report nonetheless!  We'll look into it.  It's possible there's something going on specifically with the polyfill for xD/A populates.

Going to go ahead and track this as a bug so that we remember to try this out with Waterline 0.13/Sails v1.0 as well.

**Comment by simonmilz** [comment]
Can i help with this bug somehow?

**Comment by mikermcneil** [comment]
@simonmilz So far, we haven't had any luck reproducing this, so it sounds like it's a specific mix of things that we haven't figured out yet.  What adapters are you using?  (And what versions?)  Also, would you paste the relevant model definitions?

Thanks!

**Comment by mikermcneil** [comment]
@simonmilz OK!  After further review, @sgress454 and @particlebanana were able to reproduce this in v0.12.11, and it's been fixed in the 0.12.12-1 prerelease.  To try that out, run `npm install sails@0.12-pre` in your app.

As soon as @irlnathan finishes one more pass through the release, we'll publish that as a patch.  But in the mean time, would you let me know if you notice any related problems w/ polypulates on the new release?  Thanks!

**Comment by simonmilz** [comment]
@mikermcneil , @sgress454 , @particlebanana , @irlnathan  I just update to `0.12-pre`  and it works perfectly fine! thanks for this fix! Awesome support :+1:

**Comment by sgress454** [comment]
wins for everybody!
