### ISSUE TITLE
Updating a model using `through` results in 400 error if collection attribute is updated

### ISSUE THREAD

**Issue by AskYous** [balderdashy/sails#3946]
**Sails version**: 0.12.1
**Node version**: 6.9.2
**NPM version**: 3.10.9
**Operating system**: Windows 10

<hr/>

It seems that when two models are related via a many-to-many relationship using the [`through`](http://sailsjs.com/documentation/concepts/models-and-orm/associations/through-associations) attribute property, and one of the models is updated via HTTP PUT, having the attribute using the `through` updated as well, sails throws a 400 error.

I've created a repository that reproduces this error. Please read the [README.md](https://github.com/AskYous/sails-through-error/blob/master/README.md) file there. This is my repository that reproduces this error:

https://github.com/AskYous/sails-through-error/

**Comment by sgress454** [comment]
Hi @AskYous, thanks for posting.  This has been [patched in Waterline 0.11.8](https://github.com/balderdashy/waterline/pull/1435).  If you re-install Sails (either globally or for your local project) it should pick up the new Waterline version.

**Comment by AskYous** [comment]
Hello @sgress454, I uninstalled SailsJS globally and locally, but I still experienced the same error. The error on the repository I linked above still gets thrown. Can you please check? My sails version is `0.12.11`.

**Comment by AskYous** [comment]
@sgress454 I don't know why but it works now (but wasn't before). Thanks for the update!
