### ISSUE TITLE
Sails breaks installation during an npm install.

### ISSUE THREAD

**Issue by JoshSpears3** [balderdashy/sails#3953]
**Sails version**: ^0.12.7
**Node version**:  0.12.13
**NPM version**: 2.15.0
**Operating system**: Amazon Linux

<hr/>

During `npm install -g sails@0.12.7`, Sails crashes the installation. 

##### Error:
```
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'sailshq/lodash' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'anchor'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

**Comment by karsasmus** [comment]
https://github.com/balderdashy/sails/issues/3938#issuecomment-269117539

**Comment by JoshSpears3** [comment]
Thanks @karsasmus, Sorry for the duplicate.
