### ISSUE TITLE
New records from create are undefined (v1)

### ISSUE THREAD

**Issue by nehalist** [balderdashy/sails#3971]
**Sails version**: v1.0.0-20
**Node version**: v6.3.0
**NPM version**: v3.10.8
**Operating system**: Win10

<hr/>

Minimal model:

```
module.exports = {
  attributes: {
    value: {
      type: 'string'
    }
  }
};
```

Creating new model within a controller (or wherever else, also tried in service):

```
Bar.create({
      value: 'foobar',
    }).exec(function(err, records) {
      if(err) {
        sails.log.error(err);
      }

      sails.log.debug(records);
    });

    return res.ok();
  }
```

Log:

```
debug: undefined
```

Just in case:

- `sails-hook-orm` is at `2.0.0-7`
- Waterline is at `0.13.0-3`

**Comment by julio641742** [comment]
You should read the upgrading to v1 doc
[Answer to your question link](https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md#changes-to-create-createeach-update-and-destroy-results)

**Comment by nehalist** [comment]
Checked the docs, forgot the upgrade guide. Whoops.

Thanks.
