### ISSUE TITLE
Old many-to-many associations with "through" are not cleaned up after .update()  (i.e. after replacing collection)

### ISSUE THREAD

**Issue by simonmilz** [balderdashy/sails#3977]
**Sails version**: 0.12.12-1
**Node version**: v6.9.1
**NPM version**: 3.10.8
**Operating system**: Win7 Professional

<hr/>
The models are `api/models/Travels.js`, `api/models/Images.js` and `api/models/Images_to_Records.js`. Here is the simplified content:

Travels.js:
```js
module.exports = {

	attributes: {
		type: {
			type: 'string',
			enum: ['INDEPENDENT', 'GROUP']
		},

		code: {
			type: 'string'
		},
		images: {
			collection: 'images',
			through: 'images_to_records'
		}
	}
}
```

Images.js:
```js
module.exports = {

  attributes: {
		file: {
			model: 'Files'
		},

		title: {
			type: 'string'
		},

		position: {
			type: 'integer'
		}
  }
};
```

Images_to_Records.js:
```js
module.exports = {

	attributes: {
		travels: {
			model: 'travels'
		},

		images: {
			model: 'images'
		}
	}
};
```

So, when I run the following statement:
```js
		// First, we add the first image
		Travels.update({
			code: 'DE-16-001'
		}, {
			images: ['589b25db442382144083d612']
		}).exec(function () {
			// Then we add an additional image and keep the first image
			Travels.update({
				code: 'DE-16-001'
			}, {
				images: ['589b25db442382144083d612', '589b25f4442382144083d61a']
			}).exec(function () {});
		});
```

I expect two documents in my `images_to_records` collection. But there are three. For the first relation I set, the `travels` attribute is simply set to `null`:

![image](https://cloud.githubusercontent.com/assets/5016123/22741093/4d012f9e-ee12-11e6-8ba2-4328c412c91a.png)

I expect that this record will be deleted when I reassign associations, otherwise my database will get very huge ;)

**Comment by mikermcneil** [comment]
@simonmilz Thanks for bringing this up!  I'll take a closer look asap at the behavior here specifically for `through` associations. (cc @particlebanana)

**Comment by jcharrell** [comment]
Just implemented `through` relationships on a project and ran into the same issue.  Would this be related to sails, waterline or the data adapter?  In my case, I am utilizing the `sails-postgres` adapter

**Comment by particlebanana** [comment]
Hey @simonmilz and @jcharrell we redid this logic in Sails V1 and it lives completely at the Waterline level now. I just confirmed it's fixed using the following model definitions. We are working hard to get Sails V1 and Waterline 0.13 out the door so I don't have spare time right now to dig into Sails `0.12` and try and find the logic responsible for this but can come back to it when time allows. If anyone wants to do a hotfix for [Waterline `0.11`](https://github.com/balderdashy/waterline/tree/0.11.x) I would happily merge it! 

```javascript
// Images Model
module.exports = {
  attributes: {
    title: {
      type: 'string'
    },
    position: {
      type: 'number'
    },
    travels: {
      collection: 'travels',
      via: 'images',
      through: 'images_to_records'
    }
}
```

```javascript
// Travels Model
module.exports = {
  attributes: {
    type: {
      type: 'string'
    },
    code: {
      type: 'string'
    },
    images: {
      collection: 'images',
      via: 'travels',
      through: 'images_to_records'
    }
}
```

```javascript
// Images_To_Records Model
module.exports = {
  attributes: {
    travels: {
      model: 'travels'
    },
    images: {
      model: 'images'
    }
}
```

**Comment by jcharrell** [comment]
@particlebanana I will tackle this issue.  Should I create a new issue on the Waterline repo or can I submit a PR to the Waterline repo and reference it here within this issue?

**Comment by jcharrell** [comment]
I have a [fix](https://github.com/jcharrell/waterline/commit/08992ca7dc698f2618aea83373b510e028cfd0ca) in place, but I couldn't figure out how to verify the solution in a unit test, which is required by the contribution guides.  If someone else would like to fork this and submit a PR with a test, I'd really appreciate it.

**Comment by simonmilz** [comment]
@jcharrell nice :+1:

**Comment by jcharrell** [comment]
@particlebanana Any suggestions for getting this into the Waterline 0.11 branch?

**Comment by raqem** [comment]
@simonmilz @jcharrell Hi ya'll we are currently cleaning Sails issues by closing older issues. This on appears to have been resolved with the publish of Sails V1.
