### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory while installing module sails

### ISSUE THREAD

**Issue by ndabAP** [balderdashy/sails#3994]
**Sails version**: ~0.12.11
**Node version**: 7.5.0
**NPM version**: 4.1.2
**Operating system**: Ubuntu 16.04

<hr/>

After a fresh install of Ubuntu and sails.js this error came up after 

`npm install`

> npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/backend/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/jsonlint-lines/node_modules/nomnom/node_modules/chalk/node_modules/strip-ansi/cli.js'

**Comment by Josebaseba** [comment]
try it using sudo: `sudo npm install`

**Comment by ndabAP** [comment]
Thank you,  @Josebaseba. What I tried:

- Cleared cache
- deleted node_modules
- executed with sudo.

But it didn't work.

**Comment by sgress454** [comment]
@ndabAP Using a somewhat older version of Ubuntu (14.04) I was unable to reproduce the issue.  Not to beat it over the head, but can you try:

```
rm -rf node_modules
npm cache clean
npm install sails
```

one more time?

**Comment by lifespent** [comment]
Environment: 
Ubuntu Server 16.04
Nodejs v. 6.10.0
sails v. 0.12.11

I'm having a similar issue: https://gist.github.com/lifespent/683652e1cf146c73dbe59caf64eacbf

In my project I don't have '/node_modules/anchor/'. I've removed the node_modules and cleaned the cache and tried to reinstall. Any ideas?

**Comment by mikermcneil** [comment]
@lifespent not offhand-- maybe try installing anchor by itself?  That could help get to the bottom of what's going on

**Comment by lifespent** [comment]
@mikermcneil Thanks for the follow up. I was able to fix it today. I'm running my dev environment in Virtualbox and my shared folder didn't support symbolic links out of the box. I enabled symbolic links for my virtual machine and then I removed sails -g and re-installed and it works! Thanks for the awesome code, man. It's exactly what I was looking for coming from a Ruby on Rails background.

**Comment by ndabAP** [comment]
@sgress454, I tried your steps but it didn't work. Like @lifespent, I run Sails.js inside a VirtualBox. I also enabled symbolic links but for me it didn't help.

**Comment by lifespent** [comment]
Did you run 'npm uninstall sails -g' and then 'npm install sails -g'? What command did you use to enable sym links? Did you restart virtualbox after you ran the command?

**Comment by lifespent** [comment]
Here are the steps I took to make it work:
1.   VBoxManage setextradata VM_NAME VBoxInternal2/SharedFoldersEnableSymlinksCreate/SHARE_NAME 1
(Where VMNAME is the name of your virtual machine (e.g Ubuntu) and SHARENAME the name of your shared directory (without the "sf_" prefix) 

2. Restart VirtualBox
3. After you're back inside the VM run: 'npm uninstall sails -g' and then 'npm install sails -g'

**Comment by lifespent** [comment]
Update: If I run 'sails new app' everything installs fine. If I go into 'sails new app' and run 'npm install' it runs fine. If I wipe out the 'node_modules' directory and run 'npm install' I get the same errors:

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/backend/node_modules/sails/node_modules/anchor/node_modules/geojsonhint/node_modules/jsonlint-lines/node_modules/nomnom/node_modules/chalk/node_modules/strip-ansi/cli.js'

**Comment by lifespent** [comment]
@ndabAP: I was able to fork the project and add the dependency back. You can use it to if you like. Inside of the sails application go to the 'package.json' and replace:
`"sails": "~0.12.13",` 
with:
`"sails": "github:lifespent/sails#hastings-fix",`

**Comment by lifespent** [comment]
@ndabAP: I was able to fork the project and add the dependency back. You can use it to if you like. Inside of the sails application go to the 'package.json' and replace:
`"sails": "~0.12.13",` 
with:
`"sails": "github:lifespent/sails#hastings-fix",`

And then run:
`rm -rf node_modules`
`npm clean cache`
`npm install`

**Comment by lifespent** [comment]
@ndabAP: I was able to fork the project and add the dependency back. You can use it too if you'd like... 

Inside of the sails application go to the 'package.json' and replace:
"sails": "~0.12.13",
with:
"sails": "github:lifespent/sails#hastings-fix",

And then run:
rm -rf node_modules
npm clean cache
npm install

**Comment by lifespent** [comment]
@ndabAP: I was able to fork the project and add the dependency back. You can use it too if you'd like...

Inside of the sails application go to the 'package.json' and replace:
`"sails": "~0.12.13",`
with:
`"sails": "github:lifespent/sails#hastings-fix",`

And then run:
`rm -rf node_modules`
`npm clean cache`
`npm install`

**Comment by ndabAP** [comment]
Works perfectly! Just changed clearing cache to:

`npm cache clear`

**Comment by alexz18** [comment]
Change my package.json to version 1.6.14 helps to me for the "sequelize-cli" issue:
...
  "dependencies": {
...
    "request": "^2.81.0",
    "js-beautify": "1.6.14",
    "sequelize": "^4.8.2",
...

**Comment by cloudinary-misha** [comment]
Hi guys,
I solved this issue by installing NVM and using NPM@2.14.2 that comes with Node@4.0.0
The problem probably caused by the newer version of NPM (>3.0.0) in which node_modules symlinks were deprecated.

**Comment by moryachok** [comment]
Hi guys,
I solved this issue by installing NVM and using NPM@2.14.2 that comes with Node@4.0.0
The problem probably caused by the newer version of NPM (>3.0.0) in which node_modules symlinks were deprecated.

**Comment by liuzhen2008** [comment]
@moryachok This doesn't seem to be a good way to "fix"?

@tghastings Is the fix still available somewhere?

**Comment by tghastings** [comment]
@liuzhen2008, try this:

Inside of the sails application go to the 'package.json' and replace:
"sails": "~0.12.13",
with:
"sails": "github:lifespent/sails#hastings-fix",

And then run:
rm -rf node_modules
npm cache clear
npm install
