### ISSUE TITLE
Cannot define helper from example.

### ISSUE THREAD

**Issue by mrded** [balderdashy/sails#3997]
**Sails version**: 1.0.0-25
**Node version**: 7.5.0
**NPM version**: 4.1.2
**Operating system**: macOS 10.12.3 (16D32)

<hr/>

I'm trying to create a helper exactly from [example](http://next.sailsjs.com/documentation/concepts/helpers) :

    // api/helpers/say-hello.js
    module.exports = {

      friendlyName: 'Say hello',

      description: 'A utility that accepts a name and creates a greeting.',

      sync: true, // See the `Synchronous helpers` documentation later in this document

      inputs: {

        name: {
          type: 'string',
          description: 'The name of the person to greet.',
          required: true
        }

      },

      fn: function (inputs, exits) {

        var greeting = 'Hello, ' + inputs.name + '!';
        return exits.success(greeting);

      }
    };

When I try to call it: `sails.helpers.sayHello({ name: 'Bubba'}).exec(console.log);`

It crashes with an error:

    Error: Failed to instantiate machine "Say hello" from the specified machine definition.
    The following `input` properties are not valid:
    • name

**Comment by sgress454** [comment]
Hi @mrded, this should be fixed in the latest release, which you can install with `npm install sails@beta`.  Would you mind checking it out?  Thanks!
