### ISSUE TITLE
Cannot bind route to controller named with "/.*Controller.*/"

### ISSUE THREAD

**Issue by MelwinKfr** [balderdashy/sails#4042]
**Sails version**: 0.12.13
**Node version**: 7.7.1
**NPM version**: 4.1.2
**Operating system**: alpine:3.4

<hr/>

I generated a new API using command `sails generate api microController`, it has created model and controller files as expected and RESTful blueprints are working perfectly.

But when I want to add a new custom route:
`'/microcontroller/:id/check': 'MicroControllerController.check'`

I have the following error message in my console:
`error: Ignored attempt to bind route (/microcontroller/:id/check) to unknown controller :: micro.`

**Comment by MelwinKfr** [comment]
It happens because the `controllerId` is normalized two times using `sailsUtil.normalizeControllerId()`. Once before the call to `bindController()` 
[here](https://github.com/balderdashy/sails/blob/0.12/lib/hooks/controllers/to-interpret-route-syntax.js#L92) and a second time inside the function [here](https://github.com/balderdashy/sails/blob/0.12/lib/hooks/controllers/to-interpret-route-syntax.js#L129).

I added a debug console log into `sailsUtil.normalizeControllerId()` which produce the output:
```
debug: normalize controller id: MicroControllerController
debug: normalize controller id: microcontroller
```

I would enjoy to PR something but I don't understand why two calls to `sailsUtil.normalizeControllerId()` are needed.

**Comment by sgress454** [comment]
Hi @MelwinKfr yeah, this has to do with the fact that controller names are required to have `Controller` at the end, but that string is stripped off when determining the controller `identity` to be used internally.  I'd have to look into if/why the two calls are needed, but in any case this is unlikely to be fixed in the 0.12.x branch, so in the meantime you should be able to work around this by using an alternate route syntax:

```
'/microcontroller/:id/check': {controller: 'MicroControllerController', action: 'check'}
```

**Comment by hellsinglord22** [comment]
Another reason for this problem that you may have written the name of the `Controller` wrong in the `routes.js` file ...

**Comment by tellkeygit** [comment]
In an attempt to help students learn cs, we are looking for issues that they can potentially work on.Help us by mentioning our bot "@tellkeygit {#hours}" (to solve the issue). This would help students pick up issues based on their experience. Please take a look at https://www.keygit.info for more details.

**Comment by sgress454** [comment]
🎉 Closing now that v1.0 is officially released.
