### ISSUE TITLE
columnType not working with date type

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#4068]
@Josebaseba commented on [Wed Mar 01 2017](https://github.com/balderdashy/sails-mongo/issues/458)

sails: v1.0.0-27
sails-mongo: 1.0.0-4

In my models.js:

```javascript

attributes: {
    createdAt: { type: 'string', columnType: 'date', autoCreatedAt: true },
    updatedAt: { type: 'string', columnType: 'date', autoUpdatedAt: true },
    id: { type: 'string', columnName: '_id' }
  }

```

The createdAt and updatedAt, of each document, are strings instead of dates.

---

@sailsbot commented on [Wed Mar 01 2017](https://github.com/balderdashy/sails-mongo/issues/458#issuecomment-283455557)

@Josebaseba Thanks for posting, we'll take a look as soon as possible.  In the meantime, if you haven’t already, please carefully read the [issue contribution guidelines](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#ii-issue-contributions) and double-check for any missing information above.  In particular, please ensure that this issue is about a stability or performance bug with a  documented feature; and make sure you’ve included detailed instructions on how to reproduce the bug from a clean install.   Finally, don’t forget to include the version of Node.js you tested with, as well as your version of Sails or Waterline, and of any relevant standalone adapters/generators/hooks.

Thank you!

---

@sgress454 commented on [Wed Mar 01 2017](https://github.com/balderdashy/sails-mongo/issues/458#issuecomment-283497777)

Hi @Josebaseba, `columnType` doesn't really have any meaning for Mongo, since Mongo fields can always accept any type.  If you set the `type` of the `createdAt` or `updatedAt` to `number`, it'll store the dates as JS timestamps, and then you can transform them to dates yourself.  If you leave it as `string`, it'll act just as it did in Sails v0.12, which is to save an ISO-formatted date string.

**Comment by Clan-Utility** [comment]
sails: v1.0.0-45
sails-mongo: 1.0.0-11

createdAt: { type: 'string', columnType: 'date' } saves date in Mongo as string: "2015-10-01T14:30:38.145Z"

However, in sails v12, createdAt: { type: 'datetime' } saves date as ISODate("2015-10-01T14:30:38.145Z")

Viewed by Robomongo

**Comment by nicolapalavecino** [comment]
You can follow these instructions for having the mongo adapter and to call native mongo shell methods. In my case I made:

```
var db = <model>.getDatastore().manager;

var values = await db.collection(<collection>).find({createdAt:{$gt:<Date value>,$lt:<Date value>}}).toArray();
```
