### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [balderdashy/sails#4277]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, so it may be a good idea to use it instead of EJS 😀

**Comment by davidreghay** [comment]
@Drulac at the minimum you would need to get this supported by https://github.com/tj/consolidate.js

The would be enough to allow users of Sails to adopt your templating engine in their projects.

**Comment by sgress454** [comment]
@Drulac thanks for the suggestion.  At the moment we don't have any plans to move from EJS as our default, but in Sails 1.0 you can easily use any template language you want, even if it isn't supported by Consolidate (although Consolidate support makes it even easier).  See the [view engine docs](https://next.sailsjs.com/documentation/concepts/views/view-engines) for more details.
