### ISSUE TITLE
How can I load sails into my protractor tests

### ISSUE THREAD

**Issue by danil-z** [balderdashy/sails#4357]
======================================================
### BEGIN VERSION INFO ###
-->

**Sails version**:1.0.1
**Node version**:9.10.1
**NPM version**:5.6.0
**DB adapter name**: N/A
**DB adapter version**: N/A
**Operating system**:OS X

<hr/>

How can I load sails into my protractor tests?
I have setup Sails & Angular.io + Protractor & protractor-cucumber-framework

my package.json contains these scripts:
````
  "scripts": {
    "webdriver": "webdriver-manager update && webdriver-manager start",
    "start": "npm-run-all --parallel open:client dev",
    "start:debug": "npm-run-all --parallel debug client",
    "client": "ng serve",
    "client:test": "ng serve --env=test --port 4201",
    "open:client": "ng serve --open",
    "build": "npm run build:prod",
    "build:dev": "ng build --deploy-url=dist",
    "build:prod": "ng build --prod --deploy-url=dist",
    "build:aot": "ng build --aot --deploy-url=dist",
    "clean": "rimraf .tmp/public/dist",
    "prod": "node app.js --prod",
    "dev": "sails lift --dev",
    "debug": "node --inspect=9229 app.js",
    "sails:test": "NODE_ENV=test node app.js",
    "postinstall": "npm run build",
    "test": "NODE_ENV=test npm-run-all --parallel -r webdriver sails:test client:test protractor",
    "protractor": "sleep 10 && protractor protractor.conf.js"
  },
````

so when I run:  **npm run test** , sails instance is already running for me to serve client requests.
now I want to populate Database from test steps something like this:

````
// features/steps/sails.steps.ts
var sails = require('sails');

const {Given, When, Then, Before}  = require('cucumber');

Given('following users exist', function (dataTable) {
    console.log('sails step here!!!');
    // I need execute  here something like **await User.create(dataTable.rows())**
    return 'pending';
});
````

How to get access to all models on backend from protractor process?

**Comment by johnabrams7** [comment]
@danil-z Protractor is geared towards running in Angular and AngularJS applications however, setting `browser.ignoreSynchronization = true;` in the `protractor-config.js` allows Protractor to run in non-Angular frameworks.  [Here's a great article](https://medium.com/@marcelmokos/end-to-end-testing-with-protractor-using-modern-javascript-syntax-44e5121c2e03) that explains various ways to test Protractor with non-Angular frameworks such as Sails.JS with Node.JS LTE (ES6 javascript syntax). Hope this helps!

**Comment by johnabrams7** [comment]
@danil-z I wanted to add that, while Protractor is geared towards testing your Angular front-end code, Sails has [Mocha](https://sailsjs.com/documentation/concepts/testing) to test your Sails backend code.
