### ISSUE TITLE
Model are not loaded when sails launches - upgrade from 0.12.11 to 1.0.2

### ISSUE THREAD

**Issue by liuzhen2008** [balderdashy/sails#4518]
**Sails version**: 1.0.2
**Node version**: v8.9.3
**NPM version**: v5.5.1
**DB adapter name**: sails-mongo
**DB adapter version**:  1.0.1
**Operating system**: Ubuntu 14

<hr/>

So I just upgrade my sailsjs from 0.12.11 to 1.0.2, and now I am experiencing some difficulty restoring the bahavior of my server.

This is how my globals.js look like.
```
module.exports.globals = {

	_: require("lodash"),

	async: require("async"),

	sails: true,

	services: true,

  models: true
};

```

And in one of my api/models/User.js, I have the code below (I removed a lot of uncessary stuff)
```
module.exports = {
  attributes: {
    app: { 
      type: 'string'
    },
    last_active: 'date',
    facebook_id: {
      type: 'string',
      unique: true
    },
    twitter: {
      type: 'string',
      unique: true
    },
    instagram_id:{
      type: 'string',
      unique: true,
      index: true
    },
    linkedin_id: {
      type: 'string',
      unique: true,
      index: true
    }
};
```

In my Controller code, I tried to do User.find(); before in 0.12.11 sails, it would work... but now, it i am getting the error `ReferenceError: User is not defined`

**I tried to do a bunch of console.log("aewfawfafe") in my User.js model, i notice that when I start lift, none of the console log is being displayed. On the other hand, files in api/services/ are loaded correctly**

When I `console.log(sails)` in my code in one of the controllers. (I trigger this code by making a call to that controller), i get those results

```
0 Models:


0 Controllers:


14 Hooks:
moduleloader,logger,request,blueprints,responses,helpers,policies,services,security,i18n,userconfig,session,http,userhooks

```

What should I do to further debug this issue? I must be missing some thing trivial!

**Comment by rachaelshaw** [comment]
@liuzhen2008 I definitely agree with @dbeast86's advice about enabling more detailed logs and carefully going through the upgrade guide -- if you used the automated upgrade tool, it's entirely possible there are some remaining manual migration tasks that it didn't catch.

One other thing I noticed in your model definition that'll need to change (which there should have been an error message about upon lifting your app) is that `last_active: 'date'` is no longer supported -- instead, you can use e.g. `{ type: 'string', columnType: 'date' }` (or whatever `columnType` is supported by your adapter)

**Comment by liuzhen2008** [comment]
Awesome. I briefly looked at the upgrade document and notice that i didn't modify everything according to the doc. 

I will do that soon ish and will open ticket if it still doens't work.
