### ISSUE TITLE
sails.sockets.rooms() does not exist

### ISSUE THREAD

**Issue by Ramakant701** [balderdashy/sails#4522]
**Sails version**:
**Node version**:
**NPM version**:
**DB adapter name**: N/A
**DB adapter version**: N/A
**Operating system**:

<hr/>

**Comment by streleck** [comment]
Hi @Ramakant701 I would be interested in looking into this. Can you please tell me about the project and what you are trying to do? What version of Sails are you using?

**Comment by Ramakant701** [comment]
Actually I have been trying to get rooms which are connected in a socket
with sails, usually in socket we can do this like
io.sockets.adapter.rooms(roomName) or something like that but I am not able
to find similar method with SAILS

**Comment by mikermcneil** [comment]
@streleck @Ramakant701 https://sailsjs.com/documentation/upgrading/to-v-0-12#?socket-methods

**Comment by streleck** [comment]
It looks like the .rooms() method was deprecated in v0.12 and removed in v1.0, because in socket.io it doesn't scale to use on more than one server.

**Comment by Ramakant701** [comment]
So what can be done in order to get the sockets connected to a single room
with sails. Please help

**Comment by streleck** [comment]
@Ramakant701 You can you sails.sockets.join(req, 'roomName') to determine what room a socket gets connected to.

**Comment by Ashkan4472** [comment]
@Ramakant701 in sails >= 1.0 you can use this to get rooms
sails.io.sockets.adapter.rooms

**Comment by Ramakant701** [comment]
Hello there,

I just signed the petition "Indian Cosplay Community: Price hike in Comic
Con India in 2019" and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/TRSKBMVr2y

Thanks!
Ramakant
