### ISSUE TITLE
sails websocket client

### ISSUE THREAD

**Issue by jeremy-simeon** [balderdashy/sails#4532]
**Sails version**: v1.0.2
**Node version**: v10.9.0
**NPM version**: 6.4.1
**DB adapter name**: N/A
**DB adapter version**: N/A
**Operating system**: ubuntu 16.04

Hello, 

In my sails project, I want to connect to another sails project in websocket but this server is behind a proxy. how can I set the proxy in sailsIOClient ? 

Below, my code :

```
const socketIOClient = require('socket.io-client')
const sailsIOClient = require('sails.io.js')
const io = sailsIOClient(socketIOClient)

// URL
io.sails.url = 'http://my-server.org'

// Event
io.socket.on('connect', () => {
   console.log('connect')
})
```

<hr/>

**Comment by johnabrams7** [comment]
@jeremy-simeon  Try using [req.ip](https://sailsjs.com/documentation/reference/request-req/req-ip) for either the **remote IP address of the requesting user agent**, OR if [sails.config.http.trustProxy](https://sailsjs.com/documentation/reference/configuration/sails-config-http) is enabled, consider this the [upstream address](https://en.wikipedia.org/wiki/X-Forwarded-For) instead.  Hope this helps!
