### ISSUE TITLE
`registerConnection` method must be renamed to `registerDatastore` for mssqlserver adapter

### ISSUE THREAD

**Issue by vsashidh** [balderdashy/sails#4625]
**Waterline version**: 0.13.4
**Node version**: v8.10.0
**NPM version**: 5.10.0
**Operating system**: Darwin

<hr/>

When using the latest version of sails-mssqlserver adapter with the latest version of waterline encountering the following error:

> The adapter for datastore `default` is invalid: the `registerConnection` method must be renamed to `registerDatastore`.

I ran into a similar post, but does not appear to apply to the adapter combination I'm using when encountering this issue:

> https://github.com/balderdashy/sails/issues/4051

Here is the code for the config I'm currently using to initialize the waterline instance:

```
import * as sailsMsSqlAdapter from 'sails-mssqlserver';

const config = {
  adapters: {
    mssql: sailsMsSqlAdapter,
  },

  datastores: {
    default: {
      adapter: 'mssql',
      user: 'some_user',
      password: 'some_pwd',
      host: 'some_host', 
      database: 'some_database',
      options: {
        encrypt: true, // use this for Azure databases
      },
    },
  },
};

export default config;
```

I know the waterline code is looking for `registerDataStore` function which is not currently available in the latest version of `sails-mssqlserver` package. Could you please let me know which version of waterline is compatible with sails-mssqlserver?

**Comment by johnabrams7** [comment]
Hey @vsashidh , we're moving all the Waterline cases to Sails (balderdashy/sails) for greater exposure to the community.  The latest [sails-sql](https://www.npmjs.com/package/sails-sql) 0.1.0.1 was released just a few days ago.  Hoping this issue has since been resolved, but feel free to update us if the original issue still exists.  Thanks for all the help!

**Comment by rachaelshaw** [comment]
Going to go ahead and close this one, since it's an issue with a 3rd-party module that doesn't support the current version of Sails, and since there's a workaround available (using sails-sql instead). Feel free to resurrect the conversation if anything else comes up!
