### ISSUE TITLE
.save() on a model with populated associations replaces populated associations with ids

### ISSUE THREAD

**Issue by shvelo** [balderdashy/sails#4648]
**Waterline version**: 0.12.1
**Node version**: 4.4.2
**NPM version**: 3.8.5
**Operating system**: Linux 4.4.5-1-ARCH

<hr/>

Calling `save()` on a model with populated associations (`populateAll()`) replaces all `model` associations with ids and all `collection` associations with empty arrays.  `.save({populate: false})` and  `.save({populate: true})` have same effect.  

``` javascript
BEFORE save()
{ forms: 
   [ { name: 'a',
       creator: '5704c4a042e991123a6cb930',
       createdAt: '2016-04-06T08:11:12.720Z',
       updatedAt: '2016-04-06T08:11:12.720Z',
       id: '5704c4a042e991123a6cb931' } ],
  address: 
   { street: 'Main street',
     description: 'Desc',
     createdAt: '2016-04-06T08:11:12.700Z',
     updatedAt: '2016-04-06T08:11:12.700Z',
     id: '5704c4a042e991123a6cb92f' },
  email: 'foo@bar.com',
  id: '5704c4a042e991123a6cb930' }
AFTER save()
{ forms: [],
  address: '5704c4a042e991123a6cb92f',
  email: 'foo@bar.com',
  id: '5704c4a042e991123a6cb930' }
```

[repo with tests](https://github.com/shvelo/assosiation-waterline)  
[test that reproduces this issue](https://github.com/shvelo/assosiation-waterline/blob/working-associations-on-mongo/test/unit/test/models/User.test.js)

**Comment by raqem** [comment]
Hi @shvelo, @elennaro, and @sylvainlap,
 This is a slightly older issue but my understanding is that any issues with the `patch` label have been fixed. Have any of you used Sails V1? If so have you come across this issue since upgrading? 
 Also we are currently consolidating any open Sails issues into one repo to help keep an eye on things a little more efficiently.    
~Cheers!

**Comment by elennaro** [comment]
Hi, @raqem, sorry I'm not able to test if the issue is fixed now.

**Comment by raqem** [comment]
Hi ya'll @shvelo, @elennaro, and @sylvainlap we are further cleaning up Sails issues by closing older issues that haven't had any movement in some time.
