### ISSUE TITLE
Attributes with an autoIncrement value are forced to type integer, even if autoIncrement is false

### ISSUE THREAD

**Issue by janhapke** [balderdashy/sails#4649]
Background: I'm generating my model definitions automatically, so I am setting the autoIncrement property for every attribute. Of course it is only set to _true_ for the attributes that actually are auto increment columns, for all others it is set to _false_.

The problem now is that all my attributes are internally treated as type integer, which causes all sorts of problems.

I have tracked the problem down and it is caused by waterline always setting the type of an attribute to integer, as soon as the property _autoIncrement_ is present, regardless of wether it is set to true or false. Furthermore, it works correctly if the property _autoIncrement_ is set before the type in the model definition.

This does not work:
`module.exports = {
  attributes: {
    id : { type: 'int', autoIncrement: true },
    title : { type: 'string', autoIncrement: false }
  },
  connection: 'mysql',
  tableName: 'foobar',
  migrate: 'safe'
};
`
while this does:
`module.exports = {
  attributes: {
    id : { type: 'int', autoIncrement: true },
    title : { autoIncrement: false, type: 'string' }
  },
  connection: 'mysql',
  tableName: 'foobar',
  migrate: 'safe'
};
`

**Comment by johnabrams7** [comment]
Hey @janhapke - We're currently moving all the Waterline cases to Sails for Github issues. I see a resolution was marked patched in a newer version of Waterline - we appreciate the help with the PR! Feel free to provide any further updates. Thanks
