### ISSUE TITLE
Key inside a json value is replaced by columnName of another attribute

### ISSUE THREAD

**Issue by Bangsheng** [balderdashy/sails#4650]
I have a model `User` defined as:

```
{
  ...
 phone: {
    type: 'string',
    columnName: 'ph'
  },
  prefer_ship_address: {
    type: 'json',
    columnName: 'ps'
  },
...
}
```

When I try to update prefer_ship_address, I find the key name 'phone' inside the value of the prefer_ship_address is replaced by 'ph'. For example, if I update prefer_ship_address with value

```
{
  name: 'foo',
  address: 'bar',
  phone: '11111111111'
}
```

, then I print input `values` of `update` function in the adapter

```
{
  updatedAt: Mon Feb 22 2016 14:25:32 GMT-0600 (CST),
  ps: 
    {
      name: 'foo',
      address: 'bar',
      ph: '1111111111'
    }
}
```

**Comment by johnabrams7** [comment]
@wulfsolter @Bangsheng @athieriot @particlebanana Hey everyone, we're currently moving all the Waterline cases to Sails for Github issues.  I see this one was potentially resolved with a patch to Waterline at the time. I appreciate the efforts! Feel free to update us if anything remains of the issues. Thanks!

**Comment by johnabrams7** [comment]
This has been published.
