### ISSUE TITLE
"Unique" validation rule does not provide Model in error object

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#4651]
_From @Mitjan11 on February 19, 2016 12:52_

I've built a service that relies on getting the model name where a create/update error occurred to build i18n string names. For example:

If a validation error occurs on the minLength rule in the username attribute of the User model, it will attempt to find an i18n string with the "user.username.minlength", and otherwise display the default error message.

Now it is all working correctly as I am able to fetch the model where the error occurred through err.model on every single validation rule. However, this value seems to be absent in the unique validation rule?

Here's a comparison of the error object of a "required" and a "unique" validation error:

_required_
{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid",**"model":"Page"**,"invalidAttributes":{"title":[{"rule":"required","message":"\"required\" validation rule failed for input: ''"}]}}

_unique_
{"error":"E_VALIDATION","status":400,"summary":"1 attribute is invalid","invalidAttributes":{"title":[{"value":"New page!","rule":"unique","message":"A record with that `title` already exists (`New page!`)."}]}}

I have read in the documentation that the unique rule is different from others due to being a database constraint. Would this be the reason for this inconsistency?

_Copied from original issue: balderdashy/sails#3587_

**Comment by johnabrams7** [comment]
@Mitjan11 @udanpe @particlebanana We've moved this issue to the main Sails issues hub and gave it the label "orm." I see it was possibly still in need of further documentation, feel free to update this post with further info. Thanks for the efforts so far!
