### ISSUE TITLE
notNull fails on Empty Array

### ISSUE THREAD

**Issue by pjacferreira** [balderdashy/sails#4652]
Hi,

I have the following attribute settings in a model:

``` javascript
 attributes: {
...
    roles: {// User Roles List
      type: 'array',
      defaultsTo: []
//      notNull: true // Can't Use Not Null on Array Argument
    },
    suspended: {
      type: 'boolean',
      defaultsTo: true,
      notNull: true
    }
...
}
```

I have a default set to an empty array (which works fine).
But when I add the notNull validation, I get the following error:

```
[Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to User:
 • roles
   • "notNull" validation rule failed for input: []
```

For the 'boolean' the combination works fine.

SAILS VERSION 0.11.4

**Comment by johnabrams7** [comment]
@pjacferreira @irlnathan Hey, we've moved this issue to the main Sails issues hub in effort to migrate all the Waterline issues over here.  I see it was potentially resolved with a patch but feel free to update us if any part of the issue remains.  Thanks for the help!

**Comment by johnabrams7** [comment]
This has been published.
