### ISSUE TITLE
Update node 5 tests

### ISSUE THREAD

**Issue by particlebanana** [balderdashy/sails#4654]
Right now our integration tests does some symlinking voodoo that doesn't work with NPM 3. This needs to be fixed to get the tests passing on node 5. For now I'm removing node 5 from the Travis config.

**Comment by johnabrams7** [comment]
@particlebanana @nickeddy  Hey, we're moving this issue to the main Sails issue hub in efforts to get all the Waterline issues over here.  A resolution appears to have been patched in a newer version of Waterline.  Thanks for taking the time to help out and hope it's working for everyone now. 👍

**Comment by johnabrams7** [comment]
This has been published.
