### ISSUE TITLE
broken buffer for binary data in create nested

### ISSUE THREAD

**Issue by atiertant** [balderdashy/sails#4655]
like https://github.com/balderdashy/waterline/issues/996 buffer are broken in create nested, this could be fixed using: 

```
_.cloneDeep(existingData, function dealWithBuffers(val) {
  if (val instanceof Buffer) {
    return val.slice();
  }
});
```

look at the pr in my fork for more detail: [Offshore-PR#10](https://github.com/Atlantis-Software/offshore/pull/10)

**Comment by johnabrams7** [comment]
@alexescg @atiertant Hey everyone, we're moving all the Waterline issues to the main Sails issues hub. It looks like a resolution was patched in a newer version of Waterline.  I appreciate the help and hope it's working for everyone now. Thanks

**Comment by johnabrams7** [comment]
This has been published.
