### ISSUE TITLE
"notEmpty" validation rule failed for input:0

### ISSUE THREAD

**Issue by chzhuo** [balderdashy/sails#4656]
• profileIndex
   • "notEmpty" validation rule failed for input: 0

below is my 'profileIndex' column:
    profileIndex:{
      type:"integer",
      required:true,
      notEmpty: true
    },

**Comment by johnabrams7** [comment]
@chzhuo @devinivy Hey everyone, we moved this issue to the main Sails issues hub.  A resolution appears to have been patched in a newer version of Waterline.  Thanks for helping out and hope it's working for everyone now!

**Comment by johnabrams7** [comment]
This has been published.
