### ISSUE TITLE
How to chain multiple controller actions to a single path?

### ISSUE THREAD

**Issue by kalmecak** [balderdashy/sails#4657]
I want to know if is possible to chain multiple controller actions actions to a single path like this:

`
 'get /chain': [
        'AlgoController.fn1',
        'AlgoController.fn2'
    ]
`
I'm trying it but when I call **next()** in **fn1** i got this error:

> `next` (as in req,res,next) should never be called in an action function (but in action `algo/fn1`, it was!)  It was called with no arguments.  Please use a method like `res.ok()` or `res.json()` instead.

How can I call next function?

**Comment by raqem** [comment]
Hi @kalmecak,
 We are in the process of moving all open Sails issues into one repo to help make it easier to keep an eye on issues. 
 Have a good day!
