### ISSUE TITLE
Can not write a model method for through(association) model

### ISSUE THREAD

**Issue by elennaro** [balderdashy/sails#4658]
Given an through(association) model with a field where I need to add some model method.

association model **c**:

```
module.exports = {
    attributes: {
        quantity: { type: 'integer' },
        //Relations
        a: { model: 'a', type: 'date', foreignKey: true, columnName: 'a_id' },
        b: { model: 'b', foreignKey: true, columnName: 'b_id' },
    },
    incrementQ: function () {
        //Cool native request goes here
    }
};
```

When I try to access this method I've got an error: **c.incrementQ is not a function**

```
...
//Created the model in before etc. etc.
it('decrement by one', function (done) {
        console.log('Medel method:', c.incrementQ); //undefined
        c.incrementQ({id: 123}, {quantity: -1}).then((res) => { //the error: no such method
            console.log(res.quantity);
            done();
        }).catch(done);
    });
...
```

I've made a [repository](https://github.com/elennaro/assosiation-waterline), and a [question](http://stackoverflow.com/questions/34451963/how-to-add-a-model-class-method-to-throughassociation-model-in-waterline)

**Comment by johnabrams7** [comment]
@TylerBre @particlebanana @devinivy @elennaro - Hey everyone, we've moved this issue to the main Sails hub with an added label "orm." A resolution appears to have been patched in a newer version of Waterline. Feel free to update if it's still unresolved.  Thanks

**Comment by raqem** [comment]
Hi @TylerBre @particlebanana @devinivy @elennaro we are further cleaning up the Sails issues by closing older ones that have been patched with new updates.

**Comment by johnabrams7** [comment]
This has been published.
