### ISSUE TITLE
MongoIds pass integer validation whether you are using mongo or not

### ISSUE THREAD

**Issue by kevinburkeshyp** [balderdashy/sails#4659]
Relevant code in `core/validations.js`

``` javascript
    // If type is integer and the value matches a mongoID let it validate
    if(hasOwnProperty(self.validations[validation], 'type') && self.validations[validation].type === 'integer') {
      if(utils.matchMongoId(value)) return cb();
    }
```

So it seems like if I am using Postgres but I pass something like `"4cdfb11e1f3c000000007822"` as an `integer` value, Waterline will pass it to the database without applying the normal validation.

**Comment by johnabrams7** [comment]
@kevinburke @devinivy Hey, we moved this issue to our main Sails hub with the label "orm."  It appears to have been patched in a newer version of Waterline. Thanks for sharing this info and hope it's working for everyone now.

**Comment by kevinburke** [comment]
Great! Thanks!

**Comment by raqem** [comment]
Hi @kevinburke @devinivy we are further cleaning up the Sails issues by closing old ones and issues that have been patched with newer versions.

**Comment by johnabrams7** [comment]
This has been published.
