### ISSUE TITLE
Query Normalization Test Needed

### ISSUE THREAD

**Issue by particlebanana** [balderdashy/sails#4660]
Appears `undefined` values may be slipping through the normalization pass. 

Ref https://github.com/balderdashy/sails-mongo/pull/318.

Ref https://github.com/balderdashy/waterline/issues/1226

A unit test needs to be added to either confirm or prove that this is not happening.

**Comment by johnabrams7** [comment]
@particlebanana @l1br3 Hey, we moved this Waterline issue to our main Sails issue hub with the label "orm." It looks like this one possibly needs further info and testing. Thanks for the efforts.
