### ISSUE TITLE
Validation error when trying to save a buffer to the database

### ISSUE THREAD

**Issue by mattcodez** [balderdashy/sails#4661]
I'm experiencing this same issue referenced in #792 that was fixed in 0.10.16, but I'm running 0.10.26. My code

```
setProperties: async function({siteTitle = 'Continuum', logo}){
    let cc = await ClientConfig.findOrCreate({}, {siteTitle});
    if (logo){
      //let image = await fs.readFileAsync(logo.fd);
      let image = fs.readFileSync(logo.fd);
      console.log(image);
      cc.logo = image;
    }
    return cc.save();
  }
```

The error

```
Invalid attributes sent to ClientConfig:
 • logo
   • `undefined` should be a binary (instead of "[object Object]", which is a object)
```

The log shows buffer data above the error so that seems to be coming in just fine, not sure what to look at beyond this.

**Comment by johnabrams7** [comment]
@athieriot @AnvarPK @mattcodez @devinivy @tjwebb @particlebanana Hey everyone, we've moved Waterline issues to our main Sails issue hub with the label "orm." This bug appears to have been patched and resolved in an updated version of Waterline. Thanks for contributing time and efforts and hope it's working for everyone now.

**Comment by johnabrams7** [comment]
This has been published.
