### ISSUE TITLE
Error if passing a primary key into find, update, etc

### ISSUE THREAD

**Issue by anasyb** [balderdashy/sails#4662]
I have a array of IDs, for example 3 of them. When calling `User.find(IDs).exec(console.log)` I get the three records.
When I call `User.find().where(IDs).exec(console.log)` I get all records.
I have to do `User.find().where({id: IDs}).exec(console.log)` to get the ones I wanted

Moreover, when calling `User.find().where(IDs[0]).exec(console.log)` I get the correct one.

Very inconsistant, perhaps a bug with calling .where with an array

**Comment by johnabrams7** [comment]
@devinivy @anasyb @particlebanana Hey, we've moving Waterline issues to our main Sails issue hub with the label "orm." It looks like this one was patched and resolved. Thanks for helping resolve this bug and I hope everything is working now. 👍

**Comment by johnabrams7** [comment]
This has been published.
