### ISSUE TITLE
sails.config.i18n link redirects to a 404

### ISSUE THREAD

**Issue by arswaw** [balderdashy/sails#4696]
On [this](https://sailsjs.com/documentation/anatomy/config/i18n.js) page, if you attempt to click on sails.config.i18n, it redirects to a 404 page.

**Comment by raqem** [comment]
Hi @arswaw, 
 Thank you for pointing this out! I changed the link to: 
 https://sailsjs.com/documentation/reference/configuration/sails-config-i-18-n 
 This change will go live next time we deploy. I hope this helps!

**Comment by arswaw** [comment]
This answers my question. Thanks.
