### ISSUE TITLE
Uploading multiple files with different keys on a single request

### ISSUE THREAD

**Issue by sebastialonso** [balderdashy/sails#4914]
I'm implementing the creation of a item that has an avatar and a cover in Sails. I'm using bluebird promises to handle the uploading and posterior creation of an actual model.

```
//....
.then((record) => {
          // Upload avatar
          return new Promise((resolve, reject) => {
            req.file('avatar').upload({}, (err, uploadedFile) => {
              sails.log.debug('avatar state')
              sails.log.debug(uploadedFile)
              if (err) reject(err)
              else {
                resolve({
                  post: record,
                  avatar_path: is.not.empty(uploadedFile) ? uploadedFile[0] : null
                })
              }
            })
          })
        })
        .then((result) => {
          return new Promise((resolve, reject) => {
            sails.log.debug('result')
            sails.log.debug(result)
            if (is.null(result.avatar_path)) {
              resolve(_.assign(result, { avatar: null}))
            } else {
              Image
                .create({ path: result.avatar_path.fd, owner: result.post.id})
                .then((image, err) => {
                  if (err) reject(err)
                  else {
                    resolve(_.assign(result, { avatar: image.id}))
                  }
                })
            }
          })
        })
        .then((result) => {
          return new Promise((resolve, reject) => {
            req.file('cover').upload({}, (err, uploadedFile) => {
              sails.log.debug('cover state')
              sails.log.debug(uploadedFile)
              if (err) reject(err)
              else {
                _cover_path = is.not.empty(uploadedFile) ? uploadedFile[0] : null
                resolve(_.assign(result, {cover_path: _cover_path}))
              }
            })
          })
        })
        //....
```

When my request has both `avatar` and `cover` files I always get the infamous error 

```
Error: EMAXBUFFER: An Upstream (`cover`) timed out before it was plugged into a receiver. It was still unused after waiting 4500ms. You can configure this timeout by changing the `maxTimeToBuffer` option.
```

because `cover` comes after `avatar` (which saves ok). If I only send one file, everything works fine.

As far as my researching is going, this error is unsalvageable. Any ideas on how could I work this out?

**Comment by wimarbueno** [comment]
Hello,
Documentation: https://sailsjs.com/documentation/reference/configuration/sails-config-http

To customize Skipper, first make sure to npm install skipper --save in your app. Next, uncomment the following code in your config/http.js file:

bodyParser: (function _configureBodyParser(){
  var skipper = require('skipper');
  var middlewareFn = skipper({
    strict: true,
    maxTimeToBuffer: 100000
  });
  return middlewareFn;
})(),

![Captura de pantalla de 2019-07-03 23-30-22](https://user-images.githubusercontent.com/1665816/60640014-ace35b00-9dea-11e9-8ad1-a36f62e7c45f.png)

regards

**Comment by iamgkstack** [comment]
how I can handle, if I am not sending any file

**Comment by devMarshall** [comment]
Still getting this issue

**Comment by sachingoel** [comment]
I'm also gettig this issue.
Node Version: 10.x
Sails Version: 1.2.3

**Comment by Nielio** [comment]
@iamgkstack I have a solution!
```javascript
const skipperUpstream = req.file('image');

// skipperUpstream._files is an internal array containing the uploaded files for key `image`
// here i just expecting a single file, or none
const file = skipperUpstream._files[0];

if (!file) {
  // `skipperUpstream.__proto__` is `Upstream`. It provides `noMoreFiles()` to stop receiving files.
  // It also clears all timeouts: https://npmdoc.github.io/node-npmdoc-skipper/build/apidoc.html#apidoc.element.skipper.Upstream.prototype.noMoreFiles
  skipperUpstream.noMoreFiles();
  return;
}

skipperUpstream.upload(/* your stuff */);


```

**Comment by alaaromdhani** [comment]
did any one find a solution for this  i am trying to send two files with different fieldNames 
upload: (req, res) => {

        try {
          res.status(200).send(req._fileparser.upstreams.map(u=>u.fieldName))
        }
        catch (e) {
            res.status(400).send('no file was found in the request')
        }




    }
