### ISSUE TITLE
Where did the wiki documentation go?

### ISSUE THREAD

**Issue by servel333** [balderdashy/sails#4920]
https://github.com/balderdashy/skipper-s3#usage links to https://github.com/balderdashy/skipper#uploading-files-to-s3 but the Wiki appears to have been disabled. Did the documentation move to somewhere else?

**Comment by rachaelshaw** [comment]
See https://sailsjs.com/documentation/concepts/file-uploads and https://sailsjs.com/documentation/concepts/file-uploads/uploading-to-s-3
