### ISSUE TITLE
How to find records based on association attributes in many-to-many relationships

### ISSUE THREAD

**Issue by dinana** [balderdashy/sails#4995]
[As per the example in: http://beta.sailsjs.org/#/documentation/reference/ModelAssociations/Many-to-Many.html ]

There is no documented way of how to search for users (User.find().. ) whose pets are blue. I think this must be added.

**Comment by LouAdrien** [comment]
@mikermcneil would there be any update possible to this example with sails v1?
It seems in v1 the junctor does not allow using `pet_id` anymore.  After checking there would be a `pet_users` field available for query in the junctor. Is it fair to assume that it would return all the associated pets? I can't find any official doc on this topic
