### ISSUE TITLE
Output SQL queries in SailsJS

### ISSUE THREAD

**Issue by zenati** [balderdashy/sails#5043]
Hello, is it possible to show in console SQL queries ?
Thank you.

**Comment by midori-mate** [comment]
This problem appeared to me as well.

Seems that `LOG_QUERIES` didn't work cuz it had been removed from sails-mysql lib at [this commit](https://github.com/balderdashy/sails-mysql/commit/95893be0d0c226be5d5cc99cb242ff998c2b2fd8#diff-a7bcb5fcc46018435e1ce3fa65fcb992L27).

As an alternative I could use `DEBUG=query sails lift` mentioned in #5043
