### ISSUE TITLE
Able to use Notify / Listen?

### ISSUE THREAD

**Issue by ImTheDeveloper** [balderdashy/sails#5054]
Hi,

I've set up a notification system in postgres to notify me of changes to certain tables (inserts, deletes, updates). I wish to listen for these updates within sails.js and right now I am creating a new instance via npm "pg" to connect and subscribe via a listen query in a service.

I'm wondering whether I can negate the need to use npm pg and initialising a new server connection just for this purpose. I see in the node-postgres package there are examples of LISTN/NOTIFY interactions: 

https://github.com/brianc/node-postgres/wiki/Client#notification--object-message

In sails I would love to just run a native query against the db and listen for the output notifications which could then be emitted out to my websocket without the need for a seperate pg instance. E.g.

```
Model.query("listen ally_attack", function (err,results){
if (err) return res.serverError(err);
 //Handle the notifications from the ally_attack postgres notification.
});
```

or in addition to the above being able to tap into `Model.on('notification', function(msg){});`

**Comment by kontolasu12** [comment]
Nice post. Good Quality
Raratravel & Tour. Melayani [Travel Jember](https://raratravel.id) Malang Surabaya/Juanda. Adapun Paket Wisata dan Ziarah Wali 5. Jangan lupa kunjungi kami
