### ISSUE TITLE
Lack of robust json/jsonb support

### ISSUE THREAD

**Issue by jackwanders** [balderdashy/sails#5078]
I am attempting to develop a sails project with `sails-postgresql`. One of my tables will need to contain a column with type `jsonb`, on which I will be creating indexes on nested properties. For example, the following is supported in PostgreSQL 9.4:

``` bash
CREATE TABLE myModels (
    id bigserial PRIMARY KEY,
    name varchar(255) not null,
    data jsonb not null
);
CREATE UNIQUE INDEX name_dataId ON files (name, (data->>'id'));
CREATE INDEX data_id ON files ((data->>'id'));
```

There seems to be a lack of support in `sails-postgresql` for this type of functionality; in particular, 'jsonb' as a valid attribute type in sails model definitions when using a `sails-postgresql` connection, and the ability to query on json property values.

For example, I would expect the following valid PSQL:

``` bash
SELECT * FROM myModels WHERE data->>'id' = 1234;
```

to map to a Waterline call similar to one of the following:

``` javascript
MyModel.find({
  "data->>'id'": 1234 // mimics the query language, data->>'id' being a indexable, searchable value
})
//////////////////
MyModel.find({
  data: {
    id: 1234 // mimics the structure of data within the table, relies of sparse matching
  }
})
```

Last June, https://github.com/balderdashy/sails-postgresql/issues/21 was closed with the statement that, because Waterline didn't support querying within documents, then `sails-postgresql` wouldn't either. Also, the claim that a user should modify their data persistence strategy based on the feature set of the software they're using doesn't necessarily fly with me. PostgreSQL supports these features natively, so to me, it seems to follow that it would be beneficial for a PostgreSQL adapter to support those features as well.

Last August, an issue was opened against Waterline itself (https://github.com/balderdashy/waterline/issues/562), but it was recommended that the issue be brought here.

Another issue was opened more recently (https://github.com/balderdashy/sails-postgresql/issues/187), but was closed due to inactivity. I would be happy to contribute to this end, assuming that other core contributors and maintainers believe this is functionality that is possible within `sails-postgresql`.

**Comment by alxndrsn** [comment]
The waterline repo's backlog refers to this issue in the Pending Proposals section.  If the proposal is still pending, perhaps this issue should be re-opened; if not then should the entry in the Pending Proposals section should be removed?
