### ISSUE TITLE
unexpected EOF on client connection with an open transaction

### ISSUE THREAD

**Issue by arnthorsnaer** [balderdashy/sails#5105]
I bootstrap my sails instance with a big chunk of data. It is located in bootstrap.js and I drop all data on each sails lift. 

I have no problem with lifting sails when using localdiskdb adapter but when I use sails-postgresql I get this error (in pg logs) : "unexpected EOF on client connection with an open transaction". This error is repeated 10 times (which I guess is the number of connections since the default poolsize is 10).

~~My sails is running locally, but I am using a remote postgres server. However I set up a local postgres server as well and it yields the same results so I think I can rule out any firewall / port issues.~~

This only occurs when accessing a remote postgresql server, not when accessing a local postgresql server.

I am not sure how to troubleshoot this further. Does this ring a bell with you?

**Comment by notblank00** [comment]
> My bootstrap script was to blame here. It didn't account for that the recursion would be running much slower on the network. I fixed it and this executes like you would expect, albeit slowly.

how exactly would you *account for* recursion running slowly in a script?
