### ISSUE TITLE
Transforming columnNames back to attribute names

### ISSUE THREAD

**Issue by Alessy** [balderdashy/sails#5262]
**Waterline version**: 0.13.0-rc9
**Node version**: v7.9.0
**NPM version**: 4.2.0
**Operating system**: Windows 10 pro

<hr/>

Warning: After transforming columnNames back to attribute names, a record
in the result has a value with an unexpected data type for property `created`.
The corresponding attribute declares `type: 'string'` but instead
of that, the actual value is:
```
2017-05-17T11:08:24.000Z
```
> You are seeing this warning because there are records in your database that don't
> match up with your models.  This is often the result of a model definition being
> changed without also migrating leftover data.  But it could also be because records
> were added or modified in your database from somewhere outside of Sails/Waterline
> (e.g. phpmyadmin, or another app).  In either case, to make this warning go away,
> you have a few options.  First of all, you could change your model definition so
> that it matches the existing records in your database.  Or you could update/destroy
> the old records in your database; either by hand, or using a migration script.
> 
> (For example, to wipe all data, you might just use `migrate: drop`.)
> 
> More rarely, this warning could mean there is a bug in the adapter itself.  If you
> believe that is the case, then please contact the maintainer of this adapter by opening
> an issue, or visit http://sailsjs.com/support for help.

Here is my model:

`module.exports = {
   attributes: {
    someDate: {
      type: 'string', 
      columnType: 'datetime'
    }
  }
};`

**Comment by diwakar-s-maurya** [comment]
Is there any way to turn off these warnings?

**Comment by ksaitor** [comment]
How to turn off these notifications in prod, while keeping them in staging / develop?

**Comment by ImTheDeveloper** [comment]
Agree the log warnings are so damn annoying

**Comment by Salablefuzzball** [comment]
> Agree the log warnings are so damn annoying

You can set skipRecordVerification to false in query.meta

Took a while to find..
