### ISSUE TITLE
How can I run unit tests with Sails features

### ISSUE THREAD

**Issue by wahyd4** [balderdashy/sails#529]
I have wrote a unit test in my Sails app, and it likes:

var assert = require('assert');

describe('test user model', function () {

```
var userInstance = null;
before(function () {
    User.create({
        name: 'oldName'
    }).done(function (err, user) {
            userInstance = user;
        });
});

it('the user instance should not be null', function () {
    assert.equal(userInstance === null, false);
});
```

});

User is model defined in /api/models/
But got the errors, and the error message is:

  ․․․․․․․․․

  ✖ 1 of 9 tests failed:

  1) test user model "before all" hook:
     ReferenceError: User is not defined
      at Context.<anonymous> (/Users/twer/gitrepo/sohub/test/user.test.js:7:9)
      at Hook.Runnable.run (/Users/twer/gitrepo/sohub/node_modules/mocha/lib/runnable.js:213:32)
      at next (/Users/twer/gitrepo/sohub/node_modules/mocha/lib/runner.js:243:10)
      at Object._onImmediate (/Users/twer/gitrepo/sohub/node_modules/mocha/lib/runner.js:254:5)
      at processImmediate [as _immediateCallback](timers.js:330:15)

npm ERR! weird error 1
npm ERR! not ok code 0

Can you guys tell me how can I run the units with  Models.create() method?
![qq20130707-1 2x](https://f.cloud.github.com/assets/836576/757750/fbe58be8-e6e3-11e2-8cf5-87aac0fdfbc3.png)

**Comment by vishalbiradar** [comment]
@wahyd4 @mikermcneil 
I am also facing the same problem.I want to create some mock data, by using model class and controller methods.
But getting that model is undefined error.

> test user model "before all" hook:
ReferenceError: User is not defined

So How do you solved it. Please help me.

**Comment by msv300** [comment]
How do we write test for this part of the code? `if (err) { return callback(err.message || err); }`
my coverage is not 100% cos of this basic error catching.
