### ISSUE TITLE
Populate with conditions

### ISSUE THREAD

**Issue by Rafkraft** [balderdashy/sails#5315]
Hi, I'm using waterline ORM in my sails.js project, (sails 0.11.4, waterline 0.10.17)

I'm trying do populate linked models with conditions (a simple INNER JOIN).
My models:

```
Comment.js
  attributes  : {
    post: {
      model: 'post',
      columnName: 'post_id'
    }
}

Post.js
  attributes  : {
    comments: {
      collection: 'comment',
      via: 'post'
    },
}
```

So it's a pretty simple has many relation. Simple `populate` work but I'd like to do the following things:
- Get all comments which have a post (INNER JOIN)
- Get all comments which have a post AND this post is active  (INNER JOIN with condition)

I tried with these queries:

```
 Comment.find({}).populate('post').exec(function(err, comments){ console.log(comments) });
// I get a lot of comments with post: undefined , how to get only comments which have a post ?


Comment.find({}).populate('post', { active: true }).exec(function(err, comments){ console.log(comments.length) });
// I get exactly the same result, how to set a condition to my INNER JOIN ? 
```

Thank you very much :)

**Comment by Chibuzo** [comment]
Has this been address in Waterline yet?
