### ISSUE TITLE
Docs: findOrCreate broken with high frequency calls

### ISSUE THREAD

**Issue by anasyb** [balderdashy/sails#5438]
`findOrCreate` is resulting in multiple created records when multiple requests with the same criteria come at the same time.

This only happens when no record matching the criteria exists already... and say 7 requests come in together... they will result in 7 created records. Subsequent requests, no matter how frequent, do not result in more records, obviously since there is already a match that had been persisted to the db. This causes a mess: sometimes you get one record and sometimes you get multiple ones... factor in associations and you can see how messy it gets :(

Seems like the queue isn't checking for uniques.

With this and https://github.com/balderdashy/waterline/issues/877, I think it should be a standard in waterline's tests to do couple of rounds going in the same tick. These two issues were really very tough for me to debug since they only happen sometimes.

**Comment by theScottyJam** [comment]
In the current docs, this warning seems to have disappeared: https://sailsjs.com/documentation/reference/waterline-orm/models/find-or-create, it would be good to add this back in.
