### ISSUE TITLE
Need a way to query associated object's attributes

### ISSUE THREAD

**Issue by gregorypierce** [balderdashy/sails#5472]
If an object has an associated collection, it is not clear how (or even if its possible) to query into that associated object stuff.

Pet has an Owner
Owner has an emailAddress

How do I select all of the Pets whose owner has an `emailAddress == "foo@bar.com"`

While its easy to do 2 queries to accomplish this:
1) Find the owner who has an `emailAddress == "foo@bar.com"` and get that persons `id`
2) Find all Pets who have the `id` from query 1

It seems that there would be a better syntax for this:

``` javascript
Pet.findAll({ "owner.emailAddress" : "foo@bar.com" })
```

Now whether or not this is internally optimized or just syntactic sugar doesn't matter, its much easier to read and write.

Further, if a Pet has a breed how would I select the email addresses of all of the owners whose `Pet.breed == "beagle"`

``` javascript
Owner.findAll({"pet.breed" : "beagle"})
```

**Comment by ChrisSmith5** [comment]
+1
