### ISSUE TITLE
Find/filter by association

### ISSUE THREAD

**Issue by Globegitter** [balderdashy/sails#5474]
I want to query my model, but just find the ones that have a certain association, in an efficient manner.
So if I have a `ResearchProject`, a 1:n relationship to `Funds` I want to only select `ResearchProjects` that have funding.

I think something like `ResearchProject.find({ funds: { 'not': null }).limit(20).exec()` is what I imagined but is not working.

I suppose the way to do that right now is `ResearchProject.find().limit(20).populate('funds').exec(function(err, project){})` and then filter for `project.funds.length > 0`, right?

This works, but then is hard to actually get to return exactly 20 records and for large datasets that also makes it pretty inefficient, to query the db for all records and then filter, rather than filter on the db level in the first place.

I actually don't know how waterline handles associations under the hood, if it creates the relationships in the db, etc. but that would imo be highly useful to have.

**Comment by satishbluone** [comment]
I am also waiting for inner join concept. when will it be come?
