### ISSUE TITLE
Add support for .populate({ select: [] })

### ISSUE THREAD

**Issue by anasyb** [balderdashy/sails#5549]
The `select` is being ignored.. getting back the full records instead of just the titles.

``` javascript
Model.find().populate(assoc.alias, { select: ['title']});
```

Not sure if its only on mongo?

**UPDATE @dmarcelino**: changed this issue into a feature request.

**Comment by abrantes01** [comment]
Hello guys, any news on this issue ?

**Comment by tskweres** [comment]
is this supported?

**Comment by TahaBoulehmi** [comment]
What happened to this feature? Is it supported? It doesn't work on Sails 1.2.3.

**Comment by TahaBoulehmi** [comment]
I made some tests. It works currently only with a population of one-to-many relationship.

I made a pull request to solve the one-to-one relationship issue:
#1613

**Comment by marcoshmendes** [comment]
> I made some tests. It works currently only with a population of one-to-many relationship.
> 
> I made a pull request to solve the one-to-one relationship issue:
> #1613

Some news about it?

**Comment by TahaBoulehmi** [comment]
> > I made some tests. It works currently only with a population of one-to-many relationship.
> > I made a pull request to solve the one-to-one relationship issue:
> > #1613
> 
> Any news about it?

I'm still waiting for anyone of the guys to review the pull request. If you really need to solve the issue immediately just update `lib/waterline/utils/query/forge-stage-two-query.js` like this:

https://github.com/balderdashy/waterline/pull/1613/commits/682f1e3adc244f4ebf95e06e6593e9ff73a4b016

I did it in most of my projects and until now I didn't face any problems with the fix. But as the pull request has not yet been accepted, please make sure to have a backup.

**Comment by MattGarnettWelsh** [comment]
Do the limitations in Waterline currently stand at:

- We can only use **select** sub criteria in populates for one-to-many relationships.
- There is no support with this feature for many-to-many.
- The current version (although written as supported in `lib/waterline/utils/query/forge-stage-two-query.js`) doesn't work as per comments above for one-to-one relationships?
