### ISSUE TITLE
Create query syntax for populate counts

### ISSUE THREAD

**Issue by mydearxym** [balderdashy/sails#5598]
thanks for the work！
now i have a issue with get populate count , let's say i have a many-to-many relationship like User--Pets , i want see a  specific user's pets count without populate all the Pets.
 is there some "count" like method or syntax can directly use on populate?

**Comment by abrantes01** [comment]
Do we have any news on this ?

**Comment by techwebdev** [comment]
Hello guys 
any  update on this ?
