### ISSUE TITLE
Feature Request: Disable "Validate Properties" from whitelist in waterline-schema

### ISSUE THREAD

**Issue by gstreetmedia** [balderdashy/sails#5636]
**Waterline version**:0.13.3
**Node version**:8.9
**NPM version**:5.0
**Operating system**:All

<hr/>
I'm not sure what the purpose is behind white-listing the properties of an attribute, however it would be nice to either remove this or provide a flag for disabling it. 

I would like to be able to add a range of custom attributes, such as a custom toString functions, json schema compatible syntax for enum, custom validations such as isPhone, etc. 

This isn't so much about what properties to use or allow, as it is not throwing an exception if a developer chooses to add custom property. 

Disabling this code 

`_.each(attribute, function parseProperties(propertyValue, propertyName) {
        if (_.indexOf(validProperties, propertyName) < 0) {
          throw flaverr({ name: 'userError' }, Error('The attribute `' + attributeName + '` on the `' + collection.identity + '` model contains invalid properties. The property `' + propertyName + '` isn\'t a recognized property.'));
        }
      });`

Within node_modules/waterline-schema/lib/waterline-schema/schema.js  (line 238) seems to produce no negative side effects. 

Consider the following:

`preferredPhone: {
  type: "string",
  allowNull: true,
  columnName: "preferred_phone",
  columnType: "varchar(32)",
  isMobilePhone: true,
  toString : function(val) {
    return phoneFormatter.format(val, "(NNN) NNN-NNNN");
  }
}`

A model with an attribute formed like this will cause the app to not lift.

**Comment by netrevisanto** [comment]
@gstreetmedia Thanks buddy. I had a cascade strategy on sails.js 0.11 and finally, after your sights, i got it working. 
This should be bundled and exposed as a model attribute configuration on config/models.js, so it can be easily found by other devs and avoids editing of this file:
node_modules/waterline-schema/lib/waterline-schema/schema.js

Thanks!

**Comment by mrtnzagustin** [comment]
@gstreetmedia, @netrevisanto. I am adding [joi validations](https://hapi.dev/module/joi/) to sails. My first approach is adding a joiSchema property to the Models general dictionary, this is ok with sails for example:

```javascript
/**
 * Usuario.js
 *
 * @description :: A model definition represents a database table/collection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */
const Joi = require('@hapi/joi')

module.exports = {

  attributes: {

    id: {
      columnName: 'id',
      columnType: 'bigint(20)',
      type: 'number',
      autoIncrement: true
    },

    //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
    //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
    //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝

    username: {
      type: 'string',
      columnType: 'varchar(50)',
      minLength: 6,
      required: true
    },

    password: {
      type: 'string',
      columnType: 'varchar(255)',
      required: true
    },

    email: {
      type: 'string',
      columnType: 'varchar(255)',
      required: true
    },

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝

    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

  },
  joiSchema: function () {
    return Joi.object({
      username: Joi.string()
        .alphanum()
        .min(3)
        .max(50)
        .required(),
      email: Joi.string()
        .email({ minDomainSegments: 2 })
    })
  },
  customToJSON: function () {
    return _.omit(this, ['password'])
  },
  beforeCreate: function (valuesToSet, proceed) {
    // Hash password
    sails.helpers.passwords.hashPassword(valuesToSet.password).exec((err, hashedPassword) => {
      if (err) { return proceed(err) }
      valuesToSet.password = hashedPassword
      return proceed()
    })
  }
}

```

after that i use Usuario.joiSchema() to access and use that validations. It works, but i want a different approach using this other example:

```javascript
/**
 * Usuario.js
 *
 * @description :: A model definition represents a database table/collection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */
const Joi = require('@hapi/joi')

module.exports = {

  attributes: {

    id: {
      columnName: 'id',
      columnType: 'bigint(20)',
      type: 'number',
      autoIncrement: true
    },

    //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
    //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
    //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝

    username: {
      type: 'string',
      columnType: 'varchar(50)',
      minLength: 6,
      required: true,
      joiSchema: Joi.string()
        .alphanum()
        .min(3)
        .max(50)
        .required()
    },

    password: {
      type: 'string',
      columnType: 'varchar(255)',
      required: true
    },

    email: {
      type: 'string',
      columnType: 'varchar(255)',
      required: true,
      joiSchema: Joi.string()
         .email({ minDomainSegments: 2 })
    },

    telefono: {
      type: 'string',
      columnType: 'varchar(255)',
      required: true
    }

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝

    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

  },
  fullJoiSchema: function () {
    const attributes = Object.keys(this.attributes)
    const fullJoiSchema = {}
    for (const attribute of attributes) {
      if (this.attributes[attribute].joiSchema) {
        fullJoiSchema[attribute] = this.attributes[attribute].joiSchema
      }
    }
    return fullJoiSchema
  },
  customToJSON: function () {
    return _.omit(this, ['password'])
  },
  beforeCreate: function (valuesToSet, proceed) {
    // Hash password
    sails.helpers.passwords.hashPassword(valuesToSet.password).exec((err, hashedPassword) => {
      if (err) { return proceed(err) }
      valuesToSet.password = hashedPassword
      return proceed()
    })
  }
}

```
with this approach i can edit all rules and types per attribute, is there a woraround to make this a thing? is there any attribute name that i can use? @johnabrams7 can you take a look?
