### ISSUE TITLE
AutoUpdatedAt: false does not prevent checks on updatedAt

### ISSUE THREAD

**Issue by joncodo** [balderdashy/sails#5676]
**Waterline version**: 0.11.4
**Node version**: 6.9
**NPM version**: 3.2
**Operating system**: OSX

<hr/>

Waterline throws an error on updatedAt even though I am telling my model not to track updatedAt.

My model:
```
  autoUpdatedAt: false,
  attributes: {
    id: {
      type: 'integer',
      autoIncrement: true,
      primaryKey: true,
      unique: true
    },
```

The error from waterline:

```
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  error: column "updated_at" of relation "organization" does not exist
```

I am working with an existing database that does not have updatedAt in the table. This is described in your docs here: http://sailsjs.com/documentation/concepts/models-and-orm/model-settings#?autocreatedat However, it does not work as expected when set to false.

**Comment by jjorbas** [comment]
**### In 2020...**

**Results**

(node:10818) UnhandledPromiseRejectionWarning: AdapterError: Unexpected error from database adapter: column "updatedAt" of relation "emtm_report_mrs" does not exist

**Model**

module.exports = {
  autoCreateAt: false, 
  autoUpdateAt: false,
...
