### ISSUE TITLE
Implicit filtering(Joins)

### ISSUE THREAD

**Issue by girishla** [balderdashy/sails#5753]
This feature request has been discussed in #597   before and has been closed without any proper resolution.  I wanted to create a fresh one explaining what we are missing out by not having it and hopefully pay the attention it deserves.

I think everyone will agree that Relational databases are still the data powerhouses of a vast majority of the Enterprise world. Even with mongodb,elasticsearch and the dozens of other NoSQL DBs, RDBMS's are here to stay. 
With that in mind, I'd like to point out that one of the most powerful features of enterprise systems built over traditional Relational databases is the ability to apply data visibility security rules applied implicitly through inner joins with 1:M and M:M tables.  This pattern can be seen in almost all the most successful ERP systems such as Oracle EBS, Peoplesoft, SAP and Siebel. 
Transactional data is logically partitioned by its association with a 1:M or M:M table and security slices/views are applied on it such as "My View", "My team View", "My Org View" etc etc. The security slice is nothing but an inner join to an 1:1, 1:M or M: M table. Needless to say, this way of logically partitioning data allows for massively scaling apps in the relational world.
This cannot be achieved with waterline ORM without resolving the issue raised by @RWOverdijk

So can we please please discuss this and take it fwd ?

**Comment by RWOverdijk** [comment]
wat
