### ISSUE TITLE
Need to load/create new collection after waterline.initialize()

### ISSUE THREAD

**Issue by vicneanschi** [balderdashy/sails#5773]
I need a way to declare/load new collections after waterline was initialized.

Here is an example:

``` javascript
var Waterline = require('waterline');
var sailsMemoryAdapter = require('sails-memory');
var waterline = new Waterline();

// Define your collection (aka model)
var userCollection = Waterline.Collection.extend({
    identity: 'user',
    connection: 'default'
});

waterline.loadCollection(userCollection);

var config = {
    adapters: {
        'memory': sailsMemoryAdapter
    },

    connections: {
        default: {
            adapter: 'memory'
        }
    }
};

waterline.initialize(config, function (err, ontology) {
    if (err) {
        return console.error(err);
    }

    // Tease out fully initialized models.
    var User = ontology.collections.user;
}

// here I'd like to define and load dynamically another collection (based on some conditions and context)
var orderCollection = Waterline.Collection.extend({
    identity: 'order',
    connection: 'default'
});

waterline.loadCollection(orderCollection);

// ??? how to initialize new collection ???

```

The workaround I found is to 
1. waterline.teardown(), 
2. waterline.loadCollection(newCollection) 
3. waterline.initialize() again. 
Which is not convenient because I'm loosing all previous references to collections.

**Comment by MattGarnettWelsh** [comment]
@particlebanana @mikermcneil did you guys ever get anywhere with the handling of dynamic attributes/models at runtime?

I have a use case where I'd like to give users the ability to add custom attributes to models therefore making them available for reporting/usage within the application at runtime. I don't even really need to give them the ability to create new models, just extend existing ones.

I've scoured all related articles related to the subject and can sort of see how it could be done but only by programmatically restarting the api - which I would really rather not do as it affects other user's experiences.

Let me know if you made any headway with it as I noticed the feature suggestion was supposedly put in Trello a while back (https://github.com/balderdashy/sails/issues/1160). If this isn't possible still could you perhaps suggest to me a realistic process I could use?

Would really appreciate it.
