### ISSUE TITLE
Instance methods/class methods not working for waterline

### ISSUE THREAD

**Issue by dubcanada** [balderdashy/sails#578]
Hey,

The custom instance and class method's are not working on Models for 0.9-RC. For example adding a 

```
    chicken: function() {
        return this;
    }
```

to the model attributes array, then finding the model `Model.find()` the returned `this` does not have the method `chicken`. `Model.chicken()` also does not work (if I pull it outside of the attributes array).

Gist: https://gist.github.com/dubcanada/a72abb348f7d1ffc81a4

**Comment by yosmelvin** [comment]
I think this is still be an issue in sails version 0.12
anyone with solution ?
