### ISSUE TITLE
Case sensitive `find`

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#6258]
``` javascript
User.find({
  role: 'admin',
  name: { 
    equals: 'Gabe'
    caseSensitive: true
  }
})
```

**Comment by OnbitShashan** [comment]
@albertpeiro did you find a solution for mongodb? I'm stuck on this. I have an existing database that need to query with case-insensitivity

**Comment by vrajasekhar1** [comment]
Hi, is this issue resolved? I want to do a case insensitive search with postgresql, but it does not work. Appreciate any pointers how to get this working.
