### ISSUE TITLE
Feature: implement caching mechanism

### ISSUE THREAD

**Issue by lwansbrough** [balderdashy/sails#6267]
Hey @particlebanana et al, I'm thinking it would be very useful to be able to provide a mechanism for specifying caching methods. Personally I think it would be very useful to have this functionality available within Waterline due to the importance of the way in which a cached object's key is generated. I was considering doing this outside of Waterline - but then I wouldn't have access to which properties were being populated, etc in order to build a corresponding key. Here's what I'm thinking:

Specifying a cache for the query would look something like this:

```
User.findOne(123).populate('roles').cache({
    get: function(key) {
        // call to memcached/redis/etc here
    },
    set: function(key, value) {
        // call to memcached/redis/etc here
    }
}).exec(function(err, user) { console.log(user); }));
```

The key would be a hashed representation of the normalized criteria/joins/options etc and value of course being the model. `remove` and `update` could also be specified for `User.update` and `User.remove` queries.

I will probably end up doing this anyway, but I want to request for comments in case you've got a better solution for this.

Cheers

**Comment by vikas-0** [comment]
> this is now available in [offshore 0.0.4](https://github.com/Atlantis-Software/offshore), documentation could be found [here](https://github.com/Atlantis-Software/offshore-docs/blob/master/queries/query.md#cache)

How to integrated this in sails installation?
