### ISSUE TITLE
support for custom indexes

### ISSUE THREAD

**Issue by wanderer** [balderdashy/sails#6359]
It would be nice to be able to specify custom indexes. so for example `index: "customIndex"`  the string `customIndex` would get passed along to the adapter.

If the index was a bool then the current behavior would hold.

**Comment by zhaoyao91** [comment]
5 years, wow

**Comment by TimofeyBiryukov** [comment]
It's 7 years. This would still be a good feature to add.

**Comment by vinilneves** [comment]
Just short of 11! 🤡
