### ISSUE TITLE
Using Mongoose with Sailsjs

### ISSUE THREAD

**Issue by ktkaushik** [balderdashy/sails#644]
I am looking forward to using Sailsjs with Mongoose. Are there any examples i can refer to or any wiki page that i can reach out to accomplish this ?

**Comment by mikermcneil** [comment]
@mikedevita @ktkaushik super late follow up here, but posting this in case it helps you or anyone finding this issue from search engines: https://github.com/mikermcneil/sails-hook-orm-mongoose
