### ISSUE TITLE
Mysql does not support " NOT LIKE " SQL statements

### ISSUE THREAD

**Issue by cjy37** [balderdashy/sails#6552]
Mysql does not support " NOT LIKE " SQL statements

`select * from users where host NOT LIKE '%abc%';`

[https://github.com/balderdashy/waterline-sequel/issues/98](https://github.com/balderdashy/waterline-sequel/issues/98)

**Comment by johnabrams7** [comment]
Referenced  https://github.com/balderdashy/waterline-sequel/issues/98
