### ISSUE TITLE
Slow due to usage of MySQLs LOWER() on string fields

### ISSUE THREAD

**Issue by wulfsolter** [balderdashy/sails#6575]
To re-open https://github.com/balderdashy/sails-mysql/issues/255

Workaround of "Workaround is to include the attribute wlNext: {caseSensitive: true} into sqlOptions in adapter.js." doesn't seem to be working anymore.

**Comment by johnabrams7** [comment]
Referenced: https://github.com/balderdashy/sails-mysql/pull/304
