### ISSUE TITLE
How could I change /.tmp/public to a different directory

### ISSUE THREAD

**Issue by ghost** [balderdashy/sails#709]
I would like to change the location of my public assets. Where could I configure this?

**Comment by mattblang** [comment]
Does this still work?

**Comment by windmaomao** [comment]
zooshme, thank you very much, you can set this in local.js under config. It's not documented, but works.

**Comment by juanpicado** [comment]
It has to be via either `cli` or `.sailsrc`, via .js doesn't work.
Related #3346 
Also related
http://stackoverflow.com/questions/38015622/sails-js-change-public-folder-to-be-different-than-tmp-public
