### ISSUE TITLE
Feature Request: --coffee option on sails generate

### ISSUE THREAD

**Issue by reecelewellen** [balderdashy/sails#715]
It would be neat to see Coffeescript files populated instead of Javascript on "$ sails generate myModel" if the coffee tag is added 

E.g
"$ sails generate myCoffee --coffee"
results in 

api/models/MyCoffee.coffee 
api/controllers/MyCoffeeController.coffee

**Comment by angeldeejay** [comment]
+1 for sails new projectname --coffee
