### ISSUE TITLE
The documentation page is not responsive

### ISSUE THREAD

**Issue by rohinish404** [balderdashy/sails#7271]
**Node version**: 
**Sails version** _(sails)_: 
**ORM hook version** _(sails-hook-orm)_: 
**Sockets hook version** _(sails-hook-sockets)_: 
**Organics hook version** _(sails-hook-organics)_: 
**Grunt hook version** _(sails-hook-grunt)_: 
**Uploads hook version** _(sails-hook-uploads)_: 
**DB adapter & version** _(e.g. sails-mysql@5.55.5)_: 
**Skipper adapter & version** _(e.g. skipper-s3@5.55.5)_: 
<hr/>
The documentation page is not responsive.
<img width="1435" alt="Screenshot 2023-01-25 at 7 08 23 PM" src="https://user-images.githubusercontent.com/92542124/214578560-d99bc226-def6-46ee-b899-0d129dff1966.png">

**Comment by eashaw** [comment]
Hey @rohinish404, our documentation pages are not responsive. 

If you want to view a more mobile-friendly version of our docs, you can view them directly on GitHub in [this repo](https://github.com/balderdashy/sails/tree/master/docs).

**Comment by DominusKelvin** [comment]
Hey @rohinish404 our documentation pages are now responsive. You can check it out.

Fun fact: I documented the process of making it responsive in this [thread on X](https://x.com/Dominus_Kelvin/status/1743195772815065465?s=20)
