### ISSUE TITLE
Support regexp config instead of `expectIntegerId`

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/sails#734]
For configuring what is considered an 'id' for blueprint routing, `sails.config.controllers.blueprints.expectIntegerId` should probably be a regexp config instead:

e.g. defaulting to:

``` javascript
sails.config.controllers.blueprints.validId:  /([0-9]+)|([0-9|a-f]+)/i
```

**Comment by carlospliego** [comment]
Since expectIntegerId: false is depreciated in 0.10. What can I do to use blueprints with a uuid primary key?
