### ISSUE TITLE
Is there a way for sails.js to select fields in SQL queries?

### ISSUE THREAD

**Issue by bigradish** [balderdashy/sails#780]
I'm new to sails.js. It seems that there is no way for sails.js to make a SQL query for select some fields/columns of a table. The queries seem all "select \* ". Thank you.

**Comment by mgenev** [comment]
@johnlonganecker I'm going to test with mongo, 'value' in this case is boolean?

**Comment by cjonagam** [comment]
```javascript
Model.find({field: 'value'}, {fields: ['id', 'name']})
    .paginate({page: 1}, {limit: 10)
    .exec(function(err, results) {
        if(err) {
            res.badRequest('reason');
        }
        res.jsonx(results);
    });
```

The query above works only if we specify at least one select criteria (in where clause)    for empty condition this is now working,   any idea how to fix this ?

**Comment by sahanDissanayake** [comment]
@mikermcneil @particlebanana @sgress454 Any thoughts on this suggested function to limit the number of fields returned ? :thought_balloon: 
Thanks

**Comment by mllanes** [comment]
Any update about how to do this using promises?

**Comment by JemiloII** [comment]
just for anyone who stumbles upon this, fields no longer works. use select instead.

```js
Model.find({field: 'value'}, {select: ['id', 'name']})
    .paginate({page: 1}, {limit: 10)
    .exec(function(err, results) {
        if(err) {
            res.badRequest('reason');
        }
        res.json(results);
    });
```

**Comment by prasad-1210** [comment]
I'm still not able to get results as expected. 
Test 1:
User.find({},{select: ['id', 'name']}).paginate({page: 1}, {limit: 10}).exec(function(err, data){console.log(data.length,data[0])});

Result:
All records with all keys

Test 2:
User.find({id: '552e5be95c0d53a5703cf315'},{select: ['id', 'name']}).paginate({page: 1}, {limit: 10}).exec(function(err, data){console.log(data.length,data[0])});

Result:
One record matching 'id' with all keys.

I'm using Sails.js 0.11.0 and mongodb.


Any suggestions?

**Comment by erick2014** [comment]
I have tried this approch:
 Model.find({field: 'value'}, {fields: ['id', 'name']})
worked for me, but the query is taking 2,53 seconds to bring the data from remote server, and I only have one record

**Comment by JemiloII** [comment]
Note: You need to have field and select set
`Model.find({field: 'value'}, {select: ['id', 'name']})`
Without both, it just doesn't work.

**Comment by AlexVentura** [comment]
Ho to do something like this but adding the populate option and selecting field from different models?

```javascript
User.find({ belongs_to: user.id }, {fields: ['email', 'permission_level', 'signin_count']})
	.populate('person_id')
		.exec(function (err, results) {
			if(err) {
				res.badRequest('reason');
			}
			res.jsonx(results);
		});
```
I'm using  Sails v0.11.2 and it still working ```javascript User.find({ belongs_to: user.id }, {fields: ['email', 'permission_level', 'signin_count']}) ```

But I need to select fields from both models in a one-to-one relationship.
Any help?

**Comment by shadeven** [comment]
@particlebanana @mikermcneil Does sails custom query support joining multiple tables? 
```javascript
Mode.query('SELECT * FROM user INNER JOIN pet on user.id = pet.user_id WHERE user.id = '1' ', function(err, users) {
    if(err) res.json({ error: err.message }, 400);
    res.json(users);
});
```

**Comment by particlebanana** [comment]
@shadeven yup!

**Comment by dejesus2010** [comment]
Why is the `id` field included in these `select` fields limiter option? I'm using the `select` option to limit the fields returned in the `find` query, but it always returns the `id`  field associated with the documents returned even though this field is not included in the array of fields selected to be returned in the result. I can't seem to return just the single field I want without the `id` field. I am using the `sails-mongo` db adapter. My query is as follows:

```
MyModel.find({where: { 
   fromPerson: userId,
   type: 'follow' } 
}, { select: ['to'] }).exec(function(err, results) {
 console.log(results);
}
```
The results printed are:
```
[
 {
   "to":"56d23af246722103009f4069"
   "id":"56e0f92030d2bff620d29275"
 },
 {
   "to":"56d6adeff6f8a697cbadf966"
   "id":"56e0fa4a30d2bff620d29276"
 },
]
```
Why is the `id` included and is there a way to remove it?

**Comment by irlnathan** [comment]
Howdy @dejesus2010, StackOverflow would be a better platform for this question. If, however, you think this is an issue, please open a new issue. Thanks!

**Comment by dejesus2010** [comment]
@irlnathan I'll try SO. Thanks.
