### ISSUE TITLE
Sails lift with no server.

### ISSUE THREAD

**Issue by campbellanderson** [balderdashy/sails#781]
Feature request here. I would like to be able to lift the sails app using the normal configs, but not have the express server started. 

Usage:
I have other processes that are run as async jobs in a kue and would like to be able to reuse the models logic and configuration from sails to ensure data integrity. 

ie: inside my kue process call User.find(......).done(...... user.color = newColor..... user.save();

I can currently lift a sails instance with a callback and use the models perfectly but that requires the server instance to be started, and considering this is an async queue its not ideal to be starting server instances all over the place.

Ideal solution:
In the overrides passed into the sails.lift method passing a express object of null would override the default and simple checking would avoid starting the express configuration and starting process

**Comment by levity** [comment]
This would also be ideal behavior for the `sails console` command.

**Comment by levity** [comment]
You can lift sails without the server component if you disable the `http`, `sockets`, and `views` hooks. So this is what I just wrote up as a script for a more functional console:

```javascript
#!/usr/bin/env node

var _ = require('lodash');
  sails = require('sails');

(function() {
  // Try to get `rc` dependency
  var rc;
  try {
    rc = require('rc');
  } catch (e0) {
    try {
      rc = require('sails/node_modules/rc');
    } catch (e1) {
      console.error('Could not find dependency: `rc`.');
      console.error('Your `.sailsrc` file(s) will be ignored.');
      console.error('To resolve this, run:');
      console.error('npm install rc --save');
      rc = function () { return {}; };
    }
  }

  // Start server
  sails.lift(_.merge(rc('sails'), {
    log: {
      noShip: true
    },
    hooks: {
      http: false,
      sockets: false,
      views: false
    }
  }), function(err) {

    var repl = require('repl').start('sails> ');

    repl.on('exit', function() {
      process.exit();
    });

    require('promirepl').promirepl(repl);

  });

})();

```

It's pieced together from the app.js in the root of the Sails project and [sails-console.js](https://github.com/balderdashy/sails/blob/master/bin/sails-console.js). I added [promirepl](https://www.npmjs.com/package/promirepl) to make working with promises easier.

**Comment by rishabhmhjn** [comment]
I opened an issue here: https://github.com/balderdashy/sails-hook-sockets/issues/16

The disabling of `sockets`/`http` doesn't seem to be working

**Comment by mrded** [comment]
You can run console like so: `sails console --dontLift`
