### ISSUE TITLE
Document Testing

### ISSUE THREAD

**Issue by sullimander** [balderdashy/sails#797]
I am working on a sails app, and I want to test my custom service, model, and controller methods, but there is no documentation to help me get started. I have figured out things here and there, but its mostly by requiring the model or controller methods directly from my tests.

**Comment by kevinburke** [comment]
Fyi - sails.express.app no longer exists. The (undocumented) value you are now looking for is `sails.hooks.http.app`. If you're looking to enumerate properties on the Sails object, this command can be useful.

```bash
egrep 'sails\.(.*)\b' lib -o | cut -d':' -f 3 | cut -d' ' -f 1 | cut -d '(' -f 1 | sort | uniq -c | sort -k 1
```
