### ISSUE TITLE
Change model adapter during runtime for tests. Waterline or Sails issue?

### ISSUE THREAD

**Issue by TomFreudenberg** [balderdashy/sails#804]
Hi,

howto to change the `default` adapter for model operations during runtime.

Example:

Testsuite should run some model test against _memoryDb_ and some others against _diskDb_.

In lift-up there are multiple configurations like:

``` javascript
    // override adapter and database settings from production
    adapters: {
      'default': 'testMemoryDb',

      testMemoryDb: {
        module   : 'sails-memory'
      },

      testDiskDb: {
        module   : 'sails-disk',
        filePath : '.tmp/sails.test.dat'
      }
```

If I change the value of `'default'` before running tests, models are using memory or disk. But I want to change it during runtime based on tests, like:

``` javascript
describe('Waterline Foo model test:', function () {

  before(function () {
    Foo.adapter = 'testDiskDb'
  })

  describe('Foo model test', function () {
    it ('should create a Foo record', function () {
      Foo.create({
        nickname: "My Name"
      }).done(function () {})
    })
  })

})
```

I tried some different assignments like:

`Foo.adapter = sails.adapters['sails-disk']``

and some others but without having success.

Thanks for some help

Tom

**Comment by rh0dium** [comment]
@particlebanana Would you mind sharing your database.js file?  I'm adapting that for OrientDb
