### ISSUE TITLE
Log levels order

### ISSUE THREAD

**Issue by wolneykien** [balderdashy/sails#811]
Hi,

Shouldn't the log levels be ordered more traditionally with 'info' be less than 'debug' ? While in production, setting the log level to 'debug' seems inappropriate, while by shrinking it to 'warn' you currently is missing important 'info' messages (server startup, socket handshakings, etc…).

**Comment by denishaskin** [comment]
You should really consider fixing this.  The debug/info log level order is different from practically every other framework out there (and really doesn't make sense).

For breaking changes like this, do what the Rails team does: add a deprecation warning and a provide a configuration variable that lets a developer jump to the new behavior early, and also allows someone to stay on the old behavior if necessary once you change the defaults.
