### ISSUE TITLE
Need an example of how to use core middleware in routes.js in documentation?

### ISSUE THREAD

**Issue by marshallswain** [balderdashy/sails#814]
How does one register middleware with app.use as explained in routes.js?

I'd be happy to help with getting this in the documentation if it could be explained to me.

http://stackoverflow.com/questions/18548850/how-to-use-custom-route-middleware-with-sails-js-expressjs

**Comment by juancarloscancela** [comment]
There are quite a number of cases where policies are not enough. Just to give an example, if i need to handle dynamic routes (in example, i want my API to route to the same controller, no matter if path is /v1/bla or //v1//bla or //v1////controller) i have no other choice but modify the custom express middleware. I coudnt find an example of how to create a custom hook (which seems the way to go to do it). In any case, i think providing docs or at least a code snippet would be useful.

**Comment by blah238** [comment]
@juancarloscancela I think you can do that with the `config/routes.js` file, see https://github.com/balderdashy/sails-docs/blob/master/concepts/Routes/RouteTargetSyntax.md

**Comment by juancarloscancela** [comment]
@blah238 I could eventually do that, but defining regex for any case can be actually quite hard, or at least, not trivial. Probably just adding to documentation how to configure a custom express middleware for this cases seems harmless, and could provide users with an alternative without having to use complex regexes.

**Comment by enuggetry** [comment]
"express:" is deprecated  (in sails 0.12.1). use "http:"
```
  http: {
    customMiddleware: function (app) {
      console.log("config of Middleware is called")
      app.use(function (req, res, next) {
        console.log("installed customMiddleware is used")
        next()
      })
    }
  }
```

**Comment by grimace** [comment]
how would I serve static files this way?

**Comment by ScalaSoft** [comment]
You can serv static files this way:
```
var express = require('../node_modules/sails/node_modules/express');

module.exports.express = {
  middleware: {
    custom: true
  },

  customMiddleware: function (app) {
    app.use(express.logger());
    app.use(express.compress());
    app.use('/api/docs',express.static('assets/swagger-ui/dist/'));
  }
};
```
This is my config/express.js file

**Comment by Crusader4Christ** [comment]
How to make it in 0.12? Any of listed isn`t working at all.

**Comment by tomercagan** [comment]
@Crusader4Christ - I believe you can plug additional middleware in config/http.js.
Take a look here:
http://sailsjs.com/documentation/concepts/middleware

**Comment by ggiacomo** [comment]
Hi all, I'm trying to use custom middleware, I've this code

`     myCustomMiddleware: function (req, res, next) {
         console.log("Log myCustomMiddleware");
         return next();
     },`
and added 'myCustomMiddleware' to the 'order' array, but in development mode there's no output for the console log, and can't figure out if middleware is working or not. Tried also to use 'custom:true' inside middleware.
Any idea? Thank you

**Comment by MtDalPizzol** [comment]
Hi, I made a [question related with this on Stackoverflow](https://stackoverflow.com/questions/44951358/sails-js-middleware-for-specific-path). @Crusader4Christ have you figured this out?
The method described by @alvaro-paco isn't working. I think this was the way on older Sails.js versions. In my case, I need to specify the path for the middleware.

**Comment by Crusader4Christ** [comment]
```
const express = require('@sailshq/express');
 middleware: {
    staticDocs:  express.static('assets'),
    order: [
      'startRequestTimer',
      // 'cookieParser',
      // 'session',
      'staticDocs',
```

**Comment by kavuri** [comment]
Has anyone tried to add custom middleware in sails1.0? I need to hook my own middleware for which I need access to the express app handle. Specifically, I need something like:
```
var bodyParser = require('body-parser');
expressApp.use(bodyParser.json(), myMiddleware)
```
How to get access to `expressApp` object from Sails?

**Comment by solovieff** [comment]
same problem with custom middleware (swagger)

**Comment by kdclaw3** [comment]
@kavuri @solovieff If you take a look at the hook express gets mounted on [sails.hooks.http.app](https://github.com/balderdashy/sails/blob/master/lib/hooks/http/initialize.js), here is an example I used to add the web pack dev server [Sails 1.0+ Express App.use, Webpack Dev Server Hook](https://gist.github.com/kdclaw3/6801fb4f57f03e5a861a36950c02b6ac)

**Comment by bilal68** [comment]
> @grimace You can serv static files this way:
> 
> ```
> var express = require('../node_modules/sails/node_modules/express');
> 
> module.exports.express = {
>   middleware: {
>     custom: true
>   },
> 
>   customMiddleware: function (app) {
>     app.use(express.logger());
>     app.use(express.compress());
>     app.use('/api/docs',express.static('assets/swagger-ui/dist/'));
>   }
> };
> ```
> This is my config/express.js file

I have done this but getting this error

"Detected a custom middleware `custom` that does not appear in the
middleware order.  Please add `custom` to `sails.config.http.middleware.order`."
