### ISSUE TITLE
Use MySQL As Session Store?

### ISSUE THREAD

**Issue by JohnPostlethwait** [balderdashy/sails#817]
I have searched all over – is this possible at the moment? 

I found the documentation on Mongo and Redis, but nothing for other adapters... 

If this is not possible, do I have any options for storing sessions at the moment besides switching/adding Mongo/Redis?

**Comment by kevintechie** [comment]
Is there a way to re-use the connection used by the models for the session store? Or is there a way to specify the connection parameters for the session store in the environment config files?

**Comment by tcury** [comment]
@kevintechie You can use it in any env (prod, dev) file. Would be nice use the connections configuration file for that.

**Comment by neonexus** [comment]
For anyone that stumbles upon this, looking to use the same credentials from an already existing connection, where the credentials are only stored in local.js for security (as it should be), try a project hook!

Create a file in api/hooks (call it whatever you like).js, drop in the following code:

```javascript
var MySQLSessionStore = require('express-mysql-session');

module.exports = function setupSessionStore(sails){
    return {
        configure: function(){
            var conn = sails.config.models.connection;

            sails.config.session.store = new MySQLSessionStore({
                host: sails.config.connections[conn].host,
                port: sails.config.connections[conn].port,
                user: sails.config.connections[conn].user,
                password: sails.config.connections[conn].password,
                database: sails.config.connections[conn].database,
                createDatabaseTable: true
            });
        }
    };
};
```

Don't forget to install the package:

```bash
npm install express-mysql-session --save
```

And now you have MySQL session storage.

**Comment by icodeforlove** [comment]
@neonexus That worked great for me, excepted i needed to modify the first line to

```
var session = require('express-session'),
    MySQLSessionStore = require('express-mysql-session')(session);
```

Thanks again.

**Comment by neonexus** [comment]
@icodeforlove Sounds like you probably have automatic session handling disabled, which which make your case a little different.

**Comment by wZVanG** [comment]
The before solutions does not work in Sails V1.0.0-46:
I fixed it with this configuration:

File: **/config/session.js**

```
  ...
  adapter: 'connect-mysql',
  config: {
    user: 'my_dbuser', 
    password: 'my_dbpassword', 
    database: 'my_dbname',
  },
  table: 'sessions',
 ...
```

Do not forget that you must install these packages first:

npm install sails-mysql@beta --save
npm install connect-mysql --save

**Comment by neonexus** [comment]
I had to laugh at myself a little bit, because I stumbled upon this thread, once again, found my original post about the hook to re-use already established credentials, thought to myself "I need to give a thumbs up to the poster, exactly what I needed!", only to realize I posted it -_-. 

Anyway! I've come to make an update to my original post, to work with the new Sails v1 standard of "datastores", instead of "connections". Here is the new hook that just worked for me:

```js
const MySQLSessionStore = require('express-mysql-session');

module.exports = function setupSessionStore(sails){
    return {
        configure: function(){
            const conn = sails.config.models.datastore;

            sails.config.session.store = new MySQLSessionStore({
                host: sails.config.datastores[conn].host,
                port: sails.config.datastores[conn].port,
                user: sails.config.datastores[conn].user,
                password: sails.config.datastores[conn].password,
                database: sails.config.datastores[conn].database,
                createDatabaseTable: true
            });
        }
    };
};
```
Don't forget to install the package:

```
npm install express-mysql-session --save
```
Oh, and keep the default session handling turned on in Sails, otherwise you will have to do what @icodeforlove did.
