### ISSUE TITLE
Ability to add non dynamic parameters in a route

### ISSUE THREAD

**Issue by neolao** [balderdashy/sails#821]
For example:

```
module.exports.routes = {
    "/a": {
        controller: "MyController",
        action: "index",
        parameters: {
            type: "foo"
        }
    },
    "/b": {
        controller: "MyController",
        action: "index",
        parameters: {
            type: "bar"
        }
    }
}
```

**Comment by Aidan-Chey** [comment]
For anyone coming accross this for a solution. This is completely possible now. Like the original request states, add the data to the route's object like so
```
"myRoute" : { 
    controller: "myControler",
    action: "myAction",
    customData: anythingHere
 }
```
Then, in the controller you can access the data from ``req.options``, for example: ``let dataFromRoute = req.options.customData;``

I havn't come accross this personally but i'd make sure the key you are putting your data under dosn't clash with any existing data in the options object.
