### ISSUE TITLE
Sails model unique attribute

### ISSUE THREAD

**Issue by TheFinestArtist** [balderdashy/sails#832]
> EDIT: `unique` is supported-- documentation coming soon

I'm using sails with mongoDB, trying to make "sign in" process. I'm trying to make id attribute and email attribute as a unique value. Is there any validation or comments about this issue? And also is it possible to make pass attribute not showing when I make and api call like ("url/Users/find")? Thanks!

**Comment by IanVS** [comment]
@mikermcneil @particlebanana Is https://github.com/balderdashy/sails/issues/832#issuecomment-33641786 the recommended way to handle unique attribute 500 errors from Mongo?

I'm just learning Sails and want to know the best of handling this situation.  Can't seem to find anything conclusive after days of searching.  Thanks!
