### ISSUE TITLE
Globally disabling cookies?

### ISSUE THREAD

**Issue by geoffreak** [balderdashy/sails#841]
I'm creating an API and I am trying to figure out how to disable cookies in my application. We will be using headers for authentication of our API and have no need for cookies.

I was expecting that not having a session config or setting `module.exports.session = null` would do the trick, but that does not seem to be the case.

**Comment by mattblang** [comment]
@sgress454 Was this ever made configurable?

**Comment by JetFault** [comment]
I would also like to know the same. Right now what I do is remove the cookieParser middleware, to not allow reading, but would be nice to also remove setting. 

Also, do sockets work without cookies, I'm having socket issues right now, but don't know if that's issue as of yet.

**Comment by Clan-Utility** [comment]
+1

**Comment by leomperes** [comment]
You can disable sessions in Sails, that should disable cookies. Add the code below in your `.sailsrc`:

```
{
  ...
  "hooks": {
    "session": false
  }
}
```

Source: http://sailsjs.org/documentation/reference/configuration/sails-config-session#?disabling-sessions
