### ISSUE TITLE
Cannot call method 'defaults' of undefined

### ISSUE THREAD

**Issue by wolneykien** [balderdashy/sails#844]
```
node_modules/sails/lib/configuration/validate.js:231
                    config = _.recursive.defaults(config.express.serverOptions,config.ssl);
                                         ^
TypeError: Cannot call method 'defaults' of undefined
```

Is there really something defined for the `recursive` key in lodash ?

**Comment by khmereshop** [comment]
I got the same error when I try to use https ssl certification. I use keytool to generate the certificate. The keytool is a java command use to generate certification. How do I start up sails lift and pass in the password. If I do, sails lift.  I got error below.

crypto.js:100
      c.context.setKey(options.key);
                ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:100:17)
    at Server (tls.js:1130:28)
    at new Server (https.js:35:14)
    at exports.createServer (https.js:54:10)
    at loadExpress (/opt/careApp/node_modules/sails/lib/hooks/http/initialize.js:52:39)
    at /opt/careApp/node_modules/sails/lib/hooks/http/index.js:191:18
    at /opt/careApp/node_modules/sails/lib/app/private/after.js:91:14
    at /opt/careApp/node_modules/async/lib/async.js:254:17
    at done (/opt/careApp/node_modules/async/lib/async.js:135:19)
    at /opt/careApp/node_modules/async/lib/async.js:32:16
    at /opt/careApp/node_modules/async/lib/async.js:251:21
    at /opt/careApp/node_modules/async/lib/async.js:575:34
    at handlerFn (/opt/careApp/node_modules/sails/lib/app/private/after.js:78:13)
    at /opt/careApp/node_modules/async/lib/async.js:570:21
    at /opt/careApp/node_modules/async/lib/async.js:249:17
    at /opt/careApp/node_modules/async/lib/async.js:125:13
