### ISSUE TITLE
Missing documentation for HTTPS and HTTP redirect!

### ISSUE THREAD

**Issue by boustanihani** [balderdashy/sails#862]
Please could anyone post the steps needed for configuring sails to use HTTPS and also redirect HTTP calls to HTTPS ?? Such important info is sadly still missing on the sails website!

Regards from Berlin
Hani

**Comment by Nishchit14** [comment]
http://jsbot.io/node/http-and-https-handle-with-sailsjs

**Comment by greguz** [comment]
I've created a simple [hook](https://www.npmjs.com/package/sails-hook-httpsredirect) to achieve this.
