### ISSUE TITLE
Background Jobs

### ISSUE THREAD

**Issue by tobinharris** [balderdashy/sails#866]
Nice project, the docs are beautiful.

I'm wanting to run some background jobs, any suggestions for how to integrate this with Sails?

I'm even interested in running separate processes, that have access to the Sails model/service code. Could you recommend a pragmatic approach to this? 

E.g. 
- Where should the code for these separate processes live?
- How to share model code?
- How to enforce single instance of a particular process?

Tobin

**Comment by amingilani** [comment]
I'm sorry to be posting on a closed thread again, but i made a `worker.js` file, any ideas on how to give it access to the `sails` global object?

I have `sails.log` and my models set up pretty tightly, it'd be a waste to write all that configuration again.

If you'd like to earn some good stackoverflow karma / points answer [here](http://stackoverflow.com/questions/31866141/how-do-i-give-my-worker-js-access-to-the-sails-object)

Thank you! I'm really really stuck at this point!

**Comment by robwormald** [comment]
You can use Sails.load() (as opposed to Sails.lift() ) which gives you a set up version of Sails, without firing up the webserver. useful for worker tasks and the like.
