### ISSUE TITLE
Access-Control-Allow-Origin problem using sails.js

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#874]
I use angular.js for client and sails.js for server. Both are on different domains. When accessing api in client I get

> XMLHttpRequest cannot load http://localhost/:1337/card/find?name=foo. Origin >http://my.client is not allowed by Access-Control-Allow-Origin.

In vhost config for client I already set 

```
Header set Access-Control-Allow-Origin "*"
```

But this was not enough, I still get this error. Is sails.js api not configured to accept such requests?

**Comment by cetrobo** [comment]
i have the same problem than you , how u fix it ?
