### ISSUE TITLE
Multiple named adapter connections using the same module

### ISSUE THREAD

**Issue by particlebanana** [balderdashy/sails#939]
When you have multiple adapters named in `config/adapters.js` that use the same module they will all get squashed together into a single object under the module name in sails.adapters.

**config/adapters.js**

``` javascript
module.exports.adapters = {
  "default": "foo",

  foo: {
    module: 'sails-mongo',
    url: 'some connection string'
  },

  bar: {
    module: 'sails-mongo',
    url: 'some connection string'
  }
}
```

Will get built as the following internally:

**sails.adapters**

``` javascript
{
  'sails-mongo': {
    identity: 'sails-mongo'
  }
}
```

**Comment by jeromewir** [comment]
Also getting this issue in sails 0.11 & sails-mongo 10.5.
When I add two adapters with sails-mongo in config/connections.js, the second one is always used.

**Comment by GBGuinan** [comment]
I have the same issue trying to use two sails-mongo adapters in connections.js, can anyone help

**Comment by besarthoxhaj** [comment]
I got the same issue here :( with multiple mongo connections looks like 

```js
// models.js
module.exports.models = {
	connection: "mongoTest",
	migrate: 'safe'  
};
```


```js
// connections.js
mongoProd: {
	adapter: 'sails-mongo',
	host: process.env.MONGO_HOST || 'localhost',
	port: 9999,
	user: process.env.MONGO_USER || null,
	password: process.env.MONGO_PASSWORD || null,
	database: 'foo-prod'
},

mongoTest: {
	adapter: 'sails-mongo',
	schema: 'true',
	url: "mongodb://user:xxxx@kahana.mongohq.com:1234/fooBar",
},
```

For some reason sails tries always to connect to `mongoProd` @particlebanana @mikermcneil 
I love sails guys, and this problem is pretty annoying since we are close to go to production.
Is there at least some work around that?

**Comment by izaakrogan** [comment]
+ 1

**Comment by particlebanana** [comment]
@jeromewir @GBGuinan @besarthoxhaj @izaakrogan hey guys I'm not seeing this. You have your model config setup correctly right? If you are using sails make sure you have the following in `config/models.js`:

```javascript
module.exports.models = {
  migrate: 'safe',
  // The name of the connection to use
  connection: 'mongoTest'
};
```

If you aren't using sails then define the connection name in the model as shown here: https://github.com/balderdashy/waterline/blob/master/example/express/express-example.js#L63-L64 the only way it would use a random connection is if one wasn't defined and it needs a default connection.

**Comment by besarthoxhaj** [comment]
@particlebanana thanks for the fast reply. Unfortunately it still doesn't work. I will try to replicate the problem in a new sails app and see if I make any progress

**Comment by randallmeeker** [comment]
If its a difference between production and development you can put your definitions in config/env as a solution. http://stackoverflow.com/questions/28069677/handling-database-environment-configuration-in-sails-js/28080407#28080407

However, if you need to use both in the same environment, then I'm stumped.

**Comment by particlebanana** [comment]
@besarthoxhaj do you have anything in `config/local.js`? That would override any other connection settings.

**Comment by jeromewir** [comment]
I was using env/development.js & env/production.js with both connections in connections.js and I had the problem with sails.

Thanks to @randallmeeker solution, its works now. I just had to put my different configurations in each files.

Thanks for fast replies !

**Comment by besarthoxhaj** [comment]
@particlebanana @randallmeeker thank you guys! I solved it by creating different files in the env folder.

```
config/
    env/
        production.js
        staging.js
        testing.js
```

Each of them looks something like this:

```js
module.exports = {
	connections : {
		mongoProd: {
			adapter: 'sails-mongo',
			host: process.env.MONGO_HOST || 'localhost',
			port: 27017,
			user: process.env.MONGO_USER || null,
			password: process.env.MONGO_PASSWORD || null,
			database: 'abc-prod'
		}
	},
	models: {
		connection: 'mongoProd',
		migrate: 'safe'
	},
	port: process.env.PORT || 80
};
```

Thats it! Thanks for the help!:)

p.s.
@particlebanana my `config/local.js` looked like this:
```js
module.exports = {
	port: process.env.PORT || 1337,
	environment: process.env.NODE_ENV || 'development'
}
```
I don't know however if this could have been the problem.

**Comment by ccurtisj** [comment]
@besarthoxhaj Thanks, worked for me in 0.11.0. Was driving me nuts deploying to heroku!
