### ISSUE TITLE
Unique property fails in Sails.js

### ISSUE THREAD

**Issue by gzog** [balderdashy/sails#941]
Hello all.

 It's been a couple of days and I haven't gotten a question in stackoverflow about Sails.js(http://stackoverflow.com/questions/19101531/unique-property-fails-in-sails-js).

Can anyone please explain to me why this (the unique property bypass) is happening? Should it behave that way?

**Comment by ajanssens** [comment]
I also have this problem. 

    module.exports = {
      attributes: {
        name: {
          type: 'string',
          required: true,
          unique: true
        }
      }
    };

And can't have an unique name. Dropped my MongoDB database, removed everything... not working.

**Comment by carlospliego** [comment]
Is this being fixed?

**Comment by doomsdayspectrum** [comment]
I'm running into the same issue here (Sails v0.10.5).

The 'sails-mongo' adapter simply doesn't enforce uniqueness of the corresponding attributes, so I had to create a (very ugly) workaround and manually enforce the uniqueness of the attributes. I have found several discussions about this problem - none of which with a proper solution -, so it looks like this is not a new issue.

Is the Sails team working on this problem, or at least aware that it's still happening on the latest version?

**Comment by sochka** [comment]
+1

**Comment by gilesbutler** [comment]
+1 to @doomsdayspectrum - same problem here on Sails v0.11 using MongoDB.

Tried a completely new DB and it's not enforcing uniqueness
````
name: {
      type     : 'string',
      required :  true,
      unique   :  true
},
````

**Comment by ashishmadeti** [comment]
Is this being worked upon?

**Comment by soywod** [comment]
Have the same problem with MySQL : 
<pre>
pseudo: {
     type: 'string',
     unique: true,
     required: true,
     size: 50
},
</pre>

Tried to drop table, changed database, changed login, no way :'(

**Comment by DevTima** [comment]
somebody knows how to enable this attribute?

**Comment by OwaysisApp** [comment]
Is sails dying?? No one answers these questions no moe :(

**Comment by randallmeeker** [comment]
You need to search / post in the repo of your adapter

https://github.com/balderdashy/sails-postgresql
https://github.com/balderdashy/sails-mongo/issues/290
