### ISSUE TITLE
beforeDestroy & afterDestroy

### ISSUE THREAD

**Issue by ifavo** [balderdashy/sails#957]
Hi!

I am trying to make a use of before- and afterDestroy on the models but I am struggling to get the object instance that is being destroyed.

How can I get the current dataset that is being deleted? With the criteria on the beforeDestroy function I could do a database query but for this I am missing the classname.

Thanks!
 Mario

**Comment by mzalazar** [comment]
Strange, this is working fine for me, i'm using 0.10.5
