### ISSUE TITLE
Change default timezone?

### ISSUE THREAD

**Issue by artworkad** [balderdashy/sails#969]
When I create a model object via rest the model has following fields.

```
 "createdAt": "2013-10-09T19:13:43.299Z",
 "updatedAt": "2013-10-09T19:13:43.299Z",
```

Why is this Zulu time? I need GMT+2. Is there a chance to setup this?

**Comment by nicesu** [comment]
hi. I solved the problem， you should setting the MySql options file to change timezone to UTC
in the  config/connections.js
setting at this
```
devMysqlServer: {
    adapter: 'sails-mysql',
    host: '127.0.0.1',
    user: 'root',
    password: '***',
    database: '**',
    timezone: 'utc'
  },
```
