### ISSUE TITLE
Execute raw database query

### ISSUE THREAD

**Issue by Voronchuk** [balderdashy/sails#976]
Is there a way to fetch MySQL driver used by Waterline and execute direct SQL query with it?

Don't wish to initiate new MySQL driver connection by myself.

**Comment by sahanDissanayake** [comment]
@particlebanana  Im also trying to use this but does not work

```javascript
Venue.query('SELECT * FROM venue WHERE LOWER(name) = LOWER('+ userinput +')', function(err, results) {
```

Error

```javascript
{
  "code": "ER_BAD_FIELD_ERROR",
  "errno": 1054,
  "sqlState": "42S22",
  "index": 0
}
```

**Comment by servel333** [comment]
@sahanDissanayake My guess is that the string coming from `userinput` needs to be quoted. Also note that you should sanitize your user input so someone can't do an SQL injection attack.

Try something like this

    userinput = sanatize_user_input_somehow(userinput);
    Venue.query('SELECT * FROM venue WHERE LOWER(name) = LOWER("'+ userinput +'")', function(err, results) { ...
